# Folio content module - generated from the chat-era build, hand-editable.
FOLIO = {'bottom': '<p><span class="lemma">On the shape of a trial.</span> The founding case bequeaths a '
           'scene structure, and troupes should steal it whole: the full court convened; the '
           'accused heard to the end, however vile; a deliberation interval that the players feel; '
           'the dual sentence weighed &mdash; body and Avatar tried separately; and the amendment '
           'of the records as the closing image. A Tradition tribunal run on this template needs '
           'no mechanics it does not already have; the drama is procedural, which is to say the '
           'drama is the procedure.</p>\n'
           '        <p><span class="lemma">On leaving the wound open.</span> The metaplot&rsquo;s '
           'refusal to settle the Betrayer&rsquo;s motive is load-bearing. Settle it &mdash; rule '
           'him monster or martyr in your chronicle&rsquo;s canon &mdash; and the Traditions lose '
           'their founding self-doubt, which is the engine of every argument they have had since. '
           'The wound is not a gap in the lore; it is the lore. NPCs should disagree about 1470 '
           'the way the sources do, and a player who takes a side has taken a side in the '
           'Ascension War&rsquo;s oldest internal front.</p>\n'
           '        <p><span class="lemma">On the seer at your table.</span> Sooner or later a '
           'player character with Time will foresee a betrayal, and the Salonikas precedent will '
           'be sitting in the room. Do not adjudicate it in advance; let the table discover that '
           'the founding already contains their dilemma, unresolved, with the body count attached. '
           'That discovery &mdash; the past arguing back &mdash; is what this whole apparatus is '
           'for.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on trials at the table, and on the '
                'uses of an unhealed wound</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Crimes against all</span> the Traditions are judged by the '
           'Council entire. None is condemned unheard: the accused speaks, and his words are '
           'entered in the record. The sentences, in rising severity: censure; expulsion; death, '
           'which ends a body; and <span class="term">Gilgul</span>, which unmakes an <span '
           'class="term">Avatar</span> &mdash; and Gilgul is pronounced only by the Council '
           'entire, only for crimes against the whole, and never in haste. The name of one so '
           'sentenced is marked in the records wherever it stands. The deed of one does not '
           'attaint his Tradition.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence these rules, '
           'and against whom they were first used: <span class="kw">IT HAPPENED THAT</span> the '
           'Council, being new, blessed nine of its finest and sent them out as one cabal, a '
           'Tradition apiece, to carry the word through a burning world.<sup>a</sup> Their leader '
           'was Heylel Teomim of the Solificati &mdash; alchemist, androgyne, the Twin, union of '
           'opposites made flesh &mdash; and the Council loved him for the emblem he was. Four '
           'years the Cabal did great deeds, and Heylel and Eloine of the Verbena loved, and in '
           'the fourth year she bore twins.</p>\n'
           '        <p>And in the spring of 1470, at Narbonne, Heylel went out from the camp and '
           'sold its place to the Order of Reason.<sup>b</sup> Fall Breeze of the Akashics, '
           'DuMonte of the Hermetics, and Abu Hisham of the Batini died refusing capture; Cygnus '
           'Moro of the Chakravanti died under torture at Brienne; Eloine, Bernadette, and Walking '
           'Hawk were taken. Akrites Salonikas alone escaped, and was first to Horizon with the '
           'word: the Cabal is fallen, and it was Heylel. Months later Salonikas led the rescue '
           'and pulled Brienne down. The twins were never found.</p>\n'
           '        <p>Heylel came to Horizon &mdash; some say taken, some say he walked in '
           '&mdash; and wore white to his trial.<sup>c</sup> The whisper that he had fallen, he '
           'denied; the deed, he did not. He said the Traditions would never be one until the '
           'enemy stood in the door, and that he had opened the door with his own hand, and had '
           'meant no one to die of it. The Council heard him to the end. In November they '
           'pronounced death, and Gilgul; and when the Avatar was unmade they amended the records, '
           'so that wherever his name stands, <span class="term">THOABATH</span> stands after it: '
           'Abomination. Of the nine, the four who lived scattered to silence, service, exile, and '
           'warning; the Solificati fell upon one another, their primus was slain, and the Seat of '
           'Matter stood empty four hundred years.<sup>d</sup> But the seat stood.</p>',
 'chapter': 'Chapter the First &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; the verso of the founding: the '
             'leaf of the Convocation carries the Betrayal on its back &middot; the judgments '
             'follow at folio 3a.',
 'folio': '2B',
 'glossL': '<p><span class="mark">a</span> On the First Cabal, its members and deeds, and the '
           'testaments they left, see the redactor&rsquo;s compilation, The Fragile Path.</p>\n'
           '        <p><span class="mark">b</span> On Narbonne, spring 1470; the deaths of Fall '
           'Breeze, DuMonte, and Abu Hisham; Moro&rsquo;s death at Brienne; and the rescue &mdash; '
           'see the histories of that year.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the trial and the sentence of '
           'November 1470, and the amendment of the records, see the same, and the second '
           'edition&rsquo;s history.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Solificati&rsquo;s fall, '
           'the death of their primus, and the four-hundred-year vacancy of the Seat of Matter, '
           'see the Tradition&rsquo;s own entries &mdash; and folio 3a, where the vacancy becomes '
           'law.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Barabbi: the Traditions&rsquo; word for one '
           'fallen to the Nephandi. The accused denied it at trial, and no source contradicts him. '
           'Whatever he was, he was theirs.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The trial sat at Horizon '
           '&mdash; a court without Sleeper witnesses (folio 533b). Every testimony was Awakened '
           'testimony; what that census is worth is its own question.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> On the refusal of a name, '
           'compare the sage the Talmud will not name, calling him only Acher, &ldquo;the '
           'Other.&rdquo; The Council&rsquo;s mark is the same gesture: keep the memory, refuse '
           'the man.</p>',
 'h1': 'The Betrayal',
 'hagahah': 'The Sahajiya annotators of the testaments maintain that nearly everyone in the First '
            'Cabal was in love with nearly everyone else; the redactor Porthos spends footnote '
            'after footnote wearily denying it. Scholars of the Talmud&rsquo;s own marginalia will '
            'recognize the genre at once.',
 'inner': '<p><span class="lemma">Crimes against all the Traditions.</span> Definitional, and easy '
          'to misread as a measure of enormity. It is a measure of object: the Cabal was the '
          'Council&rsquo;s own instrument, each member a Tradition&rsquo;s pledge to the compact, '
          'and to sell it was to strike the compact itself. A murder, however vile, is one '
          'Tradition&rsquo;s business under folio 2a&rsquo;s rule of subsidiarity; treason against '
          'the league is the business of everyone the league contains. The jurisdiction follows '
          'the victim, and here the victim had nine names.</p>\n'
          '        <p><span class="lemma">Censure; expulsion; death; Gilgul.</span> Read the '
          'ladder as a map of jurisdictions: censure touches standing, expulsion touches '
          'membership, death touches the body, Gilgul the soul &mdash; and each rung requires a '
          'wider bench than the one below. Note too what the aggada&rsquo;s silence implies: the '
          'founding case shows only the top of the ladder, because founding cases are always the '
          'worst cases. Ordinary justice lives on the first two rungs, and a table should not '
          'calibrate its everyday tribunals to the one trial the sources bothered to keep.</p>\n'
          '        <p><span class="lemma">None is condemned unheard.</span> Measure what the rule '
          'cost before admiring it. The Council heard, to the end and entered in the record, the '
          'worst man in its history, dressed in white, explaining that he had spent their dead for '
          'their own good. The rule is priced in exactly that currency, and the founders paid it '
          'in the founding case &mdash; which is why no later court may plead that its criminal is '
          'too vile for the rule. The precedent is the vilest one.</p>\n'
          '        <p><span class="lemma">And his words are entered in the record.</span> Further: '
          'preserved, compiled, and handed down &mdash; the redactor&rsquo;s collection keeps the '
          'traitor&rsquo;s own testament beside his victims&rsquo;. The law of the record outran '
          'mere procedure and became something stranger: the Council&rsquo;s answer to the urge to '
          'erase is to preserve, and to mark. See the sixth ruling of folio 3a.</p>\n'
          '        <p><span class="lemma">Never in haste.</span> Spring to November. The interval '
          'is not delay but an element of the sentence: Gilgul pronounced in the week of Narbonne '
          'would have been grief with a gavel. A court that claims power over Avatars must first '
          'demonstrate power over itself, and the demonstration takes months by design.</p>\n'
          '        <p><span class="lemma">Death, which ends a body; Gilgul, which unmakes an '
          'Avatar.</span> Two sentences because two jurisdictions. Death was owed to the dead of '
          'Narbonne, plain retribution in a single lifetime. Gilgul is the Council claiming '
          'authority over lifetimes &mdash; removing a soul from the wheel entire &mdash; and the '
          'Mishnah accordingly reserves it to the fullest court there is, for the widest crime '
          'there is. No Tradition may unmake an Avatar alone; the founders did not trust even '
          'themselves with that, singly.</p>\n'
          '        <p><span class="lemma">Marked in the records.</span> The cheapest punishment '
          'and the longest: executed forever, and by clerks. Note the mechanism &mdash; the mark '
          'is appended, not substituted. Nothing was unwritten. The name still stands so that the '
          'mark has something to stand after.</p>\n'
          '        <p><span class="lemma">Does not attaint his Tradition.</span> Stated as law; '
          'broken as history within a handful of years, as the Gemara&rsquo;s last lines admit. '
          'What the clause is doing there anyway is argued opposite, and resolved &mdash; if that '
          'is the word &mdash; on folio 3a.</p>',
 'inner_head': 'On the Law<span class="comm-sub">the inner commentary &middot; novellae on the law '
               '&middot; procedure from the precedent</span>',
 'name': 'The Betrayal',
 'outer': '<p><span class="lemma">The Twin.</span> The sources&rsquo; Heylel is an emblem before '
          'he is a man: the androgyne, union of opposites; the name itself means twins; the lover, '
          'the twin children, the two sentences, the double record. An aggada that rhymes this '
          'well should be distrusted as history and trusted as parable &mdash; the compilers were '
          'building a mirror, and mirrors are built to face the reader.</p>\n'
          '        <p><span class="lemma">He said the Traditions would never be one.</span> The '
          'motive problem, and the sources will not close it. His own testament survives in the '
          'redactor&rsquo;s compilation and pleads the greater good; it is also the testimony of a '
          'man explaining his monstrousness with his own mouth, in white, to an audience he had '
          'made into mourners. <span class="voice">Some read</span> a fallen idealist; <span '
          'class="voice">some</span> a monster wearing an idealist&rsquo;s vocabulary; <span '
          'class="voice">some</span> a self-appointed martyr who wrote his own passion play and '
          'cast the Council as executioner. Note who benefits from each reading: the Council '
          'needed a monster, the Solificati needed a madman, and he wanted a martyr. Every source '
          'has a client.</p>\n'
          '        <p><span class="lemma">Salonikas alone escaped.</span> The silent seer. His '
          'Tradition&rsquo;s own accounts say he foresaw the betrayal &mdash; and foresaw also a '
          'farther future in which the leader he might have unmasked ruled the world at the head '
          'of engines, a tyranny only the Council&rsquo;s sentence would forestall. So he said '
          'nothing, and let Narbonne happen, and carried the news of the crime he had watched '
          'approach. Rumor charged him afterward as accomplice; the visions, if real, charge him '
          'with something stranger &mdash; arithmetic. Whether a seer owes his cabal a warning or '
          'the future a silence is precisely the question the Mishnah of folio 3a refuses to '
          'answer, and this page is its evidence file.</p>\n'
          '        <p><span class="lemma">Some say taken, some say he walked in.</span> The '
          'variant is not sloppiness, and do not harmonize it: each entrance is a different man. '
          'Taken, he is a fugitive who lost; walking in, he is the author of the trial itself, '
          'arriving to deliver the final scene of his argument. The recensions preserve both '
          'because the witnesses could not agree on which man they saw &mdash; and neither, '
          'honestly, can the reader.</p>\n'
          '        <p><span class="lemma">Thoabath stands after it.</span> From this line forward, '
          'this commentary obeys the text it comments on: the Betrayer&rsquo;s name does not '
          'appear again on this page. The gesture has a lineage &mdash; the sages kept a '
          'heretic&rsquo;s teachings and refused his name, calling him only the Other &mdash; and '
          'it has a cost the Council accepted with open eyes: one cannot mark a name in every '
          'record without maintaining every record. Contempt this durable is a form of '
          'preservation. The mark says: we will not forget you, and we will never again say only '
          'your name.</p>\n'
          '        <p><span class="lemma">The twins were never found.</span> Every aggada leaves '
          'one door unbolted, and later hands have gone through this one &mdash; later texts claim '
          'the children were made a vessel of their parent&rsquo;s secrets, and that the vessel '
          'can be opened. A table may bolt the door or walk through it; what a table may not do is '
          'pretend the door is not in the story. The unfound child is the oldest hook in the '
          'world, and the compilers left it glinting on purpose.</p>',
 'outer_head': 'On the Story<span class="comm-sub">the outer commentary &middot; novellae on the '
               'aggada &middot; the motive, the seer, and the name</span>',
 'rubric': 'the trial of the Twin',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First: The Nine Seats, continued '
             '&middot; the First Cabal, the Great Betrayal, and the trial &middot; law as Mishnah, '
             'the fall as aggada',
 'title': 'Tractate Aliyah &middot; Folio 2b &mdash; The Betrayal: the trial of the Twin',
 'type': 'daf'}
