# Folio content module - generated from the chat-era build, hand-editable.
FOLIO = {'bottom': '<p><span class="lemma">On the two readings.</span> Sacred geometry or colonial '
           'arithmetic: the line itself migrated from the first reading to the second across its '
           'editions, and a chronicle may sit anywhere on that road &mdash; including astride it, '
           'which is where the best tables sit. Played as geometry, the Council is the '
           'cosmos&rsquo;s own parliament and its wars are crusades. Played as arithmetic, the '
           'Council is a fifteenth-century settlement whose bill is still arriving &mdash; the '
           'unseated crafts organized, and a modern chronicle can meet them. The founding is not '
           'backstory; it is the standing dispute every present-day scene inherits.</p>\n'
           '        <p><span class="lemma">On the tenth chair.</span> The guest seat is the '
           'cheapest playable object on this page: whoever sits in it tonight &mdash; a Disparate '
           'envoy, an Orphan, a technocrat under parley, something worse &mdash; imports the whole '
           'founding argument into the room without a word of exposition. Keep it empty until the '
           'table has earned the question of who deserves it.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Read this folio before a '
           'chronicle&rsquo;s first Council scene, and decide which reading of nine the sitting '
           'councilors themselves believe &mdash; for that, more than any stat, is what they will '
           'rule from. The judgments they cite are collected on folio 3a.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the uses of a founding, and on the '
                'two readings of nine</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The seats are nine,</span> and the table has ten.<sup>d</sup> '
           'Each seat is a Sphere&rsquo;s, and a Tradition holds it: the seat belongs to the art, '
           'the Tradition to the seat, the holder to the Tradition. A seat outlives its holder, '
           'and outlives the Tradition that holds it. The Council speaks for the Traditions in '
           'what concerns them all; a Tradition speaks for its own crafts; and no one compels a '
           '<span class="term">paradigm</span>. Judgment of a mage belongs to her Tradition; '
           'judgment of a Tradition, and of crimes against all, belongs to the Council entire. The '
           'Council convenes at <span class="term">Horizon</span>, which is its own agreement made '
           'into a place. The tenth seat stands for the guest.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence these rules? '
           '<span class="kw">OUR TEACHERS TOLD:</span> In those years the world was '
           'burning.<sup>a</sup> The Order of Reason had raised its White Tower, and what it '
           'called reason it enforced with fire. A witch called Nightshade, last alive of the '
           'massacre at Harrogate, hunted the hunter Wyngarde and ended him; and having buried her '
           'dead, she went looking for something larger than revenge. At Mistridge she sat with '
           'three others &mdash; Valoran, who sang; LaSalle, who wrote; Sh&rsquo;zar, who '
           'saw<sup>b</sup> &mdash; and they agreed to go out and gather everyone. Twice the '
           'gathering met at Mistridge, and the second time the Order came with engines; so the '
           'survivors built a place no engine could reach &mdash; Horizon, a realm agreed into '
           'being &mdash; and called the world&rsquo;s willworkers there.</p>\n'
           '        <p><span class="kw">IT HAPPENED THAT</span> the Grand Convocation sat nine '
           'years, and its first work was not war but names: the gathered crafts had to speak '
           'themselves into existence before any could hold a seat.<sup>c</sup> Some arrived '
           'already knowing who they were and gave no ground; others found each other in the halls '
           'and consented to a common name. And when at last the seats were counted, they were '
           'counted nine, one for each Sphere of the common theory, and a tenth left empty for the '
           'guest. Then the Council blessed nine of its finest and sent them out as one cabal, a '
           'Tradition apiece &mdash; but that is told overleaf.</p>',
 'chapter': 'Chapter the First',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; the tractate opens, as tractates '
             'do, at folio 2 &mdash; the title page keeps the first leaf &middot; continued at '
             'folio 2b.',
 'folio': '2A',
 'glossL': '<p><span class="mark">a</span> On the Grand Convocation, 1457&ndash;1466, and the '
           'groundwork at Mistridge (1439, 1449), see the published histories and Horizon: '
           'Stronghold of Hope.</p>\n'
           '        <p><span class="mark">b</span> On the conveners &mdash; Nightshade of the '
           'Verbena, Valoran of the Chorus, Baldric LaSalle of Hermes, Sh&rsquo;zar the Seer '
           '&mdash; see their entries in the lore of the line.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On &ldquo;speaking themselves into '
           'existence,&rdquo; and on the crafts shouted down and left unseated, see M20&rsquo;s '
           'Lore of the Traditions, which says so in its own voice.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the round table of ten seats, '
           'nine marked with the Spheres, see the Horizon material.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The chamber without Sleepers: within Horizon the '
           'local consensus is the Council&rsquo;s own (see folio 533a on locality), and the '
           'witness census of folio 533b is empty by construction. Every ruling of the Council is '
           'made in the one courtroom where the judges&rsquo; belief is the law of physics.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Forward: the First Cabal and '
           'the trial of the Twin, folio 2b; the judgments derived from both, folio 3a.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The crafts left unseated did '
           'not cease to exist. Their descendants are called Disparates, and their tractate is '
           'wanting.</p>',
 'h1': 'Convocation',
 'hagahah': 'The archive of Horizon is kept inside a reality its keepers agree upon. Whether that '
            'makes it the most reliable record in the world or the least is a question the archive '
            'itself is not situated to answer.',
 'inner': '<p><span class="lemma">The seats are nine.</span> Nine because the common theory counts '
          'nine Spheres; the seat is an office of the art, not a prize of the guild. Everything in '
          'the Mishnah&rsquo;s first clause hangs on this: an office can stand empty, pass to a '
          'stranger, and outlive its holder&rsquo;s disgrace, because it never belonged to the '
          'holder at all. The disputants opposite will tell you what else the count of nine was; '
          'both can be true, and the law only needs this one.</p>\n'
          '        <p><span class="lemma">Speak themselves into existence.</span> Note the order '
          'of events, for the law descends from it: first the naming, nine years of it, and only '
          'then the seating. A Tradition is not a fact the Council discovered but a declaration '
          'the Convocation accepted &mdash; whence the rule that a Tradition speaks for its own '
          'crafts, and the rule that no one compels a paradigm. The Council&rsquo;s founding act '
          'was to take people&rsquo;s word for who they were.</p>\n'
          '        <p><span class="lemma">A seat outlives its holder.</span> In 1466 the clause is '
          'ceremony &mdash; a table four years old drafting for permanence. Within a single '
          'generation it is load-bearing, and it will eventually hold through a vacancy longer '
          'than most empires. Whether the founders wrote from foresight or bravado, the clause '
          'held; the case that proved it is told overleaf, and the law it became is folio '
          '3a&rsquo;s first ruling.</p>\n'
          '        <p><span class="lemma">In what concerns them all.</span> Read the grant '
          'narrowly, as the drafters did: everything not given to the Council is retained by the '
          'Traditions. They are sovereign schools in a defensive league, not provinces of a '
          'government &mdash; the Council commands no chantry, licenses no rote, owns nothing but '
          'the war and the compact. Misread this clause and every Council scene in a chronicle '
          'plays wrong: it is a parliament of ambassadors, and its power is exactly as large as '
          'the next vote agrees it is.</p>\n'
          '        <p><span class="lemma">The table has ten.</span> Hospitality as constitutional '
          'principle. The Council was assembled by four people going out to gather strangers; it '
          'keeps an empty chair to remember that it was made of guests.</p>\n'
          '        <p><span class="lemma">Its own agreement made into a place.</span> Take the '
          'clause literally and note its legal consequence, with the margin: the chamber is a '
          'locality (folio 533a) whose consensus is the judges&rsquo; own, and its witness census '
          '(folio 533b) is empty by construction. The Council legislates from the one place its '
          'rulings are already true. Whether that is the best or the worst seat of judgment is '
          'asked again on folio 3a.</p>\n'
          '        <p><span class="lemma">Judgment of a mage belongs to her Tradition.</span> '
          'Subsidiarity: reserve to the whole only what wounds the whole. The clause reads as '
          'modesty and was written as armor &mdash; nine paradigms cannot share a criminal code, '
          'so each keeps its own, and the Council keeps only the crimes that have nine victims. '
          'The great case arrived within four years of the founding; it is told overleaf, and it '
          'is the reason this clause has a second half.</p>',
 'inner_head': 'On the Law<span class="comm-sub">the inner commentary &middot; novellae on the law '
               '&middot; what the story founds</span>',
 'name': 'Convocation',
 'outer': '<p><span class="lemma">Our teachers told.</span> Told where? The recensions differ, and '
          'honesty requires the accounting: the fullest telling is a compilation of testaments '
          'assembled by the redactor Porthos Fitz-Empress a generation after the events; the '
          'editions of the core text retell it in pr&eacute;cis and do not always agree with the '
          'compilation or with one another. One does not harmonize what the sources left rough. '
          'The roughness is data.</p>\n'
          '        <p><span class="lemma">The world was burning.</span> True, and note what the '
          'frame does: a history that opens with the pyre makes everything after it self-defense. '
          'Every founding aggada is also an apology; read this one knowing whose archive kept '
          'it.</p>\n'
          '        <p><span class="lemma">Counted nine.</span> Here the sources divide, and the '
          'division is the page&rsquo;s real subject. <span class="voice">Some say</span> the '
          'count was given by heaven &mdash; nine Spheres, nine seats, the theory made furniture. '
          '<span class="voice">And some say</span> the count was politics wearing theory&rsquo;s '
          'coat: the latest recension states in its own voice that the loud delegations shouted '
          'down, diminished, and disdained whole gatherings of crafts, and that nine is the number '
          'of those left standing near the table when the shouting ended. The first reading makes '
          'the Council a mirror of the cosmos; the second makes it a settlement &mdash; and the '
          'second is the one the line itself now prints.</p>\n'
          '        <p><span class="lemma">Consented to a common name.</span> Consented is the '
          'aggada&rsquo;s gentlest word and its most disputed. A hundred lineages of the '
          'spirit-roads were folded into a single Speakers&rsquo; chair; the folk-crafts of three '
          'continents were herded behind one witch&rsquo;s banner. A seat can be a home or a '
          'corral, and the sources know it was both: the later authorities of the line say so '
          'plainly, and the crafts that refused the folding walk outside this tractate under '
          'another name. When the Mishnah says a Tradition speaks for its crafts, ask &mdash; as '
          'the margin asks &mdash; which crafts were ever asked.</p>\n'
          '        <p><span class="lemma">A realm agreed into being.</span> Then the archive of '
          'the founding is kept inside an artifact of the founders&rsquo; agreement, and the '
          'manuscript problem squares itself: the library is made of the same stuff as its '
          'contents. <span class="voice">Some say</span> this disqualifies the record. <span '
          'class="voice">Others say</span> it merely makes Horizon&rsquo;s archive the honest case '
          '&mdash; all history is consensus; theirs admits it. On this, see the gloss below the '
          'page, which declines to decide.</p>\n'
          '        <p><span class="lemma">Nine years of names.</span> A difficulty: why should '
          'naming take nine years when the enemy&rsquo;s engines took nine days to reach '
          'Mistridge? <span class="voice">Answer:</span> because the naming was the war. To be '
          'named at Horizon was to have a paradigm acknowledged as real by every other paradigm '
          'present &mdash; a treaty among realities. The Order of Reason offers the world one name '
          'for everything; the Convocation&rsquo;s nine years were the cost of refusing to do the '
          'same, and the tenth chair is the refusal made furniture.</p>',
 'outer_head': 'On the Story<span class="comm-sub">the outer commentary &middot; novellae on the '
               'aggada &middot; sources, recensions, dissents</span>',
 'rubric': 'whence the nine seats?',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First: The Nine Seats &middot; the '
             'tractate opens &middot; law as Mishnah, the founding of the Council of Nine as '
             'aggada, out-of-character commentary throughout',
 'title': 'Tractate Aliyah &middot; Folio 2a &mdash; Convocation: whence the nine seats?',
 'type': 'daf'}
