# Folio content module - generated from the chat-era build, hand-editable.
FOLIO = {'bottom': '<p><span class="lemma">On deriving law from story.</span> Ein lemedin min ha-aggada '
           '&mdash; one does not derive law from aggada &mdash; except, as every student learns by '
           'the second week, when one does. The maxim is not a prohibition but a warning label: '
           'law derived from story imports the story&rsquo;s ambiguities, and this chapter is the '
           'demonstration. Seven rulings came out of the founding, and the seventh came out '
           'unresolved, and the third came out contradicted by its own source. That is not the '
           'method failing; that is the method disclosing its costs, which statutes never do.</p>\n'
           '        <p><span class="lemma">On metaplot as precedent.</span> Whether '
           'Horizon&rsquo;s history binds your chronicle is the table&rsquo;s form of the same '
           'question. Three postures are playable. Canonical: the founding happened as told, and '
           'NPCs cite it as these pages do. Variant-manuscript: the editions disagree, and so may '
           'your world &mdash; treat retcons as recensions and choose your reading, aloud. '
           'Apocryphal: the &ldquo;history&rdquo; is the story the Council needs to have happened, '
           'and somewhere the true minutes of 1466 disagree. All three run; the third is the most '
           'Ascension, since it makes the past one more front in the war over what is real.</p>\n'
           '        <p><span class="lemma">On procedure.</span> When a chronicle&rsquo;s tribunal '
           'convenes, put these folios on the table &mdash; literally. Let the NPC judges cite the '
           'Betrayer&rsquo;s trial as lawyers cite cases, and let the players distinguish their '
           'case from the precedent; distinguishing is the whole pleasure of the form. And when '
           'the verdict is in, write the new case into a folio of your own. A tractate that stops '
           'accreting commentary is not finished. It is dead, and this one intends to be '
           'neither.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on deriving law from story, and '
                'metaplot from canon, and chronicle from both</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">These are judgments</span> derived from the founding and the '
           'fall. <span class="term">i.</span> A seat may stand empty; it may not be abolished. '
           '<span class="term">ii.</span> One who fills an empty seat inherits its precedence and '
           'not its predecessor&rsquo;s disgrace. <span class="term">iii.</span> The deed of one '
           'does not attaint his Tradition; but a Tradition that shelters the deed is party to it. '
           '<span class="term">iv.</span> None is condemned unheard, and the words of the '
           'condemned are preserved. <span class="term">v.</span> Gilgul is pronounced only by the '
           'Council entire, only for crimes against the whole, never in haste. <span '
           'class="term">vi.</span> The name of the condemned is marked wherever it stands; the '
           'records are not otherwise altered. <span class="term">vii.</span> Of the seer who '
           'foresees treachery and keeps silent, the Mishnah does not rule.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the first? As '
           'we learned (folio 2a), the seat belongs to the art; and it happened (folio 2b) that '
           'the Seat of Matter stood empty four hundred years, and stood<sup>a</sup> &mdash; until '
           'the scientists of the ether came and sat in it, and none said the chair had died with '
           'the alchemists. And when the Subtle Ones withdrew, the seat of Correspondence waited a '
           'generation for the Adepts. The law was not written and then obeyed; it was obeyed and '
           'then written.</p>\n'
           '        <p>Whence the second? The Etherites sit in the alchemists&rsquo; chair and no '
           'one calls them Heylels &mdash; though the word survives, and finds other targets. '
           'Whence the third? Against the record, not from it: for the aggada says the Solificati '
           'fell upon one another and went out from the Council within a handful of '
           'years.<sup>b</sup> The Mishnah rules what ought; the aggada records what was; the '
           'dispute stands opposite. Whence the fourth and the sixth? He was heard to the end in '
           'white, and his testament is preserved, and THOABATH is appended wherever his name '
           'stands &mdash; a mark added, nothing erased. Whence the fifth? Spring to '
           'November.</p>\n'
           '        <p>And the seventh stands as the Mishnah left it: open.<sup>c</sup> Salonikas '
           'saw, and was silent, and the arithmetic came out as he had foreseen. The court that '
           'would try him must first say what he could have testified to &mdash; for a vision is '
           'not a witnessing &mdash; and what he owed, and to whom. The Council never tried him. '
           '<span class="kw">TEYKU</span> &mdash; let it stand.</p>',
 'chapter': 'Chapter the First &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; chapter the first concludes; the '
             'tractate resumes deep in the middle, at folio 533, with Paradox &middot; teyku '
             '&mdash; let the seer stand.',
 'folio': '3A',
 'glossL': '<p><span class="mark">a</span> Rulings i&ndash;ii: from folio 2a (the seat as office) '
           'and the histories &mdash; the Seat of Matter vacant from 1470 until the scientists of '
           'the ether sat in it, 1904; the seat of Correspondence vacant from the Subtle '
           'Ones&rsquo; withdrawal until the Adepts of the virtual, in the last century.</p>\n'
           '        <p><span class="mark">b</span> Rulings iii&ndash;vi: from folio 2b &mdash; the '
           'trial, the interval, the mark, the preserved testament.</p>\n'
           '        <p class="drop"><span class="mark">c</span> Ruling vii: from folio 2b, the '
           'silent seer; and see Tractate Aliyah 533b on what a witness is, for a vision is not a '
           'witnessing.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> &ldquo;Heylels&rdquo; survives as a slur &mdash; '
           'flung at the alchemists&rsquo; descendants, never at the Etherites who hold the chair. '
           'The disgrace stayed with the guild and not the seat: ruling ii, enforced by playground '
           'law.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The sibling tractates run on '
           'the same engine: Tractate Masekha&rsquo;s princes cite breaches, Tractate '
           'Acharit&rsquo;s elders cite the Litany&rsquo;s cases. Seder Chashak is a seder of '
           'case law wearing statute&rsquo;s clothes.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Ein lemedin min ha-aggada: '
           '&ldquo;one does not derive law from aggada.&rdquo; For the exception, see below the '
           'page.</p>',
 'h1': 'Judgments',
 'hagahah': 'One does not derive law from aggada &mdash; except when one does. One does not derive '
            'chronicle from metaplot &mdash; except when one does. The exception is the whole of '
            'play.',
 'inner': '<p><span class="lemma">Obeyed and then written.</span> The direction of derivation is '
          'the whole jurisprudence of this tractate: these mishnayot are case law dressed as '
          'statute. That is not a defect to be hidden but the method to be owned &mdash; the '
          'Council&rsquo;s constitution is precedent all the way down, which is the only reason an '
          'aggada is citable in the first place. A court that pretends its statutes fell from '
          'heaven cannot cite a story; a court that knows its statutes are stories can cite '
          'nothing else.</p>\n'
          '        <p><span class="lemma">It may not be abolished.</span> Why forbid what four '
          'centuries of vacancy never tempted? Because abolition would concede that an art can die '
          '&mdash; that Matter&rsquo;s questions had stopped being askable when the alchemists '
          'stopped answering them. The empty chair is a claim about reality, kept in furniture: '
          'the Sphere endures whether or not anyone worthy sits before it. The Council&rsquo;s '
          'cosmology is stored in its carpentry, which is why the Mishnah legislates about chairs '
          'at all.</p>\n'
          '        <p><span class="lemma">Inherits its precedence and not its predecessor&rsquo;s '
          'disgrace.</span> Ruling ii is ruling i doing work: because the seat is an office of the '
          'art (folio 2a), what passes with the seat is the art&rsquo;s standing, and the disgrace '
          '&mdash; being personal &mdash; stays with the persons. The margin notes that even the '
          'schoolyard enforces this, aiming its slur at the guild and never the chair. When an '
          'insult respects a legal distinction, the distinction has won.</p>\n'
          '        <p><span class="lemma">A Tradition that shelters the deed is party to '
          'it.</span> Whence the second clause, when the aggada shows no shelter &mdash; the '
          'Solificati surrendered their own to judgment and fell anyway? From the aggada&rsquo;s '
          'injustice, not its example. The clause is drafted to make their fate unlawful the next '
          'time: it marks the one condition under which a Tradition may be answerable, precisely '
          'so that answering for less &mdash; for mere kinship with the criminal &mdash; is '
          'barred. Law can be derived from a story&rsquo;s wound as well as from its wisdom.</p>\n'
          '        <p><span class="lemma">Hear, preserve, mark, never erase.</span> Rulings iv and '
          'vi are one law seen from two ends: the record rule. The founding court&rsquo;s answer '
          'to the urge for damnatio memoriae was its inversion &mdash; total preservation with a '
          'mark riding on it. It is the cheapest of the sentences and the only one still executing '
          'itself five centuries on, clerk by clerk, copy by copy.</p>\n'
          '        <p><span class="lemma">Never in haste.</span> The interval of ruling v is an '
          'element, not an accident: strike it and the sentence changes species, from judgment to '
          'grief. Any table&rsquo;s tribunal that pronounces Gilgul in the session of the crime '
          'has not abbreviated the precedent; it has overruled it.</p>\n'
          '        <p><span class="lemma">The Mishnah does not rule.</span> A mishnah that rules '
          '&ldquo;we do not rule&rdquo; has still ruled: it binds the lower courts &mdash; the '
          'Traditions singly, and the tables &mdash; against pretending the matter is settled. '
          'Silence, published, is a fence.</p>',
 'inner_head': 'On the Law<span class="comm-sub">the inner commentary &middot; novellae on the law '
               '&middot; the derivations defended</span>',
 'name': 'Judgments',
 'outer': '<p><span class="lemma">The Mishnah rules what ought; the aggada records what '
          'was.</span> Begin with the attainder problem, for it is the honest crack in the page. '
          'Ruling iii says the deed of one does not attaint his Tradition; history says the '
          'Solificati were destroyed by the deed of one &mdash; primus slain, guild scattered, '
          'chair empty four centuries. <span class="voice">Some say</span> the law is hypocrisy '
          'footnoted: the Council writes the rule it broke and calls the breaking weather. <span '
          'class="voice">Some say</span> the law is repentance codified: legislation against '
          'one&rsquo;s own past conduct is what repentance looks like when institutions do it. '
          '<span class="voice">And some note</span> the aggada&rsquo;s suspicious care with agency '
          '&mdash; the Solificati &ldquo;fell upon one another,&rdquo; no Council hand visible. '
          'History written by the acquitted tends to acquit. All three readings are available; '
          'only the first is boring.</p>\n'
          '        <p><span class="lemma">Salonikas saw, and was silent.</span> Now the seventh, '
          'argued in full. <span class="voice">For acquittal:</span> a vision is not knowledge but '
          'weather &mdash; the Sahajiya hold time plural, futures braided, and a seer who reports '
          'one strand as fact bears false witness against the others. To convict his silence is to '
          'convict his paradigm, and the founding&rsquo;s own charter says no one compels a '
          'paradigm (folio 2a). The Council&rsquo;s constitution shields him with its first '
          'principle. <span class="voice">For conviction:</span> he was one of nine. Comrades are '
          'owed warnings, not wagers; he priced their lives against a future only he could audit, '
          'and spent them. The greater good is the Betrayer&rsquo;s own defense &mdash; heard in '
          'white, entered in the record &mdash; and it cannot acquit the seer while condemning the '
          'alchemist without the court admitting it judges outcomes, not deeds.</p>\n'
          '        <p><span class="lemma">What he owed.</span> <span class="voice">The middle '
          'position:</span> he owed disclosure, not certainty &mdash; &ldquo;I have seen a shadow '
          'on our road&rdquo; costs one sentence and betrays no strand. <span class="voice">The '
          'rejoinder:</span> unless saying it changes the seen, and the tyrant at the head of '
          'engines walks through the door the warning opened. The seer&rsquo;s paradox admits no '
          'procedure: every duty to speak is a lever on the thing foreseen. The law wisely '
          'declined to build a court that must first rule on the metaphysics of time; the '
          'Mishnah&rsquo;s silence is not squeamishness but jurisdiction honestly refused.</p>\n'
          '        <p><span class="lemma">The Council never tried him.</span> <span '
          'class="voice">Some say</span> for lack of law &mdash; the gap this Mishnah preserves. '
          '<span class="voice">Some say</span> because every judge, hearing of the machine-god '
          'future, silently ran the same arithmetic and was ashamed to convict a man for a '
          'calculation each of them had just performed. And note the rumor the sources keep '
          'alongside the visions: that he was simply in league. The file holds exculpation, '
          'indictment, and slander in the same folder, unreconciled &mdash; which is what a real '
          'file looks like.</p>\n'
          '        <p><span class="lemma">Teyku.</span> The tractate&rsquo;s oldest question '
          'closes the chapter as it opened the leaf: who counts as a witness, and what does the '
          'witness owe? Folio 533b asked it of Sleepers and lenses; this page asks it of prophets. '
          'That the same question governs Paradox and treason is not a coincidence of drafting. It '
          'is the tractate&rsquo;s thesis: all of Ascension&rsquo;s law is the law of who is '
          'watching.</p>',
 'outer_head': 'On the Story<span class="comm-sub">the outer commentary &middot; novellae on the '
               'aggada &middot; dissents from the derivations</span>',
 'rubric': 'one does not derive law from aggada &mdash;',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First: The Nine Seats, concluded '
             '&middot; seven judgments cited to the aggada of folios 2a&ndash;2b',
 'title': 'Tractate Aliyah &middot; Folio 3a &mdash; Judgments: law derived from the founding and '
          'the fall',
 'type': 'daf'}
