# Folio 3b - The Unseated Answer. The verso the Masoret of 2a promised:
# the founding retold from outside, and the Council's law of outsiders.
FOLIO = {'bottom': '<p><span class="lemma">On quoting the recto.</span> The cheapest way to make this '
           'folio play is to let Council characters cite folio 2a aloud, chapter and verse, at '
           'people who were not at the table when it was written. The law of subsidiarity &mdash; '
           'a Tradition speaks for its own crafts &mdash; is a shield in a councilor&rsquo;s '
           'mouth and a leash in an outsider&rsquo;s ear, and both readings are correct, which '
           'is the scene. Give the Disparate characters their own quotation to answer with: the '
           'minutes their houses kept, in which the same meeting reads as a muster. A chronicle '
           'that lets both citations stand unreconciled has staged the Ascension War&rsquo;s '
           'oldest front without spending a die.</p>\n'
           '        <p><span class="lemma">On the guest chair as a standing scene.</span> The '
           'tenth seat is furniture that asks a question every time it is on camera. Seat a '
           'Disparate envoy in it and the founding argument enters the room wearing a face; '
           'leave it empty through a whole session of Council business and the emptiness '
           'testifies too. The chair needs no mechanics &mdash; it needs a camera angle, and a '
           'Storyteller who lets the players notice who looks at it and who will not.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Before the first crossover '
           'scene, decide two things separately: which telling of 1466 the sitting councilors '
           'believe, and which telling the local crafts believe &mdash; for the two beliefs, '
           'not the events, are what collide on screen. Do not resolve the tellings for the '
           'players, and do not let either side&rsquo;s reading arrive as narration; it should '
           'arrive as dialogue, from characters who have staked their lives on it. The folio '
           'opposite rules what ought; this one records what was heard; the table adjudicates '
           'nightly.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on playing both tellings, and on the '
                'uses of an empty chair</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The unseated are neither member nor enemy.</span> Council law '
           'binds the seated; upon the others it lays courtesy, not command.<sup>a</sup> One who '
           'comes under <span class="term">parley</span> leaves under it, whatever is said '
           'between. The <span class="term">guest seat</span> protects whoever fills it: the '
           'guest speaks without oath, is judged by no bench, and departs unhindered &mdash; '
           'and these protections are the Council&rsquo;s to honor, not the guest&rsquo;s to '
           'earn.<sup>b</sup> No craft is annexed by being named, counted, or thanked; a '
           'Tradition speaks for its own crafts, and for no others.<sup>c</sup> Recruitment '
           'passes through consent: of the mage, and of the house that raised her. Against '
           'the common enemies &mdash; the Fallen, the Mad, the hunters of all the Awakened '
           '&mdash; aid may be asked and given across the line without prejudice: a rescue is '
           'not a recruitment, and a debt of blood is not a treaty. And the Protocols bind '
           'the seated in every dealing with the unseated, whether or not the unseated ever '
           'signed them; a mage&rsquo;s word is her honor in both directions.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The founding is '
           'told overleaf as the sources of the seated tell it. <span class="kw">IT HAPPENED '
           'THAT</span> the same nine years are told otherwise in other houses: that the '
           'summons was a census, and the census a corral; that the naming of Traditions, '
           'which the recto calls the Convocation&rsquo;s first work, was also a fence &mdash; '
           'for whatever the count of nine could not hold, the count called <span '
           'class="term">disparate</span>, which is a word that means the namer has given '
           'up.<sup>d</sup> Some were in the halls and would not stay. Some were never '
           'summoned. Some did not yet exist, and were born already outside. The books of the '
           'seated recorded them scattered and presumed them dying; the houses themselves went '
           'everywhere, quietly, and kept their own minutes. And lately &mdash; the elders of '
           'the Council learning it late and third-hand &mdash; the unseated have taken the '
           'borrowed insult for a flag and made a compact under it. That body, its houses, and '
           'its law are tried at folio 197; this page owes it only the origin. The disputants around this text quarrel over what the second telling is, '
           'and what a seat would mean now.</p>',
 'chapter': 'Chapter the First &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; the verso the Masoret of folio 2a promised '
             '&middot; teyku &mdash; let the seat stand empty or filled.',
 'folio': '3B',
 'glossL': '<p><span class="mark">a</span> On the Disparate crafts entire &mdash; the houses, '
           'their histories, their refusals &mdash; see M20, the setting chapters, folios '
           '196&ndash;223; on their justice among themselves, the Book of Secrets.</p>\n'
           '        <p><span class="mark">b</span> On the Grand Convocation, 1457&ndash;1466, '
           'see the histories cited at folio 2a; this page cites the same events and another '
           'reading.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the modern compact of the '
           'unseated and the houses that keep it, see the M20 Disparates material and the '
           'later volume devoted to the Alliance, Forbidden and Forgotten Orders.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the name &ldquo;Disparate&rdquo; '
           'as the Council&rsquo;s word worn in irony by those it names, see the M20 '
           'Disparates chapter&rsquo;s own account of the naming.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is the debt of folio 2a&rsquo;s '
           'Masoret, paid: the corral reading, given its own page. The recto&rsquo;s tenth '
           'chair &mdash; the refusal made furniture &mdash; is this folio&rsquo;s bench.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> One craft&rsquo;s answer '
           'is already bound: the Wu Lung, old enemies of the Akashic Brotherhood, now walk the Way '
           'they warred against &mdash; folio 148a keeps the gate that question knocks '
           'at.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The compact of the '
           'unseated is tried at folio 197, and the empty chairs the Traditions themselves '
           'left &mdash; the alchemists&rsquo;, the Subtle Ones&rsquo; &mdash; at folio 3a, '
           'rulings i and ii.</p>',
 'h1': 'The Unseated Answer',
 'hagahah': 'Both sides kept minutes of 1466. The Council&rsquo;s are beautifully illuminated. '
            'The crafts&rsquo; are complete.',
 'inner': '<p><span class="lemma">Neither member nor enemy.</span> A third status, and the law '
          'is careful to keep it third. Member would mean the Protocols bind them; enemy would '
          'mean the war does. The unseated get neither the Council&rsquo;s law nor its wrath '
          'by default &mdash; only its courtesy, which costs the Council nothing and is '
          'therefore, the cynics note, reliably paid.</p>\n'
          '        <p><span class="lemma">Courtesy, not command.</span> The practical sense: a '
          'Council tribunal has no jurisdiction over an unseated mage, however grave the '
          'charge. It may complain to her house, refuse her its precincts, or treat with her '
          'as a foreign power treats &mdash; but the bench that judges its own cannot summon '
          'her, and folio 3a&rsquo;s procedures stop at the door of any house that never '
          'signed.</p>\n'
          '        <p><span class="lemma">One who comes under parley.</span> The safe-conduct '
          'is absolute and symmetrical: it protects the envoy who insults the bench, and the '
          'bench&rsquo;s envoy among the crafts. Note the tense &mdash; leaves under it: the '
          'protection is judged at departure, not arrival, so a parley cannot be honored at '
          'the threshold and revoked at the table. The histories keep the names of the '
          'chantries that tried; the names are not good ones now.</p>\n'
          '        <p><span class="lemma">The guest speaks without oath.</span> Whatever is '
          'said from the tenth chair makes no precedent and binds no house &mdash; which is '
          'precisely why things can be said there that no seated councilor could survive '
          'saying. The chair is the Council&rsquo;s pressure valve, and the wiser benches '
          'fill it often for exactly that reason.</p>\n'
          '        <p><span class="lemma">No craft is annexed by being named.</span> The '
          'clause reads like a truism and is the folio&rsquo;s whole fight. Naming is how the '
          'Convocation built the world overleaf &mdash; the crafts spoke themselves into '
          'existence, says the recto. This clause is the recto&rsquo;s own principle turned '
          'to face the other way: if a name only binds those who consent to wear it, then the '
          'count of nine describes the seated and legislates nothing about anyone else. The '
          'disputants opposite take it from here.</p>\n'
          '        <p><span class="lemma">A rescue is not a recruitment.</span> The aid clause '
          'exists because the field does not wait for diplomacy: cabals mixed of seated and '
          'unseated form wherever the Fallen are working, and the law&rsquo;s office is to '
          'keep those alliances from becoming annexations by momentum. Without prejudice '
          'means exactly that &mdash; the rescued craft owes gratitude, not membership, and '
          'the rescuing Tradition may not book the favor as a claim. Debts of blood are '
          'paid in blood&rsquo;s own currency; the recruiter&rsquo;s ledger is a different '
          'book, and the law keeps them apart on purpose.</p>\n'
          '        <p><span class="lemma">Through consent, of the mage and of the '
          'house.</span> Two consents, because two things are being taken: a person from her '
          'people, and a student from the lineage that made her. A Tradition that recruits '
          'past a craft&rsquo;s refusal has, in the crafts&rsquo; books, repeated 1466 at '
          'retail. The seated call the double consent a courtesy; the unseated call it the '
          'minimum; the difference in wording is the relationship.</p>',
 'inner_head': 'On the Law<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the outsider&rsquo;s statuses, clause by clause</span>',
 'name': 'The Unseated Answer',
 'outer': '<p><span class="lemma">Told otherwise in other houses.</span> What is the second '
          'telling? <span class="voice">Some say</span> a recension: the same events in a '
          'sourer light, and the two tellings differ as witnesses differ, not as truths do. '
          'The Mishnah rules what ought; the aggada records what was; and two aggadot may '
          'both record honestly what was, from two ends of the hall. On this reading the '
          'folios face each other as facing pages should, and a reader who wants the '
          'Convocation whole must read across the gutter. <span class="voice">And some '
          'say</span> a rival canon: not a variant of the recto&rsquo;s book but another book, '
          'with its own Mishnah the seated have never read. To harmonize them &mdash; to file '
          'the corral-telling as the founding-telling&rsquo;s footnote &mdash; is a second '
          'conquest, politer than the first. One does not harmonize what the sources left '
          'rough; the roughness is the history.</p>\n'
          '        <p><span class="lemma">What a seat would mean now.</span> Suppose the '
          'compact of the unseated were offered a chair &mdash; the tenth made permanent, or '
          'an eleventh raised. <span class="voice">Some say</span> vindication: the table '
          'finally full is what the honest founders wanted, and refusing it forever makes the '
          'refusal the identity, a house built of spite. <span class="voice">Others say</span> '
          'repetition: a seat is a name, and a name is a leash, and 1466 completed politely is '
          'still 1466 &mdash; the corral does not improve by carpeting. An objection: the '
          'guest chair exists; surely it is the answer standing ready. <span '
          'class="voice">Answer:</span> the guest chair is not an answer; it is the question, '
          'built as furniture &mdash; it keeps the seat&rsquo;s protections and withholds the '
          'seat&rsquo;s name, which is to say it holds the dispute open by design. <span '
          'class="kw">TEYKU</span> &mdash; let it stand, empty or filled.</p>\n'
          '        <p><span class="lemma">A word that means the namer has given up.</span> '
          'The exonym dispute, quietest and longest. <span class="voice">Some say</span> wear '
          'it inside out: the compact&rsquo;s own houses took the insult for a flag precisely '
          'because a borrowed sneer, worn on purpose, mocks the mouth it came from &mdash; '
          'and there is a long and honorable history of exactly this. <span '
          'class="voice">Others say</span> a borrowed insult rots from the handle: name '
          'yourselves in your own tongues or be, forever, a footnote to the namer&rsquo;s '
          'ledger &mdash; and the houses have their own names, every one, older than the '
          'Council&rsquo;s word for their sum. An objection, from the young: then this very '
          'folio repeats the offense, filing a dozen houses under one borrowed word. <span '
          'class="voice">Answer:</span> it does &mdash; and says so, which is all the law '
          'can offer: a name confessed as an exonym is a door, a name enforced as a '
          'definition is the fence, and this page is written from outside the compact too, '
          'and knows it. The first reading has the better joke; the '
          'second the better grammar; and the compact, characteristically, uses both &mdash; '
          'the flag for the border, the true names inside the house.</p>\n'
          '        <p><span class="lemma">Without prejudice.</span> A late difficulty on the '
          'aid clause. <span class="voice">Some say</span> the clause is the corral&rsquo;s '
          'patient cousin: fight beside the seated often enough and the refusal erodes by '
          'friendship &mdash; alliance by attrition, no signature required, and in a '
          'generation the compact is a caucus. <span class="voice">Others say</span> the '
          'fear insults the crafts it means to protect: houses that survived five centuries '
          'of being presumed dead can survive being helped, and a law that forbade common '
          'cause against the Fallen would guard the border by burning the bridge. The '
          'clause stands; the watch on it is the compact&rsquo;s own business; and the '
          'seated, for once, are not asked.</p>',
 'outer_head': 'The Other Minutes<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the telling, the seat, and the name</span>',
 'rubric': 'the founding, heard from outside the hall',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First, concluded: The Nine Seats '
             '&middot; the unseated answer &middot; the founding retold from outside, and the '
             'law of outsiders',
 'title': 'Tractate Aliyah · Folio 3b — The Unseated Answer: the founding, heard from outside',
 'type': 'daf'}
