# Folio 38b - The Fragile Path. Verso of the census: the road after the
# waking, per the wod-llm-wiki awakening page (M20 pp.46-53; Initiates
# of the Art pp.13-23).
FOLIO = {'bottom': '<p><span class="lemma">On pacing the three stages.</span> The Path&rsquo;s '
           'stages are a campaign spine offered free: awareness is the first '
           'season&rsquo;s wonder, conflict is every season after, and resolution '
           'is the ending the table steers toward &mdash; named early, arrived at '
           'late. A chronicle that knows which resolution it is walking toward '
           'plays every conflict differently, and better.</p>\n'
           '        <p><span class="lemma">On the presage season.</span> The '
           'signs that run before a waking &mdash; the premonitions, the telling '
           'dreams, the behavior slipping its mold &mdash; are a gift to any '
           'player introducing a character before her Epiphany: a session or two '
           'of presage lets the table watch the mold crack, and makes the '
           'lightning, when it lands, feel overdue instead of arbitrary.</p>\n'
           '        <p><span class="lemma">On the wild talent scene.</span> If '
           'the waking lashes out, let it lash meaningfully: the panic-working '
           'should touch what the character loves or fears, not merely what the '
           'set contains. The bill for it &mdash; attention, fee, the arriving '
           'runners &mdash; is the first act&rsquo;s engine, and it runs best on '
           'personal fuel.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on spines, presage, and '
                'personal fuel</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The road after the waking has a name,</span> '
           'given by an archmaster of the Hermetic houses: the <span '
           'class="term">Fragile Path</span>, and it runs three stages by '
           'law.<sup>a</sup> First <span class="term">awareness</span>: the '
           'world grows larger, the inner spark becomes a presence, and '
           'teaching begins &mdash; without which the wild talent runs '
           'haywire. Then <span class="term">conflict</span>: rival mages and '
           'the Night-Folk, the mortal agencies, the sheer inertia of the '
           'sleeping world&rsquo;s agreement, and the inward enemies &mdash; '
           'corruption, stagnation, the break inward, chains, and '
           'death.<sup>b</sup> Last <span class="term">resolution</span>: '
           'prosperity, sacrifice, transformation, transcendence &mdash; or at '
           'the worst end Gilgul, the unmaking of the spark itself, of which '
           'a later folio keeps the law.<sup>c</sup> The road is walked with '
           'signs before it and storms at its gate: the presage runs in '
           'dreams and premonitions as the stirring spark nudges the soul '
           'from its mold; the violent waking may briefly wield the '
           'spark&rsquo;s full strength before the door swings shut; and the '
           'elder manuscripts license, rarely, a waking in which the spark '
           'takes the wheel entire for a little while, bounded by its own '
           'depth.<sup>d</sup> So the road&rsquo;s law runs: the waking is a door and the '
           'Path is the house &mdash; three rooms, every walker walks them '
           'in order, and no walker is told which resolution her far '
           'room holds until she stands in it, which the namers counted '
           'a mercy and the named have disputed since.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD one waking, twice. The first telling is hers: '
           'the fire waited because she asked it, the kitchen stood '
           'unburnt, and she walked out knowing the world was negotiable '
           'and gentle. The second telling is her teacher&rsquo;s, who '
           'arrived with the runners an hour later: half the block&rsquo;s '
           'lights dead, a fee assessed that took a season to retire, and '
           'a child on the curb explaining to the firemen, with terrible '
           'patience, that they were welcome. Both tellings are true; '
           'neither contains the other; and she has since given both '
           'herself, on different anniversaries. The disputants around '
           'this text hold whether the Path describes or destines, and '
           'who should win the race to the curb.</p>',
 'chapter': 'Chapter the Second &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the census: the recto keeps the waking, this side keeps '
             'the road.',
 'folio': '38B',
 'glossL': '<p><span class="mark">a</span> On the Fragile Path, named by the '
           'archmaster Porthos, see M20, folios 46&ndash;53; the namer&rsquo;s '
           'own end is told where the Book of Magick&rsquo;s wisdom-from-'
           'madness clause is kept, folio 554a&rsquo;s margins.</p>\n'
           '        <p><span class="mark">b</span> On the three stages and '
           'the conflict roster &mdash; rivals, agencies, inertia, and the '
           'inward enemies &mdash; see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'resolutions, and on Gilgul as the worst of them, see the same '
           'folios; the unmaking&rsquo;s own law is chapter VII&rsquo;s debt, '
           'wanting, and 2b has already presupposed it.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On presage, '
           'wild talent, and the rare waking in which the spark drives '
           '&mdash; bounded by its own rating &mdash; see Initiates of the '
           'Art, folios 13&ndash;23 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The Path&rsquo;s three '
           'stages are the growth cycle 46a states as law &mdash; awareness, '
           'conflict, resolution &mdash; and the two folios should be read '
           'as one teaching at two altitudes: this side the road, that '
           'side the ladder.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'teaching that begins at awareness is 567b&rsquo;s whole law in '
           'its first hour, and the race to the curb is that folio&rsquo;s '
           'lineage question sharpened to minutes; the Masoret routes the '
           'reader both ways.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'inward enemies of the second stage each keep a folio: the '
           'break inward at 554a, the corruption at chapter VII, wanting, '
           'and the stagnation &mdash; subtler than either &mdash; in every '
           'gate this binding has audited since chapter V.</p>',
 'h1': 'The Fragile Path',
 'hagahah': 'The Path is called fragile after the walker, not the road. The '
            'road has never broken once.',
 'inner': '<p><span class="lemma">Named by an archmaster.</span> The '
          'naming&rsquo;s plain sense, kept with its irony intact: the road '
          'was named by one of the mightiest walkers the setting records, '
          'and his own walk ended in a Quiet that leveled a fortress '
          '&mdash; the namer of the Fragile Path is the binding&rsquo;s '
          'standing proof of the name. The tractate does not file this as '
          'tragedy alone: a law named by someone it later broke is a law '
          'whose drafter knew what he was pricing.</p>\n'
          '        <p><span class="lemma">Without which the wild talent '
          'runs haywire.</span> The awareness clause&rsquo;s plain sense: '
          'the first stage&rsquo;s deliverable is a teacher, and the law '
          'says so backward &mdash; naming what happens unmentored. The '
          'new mage&rsquo;s power arrives before her grammar does, and '
          'the interval between them is the most dangerous span of the '
          'whole Path measured per day: the wild talent, the fees, the '
          'attention, all before she can spell the word focus. Every '
          'faction&rsquo;s retrieval doctrine is this clause read as a '
          'deadline.</p>\n'
          '        <p><span class="lemma">The inward enemies.</span> The '
          'conflict clause&rsquo;s plain sense, with the roster&rsquo;s '
          'weighting noted: the outward enemies are listed first and '
          'feared less &mdash; rivals can be outfought, agencies '
          'outwaited &mdash; while the inward ones end more walks than '
          'all the outward together: corruption toward the Fallen, '
          'stagnation on a plateau, the break inward, the chains of '
          'debt and institution, and death, which the list files '
          'almost as an afterthought. The ordering is the '
          'books&rsquo; own pastoral theology: the Path&rsquo;s worst '
          'weather is indoors.</p>\n'
          '        <p><span class="lemma">Or at the worst end, '
          'Gilgul.</span> The resolution clause&rsquo;s plain sense, '
          'held at arm&rsquo;s length on purpose: the road&rsquo;s '
          'endings run from prosperity to transcendence, and beneath '
          'them all one floor &mdash; the spark unmade, the soul '
          'still walking. This folio keeps only the word and its '
          'place in the list; the law of who may impose it, and '
          'whether anyone should hold that power, is chapter '
          'VII&rsquo;s, and the binding has owed that chapter since '
          'its second leaf.</p>\n'
          '        <p><span class="lemma">Bounded by its own '
          'depth.</span> The wild-waking clause&rsquo;s plain sense: '
          'the elder manuscripts permit, rarely, an Epiphany in which '
          'the spark drives &mdash; full potential wielded for hours '
          'by a soul that has not yet earned its first rank &mdash; '
          'and bound it sensibly: the borrowed reach should not '
          'exceed the spark&rsquo;s own rating, and the counsel '
          'restricts the option to sparks of real depth. The clause '
          'is the chapter&rsquo;s one taste of the summit served at '
          'the door, and the manuscripts price it as memory: the '
          'mage spends years earning back a strength she has '
          'already felt, which is either cruelty or the best '
          'motivation the Path ever issued. The manuscripts also bound the option&rsquo;s '
          'availability to sparks of unusual depth, three dots and '
          'upward, so the wheel is only ever taken by souls already '
          'built to survive the driving. The bound is depth, not virtue, which the manuscripts are '
          'careful to say twice.</p>',
 'inner_head': 'On the Road<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; stage by stage, storm by '
               'storm</span>',
 'name': 'The Fragile Path',
 'outer': '<p><span class="lemma">Describes or destines.</span> The '
          'shape dispute. <span class="voice">Some say</span> the Path '
          'describes: three stages is what any life looks like '
          'compressed to a sentence &mdash; learning, struggle, ending '
          '&mdash; and reading destiny into a summary is the oldest '
          'error in hermeneutics; the road is a map drawn after the '
          'walking, by survivors, for tuition. <span '
          'class="voice">Others say</span> in this setting the '
          'distinction collapses on itself: where belief is '
          'load-bearing, a map taught to every apprentice becomes the '
          'territory &mdash; mages walk the three stages because three '
          'stages is what mages are taught a walk looks like, and the '
          'Path is the largest standing working in the setting, cast '
          'by pedagogy, renewed every generation. The first school '
          'answers that this proves too much again; the second answers '
          'that in Mage, proving too much is called the Consensus and '
          'has a folio. The schools agree on the table&rsquo;s use '
          '&mdash; the stages pace a chronicle whether they describe '
          'or destine &mdash; and disagree about whether a Storyteller '
          'who breaks the pattern is subverting a trope or performing '
          'a heresy. The folio, which is itself a map drawn after '
          'walking, declines to testify against its own kind.</p>\n'
          '        <p><span class="lemma">The race to the curb.</span> '
          'The retrieval dispute, pressed from the recto. <span '
          'class="voice">Some say</span> the race is rescue: the '
          'unmentored waking is a danger to its owner first &mdash; the '
          'haywire clause, the fees, the storm of attention &mdash; and '
          'whoever reaches the curb with patience and a blanket has '
          'done the setting&rsquo;s plainest good deed, faction '
          'notwithstanding. <span class="voice">Others say</span> the '
          'blanket has a logo on it: the first hour&rsquo;s kindness '
          'buys the lens-grinding rights of 567b, every faction knows '
          'it, and the race is a scramble for unclaimed souls '
          'conducted at the exact moment the soul cannot judge its '
          'suitors. Rescue and recruitment arrive in the same car, and '
          'the child on the curb cannot tell them apart because, in '
          'the rescuer&rsquo;s own heart, they are not apart. The '
          'schools converge on the one reform both scriptures imply '
          'and neither faction practices: that the rescued be told, '
          'early and plainly, that other houses exist. The folio '
          'files the reform under wanting, where the setting keeps '
          'its conscience. One practical clause survives both schools, '
          'and the counsel above enshrines it: whoever wins the race, '
          'the first hour&rsquo;s duty is identical &mdash; safety, '
          'quiet, and the fees contained &mdash; and a chronicle can '
          'stage the whole dispute inside that shared hour without '
          'ever ruling on it. And the schools jointly note the reform&rsquo;s '
          'one working precedent: the rare houses that pool their '
          'retrieval &mdash; rivals splitting the watch by rota, the '
          'woken told plainly who else exists &mdash; lose recruits and '
          'keep them better, which either proves the reform or '
          'explains its rarity, depending on the reader&rsquo;s '
          'faction. <span class="kw">TEYKU</span> &mdash; the '
          'firemen, at least, were welcome.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the map, and the blanket</span>',
 'rubric': 'the road after the waking',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening, '
             'continued &middot; of the fragile path &middot; the road as law',
 'title': 'Tractate Aliyah · Folio 38b — The Fragile Path: the road after the waking',
 'type': 'daf'}
