# Folio 38a - Of Gods and Men. Chapter II opens: the census of souls and
# the Awakening, per the wod-llm-wiki awakening page (M20 p.40; Initiates
# of the Art pp.13-23).
FOLIO = {'bottom': '<p><span class="lemma">On session one.</span> The Awakening is the best '
           'first session the line owns and the books quietly agree: run it live '
           'rather than filing it in backstory where its heat cannot reach the '
           'table. A prelude that ends at the Epiphany gives every later folio a '
           'root the player felt &mdash; and gives the Storyteller the retrieval '
           'scene free, since somebody is already on their way.</p>\n'
           '        <p><span class="lemma">On the bystanders of the '
           'census.</span> Keep the Sleepwalkers close: the half-roused are the '
           'chronicle&rsquo;s connective tissue &mdash; the aunt who reads cards '
           'truly, the lab tech who never asks &mdash; and they price nothing at '
           'the court while seeing almost everything. A cast rich in '
           'Sleepwalkers keeps the hidden world neighborly instead of '
           'quarantined.</p>\n'
           '        <p><span class="lemma">On the trauma clause.</span> The '
           'books tie most Awakenings to crisis survived, and the counsel is '
           '384b&rsquo;s: agree the crisis&rsquo;s content with the player, not '
           'for them. An Epiphany built from a player&rsquo;s chosen material '
           'lands harder and safer than one assigned, and the fourfold embrace '
           'deserves to land.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on preludes, neighbors, '
                'and chosen fire</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The census of souls runs three names.</span> The '
           '<span class="term">Sleeper</span>, whose eyes are closed to the '
           'larger world, and whose closed eyes are the world&rsquo;s ballast. '
           'The <span class="term">Sleepwalker</span>, half-roused &mdash; the '
           'hedge-worker, the psychic, the mad poet and the saint &mdash; who '
           'senses the shapes of the hidden without waking to it, and whose '
           'sharpened awareness of the world&rsquo;s edges often runs before a '
           'waking.<sup>a</sup> And the <span class="term">Awakened</span>, in '
           'whom the inner spark has stirred: the mage. The Night-Folk the '
           'census files apart &mdash; mighty, and stuck halfway in their own '
           'nightmares.<sup>b</sup> The Awakening itself is law in three '
           'clauses. It arrives as <span class="term">Epiphany</span>: the '
           'lightning in which the sleeping world bursts into focus and the '
           'woken sees, feels, grasps, and at last becomes the art &mdash; a '
           'fourfold embrace.<sup>c</sup> It cannot be granted, only survived: '
           'no formula wakes a soul &mdash; had one been found, the War would '
           'have ended &mdash; and most wakings ride the heels of a crisis met '
           'and overcome, the process mattering more than the blow. And it is '
           'attended: every faction runs retrieval for the newly woken, to '
           'recruit, convert, or end them, for a fresh Epiphany is loud and '
           'the world listens. So the census&rsquo;s law runs: three names, '
           'one gradient, a cliff at its end &mdash; and past the cliff, '
           'this whole binding.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear four wakings. A scholar followed a proof past its last '
           'step and found the step held her weight, and she stood on air and '
           'understood. A dying man argued with his own death and won the '
           'argument, and rose angry. A child in a burning house asked the '
           'fire, politely, to wait &mdash; and it waited, and she walked out '
           'wondering why nobody else ever asked. And a seeker who had done '
           'everything right &mdash; the fasts, the vigils, the teachers '
           '&mdash; woke at last while doing nothing at all, buying bread, and '
           'wept at the unfairness. Four doors, one house. The disputants '
           'around this text hold whether a door can be built, and whether '
           'all doors should be opened.</p>',
 'chapter': 'Chapter the Second',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter II opens: the census here, the Fragile Path overleaf, the '
             'Avatar at 43, and the will&rsquo;s measure at 46.',
 'folio': '38A',
 'glossL': '<p><span class="mark">a</span> On the census &mdash; Sleeper, '
           'Sleepwalker, and the Awareness that runs before a waking &mdash; '
           'see M20, folio 40.</p>\n'
           '        <p><span class="mark">b</span> On the Night-Folk filed '
           'apart, stuck halfway in their own nightmares, see the same folio; '
           'their standing at the court is 533b&rsquo;s dispute.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'Epiphany and the fourfold embrace &mdash; perceptual, physical, '
           'intellectual, spiritual &mdash; see folio 40.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'absent formula, the crisis and its process, the wild talents of '
           'a violent waking, and the retrieval agents, see the elder '
           'apprentice manuscript, Initiates of the Art, folios 13&ndash;23 '
           'of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The census rhymes with '
           '533b&rsquo;s and the Masoret says so: who counts as a witness and '
           'who counts as awake are one question asked at two courts, and '
           'the Sleepwalker &mdash; half-roused, half-counted &mdash; sits in '
           'both margins.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'spark that stirs is the Avatar&rsquo;s, folio 43, and the wild talent that sometimes attends a violent waking is the optional storm of M20&rsquo;s folio 527, a leaf this binding has not taken up; the walking Quiet it can end in is 554a&rsquo;s '
           'country.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'retrieval race this folio&rsquo;s last clause names is the '
           'formation law of 567b run at speed: whoever reaches the woken '
           'first grinds the lens, and chapter V&rsquo;s gates and chapter '
           'VI&rsquo;s recruiters are all downstream of that footrace.</p>',
 'h1': 'Of Gods and Men',
 'hagahah': 'Everyone remembers their Awakening; no two accounts of the same '
            'one agree, including both of the ones the same mage gives.',
 'inner': '<p><span class="lemma">Whose closed eyes are the world&rsquo;s '
          'ballast.</span> The Sleeper clause&rsquo;s plain sense: the '
          'Masses are not extras but the medium &mdash; their belief is the '
          'water every working swims in, per 62a ahead, and their number '
          'outweighs the Awakened by millions to one. The census&rsquo;s '
          'first name is therefore not a dismissal but a load-bearing '
          'wall: everything this binding prices, from the vulgar rate to '
          'the Gauntlet&rsquo;s thickness, is priced against the '
          'sleeping.</p>\n'
          '        <p><span class="lemma">Half-roused.</span> The '
          'Sleepwalker clause&rsquo;s plain sense: the middle name covers '
          'the hedge-worker with her linear paths, the psychic with his '
          'narrow gift, and the merely sensitive &mdash; awareness of the '
          'world&rsquo;s periphery without the license to redraft it. The '
          'law&rsquo;s craft is the word before: such awareness often '
          'heralds a waking, so the census is not three boxes but a '
          'gradient with a cliff at the end, and the folios of the '
          'half-roused are a sibling volume&rsquo;s business.</p>\n'
          '        <p><span class="lemma">A fourfold embrace.</span> The '
          'Epiphany clause&rsquo;s plain sense: the waking is total or it '
          'is not the waking &mdash; perception, body, intellect, and '
          'spirit comprehending at once &mdash; and the books&rsquo; '
          'four verbs climb: the woken sees the art, feels it, grasps '
          'it, becomes it. The ladder matters at the table because its '
          'counterfeit is common: the Sleepwalker sees and sometimes '
          'feels, the scholar grasps &mdash; only the mage becomes, and '
          'the census turns on that last verb.</p>\n'
          '        <p><span class="lemma">Only survived.</span> The '
          'formula clause&rsquo;s plain sense, with the books&rsquo; own '
          'dry proof: if waking could be granted, someone would have '
          'ended the War with it &mdash; recruited armies, woken '
          'nations &mdash; and no one has. What precedes a waking is '
          'pattern, not procedure: the presage signs, the crisis, and '
          'the survivor&rsquo;s triumph over it, the process weighing '
          'more than the wound. The clause is the chapter&rsquo;s '
          'humility posted at its door: the one thing no art in this '
          'binding manufactures is a mage.</p>\n'
          '        <p><span class="lemma">Loud, and the world '
          'listens.</span> The retrieval clause&rsquo;s plain sense: the '
          'fresh waking often lashes out with wild talent beyond '
          'anything the mage will do again &mdash; panicked workings, '
          'enormous fees &mdash; and every faction keeps runners for '
          'exactly that thunder. The clause prices the setting&rsquo;s '
          'first race: between the Epiphany and the first teacher '
          'stands an interval measured in hours, and the margin '
          'opposite notes what rides on who arrives.</p>\n'
          '        <p><span class="lemma">Stuck halfway.</span> The '
          'Night-Folk clause&rsquo;s plain sense, filed where the census '
          'files it: the vampire, the shapechanger, the ghost, and their '
          'kin are mighty and are not mages &mdash; caught, the books say, '
          'halfway inside their own nightmares, transformed rather than '
          'woken. The census keeps them off the gradient on purpose: '
          'their roads run through sibling tractates, their standing at '
          'the court is 533b&rsquo;s dispute, and the one thing this '
          'binding rules is the boundary &mdash; night is not sleep, and '
          'neither is it waking.</p>',
 'inner_head': 'On the Census<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; name by name, clause by '
               'clause</span>',
 'name': 'Of Gods and Men',
 'outer': '<p><span class="lemma">Whether a door can be built.</span> The '
          'induction dispute. <span class="voice">Some say</span> the '
          'Union&rsquo;s recruitment reads as proof of concept: the '
          'Technocracy finds its candidates by analytics, shapes their '
          'circumstances, and calls the resulting Enlightenment a '
          'curriculum outcome &mdash; and if circumstances can be '
          'arranged, the door is being built, however piously everyone '
          'denies the carpentry. <span class="voice">Others say</span> '
          'read the clause again: arranged circumstances are still only '
          'weather, and the books&rsquo; own recruiters &mdash; mystic '
          'and Union alike &mdash; harvest wakings, never cause them; '
          'the analytics find the about-to-wake, which is prospecting, '
          'not carpentry. The distinction carries the chapter&rsquo;s '
          'whole dignity: a soul that can be woken by procedure is a '
          'soul the procedure owns, and the setting has planted its '
          'flag &mdash; deliberately, both schools agree &mdash; on the '
          'side of the unownable. What remains disputed is the '
          'gray-suited middle: the mentor who steers a promising '
          'Sleepwalker toward crisis, gently, for her own good. The '
          'first school calls it midwifery; the second calls it 188b '
          'with a kind face; and the folio, noting that chapter V&rsquo;s '
          'gates and chapter VI&rsquo;s analytics both do it, files the '
          'practice as universal and the verdict as wanting.</p>\n'
          '        <p><span class="lemma">Whether all doors should '
          'open.</span> The mass-awakening dispute, the line&rsquo;s '
          'oldest dream. <span class="voice">Some say</span> goal: a '
          'world entire awake is Ascension&rsquo;s only honest reading '
          '&mdash; anything less crowns some souls over others &mdash; '
          'and every faction&rsquo;s scripture, the Union&rsquo;s '
          'included, promises the Masses elevation eventually. <span '
          'class="voice">Others say</span> catastrophe: the census is '
          'load-bearing &mdash; the Sleepers&rsquo; ballast is what '
          'keeps reality one thing rather than seven billion &mdash; '
          'and a world of sudden gods is 554a&rsquo;s mindscape at '
          'planetary scale, every private reality armed. The first '
          'school answers that this is the warden&rsquo;s argument for '
          'the prison; the second, that some prisons are load-bearing '
          'walls seen from inside. The folio marks where the dispute '
          'actually bites: not at the end state, which no living '
          'faction will see, but at the rate &mdash; every school '
          'wants more wakings than yesterday and fewer than all at '
          'once, and the whole Ascension War is the argument about '
          'the number in between. <span class="kw">TEYKU</span> '
          '&mdash; the bread-buyer of the Gemara, asked, said only '
          'that nobody consulted her either way. And the schools share one '
          'closing stipulation, entered jointly: whatever the rate, the '
          'woken owe the sleeping more than caution &mdash; they owe them '
          'the world kept livable while the argument runs, which is the '
          'sixth article and the ninth seat agreeing for once, to '
          'everyone&rsquo;s discomfort. For the census&rsquo;s deepest '
          'clause is the one neither dispute touched: the three names '
          'are one species &mdash; the Sleeper is not raw material but '
          'the same soul earlier, every mage was one, and the binding '
          'that forgets it has begun writing chapter VI&rsquo;s articles '
          'in a mystic hand.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the built door, and the opened '
               'ones</span>',
 'rubric': 'the census of souls, and the waking',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening '
             '&middot; of gods and men &middot; the waking as law',
 'title': 'Tractate Aliyah · Folio 38a — Of Gods and Men: the census of souls, and the waking',
 'type': 'daf'}
