# Folio 43b - The Seeking. Verso of the Avatar: the trials of rank, per
# the wod-llm-wiki seeking page (M20 pp.44, 366-369).
FOLIO = {'bottom': '<p><span class="lemma">On the solo episode.</span> The books suggest the '
           'Seeking as between-sessions material &mdash; a one-player episode run '
           'in messages or at a side table &mdash; and the counsel is to take the '
           'suggestion: the trial gains privacy, the campaign loses no table '
           'time, and the player returns to the group holding a secret shaped '
           'like growth, which is the best prop the line issues.</p>\n'
           '        <p><span class="lemma">On building the dream.</span> Build '
           'the symbolic realm from the sheet: the fears listed, the flaws '
           'bought, the people loved. A Seeking assembled from the '
           'character&rsquo;s own materials reads as revelation; one assembled '
           'from stock symbolism reads as a licensing quiz, and the Avatar of '
           '43a, who is never indifferent, would not stoop to stock.</p>\n'
           '        <p><span class="lemma">On failing forward.</span> A failed '
           'Seeking leaves the mage where she stood, and the counsel is to make '
           'the standing-still story: what she could not face is now named at '
           'the table, and the campaign until the next attempt is the facing. '
           'The trial refused is a better arc than the trial passed, and the '
           'books&rsquo; own masters mostly walked that longer road.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on side tables, sheet '
                'mining, and the longer road</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Rank is not bought; it is survived.</span> The '
           'road of Arete runs through the <span class="term">Seeking</span>: a '
           'trial the Avatar stages when mage and player have resolved to '
           'advance, and the law&rsquo;s first strangeness is exactly that '
           'order &mdash; the resolve comes first, the trial answers '
           'it.<sup>a</sup> The Seeking is walked alone, in a realm of the '
           'mage&rsquo;s own symbols, her body left sleeping where her '
           'companions fret; it runs without dice for the most part, a '
           'contest of imagination and not of luck, the will rolled only '
           'where the walker must stand firm; and no fee accrues within, for '
           'the court of 533a holds no jurisdiction in a soul.<sup>b</sup> '
           'Its outcomes are law: the trial passed unlocks the next rank; '
           'the trial failed leaves the walker where she stood until she is '
           'ready; and the trial gone wrong in a maddening place is one '
           'road, the books warn, by which the Mad are made.<sup>c</sup> The '
           'walker is her own worst enemy within &mdash; the books leave '
           'open whether Seekings are hard because mages believe they will '
           'be &mdash; and the Union runs the same trials under the name '
           'Mediation, filed as training reflecting on itself, which '
           'changes the paperwork and not the sweat.<sup>d</sup> So the trial&rsquo;s '
           'law runs: the road of rank is walked asleep, alone, and '
           'inward, judged by the passenger of the recto in the '
           'walker&rsquo;s own symbols &mdash; and no rank in the binding '
           'is reached any other way, which is the chapter saying what '
           'it thinks rank is.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD one Seeking, in symbol, as they are told. '
           'The walker entered a library where every book was her own '
           'biography, shelved by the year, and each volume she opened '
           'ended earlier than she remembered living. At the stacks&rsquo; '
           'far end a librarian with her mother&rsquo;s hands asked for '
           'her card, and the card in her pocket was the missing pages, '
           'folded. She could keep the pages or pay the fine; she paid; '
           'and she woke owning one less excuse and one more rank, in '
           'that order. Her cabal asked what the trial had been. She said: '
           'overdue. The disputants around this text hold the metagame '
           'inversion and the mercy of the failed trial.</p>',
 'chapter': 'Chapter the Second &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Avatar: the recto keeps the passenger, this side '
             'keeps its examinations.',
 'folio': '43B',
 'glossL': '<p><span class="mark">a</span> On the Seeking as the road of '
           'Arete, resolved first and staged after, see M20, folios 44 and '
           '366&ndash;368.</p>\n'
           '        <p><span class="mark">b</span> On the solo walk, the '
           'symbolic realm, the diceless contest with its will-rolls at the '
           'standing places, and the absence of the fee within, see folios '
           '367&ndash;368.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'outcomes &mdash; the rank unlocked, the walker left standing, '
           'and the maddening-place road to the Mad &mdash; see folios 44 '
           'and 367&ndash;368.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'walker as her own worst enemy, the open question of believed '
           'difficulty, and Mediation as the Union&rsquo;s filing, see '
           'folios 366&ndash;368.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The examiner&rsquo;s '
           'identity is the recto&rsquo;s first dispute, and this '
           'folio&rsquo;s whole law leans on it: whether the trial is '
           'administered by an other or by the self decides what passing '
           'means, and the two sides of the leaf are one argument '
           'folded.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'maddening-place warning is 554a&rsquo;s doorway seen from the '
           'road: the Seeking and the Quiet are the setting&rsquo;s two '
           'involuntary journeys inward, and the books&rsquo; own margin '
           '&mdash; a monumental involuntary Seeking &mdash; has already '
           'joined them. The mindscape&rsquo;s clearing exit at 554b '
           'completes the triangle.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'rank this trial unlocks is 46a&rsquo;s ladder, next leaf, and the seder of 250a prices its first rungs; the Masoret notes the chapter assembling itself.</p>',
 'h1': 'The Seeking',
 'hagahah': 'The trial is graded by the examiner, staged by the examiner, and '
            'taken inside the examiner. Every mage passes eventually. Make '
            'of the pass rate what the schools cannot.',
 'inner': '<p><span class="lemma">The resolve comes first.</span> The '
          'order&rsquo;s plain sense, stated without flinching: the '
          'player and her mage decide to advance, and the trial follows '
          'the decision &mdash; the law does not pretend the Avatar '
          'ambushes the unready. The design is honest about being a '
          'game: advancement is chosen at the table, and the Seeking is '
          'the fiction&rsquo;s dignity wrapped around the choice, a '
          'ceremony that converts a purchase into a story. The margin '
          'opposite holds what that conversion is worth; this column '
          'only notes that the books chose ceremony over bookkeeping, '
          'on purpose, for the line&rsquo;s most important number.</p>\n'
          '        <p><span class="lemma">Without dice for the most '
          'part.</span> The contest clause&rsquo;s plain sense: the trial '
          'suspends the engine &mdash; no pools, no fee, magick working '
          'or failing by the story&rsquo;s own logic &mdash; and keeps '
          'exactly one mechanic: the will, rolled where the walker must '
          'stand firm or choose hard. The suspension is doctrine, not '
          'convenience: rank measures the soul, and the one trait the '
          'trial consults is the one trait 328 will call the '
          'soul&rsquo;s floor. The suspension also settles a table question '
          'the books field often: nothing brought into a Seeking '
          'transfers out &mdash; no essence banked, no working held, no '
          'wound carried past the waking save the lesson &mdash; for the '
          'realm is symbol, and symbols pay in symbol&rsquo;s coin. What '
          'crosses back is the walker, changed or not, and the rank if '
          'earned; the trial keeps everything else as its fee. Everything else is imagination, '
          'adjudicated by decision and not by luck, which is the '
          'books&rsquo; quiet definition of what a soul is.</p>\n'
          '        <p><span class="lemma">Where she stood until she is '
          'ready.</span> The failure clause&rsquo;s plain sense: the '
          'failed trial costs nothing but time &mdash; no fee, no wound, '
          'no demotion; the walker simply remains &mdash; and the mercy '
          'is load-bearing: a trial that punished failure would teach '
          'mages to stop attempting, and the Path would silt up at the '
          'third rank. The law prices only readiness, and readiness, '
          'unlike successes, can always be earned by living &mdash; '
          'which is why the counsel below calls the refused trial the '
          'better arc.</p>\n'
          '        <p><span class="lemma">One road by which the Mad are '
          'made.</span> The warning clause&rsquo;s plain sense: some '
          'walkers return insane and some never return, and the trial '
          'gone wrong in a maddening place feeds the same country the '
          'folio of Quiet maps. The clause keeps the Seeking honest '
          '&mdash; a door inward is a door, and doors admit &mdash; and '
          'its placement in the law is pastoral: the warning is printed '
          'beside the invitation, not after it, so no walker enters '
          'unadvised.</p>\n'
          '        <p><span class="lemma">Not the sweat.</span> The '
          'Mediation clause&rsquo;s plain sense: the Union&rsquo;s '
          'operatives walk the same trials under a filing that calls '
          'them training&rsquo;s subconscious reflection, and the '
          'renaming changes nothing the trial touches &mdash; the '
          'symbols still come from the walker&rsquo;s own drawer, the '
          'will still stands or breaks, the rank still waits on the far '
          'side. The commentary files the parallel with 43a&rsquo;s '
          'laundered names and moves on; the sweat, as the law says, '
          'is denominational in neither direction.</p>',
 'inner_head': 'On the Trial<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the order, the contest, and the '
               'mercies</span>',
 'name': 'The Seeking',
 'outer': '<p><span class="lemma">The metagame inversion.</span> The '
          'folio&rsquo;s strangest law: the player decides, then the '
          'fiction examines. <span class="voice">Some say</span> the '
          'inversion is the design&rsquo;s one great confession &mdash; '
          'rank is bought at the table like any trait, the trial is '
          'pageantry after the purchase, and a ceremony that cannot '
          'fail its buyer is not an examination but a receipt. Honest '
          'bookkeeping would charge the points and skip the theater. '
          '<span class="voice">Others say</span> the inversion is the '
          'design&rsquo;s one great insight: in a game about belief, '
          'the ceremony is the substance &mdash; the player&rsquo;s '
          'decision is the resolve the fiction then tests, the trial '
          'can be failed and the books say so, and the passage '
          'earned in an evening of hard choices is worth more at the '
          'table than any receipt, because the player remembers it '
          'as a story and not a transaction. The schools agree the '
          'trial cannot be indefinitely failed &mdash; every mage '
          'passes eventually, as the hagahah files with a raised '
          'eyebrow &mdash; and split on what that proves: rigged '
          'theater, says the first; or, says the second, exactly '
          'what readiness means &mdash; a test you retake until you '
          'are the person who passes it, which is how every '
          'examination worth taking has always worked. The schools also split a quieter '
          'question beneath: whether the trial&rsquo;s difficulty is '
          'discovered or believed &mdash; the books leave open that '
          'Seekings are hard because mages expect them to be &mdash; and '
          'if belief sets the wall even here, the examiner&rsquo;s '
          'identity matters less than either school pretends. <span '
          'class="kw">TEYKU</span> &mdash; the librarian, asked, '
          'stamped the card.</p>\n'
          '        <p><span class="lemma">The mercy&rsquo;s far '
          'edge.</span> The second dispute, on the failure clause. '
          '<span class="voice">Some say</span> the mercy is complete '
          'and correct: growth ungated by punishment, the Path kept '
          'walkable, the maddening-place warning covering the true '
          'risk. <span class="voice">Others say</span> the mercy has a '
          'shadow the law does not price: the walker who fails and '
          'fails and remains &mdash; decades at one rank, the trial '
          'refused politely each season &mdash; is the setting&rsquo;s '
          'commonest tragedy precisely because nothing forces the '
          'question; the Path&rsquo;s silt is made of the comfortable, '
          'and stagnation, 38b&rsquo;s quietest inward enemy, wears '
          'this clause as a blanket. The first school answers that '
          'forcing souls is the Union&rsquo;s department and chapter '
          'VI&rsquo;s indictment; the second concedes it, and asks '
          'only that the table notice the blanket. The folio '
          'notices: the mercy stands, the silt is real, and the '
          'difference between patience and hiding is &mdash; as the '
          'whole chapter keeps concluding &mdash; a question the '
          'examiner alone can grade, whoever the examiner is. The '
          'folio closes the leaf with the observation both disputes '
          'share: the Seeking is the one place in the binding where '
          'the game admits it is a game and the fiction does not '
          'flinch &mdash; the purchase and the pilgrimage, one act &mdash; '
          'and the line has kept that double exposure in print for '
          'three decades because no one has proposed anything more '
          'honest. The leaf turns on that sentence.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the receipt, and the blanket</span>',
 'rubric': 'the trials of rank',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening, '
             'continued &middot; of the Seeking &middot; the trial as law',
 'title': 'Tractate Aliyah · Folio 43b — The Seeking: the trials of rank',
 'type': 'daf'}
