# Folio 43a - The Avatar. Chapter II's center, per the wod-llm-wiki
# avatar page (M20 pp.42-45; Masters of the Art pp.13-16; Initiates of
# the Art pp.37-42).
FOLIO = {'bottom': '<p><span class="lemma">On casting the daemon.</span> The Avatar plays best '
           'as a recurring character with exactly one rule: it is never '
           'indifferent. Give it a face drawn from the mage&rsquo;s own symbols, '
           'a manner &mdash; teacher, parent, brute, or lover, per the books&rsquo; '
           'own casting call &mdash; and an agenda the player only half-knows. '
           'An Avatar reduced to a stat line is the folio&rsquo;s whole subject '
           'wasted.</p>\n'
           '        <p><span class="lemma">On the essence as compass.</span> '
           'Use the four temperaments as steering, not scripture: the Dynamic '
           'mage&rsquo;s episodes should feel improvised, the Pattern '
           'mage&rsquo;s built, the Questing mage&rsquo;s pulled forward, the '
           'Primordial&rsquo;s haunted from behind. A table that can name each '
           'character&rsquo;s weather has the chapter working for free.</p>\n'
           '        <p><span class="lemma">On the Genius at the table.</span> '
           'Play the Technocrat&rsquo;s inner guide exactly as written: the '
           'same presence under a laundered name, guiding through models and '
           'hunches instead of visions. The operative who dreams in '
           'flowcharts is not less haunted than the witch; she is haunted in '
           'a house style, and the difference is the whole Union in '
           'miniature.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on faces, weather, and '
                'laundered names</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Every mage carries a second passenger,</span> '
           'and the law calls it the <span class="term">Avatar</span>: the '
           'divine spark, the fragment of a higher self, whose stirring is the '
           'waking itself.<sup>a</sup> Its rating is law in three places: the '
           'essence a mage may hold is bounded by it, the essence she may '
           'draw in a turn is bounded by it, and the road of her rank runs '
           'through the trials it sets &mdash; the Seekings, whose law the '
           'verso keeps.<sup>b</sup> It has a personality and never '
           'indifference: it guides by dream, vision, and staged encounter, '
           'wearing whatever face the mage&rsquo;s symbols afford it, and it '
           'pushes an agenda that is not always hers. The law counts its '
           'temperaments four, with a fifth theorized: the <span '
           'class="term">Dynamic</span>, wild and creative; the <span '
           'class="term">Pattern</span>, that would make things firm; the '
           '<span class="term">Questing</span>, that seeks between the two; '
           'and the <span class="term">Primordial</span>, sliding beneath '
           'the rest, unknowable &mdash; and the fifth, the Infinite, is '
           'said to wait past all four, worn by no living mage.<sup>c</sup> '
           'The Union keeps the same passenger under a laundered name '
           '&mdash; the Genius, the flowering of one&rsquo;s own potential, '
           'insistently not a spirit &mdash; and its unmaking has a name '
           'this folio only points to: Gilgul, the sentence beneath every '
           'sentence.<sup>d</sup> So the law runs: one soul, two '
           'wills, and every folio of this chapter is their '
           'correspondence.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear what the schools say the passenger is. The '
           'Hermetic says: a shard of the divine, riding a mortal toward '
           'reunion &mdash; worship it correctly and it is a ladder. The '
           'Ecstatic says: it is yourself, the self past the noise, and '
           'talking to it is finally listening. The Dreamspeaker says: it '
           'is older than you and will outlast you; you are its errand, '
           'and honored to be one. The elder manuscripts whisper a '
           'stranger lineage: shards of beings from creation&rsquo;s '
           'first hour, learning selfhood from the souls they ride, '
           'which is why two sparks sometimes know each other across a '
           'crowded room. And the Union&rsquo;s manual says: potential, '
           'flowering on schedule &mdash; and its operatives dream, and '
           'file the dreams as noise. The disputants around this text '
           'hold the identity question and the temperament question.</p>',
 'chapter': 'Chapter the Second &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the chapter&rsquo;s center: the passenger here, its trials '
             'overleaf.',
 'folio': '43A',
 'glossL': '<p><span class="mark">a</span> On the Avatar as divine spark and '
           'higher self, see M20, folios 42&ndash;43, whence this page takes '
           'its number.</p>\n'
           '        <p><span class="mark">b</span> On the rating&rsquo;s '
           'three jurisdictions &mdash; essence held, essence drawn by the '
           'turn, and the Seekings &mdash; see folios 330&ndash;331 and '
           '366&ndash;368, with the trials&rsquo; law overleaf.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the four '
           'essences and the theorized fifth, see folios 44&ndash;45; the '
           'archmasters&rsquo; readings and the first-hour lineage are '
           'Masters of the Art, folios 13&ndash;16 of that volume, and the '
           'apprentice teaching is Initiates of the Art, folios '
           '37&ndash;42.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'Genius as the Union&rsquo;s reading, see folio 42; on Gilgul, '
           'see the resolution clause at 38b and the debt owed chapter '
           'VII.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The essence-in-a-turn bound '
           'is the arithmetic 78a prices in full, and the trials this '
           'rating gates are 46a&rsquo;s ladder: the Avatar is the '
           'chapter&rsquo;s load-bearing wall, and three folios lean on it '
           'from three sides.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'temperaments lean toward factions and the books say so: the '
           'Pattern toward the Union&rsquo;s conventions, the Questing '
           'toward the Council&rsquo;s seats, the Dynamic toward the Mad of '
           '234, wanting, and the Primordial toward the appetite of the '
           'Fallen &mdash; sought by them, the elder manuscript warns, for '
           'what it remembers.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'internal witness question &mdash; whether the passenger counts '
           'at 533a&rsquo;s court, watching its own mage work &mdash; is '
           'filed with the census of 533b, where the Masoret has kept a '
           'seat open for it since that folio was bound.</p>',
 'h1': 'The Avatar',
 'hagahah': 'The Technocracy calls it Genius and insists that this is '
            'different. The Avatar does not mind what it is called, which '
            'the Genius would tell them, if asked.',
 'inner': '<p><span class="lemma">A second passenger.</span> The '
          'definition&rsquo;s plain sense: the Avatar is not a power source '
          'but a person-shaped fact &mdash; the part of the soul that '
          'remembers reality is negotiable &mdash; and the waking of 38a '
          'is precisely its waking. It carries echoes across lifetimes, '
          'reborn rider by rider, and its long walk home to the Source is '
          'one whole school&rsquo;s reading of the binding&rsquo;s title. '
          'Everything else in the chapter is jurisprudence about a '
          'relationship.</p>\n'
          '        <p><span class="lemma">Bounded by it.</span> The '
          'rating clause&rsquo;s plain sense: the Avatar&rsquo;s depth is '
          'a pipe gauge &mdash; so much essence held, so much drawn in a '
          'turn, no more &mdash; and the design is theological arithmetic: '
          'the mage&rsquo;s connection to the world&rsquo;s raw fuel runs '
          'through the spark, so the spark&rsquo;s depth is the '
          'connection&rsquo;s width. The seder of 250a prices the dots; '
          'this folio explains what the purchase buys, which is '
          'throughput of the sacred.</p>\n'
          '        <p><span class="lemma">Never indifference.</span> The '
          'personality clause&rsquo;s plain sense, and the '
          'chapter&rsquo;s best sentence: whatever role the passenger '
          'takes, it takes one &mdash; teacher, parent, brute, lover '
          '&mdash; and the mage who has never quarreled with her Avatar '
          'has not yet met it. The clause matters mechanically because '
          'the trials are staged by this same personality: the examiner '
          'writes the exam in the student&rsquo;s own symbols, which is '
          'either intimacy or conflict of interest, and the verso&rsquo;s '
          'dispute is already audible.</p>\n'
          '        <p><span class="lemma">Reborn rider by rider.</span> '
          'The reincarnation clause&rsquo;s plain sense: the spark '
          'carries echoes of its earlier lives, and the echoes surface '
          '&mdash; in dream, in d&eacute;j&agrave; vu, in the past-life '
          'fragments the Seekings sometimes stage &mdash; so every mage '
          'is, at one remove, an heir. The clause funds half the '
          'setting&rsquo;s deep plots: the old debts that arrive '
          'addressed to the spark rather than the bearer, and the '
          'elder sparks that recognize each other across new faces, '
          'per the first-hour lineage the Gemara whispers.</p>\n'
          '        <p><span class="lemma">Temperaments four.</span> The '
          'essence clause&rsquo;s plain sense: the four are drives, not '
          'castes &mdash; the elder teaching calls them our limit of '
          'understanding, a taxonomy of how sparks push &mdash; and each '
          'colors a road: the Dynamic&rsquo;s walk is eclectic and '
          'legible only in hindsight, the Pattern&rsquo;s methodical, '
          'the Questing&rsquo;s hungriest for the summit and likeliest '
          'to go awry chasing power past understanding, the '
          'Primordial&rsquo;s a roadmap borrowed from whatever god-face '
          'the spark wears. The fifth, the Infinite, every school '
          'agrees to theorize and none claims to have met: the four '
          'are each incomplete on purpose, and completeness, the '
          'manuscripts say, is what the summit is.</p>\n'
          '        <p><span class="lemma">A laundered name.</span> The '
          'Genius clause&rsquo;s plain sense: the Union&rsquo;s renaming '
          'changes the paperwork and nothing else &mdash; the same '
          'presence, the same temperaments under the term Eidolon, the '
          'same guidance rerouted through models and hunches &mdash; and '
          'the manual&rsquo;s insistence that it is not a spirit is '
          'filed beside the machine-faith of 186b, in the drawer this '
          'binding keeps for rationalists&rsquo; gods. The law takes no '
          'side; the law only notes that both names bound the same '
          'arithmetic.</p>',
 'inner_head': 'On the Passenger<span class="comm-sub">the inner commentary '
               '&middot; the plain sense &middot; the spark, its gauge, and '
               'its faces</span>',
 'name': 'The Avatar',
 'outer': '<p><span class="lemma">The identity question.</span> If the '
          'Avatar wills the Seeking, who passes it? <span '
          'class="voice">Some say</span> the passenger is other: it '
          'predates the rider, outlasts her, stages her trials and '
          'grades them &mdash; and an examiner distinct from the '
          'examined is the only reading under which the trials mean '
          'anything; a self that tests itself and advances itself is '
          'a bureaucracy of one, rubber-stamping. <span '
          'class="voice">Others say</span> the passenger is self: the '
          'higher self past the noise, and the otherness is the '
          'noise&rsquo;s own testimony &mdash; of course the deeper '
          'self feels foreign to the shallower one that meets it; '
          'that foreignness is the distance to be closed, and closing '
          'it is the Path entire. The stakes are pastoral and sharp: '
          'the first school&rsquo;s mage can defy her Avatar &mdash; '
          'there is someone to defy &mdash; while the second&rsquo;s '
          'mage who defies it is refusing herself, which the folio of '
          'Quiet has already priced. The elder lineage &mdash; sparks '
          'as first-hour shards learning selfhood from their riders '
          '&mdash; sits deliberately athwart both: a passenger that is '
          'becoming its rider dissolves the question by walking '
          'through it. <span class="kw">TEYKU</span> &mdash; and the '
          'exam proceeds regardless, which both schools find '
          'suspicious.</p>\n'
          '        <p><span class="lemma">Destiny or description.</span> '
          'The temperament question. <span class="voice">Some say</span> '
          'essence is destiny: the books themselves lean the '
          'temperaments toward factions &mdash; Pattern to the Union, '
          'Questing to the Council, Dynamic to the Mad &mdash; and a '
          'drive installed beneath the personality, older than the '
          'personality, steers a life however the life protests; the '
          'sorting was done before the sorted arrived. <span '
          'class="voice">Others say</span> description, and lightly '
          'held: the elder teaching calls the four our limit of '
          'understanding in as many words &mdash; a taxonomy of '
          'observers, not a decree of the observed &mdash; and the '
          'setting&rsquo;s rosters overflow with counterexamples: '
          'Pattern-souled witches, Questing suits, the Dynamic monk '
          'whose chaos wears perfect discipline. The first school '
          'answers that exceptions prove pressure, not freedom; the '
          'second, that a destiny with this many exceptions is a '
          'weather report. The folio files the question where the '
          'chapter files everything: the spark pushes, the mage '
          'steers, and the proportion between those verbs is the '
          'whole difference between a life and a fate &mdash; '
          'unresolved here as everywhere, and better for it. And '
          'the folio grants the last clause to the table: whichever '
          'reading holds, the essence on the sheet is a promise about '
          'scenes &mdash; the Dynamic mage owed her chaos, the Pattern '
          'mage her architecture &mdash; and a Storyteller who pays '
          'those promises weekly has settled the dispute in the only '
          'currency that spends. For the Avatar, both schools concede, '
          'is the line&rsquo;s quietest masterpiece: the one companion '
          'no mage chooses, no rival steals, and no death certainly '
          'ends &mdash; and a setting that gives every player character '
          'an unresolvable relationship has built its deepest '
          'engine where no dice can reach it. The disputes above are that '
          'engine running, and the folio expects them at every table, '
          'unresolved, for decades.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the examiner, and the compass</span>',
 'rubric': 'the passenger, its gauge, and its faces',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening, '
             'continued &middot; of the Avatar &middot; the spark as law',
 'title': 'Tractate Aliyah · Folio 43a — The Avatar: the passenger, its gauge, and its faces',
 'type': 'daf'}
