# Folio 46b - The War. Verso of the ladder: the Ascension War defined,
# per the wod-llm-wiki ascension and consensus pages (M20 pp.46-53, 62).
FOLIO = {'bottom': '<p><span class="lemma">On the War as weather or front.</span> Decide in '
           'session zero how loud the War runs in this chronicle: background '
           'radiation &mdash; the occasional Suit, the sense of a tide &mdash; or '
           'active front, with operations and casualties. Both are canonical; '
           'mixing them unannounced is not, for the players build characters to '
           'the loudness they were promised.</p>\n'
           '        <p><span class="lemma">On stakes the table can hold.</span> '
           'The War&rsquo;s true prize &mdash; what humanity believes possible '
           '&mdash; is too large to play directly, so play its retail form: one '
           'neighborhood&rsquo;s zone, one hospital&rsquo;s quiet miracle rate, '
           'one school&rsquo;s curriculum. A chronicle that wins or loses a '
           'street&rsquo;s worth of reality has staged the whole War at a scale '
           'where victory is visible.</p>\n'
           '        <p><span class="lemma">On fighting it without '
           'battles.</span> The books say the War is fought mostly without '
           'battles, and the counsel is to believe them: the operations that '
           'matter are curricula, clinics, franchises, and feeds. Run war '
           'sessions as heists and elections more often than firefights, and '
           'the setting&rsquo;s strangest sentence &mdash; a war over what is '
           'real &mdash; starts paying rent.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on loudness, retail '
                'stakes, and bloodless fronts</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The War is over what is real,</span> and the '
           'law states it plainly: reality&rsquo;s baseline is the sum of '
           'belief, whoever shifts the belief shifts the world, and the '
           'factions of this binding have fought for centuries over the '
           'shifting &mdash; mostly without battles, for the front is the '
           'possible itself.<sup>a</sup> Its sides the reader has met: the '
           'Council&rsquo;s nine seats, holding that the world should hold '
           'many ways of being true; the Union&rsquo;s five Conventions, '
           'holding that it should hold one, safely; the Fallen, who would '
           'end the question; and the Mad, whom the question ended.<sup>b</sup> '
           'Its stakes are asymmetric by design: the Council fights for room '
           '&mdash; zones, refuges, the right of variance &mdash; while the '
           'Union fights for settlement, and a war between room and '
           'settlement has no shared victory condition, which is why it has '
           'no armistice.<sup>c</sup> And its present state the books give '
           'with a straight face: the Union holds the broad Consensus and '
           'has for a century and a half; the Council holds the margins, '
           'the zones, and the long game; and the only faction that '
           'believes the War is over is the one currently losing '
           'control of its winnings.<sup>d</sup> So the War&rsquo;s law runs: '
           'the front is everywhere belief is, the weapons are '
           'curricula and clinics, and the casualty lists are kept in '
           'chapters, not columns.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear why nobody has won. The Union&rsquo;s victory '
           'condition is a world fully settled &mdash; and its own folios '
           'confess the settlement leaking: the Time Table wrong, the '
           'watchers drowning, the ledger&rsquo;s chaos compounding. The '
           'Council&rsquo;s victory condition is a world safe for '
           'variance &mdash; and its own folios confess the variance '
           'starving, seat by seat, gate by gate. Each side&rsquo;s win '
           'requires the Masses&rsquo; belief, and the Masses, consulted '
           'by neither, keep believing an assortment: in science at the '
           'pharmacy, in luck at the casino, in ghosts at the funeral. '
           'The War&rsquo;s front line, the teachers concluded, runs '
           'through every Sleeper&rsquo;s ordinary day, and ordinary days '
           'are held by no one. The disputants around this text hold '
           'whether the metaphor of war damages what it names, and who '
           'is actually winning.</p>',
 'chapter': 'Chapter the Second &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the ladder, and the chapter&rsquo;s last leaf: the '
             'waking, the road, the passenger, the trial, the ladder &mdash; '
             'and the weather they all walk in.',
 'folio': '46B',
 'glossL': '<p><span class="mark">a</span> On the War over the possible '
           '&mdash; belief as baseline, the shifting as the fight, the '
           'battles mostly absent &mdash; see M20, folios 46&ndash;53 and 62, '
           'whence this chapter&rsquo;s numbers run.</p>\n'
           '        <p><span class="mark">b</span> On the sides, see this '
           'binding&rsquo;s own chapters: the seats at V, the Conventions at '
           'VI, the Fallen and the Mad at VII, wanting.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On room '
           'against settlement &mdash; the asymmetric stakes &mdash; see '
           'folios 46&ndash;53, with the zones of 62b in this binding.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'century and a half of scientific baseline and the '
           'Union&rsquo;s leaking settlement, see folio 62 and Technocracy '
           'Reloaded, folios 13&ndash;15 of that volume, which print the '
           'confession.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The thesis of 3a &mdash; all '
           'of Ascension&rsquo;s law is the law of who is watching &mdash; is '
           'this folio&rsquo;s law in court dress: the War is the fight '
           'over who the watchers shall be, and the Masoret closes the '
           'chapter by citing the binding&rsquo;s own first principle.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'charter of 168a and the convocation of 2a are the War&rsquo;s '
           'two founding documents, filed as bookends; the reader who has '
           'walked chapters V and VI holds both armies&rsquo; muster '
           'rolls.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'War&rsquo;s quietest front &mdash; the retrieval race of 38b, '
           'the lens-grinding of 567b &mdash; is where this chapter says '
           'the outcome is actually decided: not in battles but in '
           'first hours, one woken soul at a time.</p>',
 'h1': 'The War',
 'hagahah': 'The only faction that thinks the War is over is losing it. This '
            'is not a paradox; it is what losing a war over the possible '
            'feels like from the winning side.',
 'inner': '<p><span class="lemma">Mostly without battles.</span> The '
          'front&rsquo;s plain sense: the War&rsquo;s currency is belief, so '
          'its campaigns are cultural &mdash; the curriculum written, the '
          'miracle staged or suppressed, the zone held &mdash; and its '
          'firefights are exceptions, expensive precisely because vulgar '
          'violence bills at 533a&rsquo;s worst rates in front of the '
          'contested audience itself. The law&rsquo;s craft is the word '
          'mostly: the battles exist, the Pogrom was real, and the '
          'chapter&rsquo;s honest reading holds both the cold war and '
          'its hot exceptions.</p>\n'
          '        <p><span class="lemma">No shared victory '
          'condition.</span> The asymmetry&rsquo;s plain sense: room and '
          'settlement are not opposite flags on one hill but different '
          'games on one board &mdash; the Council wins wherever variance '
          'survives, the Union wins wherever it does not, and a truce '
          'would require agreeing what winning is, which is the one '
          'agreement the premise forbids. The Ascension Truce the '
          'histories record was therefore an intermission, not a '
          'settlement, and the books&rsquo; own metaplot reopened the '
          'question on schedule.</p>\n'
          '        <p><span class="lemma">Holds the margins, and the '
          'long game.</span> The standings&rsquo; plain sense: the '
          'scientific baseline is real and a century and a half old, '
          'the zones of 62b are real and everywhere, and both facts '
          'are load-bearing &mdash; the Union&rsquo;s victory is broad '
          'and thin, the Council&rsquo;s survival narrow and deep, and '
          'every folio of chapters V and VI documented one side of '
          'that ledger. The books decline to name a winner, and the '
          'inner commentary notes the declining is doctrinal: a named '
          'winner would end the game the line exists to run.</p>\n'
          '        <p><span class="lemma">Losing control of its '
          'winnings.</span> The present clause&rsquo;s plain sense, '
          'cited to the Union&rsquo;s own confession: the century '
          'delivered the settled world the articles ordered, and the '
          'settlement runs ungoverned &mdash; the tools in the '
          'Masses&rsquo; hands, the chaos compounding, the once-radical '
          'Union grown, in its own literature&rsquo;s word, quaint. '
          'The clause is the chapter&rsquo;s closing irony filed as '
          'fact: the War&rsquo;s apparent winner spends its folios '
          'managing the consequences of victory, which is what the '
          'hagahah means and the Gemara proves.</p>\n'
          '        <p><span class="lemma">Through every ordinary '
          'day.</span> The Gemara&rsquo;s law, made plain: the front is '
          'retail &mdash; each Sleeper&rsquo;s daily assortment of '
          'beliefs is a district, and the assortment&rsquo;s stubbornness '
          'is why neither headquarters can close the map. The clause '
          'licenses the counsel below: a chronicle holds the War '
          'honestly at the scale of streets, because that is the '
          'scale at which the War actually exists.</p>\n'
          '        <p><span class="lemma">Mostly, and the '
          'exceptions.</span> A note on the hot passages, for honesty: '
          'the cold war has burned open before &mdash; the pogroms, the '
          'purges, the fortress-realms besieged &mdash; and the '
          'binding&rsquo;s history folios keep those seasons unsoftened. '
          'The law&rsquo;s mostly is a description of the ordinary '
          'decade, not a promise about the next one, and every faction '
          'plans accordingly, which is itself a front. The planning is '
          'the cold war&rsquo;s true body count: budgets, doctrines, and '
          'the young trained for a fire that mostly never comes.</p>',
 'inner_head': 'On the Front<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the stakes, the standings, and '
               'the streets</span>',
 'name': 'The War',
 'outer': '<p><span class="lemma">Whether the metaphor damages what it '
          'names.</span> The naming dispute, which the brief demands and '
          'the setting deserves. <span class="voice">Some say</span> the '
          'war-word earns its keep: it names truly the stakes &mdash; '
          'worlds do end when the possible narrows; ask any seat in '
          'chapter V &mdash; and it disciplines the factions&rsquo; '
          'self-understanding: soldiers audit their conduct as gardeners '
          'never bother to. <span class="voice">Others say</span> the '
          'word has been the setting&rsquo;s most expensive purchase: '
          'call the disagreement a war and every gate hardens, every '
          'retrieval race arms, every Convention&rsquo;s excess files '
          'itself under necessity &mdash; the Pogrom is what the '
          'metaphor licensed, and 188b is where the license ends up. '
          'A century of the word, and both armies are institutions '
          'this binding spends chapters auditing for what '
          'institutions at war become. The first school answers that '
          'renaming the fight would not end it, only blind its '
          'conscripts; the second, that half the fight is the name '
          '&mdash; in a setting where words bend the real, the '
          'war-word is itself a working, cast on both armies, '
          'renewed every telling. The folio, which has just retold '
          'it, files the charge against itself and lets it stand. '
          '<span class="kw">TEYKU</span> &mdash; the word remains in '
          'the title of everything.</p>\n'
          '        <p><span class="lemma">Who is winning.</span> The '
          'standings dispute, the chapter&rsquo;s exit question. <span '
          'class="voice">Some say</span> the Union, obviously: the '
          'baseline is theirs, the century is theirs, and margins are '
          'what a winner leaves. <span class="voice">Others say</span> '
          'nobody &mdash; and mean it structurally: a war whose prize is '
          'the Masses&rsquo; belief is won by whoever the Masses '
          'become, and the Masses are becoming something neither '
          'headquarters ordered &mdash; the assortment of the Gemara, '
          'science at the pharmacy and ghosts at the funeral, a '
          'consensus that is plural in practice while settled in '
          'name. On this reading the War&rsquo;s quiet verdict is '
          'already in: the world belongs to the zones, the '
          'shareholder blocs of 192b, the stubborn retail day &mdash; '
          'and both armies are veterans of a front that moved. The '
          'first school calls that wishful reading of noise; the '
          'second calls it the only reading the evidence of six '
          'chapters supports. The folio closes the chapter without '
          'ruling, as the chapter&rsquo;s own law requires: the '
          'War&rsquo;s winner is decided by watchers, the watchers '
          'are the subject of the whole binding, and the binding is '
          'not finished. One codicil, jointly filed: whoever is '
          'winning, both schools agree on what losing would look '
          'like &mdash; a world with one belief or none &mdash; and '
          'that the two failures are the same failure approached '
          'from opposite doors, which is the nearest thing to a '
          'shared war-aim the setting has ever printed. The chapter '
          'closes on that agreement, deliberately: the reader who '
          'walks on to the World&rsquo;s folios carries it as a '
          'lens. And the lens is the chapter&rsquo;s parting gift: the '
          'waking, the road, the ladder, and the War are one story at '
          'four altitudes, told about every soul on the census.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the name, and the standings</span>',
 'rubric': 'the war over the possible',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening, '
             'concluded &middot; of the war &middot; the possible as front',
 'title': 'Tractate Aliyah · Folio 46b — The War: the war over the possible',
 'type': 'daf'}
