# Folio 46a - The Will to Power. Chapter II's ladder, per the
# wod-llm-wiki arete page (M20 pp.46-53, 328-330, 367-369).
FOLIO = {'bottom': '<p><span class="lemma">On the ladder at the table.</span> Post each '
           'character&rsquo;s rank beside the paradigm sentence and the practice '
           'description: the three lines together are the character, and the '
           'rank line is the one the chronicle itself will move. Players plan '
           'around what they can see, and a visible ladder turns advancement '
           'from bookkeeping into ambition.</p>\n'
           '        <p><span class="lemma">On the gate of will.</span> The '
           'clause that caps a weak-willed mage&rsquo;s casting at her will '
           'rather than her rank is a characterization engine: the brilliant '
           'coward, the enlightened burnout &mdash; mages whose understanding '
           'outruns their spine &mdash; are the clause walking, and a '
           'Storyteller who prices will&rsquo;s recovery into the story has '
           'made a stat into a soul.</p>\n'
           '        <p><span class="lemma">On the cycle as season '
           'planner.</span> Awareness, conflict, resolution is a season&rsquo;s '
           'arc in three words: open each rank&rsquo;s span with the world '
           'grown larger, spend the middle on the tests, and let the '
           'Seeking close it. A campaign paced to the growth law feels '
           'inevitable in the best sense &mdash; the players climb because '
           'the fiction is a ladder.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on visible ladders, '
                'gates, and seasons</span>',
 'center': '<p class="noindent"><span class="dropcap">V</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The measure of enlightened will is called '
           'Arete,</span> and it is the binding&rsquo;s central number: the '
           'dice of every casting, rated one to ten, most walkers holding one '
           'to three at the door.<sup>a</sup> It is law in four places. No art '
           'may be held past it: the rank caps every Sphere, and the master of '
           'five needs five. It is gated by the will: the mage whose permanent '
           'will runs below her rank casts and holds her arts at the '
           'will&rsquo;s height, not the rank&rsquo;s, for enlightenment '
           'without spine is a library with no lamp. It is priced at creation: '
           'one rank free, three at most for the founding purse, as the seder of 250a will count. And it is bought with trial, not with '
           'points: every rank past the door is won through a Seeking, per '
           'the folio behind this one, which is why it is the dearest number '
           'on the sheet and the slowest.<sup>b</sup> Its growth follows the '
           'growth law: awareness, in which the world enlarges; conflict, in '
           'which the enlarged world objects; resolution, in which walker and '
           'world settle their account &mdash; and the cycle repeats at every '
           'rank, for the Path is a spiral and not a stair.<sup>c</sup> And '
           'the rising is a widening: rank does not add force so much as '
           'sight &mdash; the low ranks glimpse the deeper levels, the middle '
           'ranks find their place in the picture, and the high ranks learn, '
           'in the books&rsquo; own phrase, how to rework reality.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear what the number is not. It is not power: the '
           'binding&rsquo;s engines have shown ten folios running that the '
           'mighty working is bought with successes and patience, and a '
           'patient novice outbuilds a hasty adept. It is not knowledge: '
           'the lore columns are bought with points and the rank is not. '
           'It is not virtue, whatever the old word meant in the old '
           'tongue: the Fallen hold high ranks and hold them honestly. '
           'The teachers, pressed for what remains when power, knowledge, '
           'and virtue are subtracted, answered with the word the books '
           'use: excellence &mdash; the will&rsquo;s depth of acquaintance '
           'with the real. The disputants around this text hold whether '
           'one will&rsquo;s deepening moves anything but itself, and what '
           'the gate of will confesses.</p>',
 'chapter': 'Chapter the Second &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the chapter&rsquo;s ladder; the War it climbs through waits '
             'overleaf, and the chapter closes there.',
 'folio': '46A',
 'glossL': '<p><span class="mark">a</span> On Arete as the casting pool, rated '
           'one to ten, see M20, folios 328&ndash;330; the growth law is '
           'folios 46&ndash;53, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the Sphere cap, the '
           'will&rsquo;s gate, the creation prices, and the Seeking as the '
           'only road up, see folios 328&ndash;329 and 367, with the seder '
           'of 250a and the trial of 43b in this binding.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On '
           'awareness, conflict, and resolution as the walker&rsquo;s cycle, '
           'see folios 46&ndash;53.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On rank as '
           'expanding sight &mdash; the deeper levels glimpsed, the place '
           'found, the reworking learned &mdash; see folio 369.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The number this folio '
           'measures is the number every engine in the binding rolls: '
           '500a&rsquo;s castings, 533a&rsquo;s botches, the Gauntlet-'
           'crossings of 82. The Masoret marks this page as the '
           'sheet&rsquo;s load path.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'will that gates the rank has its own folio: 328, where the Order of Making prices the soul&rsquo;s '
           'floor; the trials that raise the rank are 43b&rsquo;s, one '
           'leaf back.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'shedding of tools by rank is 586a&rsquo;s ladder read against '
           'this one: what rises here releases there, and the two '
           'schedules are one law seen from the hand and from the '
           'soul.</p>',
 'h1': 'The Will to Power',
 'hagahah': 'The old word means excellence, and the books kept it untranslated '
            'on purpose: every translation on offer &mdash; power, rank, '
            'holiness, depth &mdash; is some faction&rsquo;s thumb on the '
            'scale.',
 'inner': '<p><span class="lemma">The binding&rsquo;s central number.</span> '
          'The definition&rsquo;s plain sense: Arete is the pool, and '
          'everything else on the sheet is context for it &mdash; the '
          'Spheres name what a casting may attempt, the focus names how, '
          'and the rank names how well. Its range runs one to ten and its '
          'population is bottom-heavy by design: the door admits at one, '
          'the founding purse reaches three, and each rank beyond is a '
          'season of play and a trial, so the setting&rsquo;s middle '
          'ranks are earned middle age.</p>\n'
          '        <p><span class="lemma">The rank caps every '
          'Sphere.</span> The cap&rsquo;s plain sense: no art outgrows its '
          'artist &mdash; the Sphere ladders of chapter XI all terminate, '
          'for a given mage, at her own rank &mdash; and the cap is the '
          'design&rsquo;s deepest statement about magick: the arts are '
          'not tools lying about at fixed sizes but extents of one '
          'understanding, and the understanding is the limit. The '
          'grimoire law of 607a is this cap&rsquo;s corollary: the book '
          'confers precedent, never rank.</p>\n'
          '        <p><span class="lemma">A library with no lamp.</span> '
          'The gate&rsquo;s plain sense: permanent will below rank drags '
          'the casting pool and the Sphere maxima down to the '
          'will&rsquo;s height, and the design is a theory of '
          'enlightenment in one clause &mdash; understanding is not '
          'usable past the spine that carries it. The gate bites '
          'hardest on the burned-out and the broken, which is to say '
          'after the chronicle&rsquo;s worst nights, and the counsel '
          'below makes the recovery a story rather than a purchase.</p>\n'
          '        <p><span class="lemma">A spiral and not a stair.</span> '
          'The growth law&rsquo;s plain sense: the cycle is not passed '
          'through once but per rank &mdash; each new awareness enlarges '
          'the world again, each enlargement raises fresh conflict, each '
          'conflict wants its resolution &mdash; and the spiral&rsquo;s '
          'geometry is pastoral: the walker at rank five meets the same '
          'three seasons as the novice, wider. The folio of the road, '
          '38b, tells the same law as biography; this page files it as '
          'schedule.</p>\n'
          '        <p><span class="lemma">Sight, not force.</span> The '
          'widening clause&rsquo;s plain sense, against the '
          'ladder&rsquo;s commonest misreading: rank buys dice, and dice '
          'are the least of it &mdash; the books describe ascent as '
          'expanding awareness, the deeper levels resolving like a '
          'picture walked toward. The practical edge is real: the '
          'high-rank mage shedding tools per 586a and waiving walls per '
          '500a&rsquo;s automatic clause is not stronger so much as '
          'less obstructed, and the difference between those words is '
          'this chapter&rsquo;s entire teaching.</p>\n'
          '        <p><span class="lemma">The dearest number on the '
          'sheet.</span> The pricing clause&rsquo;s plain sense, '
          'completing the seder&rsquo;s arithmetic: the rank is the most '
          'expensive trait the books sell and the only one gated past '
          'money &mdash; experience buys the attempt, the Seeking decides '
          'it, and no volume of play-hours substitutes for readiness. '
          'The design keeps the setting&rsquo;s hierarchy honest: the '
          'old are mostly deep because depth takes seasons, and the '
          'prodigy who outruns her years is rare enough that every '
          'chantry knows its local example by name. The attempt itself is '
          'never wasted, per 43b&rsquo;s mercy: the trial refused returns '
          'its price in readiness.</p>',
 'inner_head': 'On the Ladder<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the number, its gates, and its '
               'geometry</span>',
 'name': 'The Will to Power',
 'outer': '<p><span class="lemma">Whether one will moves anything but '
          'itself.</span> The altitude dispute: personal against cosmic. '
          '<span class="voice">Some say</span> personal: the ladder is '
          'private by construction &mdash; the trials are solo, the rank '
          'is a depth of one soul&rsquo;s acquaintance with the real, and '
          'a mage&rsquo;s tenth rank rearranges nothing for the '
          'billions asleep; Ascension, if the word means anything, '
          'means one walker arriving, and the world was never the '
          'walker&rsquo;s to move. <span class="voice">Others say</span> '
          'the private reading forgets the setting&rsquo;s physics: '
          'reality is consensus, a will deep enough bends the '
          'water it swims in, and the books&rsquo; own high ranks '
          'reshape zones, found realms, and tilt the possible for '
          'everyone downstream &mdash; one soul&rsquo;s rise is '
          'infrastructure, whether or not the riser intends it. The '
          'first school answers that infrastructure is exactly the '
          'Union&rsquo;s word for it, and look what that licensed; the '
          'second, that a rise which moves nothing is a hobby, and '
          'nobody wars over hobbies. The folio notes what both '
          'concede: the binding&rsquo;s title is a verb whose subject '
          'the setting never fixed &mdash; one soul, a faction, the '
          'world &mdash; and every chapter of this tractate has been '
          'an argument about that subject wearing different robes. '
          '<span class="kw">TEYKU</span> &mdash; held open at the '
          'title&rsquo;s own request.</p>\n'
          '        <p><span class="lemma">What the gate confesses.</span> '
          'The will dispute. <span class="voice">Some say</span> the '
          'gate is the design&rsquo;s finest honesty: enlightenment '
          'that cannot act is not yet enlightenment, the spine is the '
          'soul&rsquo;s load-bearing member, and a ladder gated by '
          'will keeps the setting&rsquo;s mightiest number moored to '
          'character rather than accountancy. <span '
          'class="voice">Others say</span> the gate confesses a '
          'quiet cruelty: it prices trauma &mdash; the will burns down '
          'in exactly the chronicles&rsquo; worst passages, and the '
          'clause docks the wounded walker&rsquo;s whole art at her '
          'lowest hour, a tax on having suffered recently. The '
          'schools meet at the table&rsquo;s remedy: the gate stands, '
          'and the recovery of will is played as story &mdash; rest, '
          'friends, meaning &mdash; so the clause reads as '
          'convalescence instead of punishment. What neither school '
          'disputes is the clause&rsquo;s theology, which the folio '
          'files as the chapter&rsquo;s last word before the War: in '
          'this binding the soul&rsquo;s floor is not brilliance, '
          'or lineage, or rank &mdash; it is the plain human spine, '
          'purchasable by no art, and 328 owes that sentence its whole folio, at the Order of Making&rsquo;s close. The disputants leave their marker here regardless: every ladder in '
          'this binding &mdash; the Spheres, the instruments, the '
          'ranks &mdash; terminates in some ordinary human faculty '
          'that cannot be bought, and the design&rsquo;s insistence on '
          'that termination is either its deepest humanism or its '
          'oldest sleight, depending on which school is holding the '
          'sheet. Both schools hold it often, and the folio notes the '
          'marker has never once gone unclaimed at either table, '
          'which is its own small datum about the design. Excellence, '
          'untranslated, holds the door open for every reading, and the '
          'hagahah&rsquo;s warning about thumbs stays posted beside '
          'it. Ten ranks, one untranslatable word, and a century of '
          'commentary: the ladder&rsquo;s history is this folio&rsquo;s '
          'own genre in miniature.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the altitude, and the gate</span>',
 'rubric': 'the measure of enlightened will',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Second: The Awakening, '
             'continued &middot; of the will to power &middot; the ladder as law',
 'title': 'Tractate Aliyah · Folio 46a — The Will to Power: the measure of enlightened will',
 'type': 'daf'}
