# Folio 62a - Consensus and Belief. Chapter III opens, per the
# wod-llm-wiki consensus page (M20 pp.48, 62-63).
FOLIO = {'bottom': '<p><span class="lemma">On declaring the baseline.</span> Session zero '
           'should state the chronicle&rsquo;s baseline reality in a sentence '
           '&mdash; what this world&rsquo;s street believes possible &mdash; and '
           'post it with the constitution. Every vulgarity ruling for the whole '
           'campaign is a reading of that sentence, and the folio of casting, 500a, will beg for it; this folio explains why it exists to be begged for.</p>\n'
           '        <p><span class="lemma">On the ocean at the table.</span> '
           'Let players feel the inertia physically in narration: the vulgar '
           'working strains, the coincidental one glides, and the difference '
           'should read in the prose before any die lands. A table that can '
           'feel the water believes in the wall; a table that only hears '
           'difficulty numbers is memorizing a tax code.</p>\n'
           '        <p><span class="lemma">On moving it in play.</span> The '
           'Consensus shifts at generational scale, but its retail edges move '
           'in chronicle time: a neighborhood&rsquo;s beliefs can be nudged in '
           'a season. Let the players see their works compound &mdash; the '
           'clinic&rsquo;s quiet miracles normalizing, the block growing '
           'thin-veiled &mdash; and the setting&rsquo;s grandest abstraction '
           'becomes the campaign&rsquo;s scoreboard.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on baselines, water, and '
                'scoreboards</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Reality has a baseline, and the baseline is '
           'voted.</span> The <span class="term">Consensus</span> is the '
           'collected weight of human belief: what the Masses hold possible is '
           'what the world enforces, majorities bind, and the Awakened '
           'themselves swim in the verdict.<sup>a</sup> The books&rsquo; figure '
           'is water: reality as an ocean the mage may splash, channel, and '
           'swim, but never wish into confetti &mdash; the pushback of the '
           'sum of sleeping belief, which outweighs any single will by '
           'millions to one, is the inertia every working feels.<sup>b</sup> '
           'What most people call just the way things are is the <span '
           'class="term">dominant paradigm</span>; the term Consensus began '
           'as the Union&rsquo;s and is now everyone&rsquo;s, which is itself '
           'a small proof of the law it names.<sup>c</sup> And the law keeps '
           'a clause the metaplot forgets: the single global paradigm is a '
           'fiction &mdash; belief pools locally, regions and cultures hold '
           'their own baselines, and the world is a weather map of '
           'realities, not one climate; the zones are the verso&rsquo;s '
           'business.<sup>d</sup> So the water&rsquo;s law runs, and every engine '
           'downstream obeys it: the coincidental working swims with the '
           'local current and the vulgar against, the court of 533a is '
           'the current&rsquo;s bailiff, and the mage&rsquo;s whole trade '
           'is conducted in a medium that outvotes her &mdash; which is '
           'why the wise learn hydrology before they learn fire.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD how the water moved, in three beats. In the '
           'first age belief pooled in valleys: each people&rsquo;s world '
           'ran on its own weather, the gods were local, and the workings '
           'of one valley were the commonplaces of the next. Then came the '
           'joining &mdash; trade, conquest, the burning times &mdash; and '
           'the pools ran together; what had been a thousand baselines '
           'became a few, and every joining drowned somebody&rsquo;s '
           'possible. And in the third beat, the last century and a half, '
           'one paradigm spread further than any before it: the rational '
           'creed, carried by the Union&rsquo;s long campaign, until the '
           'broad world&rsquo;s water ran cold and clear and chlorinated. '
           'The teachers ended with the accounting: the present baseline '
           'is a victory &mdash; and the disputants around this text hold '
           'whose, and what kind of fact the water is.</p>',
 'chapter': 'Chapter the Third',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter III opens: the water here, its weather map overleaf, the '
             'life-blood at 78, and the veil at 82.',
 'folio': '62A',
 'glossL': '<p><span class="mark">a</span> On the Consensus as reality&rsquo;s '
           'established baseline &mdash; rules decided by the collected '
           'weight of belief &mdash; see M20, folio 62, whence this page '
           'takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the ocean figure and '
           'reality inertia &mdash; the splash, the channel, and the '
           'refused confetti &mdash; see folios 48 and 62.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'dominant paradigm and the term&rsquo;s Union coinage, see folio '
           '62.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'single paradigm as fiction and the local pooling of belief, '
           'see folios 62&ndash;63; the zones themselves are kept overleaf, '
           'with the systems chapter&rsquo;s reading at folio 611.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is 533a&rsquo;s '
           'foundation and says so: the court&rsquo;s whole fee schedule '
           'prices offenses against the water this page defines, and the '
           'engine of 500a rolls every die inside it. The reader who '
           'started at chapter XI should now feel the floor arrive.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'War of 46b is fought over this folio&rsquo;s subject, and the '
           'three beats of the Gemara are that folio&rsquo;s front line '
           'given a history; the Union&rsquo;s coinage clause is the '
           'second article of 168a caught working.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'majority that binds is 533b&rsquo;s census aggregated: one '
           'witness prices one working, and seven billion price the '
           'world. The Masoret files the two folios as one law at two '
           'magnifications.</p>',
 'h1': 'Consensus and Belief',
 'hagahah': 'The majority is always sane by definition. The definition is the '
            'problem, and the binding&rsquo;s whole shelf of madness folios '
            'is its footnote.',
 'inner': '<p><span class="lemma">The baseline is voted.</span> The '
          'definition&rsquo;s plain sense: the Consensus is not an opinion '
          'poll about reality but reality&rsquo;s own constitution &mdash; '
          'what is believed at scale is what is enforced at scale, and '
          'the enforcement is physics, not police. The clause every '
          'newcomer misses is the franchise: the vote is cast by living, '
          'not by arguing &mdash; each Sleeper&rsquo;s ordinary expectations '
          'are a ballot marked daily, which is why the War of 46b is '
          'fought in curricula and clinics rather than parliaments.</p>\n'
          '        <p><span class="lemma">Never wish into confetti.</span> '
          'The inertia clause&rsquo;s plain sense: the ocean figure is '
          'load-bearing arithmetic &mdash; the mage&rsquo;s will is real '
          'and the water&rsquo;s weight is realer, millions of sleeping '
          'votes to one waking one &mdash; and every engine downstream '
          'implements it: the coincidental discount is swimming with '
          'the current, the vulgar surcharge is swimming against, and '
          'the court&rsquo;s backlash is what the undertow does to the '
          'arrogant. The figure also carries the chapter&rsquo;s hope: '
          'water moves &mdash; slowly, in bulk, but it moves.</p>\n'
          '        <p><span class="lemma">Now everyone&rsquo;s.</span> The '
          'coinage clause&rsquo;s plain sense, with its small irony '
          'preserved: the word Consensus entered the setting as Union '
          'vocabulary and conquered the whole discourse, mystics '
          'included &mdash; a paradigm&rsquo;s term for reality becoming '
          'everyone&rsquo;s term for reality is the second article of '
          '168a demonstrated on the reader. The inner commentary files '
          'the demonstration without alarm: words are instruments, per '
          '586b, and borrowed instruments still work &mdash; but the '
          'margin should notice whose toolbox the whole conversation '
          'is standing in. The borrowing also cuts the other way, '
          'which the margin should file in fairness: the mystics&rsquo; '
          'vocabulary &mdash; paradigm, avatar, ascension &mdash; has '
          'colonized the Union&rsquo;s corridors just as thoroughly, '
          'whatever the style guides pretend. Two vocabularies, one '
          'discourse, and the crossover is the détente neither side '
          'negotiated: the argument, at least, is conducted in a '
          'shared tongue, which is more than the founding centuries '
          'managed.</p>\n'
          '        <p><span class="lemma">A weather map, not one '
          'climate.</span> The locality clause&rsquo;s plain sense: '
          'belief pools &mdash; by region, culture, block, and hour '
          '&mdash; so the baseline is plural in fact however singular '
          'in myth, and the twentieth recension revived the zones on '
          'purpose to say so. The clause matters doubly: at the table '
          'it makes vulgarity a question of where, and in the setting '
          'it is the Council&rsquo;s whole survival &mdash; the margins '
          'where variance lives are not exceptions to the law but the '
          'law&rsquo;s own fine grain.</p>\n'
          '        <p><span class="lemma">Every joining drowned '
          'somebody&rsquo;s possible.</span> The history&rsquo;s plain '
          'sense, kept at the Gemara&rsquo;s temperature: the '
          'consolidation of baselines was conquest&rsquo;s shadow '
          '&mdash; trade and empire ran the pools together, and each '
          'merger&rsquo;s losers watched their commonplaces become '
          'impossibilities. The books say this plainly and the '
          'commentary repeats it plainly: the present baseline is not '
          'neutral ground but the high-water mark of particular '
          'victories, and chapter V&rsquo;s seats each keep a drowned '
          'valley&rsquo;s memory. The dispute over what to call those '
          'victories is the margin&rsquo;s.</p>',
 'inner_head': 'On the Water<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the vote, the weight, and the '
               'weather</span>',
 'name': 'Consensus and Belief',
 'outer': '<p><span class="lemma">What kind of fact the water is.</span> '
          'The strong and weak readings, the chapter&rsquo;s foundation '
          'dispute. <span class="voice">Some say</span> strong: the '
          'Consensus is physics &mdash; belief literally constitutes the '
          'real, the ocean is ontology, and a world believed otherwise '
          'would be otherwise, atoms and all; the setting&rsquo;s every '
          'engine reads naturally under this ontology and the books&rsquo; '
          'own cosmology chapters preach it. <span class="voice">Others '
          'say</span> weak: the Consensus governs perception and '
          'permission &mdash; what may be noticed, what may be done '
          'unpunished &mdash; while something stands beneath the water '
          'that no vote reaches; the strong reading, they note, cannot '
          'say why the deep laws hold steady across every zone and '
          'century, nor what the Masses&rsquo; belief is belief about. '
          'The stakes run through the whole binding: under the strong '
          'reading Ascension is renovation and the War is for '
          'everything; under the weak it is curatorship and the War is '
          'for the catalogue. The books decline the question in print '
          '&mdash; deliberately, both schools agree, for the line runs '
          'on the tension. <span class="kw">TEYKU</span> &mdash; the '
          'water, asked what it rests on, returned the question.</p>\n'
          '        <p><span class="lemma">Whose victory.</span> The '
          'history dispute. <span class="voice">Some say</span> '
          'conspiracy: the rational baseline was moved &mdash; a '
          'centuries-long campaign by the Order and its heir, cannon to '
          'curriculum, the greatest working ever cast and never '
          'audited; the Gemara&rsquo;s third beat has an author, and '
          'chapter VI printed his charter. <span class="voice">Others '
          'say</span> service: the Masses were not herded to the '
          'rational creed but fled to it &mdash; from plague toward '
          'medicine, from dark toward lamplight &mdash; and the '
          'Union&rsquo;s campaign pushed on a door the Sleepers were '
          'already opening; call it conspiracy and you erase the '
          'customers. The first school answers with the drowned '
          'valleys: nobody chose to lose their gods at gunpoint. The '
          'second answers with the pharmacy: nobody queues at dawn '
          'for a paradigm they were merely assigned. The folio files '
          'what six chapters of this binding have earned it: both '
          'sentences are true, the proportion varies by valley and '
          'century, and the honest history of the water is the one '
          'that keeps both &mdash; which the Gemara, read again, '
          'already does. And one procedural note the schools co-sign: '
          'whichever history holds, the water&rsquo;s present motion is '
          'observable at the table &mdash; the zones, the storms, the '
          'strange coincidences trending &mdash; and a chronicle that '
          'tracks the motion is doing primary research both '
          'factions would pay for, which is the setting&rsquo;s '
          'standing invitation to play. And the folio&rsquo;s last '
          'clause belongs to the drowned valleys, entered by both '
          'schools without dispute: whatever the water is and whoever '
          'moved it, the baselines lost were worlds, whole ones, with '
          'names &mdash; and the chapter that follows this one keeps '
          'the springs where some of them still rise. The water &mdash; '
          'plural, moving, contested &mdash; is the binding&rsquo;s true '
          'protagonist, and this folio is where it takes the '
          'stage under its own name.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the ontology, and the history</span>',
 'rubric': 'the baseline, and the weight of belief',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World '
             '&middot; of consensus and belief &middot; the water as law',
 'title': 'Tractate Aliyah · Folio 62a — Consensus and Belief: the baseline, and the weight of belief',
 'type': 'daf'}
