# Folio 62b - The Zones. Verso of Consensus: reality's weather map, per
# the wod-llm-wiki consensus page (M20 pp.62-63, 611).
FOLIO = {'bottom': '<p><span class="lemma">On mapping the chronicle.</span> Draw the '
           'campaign&rsquo;s zone map early and coarsely: downtown runs '
           'technocratic, the old quarter remembers, the reservation and the '
           'cathedral keep their own weather, and one block is stranger than it '
           'should be. Five zones is plenty; the map&rsquo;s purpose is that '
           'travel changes the rules, and the players learn the city the way '
           'mages actually would &mdash; by where their hands work.</p>\n'
           '        <p><span class="lemma">On the simple option.</span> The '
           'books bless the single-Consensus game in as many words, and so does '
           'this counsel: a chronicle that wants one baseline &mdash; the '
           'Union&rsquo;s victory played flat &mdash; should take it and skip '
           'the map. Zones reward travel-heavy, culture-heavy campaigns; a '
           'single tight city story may play better on one climate.</p>\n'
           '        <p><span class="lemma">On zones with people in '
           'them.</span> A zone is a community&rsquo;s believing, so play the '
           'community and not just the modifier: the faith-zone&rsquo;s weather '
           'comes from congregants, the old quarter&rsquo;s from grandmothers, '
           'and the campaign&rsquo;s best zone scenes are the ones where the '
           'players meet the believers whose belief they are borrowing. '
           'Respect is also good craft: a zone reduced to terrain is a '
           'people reduced to terrain.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on coarse maps, flat '
                'options, and believers</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The water pools, and the pools have '
           'names.</span> The law of <span class="term">reality zones</span>: '
           'belief is local before it is global, and where a community&rsquo;s '
           'holding differs from the broad baseline, the difference governs '
           '&mdash; the zone&rsquo;s own creed sets what reads as coincidence '
           'within it.<sup>a</sup> In the technocratic zone the machine-creed '
           'rules: the device passes, the sigil bills. In the zones of faith '
           'and custom the poles reverse by degree: the blessing passes where '
           'the gadget startles, and the old arts run at the discount the '
           'city denies them.<sup>b</sup> The zones are graded, not fenced: '
           'belief shades block by block and hour by hour, the airport is '
           'nobody&rsquo;s country, and the same working may price three ways '
           'on one afternoon&rsquo;s walk.<sup>c</sup> The recension states '
           'the option plainly in both directions: the twentieth revived the '
           'zones on purpose, against the myth of the single victory &mdash; '
           'vast regions live unwired, the mystic cultures hold their '
           'ground &mdash; and it licenses with equal plainness the simpler '
           'game, one Earth on one Consensus, for the tables that want the '
           'victory played flat.<sup>d</sup> So the map&rsquo;s law runs: '
           'venue governs, gradients shade, and the traveler prices her '
           'workings by the block &mdash; for the chronicle&rsquo;s city is '
           'not one country but a treaty of neighborhoods, and every '
           'mage in it is somewhere a native and somewhere an '
           'ambassador, whether or not she has checked which.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and walk one street. At its foot, the hospital: the '
           'water runs cold and clear, the witch&rsquo;s poultice is '
           'assault and the surgeon&rsquo;s laser is Tuesday. Three blocks '
           'up, the old quarter: the poultice is what your grandmother '
           'would have used, and works accordingly, and the laser is '
           'looked at askance. At the hill&rsquo;s crown, the cathedral: '
           'within its doors the candle outranks them both, and has since '
           'before the street had a name. One working &mdash; a mending '
           '&mdash; walks the street with the reader: vulgar at the foot, '
           'folk-remedy in the middle, miracle at the crown, identical '
           'dice throughout. The disputants around this text hold what '
           'the map honors and what it risks, and whether the zones are '
           'the War&rsquo;s margins or its verdict.</p>',
 'chapter': 'Chapter the Third &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Consensus: the recto keeps the water, this side keeps '
             'the weather map.',
 'folio': '62B',
 'glossL': '<p><span class="mark">a</span> On reality zones &mdash; local '
           'belief governing the local possible &mdash; see M20, folios '
           '62&ndash;63, with the systems reading at folio 611.</p>\n'
           '        <p><span class="mark">b</span> On the technocratic zone '
           'and the zones of faith and custom, and the reversal of the '
           'poles by degree, see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'grading &mdash; belief shading by block and hour &mdash; see '
           'folio 611&rsquo;s counsel; the airport is this '
           'commentary&rsquo;s example, offered in the source&rsquo;s '
           'spirit.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'revival of the zones against the single-victory myth, and the '
           'equal license of the one-Consensus game, see folios '
           '62&ndash;63.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The zone law is the '
           'court&rsquo;s change of venue: 533a&rsquo;s fees and '
           '533b&rsquo;s census both read against the local water, and '
           'the practice folio of 572a &mdash; the theater priced by its '
           'street &mdash; is this page&rsquo;s law worn as a coat.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'thin and thick of the veil at 82 tracks the same map: where '
           'belief holds the old weather, the wall to the spirit runs '
           'low, and the two folios should be read as one atlas in two '
           'projections.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'zones are the Council&rsquo;s survival and the War&rsquo;s '
           'scoreboard, per 46b; the Masoret notes that every Tradition '
           'seat of chapter V is, among other things, the gardener of a '
           'zone.</p>',
 'h1': 'The Zones',
 'hagahah': 'The map is not the territory, except here, where the territory is '
            'made of what its people believe the map should say.',
 'inner': '<p><span class="lemma">The difference governs.</span> The zone '
          'law&rsquo;s plain sense: vulgarity is adjudicated against the '
          'local water, not the planetary average &mdash; the working '
          'reads as the zone reads it &mdash; and the mechanical carriage '
          'is through the court&rsquo;s own instruments: the bystander of '
          '533a is always a local, and her expectations are the '
          'zone&rsquo;s. Nothing new is bolted on; the venue simply '
          'changes, which is why the law needed one folio and not a '
          'subsystem.</p>\n'
          '        <p><span class="lemma">By degree.</span> The '
          'reversal clause&rsquo;s plain sense: zones are not photographic '
          'negatives of the city &mdash; the faith-zone does not price '
          'the laser as the city prices the poultice, symmetric to the '
          'decimal; each pool holds its own particular assortment, '
          'stricter here and looser there, and the Storyteller reads '
          'the local creed rather than flipping a switch. The '
          'grain matters: a zone is a culture, and cultures are not '
          'inversions of each other but originals.</p>\n'
          '        <p><span class="lemma">Nobody&rsquo;s country.</span> '
          'A note on the mixed places, the map&rsquo;s hardest terrain: '
          'the airport, the hospital lobby, the border town &mdash; '
          'venues where no single water holds and the '
          'bystander&rsquo;s creed must be read head by head. The '
          'commentary&rsquo;s counsel is the chart&rsquo;s own: where the '
          'water is genuinely mixed, default to the broad baseline and '
          'let the particular witnesses move it, which keeps the '
          'ruling fast and the fiction honest at once. The mixed venues '
          'are also the War&rsquo;s livest fronts, for whoever settles a '
          'crossroads&rsquo; weather has annexed it, and both armies '
          'know which buildings to fund. The commentary marks the '
          'crossroads accordingly.</p>\n'
          '        <p><span class="lemma">Graded, not fenced.</span> The '
          'boundary clause&rsquo;s plain sense: no wall stands at the '
          'zone&rsquo;s edge &mdash; belief shades, mixes, and commutes; '
          'the hospital&rsquo;s nurses live in the old quarter and carry '
          'both waters in one head &mdash; and the gradient is the '
          'law&rsquo;s realism. For the table it means the map is '
          'coarse and the margins are play: the three-price afternoon '
          'of the Gemara is not an edge case but the law working '
          'normally on a normal street.</p>\n'
          '        <p><span class="lemma">Against the myth of the single '
          'victory.</span> The revival clause&rsquo;s plain sense: the '
          'twentieth recension restored the zones deliberately, naming '
          'the single global paradigm a fiction &mdash; the unwired '
          'regions, the standing mystic cultures, the plural fact of '
          'the world &mdash; and the restoration is a load-bearing '
          'correction to the metaplot&rsquo;s own habit of speaking as '
          'if the Union&rsquo;s victory were total. The recto&rsquo;s '
          'weather map is not flavor; it is the setting&rsquo;s census '
          'done honestly.</p>\n'
          '        <p><span class="lemma">Played flat.</span> The '
          'option clause&rsquo;s plain sense: the one-Consensus game is '
          'licensed, not grudged &mdash; a table may run the whole '
          'Earth on the cold clear water and lose nothing but the '
          'map; the engines run identically, only the venue stops '
          'moving. The license is the books&rsquo; recurring humility '
          'about their own machinery, and the counsel below repeats '
          'it without embarrassment: complexity is a budget, and '
          'some chronicles spend it better elsewhere.</p>',
 'inner_head': 'On the Map<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; venues, gradients, and '
               'options</span>',
 'name': 'The Zones',
 'outer': '<p><span class="lemma">What the map honors and what it '
          'risks.</span> The representation dispute, which the folio '
          'owes its own subject. <span class="voice">Some say</span> the '
          'zone law is the setting&rsquo;s deepest respect paid: it '
          'writes into physics that the mystic cultures&rsquo; worlds '
          'are not error but reality &mdash; the reservation&rsquo;s '
          'weather is as constitutionally real as the laboratory&rsquo;s '
          '&mdash; and no other license in the books does more to '
          'unwrite the single-victory myth that flattered the '
          'colonizers&rsquo; century. <span class="voice">Others '
          'say</span> honor at that altitude risks the museum again: a '
          'map that marks the old quarter magical and the downtown '
          'real has exoticized the quarter in the act of blessing it, '
          'and a table&rsquo;s zone of faith can slide into scenery '
          '&mdash; a place where the rules get colorful &mdash; unless '
          'the believers are played as people with the pen. The '
          'schools agree the difference is made at the table, not in '
          'the law, and the counsel below is their joint draft: zones '
          'with people in them, communities before modifiers. The '
          'folio adds the binding&rsquo;s standing coda: where the '
          'table cannot do it with care, choose a different coat '
          '&mdash; and notes that the law itself, read whole, sides '
          'with the first school, for it makes the quarter&rsquo;s '
          'water load-bearing, and nothing in a museum bears '
          'load. The schools add one drafting note for the '
          'table&rsquo;s use: the zone drawn from research and '
          'relationship &mdash; a real community&rsquo;s believing, '
          'consulted &mdash; plays deeper than the zone drawn from '
          'costume, every time, and the difference is audible within '
          'a session. The verdict question they leave standing where the '
          'chapter&rsquo;s law leaves everything: in the water, which '
          'moves, and will have moved again before the binding&rsquo;s '
          'next reader walks the street. Walk it twice; bring '
          'change. The pun is the folio&rsquo;s, and it stands by '
          'it.</p>\n'
          '        <p><span class="lemma">Margins or verdict.</span> '
          'The standings dispute, inherited from 46b and sharpened '
          'here. <span class="voice">Some say</span> margins: the zones '
          'are where variance survives, which is to say where it '
          'retreated &mdash; a weather map of holdouts, each smaller '
          'than its grandmother&rsquo;s, and calling the reservation a '
          'victory is the loser&rsquo;s arithmetic. <span '
          'class="voice">Others say</span> verdict: read the map at '
          'scale &mdash; the unwired regions are not pockets but '
          'continents&rsquo; worths of humanity, the faith zones hold '
          'billions, and the cold clear water, for all its reach, '
          'runs shallowest exactly where most people live; the '
          'single victory was always the Union&rsquo;s press release, '
          'and the zones are the audit. The first school answers '
          'that audits do not stop tides; the second, that tides do '
          'not vote, and the water, per the recto, is nothing but '
          'votes. The folio files the dispute as the chapter&rsquo;s '
          'live wire and declines to cut it: the map is either the '
          'War&rsquo;s consolation prize or its true score, and the '
          'binding&rsquo;s remaining chapters will keep asking. <span '
          'class="kw">TEYKU</span> &mdash; the street of the Gemara, '
          'walked again at midnight, prices differently, which is '
          'both schools&rsquo; whole point.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the museum, and the score</span>',
 'rubric': 'reality&rsquo;s weather map',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World, '
             'continued &middot; of the zones &middot; the weather as law',
 'title': 'Tractate Aliyah · Folio 62b — The Zones: reality’s weather map',
 'type': 'daf'}
