# Folio 78b - The Wells. Verso of the Life-Blood: Nodes, Tass, and the
# property war, per the wod-llm-wiki quintessence and node pages (M20
# pp.330-331; the Node Background).
FOLIO = {'bottom': '<p><span class="lemma">On the chantry&rsquo;s deed.</span> Give the '
           'party&rsquo;s home a well and the well a history: who held it before, '
           'what the tithe was, which claim was never quite extinguished. A '
           'chantry is a home, a fortress, and a lawsuit in one building, and '
           'the campaign inherits all three the day the players move in.</p>\n'
           '        <p><span class="lemma">On scarcity as engine.</span> The '
           'books make the wells few and the age drier than the old days, and '
           'the counsel is to keep them so: essence scarcity is the '
           'setting&rsquo;s cleanest campaign engine &mdash; every faction needs '
           'the same wells, every alliance prices them in, and a chronicle '
           'never lacks a plot while two parties want one spring. Abundance is '
           'the one house rule this folio begs against.</p>\n'
           '        <p><span class="lemma">On paying the tithe '
           'onscreen.</span> If the party holds a well under a greater house, '
           'play the tithe as scenes, not subtraction: the collector&rsquo;s '
           'visit, the short season argued down, the year the crop failed. '
           'Feudal economics is drama precisely because it is personal, and '
           'the folio&rsquo;s whole point is that essence never stopped being '
           'personal.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on deeds, droughts, and '
                'collectors</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The blood wells up in places,</span> and the '
           'law calls them <span class="term">Nodes</span>: springs where '
           'essence rises free, rated by their flow, the temporary ones '
           'called wellsprings and the great ones contested for '
           'centuries.<sup>a</sup> The spring&rsquo;s yield congeals: <span '
           'class="term">Tass</span> is essence embodied &mdash; the '
           'grove&rsquo;s berries, the well&rsquo;s water, the stone that '
           'hums &mdash; carriable, storable, spendable, and therefore '
           'tradable, with everything the last word drags behind '
           'it.<sup>b</sup> Around the wells the setting&rsquo;s property law '
           'grew by custom, never by statute: the chantry built on its '
           'spring, holding by occupation and defense; the tithe paid '
           'upward by lesser holders to greater houses; the trespass '
           'priced in duels, suits, and wars &mdash; for a well can be '
           'held, and whatever can be held will be.<sup>c</sup> And the age '
           'is drier than the old days: the springs are fewer, the great '
           'ones spoken for, and the drought is load-bearing &mdash; the '
           'scarcity of the blood is the quiet engine under half the '
           'setting&rsquo;s politics, and the books built it so on '
           'purpose.<sup>d</sup> So the wells&rsquo; law runs: the blood rises '
           'free and is held fast, the holding is custom armed, and '
           'every deed in the setting is a claim about people pinned '
           'to a spring that signs nothing &mdash; the folio&rsquo;s whole '
           'dispute in a sentence of hydrology.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD the case of the taken well. A small house '
           'held a spring three generations, by the custom: they found it, '
           'they fenced it, they defended it twice. A greater house '
           'arrived with a deed of another kind &mdash; precedence, '
           'lineage, a charter from a convocation the small house had '
           'never attended &mdash; and took the spring without a working '
           'cast, by the arithmetic of allies alone. The elders of the '
           'small house appealed to every court the setting keeps: the '
           'seat said the matter was internal, the convocation said it '
           'was local, and the well, consulted, kept flowing for its new '
           'holders exactly as it had for its old, which the small '
           'house&rsquo;s youngest called the only honest verdict '
           'returned. The disputants around this text hold whether a '
           'well can be owned at all, and what the coin does to the '
           'blood.</p>',
 'chapter': 'Chapter the Third &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Life-Blood: the recto keeps the blood, this side '
             'keeps the wells and their wars.',
 'folio': '78B',
 'glossL': '<p><span class="mark">a</span> On Nodes as the springs of '
           'essence, their rated flow, and the temporary wellsprings, see '
           'M20, folios 330&ndash;331, with the Node background&rsquo;s own '
           'entry in the sixth chapter.</p>\n'
           '        <p><span class="mark">b</span> On Tass &mdash; essence '
           'congealed to carriable form &mdash; see folio 330.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'property law of custom &mdash; occupation, tithe, and trespass '
           '&mdash; the books legislate little and the chronicles much; '
           'this folio derives the custom from the standing arrangements of the covenant houses and their wells, M20, folios 77&ndash;79 and 318&ndash;320.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'drier age and the scarcity&rsquo;s design weight, see the '
           'World chapter, folios 78&ndash;79, whence this page takes its '
           'number.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto meters the blood; '
           'this side deeds it. Read the two against 2a&rsquo;s convocation '
           'and the chantry politics of every chapter V folio: the '
           'setting&rsquo;s institutions are, at the foundation, '
           'water-rights districts wearing philosophy.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'Union runs the same hydrology under requisition forms: the '
           'wanderers of 194 owe the Union its essence supply, and the '
           'Syndicate&rsquo;s Utility at 192 is this folio&rsquo;s coin '
           'question answered with a straight face and a prospectus.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'well&rsquo;s indifference in the Gemara &mdash; flowing for '
           'whoever holds it &mdash; is the folio&rsquo;s quiet horror and '
           'quiet hope at once; the groves that choose their keepers '
           'belong to 162a&rsquo;s garden, and the exceptions are argued '
           'there.</p>',
 'h1': 'The Wells',
 'hagahah': 'The commons is what everyone calls the well before they hold it; '
            'the deed is what they call the fence after. The well itself '
            'calls nothing anything, and flows.',
 'inner': '<p><span class="lemma">Rated by their flow.</span> The '
          'spring clause&rsquo;s plain sense: a Node is measured in what it '
          'yields by the turn and scene, purchased at creation through '
          'the background that bears its name, and shared &mdash; the '
          'books&rsquo; own arrangements assume group holdings, the '
          'cabal&rsquo;s dots pooled on one spring. The wellspring '
          'clause keeps the map honest: essence also rises briefly, at '
          'the crossing-days and the charged hours, and the mage who '
          'knows the temporary springs drinks free where the great '
          'houses pay. The shared holding is also the law&rsquo;s quiet '
          'social engineering: a spring pooled among a cabal binds the '
          'cabal as no oath does, for the dots are communal and the '
          'thirst is not. A shared spring is the setting&rsquo;s marriage '
          'contract, and the chantry disputes of every chapter are '
          'its divorces. Property and kinship, one clause.</p>\n'
          '        <p><span class="lemma">And therefore tradable.</span> '
          'The Tass clause&rsquo;s plain sense: congealed essence is '
          'portable grace, and portability is the whole clause &mdash; '
          'Tass stores against drought, travels to the working&rsquo;s '
          'site, and changes hands; the moment it changes hands it is '
          'coin, and the setting&rsquo;s tithe-economies, gray markets, '
          'and favors-denominated-in-berries all follow from the one '
          'word. The margin holds what the coinage costs; the plain '
          'sense only notes that the books never legislated a currency '
          '&mdash; the mages made one, as holders always do.</p>\n'
          '        <p><span class="lemma">By custom, never by '
          'statute.</span> The property clause&rsquo;s plain sense: no '
          'folio of the books hands down a law of Node ownership, and '
          'the silence is the law &mdash; holding runs by occupation, '
          'defense, and the recognition of neighbors, which is to say '
          'by the oldest property regime there is. The tithe formalizes '
          'the hierarchy: lesser holders buy peace from greater '
          'houses in yield, and the arrangement is feudal without '
          'apology, for feudalism is what property law looks like '
          'where no sovereign holds the monopoly on force &mdash; and '
          'no sovereign does.</p>\n'
          '        <p><span class="lemma">The drought is '
          'load-bearing.</span> The scarcity clause&rsquo;s plain sense: '
          'the drier age is design, not accident &mdash; scarce essence '
          'prices every alliance, feuds every border, and gives the '
          'setting&rsquo;s conflicts a material floor beneath the '
          'philosophy. The counsel below defends the drought at the '
          'table; the plain sense defends it in the text: a setting '
          'where grace ran free would be a setting where the War of '
          '46b had nothing to hold, and the books chose the harder, '
          'truer hydrology.</p>\n'
          '        <p><span class="lemma">Flowing for its new holders '
          'exactly as for its old.</span> The Gemara&rsquo;s law, made '
          'plain: the wells are indifferent to title &mdash; essence '
          'rises for the holder, not the heir, and no custom yet '
          'devised makes a spring recognize a deed. The indifference '
          'cuts every way at once: it makes theft profitable, defense '
          'necessary, and every claim of rightful holding &mdash; the '
          'small house&rsquo;s and the great one&rsquo;s alike &mdash; a '
          'claim about people, enforceable only on people. The wells '
          'never joined the argument, which is why the argument '
          'never ends.</p>',
 'inner_head': 'On the Springs<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; flow, coin, custom, and '
               'drought</span>',
 'name': 'The Wells',
 'outer': '<p><span class="lemma">Whether a well can be owned.</span> The '
          'commons dispute. <span class="voice">Some say</span> the '
          'commons: essence is the world&rsquo;s blood, risen free, owed '
          'to whoever thirsts &mdash; the wells predate every claimant, '
          'the claims are fences around a gift, and every creed in '
          'chapter V says so at the altar while its chantry says '
          'otherwise at the gate. Property in grace is the original '
          'category error, and the setting&rsquo;s well-wars are the '
          'error compounding at interest. <span class="voice">Others '
          'say</span> the title: the commons reading is beautiful and '
          'has never once kept a spring &mdash; the unheld well is not '
          'shared, it is taken, by the first party with the arithmetic '
          'of allies, and the custom of occupation-and-defense is not '
          'greed but stewardship&rsquo;s only working form; the small '
          'house of the Gemara held its spring three generations '
          'precisely because it fenced it. The schools trade the '
          'Gemara&rsquo;s case like a relic: the first reads the '
          'taking as the title system working as designed &mdash; the '
          'strong eat &mdash; and the second reads it as the title '
          'system failing for want of a court, which is an argument '
          'for more law, not less. The folio notes what neither '
          'school can explain away: the well&rsquo;s own indifference, '
          'which funds both readings and endorses neither. <span '
          'class="kw">TEYKU</span> &mdash; and the spring, meanwhile, '
          'is held.</p>\n'
          '        <p><span class="lemma">What the coin does to the '
          'blood.</span> The Tass dispute, the recto&rsquo;s double '
          'ledger gone liquid. <span class="voice">Some say</span> '
          'coinage corrupts absolutely: grace denominated is grace '
          'commodified &mdash; the tithe-economy turns springs into '
          'rents, berries into balance sheets, and the mystic&rsquo;s '
          'relationship with the world&rsquo;s blood into a supply '
          'chain; the Syndicate did not profane the setting&rsquo;s '
          'sacrament, the setting&rsquo;s own markets did, and 192a '
          'merely said it aloud. <span class="voice">Others say</span> '
          'the coin is circulation: Tass travels &mdash; from the '
          'grove that has to the healer who needs, across the '
          'drought, ahead of the working &mdash; and a sacrament that '
          'cannot move is a sacrament for whoever lives beside the '
          'spring and no one else; the trade the first school '
          'mourns is the only mechanism the setting has for grace '
          'reaching the graceless. The folio files the dispute '
          'beside its recto twin and closes the leaf with the '
          'chapter&rsquo;s recurring verdict: the blood is holy, the '
          'blood is money, the setting prints both books &mdash; and '
          'the mage who can read only one of them is dangerous in '
          'either direction. And the leaf&rsquo;s last word goes to the '
          'drought: scarce grace is the one policy neither school '
          'would repeal if it could, for the commons reading needs '
          'scarcity to make sharing mean anything, and the title '
          'reading needs it to make holding worth the fence &mdash; '
          'the setting&rsquo;s dryness is the argument&rsquo;s water '
          'supply, and both sides drink from it. The chapter&rsquo;s '
          'last folio waits at the wall the wells thin, and the '
          'reader is sent there with the deed question unsettled, '
          'as the binding intends.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the fence, and the coin</span>',
 'rubric': 'nodes, tass, and the property war',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World, '
             'continued &middot; of the wells &middot; the springs as law',
 'title': 'Tractate Aliyah · Folio 78b — The Wells: nodes, tass, and the property war',
 'type': 'daf'}
