# Folio 78a - The Life-Blood. Chapter III's fuel, per the wod-llm-wiki
# quintessence page (M20 pp.330-333).
FOLIO = {'bottom': '<p><span class="lemma">On the Wheel in view.</span> Track the Wheel where '
           'the table can see it: essence filling one way, the fee filling the '
           'other, the collision visible turns in advance. The single dial that '
           'holds a mage&rsquo;s grace and her debt in one circle is the '
           'line&rsquo;s best piece of instrumentation, and hiding it behind the '
           'screen wastes the dread it was built to generate.</p>\n'
           '        <p><span class="lemma">On essence as scene fuel.</span> '
           'Essence spent should be essence seen: the discount is mechanical but '
           'the spending is theater &mdash; the ring warming, the coffee '
           'sanctified, the last of the node-water drunk. A resource narrated at '
           'every spend stays precious; one subtracted silently becomes '
           'ammunition, and the folio&rsquo;s whole subject is that it is not '
           'ammunition.</p>\n'
           '        <p><span class="lemma">On the visible threshold.</span> The '
           'clause that makes bulk essence-work glow &mdash; lights dimming at a '
           'few points, the flow going visible past ten &mdash; is a scene cue '
           'printed as physics: big Prime is always an event. Stage it as one, '
           'every time, and players will plan around the glow the way the '
           'clause intends.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on dials, theater, and '
                'the glow</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The world runs on a fifth essence,</span> and '
           'the law calls it <span class="term">Quintessence</span>: the raw '
           'stuff of creation, the Prime energy beneath every pattern, which a '
           'mage may hold, channel, and spend.<sup>a</sup> Its bookkeeping is '
           'the Avatar&rsquo;s: the spark&rsquo;s rating caps the free essence '
           'a mage carries and meters what she may draw or spend in a turn '
           '&mdash; the pipe&rsquo;s gauge, as chapter II already ruled. Spent, '
           'it eases the caster&rsquo;s wall a step per point, three at the '
           'most, and fuels the workings that demand raw Prime; committed, it '
           'binds into standing works and wonders and is free no '
           'more.<sup>b</sup> Its motion shows: a few points moving dim the '
           'lamps and stir the air, and past ten the flow goes visible to '
           'sleeping eyes &mdash; and visibly impossible, billing at the '
           'vulgar rate always.<sup>c</sup> And its ledger shares a dial with '
           'the court&rsquo;s: essence and Paradox fill one Wheel from '
           'opposite ends, the fee cancels the essence where they meet and '
           'never the reverse, and the mage whose debt has reached her grace '
           'absorbs no more until the court is paid &mdash; the '
           'binding&rsquo;s whole moral arithmetic drawn as one '
           'circle.<sup>d</sup> So the blood&rsquo;s law runs: grace is real, '
           'metered, and mortgaged before it is spent &mdash; and the '
           'mage who reads her own dial daily is not anxious but '
           'literate.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear what the names confess. The philosophers called '
           'it the fifth essence, after the four that make the world: the '
           'quintessence is what the elements are made of when you ask one '
           'more time. The witches call it the life-blood; the '
           'Union&rsquo;s ledgers call it Primal Energy and the '
           'Syndicate&rsquo;s call it Utility, and 520a has already heard '
           'that argument. What every name agrees on is the direction of '
           'flow: it is drawn from wells, carried in vessels, spent in '
           'work, and wanted always &mdash; the one substance in the '
           'setting that every faction, seat, and creed treats as money '
           'while insisting it is holy, or as holy while spending it '
           'like money. The disputants around this text hold that double '
           'ledger, and the Wheel&rsquo;s crooked seesaw.</p>',
 'chapter': 'Chapter the Third &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the chapter&rsquo;s life-blood; its wells and their property law '
             'wait overleaf.',
 'folio': '78A',
 'glossL': '<p><span class="mark">a</span> On Quintessence as the raw stuff '
           '&mdash; Prime energy held in the pattern &mdash; see M20, folio '
           '330; the page number this folio wears is the World '
           'chapter&rsquo;s, folios 78&ndash;79, where the life-blood is '
           'introduced.</p>\n'
           '        <p><span class="mark">b</span> On the Avatar&rsquo;s cap '
           'and meter, the step-per-point easing to three, and free against '
           'committed essence, see folios 330&ndash;331.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'dimming at a few points and the visible &mdash; and always '
           'vulgar &mdash; flow past ten, see folio 331.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'Wheel &mdash; the shared dial, the one-way cancellation, and '
           'the absorption stopped where debt meets grace &mdash; see '
           'folios 331&ndash;333.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The essence this folio '
           'meters is 520a&rsquo;s whole Sphere seen as a substance, and '
           'the spending clause is 500a&rsquo;s modifier catalogue&rsquo;s '
           'biggest line item; the seder of 250a prices the starting '
           'pool. Three engines, one fuel.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'Wheel&rsquo;s crooked seesaw is 533a&rsquo;s court holding the '
           'pen on this folio&rsquo;s ledger: the fee that cancels grace '
           'is the binding&rsquo;s tersest theology, and the recto of '
           'Quiet has already shown where the overdraft leads.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'wells, the congealed coin, and the property war over both '
           'are overleaf; the Masoret notes only that every chantry '
           'folio since 2a has been, among other things, a deed.</p>',
 'h1': 'The Life-Blood',
 'hagahah': 'Every tradition condemns hoarding Quintessence; every chantry '
            'hoards it. The word for this is not hypocrisy but liquidity, '
            'which is worse.',
 'inner': '<p><span class="lemma">The raw stuff of creation.</span> The '
          'definition&rsquo;s plain sense: essence is not a kind of energy '
          'among others but the substrate &mdash; what patterns are woven '
          'from, what the Prime art of 520a perceives directly &mdash; and '
          'its game presence is a pool of points because the engine must '
          'count something; the counted thing is grace made fungible, '
          'and the folio&rsquo;s disputes all grow from that '
          'made.</p>\n'
          '        <p><span class="lemma">Free against committed.</span> '
          'The ledger clause&rsquo;s plain sense, expanded for the '
          'sheet&rsquo;s sake: free essence floats in the pattern, ready '
          'to spend and capped by the spark; committed essence is '
          'invested &mdash; bound into the standing ward, the charged '
          'wonder, the reinforced flesh &mdash; and returns only when '
          'the work ends. The division is the setting&rsquo;s whole '
          'theory of wealth in miniature: liquidity against '
          'investment, and the wise mage, like the wise house, holds '
          'both books balanced. The committed ledger also prices ambition '
          'honestly: the great standing works of the setting are '
          'fortunes sunk, and the house that wards a mountain has '
          'spent a mountain&rsquo;s worth of grace to do it.</p>\n'
          '        <p><span class="lemma">The pipe&rsquo;s gauge.</span> '
          'The bookkeeping clause&rsquo;s plain sense: the Avatar rates '
          'the connection, so the spark&rsquo;s dots cap the free pool '
          'and meter the turn&rsquo;s flow &mdash; deep-souled mages are '
          'wide pipes &mdash; and the committed ledger runs separately: '
          'essence bound into wonders and standing works is spent '
          'grace, drawing no interest and paying no walls until '
          'released. The division keeps the economy honest: the '
          'miser&rsquo;s hoard and the builder&rsquo;s investment are '
          'different virtues, and the sheet tracks them apart.</p>\n'
          '        <p><span class="lemma">A step per point, three at '
          'the most.</span> The spending clause&rsquo;s plain sense: '
          'essence eases the caster&rsquo;s wall inside the same net '
          'cap that governs every discount in 500a&rsquo;s catalogue '
          '&mdash; the fuel is potent and the ceiling is civic &mdash; '
          'and the turn meter binds the spend to the Avatar&rsquo;s '
          'gauge, so the deep spender is the deep-souled, not the '
          'merely rich. The design keeps essence from becoming pure '
          'ammunition: it rewards depth over stockpile at every '
          'valve.</p>\n'
          '        <p><span class="lemma">Visible, and visibly '
          'impossible.</span> The threshold clause&rsquo;s plain sense: '
          'bulk essence-work announces itself &mdash; the dimming lamps '
          'at small flows, the naked-eye glow past ten points &mdash; '
          'and the announcement is priced: the visible flow is vulgar '
          'always, whatever the theater, for no street believes in '
          'light that pours. The clause is the folio&rsquo;s bridge to '
          '62a: even the world&rsquo;s own blood must respect the '
          'water it moves through.</p>\n'
          '        <p><span class="lemma">Never the reverse.</span> The '
          'Wheel&rsquo;s plain sense, and the chapter&rsquo;s sternest '
          'arithmetic: the fee cancels the essence where the two '
          'meet, grace never cancels debt, and the mage whose Paradox '
          'has reached her Quintessence stops absorbing entirely '
          '&mdash; the pipe closed by the court&rsquo;s lien. The '
          'asymmetry is deliberate and the margin disputes its '
          'justice; the plain sense only records the mechanism: in '
          'this binding, debt is prior to grace, and the dial says '
          'so every time it turns.</p>',
 'inner_head': 'On the Blood<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the gauge, the valves, and the '
               'dial</span>',
 'name': 'The Life-Blood',
 'outer': '<p><span class="lemma">The double ledger.</span> The '
          'sacrament-or-fuel dispute, which the Gemara&rsquo;s census of '
          'names opens. <span class="voice">Some say</span> the '
          'arithmetic profanes: grace metered in points, spent for '
          'discounts, capped by rating, is grace made gasoline &mdash; '
          'and the setting&rsquo;s own mystics say so in every seat&rsquo;s '
          'scripture, condemning the hoard, the tithe-economy, the '
          'well run as a utility. A sacrament with an exchange rate is '
          'a commodity wearing vestments. <span class="voice">Others '
          'say</span> the meter is the reverence: the books count '
          'essence because essence is the one thing the setting '
          'refuses to make infinite &mdash; scarcity is how a game '
          'says sacred &mdash; and the mystic who spends her last '
          'point on a stranger&rsquo;s healing has performed a devotion '
          'that no unmetered resource could carry. The schools meet '
          'at the hagahah&rsquo;s bitter joke: every creed condemns '
          'the hoard, every chantry keeps one, and the folio files '
          'the contradiction not as hypocrisy but as the double '
          'ledger every real sacredness runs &mdash; the church has '
          'always had both a tabernacle and a treasury, and the '
          'setting is honest enough to print the treasury&rsquo;s '
          'books. <span class="kw">TEYKU</span> &mdash; the essence, '
          'spent either way, spends.</p>\n'
          '        <p><span class="lemma">The crooked seesaw.</span> '
          'The Wheel dispute. <span class="voice">Some say</span> the '
          'one-way cancellation is the court&rsquo;s thumb on the '
          'scale, indefensible in equity: the mage&rsquo;s grace '
          'cannot retire her debt, but her debt confiscates her '
          'grace &mdash; a lien senior to everything, held by a court '
          'nobody elected, and the dial&rsquo;s geometry teaches '
          'every player that the house wins. <span '
          'class="voice">Others say</span> the asymmetry is the '
          'setting&rsquo;s deepest sentence about consequence: grace '
          'is renewable and debt is real &mdash; a world where '
          'holiness could simply buy off backlash would be a world '
          'where the rich sin freely, and the Wheel&rsquo;s crooked '
          'seesaw is the one mechanism in the binding that cannot '
          'be gamed by accumulation. The first school answers that '
          'this is a sermon printed as a rule; the second answers '
          'that every rule is, and points at the whole shelf. The '
          'folio notes where both schools stand together: on the '
          'dial&rsquo;s far side, where debt has eaten grace '
          'entirely, sits the country of 554a &mdash; and neither '
          'school has ever proposed to move it. For the Wheel&rsquo;s '
          'geometry, both schools concede, is also the binding&rsquo;s '
          'kindest warning label: the mage can read her own distance '
          'from the break inward on one dial, daily, which no other '
          'madness in any setting on the shelf has ever offered its '
          'sufferers. Grace and debt on one dial, legible daily: the '
          'schools file the design under mercy, jointly, and move '
          'on before the agreement embarrasses them. For the dial&rsquo;s '
          'deepest kindness is the one the whole chapter turns on: in '
          'a setting of unpriced mysteries, the two numbers that '
          'matter most are posted where their owner can read them, '
          'every day, in her own pattern&rsquo;s hand &mdash; grace and '
          'debt made legible, which is the closest the binding comes '
          'to promising that the moral life can be navigated at '
          'all.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the ledger, and the seesaw</span>',
 'rubric': 'the fifth essence, and its wheel',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World, '
             'continued &middot; of the life-blood &middot; the essence as law',
 'title': 'Tractate Aliyah · Folio 78a — The Life-Blood: the fifth essence, and its wheel',
 'type': 'daf'}
