# Folio 82b - The Crossing. Verso of the Gauntlet: passages, roads, and
# the between, per the wod-llm-wiki gauntlet page (M20 pp.82-83,
# 474-475, 484).
FOLIO = {'bottom': '<p><span class="lemma">On the first crossing.</span> A party&rsquo;s '
           'first passage deserves a whole session: the preparation, the wall '
           'read and argued, the gathering rolls staged as ordeal, and the far '
           'side&rsquo;s first breath held until everyone is through. Every '
           'later crossing can compress; the first one is the campaign '
           'learning that the world has a basement and an attic, and '
           'learning should take an evening.</p>\n'
           '        <p><span class="lemma">On doors as politics.</span> Every '
           'standing portal and thin place has a keeper, a custom, and a fee '
           '&mdash; treat the doors as the borders they are. A chronicle&rsquo;s '
           'crossing map is also its diplomatic map, and the party that '
           'antagonizes a door&rsquo;s keeper learns what commuting meant '
           'before trains.</p>\n'
           '        <p><span class="lemma">On the storm as memory.</span> The '
           'storm season is over in the baseline and recent in every '
           'elder&rsquo;s memory: use it as scar tissue &mdash; the crossing '
           'generation that would not cross, the realms cut off and only '
           'lately answering &mdash; and the geography gains a history the '
           'players can interview. A wall that was once lethal is more '
           'interesting than a wall that is merely high.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on first passages, '
                'doors, and scars</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The wall has doors, and the doors have '
           'law.</span> Four passages the books grade. The <span '
           'class="term">labor</span>: the extended working of the recto, '
           'will against the local wall, open to any walker with the '
           'crossing art. The <span class="term">portal</span>: the standing '
           'door, cut once and kept, with a keeper and a custom at every one '
           'worth the name. The <span class="term">thin place</span>: the '
           'shallowing where the worlds lean together and the wall forgets '
           'itself &mdash; found, not made, and mapped jealously. And the '
           '<span class="term">old roads</span>: the ways of the first '
           'witches, walked before the wall was high, remembering routes '
           'the present geography denies.<sup>a</sup> The Union crosses by '
           'its own filing &mdash; dimensional science, the art of 521a in a '
           'clean suit &mdash; and its laboratories stand as nodes to their '
           'own crossings: the rampart keeps a staff door.<sup>b</sup> The '
           'between is a place: the botched crossing strands its walker in '
           'the membrane, rescued only by skilled hands, and in the storm '
           'season the stranding shredded body and spark &mdash; the books '
           'keep the season&rsquo;s name and its calming, and the walls '
           'stand thicker for it.<sup>c</sup> And the crossing&rsquo;s '
           'oldest law is courtesy: the far side is a country, not a '
           'basement &mdash; entered as guests enter, or answered as '
           'trespassers are.<sup>d</sup> So the doors&rsquo; law runs: four '
           'passages, four prices, one etiquette &mdash; and the chapter '
           'closes where the world does, at a threshold with the '
           'binding&rsquo;s standing counsel carved over it: knock '
           'first.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD one crossing, complete. The walker read the '
           'wall at dusk &mdash; countryside, the middle bands &mdash; and '
           'paid the preparation: the fast, the threshold-song, the salt. '
           'The labor took the evening; the wall gave by inches; and at '
           'the last gathered success the world went thin as paper held '
           'to light, and she stepped through the page. On the far side '
           'the same meadow waited, wearing its true colors, and '
           'something with her grandmother&rsquo;s patience and nobody&rsquo;s '
           'face asked her business as if the question were a toll. She '
           'answered honestly, which is the toll. The disputants around '
           'this text hold who the wall is for, and what lives in the '
           'between.</p>',
 'chapter': 'Chapter the Third &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Gauntlet, and the chapter&rsquo;s last leaf: the '
             'water, its weather, its blood, its wells, its wall &mdash; and '
             'the doors through.',
 'folio': '82B',
 'glossL': '<p><span class="mark">a</span> On the four passages &mdash; the '
           'extended labor, the portals, the shallowings, and the old roads '
           'of the Wyck &mdash; see M20, folios 474&ndash;475.</p>\n'
           '        <p><span class="mark">b</span> On dimensional science '
           'as the Union&rsquo;s crossing and the laboratory counted as a '
           'node for it, see the traveling chart&rsquo;s footnote, folio '
           '484.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'stranding, the rescue by skilled hands, and the storm '
           'season&rsquo;s lethal passages and thicker aftermath, see '
           'folios 82&ndash;83 and 474&ndash;475.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the courtesy of the far country &mdash; the guest-law of spirits, their tolls and bargains &mdash; see M20, the Spirit entries at folios 520&ndash;521, and Umbra: the Velvet Shadow, folios 20&ndash;21 of that volume; the ladder of dealings is bound at folio 521a.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This leaf closes the '
           'chapter&rsquo;s circuit: the water of 62a sets the wall of 82a, '
           'the wells of 78b thin it, and the doors of this side open on '
           'the countries of chapter IV, folios 89 through 109. The World is one argument in six pages, and the Masoret binds them as such.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'keeper at every portal is 521a&rsquo;s bargain law standing in '
           'a doorway, and the guest-or-trespasser clause is the '
           'Dreamspeakers&rsquo; whole seat at 154a stated as border '
           'control; the two folios have expected this page since '
           'chapter V.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'old roads&rsquo; first witches are the Wyck of the deep '
           'histories, 2a&rsquo;s margins and the garden&rsquo;s ancestors '
           'at 162a; that their roads predate the wall is the nature '
           'dispute of the recto carrying luggage.</p>',
 'h1': 'The Crossing',
 'hagahah': 'Every door in the wall has a keeper, including the ones nobody '
            'keeps: those are kept by whatever decided to look like an '
            'empty door, and the old roads teach you to knock anyway.',
 'inner': '<p><span class="lemma">Doors have law.</span> The passages&rsquo; '
          'plain sense, graded: the labor is universal and expensive; the '
          'portal is cheap and political, for the standing door '
          'outlives its cutter and accumulates a keeper, a custom, and a '
          'queue; the thin place is free and jealously mapped, the '
          'crossing world&rsquo;s equivalent of a spring; and the old '
          'roads are the deep option &mdash; ways that remember an easier '
          'geography, walked by lineages that keep the walking secret. '
          'The four prices sort every crossing story the setting '
          'tells.</p>\n'
          '        <p><span class="lemma">A staff door in the '
          'rampart.</span> The Union clause&rsquo;s plain sense, priced as '
          'the margin promised: the laboratory&rsquo;s wall stands '
          'highest on the chart against strangers and lowest against '
          'its own dimensional science &mdash; the thickest rampart in '
          'the world, with a keycard reader. The asymmetry is the '
          'whole Union in one architectural detail: the border sealed '
          'for everyone is a border held by someone, and 194a&rsquo;s '
          'patrol walks out through the door it denies exists.</p>\n'
          '        <p><span class="lemma">The between is a place.</span> '
          'The stranding clause&rsquo;s plain sense: the membrane has an '
          'inside &mdash; the botched walker is somewhere, helpless and '
          'housed, until skilled hands reach in &mdash; and the storm '
          'season proved the somewhere could hold weather. The law '
          'declines to inventory the between&rsquo;s residents, which '
          'the margin reads as discretion and the counsel reads as an '
          'adventure seed; the plain sense notes only that a place '
          'that can strand can be searched, and the rescue craft is '
          'real, teachable, and honored everywhere.</p>\n'
          '        <p><span class="lemma">Thicker for it.</span> The '
          'storm clause&rsquo;s plain sense: the season of shredding '
          'wind is past in the baseline &mdash; the passages survivable '
          'again &mdash; and its monument is the masonry: walls thicker '
          'than the elder books remember, crossings dearer than the '
          'old lineages trained for. The scar is load-bearing '
          'history: a whole generation&rsquo;s crossing craft withered '
          'in the storm years, and the present age&rsquo;s thin '
          'expertise is the setting&rsquo;s quiet explanation for why '
          'the far countries feel newly far.</p>\n'
          '        <p><span class="lemma">Entered as guests '
          'enter.</span> The courtesy clause&rsquo;s plain sense, and the '
          'chapter&rsquo;s closing manners: the far side is inhabited, '
          'the inhabitants hold their own law, and the crossing that '
          'ends well is the one that arrives as a guest &mdash; named, '
          'announced, toll paid in honesty as the Gemara&rsquo;s walker '
          'paid it. The clause is not flavor but survival doctrine, '
          'and 521a&rsquo;s whole ladder of bargains stands on it: the '
          'wall&rsquo;s law ends at the wall, and past it the law is '
          'theirs.</p>\n'
          '        <p><span class="lemma">Found, not made.</span> The '
          'thin place&rsquo;s plain sense, held apart from the portal on '
          'purpose: the shallowing is the world&rsquo;s own gesture '
          '&mdash; the worlds leaning together where the old weather '
          'holds &mdash; and it can be found, mapped, guarded, and lost, '
          'but never manufactured. The distinction prices the '
          'setting&rsquo;s cartography: portals are property, '
          'shallowings are secrets, and the lineages that hold the '
          'maps hold something no working can mint.</p>',
 'inner_head': 'On the Doors<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; passages, prices, and '
               'manners</span>',
 'name': 'The Crossing',
 'outer': '<p><span class="lemma">Who the wall is for.</span> The '
          'protection dispute, the recto&rsquo;s symmetry clause pressed. '
          '<span class="voice">Some say</span> the wall protects the '
          'flesh: the far countries hold the devouring things, the '
          'storm proved the passages can kill, and a membrane that '
          'keeps the banes from the nursery is a mercy whoever grew or '
          'built it &mdash; the Union&rsquo;s thickening, on this '
          'reading, is crude but not wrong. <span class="voice">Others '
          'say</span> the wall imprisons both houses: it bars the '
          'spirits from the flesh that dreamed them and the dreamers '
          'from the country of their dreams &mdash; a partition running '
          'through one being, and every folio of thinning sacred '
          'places testifies which side of the family keeps trying to '
          'visit. The first school asks who, then, should decide the '
          'wall&rsquo;s height; the second answers: the neighbors, '
          'jointly, which is what the thin places and the old roads '
          'already are &mdash; negotiated openings in a wall neither '
          'house voted for. The folio files the dispute where the '
          'chapter files everything: the wall is made of disbelief, '
          'disbelief is votes, and the franchise question &mdash; who '
          'votes on the border between worlds &mdash; is chapter '
          'IV&rsquo;s to inherit and the binding&rsquo;s to keep '
          'asking. <span class="kw">TEYKU</span> &mdash; the '
          'grandmother-patient thing at the toll declined to say '
          'which side it was protecting.</p>\n'
          '        <p><span class="lemma">What lives in the '
          'between.</span> The membrane dispute, quieter and stranger. '
          '<span class="voice">Some say</span> nothing: the between is '
          'a thickness, not a territory &mdash; the stranded '
          'walker&rsquo;s dread is suffocation, not neighbors, and the '
          'storm&rsquo;s horrors were weather, not residents; the law '
          'inventories no inhabitants because there are none to '
          'inventory. <span class="voice">Others say</span> the '
          'law&rsquo;s silence is a curtain: things met in the '
          'membrane appear in testimony from every crossing lineage '
          '&mdash; the shapes in the thickness, the guides that ask no '
          'toll and should &mdash; and a place that can hold a '
          'stranded soul for days is a place, with a place&rsquo;s '
          'prerogatives. The schools agree the question is '
          'empirical and agree nobody sane runs the experiment; the '
          'stranded, rescued, report dreams they decline to repeat, '
          'and the rescuers, asked what they saw on the way in, '
          'develop the crossing trade&rsquo;s famous deafness. The '
          'folio closes the chapter with the binding&rsquo;s oldest '
          'move: the question filed open, the door marked knock '
          'first, and the atlas of what answers left, deliberately, '
          'to the next chapter&rsquo;s folios. And the chapter&rsquo;s '
          'last courtesy is the reader&rsquo;s: three folios of water, '
          'blood, and wall have built the world the first three '
          'chapters of workings assumed &mdash; the binding&rsquo;s '
          'foundations poured after its towers, in the '
          'printers&rsquo; own strange order, and holding. Whatever '
          'lives in the between, the binding now stands on both '
          'sides of it, and the chapters that follow stand bound, countries with their doors already hung. The chapter&rsquo;s six sides close as one folio of the World, which is what the Masoret promised at its first margin, and the binding keeps its '
          'promises in geometry when it cannot in law.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the beneficiary, and the '
               'resident</span>',
 'rubric': 'the doors, the roads, and the between',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World, '
             'concluded &middot; of the crossing &middot; the doors as law',
 'title': 'Tractate Aliyah · Folio 82b — The Crossing: the doors, the roads, and the between',
 'type': 'daf'}
