# Folio 82a - The Gauntlet. Chapter III's veil, per the wod-llm-wiki
# gauntlet page (M20 pp.82-83, 474-475, 484).
FOLIO = {'bottom': '<p><span class="lemma">On the veil as scene transition.</span> The '
           'crossing is the line&rsquo;s best act break: treat every passage as a '
           'threshold scene &mdash; the world thinning, the light going wrong, '
           'the first breath of the other country &mdash; and never as a door '
           'opened in a sentence. A table that feels the membrane respects the '
           'geography, and the geography is half the setting.</p>\n'
           '        <p><span class="lemma">On the local reading.</span> Rate '
           'the chronicle&rsquo;s own places once and keep the ratings: the '
           'players&rsquo; node, their downtown, the wilderness they can reach '
           'by dawn. The veil&rsquo;s thickness is a map the party will learn '
           'by trying, and consistency is what makes their learning '
           'strategy rather than luck.</p>\n'
           '        <p><span class="lemma">On stranding with intent.</span> '
           'The botched crossing that wedges a mage between worlds is a '
           'dreadful and excellent complication: use it seldom, resolve it as '
           'a rescue arc, and remember the books&rsquo; mercy &mdash; another '
           'party skilled at crossing can pull the stranded through. The '
           'between is a place someone must go, which is a session, not a '
           'penalty.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on thresholds, maps, '
                'and rescues</span>',
 'center': '<p class="noindent"><span class="dropcap">H</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Between the flesh and the spirit stands a '
           'skin,</span> and the law calls it the <span '
           'class="term">Gauntlet</span>: the barrier dividing the material '
           'world from the near country of spirit and the countries '
           'beyond.<sup>a</sup> Its thickness is the water&rsquo;s: where '
           'disbelief runs dense the veil runs thick &mdash; the laboratory, '
           'the downtown &mdash; and it thins at the sacred and the wild, '
           'the node, the deep forest, the charged hour; the chart grades '
           'the walls by locale, from the node&rsquo;s low sill to the '
           'lab&rsquo;s high rampart, abridged here to its bands per the '
           'luachs&rsquo; standing rule.<sup>b</sup> Crossing is a working: '
           'an extended labor of the will against the local wall, '
           'gathering successes by the band &mdash; and the botch is the '
           'crossing&rsquo;s own dread, wedging the walker between worlds '
           'until skilled hands pull her through.<sup>c</sup> The veil bars '
           'both ways &mdash; it holds the spirits from the flesh as it '
           'holds the mages from the spirit &mdash; and its history carries '
           'a scar: for a terrible season the storm filled its passages '
           'with soul-shredding wind, and the storm&rsquo;s calming left '
           'the walls thicker than the old books remember '
           'them.<sup>d</sup> So the veil&rsquo;s law runs: one world wearing '
           'a skin, the skin&rsquo;s thickness the neighborhood&rsquo;s '
           'disbelief, and every crossing a negotiation with the '
           'neighbors.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear why there is a wall at all. One telling says the '
           'worlds were a single country once &mdash; the One that shattered '
           'into Infinity &mdash; and the wall is scar tissue where the '
           'break healed badly, fear and dogma holding the halves apart. '
           'Another says the wall was raised on purpose: to keep the dead '
           'from the living, or the devouring things from the fed. And the '
           'accusation every reader expects, the books dismiss with '
           'unusual flatness: the Union did not build it &mdash; the wall '
           'predates their oldest guild &mdash; though they have thickened '
           'it gladly, course by course, wherever their water runs. The '
           'teachers noted what all the tellings share: nobody claims the '
           'wall was always there, and nobody alive remembers the country '
           'without it. The disputants around this text hold the '
           'wall&rsquo;s nature and its number.</p>',
 'chapter': 'Chapter the Third &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the chapter&rsquo;s veil; the crossings and their roads wait '
             'overleaf, and the chapter closes there.',
 'folio': '82A',
 'glossL': '<p><span class="mark">a</span> On the Gauntlet as the skin between '
           'worlds, see M20, folios 82&ndash;83, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On thickness by locale '
           '&mdash; the node&rsquo;s sill, the wilderness, the countryside, '
           'the town, the downtown, the laboratory&rsquo;s rampart &mdash; '
           'see the traveling chart at folio 484, whose grain is the '
           'source&rsquo;s.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'crossing as extended working and the botch&rsquo;s stranding '
           'between worlds, see folios 474&ndash;475.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'two-way bar, the storm season, and the thicker walls after, '
           'see folios 82&ndash;83.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The veil&rsquo;s thickness '
           'tracks 62a&rsquo;s water point for point: where disbelief is '
           'dense the wall is high, and the two folios are one atlas &mdash; '
           'the zones of 62b in a second projection, as the Masoret filed '
           'there in advance.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'art of the crossing is 521a&rsquo;s, and the wanderers of 194 '
           'patrol the far side of this folio&rsquo;s subject; the storm '
           'scar is the same weather their renegade is blamed for, filed '
           'with the end-times, wanting.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'countries beyond the wall are chapter IV&rsquo;s, folios 89 '
           'through 109: this folio builds the door and that chapter keeps the atlas &mdash; the mirror at 89, the deeps at 91, the outer wall at 109. The Masoret marks the door at the threshold.</p>',
 'h1': 'The Gauntlet',
 'hagahah': 'The wall between worlds is measured in how hard the neighbors '
            'disbelieve you. Good fences make sane neighbors, and the '
            'neighbors built the fence.',
 'inner': '<p><span class="lemma">A skin, and not a wall after all.</span> '
          'The definition&rsquo;s plain sense: the books&rsquo; own figure '
          'is a skin &mdash; the layer bitten through to reach the layers '
          'beneath &mdash; and the figure corrects the fortress reading '
          'before it starts: a skin is alive, varies by the body&rsquo;s '
          'place and hour, and belongs to the organism rather than to '
          'any architect. The near country behind it is the '
          'spirit&rsquo;s shallows; the deeps are the far countries, and '
          'chapter IV keeps their atlas.</p>\n'
          '        <p><span class="lemma">Graded by locale.</span> The '
          'chart clause&rsquo;s plain sense, banded per the standing '
          'rule: the node&rsquo;s sill barely resists &mdash; a single '
          'gathered success against a low wall &mdash; the wild and the '
          'countryside rise by steps, the town and downtown by steps '
          'again, and the laboratory&rsquo;s rampart crowns the chart, '
          'wanting the most of both wall and gathering. The '
          'metaplot&rsquo;s season of victory adds its step in the '
          'industrial zones, and the hour moves everything: the chart '
          'itself warns that a garden at noon and an alley on the old '
          'year&rsquo;s night trade places. The grain, as always, is '
          'in the source.</p>\n'
          '        <p><span class="lemma">An extended labor of the '
          'will.</span> The crossing clause&rsquo;s plain sense: passage '
          'is earned in gathered successes against the local wall, '
          'each roll a stretch of focused effort, and the alternatives '
          'the law lists &mdash; the standing portals, the thin places, '
          'the old roads of the first witches &mdash; are doors that '
          'spare the labor where they stand. The Union&rsquo;s '
          'dimensional science runs the same crossing under its own '
          'filing, and its laboratories, by the chart&rsquo;s own '
          'footnote, count as nodes for their crossings &mdash; the '
          'rampart with a staff door, which the margin is invited to '
          'price. The labor&rsquo;s own texture matters at the table: '
          'each roll is minutes of focused effort, interruptible and '
          'felt, so a crossing is a scene by construction and never a '
          'sentence. The bands&rsquo; successes scale with the walls, '
          'so the deep crossing is long as well as hard &mdash; hours at '
          'the rampart, minutes at the sill.</p>\n'
          '        <p><span class="lemma">Wedging the walker '
          'between.</span> The botch clause&rsquo;s plain sense: the '
          'failed crossing&rsquo;s catastrophe is not damage but '
          'suspension &mdash; the walker stuck in the membrane, helpless '
          'until another party with the crossing craft pulls her '
          'through &mdash; and in the storm season the suspension was '
          'torture and sometimes death. The clause builds the '
          'setting&rsquo;s strangest rescue genre, and the counsel '
          'below spends it as such: the between is a place, the '
          'stranded are its only residents, and somebody has to '
          'go.</p>\n'
          '        <p><span class="lemma">Bars both ways.</span> The '
          'symmetry clause&rsquo;s plain sense, easy to read past: the '
          'veil holds the spirits out as it holds the mages in, and '
          'every folio of bargains and bindings downstream &mdash; '
          '521a&rsquo;s whole ladder &mdash; assumes the wall&rsquo;s '
          'symmetry. Whoever the wall serves, it serves at both '
          'faces; whatever it protects, it protects from both '
          'directions; and the margin&rsquo;s first dispute begins '
          'exactly there.</p>',
 'inner_head': 'On the Skin<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the grades, the labor, and the '
               'symmetry</span>',
 'name': 'The Gauntlet',
 'outer': '<p><span class="lemma">Scar or masonry.</span> The nature '
          'dispute. <span class="voice">Some say</span> scar tissue: the '
          'wall is the Consensus&rsquo;s own hide &mdash; grown, not '
          'built, thickening wherever disbelief presses and thinning '
          'wherever the old weather holds, exactly as 62a&rsquo;s water '
          'would predict; no architect is needed where physiology '
          'suffices, and the books&rsquo; flat dismissal of the '
          'Union-built reading is the setting telling its readers to '
          'put the trowel down. <span class="voice">Others say</span> '
          'the dismissal dismisses too fast: grown things can be '
          'gardened &mdash; the Union thickens the wall course by '
          'course, the books concede the masonry in the same breath as '
          'the acquittal, and a wall that predates the mason may still '
          'be the mason&rsquo;s project now; ask who benefits from the '
          'present thickness, and the answer wears a gray suit. The '
          'first school answers that the sacred and the wild thin the '
          'wall daily and no Convention permits it &mdash; the hide '
          'grows as it will. The second answers that this is what '
          'losing a gardening war feels like from the garden. The '
          'folio files the dispute into the atlas it opens: scar or '
          'masonry decides who can be sued for the wall, and chapter '
          'IV&rsquo;s stranded countries are the plaintiffs. <span '
          'class="kw">TEYKU</span> &mdash; the skin, biopsied, is '
          'made of disbelief either way.</p>\n'
          '        <p><span class="lemma">One wall or many.</span> The '
          'number dispute. <span class="voice">Some say</span> one: the '
          'Gauntlet is a single membrane wrapping the world, thick '
          'here and thin there but continuous &mdash; the chart&rsquo;s '
          'grades are one wall&rsquo;s weather, and the crossing '
          'learned anywhere is the crossing learned everywhere. <span '
          'class="voice">Others say</span> many: the grades are '
          'deeper than weather &mdash; each zone&rsquo;s wall is that '
          'zone&rsquo;s own scar, raised by its own disbelief against '
          'its own spirits, and the elder cosmologies count the walls '
          'in pluralities the modern chart flattens; the traveler who '
          'treats the reservation&rsquo;s veil as the '
          'laboratory&rsquo;s with a different number has misread '
          'both. The stakes are a cartographer&rsquo;s: one wall makes '
          'the spirit world a country with a border, many walls make '
          'it an archipelago of neighborhoods &mdash; and the '
          'setting&rsquo;s own sources, the folio notes with a '
          'librarian&rsquo;s patience, have printed both maps in '
          'different decades and reconciled them never. The girsa is '
          'filed unharmonized per the binding&rsquo;s law, and chapter '
          'IV inherits it with the atlas: the first folio past the '
          'wall will have to decide which map it is drawn on. And '
          'both schools sign the practical rider: whichever count '
          'holds, the crossing craft transfers imperfectly between '
          'venues &mdash; the walker who knows her home wall learns a '
          'strange one faster than a stranger but slower than she '
          'expects &mdash; and the chronicle that prices the '
          'difference has made geography into character, which is '
          'this chapter&rsquo;s whole ambition. The atlas&rsquo;s first '
          'question &mdash; one map or many &mdash; thus becomes the '
          'first purchase every traveling chronicle makes, and the '
          'folio commends deciding it aloud.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the mason, and the count</span>',
 'rubric': 'the skin between the worlds',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Third: The World, '
             'continued &middot; of the Gauntlet &middot; the veil as law',
 'title': 'Tractate Aliyah · Folio 82a — The Gauntlet: the skin between the worlds',
 'type': 'daf'}
