# Folio 89b - The Reflection. The Penumbra's verso: domains, webs, and
# meddling, per the wod-llm-wiki penumbra and pattern-web pages (M20
# pp.89-90; W20 Umbra pp.16-29; Book of Worlds pp.10, 19).
FOLIO = {'bottom': '<p><span class="lemma">On the domain as recurring cast.</span> A '
           'glen is the best ally a chronicle can keep and a blight the best '
           'slow antagonist: neither moves, both grow, and the players learn '
           'the neighborhood by watching which way each is growing. Give the '
           'local glen a face &mdash; a guardian, a custom, a gift it grants '
           'and a courtesy it expects &mdash; and the party will defend '
           'ground before they are asked to.</p>\n'
           '        <p><span class="lemma">On the census as clock.</span> The '
           'elder wardens&rsquo; warning that the glens are shrinking is a '
           'chronicle clock ready-made: count the green places at the '
           'campaign&rsquo;s start, and let the count move only when the '
           'players&rsquo; choices move it. A number that falls on schedule '
           'is despair; a number the table can defend is stakes.</p>\n'
           '        <p><span class="lemma">On ruling the toolkit once.</span> '
           'The gear rulings &mdash; what works past the glass, what '
           'flickers, what dies &mdash; are the mirror&rsquo;s tactile '
           'grammar: rule them once and keep the rulings. The dedicated '
           'flashlight that always works and the phone that never does '
           'teach the players the country&rsquo;s law faster than any '
           'lecture, and consistency here is worldbuilding at retail '
           'price.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on gardens, clocks, '
                'and flashlights</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The mirror keeps gardens.</span> Every '
           'well of power casts a <span class="term">domain</span> &mdash; a '
           'country of influence shining through the whole depth of the '
           'glass &mdash; and the law names their two kinds: the <span '
           'class="term">glen</span>, tranquil, its essence running pure; '
           'and the <span class="term">blight</span>, the poisoned garden, '
           'seething with a light that is the opposite of light.<sup>a</sup> '
           'Domains are fluid: they swell and shrink as their streets '
           'prosper or sicken, and the elder wardens attest the glens '
           'are fewer every year.<sup>b</sup> Across the whole mirror '
           'runs the web: silver thread spun by the weaver&rsquo;s '
           'numberless children along every line of wire and traffic, '
           'binding the worlds together and pulling them taut; the '
           'spinners tear down the crooked and rebuild it straight, and '
           'the brave may climb the strands between countries at the '
           'price of meeting the spinner.<sup>c</sup> Meaning walks '
           'manifest: intent is a force in this country &mdash; the '
           'seeker&rsquo;s road assembles itself from things that mean '
           'her quarry &mdash; and the traveler&rsquo;s tools obey the '
           'mirror&rsquo;s prejudices: the dedicated lamp burns, the '
           'chattering devices die, and the gun, to nobody&rsquo;s comfort, works fine.<sup>d</sup> So the verso&rsquo;s law runs: the mirror is no wilderness &mdash; it is gardened, webbed, tolled, and opinionated &mdash; and the walker crosses into a property with standing tenants, whatever the deed on the street side says.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the biography of two gardens. A safehouse for '
           'runaways kept its porch light on for thirty years, and the '
           'mirror grew a glen there: a fountain, a warmth, an essence so '
           'clean the spirits came to drink. A dump took the city&rsquo;s '
           'refusals for the same thirty, and the mirror grew the other '
           'garden: a seething acre where small twisted things nest and '
           'the ground drinks whatever lands on it. Neither garden was '
           'planted; both were earned. The wardens who keep the count '
           'say the second kind is winning, and say it in the tone of '
           'men reporting weather rather than war &mdash; which, the '
           'teachers noted, is itself a symptom. The disputants around '
           'this text hold whether the mirror can be gardened, and whom '
           'the web serves.</p>',
 'chapter': 'Chapter the Fourth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the mirror&rsquo;s gardens; the three deeps wait at folio 91.',
 'folio': '89B',
 'glossL': '<p><span class="mark">a</span> On domains cast by wells of power '
           'through all the mirror&rsquo;s depth, and on glens and '
           'blights by name, see Book of Worlds, folios 10 and 19 of that '
           'volume, and M20, folios 89&ndash;90.</p>\n'
           '        <p><span class="mark">b</span> On the fluidity of '
           'domains and the wardens&rsquo; shrinking count, see Book of '
           'Worlds, folio 10 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'web, its spinners, their tireless straightening, and the '
           'climbing of strands, see Umbra: the Velvet Shadow, folios '
           '17&ndash;18 of that volume, and the wilds folio of M20, '
           '97&ndash;99.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'meaning made manifest and intent as a force, and on the '
           'traveler&rsquo;s tools &mdash; the lamp, the dead phone, the '
           'working gun &mdash; see Umbra: the Velvet Shadow, folios '
           '21&ndash;23 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The wells that cast these '
           'domains are 78b&rsquo;s wells seen from the far side of the '
           'glass: the node&rsquo;s custody law there and the '
           'glen&rsquo;s courtesy here are one property dispute in two '
           'jurisdictions.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'spinners&rsquo; tireless straightening is the stasis this '
           'binding&rsquo;s adversaries of 186a are accused of loving; '
           'the margin has filed the resemblance without ruling on '
           'it, and the Union&rsquo;s own folios decline to comment.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'seeker&rsquo;s road that assembles from meaning is '
           '512a&rsquo;s correspondence walked instead of worked; and '
           'the working gun is 409a&rsquo;s combat law, which crosses '
           'the glass undiminished, to nobody&rsquo;s comfort there '
           'either.</p>',
 'h1': 'The Reflection',
 'hagahah': 'A city keeps two ledgers, and the one behind the glass cannot '
            'be cooked.',
 'inner': '<p><span class="lemma">Cast, not built.</span> The domain '
          'clause&rsquo;s plain sense: a glen is not made the way a ward '
          'is made &mdash; it is earned, the long shadow of what its '
          'street kept doing &mdash; and the blight likewise; the mirror '
          'compounds a place&rsquo;s habits into a garden the way a '
          'ledger compounds interest. The well at the center is the '
          'engine: where essence flows, the flow takes the '
          'street&rsquo;s flavor, and the domain is that flavor grown '
          'territorial.</p>\n'
          '        <p><span class="lemma">Two kinds, one law.</span> '
          'The taxonomy&rsquo;s plain sense: glen and blight are one '
          'mechanism at two signs, not two mechanisms &mdash; the '
          'safehouse and the dump run the same compounding, and the '
          'law&rsquo;s refusal to moralize the machinery is deliberate. '
          'What differs is the essence: the glen&rsquo;s runs '
          'refreshing and pure, the blight&rsquo;s poisoned &mdash; '
          'anti-light, the books say &mdash; and the spirits each '
          'garden gathers are the flavors made citizens.</p>\n'
          '        <p><span class="lemma">The swelling and the '
          'count.</span> The fluidity clause&rsquo;s plain sense: '
          'domains track their streets in something near real time '
          '&mdash; the shelter defunded shrinks its glen, the '
          'dump capped and planted starves its blight &mdash; so the '
          'mirror is a leading indicator any warden can read. The '
          'count&rsquo;s direction is the setting&rsquo;s quiet '
          'thesis: the green places are losing, gradually, on '
          'trend, and no single villain need be convicted for a '
          'trend.</p>\n'
          '        <p><span class="lemma">The web and its '
          'spinners.</span> The web clause&rsquo;s plain sense: the '
          'silver thread is infrastructure and appetite at once. It '
          'binds the worlds &mdash; the strands can be climbed, the '
          'law concedes, by the brave and the foolish &mdash; and it '
          'edits: the spinners remove the asymmetrical and replace '
          'it with the perfectly ordered facsimile, tirelessly, '
          'without malice, which is worse. Their thickening over a '
          'street is a diagnosis the sight of 89a reads at a '
          'glance.</p>\n'
          '        <p><span class="lemma">Intent as a force.</span> '
          'The meaning clause&rsquo;s plain sense: the country runs on '
          'significance, so a walker&rsquo;s purpose is a physical '
          'parameter &mdash; the road to the quarry assembles from '
          'things that mean the quarry, the graveyard&rsquo;s '
          'reflection for the seeker of the dead, the web&rsquo;s '
          'strands for the seeker of the machine. Coincidence, the '
          'books warn, is anything but; and the gear rulings are the '
          'same law in miniature &mdash; the dedicated lamp is an '
          'object with a meaning, the phone is a meaning the country declines to host, and the gun means exactly what it means everywhere.</p>\n        <p><span class="lemma">When the garden closes over.</span> The limit case, from the wolves&rsquo; recension: a domain grown strong enough warps shut &mdash; the resonance makes itself a room, a pocket country with its own weather sealed off the mirror&rsquo;s street grid &mdash; and the catalog runs from hidden gardens to little hells. The clause is the chapter&rsquo;s hinge in miniature: the mirror&rsquo;s gardens, sufficiently compounded, graduate into the made countries the chapter&rsquo;s last folio deeds, and the walker who watches a blight begin to close its door over a neighborhood is watching real estate become jurisdiction.</p>',
 'inner_head': 'On the Gardens<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the domains, the web, and the '
               'meaning</span>',
 'name': 'The Reflection',
 'outer': '<p><span class="lemma">Whether the mirror can be '
          'gardened.</span> The meddling dispute. <span '
          'class="voice">Some say</span> the reflection is load-bearing '
          'and therefore governable: the spirit side is not a report '
          'but a share of the thing itself &mdash; the living, the '
          'sources rule, cannot survive the destruction of their '
          'spiritual halves, and the enemy&rsquo;s doctrine of salting '
          'the far side first is that ruling weaponized &mdash; so the '
          'warden who feeds a glen or starves a blight is doing real '
          'work on the real street, and the mirror is a lever. <span '
          'class="voice">Others say</span> the lever is held '
          'backwards: the mirror compounds the street, not the street '
          'the mirror &mdash; polish the reflection and the dump still '
          'stinks; the glen died because the porch light went out, '
          'and no quantity of spirit-side gardening relights it. The '
          'first school answers with the salted earth: a street '
          'whose far side is killed sickens visibly, so causation '
          'runs both ways or the enemy is wasting its wars. The '
          'second answers that destruction is the easy direction '
          '&mdash; anyone can burn a ledger; writing in one is harder '
          '&mdash; and grants the arsonist his lever while denying '
          'the gardener hers. The folio prices the middle: '
          'downhill amendments run, uphill ones crawl, and the chronicle should charge accordingly &mdash; the arsonist&rsquo;s discount posted beside the gardener&rsquo;s premium. <span '
          'class="kw">TEYKU</span> &mdash; the porch light, relit, has '
          'never yet been billed to either side.</p>\n'
          '        <p><span class="lemma">Whom the web serves.</span> '
          'The spinner dispute. <span class="voice">Some say</span> '
          'menace: the web is stasis with a work ethic &mdash; the '
          'spinners&rsquo; perfect facsimiles are the death of the '
          'crooked and living particular, their thread thickens '
          'wherever the water of 62a runs coldest, and the '
          'binding&rsquo;s adversaries need only stand back and let '
          'the loom work; a tool that always tidies in one '
          'direction is a policy, whoever holds it. <span '
          'class="voice">Others say</span> maintenance: the thread '
          'binds the worlds &mdash; the law&rsquo;s own verb &mdash; '
          'and a cosmos wants tension as a tent wants guys; cut '
          'the web and the countries drift, and the climbers who '
          'curse the spinner still trust her strand with their '
          'weight at every crossing. The first school answers that '
          'a tent pitched over a garden is a cage with weather. '
          'The second answers that the garden grew inside the '
          'tent and has never once been observed outside it. The '
          'stakes are practical and the folio names them: whether '
          'the party&rsquo;s wire-cutters are liberation or '
          'sabotage decides half the chronicle&rsquo;s third act, '
          'and the sources &mdash; wisely, the teachers thought '
          '&mdash; sell the thread and the shears in the same shop. One codicil is shared: whatever the loom is for, nobody disputes what it is doing to the count &mdash; the glens thin as the thread thickens, on trend, decade over decade &mdash; and a chronicle may refuse both theories and still owe the correlation an answer, which is the folio&rsquo;s parting homework.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the gardener, and the loom</span>',
 'rubric': 'the gardens behind the glass',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond, continued &middot; of glens, blights, and the web',
 'title': 'Tractate Aliyah · Folio 89b — The Reflection: the gardens behind the glass',
 'type': 'daf'}
