# Folio 89a - The Penumbra. Chapter IV opens: the near shadow, per the
# wod-llm-wiki penumbra and vidare pages (M20 pp.82, 89-90; W20 Umbra
# pp.14-32; The Infinite Tapestry pp.22-23; Book of Worlds pp.9-11, 19).
FOLIO = {'bottom': '<p><span class="lemma">On the mirror as detective.</span> The '
           'Penumbra is the line&rsquo;s best investigation tool and the books '
           'quietly know it: the place&rsquo;s meaning is evidence no camera '
           'gathers &mdash; the respectable house that rots on the far side has '
           'confessed before the first interview. Let the party&rsquo;s '
           'spirit-worker read a scene the mundane methods have exhausted, and '
           'pay the reading honestly.</p>\n'
           '        <p><span class="lemma">On showing the shadow first.</span> '
           'The mirror is foreshadowing on legs: walk the players past the '
           'reflection before the plot arrives &mdash; the alley that bleeds a '
           'week before the body, the web thickening over the precinct house '
           '&mdash; and the chronicle earns dread at no cost but consistency. '
           'A Penumbra shown only when consulted is a prop; shown on '
           'schedule, it is weather.</p>\n'
           '        <p><span class="lemma">On keeping one mirror.</span> '
           'Whatever the table rules about the three lenses, rule it once: '
           'the same street must show the same soul to every reader, however '
           'differently dressed. A reflection that changes verdicts between '
           'sessions teaches the players the mirror lies, and a lying mirror '
           'is a prop the chronicle cannot get back.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on evidence, weather, '
                'and one mirror kept</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Every place casts a reflection,</span> and '
           'the first country past the veil is the mirror itself: the <span '
           'class="term">Penumbra</span>, the skin of the world, where nearly '
           'every crossing begins.<sup>a</sup> The reflection is honest and '
           'not literal: it shows what a place <span class="term">is</span>, '
           'never merely how it looks &mdash; the loved garden glows, the '
           'sweatshop bleeds, the vanished landmark stands where memory '
           'keeps it &mdash; and things long gone from the street persist in '
           'the mirror, so the walker travels, after a fashion, into the '
           'past.<sup>b</sup> The viewer shapes the view: the law names '
           'three lenses &mdash; the thinker&rsquo;s lattice of shining '
           'geometry, the shaman&rsquo;s raw and vivid wilds, the '
           'mourner&rsquo;s rot and bone &mdash; and rules them one place '
           'seen three ways, for travelers of different lenses stand in one '
           'clearing and see each other plainly.<sup>c</sup> The living '
           'show faint: an ordinary soul is a smear on the mirror, and only '
           'the strong and the corrupt cast solid shadows &mdash; while the '
           'spirits that walk there are as solid as the visitor. The country receives its guests strangely: sensation runs muted and more vivid at once, mist and moonlight over everything, and the first breath tells the walker she stands inside a meaning rather than a place. And the mirror may be consulted without crossing: the sensitive&rsquo;s '
           'sidelong sight reads the reflection from the street '
           'side.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and walk one city. At the river the mirror ran green and '
           'patient, for the river does not care who owns it. Downtown the '
           'walker found a ghost town strung with silver thread, '
           'street-lights burning without light, few citizens casting any '
           'reflection at all; small gray things fed in the doorways on '
           'what the doorways felt. Past the yards the mirror opened on a '
           'garden that was not there in the flesh &mdash; it had been, '
           'once, and the mirror declined to forget it. And at the '
           'shelter on the hill the reflection blazed so warm the walker '
           'checked the street twice: a plain door, a plainer kitchen, '
           'and on the far side, a hearth the size of a public square. '
           'The disputants around this text hold whose mirror it is, and '
           'whether any lens sees straight.</p>',
 'chapter': 'Chapter the Fourth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter IV opens: the mirror here, its glens and blights '
             'overleaf, the three deeps at 91, and the outer wall at 109.',
 'folio': '89A',
 'glossL': '<p><span class="mark">a</span> On the Penumbra as the skin of the '
           'world and the first stop of nearly every crossing, see M20, '
           'folios 89&ndash;90, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the honest mirror '
           '&mdash; meaning over appearance, the persistence of things '
           'past, and travel into the past after a fashion &mdash; see '
           'Umbra: the Velvet Shadow, folios 19&ndash;23 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'three lenses and their one clearing, see M20, folio 82, and '
           'The Infinite Tapestry, folios 22&ndash;23 of that volume; the '
           'elder recension spells the lens otherwise, Book of Worlds, '
           'folios 9&ndash;11 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'faint smears of the living and on the sidelong sight that '
           'reads without crossing, see M20, folios 89&ndash;90, and The '
           'Infinite Tapestry, folios 22&ndash;23 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The door was built at 82a '
           'and this folio is the first country through it; the '
           'wall&rsquo;s thickness there and the mirror&rsquo;s weather '
           'here are one geography, as that folio&rsquo;s Masoret '
           'promised.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'sight that opens on this mirror is 521a&rsquo;s first rank '
           '&mdash; its bleeding sweatshop and glowing house are this '
           'folio&rsquo;s subject read at one remove &mdash; and the '
           'sidelong sight of the unawakened sensitive is 38a&rsquo;s '
           'half-roused census walking this page&rsquo;s margin.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'wolves&rsquo; tractate claims this ground too, and claims it '
           'as a birthright rather than a visit; their recension of the '
           'mirror stands on the shelf beside this binding, and the '
           'dispute below cites it rather than settles it.</p>',
 'h1': 'The Penumbra',
 'hagahah': 'The reflection is honest, which is why nobody consults it '
            'twice.',
 'inner': '<p><span class="lemma">The skin of the world.</span> The '
          'definition&rsquo;s plain sense: the mirror is not a country '
          'past the wall but the wall&rsquo;s own inner face &mdash; the '
          'layer every crossing lands on first, mist-shrouded and '
          'moonlit, its sensations muted and more vivid at once. The '
          'figure matters: a skin belongs to the body it covers, so the '
          'mirror&rsquo;s weather is the street&rsquo;s biography and '
          'not a foreign climate; the folio&rsquo;s whole use follows '
          'from the possessive.</p>\n'
          '        <p><span class="lemma">Is, not looks.</span> The '
          'honesty clause&rsquo;s plain sense: the reflection trades '
          'appearance for meaning &mdash; subtext laid bare as text, the '
          'books say elsewhere of this country &mdash; and its honesty '
          'includes tenses: what a place was, and what it should be, '
          'stand beside what it is. The vanished oasis holds its ground; '
          'the felled forest stands green; and the walker who needs the '
          'street&rsquo;s past interviews the mirror, not the '
          'archive.</p>\n'
          '        <p><span class="lemma">One clearing, three '
          'lenses.</span> The lens law&rsquo;s plain sense: the '
          'thinker&rsquo;s geometry, the shaman&rsquo;s wilds, and the '
          'mourner&rsquo;s rot are named lenses, not named countries '
          '&mdash; the source&rsquo;s own proof is the shared clearing, '
          'three travelers each in a different weather seeing one '
          'another plainly. The elder books put it as the oak: shining '
          'lattice to one eye, sap and appetite to the second, a column '
          'of rot to the third, and the tree is the sum of all three '
          'and more. The lens also steers the feet: where a walker '
          'arrives is bent by how she sees, which the margin will '
          'press.</p>\n'
          '        <p><span class="lemma">The faint and the '
          'solid.</span> The smear clause&rsquo;s plain sense: the '
          'ordinary living barely mark the mirror &mdash; a passing '
          'blur, a warmth &mdash; while the great-souled and the '
          'corrupt print hard, and the spirits native to the place '
          'are as solid as the visitor and considerably more at home. '
          'The consequence runs both ways: the mirror is a poor census '
          'of the street&rsquo;s crowds and an excellent census of its '
          'saints and predators, which is the investigator&rsquo;s '
          'whole interest in one sentence.</p>\n'
          '        <p><span class="lemma">Sight without '
          'crossing.</span> The sidelong clause&rsquo;s plain sense: '
          'the mirror leaks. The sensitive at the street&rsquo;s edge '
          '&mdash; the half-roused of 38a&rsquo;s census, the mage with '
          'a spare glance &mdash; reads the reflection without paying '
          'the wall&rsquo;s toll, and the reading is dimmer but free. '
          'The law thus prices two grades of the same intelligence: '
          'the glance from the curb, and the walk behind the glass '
          '&mdash; and the folio&rsquo;s counsel spends most cases on the cheaper one.</p>\n        <p><span class="lemma">Muted, and more vivid.</span> The arrival clause&rsquo;s plain sense: the mirror&rsquo;s sensorium is a paradox kept on purpose &mdash; sound damped as under snow, color sharpened past the street&rsquo;s palette &mdash; because the country transmits meaning rather than light, and meaning has no volume knob. The practical consequence is the folio&rsquo;s cheapest advice: attention outperforms equipment there &mdash; the walker who describes what she sees is already navigating, and the one who consults her instruments is reading the wrong country&rsquo;s gauges.</p>',
 'inner_head': 'On the Mirror<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the skin, the lenses, and the '
               'sidelong sight</span>',
 'name': 'The Penumbra',
 'outer': '<p><span class="lemma">Whose mirror.</span> The crossover '
          'dispute. <span class="voice">Some say</span> one mirror with '
          'three tenants&rsquo; readings: the wolves walk an idealized '
          'garden and call it their half of home; the mages walk a '
          'lensed reflection and call it the first country; the dead '
          'gray everything and call it the Shadowlands &mdash; and all '
          'three are one street behind one glass, for the sources '
          'themselves let the tenants meet there and fight over the '
          'furniture. <span class="voice">Others say</span> the '
          'harmonization is a courtesy that fails on inspection: each '
          'tractate&rsquo;s near shadow keeps its own law &mdash; the '
          'garden admits by birthright what the reflection admits by '
          'labor, the gray country starts at a wall the other two '
          'never meet &mdash; and a place is its admission rules, so '
          'three laws are three countries wearing one address. The '
          'first school answers that admission rules differ at every '
          'door of one city. The second answers that a city whose '
          'tenants cannot agree on its existence is three cities, '
          'and the shelf holds three tractates for cause. The folio '
          'files the girsa unharmonized per the binding&rsquo;s law '
          'and notes the stakes plainly: a chronicle that crosses '
          'lines must pick its map before the second session. <span '
          'class="kw">TEYKU</span> &mdash; the street, asked, reflects '
          'the asker.</p>\n'
          '        <p><span class="lemma">Whether any lens sees '
          'straight.</span> The privilege dispute. <span '
          'class="voice">Some say</span> the lenses are equals: the '
          'law&rsquo;s own tree is the sum of geometry, sap, and rot '
          'and more besides, so every lens is true and none '
          'sufficient, and the traveler&rsquo;s view is a confession '
          'of temperament rather than a measurement. <span '
          'class="voice">Others say</span> the elder recension broke '
          'the tie and the binding should not hide it: the '
          'shaman&rsquo;s lens, that recension rules, sees what is '
          'rather than what the seer thinks &mdash; the raw view is '
          'less subjective than its rivals, resonance stark upon it '
          '&mdash; so one lens is a window and the others are '
          'spectacles. The first school answers that a recension '
          'which spells the very lens differently is a witness to '
          'handle with care, and that the newer law flattened the '
          'privilege on purpose. The second answers that flattening '
          'a privilege is how a losing lens negotiates. The dispute '
          'is priced at the table: if one lens is a window, the '
          'chronicle&rsquo;s shamans hold the atlas and everyone else '
          'buys their readings &mdash; a market the next folios&rsquo; '
          'journeys will quote whether or not the table has ruled. '
          'And both schools sign one rider: whichever lens reads '
          'truest, the mirror bends the feet &mdash; where a walker '
          'lands is steered by how she sees, so the lens is never '
          'only optics but always also destination, and a chronicle '
          'that forgets this sends three travelers to one address '
          'and strands them in three different streets. The teachers kept the quarrel&rsquo;s best exhibit: one square surveyed on commission by three lenses, filed unreconciled, each surveyor certifying the others&rsquo; maps as excellent work about somewhere else &mdash; and the commissioning elder&rsquo;s note, that she had asked for a map and received three portraits, is the dispute in one line.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the tenants, and the lenses</span>',
 'rubric': 'the near shadow',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond &middot; of the Penumbra &middot; the mirror as law',
 'title': 'Tractate Aliyah · Folio 89a — The Penumbra: the near shadow',
 'type': 'daf'}
