# Folio 91a - The Three Umbrae. The triple deep, per the wod-llm-wiki
# high/middle/low umbra pages (M20 pp.94-100; The Infinite Tapestry
# pp.9-10, 24-26, 37-38; Book of Worlds pp.23-53, 71-76).
FOLIO = {'bottom': '<p><span class="lemma">On anchoring the journey.</span> The '
           'otherworld session dies when it floats: tie every deep journey to '
           'a stake on the ground floor &mdash; the patient who needs the '
           'idea retrieved, the node the court&rsquo;s favor protects, the '
           'name only the dead still remember. A traveler with a material '
           'errand reads the wonders as terrain; a tourist reads them as '
           'wallpaper, and wallpaper is where chronicles go to nap.</p>\n'
           '        <p><span class="lemma">On the clock in the deeps.</span> '
           'Keep the ground game running while the travelers are away: the '
           'deep&rsquo;s strange hours are the excuse the plot needed &mdash; '
           'the party returns to a street three days older, or three '
           'minutes, and either bill is drama if the Storyteller kept the '
           'meter honestly. A journey that pauses the world teaches the '
           'players the world is a set.</p>\n'
           '        <p><span class="lemma">On the maps as props.</span> Hand '
           'the players the courtesies &mdash; the elder&rsquo;s hand-drawn '
           'atlas, the Convention&rsquo;s survey with its margins stamped '
           'provisional &mdash; and let the maps disagree. A wrong map the '
           'table trusted for three sessions is worth more than a right '
           'one, because the deeps&rsquo; first law is that the map is a '
           'promise nobody&rsquo;s country has to keep.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on stakes, meters, '
                'and wrong maps</span>',
 'center': '<p class="noindent"><span class="dropcap">P</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Past the mirror the deep runs three '
           'countries.</span> The <span class="term">High</span>, the '
           'astral reaches, where ideas live as places: from the basement '
           'of common notions, up through the heavens and hells that souls '
           'reach by expecting them, past the courts of the mighty, up '
           'spires climbed by understanding rather than by hand, to '
           'heights no visiting mind can hold for long.<sup>a</sup> The '
           '<span class="term">Middle</span>, the spirit wilds, nature '
           'with the mask off: misted country navigated by omen-trails '
           'and moonlit roads, webbed with the spinners&rsquo; silver, '
           'rising at last into an open sky of cloud-realms where the '
           'machines of the flesh give out entirely.<sup>b</sup> And the '
           '<span class="term">Low</span>, the underworld, which keeps '
           'its own second veil: the living enter only by a threefold '
           'descent few can work, every crossing stains the crosser with '
           'a residue of death that never fully fades, and its weather '
           'is a storm around drowned cities, over a pit into which all '
           'things are eventually swept.<sup>c</sup> Each country admits '
           'differently, costs differently, and keeps its own law; and '
           'of all three the teaching holds: the maps are courtesies '
           '&mdash; drawn by the polite for the grateful, binding on '
           'nobody, least of all the territory.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear three journeys. A scholar climbed a proof into '
           'the high country; the stairs bore her exactly as long as she '
           'understood them, and at the landing an idea too large to '
           'hold looked at her, briefly, with something like approval '
           '&mdash; she says the world has never felt entirely real '
           'since, and says it smiling. A witch walked a moon-road '
           'through the wilds and paid the road&rsquo;s keeper in songs; '
           'off the path, she had been warned, the mists own the '
           'compass &mdash; she arrived owing two verses and aged either '
           'a night or a season, depending which calendar you trust. '
           'And a death-mage made the third descent, worked the '
           'threefold door, and came back with what she went for; but '
           'she wears the stain still, and the flowers, she reports '
           'without complaint, no longer lean toward her. The '
           'disputants around this text hold the count of the '
           'countries, and who holds the deed to the third.</p>',
 'chapter': 'Chapter the Fourth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the three deeps; their courts and citizens wait overleaf.',
 'folio': '91A',
 'glossL': '<p><span class="mark">a</span> On the high country &mdash; the '
           'basement of notions, the afterworlds sized by expectation, '
           'the courts, the spires, and the unholdable heights &mdash; '
           'see M20, folios 94&ndash;97.</p>\n'
           '        <p><span class="mark">b</span> On the spirit wilds '
           '&mdash; the omen-trails and moon-roads, the web, and the '
           'open sky where machines fail &mdash; see M20, folios '
           '97&ndash;99.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'underworld &mdash; its second veil, the threefold descent, '
           'the stain of death, the storm, and the pit &mdash; see M20, '
           'folios 99&ndash;100.</p>\n'
           '        <p class="drop"><span class="mark">d</span> The '
           'variant manuscripts survey the same three countries under '
           'other names: The Infinite Tapestry, folios 9&ndash;10 and '
           '24&ndash;26 and 37&ndash;38 of that volume, and the elder '
           'recension, Book of Worlds, folios 23&ndash;53 and '
           '71&ndash;76 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The mirror of 89 is the '
           'porch of all three countries, and the wall of 82a their '
           'common door; the atlas this chapter owes began there and '
           'deepens here, one geography in three volumes.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'arts of the roads: the spirit-craft of 521a walks the wilds, '
           'the mind-craft of 519a climbs the high country, and the '
           'threefold descent is 156b&rsquo;s death-work stated as a '
           'travel visa; the stain it prices is that folio&rsquo;s whole '
           'subject.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'third country&rsquo;s deed is contested out of binding: the '
           'dead&rsquo;s own tractate on the shelf claims the underworld '
           'entire, and the wilds are the wolves&rsquo; second home by '
           'their tractate&rsquo;s law; the dispute overleaf cites both '
           'without settling either.</p>',
 'h1': 'The Three Umbrae',
 'hagahah': 'The map is not the territory; past the outer wall, the '
            'territory is not the territory either.',
 'inner': '<p><span class="lemma">Ideas as places.</span> The high '
          'country&rsquo;s plain sense: thought has geography there '
          '&mdash; the common notion is a basement anyone can reach, '
          'the difficult truth a spire climbed only by understanding '
          'it, and the visitor&rsquo;s constant weather is epiphany, '
          'the click of things suddenly obvious. Two clauses carry '
          'the law&rsquo;s weight: the heavens and hells are sized by '
          'their congregations and reached by expectation &mdash; the '
          'soul goes where it was sure it was going &mdash; and the '
          'returning traveler&rsquo;s souvenir is subtraction: the world beneath never feels entirely real again &mdash; a debit the folio declines to romanticize, for the chapter&rsquo;s travelers pay it compounding.</p>\n'
          '        <p><span class="lemma">Nature with the mask '
          'off.</span> The wilds&rsquo; plain sense: the middle country '
          'is not a metaphor for the woods but the woods&rsquo; own '
          'soul, red in fang and claw, and it enforces a dress code '
          '&mdash; the machines of the flesh sputter and die while the '
          'bone-deep crafts work reliably, which is the country '
          'telling the visitor whose law runs. Its navigation is '
          'literacy: the omen-trail is read, not seen &mdash; a broken '
          'twig, a raven&rsquo;s cry, a pattern in the dirt &mdash; and '
          'the moon-roads are clearer, tolled, and jealously '
          'guarded by the wolves who hold them. Storms walk the wilds besides &mdash; winds that scatter the roads and hurl the traveler, quakes when a great spirit rages &mdash; and the elder appendix prices both in bruises and in strandings.</p>\n'
          '        <p><span class="lemma">The second veil and the '
          'threefold door.</span> The underworld&rsquo;s plain sense: '
          'the third country is doubly locked &mdash; behind the '
          'common wall stands a second veil that is nobody&rsquo;s '
          'lens and everybody&rsquo;s wall &mdash; and the living '
          'key is a compound working of ending, life, and passage '
          'that few hands can hold at once. The stain is the '
          'toll&rsquo;s fine print: a residue of death that never '
          'fully fades, priced into every later working the '
          'crosser attempts, so the descent is paid in '
          'installments for the rest of a career.</p>\n'
          '        <p><span class="lemma">The storm and the '
          'pit.</span> The weather clause&rsquo;s plain sense: the '
          'underworld&rsquo;s interior is a standing tempest around '
          'islands of the dead&rsquo;s own building, crossed on '
          'old roads the dead maintain, and at the bottom of '
          'everything an unmaking into which all things are '
          'eventually swept. The law states it without comfort '
          'and the folio declines to add any: the deepest fact '
          'in the atlas is a drain.</p>\n'
          '        <p><span class="lemma">Courtesies, not '
          'contracts.</span> The map clause&rsquo;s plain sense: '
          'every atlas of the deeps is a courtesy &mdash; drawn '
          'true at drawing, binding on nothing &mdash; because the '
          'countries rearrange: the high country moves when '
          'minds move, the wilds shift with the seasons of '
          'story, the storm redraws the third weekly. The '
          'practical law follows: navigation there is a skill '
          'and a diplomacy, never a possession, and the traveler&rsquo;s best instrument is a local. The clause grades the courtesies too: the wolves&rsquo; road-charts run truest and dearest, the Union&rsquo;s surveys are precise about everything except what matters, and the elder atlases are wrong in ways so faithfully documented that their errors navigate better than a stranger&rsquo;s accuracies.</p>',
 'inner_head': 'On the Deeps<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the three countries and their '
               'tolls</span>',
 'name': 'The Three Umbrae',
 'outer': '<p><span class="lemma">Three, or one seen three '
          'ways.</span> The count dispute. <span class="voice">Some '
          'say</span> three countries in earnest: each admits by its '
          'own door, costs its own toll, and keeps a law the others '
          'never enforce &mdash; no lens makes the idea-spire grow '
          'fangs or the moon-road quote scripture, and the second '
          'veil bars the living from the third country under every '
          'lens ever ground. <span class="voice">Others say</span> '
          'the chapter&rsquo;s own first folio decided otherwise and '
          'should be believed: the porch is provably one place '
          'wearing three weathers &mdash; the travelers see each '
          'other &mdash; and what holds at the sill holds in the '
          'cellar; the three deeps are one deep read by the three '
          'lenses, their differences a survey of the surveyors. '
          'The first school answers with the wall: the '
          'underworld&rsquo;s second veil is a fact for every '
          'viewer, and facts that bind all lenses are not lens '
          'effects. The second answers that a lens can grind a '
          'wall as easily as a window &mdash; the mourner&rsquo;s '
          'country would of course wall itself against the '
          'living. The stakes are a traveler&rsquo;s life: if the '
          'countries are one, craft transfers and the wilds&rsquo; '
          'literacy reads the spires; if three, every border '
          'resets the tuition. The folio files the girsa '
          'unharmonized and notes that the sources themselves '
          'built the doubt: the porch is ruled one place in so '
          'many words, and the deeps are mapped as three in the '
          'same books, unreconciled at press. <span '
          'class="kw">TEYKU</span> &mdash; the only witnesses who '
          'could settle it have all, necessarily, used a '
          'lens.</p>\n'
          '        <p><span class="lemma">Who holds the deed to '
          'the third.</span> The jurisdiction dispute. <span '
          'class="voice">Some say</span> this tractate visits and '
          'must say so: the underworld is the dead&rsquo;s own '
          'country with a standing government and a shelf of its '
          'own law &mdash; the storm, the islands, the drain are '
          'theirs to name &mdash; and the living art&rsquo;s writ '
          'runs exactly as far as a tourist&rsquo;s visa; the '
          'folio should cite the dead&rsquo;s tractate the way a '
          'treaty cites a foreign code. <span class="voice">Others '
          'say</span> the atlas cannot outsource its own third '
          'volume: the threefold descent, the stain, the '
          'drain&rsquo;s pull on every pattern are this '
          'art&rsquo;s law wherever they operate, and a country '
          'does not escape the chapter by having natives. The '
          'first school answers that writing law for a land '
          'whose citizens outnumber your visitors a million to '
          'one is not jurisprudence but tourism with '
          'footnotes. The second answers that every folio in '
          'this binding legislates for countries with natives '
          '&mdash; the wilds have wolves, the high courts have '
          'kings &mdash; and only the dead&rsquo;s lobby has '
          'argued itself a special exemption. The folio rules '
          'narrowly, as befits a guest: the descent, the '
          'stain, and the coming home are this chapter&rsquo;s; '
          'the country&rsquo;s interior law is cited as '
          'foreign, held on the sibling shelf; and the reader '
          'crossing that border is advised, in both '
          'tractates&rsquo; voices, to mind the local '
          'code.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the count, and the deed</span>',
 'rubric': 'the triple deep',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond, continued &middot; of the three Umbrae &middot; the deeps '
             'as law',
 'title': 'Tractate Aliyah · Folio 91a — The Three Umbrae: the triple deep',
 'type': 'daf'}
