# Folio 91b - The Courts. The deeps' citizens, per the wod-llm-wiki
# high/middle/low umbra pages (M20 pp.94-100; W20 Umbra pp.96-103;
# Book of Worlds pp.25-33).
FOLIO = {'bottom': '<p><span class="lemma">On the court as recurring cast.</span> A '
           'court visited twice is worth ten visited once: pick the '
           'chronicle&rsquo;s two or three &mdash; the clockwork dominion, '
           'the moon-road&rsquo;s toll-keeper, one patient ghost &mdash; and '
           'let the party build standing. Favor and grudge are the '
           'deeps&rsquo; only durable currency, and an entity that '
           'remembers the players is worth more than any wonder they '
           'carry out.</p>\n'
           '        <p><span class="lemma">On playing the protocol.</span> '
           'Run audiences as scenes of manners, not skill rolls: the '
           'gift chosen, the name withheld, the chair declined. The '
           'books&rsquo; counsel to pay respects regardless of belief is '
           'table advice as much as theology &mdash; the player who '
           'role-plays the courtesy has done the diplomacy, and dice '
           'should only arbitrate what courtesy left undecided.</p>\n'
           '        <p><span class="lemma">On statting the '
           'unstattable.</span> Stat the doorkeepers and the small '
           'hungry things; leave the enthroned unstatted. A god with a '
           'pool is a monster with a title, and the table smells it: '
           'the great courts work best as weather and verdict &mdash; '
           'something the party negotiates with or flees, never '
           'something they whittle.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on standing, manners, '
                'and the unstatted</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The deeps are peopled, and the people '
           'hold court.</span> In the high country every idea is a '
           'citizen: each thought held anywhere is a spirit somewhere, '
           'the mighty concepts keep dominions shaped to their own '
           'desire, and in their halls a god and a theorem are equally '
           'strong and equally dangerous &mdash; the law&rsquo;s counsel '
           'is one line: pay respects, whatever you believe.<sup>a</sup> '
           'The wilds keep the elder houses: totems and beast-fathers, '
           'the elements enthroned, the moon&rsquo;s pale heralds on '
           'their roads, and the spinners at their loom; their code is '
           'the guest-law &mdash; toll, gift, and grudge &mdash; and it is enforced, for the roads themselves keep the ledger: the mists own the shirker&rsquo;s compass, and the grudge outlives the traveler who earned it.<sup>b</sup> The underworld&rsquo;s citizens '
           'are the unfinished dead, and its aristocracy is worse: '
           'the drowned who gave themselves to the drain return as '
           'its agents, hunting the light the living cannot help but carry, for the living burn like lamps in that country and cannot be shuttered.<sup>c</sup> And one writ runs through every '
           'court alike: names are property, bargains bind past '
           'death, and the traveler who cannot say what she is '
           'worth will be appraised, by assessors whose fee is customarily taken from the estate.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear of one pilgrim in two heavens. She climbed '
           'to the first and found the Throne as her grandmother had '
           'promised it, light upon light, and paid her respects; she '
           'walked the shadows of the second and found Night '
           'enthroned there, older than the light and unbothered by '
           'it, and paid her respects. Asked at home which court was '
           'true, she said: both received me, which is more than the '
           'courts of the flesh have managed &mdash; and the teachers '
           'preserved her answer beside a harder saying: that in '
           'those halls the congregation&rsquo;s size is the '
           'throne&rsquo;s size, and a god forgotten is a cottage where a palace stood &mdash; and that no court, however small its rooms have grown, forgets a visit from the living. The disputants around this text '
           'hold what the enthroned are, and whether courtesy there '
           'is law or manners.</p>',
 'chapter': 'Chapter the Fourth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the deeps&rsquo; citizens; the outer wall waits at folio 109.',
 'folio': '91B',
 'glossL': '<p><span class="mark">a</span> On the high courts &mdash; every '
           'thought a spirit, dominions shaped to desire, gods and '
           'theorems equally deadly, and the counsel of respects '
           '&mdash; see M20, folios 94&ndash;97, and Umbra: the Velvet '
           'Shadow, folios 96&ndash;97 of that volume.</p>\n'
           '        <p><span class="mark">b</span> On the wilds&rsquo; '
           'houses &mdash; the totems, the enthroned elements, the '
           'moon&rsquo;s heralds, the spinners &mdash; see M20, folios '
           '97&ndash;99, and the elder court catalog, Book of Worlds, '
           'folios 25&ndash;33 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'unfinished dead and on the drowned who serve the drain, '
           'see M20, folios 99&ndash;100, and Umbra: the Velvet '
           'Shadow, folios 99&ndash;103 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'names, bargains, and appraisal in the spirit courts, see '
           'the protocol law bound at folio 521a and the sources it '
           'cites.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The court protocol here '
           'is 521a&rsquo;s bargain ladder worn as etiquette: the toll, '
           'the gift, and the grudge are that folio&rsquo;s law '
           'restated by a herald, and the appraisal clause is its '
           'warning label.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'congregation-sized throne is 62a&rsquo;s water ruling the '
           'far shore: belief builds palaces there as it builds '
           'baselines here, and the cottage where a palace stood is '
           'that folio&rsquo;s erosion clause in court dress.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'drowned hunters of the third country are tried in full in '
           'the dead&rsquo;s own tractate on the shelf; and the '
           'beast-fathers&rsquo; houses are the wolves&rsquo; '
           'birthright by theirs. This folio keeps the visitor&rsquo;s '
           'code and leaves the thrones their own law.</p>',
 'h1': 'The Courts',
 'hagahah': 'Every throne in the deeps is exactly the size of its '
            'congregation, and none of them likes to be measured.',
 'inner': '<p><span class="lemma">Every thought a citizen.</span> The '
          'high clause&rsquo;s plain sense: the idea-country&rsquo;s '
          'census is the census of thinking &mdash; whatever is held in '
          'any mind holds ground there, the trivial as vermin, the '
          'profound as princes &mdash; and its nobility is '
          'proportional: the widely believed are the mighty. The god '
          'and the theorem stand equal because both are ideas '
          'enthroned, and the law&rsquo;s refusal to rank them is the '
          'refusal every visitor must learn before speaking.</p>\n'
          '        <p><span class="lemma">Shaped to desire.</span> '
          'The dominion clause&rsquo;s plain sense: a court is its '
          'holder&rsquo;s self-portrait &mdash; the clockwork dominion, '
          'the throne of blood and fire, the several wonderlands '
          '&mdash; so the architecture is intelligence: read the hall '
          'and you have read the host. The visitor&rsquo;s corollary '
          'cuts both ways: what she wears, carries, and refuses in '
          'a court reads as her own architecture, and the enthroned are better readers than she is. The counsel is wardrobe as diplomacy: dress for the court you intend to be read as.</p>\n'
          '        <p><span class="lemma">The guest-law of the '
          'wilds.</span> The middle clause&rsquo;s plain sense: the '
          'elder houses run on reciprocity old as burrows &mdash; the '
          'toll paid at the road, the gift at the threshold, the '
          'grudge kept to the seventh season &mdash; and its '
          'enforcement wants no bailiff: the road itself forgets '
          'the toll-shirker, the mists misplace the rude. The moon&rsquo;s heralds and the spinners are the two bureaucracies every traveler meets first, and both keep books, and audit: the herald&rsquo;s road dims for the indebted, and the spinner&rsquo;s thread draws tight around the account overdrawn.</p>\n'
          '        <p><span class="lemma">The unfinished and the '
          'drowned.</span> The low clause&rsquo;s plain sense: the '
          'dead who remain are the interrupted &mdash; lives cut '
          'off unresolved, still facing the wrong way &mdash; and '
          'they are dangerous chiefly as the desperate are. The '
          'aristocracy is another matter: the drowned served '
          'the drain and were remade as its collectors, and '
          'the light clause explains the peril&rsquo;s mechanics, and the folio&rsquo;s counsel is the dead&rsquo;s own: travel dim, travel brief, and owe nothing on the far side of the storm.</p>\n'
          '        <p><span class="lemma">Appraisal.</span> The '
          'writ&rsquo;s plain sense: the courts price everything, '
          'travelers included. A name given is a lien granted; a '
          'bargain sworn binds the estate; and the visitor who '
          'arrives without knowing her own worth will have it '
          'fixed for her, by parties with an interest in fixing '
          'it low. The protocol folio&rsquo;s whole ladder is this '
          'sentence with sub-clauses, and the counsel below '
          'spends it at the table.</p>\n        <p><span class="lemma">The nightmare clause.</span> The census&rsquo;s underside: what is commonly feared takes shape as commonly feared &mdash; the spider, the clown, the count &mdash; and hunts as its subject hunts, staging the victim through a waking dream with real teeth. The mercy is symmetrical and the law insists on it: each such citizen wears its subject&rsquo;s weaknesses along with its face, and the count&rsquo;s shadow, however dreadful, still minds the stake. The counsel prices the clause for travelers: know the story before you meet its tenant, for the deeps&rsquo; monsters come pre-annotated, and the annotation is the weapon.</p>',
 'inner_head': 'On the Citizens<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the census, the guest-law, and the '
               'appraisal</span>',
 'name': 'The Courts',
 'outer': '<p><span class="lemma">What the enthroned are.</span> The '
          'ontology dispute. <span class="voice">Some say</span> '
          'persons: the courts are polities of genuine others &mdash; '
          'wills older than the visitor&rsquo;s species, keeping law, '
          'levying toll, honoring treaty &mdash; and the proof is '
          'contractual: a bargain with a reflex does not bind, yet '
          'the courts&rsquo; bargains bind past death and are '
          'collected on, which is personhood by any test a court of '
          'the flesh would accept. <span class="voice">Others '
          'say</span> census: the enthroned are humanity&rsquo;s '
          'thinking worn as crowns &mdash; the throne is exactly the '
          'congregation&rsquo;s size, the god forgotten dwindles to a '
          'cottage, and an entity whose stature tracks belief that '
          'closely is belief, personified by visitors who cannot '
          'bear to negotiate with weather. The first school '
          'answers with the second heaven: Night received the '
          'pilgrim with courtesies no congregation taught it, and '
          'the drowned hunt with an appetite nobody believes in '
          'on purpose. The second answers that appetite is the '
          'easiest thing of all to believe in, and that the '
          'first school has never met a court older than its '
          'oldest worshipper. The stakes are the chronicle&rsquo;s '
          'diplomacy entire: persons can be wronged and owed; '
          'census can only be surveyed and steered &mdash; and a '
          'party that picks the wrong theory will either sue the rain or insult a king &mdash; and the deeps forgive the second error less often than the first. The folio files the girsa '
          'unharmonized, noting that the sources house both '
          'readings without embarrassment. <span '
          'class="kw">TEYKU</span> &mdash; the enthroned, asked '
          'directly, have answered both ways, and smiled '
          'both times.</p>\n'
          '        <p><span class="lemma">Whether courtesy is law '
          'or manners.</span> The protocol dispute. <span '
          'class="voice">Some say</span> law: the guest-code is the '
          'deeps&rsquo; constitution &mdash; the toll, the gift, the '
          'name withheld are compliance, not charm; the road '
          'forgets the shirker as surely as the wall of 82a '
          'stops the unready, and the wolves&rsquo; tractate, '
          'which has kept these courts longest, writes the '
          'code as statute with penalties. <span '
          'class="voice">Others say</span> manners: the code '
          'is custom hardened by fear &mdash; the courts '
          'themselves waive it for the interesting, enforce it '
          'selectively on the weak, and no statute that bends '
          'to charisma was ever law; the strong traveler '
          'transacts, the weak one curtsies, and calling the '
          'difference jurisprudence flatters the curtsy. The '
          'first school answers that selective enforcement is '
          'still enforcement, as any street in the flesh '
          'could testify. The second answers that this proves '
          'the courts are exactly as lawful as the street, '
          'which was its point. The folio declines the middle '
          'and prices the wager instead: treat the code as '
          'law and lose nothing but pride; treat it as '
          'manners and be occasionally, unrecoverably wrong '
          '&mdash; and the teachers, who buried the occasionally '
          'wrong, commend the premium. And the rider both schools initial: whatever courtesy is, arrears are real &mdash; the deeps keep accounts receivable, and a toll unpaid returns with interest, at the season the road finds most instructive.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the thrones, and the curtsy</span>',
 'rubric': 'the deeps&rsquo; citizens',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond, continued &middot; of courts and citizens',
 'title': 'Tractate Aliyah · Folio 91b — The Courts: the deeps&rsquo; citizens',
 'type': 'daf'}
