# Folio 109a - The Horizon. The outer wall, per the wod-llm-wiki
# horizon and deep-umbra pages (M20 pp.109-111, 114-115; The Infinite
# Tapestry pp.10-11, 117; Book of Worlds pp.185-186).
FOLIO = {'bottom': '<p><span class="lemma">On the crossing as finale.</span> The '
           'outer wall is a season boundary, not a scene transition: price the '
           'first crossing as the campaign&rsquo;s hinge &mdash; preparation '
           'arcs, a vessel or a vortex found, the long labor staged against '
           'a clock &mdash; and the far side will feel like the far side. A '
           'party that day-trips past the sky has been cheated of the '
           'setting&rsquo;s best border.</p>\n'
           '        <p><span class="lemma">On the surcharge home.</span> The '
           'law&rsquo;s cruelest number is the return price, and it is a '
           'gift: the party that crossed out on ten successes owes fifteen '
           'to come home, and the Storyteller who makes them feel the '
           'difference &mdash; supplies thinning, the world&rsquo;s pull '
           'weakening &mdash; has built the third act for free. Out is '
           'ambition; home is the story.</p>\n'
           '        <p><span class="lemma">On the ether as register.</span> '
           'The sea between the walls is the setting&rsquo;s pulp shelf: '
           'brass ships, wardens at the vortices, planets with opinions. '
           'Run it in that register unapologetically &mdash; the '
           'chapter&rsquo;s horror lives below and its politics behind, '
           'and the chronicle earns both by letting the middle passage '
           'be wonder.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on hinges, surcharges, '
                'and brass ships</span>',
 'center': '<p class="noindent"><span class="dropcap">A</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Around the whole agreement stands a '
           'second wall.</span> The law names it the <span '
           'class="term">Horizon</span>: a thicker veil above the first, '
           'the shell that insulates the world from the outer dark '
           '&mdash; and, the books add without smiling, probably '
           'insulates the dark from us.<sup>a</sup> It is not stepped '
           'through: the astral masters project past it, the lucky ride '
           'the standing vortices, the technologists sail ships, the '
           'rest buy doors &mdash; and the unaided fording is the '
           'art&rsquo;s longest labor, ten successes gathered to leave '
           'and fifteen to come home, where a vortex spares all but a '
           'test of will.<sup>b</sup> Between this wall and the deep '
           'some count a second sea and a farther wall: the ether, '
           'where the old laws of legend still sail, its vortices '
           'warded by fallen masters &mdash; a variant geography the '
           'binding files unharmonized.<sup>c</sup> And past every '
           'counting waits the deep itself, where the paradox law of '
           '533a does not run at all: the mad and the fallen were '
           'driven there within living memory and build on the far '
           'rocks, and the void unhouses the unshipped soul &mdash; the '
           'traveler who crosses unwarded scatters.<sup>d</sup> So the '
           'wall&rsquo;s law runs: the world wears two skins, and the '
           'outer one was fitted against something.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear how the wall is said to have risen. The old '
           'telling: the world stood at the center once, the sky&rsquo;s '
           'countries hung close as lamps, and ships of sail rigged for '
           'the ether worked the near heavens. Then the glass turned, '
           'and the world learned to call itself a speck in an endless '
           'dark &mdash; and the shell, this telling says, grew to fit '
           'the new modesty: a wall raised by an argument, as the '
           'wall of 82a is raised by disbelief. And the '
           'source&rsquo;s own narrator scoffs at the whole account '
           '&mdash; nonsense, he rules, the shell is older than the '
           'telescope &mdash; and the binding keeps the scoff beside '
           'the telling per its law, noting only this: both '
           'parties agree the ships stopped coming home. The '
           'disputants around this text hold who raised the shell, '
           'and what it was fitted against.</p>',
 'chapter': 'Chapter the Fourth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the outer wall; the countries carved in it wait overleaf, '
             'and the chapter closes there.',
 'folio': '109A',
 'glossL': '<p><span class="mark">a</span> On the Horizon as the second, '
           'thicker veil and the two-way insulation, see M20, folios '
           '109&ndash;111, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the crossings '
           '&mdash; projection, vortices, ships, doors &mdash; see the '
           'same folios; the fording&rsquo;s prices, ten out and '
           'fifteen home and the vortex&rsquo;s mercy, are the elder '
           'recension&rsquo;s, Book of Worlds, folio 186 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'ether sea, its warded vortices, and the model of three '
           'walls in place of two, see M20, folios 109&ndash;111, and The Infinite Tapestry, folios 10&ndash;11 of that volume; the wall&rsquo;s own confusion of paradox is folio 117 there.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'deep &mdash; the lapse of the paradox law, the exiled '
           'builders, and the scattering of the unshipped &mdash; see '
           'M20, folios 114&ndash;115, and Book of Worlds, folios '
           '185&ndash;186 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The first wall is '
           '82a&rsquo;s and this folio is its second course: one '
           'crossing is a scene and the other a season, and the two '
           'folios&rsquo; prices should be read as one tariff '
           'schedule.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'wardens of this rampart are 194a&rsquo;s border corps, whose '
           'whole Convention is this folio worn as a uniform; and the '
           'paradox law that lapses past the wall is 533a&rsquo;s, whose '
           'margin has been warned.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'exile of the mad and the fallen is chapter VII&rsquo;s, folios 197 through 234; and the storm that '
           'scarred these crossings is filed with the end-times, '
           'wanting, as 82a&rsquo;s Masoret already marked.</p>',
 'h1': 'The Horizon',
 'hagahah': 'The world put up a wall between itself and the sky, and both '
            'parties call it self-defense.',
 'inner': '<p><span class="lemma">A second skin, fitted.</span> The '
          'definition&rsquo;s plain sense: the shell repeats the '
          'wall&rsquo;s figure at planetary scale &mdash; grown or '
          'raised around the whole agreement, thicker than the first '
          'veil, and double-faced by the law&rsquo;s own aside: it '
          'keeps the dark from the world and the world from the dark, '
          'and the aside is load-bearing &mdash; a wall with two '
          'clients has two theories of what it is for, and the '
          'margin will hold the hearing.</p>\n'
          '        <p><span class="lemma">Four doors and a '
          'labor.</span> The crossing clause&rsquo;s plain sense: the '
          'shell does not admit the wall&rsquo;s ordinary crossing '
          '&mdash; the catalog runs projection for the masters of '
          'mind, the standing vortices for the lucky and the '
          'informed, hulls for the technologists, bought doors for '
          'the rest &mdash; and the unaided fording is priced as the '
          'art&rsquo;s longest labor: ten gathered to leave, with '
          'the vortex discounting the toll to a test of will. '
          'Each door keys a faction, which is the clause&rsquo;s '
          'quiet politics: how a fellowship crosses tells you what it worships &mdash; and how it is shipwrecked: the projector&rsquo;s cord can be cut, the vortex&rsquo;s warden turned, the hull holed, the bought door repossessed, each crossing carrying its faction&rsquo;s characteristic disaster in its luggage.</p>\n'
          '        <p><span class="lemma">Fifteen home.</span> The '
          'surcharge&rsquo;s plain sense: coming home costs half '
          'again the leaving, and the asymmetry is doctrine, not '
          'bookkeeping &mdash; the world&rsquo;s agreement does not '
          'miss its emigrants, and readmission is negotiated '
          'against a wall that has already closed once. The '
          'counsel below spends the number as drama; the law '
          'here only insists it be charged.</p>\n'
          '        <p><span class="lemma">The sea between the '
          'walls.</span> The variant&rsquo;s plain sense, filed '
          'unharmonized: one recension draws two walls with an '
          'ether sea between &mdash; legend&rsquo;s own ocean, where '
          'the star-ships worked and the vortices are warded by '
          'entities said to be fallen masters &mdash; and another '
          'draws three walls concentric, the countries of the '
          'sky drifting in the middle passage. The binding&rsquo;s '
          'rule holds: recensions are variant manuscripts, '
          'never harmonized, and the traveler&rsquo;s working map '
          'is whichever her chronicle has paid for. One hazard the recensions share deserves the margin&rsquo;s asterisk: paradox taken on the wall confuses the taker&rsquo;s geography &mdash; she believes herself still in the country she left, the error compounding with the debt &mdash; and the fine pays itself off only with time, which the folio commends marking apart from the ordinary ledger.</p>\n'
          '        <p><span class="lemma">Where the paradox law '
          'ends.</span> The deep clause&rsquo;s plain sense: past '
          'the shell the court of 533a has no bailiff &mdash; the '
          'vulgar walks unfined &mdash; and the law names the '
          'price of the freedom in the same breath: the free '
          'country is the exile country, the mad and the '
          'fallen driven past the wall in living memory and '
          'building there, and the void itself collects what '
          'the court no longer can &mdash; the unshipped soul '
          'scatters. Freedom from consequence, the clause '
          'teaches, is not freedom from the dark; it is the '
          'dark&rsquo;s admission price.</p>',
 'inner_head': 'On the Shell<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the doors, the surcharge, and the '
               'deep</span>',
 'name': 'The Horizon',
 'outer': '<p><span class="lemma">Who raised the shell.</span> The '
          'origin dispute. <span class="voice">Some say</span> the '
          'agreement grew it: the shell is 62a&rsquo;s water frozen at '
          'altitude &mdash; the world believed itself small and grew a '
          'skin to match, the old close heavens receding as the new '
          'count took hold &mdash; and the telling of the turned glass '
          'is the case in miniature: an argument won on the ground '
          'rewrote the sky, which is this binding&rsquo;s whole '
          'physics applied upward. <span class="voice">Others '
          'say</span> the source itself scoffs and the scoff is '
          'evidence: the narrator rules the telling nonsense, the '
          'shell older than the telescope &mdash; and a wall that '
          'predates the argument said to have raised it acquits '
          'the argument; the moderns found the shell, mistook '
          'finding for making, and flattered their own era with '
          'the confusion. The first school answers that the '
          'wall of 82a also predates any single argument and is '
          'still made of argument &mdash; walls of belief are '
          'raised in courses, not at a stroke. The second '
          'answers that a theory which survives every possible '
          'evidence has stopped being a theory. The stakes run '
          'past cosmology into strategy: if consensus reaches '
          'the sky, the sky can be renegotiated &mdash; and both '
          'the Union&rsquo;s surveys and the ether-sailors&rsquo; '
          'old routes are bets on opposite answers. <span '
          'class="kw">TEYKU</span> &mdash; the shell, cored, dates '
          'to whichever century the corer believes in.</p>\n'
          '        <p><span class="lemma">What it was fitted '
          'against.</span> The purpose dispute. <span '
          'class="voice">Some say</span> mercy: the shell is the '
          'dreams&rsquo; own casing &mdash; it keeps the things that '
          'eat dreams from the sleeping world, and the '
          'testimony is the patrol&rsquo;s: the border corps of '
          '194a spend courage on that rampart nightly against '
          'an outside the folio declines to describe, and a '
          'wall so garrisoned is a wall with a wolf side. '
          '<span class="voice">Others say</span> quarantine, '
          'written from without: the law&rsquo;s own aside &mdash; '
          'that the shell probably protects the dark from us '
          '&mdash; is the confession filed in the definition, '
          'and the exile clause reads accordingly: the mad '
          'and the fallen were not locked out but locked '
          'away, with the rest of the agreement sealed in '
          'beside them for company. The first school answers '
          'that a quarantine does not post its sentries on '
          'the inside. The second answers that this is '
          'exactly where a competent warden posts them, and '
          'invites the reader to check where the patrol '
          'actually stands. The folio notes what the schools '
          'share &mdash; the shell was fitted against '
          'something, and neither school sleeps better for '
          'having named it &mdash; and files the question '
          'where the chapter&rsquo;s design wants it: in the reader&rsquo;s luggage, carried past the wall. And the schools&rsquo; shared homework is the chapter&rsquo;s hinge: a party that crosses will meet the wall&rsquo;s client before it meets home again &mdash; fifteen successes is a long time to wonder which theory was right &mdash; and the Storyteller who has decided the answer for her chronicle should still, the teachers ruled, let the wall collect first.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the mason again, and the client</span>',
 'rubric': 'the outer wall',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond, continued &middot; of the Horizon &middot; the shell as law',
 'title': 'Tractate Aliyah · Folio 109a — The Horizon: the outer wall',
 'type': 'daf'}
