# Folio 109b - The Made Countries. Realm law, per the wod-llm-wiki
# horizon-realm, shard-realms, and founding-of-horizon pages (M20
# pp.111-112, 127-135; The Infinite Tapestry pp.10-11; Horizon:
# Stronghold of Hope pp.39-46).
FOLIO = {'bottom': '<p><span class="lemma">On the realm as playground and '
           'trap.</span> The chantry-realm is both at once and should be run '
           'as both: a venue where the cabal&rsquo;s paradigm is simply true '
           '&mdash; let the players decorate, legislate, and rest &mdash; and a '
           'dependency with four anchors, every one of them a hostage. The '
           'table that loves its realm will defend it, and a defended home '
           'is the easiest campaign frame the line owns.</p>\n'
           '        <p><span class="lemma">On pricing the anchors.</span> '
           'Each anchor is a scenario on retainer: the node coveted, the '
           'portal watched, the earthly aspect burgled, the essence bill '
           'due. Rotate the threats and the realm stays load-bearing '
           'without ever being invaded &mdash; a siege is one story, but a '
           'lease is a chronicle.</p>\n'
           '        <p><span class="lemma">On the landlord.</span> A realm '
           'session needs somebody at home: a custodian, a charter, a '
           'house law the guests can trip over. The made country whose '
           'only furniture is the party&rsquo;s equipment is a set; give '
           'it a steward with opinions and the venue becomes a '
           'character &mdash; which is what the folio&rsquo;s law, with its '
           'maker&rsquo;s-death question, has been quietly assuming all '
           'along.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on homes, leases, '
                'and stewards</span>',
 'center': '<p class="noindent"><span class="dropcap">A</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">In the shell, countries are '
           'carved.</span> A <span class="term">realm</span> is a made '
           'place with made rules: hollowed from the outer wall by great '
           'workings or advanced technique, its local law rewoven until '
           'the place suits its maker &mdash; the grandest form of the '
           'covenant house, and the safest, for those who can pay '
           'it.<sup>a</sup> The law of standing is fourfold: a realm '
           'must be forged, fueled, attached, and connected &mdash; '
           'raised by power, fed with essence, rooted to a well, and '
           'tied to the world by doors and by earthly tokens that '
           'remember it &mdash; and a realm wanting any anchor folds '
           'inward or drifts loose into the deep.<sup>b</sup> A realm '
           'severed does not die cleanly: the husk persists as a <span '
           'class="term">ghost country</span>, peopled by the '
           'disembodied who do not know the doors are shut and believe '
           'themselves alive.<sup>c</sup> And the elder recension '
           'widens the register: the wandering stars themselves are '
           'counted shard-countries, one to each of the nine arts, and '
           'the world underfoot &mdash; the recension rules, and the '
           'binding files &mdash; is the shard of the first essence, '
           'the only one with tenants who deny it.<sup>d</sup> So the chapter closes as it opened: every country in the atlas is somebody&rsquo;s argument, and the best-kept are the ones that admit it.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear of the greatest of the made countries, whose '
           'raising the first folio of this binding already keeps: '
           'Horizon, the chamber agreed into being, six years in the '
           'raising &mdash; the founders&rsquo; wells dedicated as '
           'columns, the buried titan whose chains are its mountains, '
           'the three doors named for the Fates &mdash; as folio 2a '
           'tells it, and this page will not tell it twice. Add only '
           'the ledger&rsquo;s other column: the realm outlived its '
           'builders&rsquo; unity by five centuries and did not '
           'outlive their war &mdash; the histories record it leveled '
           'in the age&rsquo;s last convulsion, its survivors '
           'scattered &mdash; so the chapter&rsquo;s finest exhibit is '
           'also its ruin, and the law of anchors above should be '
           'read with the casualty list open. The disputants around '
           'this text hold whether the made country is escape or '
           'abdication, and whose law survives the maker.</p>',
 'chapter': 'Chapter the Fourth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter IV closes; the Traditions&rsquo; houses wait at '
             'folio 148, and the fallen countries&rsquo; war with the '
             'end-times, wanting.',
 'folio': '109B',
 'glossL': '<p><span class="mark">a</span> On the realm as a made place '
           'with made rules, carved and rewoven, see M20, folios '
           '111&ndash;112.</p>\n'
           '        <p><span class="mark">b</span> On the fourfold '
           'anchoring &mdash; forged, fueled, attached, connected, and '
           'the folding or drifting of the unanchored &mdash; see the '
           'same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'ghost countries and their disembodied tenants, see the '
           'same folios.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'shard-countries of the nine arts, see The Infinite '
           'Tapestry, folios 10&ndash;11 of that volume, and Masters of '
           'the Art, folios 53&ndash;54 of that volume; on the raising '
           'and fall of Horizon, see Horizon: Stronghold of Hope, '
           'folios 39&ndash;46 of that volume, and M20, folios '
           '127&ndash;135.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The raising is kept at '
           'folio 2a, whose chamber without Sleepers is this '
           'folio&rsquo;s law worked at its grandest; the citation runs '
           'forward from there to here, and the aggada is told once, '
           'as the binding&rsquo;s custom requires.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'fueling anchor is 78b&rsquo;s well law annexed past the '
           'sky: the realm eats from a node as the covenant house '
           'does, the tithe and the drought included, and the '
           'seizure of wells there is the fall of countries '
           'here.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'war that leveled the exhibit is filed with the end-times, '
           'wanting; the venue-law the realm perfects is 62b&rsquo;s '
           'flat option built out to a nation; and the chapter closes '
           'owing the atlas nothing but the histories.</p>',
 'h1': 'The Made Countries',
 'hagahah': 'Every paradise is somebody&rsquo;s argument, won.',
 'inner': '<p><span class="lemma">Made rules for made places.</span> The '
          'definition&rsquo;s plain sense: the realm is the '
          'venue-law&rsquo;s limit case &mdash; where 62b licenses a '
          'street&rsquo;s local weather, the realm is weather owned '
          'outright, the local reality rewoven until it suits &mdash; '
          'and the ownership is the point: within the walls the '
          'maker&rsquo;s paradigm is not dominant but true, the one '
          'jurisdiction where the argument needs no opponent. The covenant houses of every chapter aspire to this clause; the greatest reached it. And the grammar stays honest: a realm is a covenant house the way a nation is a household &mdash; the same law at a new order of magnitude, with the anchors below for a mortgage.</p>\n'
          '        <p><span class="lemma">Forged, fueled, attached, '
          'connected.</span> The anchor law&rsquo;s plain sense, '
          'counted on four fingers: raised by power sufficient to '
          'carve the shell; fed with essence on a schedule that '
          'never lapses; rooted to a well whose flow is the '
          'realm&rsquo;s pulse; and tied to the world twice over '
          '&mdash; doors that open both ways, and earthly tokens, '
          'walls or sigils or a van on the interstate, that '
          'remember the country into persistence. The fourth '
          'anchor is the strangest and the strictest: a made '
          'country is kept real by things that point at it, '
          'which is this binding&rsquo;s epistemology in '
          'masonry.</p>\n'
          '        <p><span class="lemma">Folds or drifts.</span> '
          'The failure clause&rsquo;s plain sense: the unanchored '
          'realm has two deaths &mdash; inward, the country '
          'collapsing on itself like an argument abandoned '
          'mid-sentence; or loose, the whole estate slipping its '
          'moorings into the deep with everyone aboard. Neither '
          'death announces itself; the anchors simply fail in '
          'the order nobody was watching, which is why the '
          'counsel below prices them as scenarios.</p>\n'
          '        <p><span class="lemma">The tenants who stayed '
          'on.</span> The ghost clause&rsquo;s plain sense: '
          'severance strands whatever the doors shut on, and the '
          'stranded keep house &mdash; the disembodied walk the '
          'halls, hold the offices, and believe themselves '
          'alive, a country running on the memory of its own '
          'law. The clause is the setting&rsquo;s best haunted '
          'house and its plainest warning: the realm&rsquo;s '
          'tenants are the fourth anchor&rsquo;s hostages, and the law counts them when the ledger does not. The recension adds the roll of causes &mdash; doors slammed in the age&rsquo;s convulsions, wells seized or burned &mdash; and the count of husks, once reckoned in dozens and perhaps hundreds, is remembered as the tuition the art paid for the anchor law above.</p>\n'
          '        <p><span class="lemma">The shard '
          'register.</span> The elder clause&rsquo;s plain sense, '
          'filed as variant: the recension that counts the '
          'wandering stars as shard-countries keyed to the nine '
          'arts is geography as theology &mdash; the sky a '
          'syllabus, each planet an art enthroned &mdash; and its '
          'sting is the last line: the world underfoot is the '
          'shard of the first essence, a made country like the '
          'rest, whose tenants alone insist their venue is the '
          'neutral ground. The binding files the register '
          'unharmonized and lets the sting stand.</p>',
 'inner_head': 'On the Anchors<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the four, the failures, and the '
               'shards</span>',
 'name': 'The Made Countries',
 'outer': '<p><span class="lemma">Escape or abdication.</span> The '
          'retreat dispute. <span class="voice">Some say</span> '
          'abdication: every master who moves the library past the '
          'sky removes a defender from the street &mdash; the war of '
          '46b is fought in the ordinary day, and a fellowship '
          'that perfects its paradise has conceded the venue that '
          'matters; the histories&rsquo; verdict is entered in '
          'evidence, for the made countries fell and the street '
          'remained, and the fellowships that survived are the '
          'ones that had kept shops on it. <span '
          'class="voice">Others say</span> escape is the wrong '
          'noun entirely: the realm is the argument won and '
          'banked &mdash; proof before witnesses that the paradigm '
          'can govern a world, sanctuary for what the street '
          'would burn, high ground from which the long war is '
          'supplied &mdash; and disarming your own capital because '
          'the enemy might besiege it is not strategy but '
          'stage fright. The first school answers with the '
          'casualty list: the capitals were besieged, and the '
          'proof-before-witnesses proved chiefly that anchors '
          'can be cut. The second answers that the street&rsquo;s '
          'survivors wintered in realms all the same, and that '
          'the school auditing paradise has never once declined '
          'the invitation. The folio notes the middle the '
          'histories actually wrote &mdash; the realms fell, the '
          'street held, and the new houses are built lower and '
          'closer to the ground &mdash; and files the lesson '
          'without gloating. <span class="kw">TEYKU</span> &mdash; '
          'the argument won, and the war lost, in the same '
          'exhibit.</p>\n'
          '        <p><span class="lemma">Whose law survives the '
          'maker.</span> The succession dispute. <span '
          'class="voice">Some say</span> the law dies with the '
          'will that spoke it: a made country is a held '
          'argument, and a realm whose legislator dies begins '
          'to forget itself &mdash; the weather wanders, the '
          'doors misremember their keys, and the drift toward '
          'the deep begins at the funeral; the ghost countries '
          'are the proof, law running on memory until the '
          'memory is all that is left. <span '
          'class="voice">Others say</span> a well-made law '
          'outlives its legislator as a city outlives its '
          'founder: the anchors hold whoever holds them, the '
          'realm keeps the rule and loses only the mercy '
          '&mdash; the discretion, the exceptions, the '
          'founder&rsquo;s hand on the scale &mdash; and the '
          'histories&rsquo; five centuries of Horizon after its '
          'founders are the counter-exhibit: the chamber '
          'held; only the charity aged. The first school '
          'answers that a law kept without mercy is the '
          'drift, measured socially instead of spatially. '
          'The second answers that this is true of every '
          'city on the street side of the wall as well, and '
          'asks why the made countries should be held to a '
          'higher standard than the found ones. The stakes '
          'are testamentary and the folio names them: every '
          'covenant house in this binding will someday be '
          'somebody&rsquo;s estate, and the table that decides '
          'early what its realm remembers &mdash; the rule, '
          'the mercy, or the maker &mdash; has written the will while the testator can still argue &mdash; which the teachers commended as the only estate planning the deeps have ever honored.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the retreat, and the estate</span>',
 'rubric': 'the countries carved in the shell',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fourth: The Worlds '
             'Beyond, concluded &middot; of realms, ghosts, and shards',
 'title': 'Tractate Aliyah · Folio 109b — The Made Countries: the realms in the shell',
 'type': 'daf'}
