# Folio 143b - The Stakes. Verso of certamen: enforcement, precedent,
# refusal, and the abolition question, per the wod-llm-wiki certamen and
# code-of-hermes pages (TBOoH Rev pp.37, 43-45; GttT pp.275-276).
FOLIO = {'bottom': '<p><span class="lemma">On staking what the table can '
           'afford.</span> The stake law is player-facing counsel in '
           'disguise: never let a duel stake what its loser cannot afford '
           'to keep playing without &mdash; the character&rsquo;s life, the '
           'concept&rsquo;s spine. Stake standing, access, favors, and '
           'objects; the campaign survives the verdict either way, which '
           'is the charter&rsquo;s whole point restated for the table.</p>\n'
           '        <p><span class="lemma">On pricing refusal in '
           'scenes.</span> When a challenge is declined, spend the price '
           'onscreen: the room that goes quiet, the invitation that stops '
           'arriving, the second who resigns. Standing is a currency the '
           'players cannot see on a sheet, so the Storyteller must mint it '
           'in scenes &mdash; a refusal priced in narration is drama; one '
           'priced in a lecture is homework.</p>\n'
           '        <p><span class="lemma">On the crowd as court.</span> '
           'Seat named witnesses at every duel and let them carry the '
           'verdict outward: who watched, who repeats it, who embellishes. '
           'The circle&rsquo;s enforcement runs on reputation, and '
           'reputation runs on scenes of telling &mdash; the duel is one '
           'session; its stake collects for a season.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on affordable stakes, '
                'priced refusals, and the telling</span>',
 'center': '<p class="noindent"><span class="dropcap">W</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">What the circle decides, who '
           'collects?</span> Within the Order, the law: the '
           'parameters of the match and the standing of its outcomes are '
           'fixed in the great commentary of amendments to the '
           'Order&rsquo;s code, and the code&rsquo;s own tenet bends its ban '
           'on harming a fellow exactly once &mdash; for the justly '
           'declared, open duel &mdash; so the victor&rsquo;s claim is a '
           'judgment, and the tribunals stand behind it.<sup>a</sup> '
           'Beyond the Order, the custom: the Council adopted the circle '
           'and not the code, so between the seats the stake binds by '
           'witness and standing &mdash; enforcement by reputation, which '
           'the wise call the only enforcement a parliament of nine '
           'paradigms can have. Persons may not be staked: the precedent '
           'that granted a victor a year and a day of the loser&rsquo;s '
           'service was granted once and overturned, for a form chartered '
           'to leave both parties living may not leave one of them '
           'owned.<sup>b</sup> The challenged may refuse, and the refusal '
           'is lawful and priced &mdash; paid in standing, not in blood, '
           'by honor&rsquo;s own ledger. And one custom no challenge may '
           'refuse: the inherited blades of the Houses enter the circle '
           'by right, their edge banded at the margin&rsquo;s '
           'grain.<sup>c</sup> The motion to retire the form entire stands '
           'on the docket, moved by the Order&rsquo;s own reformers and '
           'resisted by its own devout, and the law records the motion as pending.<sup>d</sup> So the verso counts the circle&rsquo;s teeth, and finds them real and few.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD the case of the year and a day. A quaesitor '
           'of standing ruled that the victor of a lawful match might '
           'collect the defeated herself &mdash; service, a year and a day '
           '&mdash; and for a season the ruling stood, and the circles '
           'filled with suitors who had inventoried their rivals. Then '
           'the Order looked at what it had licensed: a court chartered '
           'to end feuds was minting bondsmen. The ruling was overturned, '
           'the precedent filed with its reversal stapled to it, and the '
           'law learned the verso&rsquo;s lesson: a stake is safe only '
           'while it is smaller than the parties. The disputants hold '
           'what else the case teaches.</p>',
 'chapter': 'Chapter the First &middot; resumed and concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter I concludes a second time, far from its head: the '
             'circle&rsquo;s law on the recto, its teeth on this side; the '
             'Avot of chapter V stand overleaf.',
 'folio': '143B',
 'glossL': '<p><span class="mark">a</span> On the parameters and outcomes '
           'fixed in the Peripheral Corrigenda, and on the tenet excepting '
           'the justly declared, open cert&aacute;men from the ban on '
           'harming a fellow, see the Tradition Book of the Order of '
           'Hermes, revised recension, folios 37 and 43&ndash;44 of that '
           'volume.</p>\n'
           '        <p><span class="mark">b</span> On the precedent of the '
           'year and a day &mdash; granted by Guzman bani Quaesitor and '
           'since overturned &mdash; see the same volume, folio 45.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'Houses&rsquo; blades, whose entry no challenge may deny and '
           'whose edge is one success the turn, see the Guide to the '
           'Traditions, folios 275&ndash;276 of that volume, banded here '
           'per the standing rule.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'reform that would cycle the form from practice and at last '
           'outlaw it, and on those who cherish it among the Order&rsquo;s '
           'most venerable institutions, see the revised Tradition Book, '
           'folio 45.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The stake&rsquo;s cousin '
           'in Strife is 430b&rsquo;s wager, which will price stakes for '
           'every lesser form of contest; this verso keeps what the '
           'circle can enforce, and the Masoret marks the division as '
           'the recto marked its own.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'sentence-ladder behind the victor&rsquo;s claim runs to the '
           'unmaking whose law 2b keeps, and the tribunals that '
           'pronounce it are 3a&rsquo;s judgments: the verso&rsquo;s '
           'enforcement is the chapter&rsquo;s opening machinery, '
           'collected at last by the leaf that wandered.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'Etherites&rsquo; duel by demonstration, which will convene at '
           '160b, is this circle&rsquo;s cousin in a lab coat, and the '
           'consent tools of 384b will cite this folio&rsquo;s law; the '
           'Masoret posts both appointments and keeps the seats '
           'warm.</p>',
 'h1': 'The Stakes',
 'hagahah': 'The circle enforces nothing. The crowd around it enforces '
            'everything, which is why the crowd is in the protocol.',
 'inner': '<p><span class="lemma">Fixed in the amendments.</span> The '
          'first clause&rsquo;s plain sense: inside the Order the stake '
          'is a judgment &mdash; parameters set in the great commentary, '
          'outcome recorded, collection backed by the same tribunals '
          'that hang sentences on code-breakers. The duel is not an '
          'alternative to Hermetic law; it is a chamber of it, and the '
          'victor who cannot collect appeals like any other '
          'litigant.</p>\n'
          '        <p><span class="lemma">The tenet&rsquo;s one '
          'bend.</span> The exception&rsquo;s plain sense: the ban on '
          'harming a fellow bends for the duel and for nothing else, '
          'and the three qualifying words are the hinge &mdash; justly, '
          'so a pretext duel is still a crime; declared, so the '
          'grievance predates the blow; open, so the crowd is present '
          'before the parties can disagree about what happened. The '
          'law&rsquo;s narrowest door, and the counsel notes it swings '
          'both ways: everything outside it remains assault.</p>\n'
          '        <p><span class="lemma">Beyond the Order, the '
          'custom.</span> The adoption clause&rsquo;s plain sense: the '
          'Council took the circle and left the code, so between '
          'Traditions the stake binds by witness and standing &mdash; '
          'no tribunal reaches across paradigms, and none is needed '
          'while the seats must keep meeting. Reputation is '
          'enforcement by future dealings, and the counsel ranks it '
          'honestly: often stronger than the tribunal, for the '
          'tribunal ends at the Order&rsquo;s door and the crowd '
          'goes everywhere.</p>\n'
          '        <p><span class="lemma">The overturned year.</span> '
          'The precedent&rsquo;s plain sense: persons are not stakes. '
          'The case granted a victor the defeated&rsquo;s service and '
          'the reversal extended the charter&rsquo;s logic one step '
          '&mdash; resolved without killing became resolved without '
          'owning &mdash; and the counsel reads the season between '
          'grant and reversal as the institution&rsquo;s one recorded '
          'infection: the circle can be captured by what it '
          'licenses, and the cure was case law, not protocol.</p>\n'
          '        <p><span class="lemma">The lawful refusal.</span> '
          'The refusal clause&rsquo;s plain sense: declining is legal, '
          'always &mdash; the form runs on consent or it is not the '
          'form &mdash; and the price is paid in the softest, '
          'slowest currency the setting mints. Honor&rsquo;s ledger '
          'never forecloses; it only remembers, and the counsel '
          'notes the design&rsquo;s mercy: a law that priced refusal '
          'in blood would have re-invented the feud with extra '
          'steps.</p>\n'
          '        <p><span class="lemma">The blades&rsquo; right of '
          'entry.</span> The custom&rsquo;s plain sense: the inherited '
          'steel of the Houses enters any circle unchallenged, its '
          'edge real and banded at the margin&rsquo;s grain &mdash; '
          'lineage priced into the level field, openly. The counsel '
          'files the tension without resolving it: the same '
          'institution that levels rank at the bounds honors ancestry at the door, and the crowd has opinions. The custom&rsquo;s defenders answer that the blade is not rank but memory &mdash; steel that has kept the form&rsquo;s law longer than any living duelist &mdash; and that a court may honor its own history at the door it makes everyone use; the counsel files the answer beside the objection, at equal weight, which is where this folio keeps all its furniture.</p>',
 'inner_head': 'On the Enforcement<span class="comm-sub">the inner commentary '
               '&middot; the plain sense &middot; who collects, and '
               'how</span>',
 'name': 'The Stakes',
 'outer': '<p><span class="lemma">Whether the form should die.</span> The '
          'abolition dispute, moved by the Order&rsquo;s own. <span '
          'class="voice">Some say</span> the reformers have it: a '
          'dueling court is a relic wearing robes &mdash; might '
          'auditing right &mdash; and the modern Order should cycle '
          'the form from practice and at last outlaw it, as its own '
          'radicals openly move; an institution that must be '
          'apologized for at every convening has already lost its '
          'case. <span class="voice">Others say</span> the devout have '
          'it: the venerable institution is the peace &mdash; strike '
          'the circle and the disputes do not vanish, they go home '
          'to the feud the circle was built to replace, and the '
          'form is not violence but violence&rsquo;s containment '
          'vessel, kept polished precisely because it is old. The '
          'first school answers that containment which flatters '
          'violence perpetuates it &mdash; the duel keeps might '
          'prestigious, and prestige is the fuel. The second '
          'answers with the centuries: name the age that lacked '
          'the circle and kept the peace, and the reformers&rsquo; '
          'silence on this point is filed as evidence. The folio '
          'records the motion as the Order records it &mdash; '
          'pending, perennial, and closer to carrying than the devout admit. The stakes of the vote are the chapter&rsquo;s own: what the Council does with its inherited instruments is what the Council is, and the reformers know it, which is why the motion returns every convening like a tide. <span class="kw">TEYKU</span> &mdash; the '
          'docket holds the question; the circle, meanwhile, holds '
          'the peace, and both facts are true on the same '
          'afternoon.</p>\n'
          '        <p><span class="lemma">Whose court, at the '
          'last.</span> The enforceability dispute, the verso&rsquo;s '
          'deepest. <span class="voice">Some say</span> the stake '
          'between seats is a gentleman&rsquo;s fiction: no tribunal '
          'reaches across paradigms, the loser who walks away '
          'loses only face, and face regrows &mdash; so the '
          'cross-Tradition duel is theater whose verdicts bind '
          'exactly as long as both parties feel like it. <span '
          'class="voice">Others say</span> face is the hardest '
          'currency the Council mints: the seat that welches on a '
          'posted stake finds every door heavier at the next '
          'convening, every ally costlier, every witness ready '
          '&mdash; and enforcement by standing is not the weak form '
          'of law but its oldest, the kind that governed before '
          'tribunals and will govern after. The schools converge '
          'where the setting forces them to: the circle&rsquo;s '
          'verdicts run on the same substance as everything else '
          'in the binding &mdash; belief, jointly maintained &mdash; '
          'and a judgment the community holds is enforced by the '
          'community holding it. The folio closes the '
          'chapter&rsquo;s long parenthesis on that note: the Nine '
          'Seats opened with a convocation that was only words, '
          'and conclude with a court that is only standing, and both have outlasted empires built of harder stuff. The disputants append the note the shelf demands: every court in this binding &mdash; the Paradox court ahead, the tribunals behind, the seats themselves &mdash; enforces by the same two instruments, sentence and standing, mixed to taste; the circle merely runs on the leaner mix, and its survival is the standing half&rsquo;s proof of concept, entered into evidence for the whole shelf.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the docket, and the teeth</span>',
 'rubric': 'the enforcement of the circle',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First: The Nine Seats, '
             'resumed and concluded &middot; of the stakes &middot; enforcement, '
             'precedent, and refusal',
 'title': 'Tractate Aliyah · Folio 143b — The Stakes: the enforcement of the circle',
 'type': 'daf'}
