# Folio 143a - Certamen. Chapter I resumed at its number: the duel as
# legal process, per the wod-llm-wiki certamen and magickal-duels pages
# (TBOoH Rev pp.26, 37, 43-45; M20 pp.430-433; Masters of the Art p.42).
FOLIO = {'bottom': '<p><span class="lemma">On stakes before dice.</span> Run the duel '
           'as a suit, not a fight: the stakes named aloud, the witnesses '
           'seated, the marshall&rsquo;s protocol read &mdash; all before a die '
           'is lifted. A table that has watched the paperwork happen fights '
           'the duel over something, and the winner collects a scene '
           'instead of a number.</p>\n'
           '        <p><span class="lemma">On the circle as pressure '
           'valve.</span> The form is the chronicle&rsquo;s lawful outlet for '
           'player-against-player heat: when two characters genuinely '
           'collide, offer the circle before the campaign fractures. A '
           'grudge spent in certámen returns as story; a grudge spent in '
           'ambush returns as a second campaign, usually shorter.</p>\n'
           '        <p><span class="lemma">On casting the marshall.</span> '
           'Give the arbiter a face and one procedural obsession &mdash; the '
           'salute held too long, the stakes read twice &mdash; and the '
           'protocol becomes theater the players learn by watching. The '
           'circle is a court; courts run on clerks; and the clerk who '
           'stops a mistimed working with one raised hand is the '
           'institution characterized in a gesture.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on paperwork, valves, '
                'and clerks</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Two mages may make a court of a '
           'circle,</span> and the law calls it <span '
           'class="term">certámen</span>. Five things make the match '
           'lawful. The <span class="term">consent</span> of both, the '
           'challenge justly declared and open, for the unconsented duel '
           'is assault under every seat&rsquo;s law.<sup>a</sup> The <span '
           'class="term">stakes</span>, agreed beforehand and posted with '
           'witnesses and seconds to keep the match fair.<sup>b</sup> The '
           '<span class="term">arbiter</span>: marshalls, one to three, '
           'certified to the protocol they enforce. The <span '
           'class="term">circle</span> itself, bounded and built in the '
           'countries beyond the world, for the working is vulgar past any '
           'street&rsquo;s tolerance and the earthly match is undone by the '
           'court of another chapter in displays the books call '
           'theatrical.<sup>c</sup> And the <span class="term">yield</span>, '
           'which ends the matter with the stake and never the life &mdash; '
           'for the form&rsquo;s whole charter is the dispute resolved with '
           'both parties living, and the elder recension that fought it to '
           'the death is filed as the archmasters&rsquo; girsa, disturbing '
           'to witness and not this binding&rsquo;s baseline.<sup>d</sup> So '
           'the law runs: consent, stakes, arbiter, circle, yield &mdash; '
           'five clauses, one instrument, and the mystic&rsquo;s preference '
           'of Arts over force made procedure.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD the instrument&rsquo;s youth. In the '
           'Order&rsquo;s first days the theorist of theorists devised the '
           'form, and the cold house&rsquo;s founder mastered it &mdash; '
           'mastered it so thoroughly that his voice carried the '
           'convocations for a century, which the Order records without '
           'blushing, for its ethic says plainly that greater command of '
           'the arts remains the surest way to be heard. The Houses took '
           'to the circle because the alternative was the feud, and a feud '
           'between wizards has no natural end &mdash; only heirs. And when '
           'the nine seats convened, the Council took the Order&rsquo;s '
           'instrument for the same reason at a larger table: nine '
           'paradigms cannot share a war, so they were given a circle to '
           'share instead. And the record keeps the instrument&rsquo;s honesty about itself: the form was named in the old tongue for struggle, and the Order never pretended the circle abolished the contest of strength &mdash; it housed the contest, roofed it, and charged admission in protocol; the taming, not the denial, is the invention. The disputants around this text hold what the sharing is worth.</p>',
 'chapter': 'Chapter the First &middot; resumed at its number',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter I resumes here, one hundred and forty folios from its '
             'head, by the printers&rsquo; custom of numbering; the duel as '
             'institution on this side, its stakes and enforcement '
             'overleaf.',
 'folio': '143A',
 'glossL': '<p><span class="mark">a</span> On certámen devised in the '
           'Order&rsquo;s youth by Bonisagus and mastered by Tremere, and on '
           'the form as the dispute resolved without killing, see the '
           'Tradition Book of the Order of Hermes, revised recension, folio '
           '26 of that volume; the just declaration is the Code&rsquo;s own '
           'tenet, folios 43&ndash;44.</p>\n'
           '        <p><span class="mark">b</span> On the stakes agreed '
           'beforehand and the witnesses and seconds who keep the match '
           'fair, see M20, folio 430, with the preference of Arts over '
           'force at the same folio&rsquo;s head.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'circle built in the Horizon countries, the vulgar energies, the '
           'theatrical undoing of earthly matches, and the marshalls one to '
           'three, see M20, folios 432&ndash;433; the optional tactics are '
           'the Book of Secrets, folios 112&ndash;115 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'archmasters&rsquo; recension &mdash; the duel sometimes fought to '
           'the death, profoundly disturbing to witness &mdash; see Masters '
           'of the Art, folio 42 of that volume; the parameters fixed in '
           'the Order&rsquo;s own law are the revised Tradition Book, folios '
           '37 and 45.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The arena&rsquo;s machinery '
           '&mdash; the Locus, the two spheres, the banished art of slowed '
           'time &mdash; will be built at folio 430, where Strife keeps the '
           'old form; this leaf owns the courthouse and that one the '
           'arena, and the Masoret marks the division as standing.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'Council law this instrument serves is 2a&rsquo;s convocation '
           'and 3a&rsquo;s judgments, at the binding&rsquo;s head; that the '
           'chapter resumes here, a hundred and forty folios on, is the '
           'numbering&rsquo;s custom keeping its own counsel, and the '
           'Masoret files the strangeness rather than repairing it.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'circle&rsquo;s jurisdiction stands in the made countries of '
           '109a, one leaf back; the court that undoes the earthly match '
           'will hold session at 533a; and the seat that keeps the '
           'form&rsquo;s law will be seated at 158a, where the Houses '
           'convene.</p>',
 'h1': 'Certámen',
 'hagahah': 'The circle is the only place two paradigms agree, and what '
            'they agree to is to disagree formally.',
 'inner': '<p><span class="lemma">Consent of both.</span> The first '
          'clause&rsquo;s plain sense: the duel begins as a contract, and '
          'the three words of the declaration each bear load &mdash; <span '
          'class="aside">justly</span>, so the challenge is reviewable; '
          '<span class="aside">declared</span>, so there is no ambush '
          'wearing a salute; <span class="aside">open</span>, so the '
          'witnesses exist before the grievance needs them. A working '
          'flung at a rival without the declaration is not a duel lost '
          'but a crime committed, and every seat&rsquo;s law reads it '
          'so.</p>\n'
          '        <p><span class="lemma">The stakes, posted.</span> The '
          'second clause&rsquo;s plain sense: the stake is the '
          'suit&rsquo;s remedy, named before the dice so that victory '
          'has a meaning the crowd can audit. A duel without stakes is '
          'brawling with etiquette, and the seconds&rsquo; office is '
          'older than courtesy: they are the escrow in which the '
          'remedy sits while the circle decides.</p>\n'
          '        <p><span class="lemma">The marshalls.</span> The '
          'arbiter clause&rsquo;s plain sense: one to three, certified, '
          'empowered to stop the match on a breach &mdash; and their '
          'presence is the whole difference between a court and a '
          'field. The protocol they enforce is the institution&rsquo;s '
          'body: salute, bounds, tempo, the yield honored at once. '
          'Where no marshall can be had, the books&rsquo; counsel is '
          'blunt &mdash; what happens is not certámen, whatever the '
          'parties call it.</p>\n'
          '        <p><span class="lemma">The circle beyond the '
          'world.</span> The venue clause&rsquo;s plain sense: the form '
          'is exiled to the far countries because its energies are '
          'vulgar past pardon, and the exile doubles as a filter '
          '&mdash; the parties must be able to reach the courtroom, so '
          'the court&rsquo;s door has a rank. The counsel reads the '
          'filter honestly: the institution is the elite&rsquo;s, and '
          'the street&rsquo;s grudges are settled by the lesser forms '
          'another chapter will grade.</p>\n'
          '        <p><span class="lemma">The yield.</span> The fifth '
          'clause&rsquo;s plain sense, and the charter&rsquo;s heart: '
          'the yield ends the matter &mdash; stake collected, life '
          'kept, grievance legally dead. The elder recension that '
          'fought past the yield belongs to the archmasters&rsquo; '
          'girsa, and the baseline files it as warning, not option: '
          'a form that can kill is a feud with better lighting, '
          'which is precisely what the instrument was built to end. The grudge girsa the baseline does keep is fought to the pain, not the death: will staked beside essence, the loser waking emptied but waking, per the optional leaves the margin cites &mdash; the charter bending without breaking, and the marshalls still seated over every variant.</p>\n'
          '        <p><span class="lemma">What may not be staked.</span> The reserve, read from the charter: the life is not a stake, for the form exists to keep both parties living, and the person is not a stake, by the precedent the verso will try. Whatever else the parties post &mdash; standing, holdings, secrets, service short of servitude &mdash; the law leaves to the seconds&rsquo; escrow and the marshalls&rsquo; review. The reserve is short on purpose: a court that enumerated every forbidden stake would invite the reading that everything unlisted is fair, and the drafters knew their clientele.</p>\n'
          '        <p><span class="lemma">Alternative to feud.</span> '
          'The adoption clause&rsquo;s plain sense: the Council took '
          'the Order&rsquo;s instrument because feud between paradigms '
          'has no natural end, only heirs &mdash; and a parliament of '
          'nine standing grudges needed a drain. The circle is that '
          'drain, and the counsel notes what the Gemara implies: the '
          'institution&rsquo;s legitimacy is borrowed from the war it '
          'prevents, which is the strangest collateral in the '
          'binding.</p>',
 'inner_head': 'On the Process<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; five clauses, one '
               'instrument</span>',
 'name': 'Certámen',
 'outer': '<p><span class="lemma">Justice, or violence with '
          'paperwork.</span> The institution&rsquo;s trial, as the brief '
          'demands. <span class="voice">Some say</span> the form is '
          'law&rsquo;s triumph in miniature: consent, stakes, arbiter, '
          'review &mdash; every element of a suit, applied to the one '
          'quarrel courts cannot otherwise hear, and the proof is the '
          'charter itself: what would have been a killing becomes a '
          'judgment, collected and filed. <span class="voice">Others '
          'say</span> the paperwork is the costume and the violence is '
          'the body: the remedy goes to the stronger will, not the '
          'juster claim, and a court whose verdict tracks power '
          'instead of right is not a court &mdash; it is the war, '
          'miniaturized and rescheduled. The first school answers '
          'that every court on earth favors the capable &mdash; the '
          'richer litigant, the better advocate &mdash; and this one '
          'at least posts its bias in glowing spheres where the '
          'crowd can count it. The second answers that a bias '
          'posted is still a bias, and asks what the weak '
          'party&rsquo;s consent is worth on the day the strong party '
          'wants something. The folio files the institution as its '
          'own Order files it &mdash; venerable and suspect in the '
          'same breath, kept because the alternative is worse, '
          'audited because keeping is not trusting. One rider the disputants post from the record: the institution&rsquo;s best defense is not its justice but its bookkeeping &mdash; every match filed, every stake reviewed, every breach a precedent &mdash; for a violence that generates case law is at least learning, and the feud it replaced learned nothing in a thousand years. <span class="kw">TEYKU</span> &mdash; the circle holds; the '
          'question of what it holds instead of is the '
          'chapter&rsquo;s oldest, resumed here at its number.</p>\n'
          '        <p><span class="lemma">Dueling a superior.</span> '
          'The rank dispute. <span class="voice">Some say</span> the '
          'circle levels: within the bounds there is no degree, only '
          'excellence made visible, and the apprentice may call the '
          'master &mdash; which is the form&rsquo;s democratic genius '
          'and the Order&rsquo;s ethic stated as architecture, for '
          'greater command remains the surest way to be heard, and '
          'the circle is where the hearing happens. <span '
          'class="voice">Others say</span> the leveling is nominal '
          'and the architecture honest about it: the master '
          'manifests her rank in light, the summit defends itself '
          'by being the summit, and a court where the stronger '
          'party nearly always prevails is an org chart with '
          'dramatic lighting. The schools converge on the one thing '
          'the record supports: the challenge itself is speech. '
          'Even lost &mdash; especially lost &mdash; the declared suit '
          'is on the record, witnessed, and the grievance of the '
          'weak acquires what it never had before the circle: a '
          'date, a crowd, and a file. The form gives the low a rostrum if not a victory, and the folio notes that institutions have been founded on less. And the rank dispute&rsquo;s quiet coda: the masters know the arithmetic too, which is why the shrewd ones settle with apprentices before the circle is cut &mdash; the challenge they cannot lose in the arena they can still lose in the telling. And one boundary the folio leaves unruled: whether the sitting offices &mdash; the judges, the primi, the keepers of the code &mdash; may be called into the circle at all, the leaves on this binding&rsquo;s shelf do not say, and the folio files the question as wanting rather than guessing.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the costume, and the rank</span>',
 'rubric': 'the duel as law',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the First: The Nine Seats, '
             'resumed at its number &middot; of cert&aacute;men &middot; the duel '
             'as legal process',
 'title': 'Tractate Aliyah · Folio 143a — Certámen: the duel as law',
 'type': 'daf'}
