# Folio 148b - The Wheel. Verso of the Akashic Brotherhood folio: the law of return
# (reincarnation, the lukou bond, the teaching structure), per Lore of the
# Traditions via the wod-llm-wiki knowledge base.
FOLIO = {'bottom': '<p><span class="lemma">On playing a returning soul.</span> Reincarnation is a '
           'backstory engine with a safety catch, and the catch matters more than the engine. '
           'Establish in session zero how much past-life material the player authors and how '
           'much the Storyteller holds in reserve; a returned master whose old lives arrive '
           'entirely by Storyteller fiat is a puppet with a distinguished pedigree, and one '
           'whose player invents freely is a continuity dispute wearing robes. Split the '
           'difference in writing: the player owns who the soul was, the Storyteller owns what '
           'it left unfinished. And meter the remembering &mdash; a past life that returns all '
           'at once is exposition; one that returns at the wrong moments is a story.</p>\n'
           '        <p><span class="lemma">On the l&ugrave;k&#466;u as chronicle glue.</span> '
           'The intersection is the cleanest bond mechanic the setting offers a troupe: two '
           'player characters whose Avatars have met before solves the first-session problem '
           '&mdash; why do these strangers trust each other &mdash; with one word, and plants '
           'a mystery besides, since neither need remember why the bond is there or what it '
           'wants. Use the hateful form sparingly and on purpose: a l&ugrave;k&#466;u born of '
           'violent death, seeded between a player character and a recurring antagonist, is a '
           'feud with lifetimes of momentum, and it will bend every scene the two share until '
           'the table resolves it or dies trying. That is the point; budget for it.</p>\n'
           '        <p><span class="lemma">On procedure.</span> The Wheel is a doctrine, not a '
           'leash. A Storyteller who uses past lives to overrule a player&rsquo;s present '
           'choices &mdash; you must, because you once did &mdash; has inverted the '
           'Tradition&rsquo;s own teaching, in which the self is a habit and this life is the '
           'one being lived. Let the old lives inform, tempt, and haunt; never let them '
           'drive. The sangha&rsquo;s own rule below the mountain is the table&rsquo;s rule '
           'too: the student bows to the teaching, not the teaching to the student&rsquo;s '
           'yesterday.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on returning souls at the table, '
                'and on the bond as story</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Wheel turns,</span> and the Way&rsquo;s dead return to '
           'it: of each generation of the sangha, near half are old souls come back, and the '
           'sangha plans for their return as a house plans for winter.<sup>a</sup> Where two '
           'Avatars have met across lifetimes and the meeting marked them, the mark is called '
           'a <span class="term">l&ugrave;k&#466;u</span> &mdash; an intersection: a karmic '
           'bond, born of love or of violent death, and it holds until it is resolved '
           '&mdash; neither party need remember the bond for the bond to hold.<sup>b</sup> '
           'An old soul returns owing what it left owing: unfinished work comes back with '
           'the worker, and the monasteries keep registers of both. And the sangha owes the '
           'returned what it owes any student &mdash; a season, a school, a senior &mdash; '
           'and nothing it owes a ghost. The teaching keeps its own order. A <span '
           'class="term">bodhimandala</span> is kept by a master; the newly Awakened serve '
           'first a season among the monastics, learning what the Way is before choosing how '
           'to walk it; then each chooses a school freely, and a senior to learn from, and in '
           'time is chosen by juniors in turn.<sup>c</sup> Seniority is of the teaching, '
           'and every senior was junior first &mdash; in this life, which is the life the '
           'teaching addresses.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the '
           'planning for winter? <span class="kw">OUR TEACHERS TOLD:</span> a master of the '
           'forms died badly, mid-argument, her great correction of the spear-form unfinished '
           'and her temper unresolved. Eleven years later, in another country, a child in her '
           'first season stood up during drill and corrected the spear-form &mdash; the same '
           'correction, finished &mdash; and then asked, in a child&rsquo;s voice, who had '
           'won the argument. The elders did not celebrate; they assigned her the argument. '
           'The Wheel returns souls, not rank, and the sangha&rsquo;s bookkeeping of this '
           '&mdash; who is old, who is merely young, and what each is owed &mdash; is the '
           'quarrel that surrounds this text. And the Wheel checks no affiliations: enemies '
           'of the Way have died and come back walking it, and the gate of the folio '
           'overleaf was not built for that visitor.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy '
             'Old Style after the M20 interior &middot; verso of the Brotherhood&rsquo;s folio; '
             'the gate of 148a opens onto this Wheel.',
 'folio': '148B',
 'glossL': '<p><span class="mark">a</span> On reincarnation as central to the modern '
           'Brotherhood &mdash; near half of each generation returning &mdash; see the Lore of '
           'the Traditions chapter on the Akashayana.</p>\n'
           '        <p><span class="mark">b</span> On the l&ugrave;k&#466;u, the intersection '
           'binding two Avatars across lifetimes, see the same chapter; the word, the bond, '
           'and its two births &mdash; love and violent death &mdash; are treated there.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the bodhimandala, the '
           'monastic first season, and the teaching pairs of senior and junior, see the Lore '
           'of the Traditions account of the sangha&rsquo;s structure.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Avatar, whose business '
           'reincarnation properly is, see folio 43, which is wanting; on its destruction '
           '&mdash; the Wheel broken &mdash; folio 2b&rsquo;s sentence of Gilgul.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto keeps the Tradition&rsquo;s law and '
           'lineage; this verso keeps its dead. Read 148a&rsquo;s gate dispute first: the '
           'Wheel is that dispute&rsquo;s trapdoor, for the Way&rsquo;s enemies return '
           'walking it.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The Wheel is also the '
           'Chakravanti&rsquo;s word and their whole vocation &mdash; folio 156, which is '
           'wanting, will claim jurisdiction; the old war between the two houses was, among '
           'other things, a dispute over who keeps death&rsquo;s books.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Gilgul, tried at folio '
           '2b, is this folio&rsquo;s photographic negative: the sentence that stops a '
           'soul&rsquo;s returning is exactly as grave as this page says returning is.</p>',
 'h1': 'The Wheel',
 'hagahah': 'Half the sangha remembers dying for the Way. The other half must take their word '
            'for it. Seniority disputes proceed accordingly, and the minutes of those '
            'disputes are, of course, in the Record &mdash; all of them.',
 'inner': '<p><span class="lemma">Near half are old souls.</span> The plain sense is '
          'demographic, and startling: the Brotherhood are the one Tradition whose elders may '
          'be novices and whose novices may be elders, at a rate too high to treat as legend. '
          'At the table this means any Akashic character &mdash; player or otherwise &mdash; '
          'might carry prior lives, and the sangha&rsquo;s institutions assume it the way a '
          'harbor assumes tides.</p>\n'
          '        <p><span class="lemma">Plans for their return.</span> Not metaphor: '
          'schools keep unfinished work on purpose, teachers file their students&rsquo; '
          'unresolved questions, and a master&rsquo;s death opens a ledger entry rather than '
          'closing one. The bodhimandala&rsquo;s archives are half library, half '
          'left-luggage office, and the monastics&rsquo; first-season interviews of the '
          'newly Awakened are, among their gentler purposes, a customs inspection for '
          'arriving souls.</p>\n'
          '        <p><span class="lemma">Born of love or of violent death.</span> The two '
          'births are the same mechanism at two temperatures: a bond strong enough to '
          'outlast the body forms where two Avatars have mattered to each other absolutely '
          '&mdash; the beloved, and the killer or the killed. The law&rsquo;s word is <span '
          'class="aside">resolved</span>, not served or severed: a l&ugrave;k&#466;u ends '
          'when what formed it is finished, and no earlier, and the finishing is rarely what '
          'either party first supposes it to be.</p>\n'
          '        <p><span class="lemma">First a season among the monastics.</span> The '
          'apprenticeship&rsquo;s plain sense: roughly a year &mdash; sometimes months, '
          'sometimes several years &mdash; of history and philosophy before any school of '
          'practice may claim the newcomer. The season exists so that the choice of school '
          'is a choice, made by someone who knows what the Way is; the schools accept the '
          'delay because each believes, given a fair viewing, it is the obvious pick.</p>\n'
          '        <p><span class="lemma">Chooses a school freely.</span> Freely is load-'
          'bearing: no school owns the newly Awakened, no lineage inherits them, and a '
          'returning master&rsquo;s old school has no lien on the child she returns as. '
          'Where the recto&rsquo;s gate law faces outward, this clause is the gate&rsquo;s '
          'inward twin &mdash; the Way is not property inside the house either.</p>\n'
          '        <p><span class="lemma">Nothing it owes a ghost.</span> The clause is a '
          'kindness wearing a ruling&rsquo;s face: the returned are students, not revenants, '
          'and the sangha&rsquo;s duty is to the life being lived. No shrine is kept for the '
          'child who was a master, no deference paid to the body her soul used last, and no '
          'grief permitted to enroll her in a dead woman&rsquo;s quarrels &mdash; the '
          'registers hold the unfinished work until she comes asking for it, and not one '
          'day sooner.</p>\n'
          '        <p><span class="lemma">Seniority is of the teaching.</span> The pairs of '
          'senior and junior are offices of the relationship, not ranks of the soul: senior '
          'is whoever is senior to you, in this life, in this teaching, and the titles '
          'travel with the bow, not the birth certificate. What happens when the junior in '
          'the pair remembers teaching the senior&rsquo;s teacher &mdash; the disputants '
          'opposite have been waiting for exactly this case.</p>',
 'inner_head': 'On the Way, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; the Wheel&rsquo;s bookkeeping, clause by clause</span>',
 'name': 'The Wheel',
 'outer': '<p><span class="lemma">The Wheel returns souls, not rank.</span> So the Gemara, '
          'serenely; the houses are less serene. <span class="voice">Some say</span> the '
          'ruling is the only possible one: rank is of the teaching, the teaching is of this '
          'life, and a soul&rsquo;s past mastery is exactly as relevant as a champion&rsquo;s '
          'past body &mdash; honored, and gone. Let the returned master requalify; the forms '
          'will remember her if she is who she was. <span class="voice">Others say</span> '
          'the ruling wastes the Tradition&rsquo;s rarest asset to protect its org chart: a '
          'soul that carries a master&rsquo;s understanding is a master inconveniently '
          'housed, and making her repeat the ladder is seniority worshipping itself. An '
          'objection to the second view: understanding is not carried, it is rebuilt &mdash; '
          'the child corrected the spear-form and still asked who won the argument, which is '
          'to say she returned with the answer and not yet the question. <span '
          'class="voice">Answer:</span> then the ladder exists to rebuild questions, and '
          'the dispute is only over how fast a rebuilt master climbs &mdash; on which every '
          'bodhimandala rules differently, and the Record files every ruling, dissents '
          'included.</p>\n'
          '        <p><span class="lemma">Until it is resolved.</span> The hateful '
          'l&ugrave;k&#466;u is the hard case. <span class="voice">Some say</span> the bond '
          'born of violent death is a debt: the Wheel rejoins killer and killed until '
          'something is paid &mdash; confession, restitution, rescue, the debt names its own '
          'coin &mdash; and to flee the bond is to compound it. <span class="voice">Others '
          'say</span> a doom is not a debt: the bond is scar tissue, not a summons, and '
          'teaching the young that fate has assigned them a murderer to reconcile with is '
          'how a doctrine of harmony manufactures martyrs. The first reading makes the bond '
          'a duty and risks the martyr; the second makes it weather and risks the coward. '
          'The masters teach the first to the brave and the second to the reckless, which '
          'is not a resolution but is, its critics concede, pedagogy.</p>\n'
          '        <p><span class="lemma">The gate was not built for that visitor.</span> '
          'The enemy who returns walking the Way &mdash; the old court sorcerers who warred '
          'on the sangha for centuries now among its arrivals. <span class="voice">Some '
          'say</span> welcome, and completely: the Wheel outranks the gate, the Way was '
          'never property, and a soul the teaching claims is claimed &mdash; the recto&rsquo;s '
          'gate dispute is hereby answered from above, by management. <span '
          'class="voice">Others say</span> infiltration wears patience like a robe: an '
          'enemy house that has learned to arrive by being born will be inside every ward '
          'the sangha owns within three generations, and the monastics&rsquo; customs '
          'inspection had better be very good indeed. Note what neither side disputes: the '
          'visitors are already here. The argument is over locks, in a house whose doors '
          'the Wheel installed &mdash; and the monastics, who conduct the first '
          'season&rsquo;s interviews, decline to publish which answer their questions are '
          'built to catch.</p>',
 'outer_head': 'The Three Hands, at the Wheel<span class="comm-sub">the outer commentary '
               '&middot; three difficulties: the returned master, the hateful bond, and the '
               'enemy reborn</span>',
 'rubric': 'the law of return, and its bookkeeping',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, '
             'continued &middot; of the Wheel &middot; the Akashic Brotherhood&rsquo;s law of return',
 'title': 'Tractate Aliyah · Folio 148b — The Wheel: the law of return, and its bookkeeping',
 'type': 'daf'}
