# Folio 148a - The Akashic Brotherhood. The Phase-1 Avot-mold proof (SPEC section 7):
# Mishnah = the Tradition as law; Gemara = the chain of transmission,
# Pirkei Avot form; outer = the Tradition's internal factions arguing.
FOLIO = {'bottom': '<p><span class="lemma">On playing the Brotherhood.</span> The caricature arrives '
           'before the character does: shave the head, fold the hands, wait for the fight scene. '
           'Resist it. The Brotherhood of the books are librarians, medics, fencers, monks, '
           'programmers, and grandmothers, drawn from half the world&rsquo;s cultures and several '
           'of its quarrels, and the Way is what they share, not a costume. Two pitfalls '
           'deserve naming in session zero: the kung-fu cartoon, which reduces a contemplative '
           'tradition to its sparring wing; and the monolith, which melts a dozen distinct '
           'peoples and lineages into one vaguely eastern blur. The published material itself '
           'warns against both; the table should honor the warning, and the simplest tool is '
           'specificity &mdash; this character, this lineage, this teacher, this grudge.</p>\n'
           '        <p><span class="lemma">On the Record at the table.</span> A library of every '
           'life the Way has touched is a plot faucet, and faucets must be metered. Rule early '
           'on three things: what a reading costs (scenes of meditation, not a roll between '
           'rolls); how the Record answers (as memory answers &mdash; vividly, partially, and '
           'from a point of view, never as a database report); and who else notices the '
           'inquiry, for the shelf is shared and other readers have opinions about what you '
           'take down. A Storyteller who makes the Record cheap has replaced her mystery plots '
           'with a search engine; one who makes it vivid has gained a haunted archive that '
           'answers questions the character did not ask.</p>\n'
           '        <p><span class="lemma">On Do in the chronicle.</span> The art&rsquo;s '
           'reputation for imbalance precedes it; the measures themselves are tried at folio 423, and this page will not retry them. At the table the older '
           'problem is narrative: a master of Do makes ordinary violence boring, so stop '
           'offering ordinary violence. Stake the fights on something the fists cannot hold '
           '&mdash; a student watching, a vow not to strike first, a hall that must not be '
           'damaged &mdash; and the art becomes interesting again at any power level. Stakes '
           'on the table before the first stance; the duel law of folio 143 says the same, and said it first.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on stereotype and specificity, the '
                'Record as plot, and the Way at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Akashic Brotherhood hold</span> that mind is prior: body, breath, '
           'and thought are one motion, and the self is a habit that training unlearns.<sup>a</sup> '
           'Their practice is <span class="term">Do</span>, the Way entire &mdash; meditation, '
           'medicine, calligraphy, and the arts of war as one curriculum, of which combat is a '
           'wing and not the house.<sup>b</sup> Their instruments are the body and its '
           'disciplines: breath, stance, fast, drill, and the question sat with until it opens. '
           'Their seat among the Nine is <span class="term">Mind</span>. They are many peoples, many '
           'lineages, and several old quarrels walking one Way &mdash; some urge the pan-Asian '
           'name <span class="term">Akashayana</span> for the whole, and the urging is argued '
           'below; the Way is what is shared, and the law requires nothing else to be.</p>\n'
           '        <p>Their internal law is twofold. The <span class="term">Akashic '
           'Record</span>: every action, thought, and intent &mdash; past, passing, and to '
           'come &mdash; leaves its imprint in the primal emptiness, and the trained may reach '
           'that imprint in meditation: in fleeting parts, never in full, and never to revise '
           'it.<sup>c</sup> And the Way is taught within the sangha only; what leaves the '
           'house leaves it by ruling, not by accident.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Way was received '
           'on the mountain, and the mountain handed it to the monasteries; the monasteries '
           'handed it to the roads, and the roads handed it to whoever walked them well. It met '
           'the death-mages in the high passes and warred with them for centuries, and the '
           'grief of that war is still kept &mdash; folio 156 keeps it '
           'too. It sent walkers west when the West convened, and took a chair at the '
           'Convocation with the ink of that grief not yet dry, and it has held the chair of '
           'Mind through scattering, empire, and exile since. <span class="kw">OUR TEACHERS '
           'TOLD:</span> a seeker climbed to a master and demanded the Way&rsquo;s first '
           'lesson. The master poured tea until the cup ran over, and kept pouring, and said '
           'nothing. The seeker shouted that the cup was full. <span class="aside">So are '
           'you,</span> said the master, and that was the first lesson, and the seeker stayed '
           'nine years. The disputants around this text have been arguing about the second '
           'lesson ever since.</p>',
 'chapter': 'Chapter the Fifth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; first of the nine Avot folios; its eight siblings follow at 150 through 164 &middot; teyku &mdash; let the gate stand open or shut.',
 'folio': '148A',
 'glossL': '<p><span class="mark">a</span> On the Akashic Brotherhood entire &mdash; paradigm, practice, '
           'history, and the modern sangha &mdash; see M20, the Traditions chapter, folio 148, '
           'whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On Do as curriculum and combat art, see '
           'M20&rsquo;s martial-arts material and its cautions; the measures are tried at folio 423.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Akashic Record &mdash; '
           'the karmic repository of all action and intent, read in fleeting parts, never in '
           'full &mdash; see the Tradition&rsquo;s M20 entry and the Lore of the Traditions '
           'chapter on the Akashayana.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the sects here called the '
           'fist, the eye, and the open hand &mdash; and the roles the modern books add &mdash; '
           'see the same entries; the names vary by recension, the argument does not.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The chair was taken at the Convocation of '
           'folio 2a, with the war against the Chakravanti (folio 156) barely '
           'cold; the Council seated two enemies and called it peace, and it held.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The fist&rsquo;s '
           'coincidence is tried at folio 533a: a master&rsquo;s strike is witness-proof, for '
           'the bystander sees only skill. As folio 3a says of all law &mdash; this too is the '
           'law of who is watching, and practice is witness-management perfected.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The seat&rsquo;s Sphere is '
           'tried at folio 519; the duel law this folio&rsquo;s masters are '
           'forever being challenged under is folio 143, bound at its wandering number.</p>',
 'h1': 'The Akashic Brotherhood',
 'hagahah': 'The Akashic Record preserves, complete and consultable, every argument the '
            'Brotherhood has ever held about what the Akashic Record is. Consulting it does not '
            'settle the question. It adds the consultation.',
 'inner': '<p><span class="lemma">Mind is prior.</span> The paradigm&rsquo;s plain sense at the '
          'table: an Akashic effect is a perfected action, not an imposed exception. The '
          'brother does not bend the world; he removes the clumsiness between intention and '
          'act, and what remains looks like skill because it is skill &mdash; distilled past '
          'what training alone could reach. Frame every working this way and half the '
          'Tradition&rsquo;s coincidence problems solve themselves before the dice come '
          'out.</p>\n'
          '        <p><span class="lemma">One motion.</span> The unity clause does real work: '
          'body, breath, and thought are not three instruments but one, which is why the '
          'Tradition&rsquo;s magick runs through posture and respiration rather than wand and '
          'circle. It is also why the paradigm travels light philosophically &mdash; a member '
          'may keep any faith or none, so long as the practice is the practice; the Way '
          'describes how to walk, not what waits at the end.</p>\n'
          '        <p><span class="lemma">Of which combat is a wing.</span> Play the whole '
          'house. The healer setting bones by feel, the archivist in meditation, the cook whose '
          'kitchen runs like a kata &mdash; all are practicing Do as fully as the duelist, and '
          'a character built only for the sparring wing has packed one book for a long '
          'journey. The fights will come regardless; the Way is what the character does '
          'between them.</p>\n'
          '        <p><span class="lemma">The body and its disciplines.</span> The instrument '
          'law&rsquo;s plain sense: nothing to confiscate, nothing to forget in the other '
          'coat. Customs cannot seize breath, and the naked-cell scene that disarms every '
          'other Tradition leaves the Brotherhood approximately as dangerous as before. The '
          'price sits on the other side of the ledger: the toolkit took years the other '
          'Traditions spent elsewhere, and the body&rsquo;s limits &mdash; fatigue, injury, '
          'age &mdash; are the toolkit&rsquo;s limits too.</p>\n'
          '        <p><span class="lemma">In fleeting parts, never in full.</span> The Record '
          'at plain sense: a library, not an oracle &mdash; though it shelves even tomorrow. '
          'Its scope is total: what was done, what is being done, what will be done, and how '
          'the universe received each. What it refuses is browsing. There is no index and no '
          'whole view; deep meditation yields glimpses, and what a glimpse yields is an '
          'act&rsquo;s karmic weight &mdash; the measure the Way steers by. Reaching it is a '
          'discipline with a posture and a cost; the procedure belongs below the page, with '
          'the Later Authorities.</p>\n'
          '        <p><span class="lemma">Never to revise it.</span> Note the asymmetry: the '
          'Record is written by living and edited by no hand, which makes it the one '
          'incorruptible witness in a setting run on witness-management. What a brother did '
          'is written as the universe received it, including what he would pay to unwrite. '
          'And yet no reader has ever held the whole; the Tradition&rsquo;s elders are '
          'therefore the setting&rsquo;s rarest thing &mdash; an institution that cannot lie '
          'to itself about its history, only argue over glimpses of it.</p>\n'
          '        <p><span class="lemma">Taught within the sangha only.</span> The plain '
          'sense is custody, not secrecy for its own sake: forms taught without their '
          'discipline maim their students, and the gate exists first as medicine. Whether the '
          'gate is also something less noble is the disputants&rsquo; business, directly '
          'opposite.</p>',
 'inner_head': 'On the Way<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; playing the paradigm, clause by clause</span>',
 'name': 'The Akashic Brotherhood',
 'outer': '<p><span class="lemma">Of which combat is a wing.</span> Then which wing bears the '
          'house? <span class="voice">The fist says:</span> the Way survived because warriors '
          'died for it &mdash; against the death-mages in the passes, against the Union in the '
          'cities &mdash; and a Way that cannot defend its students is a beautiful epitaph. '
          '<span class="voice">The eye answers:</span> the fist remembers the wars and forgets '
          'what they were fought to protect; the Record is the treasure, the library is the '
          'house, and a fist is a rough bookmark. <span class="voice">And the open hand '
          'says:</span> a Way that cannot walk in the market is a museum piece in either '
          'case &mdash; the world is made of ledgers and negotiations now, and the sangha '
          'that will not sit at those tables abandons them to the Syndicate. Each hand '
          'accuses the others of mistaking its wing for the house; the house, meanwhile, '
          'stands on all three and creaks.</p>\n'
          '        <p><span class="lemma">Taught within the sangha only.</span> The '
          'gate dispute, and the folio&rsquo;s hardest. <span class="voice">Some say</span> '
          'the gate betrays the Way it guards: a truth about mind and motion is not the '
          'sangha&rsquo;s property, and hoarding a universal medicine is not custody but '
          'avarice with a liturgy. <span class="voice">Others say</span> the gate is the '
          'teaching: unearned forms kill their students &mdash; slowly, by making them '
          'confident &mdash; and the first thing the Way teaches is that sequence matters. '
          'An objection to the openers: the discipline is also the key to the Record, and '
          'the Record shelves everything &mdash; teach a stranger the Way and you have '
          'taught him to read the world&rsquo;s private ledger. <span '
          'class="voice">Answer:</span> then say '
          'so honestly &mdash; the gate guards the library, not the students &mdash; and '
          'give up the medical argument. The objection to the gatekeepers cuts as deep: '
          'every reason given for the gate was once given for keeping scripture in a '
          'language the people could not read. <span class="kw">TEYKU</span> &mdash; the '
          'gate stands, and the argument stands at the gate.</p>\n'
          '        <p><span class="lemma">Never in full.</span> A quieter dispute, with '
          'teeth. <span class="voice">Some say</span> the Record settles history: it cannot '
          'be revised, and an unrevisable witness is the end of every argument. <span '
          'class="voice">Others say</span> what cannot be revised can still be misread, and '
          'must be &mdash; every consultation is a glimpse, taken from inside one life and '
          'one discipline. The war in the passes reads differently to the monk who buried '
          'students and to the death-mage&rsquo;s reformed grandson; both consulted truly, '
          'and both came back partial. The eye&rsquo;s scholars have built '
          'a discipline on reconciling testimonies; the fist observes that the '
          'reconciliations also get written down, and also disagree. <span class="voice">Some '
          'conclude</span> that the Record is the Way&rsquo;s humility lesson in archive form '
          '&mdash; perfect memory, imperfect knowers &mdash; and that this is the point. Others '
          'conclude only that the eye needs more shelves. The dispute is gentle by this '
          'folio&rsquo;s standards: no one has struck anyone over it in living memory, which '
          'among the Nine Traditions may be the Record&rsquo;s finest verified effect.</p>',
 'outer_head': 'The Three Hands<span class="comm-sub">the outer commentary &middot; the fist, '
               'the eye, and the open hand &middot; and the dispute at the gate</span>',
 'rubric': 'the Way, its keepers, and its gate',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions &middot; '
             'of the Akashic Brotherhood &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 148a — The Akashic Brotherhood: the Way, its keepers, and its gate',
 'type': 'daf'}
