# Folio 150a - The Celestial Chorus. Avot mold; facts per the wod-llm-wiki
# Celestial Chorus page (M20 pp.150-151; Lore of the Traditions ch.2).
FOLIO = {'bottom': '<p><span class="lemma">On playing a Singer.</span> The pitfall is piety as costume: a '
           'Chorister reduced to a collar and a disapproval. The books&rsquo; own Choristers are '
           'heretics first &mdash; every one of them defied an orthodoxy to stand in this choir, '
           'and a character who has never argued with her own creed has skipped the '
           'Tradition&rsquo;s admission exam. Give her a faith with a wound in it and convictions '
           'that cost something, and the Chorus plays itself; give her a pulpit and she plays a '
           'lecture. Note too that a Singer need not be devout in any recognizable way &mdash; the '
           'books admit the doubter who is certain only that the universe cares, and that '
           'character is often the most interesting voice on the sheet.</p>\n'
           '        <p><span class="lemma">On the One at the table.</span> Do not adjudicate '
           'theology. The Storyteller who rules on what the One is has answered a question the '
           'Tradition itself has kept open for thirty centuries, and has flattened the '
           'folio&rsquo;s whole dispute into set dressing. Let Prime workings succeed, let prayers '
           'be answered ambiguously, and let every answer support both readings &mdash; the being '
           'and the song. The Chorus&rsquo;s faith should be load-bearing and unprovable at once; '
           'that tension is the character sheet&rsquo;s real engine.</p>\n'
           '        <p><span class="lemma">On procedure.</span> The Chorus makes an excellent '
           'chronicle frame precisely because it is an institution: committees, missions, '
           'inquiries, and a hierarchy recently and incompletely reformed. Use the machinery. A '
           'cabal sent by an assembly with a mandate and a budget has stakes before the first '
           'scene, and the machinery&rsquo;s creaks &mdash; the old guard, the watchdogs, the '
           'zealots the reform expelled &mdash; supply antagonists no other Tradition can: enemies '
           'who share the character&rsquo;s hymnal.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on faith as engine, and on the choir '
                'as institution</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Celestial Chorus hold</span> that the One is real and is '
           'sung by many: the Song has many harmonies, and a soul of any creed may carry the '
           'tune.<sup>a</sup> Their practice is the high rite of faith &mdash; prayer, sacrament, '
           'blessing, and above all <span class="term">song</span>, many voices in harmony; their '
           'instruments are the instruments of worship: the candle, the fast, the hymn, the '
           'consecrated place. Their seat among the Nine is <span class="term">Prime</span>, for '
           'they claim the first Sphere as first matter of the divine.<sup>b</sup></p>\n'
           '        <p>Their internal law is a law of harmony and heresy. No creed commands the '
           'choir, and no Singer commands a creed &mdash; the offense the law knows is not wrong '
           'belief but <span class="term">discord</span>: the voice that would silence other '
           'voices. Discord is tried by the body of the faithful, and its sentences run from '
           'correction to expulsion; and the choir keeps watchers against the <span '
           'class="term">Dark Singers</span>, whose song is the Song inverted.<sup>c</sup> The '
           'choir&rsquo;s offices are of service, not dominion: catechumen learns from praecept, '
           'congregation answers to presbyter and exarch, and the whole answers to the assembled '
           'voice of all &mdash; the reformation overleaf remade the summit of this order, and '
           'left the base standing, for the base was never the problem.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Song was received '
           'whole, say the Singers, and has been gathering its scattered voices since the '
           'Shattering. It was carried by congregations under empires that burned them, and by '
           'empires that carried it burning others &mdash; the choir remembers both, or is '
           'learning to. A bishop of France gathered the quarreling voices and made peace with the '
           'pagans he was taught to hunt, and brought one choir to the Convocation, and sat it in '
           'the seat of Prime; the histories of folio 2a name him.<sup>d</sup> <span '
           'class="kw">OUR TEACHERS TOLD:</span> a catechumen asked her praecept which creed the '
           'One prefers. The praecept set a psalm before her in four languages and asked which '
           'column the poem lived in. She began to answer and stopped. <span '
           'class="aside">Sing,</span> said the praecept, and that was the lesson &mdash; though '
           'the disputants opposite have never accepted that it settled anything.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; second of the Avot; its verso carries the '
             'choir&rsquo;s reformation.',
 'folio': '150A',
 'glossL': '<p><span class="mark">a</span> On the Celestial Chorus entire &mdash; the Song, the '
           'harmonies, the bloodied history of tolerance &mdash; see M20, the Traditions chapter, '
           'folio 150, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On prayer, sacrament, and song as instruments, '
           'see the Revised Tradition book&rsquo;s treatment of the Singers&rsquo; focus and the '
           'Lore of the Traditions chapter.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Dark Singers and the '
           'assemblies kept against them, see the Lore of the Traditions account of the reformed '
           'choir&rsquo;s structure.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Valoran, who unified the '
           'Messianic Voices and presented one choir in 1461, see the histories cited at folio 2a '
           'and the Chorus&rsquo;s own Book of Ages.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 520, '
           'which is wanting; the life-blood it governs at folio 78, likewise. The choir&rsquo;s '
           'claim &mdash; that Prime is the divine substance &mdash; is a paradigm, and folio 2a '
           'rules that no one compels one.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The choir&rsquo;s knightly '
           'order of old became the watchers of the Union &mdash; the New World Order&rsquo;s '
           'ancestry runs through the Cabal of Pure Thought, folio 188. The Chorus does '
           'not sing about this. The Masoret does.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The reformation of the choir '
           '&mdash; its doctrines, its Great Return, its departed hardliners &mdash; is the '
           'verso&rsquo;s whole subject, overleaf at 150b.</p>',
 'h1': 'The Celestial Chorus',
 'hagahah': 'The choir argues in harmony. This is not a metaphor: the argument has parts, keeps '
            'time, and resolves at the cadence &mdash; and then begins again at the top of the '
            'page, as harmony does. It is still arguing.',
 'inner': '<p><span class="lemma">The One is real and is sung by many.</span> The paradigm&rsquo;s '
          'plain sense at the table: a Chorister&rsquo;s magick is participation, not command. She '
          'does not compel the world; she joins its standing music and lends her voice weight, '
          'which is why her workings read as blessing, answered prayer, and improbable grace '
          '&mdash; and why they ride coincidence so well. A congregation believes in answered '
          'prayers; the bystander of folio 533a balks at nothing he has seen in church.</p>\n'
          '        <p><span class="lemma">A soul of any creed.</span> The clause that costs the '
          'most and defines the choir: every Singer is a heretic somewhere. The Tradition&rsquo;s '
          'tolerance is not softness; it is a doctrine bought with martyrdoms, held against every '
          'orthodoxy including its members&rsquo; own. Play the friction &mdash; the '
          'character&rsquo;s creed and the choir&rsquo;s breadth should pinch somewhere, or the '
          'concept is wasted.</p>\n'
          '        <p><span class="lemma">Above all song.</span> The instrument law&rsquo;s plain '
          'sense: the Chorus&rsquo;s tools are congregational, and the Tradition is strongest '
          'where voices gather. The books make this mechanical as well as liturgical &mdash; '
          'fellow believers lend real weight to a working &mdash; and the strategic consequence is '
          'a Tradition that builds communities as other Traditions build laboratories. Isolate a '
          'Singer and you have disarmed half her kit.</p>\n'
          '        <p><span class="lemma">Not wrong belief but discord.</span> The heresy '
          'law&rsquo;s plain sense, and its genius: a court that judged doctrine would shatter '
          'this Tradition in a season, so the law judges conduct toward other voices instead. The '
          'zealot who anathemizes a sister creed is triable; the mystic whose theology is frankly '
          'bizarre is not. Note the one theological exception, the Dark Singers &mdash; where the '
          'song is sung to unmake singing, the choir&rsquo;s tolerance ends, and its watchers hold '
          'jurisdiction the folio of the Fallen will map.</p>\n'
          '        <p><span class="lemma">The seat of Prime.</span> Why this Sphere, of all nine, '
          'for the faithful? Because Prime is the Sphere of first substance, and the choir&rsquo;s '
          'whole claim is that first substance sings. The claim is paradigm, not law &mdash; the '
          'gloss beside the text says so &mdash; but it makes the Chorus the Council&rsquo;s '
          'theologians of Quintessence, and their quarrel with the Union&rsquo;s accountants over '
          'the same Sphere is tried where the Syndicate&rsquo;s folio falls.</p>\n'
          '        <p><span class="lemma">From correction to expulsion.</span> The discord '
          'procedure&rsquo;s plain sense: the offense is tried by the offender&rsquo;s own '
          'congregation first, fraternally and in private; appeal runs upward through the regional '
          'bodies; and expulsion &mdash; the choir&rsquo;s only capital sentence &mdash; is '
          'pronounced by the whole assembled, rarely, and mourned like a death, because it is one: '
          'the expelled Singer keeps her Arts and loses her choir, and the Tradition&rsquo;s '
          'theology has no word for a voice singing alone that is not also a warning. Contrast the '
          'Union&rsquo;s erasures, chapter VI; the choir&rsquo;s worst sentence leaves the '
          'sentenced alive, visible, and grieved for, which the Singers count as the whole '
          'difference between a church and a machine.</p>',
 'inner_head': 'On the Song<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; playing the choir, clause by clause</span>',
 'name': 'The Celestial Chorus',
 'outer': '<p><span class="lemma">The One is real.</span> But what is it? <span class="voice">Some '
          'say</span> a being: the One is someone &mdash; a will, a person, a You to whom prayer '
          'is conversation and from whom the Song descends. The monotheist reading, and the plain '
          'sense of every scripture the choir salvaged its members from. <span class="voice">And '
          'some say</span> the sum of the singing: the One is what all voices make together, no '
          'more separable from the singers than a chord from its notes &mdash; the ecumenical '
          'reading, and the only one on which &ldquo;many harmonies&rdquo; is literally true '
          'rather than generously false. An objection to the first: then the creeds contradict, '
          'and one of them is right, and the choir&rsquo;s tolerance is diplomatic fiction. <span '
          'class="voice">Answer:</span> a being may be sung badly in a thousand true ways; ask any '
          'subject of a portrait. An objection to the second: then prayer is the choir talking to '
          'itself. <span class="voice">Answer:</span> and has the objector never been answered by '
          'a room? The dispute is the Tradition&rsquo;s oldest possession; both readings fill '
          'pews; the Mishnah, note well, rules only that the One is <span '
          'class="aside">real</span>.</p>\n'
          '        <p><span class="lemma">And by empires that carried it burning others.</span> '
          'The history dispute, nearer the bone. <span class="voice">Some say</span> the imperial '
          'centuries are a wound the choir has dressed: the Tradition owned its crusades, expelled '
          'its militants, returned what its missions took &mdash; the verso carries the accounting '
          '&mdash; and a body should be judged by its repentance as much as its record. <span '
          'class="voice">Others say</span> the accounting is not closed by the debtor: '
          'universalism preached from the old cathedrals still arrives wearing their stones, and '
          'the peoples the missions burned are not obliged to hear the new humility as different '
          'music. The first reading honors real reform; the second explains why the '
          'Kha&rsquo;vadi, two folios hence, still seat themselves at the far end of the table. '
          'Both are true, which is why the argument is good.</p>\n'
          '        <p><span class="lemma">Sing, said the praecept.</span> And is the maaseh a '
          'ruling or an evasion? <span class="voice">Some say</span> it settles the question the '
          'only way it can be settled: the Song is prior to its languages, and the lesson is that '
          'theology is commentary on music, not the reverse. <span class="voice">Others say</span> '
          'the praecept changed the subject beautifully, as praecepts do, and the '
          'catechumen&rsquo;s question &mdash; which creed does the One prefer &mdash; waits in '
          'the choir loft to this day, patient as all unanswered questions are. The tractate '
          'observes only that both parties went on singing, which may be the ruling after all. A '
          'late objection, from the doubter&rsquo;s pew: the Mishnah rules the One <span '
          'class="aside">real</span> &mdash; on what evidence? <span class="voice">Answer:</span> '
          'on the working&rsquo;s: Prime answers the Song, nightly, verifiably. <span '
          'class="voice">Rejoinder:</span> Prime answers the Etherites too, and their folio is two '
          'leaves on; the evidence proves the singing works, not whom it reaches. The choir has '
          'heard this rejoinder for thirty centuries and calls it, without irony, the descant.</p>',
 'outer_head': 'The Harmonies<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the One, the empire, and the lesson</span>',
 'rubric': 'the Song, its singers, and its discords',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Celestial Chorus &middot; the Tradition as law, its lineage as '
             'aggada',
 'title': 'Tractate Aliyah · Folio 150a — The Celestial Chorus: the Song, its singers, and its '
          'discords',
 'type': 'daf'}
