# Folio 150b - The Reformation. Verso of the Chorus folio: the modern
# reform, per Lore of the Traditions ch.2 via the wod-llm-wiki.
FOLIO = {'bottom': '<p><span class="lemma">On playing the aftermath.</span> A freshly reformed institution '
           'is the best chronicle furniture the Chorus has ever offered. Committees with new names '
           'and old members; returned treasures whose recipients did not ask for the ceremony; '
           'hardliners who left loudly and correspond with those who stayed &mdash; every one of '
           'these is a scene, and none requires an antagonist more exotic than a colleague. Set a '
           'Chorus cabal to execute some clause of the reform in one particular place &mdash; '
           'return this one relic, close this one mission, merge these two congregations &mdash; '
           'and the campaign writes itself out of the friction between the doctrine and the '
           'parish.</p>\n'
           '        <p><span class="lemma">On the departed.</span> The hardliners who left for the '
           'Templars are the rare antagonist with a complete moral argument: they kept faith with '
           'the choir the reform dissolved, and they can quote the old hymnal at the heroes with '
           'perfect accuracy. Use them sparingly and never as cartoons; the scene where the zealot '
           'is partly right is worth ten where he is simply armed.</p>\n'
           '        <p><span class="lemma">On the edge of the song.</span> The Apocalyptics '
           'deserve care disproportionate to their page count. A faction seeking union with the '
           'One through annihilation sits one doctrinal inch from the Dark Singers the choir '
           'hunts, and the table&rsquo;s horror budget should spend that inch deliberately &mdash; '
           'as tragedy or as threat, not as both by accident. Decide before they appear whether '
           'the chronicle&rsquo;s Order of Naught is sick, seduced, or seeing something; the three '
           'stories do not mix.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on reform as chronicle, and on the '
                'choir&rsquo;s dangerous margins</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The choir reformed itself</span> in living memory, and the '
           'reform is law. Five doctrines govern: charity, comity, compassion, foresight, and '
           '<span class="term">harmony</span> &mdash; and harmony is given teeth: what devotion '
           'made and conquest carried away is returned to the hands that made it.<sup>a</sup> The '
           'old throne is abolished; the last of its holders stepped down by his own act, and the '
           'choir is led now by an elected voice among voices, not a voice above them.<sup>b</sup> '
           'Every Singer sits in three bodies: with her creed, with her region, and with her '
           'calling &mdash; and among the callings stand the watchers against the Union and the '
           'watchers against the Dark Singers.<sup>c</sup> The restitution runs by inquest: '
           'provenance traced, the makers&rsquo; heirs sought, the return performed in ceremony '
           'and entered in the register; where no heir survives, the treasure is held in trust and '
           'the trust is published, that the holding never quietly become a keeping. Every office '
           'of the new order is elective and term-bound, and the watchers&rsquo; assemblies stand '
           'under the same doctrines they enforce &mdash; foresight for those who face the Union, '
           'compassion for those who face the dark &mdash; lest the watch become what it '
           'watches.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence a reformation? '
           '<span class="kw">OUR TEACHERS TOLD:</span> the leader of the choir was granted a '
           'vision, and the face in it was not the face his creed had taught him to expect. He did '
           'not rationalize the vision, and he did not resign from it; he convened the Curia and '
           'swept away centuries of canon, and where the old law had said <span '
           'class="aside">order</span>, the new said <span class="aside">service</span>. The '
           'hardliners issued their declaration and departed &mdash; many to the old knightly '
           'orders that no longer answer to the choir &mdash; and the treasures went home in '
           'ceremony after ceremony, some to peoples who accepted them in silence. Then the leader '
           'laid down the throne itself, the last office of the old music, and the choir elected '
           'its first speaker under the new. The disputants around this text argue whether all '
           'this was repentance or retreat; the Gemara notes only that no one who stayed calls it '
           'small.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Chorus&rsquo;s folio: the recto '
             'keeps the Song, this side keeps the accounting.',
 'folio': '150B',
 'glossL': '<p><span class="mark">a</span> On the Five Doctrines and the duty of return, see the '
           'Lore of the Traditions chapter on the Celestial Chorus; the doctrine of harmony '
           'carries the restitution clause.</p>\n'
           '        <p><span class="mark">b</span> On the last Pontifex Maximus, his vision, and '
           'the Great Return, and on the first Diapason elected after him, see the same '
           'chapter&rsquo;s account of the reformation.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the three committees of every '
           'Singer &mdash; worship, region, vocation &mdash; and the assemblies that watch the '
           'Union and the infernal, see the same chapter&rsquo;s account of the reformed '
           'structure.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Order of Naught and the '
           'Return to Zero, see the same chapter&rsquo;s survey of the choir&rsquo;s margins.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto&rsquo;s empire dispute continues here '
           'with a ledger in hand: the Great Return is the choir&rsquo;s answer to the folio '
           'overleaf, and the Kha&rsquo;vadi of folio 154 are among its auditors.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The hardliners&rsquo; road '
           'leads out of the Council entire: the Templar knights they joined stand among the '
           'unseated of folio 3b, which a reader of this page has already met.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Order of Naught&rsquo;s '
           'doctrine borders the Fallen&rsquo;s, tried at folio 224, wanting; the difference '
           'between union and unmaking is the whole width of this seder.</p>',
 'h1': 'The Reformation',
 'hagahah': 'The choir abolished its own papacy, and the motion carried on a voice vote. '
            'Institutions occasionally astonish. The minutes record one abstention, unexplained, '
            'and the Chorus has been speculating about it ever since with more pleasure than it '
            'took in the vote.',
 'inner': '<p><span class="lemma">And the reform is law.</span> The plain sense first: this is not '
          'a mood but a constitution. The doctrines bind; the committees have budgets; the '
          'restitution clause has case law. A player&rsquo;s Chorister swore to the new order or '
          'joined after it, and either way the old music is her history, not her polity &mdash; a '
          'distinction her elders feel in the knees.</p>\n'
          '        <p><span class="lemma">Harmony is given teeth.</span> The restitution '
          'doctrine&rsquo;s plain sense: return is owed to the makers, not offered to them, and '
          'the doctrine does not lapse when the makers are unfriendly, ungrateful, or gone. Where '
          'the maker&rsquo;s line is extinct the case gets hard, and the choir&rsquo;s courts are '
          'accumulating precedent nobody envies &mdash; who inherits a god&rsquo;s house when the '
          'god&rsquo;s people were made extinct partly by the debtor?</p>\n'
          '        <p><span class="lemma">The old throne is abolished.</span> Note what was not '
          'abolished: hierarchy. The choir still has offices, elections, and chains of duty '
          '&mdash; the reform replaced a crown with a chair, not order with anarchy. The plain '
          'sense for play: authority in the new Chorus is real but always answerable, and a Singer '
          'may appeal anything, which her superiors know, which changes how they command.</p>\n'
          '        <p><span class="lemma">With her creed, with her region, with her '
          'calling.</span> The triple seat is the reform&rsquo;s cleverest clause: no Singer '
          'belongs to only one body, so no schism can take a clean slice. A zealous creed-bloc '
          'finds its members answerable to regions; a rebellious region finds its members sworn to '
          'callings. The structure is a fugue &mdash; voices crossing so that no single line can '
          'carry the piece away &mdash; and it was designed by people who had just watched a '
          'schism, which shows.</p>\n'
          '        <p><span class="lemma">The watchers.</span> Two standing assemblies carry the '
          'choir&rsquo;s wars: one facing the Union &mdash; wary, professional, and lately almost '
          'courteous, for the New World Order and the Chorus are estranged cousins and both know '
          'it &mdash; and one facing the Dark Singers, which is not courteous at all. A Chorister '
          'character with a calling has a commanding officer and a beat; use them.</p>\n'
          '        <p><span class="lemma">The trust is published.</span> The hard case&rsquo;s '
          'plain sense: where conquest&rsquo;s victims left no line to receive the return, the '
          'choir may not simply keep the treasure with a sad face &mdash; the holding is declared, '
          'inventoried, and open to claim, and the register of unclaimed trusts is read into the '
          'record annually. The clause exists because the reformers had watched a century of '
          'Sleeper museums discover that provenance research, unsupervised, reliably concludes the '
          'museum may keep everything; publication is the choir&rsquo;s answer, and its auditors '
          '&mdash; folio 154a names them &mdash; check the arithmetic.</p>\n'
          '        <p><span class="lemma">Elective and term-bound.</span> The plain sense of the '
          'new offices: no Singer holds power she cannot lose by vote, and no term outlives its '
          'mandate. The old order&rsquo;s lesson, learned at cost: thrones accrete theology, and a '
          'chair held for life becomes, in a Tradition of the divine, held by divine right within '
          'two holders. The Diapason serves at the choir&rsquo;s pleasure and says so in the title '
          '&mdash; a diapason is a range of voices, not a voice above them.</p>',
 'inner_head': 'On the New Music<span class="comm-sub">the inner commentary &middot; the plain '
               'sense &middot; the reform, clause by clause</span>',
 'name': 'The Reformation',
 'outer': '<p><span class="lemma">Repentance or retreat.</span> The verso&rsquo;s central dispute. '
          '<span class="voice">Some say</span> repentance, and point to the teeth: institutions '
          'apologize cheaply, but this one returned its treasures, abolished its crown, and bled '
          'membership to do it &mdash; repentance that costs nothing is theater, and this cost '
          'plenty. <span class="voice">Others say</span> retreat wearing vestments: the choir '
          'reformed at the precise historical moment its old power had already failed, and giving '
          'back what empire can no longer hold is not penance but bookkeeping &mdash; the test '
          'will come the day restitution costs the choir something it still wants. An objection to '
          'the cynics: the vision came unbidden and the leader obeyed it against his interest; '
          'read the man, not the moment. <span class="voice">Answer:</span> one man&rsquo;s '
          'sincerity does not launder an institution&rsquo;s timing; both may be true, and the '
          'Kha&rsquo;vadi, who keep their own ledger of the choir&rsquo;s centuries, will rule in '
          'their own court and are entitled to.</p>\n'
          '        <p><span class="lemma">Many to the old knightly orders.</span> The schism '
          'dispute: who left whom? <span class="voice">Some say</span> the hardliners abandoned '
          'the choir &mdash; the Declaration of Imminence reads as an ultimatum, and those who '
          'issue ultimatums to a body they could simply serve have chosen their exit. <span '
          'class="voice">Others say</span> the choir abandoned them first: a Singer sworn to the '
          'old canon watched the canon dissolved over his objection, and calling his departure a '
          'betrayal makes every reform retroactively innocent. The law of the unseated, folio 3b, '
          'hangs oddly over this case &mdash; the Templars the hardliners joined never signed the '
          'Protocols, and men who spent lifetimes enforcing the choir&rsquo;s law now stand '
          'outside all of it, which some call irony and the Masoret calls jurisdiction.</p>\n'
          '        <p><span class="lemma">Union with the One through annihilation.</span> The '
          'Apocalyptic dispute, quietest and worst. <span class="voice">Some say</span> the Order '
          'of Naught are mystics of a legitimate and ancient road: the self&rsquo;s dissolution in '
          'the divine is testified in every tradition&rsquo;s deepest cellar, and a choir of many '
          'harmonies must hold even the diminuendo. <span class="voice">Others say</span> the road '
          'they walk has a cliff at the end wearing a welcome mat: the Dark Singers also preach '
          'return to zero, and a doctrine distinguishable from the enemy&rsquo;s only by its '
          'sincerity is not distinguishable in the dark. The watchers against the infernal keep a '
          'file; the Order knows it and has never once objected, which each side reads as '
          'vindication. <span class="kw">TEYKU</span> &mdash; let the last note fade unresolved, '
          'as last notes do. And the auditors&rsquo; silence, offered by both sides as evidence, '
          'is claimed by neither: some returns were accepted without a word, and the cynics read '
          'contempt where the hopeful read a grief too old for ceremony. The ledger stays open. '
          'That the choir keeps it open &mdash; publicly, annually, against its own comfort '
          '&mdash; is the one fact both readings must accommodate, and neither quite does. The '
          'auditors, for their part, keep auditing, which both sides have agreed to call '
          'progress.</p>',
 'outer_head': 'The Descant<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the reform, the schism, and the edge of the song</span>',
 'rubric': 'the choir&rsquo;s accounting, in living memory',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Chorus&rsquo;s reformation &middot; doctrine, restitution, and the '
             'departed',
 'title': 'Tractate Aliyah · Folio 150b — The Reformation: the choir’s accounting',
 'type': 'daf'}
