# Folio 152a - The Cult of Ecstasy. Avot mold; facts per the wod-llm-wiki
# Cult of Ecstasy page (M20 pp.152-153; Lore of the Traditions ch.3).
FOLIO = {'bottom': '<p><span class="lemma">On playing an Ecstatic.</span> The pitfall is the party as '
           'personality: a character who is a mood, not a person. The books&rsquo; own correction '
           'is on the tin &mdash; these are the scariest mages around when played to spec, seers '
           'who have felt every future of the room and mystics whose instruments would hospitalize '
           'a Sleeper. Build the discipline first and the appetite second: what does this '
           'character practice, daily and hard, that opens the door &mdash; and what has it cost '
           'them? An Ecstatic with a bill is a character; one with only a playlist is '
           'scenery.</p>\n'
           '        <p><span class="lemma">On instruments and the table.</span> The '
           'Tradition&rsquo;s tools &mdash; sex, drugs, pain, fasting, dance &mdash; touch real '
           'limits at real tables. Establish lines and veils in session zero, on paper, before the '
           'first working: what happens on screen, what happens by fade, what does not happen. The '
           'Code&rsquo;s own consent law, overleaf on the recto, is the in-fiction mirror of this '
           'procedure, and a table that runs the Ecstatics without the out-of-fiction half has '
           'misread the whole Tradition.</p>\n'
           '        <p><span class="lemma">On the two camps.</span> The Renewers and the Revelry '
           'are a live wire for troupe play: they disagree about whether the Tradition&rsquo;s '
           'reform was rescue or gentrification, and both camps are charming. Let NPCs of each '
           'court the players&rsquo; cabal &mdash; an invitation to the cleaned-up salon, an '
           'invitation to the party that never reformed &mdash; and the chronicle&rsquo;s stance '
           'on the whole Tradition gets chosen by the players, scene by scene, which is where such '
           'choices belong.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on discipline before appetite, and on '
                'consent at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Cult of Ecstasy hold</span> that reality is widened by '
           'widening the one who perceives it: rearrange perception and you have rearranged the '
           'possible.<sup>a</sup> Their practice is the ecstatic road &mdash; music and dance, the '
           'sacred appetites, the opened body &mdash; and their instruments are whatever breaks '
           'the pattern: the drum, the fast, the vigil, the entheogen taken as sacrament and not '
           'as vice.<sup>b</sup> Their seat among the Nine is <span class="term">Time</span>, for '
           'the widened eye sees the moment&rsquo;s neighbors. Their reformers urge a self-chosen '
           'name, <span class="term">Sahajiya</span>, the Naturals, in place of the one outsiders '
           'coined; the urging has not carried, and is argued below with everything else.</p>\n'
           '        <p>Their internal law is the <span class="term">Code of Ananda</span>, lately '
           'rewritten, and its root is consent: no one&rsquo;s passions are another mage&rsquo;s '
           'playground; the sleeping are left to sleep; enlightenment excuses nothing.<sup>c</sup> '
           'The Code is enforced to expulsion and beyond &mdash; the predators the old laxity '
           'sheltered were named and cast out, and the Tradition hunts its own fallen with a '
           'diligence its critics never expected of it.<sup>d</sup> And the Code binds teacher '
           'before student: the elder&rsquo;s seniority is measured first by what the Code cost '
           'her.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Way of ecstasy was '
           'received in many houses &mdash; the tantrikas of Kamarupa, the wine-rites of the '
           'Greeks &mdash; and a seer gathered them when he foresaw the coming of Reason&rsquo;s '
           'order, and brought them to the Convocation as one people, the Seers of Chronos. Their '
           'duelist stood in the First Cabal, escaped its betrayal, rescued its survivors, and '
           'hauled the betrayer to judgment &mdash; folios 2b and 3a keep that account, and the '
           'seat of Time is held to this day by a mistress who shares her very Avatar with him, '
           'the living and the dead of one soul keeping one chair. <span class="kw">OUR TEACHERS '
           'TOLD:</span> a novice asked why the discipline of joy needs a law code at all. Her '
           'teacher handed her the Code and told her to read only the names signed under the '
           'oldest tenet. She read, and understood: every signature was a survivor&rsquo;s. The '
           'disputants opposite have been arguing the sufficiency of that answer since it was '
           'first given.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; third of the Avot; the seer&rsquo;s burden '
             'waits overleaf.',
 'folio': '152A',
 'glossL': '<p><span class="mark">a</span> On the Cult of Ecstasy entire &mdash; and the proposed '
           'name Sahajiya, the Naturals &mdash; see M20, the Traditions chapter, folio 152, whence '
           'this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On entheogens, sigils, tantra, and the ecstatic '
           'instruments, see the Lore of the Traditions chapter and the Revised Tradition '
           'book.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the rewritten Code of Ananda '
           'and its ten tenets &mdash; the first phrased less politely than any law in this '
           'tractate &mdash; see the Lore of the Traditions chapter on the Ecstatics.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the purged &mdash; the Aghoris, '
           'the Acharne, the Maenads &mdash; see the same chapter; on the fallen generally, folio 224.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 522; the seer&rsquo;s silence before the court &mdash; ruling vii of folio 3a, '
           'argued from Salonikas&rsquo;s case &mdash; is faced on this folio&rsquo;s verso, where '
           'it belongs to his heirs.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The shared Avatar of the '
           'seat&rsquo;s mistress rhymes with the Wheel of folio 148b &mdash; two Traditions, two '
           'doctrines of one soul in many keepings; the Masoret notes the rhyme and declines to '
           'harmonize it.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The First Cabal&rsquo;s '
           'betrayal and trial are folios 2b and 3a; this Tradition supplied the trial its chief '
           'witness, its rescuer, and its longest grief.</p>',
 'h1': 'The Cult of Ecstasy',
 'hagahah': 'The Ecstatics are the only Tradition whose law is mostly about parties, which is jest '
            'until read closely: it is a law of consent, written by survivors, and enforced to '
            'expulsion. Most codes govern how members may harm the enemy. This one governs how '
            'they may not harm each other, which is rarer.',
 'inner': '<p><span class="lemma">Rearrange perception.</span> The paradigm&rsquo;s plain sense at '
          'the table: an Ecstatic&rsquo;s magick begins in a state, not a formula. The working '
          'rides an altered consciousness &mdash; reached by discipline, exhaustion, rapture, or '
          'the sacrament &mdash; and the coincidental reading follows naturally: nothing looks '
          'less like a spell than a dancer, and the bystander of folio 533a has watched ecstatic '
          'crowds do improbable things all his life.</p>\n'
          '        <p><span class="lemma">Taken as sacrament and not as vice.</span> The '
          'instrument law&rsquo;s plain sense, and the Tradition&rsquo;s most misread clause: the '
          'tool is the opened door, not the pleasure as such, and the discipline is real &mdash; '
          'the fast and the vigil sit in the same toolbox as the wine. A character whose '
          'instruments cost her nothing is not practicing the Way; she is decorating it, and her '
          'Arete will say so.</p>\n'
          '        <p><span class="lemma">The moment&rsquo;s neighbors.</span> Why Time is theirs: '
          'the widened perception the practice cultivates does not stop at the present&rsquo;s '
          'edges. The Ecstatic seer feels how the moment leans &mdash; which futures crowd close, '
          'which have gone dry &mdash; and the Tradition&rsquo;s elders are the Council&rsquo;s '
          'weather service for history. What a seer owes the court about what she sees is the '
          'verso&rsquo;s burden, not this page&rsquo;s.</p>\n'
          '        <p><span class="lemma">Its root is consent.</span> The Code&rsquo;s plain '
          'sense: the Way works on the practitioner&rsquo;s own doors. Opening someone '
          'else&rsquo;s &mdash; drugging the unwitting, riding another&rsquo;s rapture, recruiting '
          'by seduction &mdash; is the Tradition&rsquo;s native sin, named as such precisely '
          'because the practice makes it easy. The law is strict where the temptation is strong; '
          'that is what law codes are for.</p>\n'
          '        <p><span class="lemma">Hunts its own fallen.</span> Note the asymmetry with '
          'gentler Traditions: the Ecstatics purge. The predators cast out were not exiled to '
          'comfortable dissent; they were named barabbi, and the Tradition treats their arts as '
          'evidence, not heritage. The plain sense for play: an Ecstatic elder who shrugs at the '
          'Code is not a rake; she is a red flag, and the character sheet should treat her as '
          'one.</p>\n'
          '        <p><span class="lemma">The drum, the fast, the vigil.</span> Practice shapes '
          'coincidence, as folio 533a&rsquo;s bystander requires: the Ecstatic&rsquo;s workings '
          'arrive inside states the world already grants strange powers &mdash; the dancer&rsquo;s '
          'impossible grace, the fasting visionary&rsquo;s sight, the crowd&rsquo;s single mind at '
          'the drop. Her effects ride cultural permissions centuries old, which is why an Ecstatic '
          'working a festival crowd is the most coincidental mage in the setting, and the same '
          'mage working a courtroom is nearly the least; the instrument list is also a map of '
          'where she is safe.</p>\n'
          '        <p><span class="lemma">Teacher before student.</span> The seniority '
          'clause&rsquo;s plain sense, written after the purge and because of it: authority in '
          'this Tradition is custody of thresholds, and the elder is bound exactly where her power '
          'over the young is greatest &mdash; the initiation, the shared working, the sacrament '
          'administered. An elder&rsquo;s violation is tried as the graver case, seniority serving '
          'as aggravation rather than shield, and the Tradition&rsquo;s younger members will tell '
          'you, with datable precision, when that sentence entered the Code and whose students put '
          'it there.</p>',
 'inner_head': 'On the Pulse<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; playing the Way of ecstasy, clause by clause</span>',
 'name': 'The Cult of Ecstasy',
 'outer': '<p><span class="lemma">Lately rewritten.</span> The reform dispute, in the '
          'Tradition&rsquo;s own tempo. <span class="voice">The Renewers say</span> the rewriting '
          'rescued the Way from what it had excused: a liberation practice that shelters predators '
          'is a hunting ground with a philosophy, and the old Code&rsquo;s laxity was not freedom '
          'but negligence with incense. <span class="voice">The Revelry answer</span> that a fence '
          'teaches nothing: the Way is the discipline of thresholds, crossing them is the '
          'curriculum, and a generation raised on the rewritten Code will be safe, considerate, '
          'and unable to open the door the whole practice exists to open &mdash; and a Cult that '
          'rebrands is a Cult embarrassed of itself, which is the one vice the Way never had. An '
          'objection to the Revelry: the purged predators crossed thresholds too, and called it '
          'curriculum. <span class="voice">Answer:</span> they crossed other people&rsquo;s; the '
          'distinction is the whole Code; and if the Revelry cannot keep that distinction while '
          'keeping the party, the Renewers rest their case. An objection to the Renewers: rules '
          'written after a scandal legislate the last war. <span class="voice">Answer:</span> most '
          'law does; ask the Council why parley is absolute. The two camps share every festival '
          'and reconcile at none of them.</p>\n'
          '        <p><span class="lemma">A law code at all.</span> The deeper dispute under the '
          'reform: is codified ecstasy a contradiction? <span class="voice">Some say</span> yes, '
          'and gladly: the Code is a boundary practice, and boundaries are what ecstasy is <span '
          'class="aside">of</span> &mdash; the frame that makes the picture. Law and rapture need '
          'each other as the drum needs its skin stretched tight. <span class="voice">Others '
          'say</span> the argument proves too much: by its logic every fence improves the '
          'wilderness, and the Way&rsquo;s founders codified nothing and reached further than any '
          'of their annotated heirs. The tractate, which is itself a frame around a wilder book, '
          'declines to pretend neutrality here, and the reader may weigh its bias '
          'accordingly.</p>\n'
          '        <p><span class="lemma">One soul keeping one chair.</span> The seat&rsquo;s '
          'strange tenure: the mistress of Time shares her Avatar with the First Cabal&rsquo;s '
          'survivor, and the Tradition treats the arrangement as an honor. <span '
          'class="voice">Some say</span> it is the Way&rsquo;s thesis made flesh &mdash; the self '
          'is a door, and a soul wide enough holds visitors; who better to keep Time&rsquo;s chair '
          'than a soul in two tenses? <span class="voice">Others say</span> quietly that a Council '
          'seat held by a partnership of the living and the dead answers to no living electorate, '
          'and that the Tradition&rsquo;s reverence has excused a constitutional oddity it would '
          'mock in the Hermetics. Both notice that the arrangement has worked for five centuries. '
          'Neither finds that dispositive; five centuries is exactly how long an error can also '
          'last. The Masoret files the arrangement beside folio 148b&rsquo;s Wheel and folio '
          '164b&rsquo;s undying sectors: chapter V keeps finding Traditions that cannot let their '
          'dead be entirely dead, and the Ecstatics&rsquo; version, characteristically, is the '
          'only one anybody envies. The envy is general, unconfessed, and, the Ecstatics would '
          'note, exactly the kind of appetite the Code was written to make people admit.</p>',
 'outer_head': 'The Tempo<span class="comm-sub">the outer commentary &middot; three difficulties: '
               'the reform, the frame, and the shared chair</span>',
 'rubric': 'the Way of ecstasy, and the law it keeps',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Cult of Ecstasy &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 152a — The Cult of Ecstasy: the Way of ecstasy, and the law it '
          'keeps',
 'type': 'daf'}
