# Folio 152b - The Burden. Verso of the Cult of Ecstasy folio: the seer's
# law - what foresight owes the court, the cabal, and the seer. Faces 3a
# ruling vii (Salonikas's silence) from the Tradition's own side.
FOLIO = {'bottom': '<p><span class="lemma">On prophecy at the table.</span> The seer&rsquo;s player and '
           'the Storyteller are co-authors of a hazard: foresight that works is a spoiler machine, '
           'and foresight that never works is a refunded dot. The livable middle is texture over '
           'transcript &mdash; the vision arrives as weather, mood, and one concrete wrong-feeling '
           'detail, never as the scene played in advance. Answer the question the player did not '
           'ask; show the door and not what knocks. A seer who must interpret is a character; one '
           'who downloads is a search result.</p>\n'
           '        <p><span class="lemma">On the burden as drama.</span> The folio&rsquo;s law is '
           'a gift to troupe play: the seer who may not simply blurt is a walking scene. Let the '
           'table feel the weight &mdash; the vision she carries through three sessions deciding '
           'whom it belongs to, the warning she words carefully because the full truth would cause '
           'the harm it names. The rule that the telling changes the told is not a nerf; it is the '
           'job description, and the players who grasp that stop asking the seer for answers and '
           'start asking her what she is willing to carry.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Decide in session zero how this '
           'chronicle&rsquo;s futures behave: fixed, branching, or fogged by observation &mdash; '
           'the folio of Time, when it is written, will hold the mechanics, but the table&rsquo;s '
           'metaphysic should be chosen before the first vision, not discovered in an argument '
           'after one. And grant the seer&rsquo;s player the 3a protection explicitly: what her '
           'character saw and did not say is not table knowledge, not evidence, and not the '
           'Storyteller&rsquo;s to reveal for her. The court declined to compel the seer; so '
           'should the troupe.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on running foresight, and on the '
                'seer&rsquo;s protections</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The seer owes the seen</span> nothing simple. What foresight '
           'yields is not the future but a future&rsquo;s leaning &mdash; the moment&rsquo;s '
           'neighbors, crowding or thinning &mdash; and the law of the widened eye is '
           'threefold.<sup>a</sup> The seer is not the author of what she sees, and bears no guilt '
           'for it; she is the carrier of what she sees, and bears the weight of it; and the '
           'telling is itself an act &mdash; for the told future is no longer the future that was '
           'seen, and the seer answers for the telling as any mage answers for a '
           'working.<sup>b</sup> Therefore no seer is compelled to speak; the court&rsquo;s own '
           'ruling, folio 3a, holds the silence privileged.<sup>c</sup> And a vision is not '
           'counsel: the Tradition sells no futures, and the seer who trades in them is tried '
           'under the Code as any other predator of perception.<sup>d</sup> Nor may a vision be '
           'entered as testimony: what the court cannot compel from the seer it cannot subpoena '
           'secondhand, and the cabal-mate who repeats a warning has repeated hearsay, not '
           'evidence. And the sight itself is disciplined: the seer rests her eye as the '
           'Wheel&rsquo;s people rest their knife-hands, for the eye that never closes begins, in '
           'time, to author what it claims to read.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the privilege? '
           'From the master the Tradition will not stop mourning. He saw the betrayal of the First '
           'Cabal &mdash; the histories of folio 2b allow it &mdash; and said nothing, and the '
           'cabal fell, and he spent the rest of a very long life rescuing what his silence had '
           'cost. Brought before the court&rsquo;s successors in argument ever after: <span '
           'class="aside">why did the seer not speak?</span> And the Tradition&rsquo;s answer, '
           'given once and kept since: because he had seen the tellings too. Every warning he '
           'might have spoken, he had watched fail &mdash; or worse, watched cause the fall it '
           'warned of &mdash; and he chose the one future in which the survivors could be saved, '
           'and saved them. The court of folio 3a heard the case and declined to rule the silence '
           'a crime, and the disputants around this text have never stopped retrying it.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Ecstatics&rsquo; folio: the recto '
             'keeps the Way, this side keeps its weight.',
 'folio': '152B',
 'glossL': '<p><span class="mark">a</span> On Ecstatic foresight &mdash; the widened perception '
           'that reads the moment&rsquo;s neighbors &mdash; see M20&rsquo;s Cult of Ecstasy entry '
           'and the Time Sphere, folio 522, wanting.</p>\n'
           '        <p><span class="mark">b</span> On the told future differing from the seen one, '
           'see the Time discussions of the recensions; the Storyteller&rsquo;s side of the '
           'problem is treated wherever precognition meets plot.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the seer&rsquo;s silence held '
           'privileged, see folio 3a, ruling vii, argued there from this very case.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Salonikas &mdash; the survivor, '
           'the rescuer, the mourned &mdash; see the First Cabal histories cited at folios 2b and '
           '3a and the Tradition&rsquo;s own books.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This verso answers folio 3a from the '
           'defendant&rsquo;s side of the bench: the court&rsquo;s ruling vii is the '
           'Tradition&rsquo;s case law, and the Tradition has opinions about how it was '
           'argued.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The betrayal itself is folio '
           '2b&rsquo;s; this page touches it only where the seer stood. Note the symmetry the '
           'Masoret cannot resist: the betrayer acted and was condemned; the seer refrained and '
           'was acquitted; the tractate keeps both verdicts.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The mechanics of sight '
           '&mdash; what Time&rsquo;s ranks actually yield, and whether a rewind unmakes Paradox '
           '&mdash; are folio 522&rsquo;s, wanting; this folio is the ethics, not the engine.</p>',
 'h1': 'The Burden',
 'hagahah': 'Scholars with foresight argue anyway; the recto&rsquo;s chapter promised as much. The '
            'Burden explains why: the seer who knows how the argument ends still does not know how '
            'it ends if she says so, and arguing is the only way to find out. This is offered as '
            'consolation to everyone who has argued with a seer, which is everyone.',
 'inner': '<p><span class="lemma">Not the future but a future&rsquo;s leaning.</span> The plain '
          'sense first, because every dispute on this page stands on it: Ecstatic sight is '
          'probabilistic, perspectival, and partial. The seer feels which futures crowd close '
          '&mdash; she does not read a script, because there is no script, only pressure. This is '
          'why two honest seers disagree about tomorrow and why neither is lying; they stood at '
          'different windows of the same weather.</p>\n'
          '        <p><span class="lemma">Bears no guilt for it.</span> The first clause&rsquo;s '
          'mercy: seeing a horror is not consenting to it. The young seer who dreams the fire did '
          'not set the fire, and a Tradition of involuntary visionaries would devour itself in a '
          'generation without this clause. Note its limit, though &mdash; the clause covers the '
          'seeing, never the sitting still; what refraining costs is the disputants&rsquo; '
          'business opposite.</p>\n'
          '        <p><span class="lemma">The telling is itself an act.</span> The load-bearing '
          'clause. A future told is a future touched: the warning reshuffles the listeners, the '
          'listeners reshuffle the odds, and the seer who speaks has worked upon the world as '
          'surely as one who cast. Hence the law treats the telling, not the seeing, as the '
          'accountable event &mdash; and hence the privilege, for a compelled telling would be a '
          'compelled working, and no court compels a mage to cast.</p>\n'
          '        <p><span class="lemma">The silence privileged.</span> Plain sense of the 3a '
          'ruling as the Tradition reads it: privileged means unquestioned, not endorsed. The '
          'court did not rule the master&rsquo;s silence right; it ruled the silence <span '
          'class="aside">his</span> &mdash; beyond the bench&rsquo;s reach, like the contents of '
          'any other conscience. The Tradition&rsquo;s elders teach the distinction hard, because '
          'young seers reliably hear acquittal where the court only said jurisdiction.</p>\n'
          '        <p><span class="lemma">A vision is not counsel.</span> The commerce clause: '
          'futures are not for sale, not to Sleepers, not to chantries, not to the highest-bidding '
          'prince of some sibling tractate. The reason is the telling-law again &mdash; a sold '
          'future is a working performed on the buyer&rsquo;s enemies without their consent, and '
          'the Code&rsquo;s root, the recto rules, is consent. The seer who becomes an '
          'oracle-for-hire has made other people&rsquo;s futures her playground, and the Tradition '
          'has a word for that, and a door.</p>\n'
          '        <p><span class="lemma">Cannot subpoena secondhand.</span> The hearsay '
          'clause&rsquo;s plain sense: a vision cannot be cross-examined &mdash; its terms cannot '
          'be audited, its confidence cannot be measured, and its teller cannot be distinguished, '
          'by any bench, from a liar with good instincts. Admitting repeated visions would make '
          'every seer a weapon pointable by her friends; the bar protects the court from the sight '
          'and the sight from the court, and the Tradition drafted it, knowing its own members '
          'best.</p>\n'
          '        <p><span class="lemma">The eye that never closes.</span> The rest '
          'discipline&rsquo;s plain sense: unrested foresight degrades toward wish. The seer who '
          'reads the moment&rsquo;s neighbors without pause begins to lean on them, then to lean '
          'them &mdash; the observer&rsquo;s pressure folio 522 will give mechanics to &mdash; and '
          'the Tradition&rsquo;s elders enforce fallow seasons the way the Chakravanti enforce '
          'their watches: as statute, against the diligent, who need it most.</p>',
 'inner_head': 'On the Weight<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the threefold law, clause by clause</span>',
 'name': 'The Burden',
 'outer': '<p><span class="lemma">Why did the seer not speak?</span> The retrial, perpetual. <span '
          'class="voice">Some say</span> the acquittal was right and the reasoning wrong: the '
          'master&rsquo;s silence should stand not because silence is privileged but because he '
          'was correct &mdash; he had seen the tellings fail, he optimized among futures like a '
          'surgeon among cuts, and the survivors he saved are the proof. On this reading the '
          'privilege is earned case by case, by seers wise enough to hold it. <span '
          'class="voice">Others say</span> the reasoning was right and the comfort false: no seer '
          'sees every telling, and a doctrine that licenses silence whenever the seer despairs of '
          'speech will license despair itself soon enough. The privilege must be absolute '
          'precisely because no court can audit a vision &mdash; but let no Ecstatic pretend the '
          'absolution is moral rather than jurisdictional. An objection to both: the master '
          'himself refused every version of this comfort and spent four centuries in penance no '
          'court imposed. <span class="voice">Answer:</span> yes. That is the datum. The law '
          'acquitted him and he did not acquit himself, and the Tradition keeps both facts, and '
          'the weight of the folio&rsquo;s title is exactly the distance between them.</p>\n'
          '        <p><span class="lemma">The told future is no longer the future.</span> The '
          'metaphysical dispute under the ethical one. <span class="voice">Some say</span> telling '
          'merely perturbs: the future is a river, the warning a thrown stone, and a wise seer can '
          'say much while changing little if she words the telling well &mdash; the craft of the '
          'oblique warning is the Tradition&rsquo;s high art. <span class="voice">Others '
          'say</span> the perturbation is total: the seen future included the seer&rsquo;s '
          'silence, so any telling at all steps into an unseen world, and the careful wording is '
          'superstition &mdash; a ritual of control over the one thing sight proves '
          'uncontrollable. The first school produces the Tradition&rsquo;s diplomats; the second '
          'its hermits; the chronicle may cast either as wise, and the folio of Time will inherit '
          'the mechanics of the fight.</p>\n'
          '        <p><span class="lemma">Tried under the Code as any other predator.</span> A '
          'late difficulty: is the oracle-for-hire truly the seducer&rsquo;s kin, or did the law '
          'reach for the nearest club? <span class="voice">Some say</span> the analogy is exact '
          '&mdash; both work another&rsquo;s inner life without consent, one through the '
          'body&rsquo;s doors and one through tomorrow&rsquo;s. <span class="voice">Others '
          'say</span> the clause criminalizes a courtesy: the friend who warns a friend has sold '
          'nothing, and the line between warning and counsel will be drawn, in practice, by '
          'whoever dislikes the seer. The case law is young; the elders watch it; and the Masoret '
          'observes that every Tradition&rsquo;s law is strictest exactly where its gift is '
          'strongest, which is either wisdom or fear, or the thing those two become when codified. '
          '<span class="kw">TEYKU</span> &mdash; let the warning stand half-spoken. The elders '
          'add, dryly, that the warning half-spoken has this to recommend it: it is the only kind '
          'whose consequences the seer has not already seen, which makes it, for her alone, the '
          'future&rsquo;s last surprise.</p>',
 'outer_head': 'The Retrial<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the silence, the telling, and the sold tomorrow</span>',
 'rubric': 'what the seer owes, and to whom',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the seer&rsquo;s burden &middot; the law of foresight',
 'title': 'Tractate Aliyah · Folio 152b — The Burden: what the seer owes, and to whom',
 'type': 'daf'}
