# Folio 154a - The Dreamspeakers. Avot mold; facts per the wod-llm-wiki
# Dreamspeakers page (M20 pp.154-155; Lore of the Traditions ch.4).
FOLIO = {'bottom': '<p><span class="lemma">On playing the People.</span> The stereotype is named in the '
           'books themselves &mdash; the bongo-beating throwback, the wise elder who exists to '
           'advise someone else&rsquo;s story &mdash; and the correction is the same as the '
           'Brotherhood folio&rsquo;s, doubled: specificity. This character is of a particular '
           'people, keeps particular protocols with particular spirits, and carries a particular '
           'history with the Council &mdash; and none of those particulars is '
           '&ldquo;shaman,&rdquo; a word the books remind us was itself an imposition. A '
           'Storyteller who cannot name the character&rsquo;s nation should not be running the '
           'character&rsquo;s Tradition.</p>\n'
           '        <p><span class="lemma">On the spirits as cast.</span> The Tradition&rsquo;s '
           'table advantage is that its cosmology arrives pre-populated: every river, engine, and '
           'intersection in the chronicle is potentially a character with opinions. Use protocols '
           'as scene structure &mdash; the offering made correctly, the introduction performed, '
           'the obligation incurred &mdash; and spirit-work becomes social play with stakes rather '
           'than a summoning subsystem. The folio of Spirit will carry the dice; this '
           'folio&rsquo;s advice is that the dice are the least of it.</p>\n'
           '        <p><span class="lemma">On the wound in the room.</span> The seat &mdash; one '
           'chair for a hundred nations &mdash; is a live grievance, and a Council scene that '
           'includes a Dreamspeaker includes it. Do not resolve the grievance for the players, and '
           'do not sanitize it into backstory; let Council NPCs be exactly as oblivious as '
           'institutions are, and let the character decide, case by case, whether tonight is a '
           'night for diplomacy, for the long game of reclamation, or for the door. The verso '
           'carries that argument in full.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on specificity, spirit protocol as '
                'scene, and the grievance at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Dreamspeakers hold</span> that the world is alive and '
           'peopled all the way down: every mountain, river, and made thing has its spirit, and '
           'the worker&rsquo;s art is right relation, not command.<sup>a</sup> Their practice is '
           'medicine, in the old full sense &mdash; healing, mediation, and the tending of the '
           'ways between flesh and spirit; their instruments are the drum, the offering, the '
           'vigil, and the <span class="term">protocols</span>: the etiquette each people keeps '
           'with its other-than-human neighbors.<sup>b</sup> Their seat among the Nine is <span '
           'class="term">Spirit</span>. They are not one people and never were: the seat is an '
           'umbrella the Council raised over many nations, and some among them urge a self-chosen '
           'name, <span class="term">Kha&rsquo;vadi</span>, while others keep the old one '
           'precisely to keep the debt it names visible; the argument is the '
           'verso&rsquo;s.<sup>c</sup> Their internal law is custodianship: the ways between the '
           'worlds are held in trust, and initiation passes through a death &mdash; ritual or '
           'otherwise &mdash; that the initiate must survive to stand in both worlds at '
           'once.<sup>d</sup> The trust does not trade: gates are kept, not owned; passage is '
           'granted, not sold; and no protocol is taught for payment.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Tradition was '
           'founded twice over, by a marriage: two visionaries, one of Africa and one of the '
           'Americas, joined their peoples&rsquo; causes at the Convocation and made of many '
           'nations one delegation &mdash; and the histories of folio 2a say the nations <span '
           'class="aside">consented</span>, and this folio lets that word stand exactly as long as '
           'it takes to turn the page. The bride was murdered by a mocker of visions, and the '
           'grief of that murder is the Tradition&rsquo;s founding possession, held in common like '
           'a Node. <span class="kw">OUR TEACHERS TOLD:</span> a young worker asked her elder why '
           'the People stay at a table that named them wrong. The elder said: because the table is '
           'where the naming can be corrected, and the door is where it becomes permanent. Her own '
           'student, years later, asked the same question and received the opposite answer from '
           'the same elder, older. Both answers are kept; the disputants opposite explain why.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; fourth of the Avot; the People themselves are '
             'overleaf.',
 'folio': '154A',
 'glossL': '<p><span class="mark">a</span> On the Dreamspeakers entire &mdash; the '
           'medicine-people, the World Spirit, the endurance &mdash; see M20, the Traditions '
           'chapter, folio 154, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On protocols as the one unifying practice of a '
           'Tradition with deliberately no single paradigm, see the Lore of the Traditions chapter '
           'on the Kha&rsquo;vadi.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the proposed name and the '
           'argument over it, see the same chapter, which presses the question harder than this '
           'folio may.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the founders Naioba and '
           'Star-of-Eagles, their marriage, and her murder, see the Tradition&rsquo;s entries '
           'across the recensions.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 521; the Gauntlet it works across at folio 82; the worlds beyond at '
           'chapter IV entire, folios 89 through 109.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The word '
           '&ldquo;consented&rdquo; in folio 2a&rsquo;s aggada is this folio&rsquo;s inheritance '
           'and the verso&rsquo;s subject; the unseated cousins who never consented at all hold '
           'folio 3b, and the two pages should be read within shouting distance of each other, '
           'because they are.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Brotherhood&rsquo;s '
           'monolith warning, folio 148a, applies here with double force; the Chorus&rsquo;s '
           'restitution ledger, folio 150b, lists this Tradition among its auditors.</p>',
 'h1': 'The Dreamspeakers',
 'hagahah': 'One chair, a hundred nations. Before asking why they share it so uneasily, ask who '
            'built the chair, who chose its shape, and who was told it was an honor. The carpentry '
            'answers most of the questions the Council still thinks are about the sitters.',
 'inner': '<p><span class="lemma">Right relation, not command.</span> The paradigm&rsquo;s plain '
          'sense at the table: a Dreamspeaker&rsquo;s working is a negotiation that succeeded, not '
          'an order that compiled. She asks, offers, obliges, and is obliged; the spirit acts '
          'because relation exists. This is why her magick reads coincidental with such ease '
          '&mdash; the world did it, because the world was asked properly &mdash; and why her '
          'failures look like snubs rather than fizzles. The bystander of 533a sees weather; the '
          'worker sees a neighbor&rsquo;s answer.</p>\n'
          '        <p><span class="lemma">Medicine, in the old full sense.</span> Not the healing '
          'subsystem: the whole office. A medicine person diagnoses relations &mdash; between a '
          'body and its spirit, a family and its dead, a town and its river &mdash; and treats the '
          'relation, whatever organ it presents in. Build the character around the office and the '
          'Sphere list follows; build her around the Sphere list and you get a spirit-themed '
          'utility caster, which the books warn against by name.</p>\n'
          '        <p><span class="lemma">The protocols.</span> The plain sense of the one shared '
          'practice: every people keeps its own etiquette, and the etiquette is law, not flavor. '
          'Greetings, offerings, prohibitions, reciprocities &mdash; these are the '
          'Tradition&rsquo;s casting grammar, and they do not transfer: the protocol that honors a '
          'river of one nation may insult the mountain of another. A traveling Dreamspeaker is '
          'always a guest, and knows it, which is more than most mages know anywhere.</p>\n'
          '        <p><span class="lemma">Held in trust.</span> Custodianship&rsquo;s plain sense: '
          'the ways between the worlds are not the Tradition&rsquo;s property but its charge, held '
          'for the nations and the spirits both. Practically: gates are kept, not owned; passage '
          'is granted, not sold; and the worker who strip-mines the spirit world for Quintessence '
          'and favors answers to her own Tradition first, before any Council bench gets a '
          'word.</p>\n'
          '        <p><span class="lemma">A death the initiate must survive.</span> The initiation '
          'law shared, note well, with the Chakravanti two folios hence: the worker stands in both '
          'worlds because she has been to the other one and returned. The plain sense for play is '
          'that every full Dreamspeaker has a death in her backstory and a standing in the spirit '
          'world that Sleepers and most mages lack &mdash; she is a documented resident of two '
          'jurisdictions, with the obligations of both.</p>\n'
          '        <p><span class="lemma">The drum, the offering, the vigil.</span> The '
          'instruments&rsquo; plain sense: these are gifts and greetings, not switches. An '
          'offering is not fuel for an effect but the opening of an exchange, and the economy it '
          'enters is reciprocal &mdash; the spirit obliged today holds a claim tomorrow, and the '
          'worker&rsquo;s power is exactly her standing in that web of debts. At the table this '
          'means a Dreamspeaker&rsquo;s character sheet undercounts her: her real resources are '
          'relationships, unstatted, accumulated session by session, and a Storyteller who tracks '
          'the favors owed in both directions has the Tradition&rsquo;s whole engine running.</p>',
 'inner_head': 'On the Ways<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; medicine, protocol, and custody</span>',
 'name': 'The Dreamspeakers',
 'outer': '<p><span class="lemma">The nations consented.</span> The word from folio 2a, and the '
          'folio&rsquo;s first difficulty. <span class="voice">Some say</span> the consent was '
          'real as consent goes in a burning world: the founders were not fools, the alternative '
          'was facing Reason&rsquo;s order alone, and the marriage that sealed the delegation was '
          'genuine &mdash; love is not a colonial artifact, whatever the chair turned out to be. '
          '<span class="voice">Others say</span> consent named under siege is triage, not '
          'agreement: the nations consented to survival, and the Council billed it as endorsement '
          'for five centuries, and the difference between those two documents is the whole file. '
          'An objection to the second view: then no compact made in crisis binds, and the Council '
          'itself dissolves, for it was all made in crisis. <span class="voice">Answer:</span> a '
          'compact made in crisis binds exactly as far as it is honored after the crisis &mdash; '
          'which is the People&rsquo;s point, precisely stated.</p>\n'
          '        <p><span class="lemma">One delegation.</span> The umbrella dispute: is the '
          'Tradition a Tradition at all? <span class="voice">Some say</span> yes, and proudly now: '
          'whatever the chair&rsquo;s carpentry, five centuries of shared grief, shared war, and '
          'shared protocols have made a real people of the many peoples &mdash; the '
          'founders&rsquo; marriage worked, and disowning the result insults the ancestors who '
          'built it. <span class="voice">Others say</span> the umbrella is the colonizer&rsquo;s '
          'filing system internalized: the nations were distinct before the Council named them '
          'one, remain distinct under the name, and the &ldquo;Tradition&rdquo; is a convenience '
          'of other people&rsquo;s bookkeeping &mdash; useful, at most, the way any alliance is '
          'useful, and owed exactly an alliance&rsquo;s loyalty and no more. The verso stages this '
          'argument among the People&rsquo;s own societies, where it belongs and where it is '
          'sharper.</p>\n'
          '        <p><span class="lemma">Both answers are kept.</span> The maaseh&rsquo;s '
          'difficulty: the same elder, the same question, opposite rulings a generation apart. '
          '<span class="voice">Some say</span> the elder changed as the table changed &mdash; the '
          'Council of her youth could be corrected from within, and the Council of her age had '
          'proven it would not be, and wisdom updates. <span class="voice">Others say</span> the '
          'two answers were both true on the day each was given, and the lesson is not about the '
          'Council at all: it is that the stay-or-go question has no standing answer, only a '
          'nightly one, renewed or revoked each time the People sit down. The Tradition&rsquo;s '
          'own societies split exactly along this line, and the tractate follows them overleaf. An '
          'objection to the alliance-reading: an alliance would seat its nations severally, one '
          'voice apiece. <span class="voice">Answer:</span> so would an honest Tradition &mdash; '
          'and the nine-seat frame is the Council&rsquo;s furniture, not the People&rsquo;s '
          'choice; folio 2a&rsquo;s own disputants ruled the arithmetic of nine a settlement, and '
          'this folio merely names who paid the rounding error. The umbrella was rented, not '
          'bought; the rent is renegotiated, as the elder said, nightly. And the rounding error, '
          'the People add, had names.</p>',
 'outer_head': 'The Council Fire<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the consent, the umbrella, and the elder&rsquo;s two answers</span>',
 'rubric': 'the People, the protocols, and the chair',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Dreamspeakers &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 154a — The Dreamspeakers: the People, the protocols, and the '
          'chair',
 'type': 'daf'}
