# Folio 154b - The People. Verso of the Dreamspeakers folio: the societies,
# the Storm's losses, and the reclamation-vs-departure dispute, per Lore of
# the Traditions ch.4 via the wod-llm-wiki.
FOLIO = {'bottom': '<p><span class="lemma">On the societies as cast.</span> The People&rsquo;s societies '
           'hand a Storyteller a full political stage without a single invented NPC: the '
           'spirit-led engineers of the Ghost Wheel, the Red Spear&rsquo;s warriors with a target '
           'list, the Keepers tending rites the century keeps interrupting, the Akinkanju guarding '
           'each nation&rsquo;s own ways against the blender, the Baruti shelving what everyone '
           'else is too busy to remember. Any two of them disagree about tonight&rsquo;s problem '
           'in a way that respects both; write the scene where the cabal needs help and two '
           'societies offer it on incompatible terms, and the chronicle has politics that no '
           'Council subplot can supply.</p>\n'
           '        <p><span class="lemma">On playing the losses.</span> The Storm&rsquo;s costs '
           'are heavy furniture; move them carefully. A vanished society, a severed memory-realm, '
           'elders who simply never came home &mdash; these are the Tradition&rsquo;s recent dead, '
           'and an NPC who mentions them casually has told the table more about her grief than a '
           'monologue would. Avoid the temptation to fix them: a chronicle that reopens the lost '
           'realm in three sessions has spent the Tradition&rsquo;s gravest wound as a dungeon '
           'key.</p>\n'
           '        <p><span class="lemma">On procedure.</span> If a player&rsquo;s character '
           'faces the stay-or-go question, let it be plural: staying at the Council table, staying '
           'with the Tradition, and staying with her own society are three different doors, and '
           'the books&rsquo; own factions hold every combination. The question is only flat if the '
           'table flattens it; the People&rsquo;s answer, the recto rules, is nightly, and the '
           'chronicle should bill it that way.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the societies, the losses, and the '
                'nightly question</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The People keep their own houses.</span> The Tradition is a '
           'confederation of societies, each with its charge: the keepers of the old rites; the '
           'warriors against the machine&rsquo;s wars; the smiths and engineers who work spirit '
           'through circuitry; the guardians of each nation&rsquo;s distinct ways; the '
           'memory-keepers, who archive what the others live.<sup>a</sup> No society commands '
           'another, and none speaks for the whole; the whole speaks, when it must, in council, '
           'and grudgingly.<sup>b</sup> And the law counts its dead: a great storm in the ways '
           'between the worlds took from the People more than from any other Tradition &mdash; a '
           'whole society of far-walkers, gone; a realm of common memory, severed; teachers '
           'uncounted, unreturned &mdash; and the losses are carried as obligations, not as '
           'history.<sup>c</sup> Those who walk from community entire walk out of the law&rsquo;s '
           'reach: the solitaries are no society, and the Tradition counts them departed even '
           'where the Council&rsquo;s rolls still count them members. And the storm&rsquo;s '
           'survivors keep two rules the losses taught: no far-walker goes alone, and no realm of '
           'the People&rsquo;s is built again upon one society&rsquo;s memory only.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> After the storm, the '
           'People gathered &mdash; not at the Council&rsquo;s table but at their own fires, at '
           'the protests and the powwows and the block parties, and the gathering was itself the '
           'ruling: community first, the rest negotiable. Some societies read the age as a summons '
           'to the old ways kept stricter; some as a summons to new instruments &mdash; the '
           'spirits, they observe, moved into the wires without asking anyone&rsquo;s permission '
           'either; and some read it as the hour to leave the Council&rsquo;s umbrella altogether, '
           'as cousins among the unseated already have. <span class="kw">IT HAPPENED THAT</span> a '
           'society long accused of sheltering the enemy&rsquo;s defectors weighed departure, '
           'stood at the very door &mdash; and turned back, merging its forges into the spirit-led '
           'engineers instead; and another society weighed the same door and walked through it, '
           'and stands now among the crafts of folio 3b. One threshold, two verdicts, the same '
           'decade. The disputants around this text hold the door open.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Dreamspeakers&rsquo; folio: the '
             'recto keeps the chair, this side keeps the houses.',
 'folio': '154B',
 'glossL': '<p><span class="mark">a</span> On the societies &mdash; Ghost Wheel, Red Spear, the '
           'Keepers of the Sacred Flame, the Akinkanju, the Baruti &mdash; see the Lore of the '
           'Traditions chapter on the Kha&rsquo;vadi.</p>\n'
           '        <p><span class="mark">b</span> On the Four Winds, who ceased to exist in the '
           'Avatar Storm, and the severed memory-realm the Baruti sustained, see the same '
           'chapter.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Spirit Smiths&rsquo; '
           'near-departure and merger, and on the Thunder Society&rsquo;s actual departure to the '
           'Disparate crafts, see the same chapter and the M20 Disparates material.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the gathering-in after Standing '
           'Rock and the community-centered turn, see the same chapter&rsquo;s modern history.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The storm itself belongs to the histories of the '
           'worlds beyond, chapter IV, folios 89 through 109; this folio keeps only what it cost the People. The '
           'far-walkers&rsquo; fate rhymes darkly with folio 148b&rsquo;s Wheel &mdash; some dead '
           'return; some ways of returning died.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The threshold cases &mdash; '
           'the society that turned back, the society that left &mdash; bracket folio 3b&rsquo;s '
           'seat question from the inside: what that folio argues in the abstract, this one has '
           'minutes for.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The technoshamans&rsquo; '
           'wires run toward folio 164&rsquo;s Web, where the spirits in the machine have '
           'other keepers with other protocols.</p>',
 'h1': 'The People',
 'hagahah': 'The memory-keepers&rsquo; realm was severed by the storm, and the Baruti&rsquo;s '
            'answer was to begin again, on paper, in fireproof boxes. Archivists are the only '
            'mystics whose response to apocalypse is acid-free. The tractate, which is also paper, '
            'notes this with professional respect.',
 'inner': '<p><span class="lemma">Each with its charge.</span> The plain sense of the society '
          'structure: these are offices, not denominations. A society holds a duty &mdash; rites, '
          'war, memory, making &mdash; and a worker may hold more than one loyalty or none, '
          'answering directly to her nation. The Tradition&rsquo;s org chart, insofar as it '
          'tolerates one, is a division of labor among equals, and the recto&rsquo;s custodianship '
          'law is the whole of its constitution.</p>\n'
          '        <p><span class="lemma">Spirit through circuitry.</span> The technoshamanic '
          'clause, plain sense: the spirits of the wires are spirits, full stop &mdash; the Ghost '
          'Wheel&rsquo;s insight is that the protocols extend, not that the old ways failed. An '
          'engine has an etiquette; a server farm has a genius loci with strong opinions about '
          'downtime; and the worker who approaches the network as a nation to be in right relation '
          'with does magick the pure coder of folio 164 cannot, and vice versa, and both know '
          'it.</p>\n'
          '        <p><span class="lemma">None speaks for the whole.</span> The anti-umbrella '
          'clause, applied inward: the People refuse to do to themselves what the Council did to '
          'them. Practically, a Council vote by the seat of Spirit binds far less than other '
          'seats&rsquo; votes bind their Traditions, and everyone at the table knows it; the '
          'Dreamspeaker delegate speaks as an ambassador of a confederation, not a governor of '
          'one, and treaties with the People are negotiated society by society or not at all.</p>\n'
          '        <p><span class="lemma">As obligations, not as history.</span> The losses '
          'clause, plain sense: an unreturned teacher is owed searching; a severed realm is owed '
          'rebuilding; a vanished society is owed its work continued. Grief is kept as a task '
          'list. This is the same instinct the Brotherhood files under the Record and the '
          'Chakravanti under the Wheel &mdash; chapter V keeps proposing bookkeepings of the dead '
          '&mdash; but the People&rsquo;s version assigns the debt to the living by name, which is '
          'harder and holds better.</p>\n'
          '        <p><span class="lemma">The solitaries are no society.</span> The departure '
          'clause&rsquo;s plain sense: the Tradition&rsquo;s modern turn made community the '
          'load-bearing wall, and those who reject it entirely &mdash; not this society or that, '
          'but the fire itself &mdash; have left the People in fact whatever the Council&rsquo;s '
          'bookkeeping says. Some drift to orphanhood; a few have crossed to the unseated compact '
          'of folio 3b; and the law&rsquo;s coldness here is deliberate warmth inverted: a '
          'confederation held together by obligation cannot pretend the unobligated are held.</p>\n'
          '        <p><span class="lemma">No far-walker goes alone.</span> The buddy-rule&rsquo;s '
          'plain sense, written in the Four Winds&rsquo; ink: the society that walked deepest '
          'walked in scattered ones and twos, and when the storm came, there was no one to carry '
          'back even the news. The rule is grief made procedure &mdash; chapter V&rsquo;s '
          'recurring craft &mdash; and its second clause is the first&rsquo;s architectural twin: '
          'the severed memory-realm died because one society&rsquo;s keeping was its single point '
          'of failure, and the People do not build that way twice.</p>',
 'inner_head': 'On the Houses<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; societies, wires, and debts</span>',
 'name': 'The People',
 'outer': '<p><span class="lemma">Some as the hour to leave.</span> Reclamation or departure '
          '&mdash; the argument the recto promised. <span class="voice">The reclaimers say:</span> '
          'the chair exists; burn it or leave it, the carpentry stays in the room, and only a '
          'sitter can demand it be rebuilt. Five centuries of the People&rsquo;s blood is sunk '
          'into the Council&rsquo;s wars &mdash; walking out forfeits the claim that blood '
          'established, and hands the whole apparatus to the Traditions least likely to miss us. '
          '<span class="voice">The departers say:</span> the claim was never honored and the '
          'forfeit is imaginary: you cannot lose standing you were never granted, and the crafts '
          'of folio 3b have proven the door survivable &mdash; more than survivable, dignified. An '
          'objection to the departers: the Storm&rsquo;s losses make this the worst hour to stand '
          'alone. <span class="voice">Answer:</span> the Storm&rsquo;s losses were taken while '
          'standing together, under a Council that could not shield the People&rsquo;s realms and '
          'did not try very hard; togetherness has a record, and it is mixed. An objection to the '
          'reclaimers&rsquo; patience: how long? <span class="voice">Answer, from the elder of the '
          'recto&rsquo;s maaseh:</span> nightly. The question is renewed nightly. <span '
          'class="kw">TEYKU</span> &mdash; and this teyku, unlike most, is the Tradition&rsquo;s '
          'own official position.</p>\n'
          '        <p><span class="lemma">The spirits moved into the wires.</span> The instruments '
          'dispute, gentler but real. <span class="voice">Some say</span> the Ghost Wheel&rsquo;s '
          'road is the protocols&rsquo; triumph &mdash; a cosmology confident enough to greet the '
          'server farm as a neighbor has nothing to fear from the century; the Keepers&rsquo; '
          'strictness, on this reading, preserves the letter of the ways by embalming their '
          'spirit. <span class="voice">Others say</span> the wires are not neutral country: the '
          'machine world was built by the enemy, on stolen land, out of extraction &mdash; and a '
          'protocol extended to it too easily launders that history into etiquette. The Keepers do '
          'not oppose new spirits; they oppose forgetting what the new spirits&rsquo; houses are '
          'built on. Both societies tend the same fire and stack the wood differently; the merger '
          'of the Smiths into the Ghost Wheel settled the org chart and not one syllable of the '
          'argument.</p>\n'
          '        <p><span class="lemma">One threshold, two verdicts.</span> The Gemara&rsquo;s '
          'paired cases, pressed. <span class="voice">Some say</span> they prove the system works: '
          'the door is real, the choice is real, and a confederation that can lose a society '
          'without a war and keep a society without a purge is healthier than any Tradition on '
          'this chapter&rsquo;s other folios. <span class="voice">Others say</span> the pairing '
          'flatters: the society that stayed was kept by an accusation disproven, the society that '
          'left was driven by wariness the Council earned, and neither verdict was free &mdash; '
          'the door only looks like a choice from inside the house. The Masoret observes that '
          'folio 3b makes the same point about the Convocation itself, and that the People have '
          'now stood on both sides of it, which is either irony or expertise. The door, both sides '
          'agree, is load-bearing either way: a house is defined as much by its exits as its '
          'hearth.</p>',
 'outer_head': 'At the Door<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the leaving, the wires, and the two verdicts</span>',
 'rubric': 'the societies, the storm, and the door',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the People &middot; societies, losses, and the nightly question',
 'title': 'Tractate Aliyah · Folio 154b — The People: the societies, the storm, and the door',
 'type': 'daf'}
