# Folio 156a - The Chakravanti. Avot mold; facts per the wod-llm-wiki
# Euthanatos page (M20 pp.156-157; Lore of the Traditions ch.5).
FOLIO = {'bottom': '<p><span class="lemma">On playing a death-mage.</span> The books call this the easiest '
           'Tradition to play superficially and the hardest to play sincerely, and they are right '
           'twice. The superficial version arrives pre-ruined: the grim executioner, the edgelord '
           'with a garrote. The sincere version is a hospice nurse with a terrible clearance level '
           '&mdash; a character for whom the knife is the last rung of a long ladder of gentler '
           'answers, and who has climbed the whole ladder every time. Build the ladder into the '
           'character: what does she try first, second, and third, and what has to be true before '
           'the bottom rung? A Chakravanti whose first tool is the blade is not a member; she is a '
           'case the members are discussing.</p>\n'
           '        <p><span class="lemma">On the mandate at the table.</span> The jurisdiction '
           'dispute opposite is not softened for player convenience: nobody appointed them, and '
           'every table with a Chakravanti in the cabal eventually stages its own version of the '
           'argument, usually at a bedside. Let it be staged; do not resolve it in the '
           'character&rsquo;s favor by fiat. The other players&rsquo; horror at the mandate is not '
           'a rules dispute to be settled but the Tradition&rsquo;s actual social position, '
           'rendered in miniature, and the campaign is richer with it unresolved.</p>\n'
           '        <p><span class="lemma">On procedure.</span> The Good Death is a consent '
           'framework, and it deserves an out-of-fiction mirror: establish in session zero how the '
           'table handles mercy-killing scenes, whose consent is gathered, and what stays off '
           'screen. And meter the verso&rsquo;s disease honestly &mdash; a chronicle that tracks '
           'the character&rsquo;s jhor as carefully as her Paradox has the Tradition entire on one '
           'sheet: the work, the ladder, and the bill.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on sincerity, the bedside argument, '
                'and the bill</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Chakravanti hold</span> that the Wheel must turn: all that '
           'lives moves through death to life again, and the art&rsquo;s office is the '
           'cycle&rsquo;s health, not its interruption.<sup>a</sup> Their practice is the tending '
           'of endings &mdash; the mercy at the deathbed, the unmaking of what jams the Wheel, the '
           'fortune-work of fate&rsquo;s currents; their instruments are the tools of last '
           'offices, and their seat among the Nine is <span '
           'class="term">Entropy</span>.<sup>b</sup> Their law is the eightfold Wheel of the Law: '
           'the cycle honored, all things one, mortality accepted, the weak guarded, the self '
           'mastered, compassion kept, temptation shunned, and the member&rsquo;s own death '
           'undergone &mdash; for every Chakravanti has died, in the initiation called the <span '
           'class="term">Diksha</span>, and come back knowing the road.<sup>c</sup> The <span '
           'class="term">Good Death</span> is licensed narrowly: diagnosis before sentence, '
           'gentler remedies exhausted, consent where consent can live &mdash; and the license is '
           'the member&rsquo;s burden, never her right. Teacher and student are bound by '
           'life-oath; the student who breaks it is hunted by the teacher who gave it.<sup>d</sup> '
           'They were called Euthanatos, the good death, by Greeks and strangers; the elder name '
           'Chakravanti, the people of the Wheel, has been set back in its place, and some urge '
           'gentler coinages yet &mdash; the naming is argued opposite. The houses keep their own '
           'liturgies; the Wheel of the Law is what they share, and it is enough.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Many houses of the '
           'dead &mdash; Vedic, Hellenic, Celtic, African &mdash; were gathered at a first '
           'assembly under the Wheel of the Law, a century and a half before the Convocation; they '
           'came to the Council&rsquo;s founding already old. Their delegate to the First Cabal '
           'died under the Order&rsquo;s torture rather than yield the others &mdash; folio 2b '
           'keeps him &mdash; and the Tradition&rsquo;s war with the Brotherhood in the high '
           'passes is kept, with grief on both sides, at folio 148a. And the law&rsquo;s worst '
           'case is its own: a house of the Tradition turned its license to murder for profit, and '
           'prospered for a generation before an outsider exposed it, and the Chakravanti erased '
           'that house root and branch &mdash; and took its surviving student in, and raised her. '
           'The disputants opposite begin there.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; fifth of the Avot; the disease of the work '
             'waits overleaf.',
 'folio': '156A',
 'glossL': '<p><span class="mark">a</span> On the Euthanatos entire &mdash; the Chakravanti, '
           'people of the Wheel &mdash; see M20, the Traditions chapter, folio 156, whence this '
           'page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the eightfold Wheel of the Law and the first '
           'assembly of 1304, see the Lore of the Traditions chapter on the Euthanatos.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Diksha &mdash; the '
           'initiate&rsquo;s death and return &mdash; and the teacher&rsquo;s life-oath, see the '
           'same chapter and the Revised Tradition book.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the fallen house &mdash; its '
           'crimes, its erasure, and the student redeemed &mdash; see the same chapter&rsquo;s '
           'account of the Helekar affair.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 514, '
           'wanting; the botch it tithes at folio 393, likewise. The Wheel&rsquo;s rhyme with '
           'folio 148b is exact and uncomfortable: two Traditions keep death&rsquo;s books, and '
           'their war was, among other things, an audit dispute.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Gilgul, the sentence of '
           'folio 2b, is this Tradition&rsquo;s nightmare written into Council law: the '
           'destruction of a soul is the one killing the people of the Wheel count as murder '
           'absolute, for it kills the returning, not the returned.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The martyr of the First Cabal '
           'is folio 2b&rsquo;s; the war in the passes, folio 148a&rsquo;s; the fallen generally, '
           'folio 224&rsquo;s, wanting.</p>',
 'h1': 'The Chakravanti',
 'hagahah': 'The Chakravanti keep the only law code whose every case is capital. This reads as '
            'gallows humor until one notices its discipline: a code that cannot impose a lesser '
            'sentence must argue every case as if it were the last, which is, of course, the point '
            'of the whole Tradition.',
 'inner': '<p><span class="lemma">The cycle&rsquo;s health, not its interruption.</span> The '
          'paradigm&rsquo;s plain sense, against the caricature: life is the heart of the '
          'doctrine. The Wheel-keeper&rsquo;s enemy is stagnation &mdash; the soul trapped, the '
          'corpse walking, the suffering prolonged past meaning &mdash; and death is her '
          'instrument the way the scalpel is the surgeon&rsquo;s: named in the job title by people '
          'who fear it, not by the practitioner. Play the office as tending, and the grim scenes '
          'acquire the tenderness the books insist on.</p>\n'
          '        <p><span class="lemma">The fortune-work of fate&rsquo;s currents.</span> The '
          'forgotten half of the portfolio: Entropy is chance as well as decay, and the '
          'Tradition&rsquo;s daily work is more often the nudge than the knife &mdash; the lottery '
          'ticket that finds the widow, the brakes that fail a week late. The plain sense for '
          'play: a Chakravanti reads and tilts probability as her siblings read auras, and a '
          'session built on her fate-craft need never mention dying at all.</p>\n'
          '        <p><span class="lemma">Every Chakravanti has died.</span> The Diksha&rsquo;s '
          'plain sense: membership is posthumous. The initiate is killed &mdash; ritually, and the '
          'books do not soften the word &mdash; walks the low road, and returns; what returns is a '
          'colleague. The Tradition&rsquo;s authority at deathbeds rests here: its members are the '
          'only counselors in the room who speak from experience, and the Dreamspeakers, who share '
          'the door if not the doctrine, nod across the chapter.</p>\n'
          '        <p><span class="lemma">Diagnosis before sentence.</span> The license&rsquo;s '
          'plain sense, rung by rung: the Good Death is a medical procedure wearing a juridical '
          'robe. Diagnosis &mdash; is the Wheel truly jammed here, or merely slow? Remedies '
          '&mdash; healing, mediation, time, the gentler Spheres, exhausted in order. Consent '
          '&mdash; of the dying where the dying can speak, and the law&rsquo;s hardest pages are '
          'about where it cannot. Only then the bottom rung, and the member climbs down carrying '
          'the whole ladder&rsquo;s weight. Note the grammar: burden, never right &mdash; the '
          'license protects the patient from the mage, not the mage from the argument.</p>\n'
          '        <p><span class="lemma">Hunted by the teacher who gave it.</span> The '
          'life-oath&rsquo;s plain sense, and its severity is the system&rsquo;s honesty: a '
          'Tradition that licenses killing cannot outsource its discipline. The teacher answers '
          'for the student &mdash; literally, lethally &mdash; and so teaches as if her own soul '
          'were the tuition, which it is. Recruitment is correspondingly slow, examined, and '
          'reluctant, and the Tradition stays small on purpose.</p>\n'
          '        <p><span class="lemma">Many houses of the dead.</span> The '
          'confederation&rsquo;s plain sense: the Tradition is plural to its bones &mdash; Celtic '
          'keepers of the dark year, Hellenic tenders of the chthonic rites, African houses of the '
          'ancestors, and the Indian lineages that named the Wheel &mdash; each with its own '
          'liturgy of endings, none ranked above another. The eightfold law binds conduct, not '
          'cosmology; a member owes the Wheel her discipline and her own house her prayers, and '
          'the Tradition&rsquo;s diplomats spend careers translating between funerals. The '
          'umbrella problem of folio 154a knocks here too, and is answered differently: this '
          'confederation named itself, before the Council existed to name it.</p>',
 'inner_head': 'On the Wheel<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the office, the license, and the oath</span>',
 'name': 'The Chakravanti',
 'outer': '<p><span class="lemma">Licensed narrowly.</span> By whom? The jurisdiction dispute, the '
          'Tradition&rsquo;s permanent guest. <span class="voice">Some say</span> the license is '
          'self-issued and therefore void: no bench, no electorate, no heaven anyone can produce '
          'has deputized these mages to end anyone, and a burden assumed voluntarily is '
          'indistinguishable, from the outside, from a appetite dressed in duty. The Council '
          'tolerates them as one tolerates a neighbor&rsquo;s guard dog &mdash; useful, watched. '
          '<span class="voice">Others say</span> the license is issued by the work itself: someone '
          'tends the deathbeds no healer can win, unmakes the things folio 224 will catalogue, and '
          'carries what that carrying costs &mdash; and the objectors have had five centuries to '
          'volunteer and have sent, instead, opinions. An objection to the defenders: the fallen '
          'house prospered for a generation inside this very framework; the license did not fail '
          '&mdash; it was the camouflage. <span class="voice">Answer:</span> and the Tradition '
          'erased that house at its own hand and audits itself harder since; show another court '
          'that sentences its own bench. <span class="voice">Rejoinder:</span> the exposure came '
          'from a Hermetic outsider, not the audit. The defenders concede the rejoinder and keep '
          'the practice; the critics concede the practice and keep the rejoinder; the bedside '
          'argument continues nightly, as the Later Authorities attest.</p>\n'
          '        <p><span class="lemma">Took its surviving student in.</span> The redemption '
          'case, pressed. <span class="voice">Some say</span> raising the fallen house&rsquo;s '
          'student was the Tradition&rsquo;s finest ruling: the Wheel&rsquo;s whole doctrine is '
          'that nothing is only its worst turn, and a law of endings that could not imagine '
          'beginnings would be half a faith. <span class="voice">Others say</span> the mercy was '
          'also an argument of convenience &mdash; the redeemed student is walking evidence that '
          'the system corrects, displayed accordingly; ask whether an unremarkable student would '
          'have been gathered so warmly. The tractate notes the pattern for the chapter: every '
          'Tradition&rsquo;s proudest mercy doubles as its best exhibit, and the Wheel turns that '
          'observation without apparent embarrassment.</p>\n'
          '        <p><span class="lemma">Gentler coinages yet.</span> The naming dispute, this '
          'Tradition&rsquo;s edition. The Greek name stuck for centuries because outsiders found '
          'the fear useful to say; the Wheel-name is restored; and reformers within urge a further '
          'step &mdash; a name meaning agents of fate, executioners of nobody. <span '
          'class="voice">Some say</span> take it: names teach, and a Tradition tired of being '
          'feared should stop answering to fear. <span class="voice">Others say</span> the fear is '
          'load-bearing: the license survives scrutiny partly because nobody envies it, and a '
          'comfortable name invites comfortable members, which the oath exists to prevent. Between '
          'the name that frightens and the name that flatters, the Tradition has, '
          'characteristically, chosen the one that merely tells the truth &mdash; the Wheel '
          '&mdash; and the argument over the third name is adjourned, not ended. The third name '
          'waits, as third names do, for the generation that will need it; the Wheel, which '
          'measures such things, reports no hurry. In the meantime the license is exercised, the '
          'ladder is climbed, and the bedside keeps its argument &mdash; which is, the Tradition '
          'holds, precisely the arrangement a healthy fear of one&rsquo;s own mandate would '
          'design.</p>',
 'outer_head': 'The Spokes<span class="comm-sub">the outer commentary &middot; three difficulties: '
               'the mandate, the mercy, and the name</span>',
 'rubric': 'the Wheel, its keepers, and their license',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Chakravanti &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 156a — The Chakravanti: the Wheel, its keepers, and their '
          'license',
 'type': 'daf'}
