# Folio 156b - Jhor. Verso of the Chakravanti folio: the occupational
# disease of death-work, per the Euthanatos materials via the wod-llm-wiki.
FOLIO = {'bottom': '<p><span class="lemma">On tracking the disease.</span> Jhor is the rare corruption '
           'mechanic that improves a chronicle by being bookkept: log the character&rsquo;s '
           'death-work as faithfully as her Paradox, and let the symptoms arrive on schedule '
           '&mdash; the flattened affect first, the aesthetic drift, the bedside manner turning '
           'clinical, the jokes stopping. The player should see the ledger; the character should '
           'not. The horror of the disease is that it presents, from inside, as '
           'professionalism.</p>\n'
           '        <p><span class="lemma">On the watch as troupe play.</span> The partner-watch '
           'is a standing invitation to bind two player characters: give the Chakravanti&rsquo;s '
           'watch to another player, on paper, with the duty spelled out &mdash; observe, name, '
           'and if it comes to it, report. The scene where the watcher must decide whether the '
           'deadened thing she saw was fatigue or symptom is the Tradition&rsquo;s whole tragedy '
           'in one exchange, and no Storyteller-run NPC can carry it as well as a friend across '
           'the table.</p>\n'
           '        <p><span class="lemma">On the far end.</span> A character lost to jhor is not '
           'a combat encounter; she is a funeral the survivors must conduct for someone still '
           'walking. If the chronicle goes there, go slowly, let the intervention be tried and '
           'argued, and let the Good Death&rsquo;s own ladder govern the ending &mdash; diagnosis, '
           'remedies, consent if consent can live. The Tradition applying its license to its own '
           'is the hardest page in its book, and a table that reaches it has earned the right to '
           'play it in full.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on ledgers, watchers, and the hardest '
                'page</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The work sickens the worker.</span> Death handled daily leaves a '
           'residue, and the law names it <span class="term">jhor</span>: the death-taint, a '
           'morbidity of the soul that gathers where endings are tended.<sup>a</sup> Its course is '
           'cold: not madness but flattening &mdash; empathy thins, the dark grows comfortable, '
           'the exception becomes the habit, and the mage who began by grieving each sentence ends '
           'by drafting them at breakfast.<sup>b</sup> Therefore the law of the Wheel sets '
           'watches: no member works endings alone for long; each is observed by teacher, partner, '
           'or circle, and the watcher&rsquo;s duty is to name the symptoms aloud, early, and to '
           'the face.<sup>c</sup> Rest is prescribed as duty, not leave; the tainted are drawn '
           'back from the work, cleansed where cleansing avails; and the member far gone &mdash; '
           'who has become what the license exists against &mdash; is owed the Tradition&rsquo;s '
           'whole ladder, climbed for her as she once climbed it for others.<sup>d</sup> Cleansing '
           'is prescribed by stage: retreat and the living&rsquo;s service early; the gentler '
           'Spheres worked for a season, midwifery set against the knife&rsquo;s memory; past the '
           'third stage the law stops prescribing and begins convening. And no member diagnoses '
           'herself: the taint&rsquo;s first symptom is the certainty of immunity, and the law is '
           'written for people who have read it.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the watches? '
           'From the worst case, as ever. The fallen house of the recto did not begin murderous; '
           'it began diligent. Its founder worked the hardest endings of a hard century, refused '
           'the rests, called the watchers&rsquo; concern sentimentality &mdash; and the taint '
           'accrued so slowly that each day&rsquo;s member was almost yesterday&rsquo;s, until the '
           'house that tended deathbeds was selling them, and believed itself, by then, efficient. '
           'When the accounting came, the Tradition read the ledgers backward looking for the day '
           'the crime began, and could not find it: there was no day. That is jhor, said the '
           'elders, and wrote the watches into law, and the disputants around this text have been '
           'asking ever since whether a disease with no first day can support a doctrine of guilt '
           'at all.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Chakravanti&rsquo;s folio: the '
             'recto keeps the license, this side keeps the bill.',
 'folio': '156B',
 'glossL': '<p><span class="mark">a</span> On jhor &mdash; the death-taint, Morbidity &mdash; see '
           'the Euthanatos entries of M20 and the Lore of the Traditions, and the Revised '
           'Tradition book&rsquo;s treatment of its mood.</p>\n'
           '        <p><span class="mark">b</span> On the taint&rsquo;s course as loss of empathy '
           'rather than frenzy, see the same sources; the recensions agree on the coldness.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the fallen house as the '
           'doctrine&rsquo;s proof case, see the Helekar material cited on the recto.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On resonance and the marks the '
           'Arts leave on their workers generally, see the focus and resonance discussions of M20; '
           'jhor is the severest of a family.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto&rsquo;s license and this verso&rsquo;s '
           'disease are one law read twice: the burden that justifies the mandate is this bill, '
           'itemized. Read them in either order but read both.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The taint rhymes with the '
           'Quiet of folio 554, wanting, and the Masoret marks the difference now against future '
           'confusion: Quiet breaks the world&rsquo;s shape in the mage; jhor keeps the shape and '
           'drains the warmth. The mad mage believes too much; the tainted one, at the end, '
           'believes nothing.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The watcher&rsquo;s office '
           'rhymes with folio 533b&rsquo;s census &mdash; this chapter&rsquo;s law, too, is the '
           'law of who is watching, and the Chakravanti answered it by statute: someone, always, '
           'by name.</p>',
 'h1': 'Jhor',
 'hagahah': 'The taint&rsquo;s first symptom is the conviction that one is immune to it, and its '
            'second is the impatience of this folio&rsquo;s cautions. Several readers have just '
            'now felt that impatience. The Tradition asks them, gently, to note the date.',
 'inner': '<p><span class="lemma">A morbidity of the soul.</span> The plain sense: jhor is '
          'resonance turned occupational disease. Every mage&rsquo;s work stains her &mdash; the '
          'fire-thrower smells faintly of ozone, the dream-walker&rsquo;s coffee goes cold '
          'strangely &mdash; but death&rsquo;s resonance is heavier than the others, and its stain '
          'reaches past the aura into the appetites. It is not a punishment and carries no '
          'verdict; it is what handling the Wheel&rsquo;s heaviest spoke does to hands, however '
          'clean.</p>\n'
          '        <p><span class="lemma">Not madness but flattening.</span> The course, plainly, '
          'so the table can play it: stage one is style &mdash; the wardrobe darkens, the humor '
          'dries, colleagues call it a phase. Stage two is procedure &mdash; the ladder&rsquo;s '
          'upper rungs get climbed faster, the diagnosis arrives before the patient finishes '
          'speaking. Stage three is doctrine &mdash; the exception is now the rule, and the mage '
          'can defend each step in perfect logic, which is the tell: the arguments stay sound and '
          'the arguer stops being anywhere inside them.</p>\n'
          '        <p><span class="lemma">The watcher&rsquo;s duty.</span> Plain sense of the '
          'statute: naming, early, to the face &mdash; not reporting upward, not managing around. '
          'The design is deliberate: jhor cannot be audited from records, because the records stay '
          'impeccable; it can only be seen by someone close enough to notice the warmth leaving. '
          'Hence the law binds partners, not benches, and hence the Tradition&rsquo;s teaching '
          'pairs outlive training by design &mdash; the Acarya watches the Chatra&rsquo;s whole '
          'career, and is watched back.</p>\n'
          '        <p><span class="lemma">Rest is prescribed as duty.</span> The clause the '
          'diligent hate, on purpose: the member who refuses rest is not admirable, she is '
          'symptomatic &mdash; the founder of the fallen house refused rests, and the Gemara means '
          'the echo to be heard. Cleansing &mdash; retreat, service among the living, the gentler '
          'Spheres worked for a season &mdash; avails early and less late, which is why the '
          'watches are set early, which is why the naming must be to the face, which is why the '
          'whole statute reads like impertinence codified. It is. Politeness was tried; see the '
          'recto&rsquo;s worst case.</p>\n'
          '        <p><span class="lemma">No member diagnoses herself.</span> The clause&rsquo;s '
          'plain sense, and its cold logic: jhor corrupts precisely the faculties that would '
          'detect it &mdash; empathy, doubt, the sense of drift &mdash; so self-audit returns '
          'clean exactly when it matters. Hence the watches are external by statute, and hence the '
          'strange etiquette of the Tradition&rsquo;s elders, who accept a colleague&rsquo;s '
          'naming of their symptoms with a formal thanks that younger members mistake for '
          'coldness: it is drill. One thanks the watcher because the day one stops wanting to is '
          'the day the watch was for.</p>\n'
          '        <p><span class="lemma">Midwifery set against the knife&rsquo;s memory.</span> '
          'The cleansing&rsquo;s plain sense: the cure is opposite work &mdash; the death-mage '
          'seconded to birthing rooms, disaster relief, the patient tending of things that grow. '
          'The Verbena elder of folio 162a set her seeker a season of each; the Chakravanti '
          'prescribe the same pairing in the other order, and for medicine rather than pedagogy. '
          'Whether opposite work heals the taint or merely masks its readings, the elders dispute '
          'in private; that it postpones the third stage, the registers show; and the Tradition '
          'takes postponement, being professionally unsentimental about cures.</p>',
 'inner_head': 'On the Bill<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the disease, its course, and its watch</span>',
 'name': 'Jhor',
 'outer': '<p><span class="lemma">No first day.</span> The guilt dispute the Gemara promised. '
          '<span class="voice">Some say</span> a crime with no first day is still a crime with a '
          'last one: wherever the descent began, the fallen house&rsquo;s members each woke on '
          'their final morning, read their own ledgers, and chose not to see &mdash; the disease '
          'explains the road and excuses no step on it, or else the license itself is void, for '
          'who may wield death whose culpability dissolves in diagnosis? <span '
          'class="voice">Others say</span> the hard line is the healthy speaking: jhor&rsquo;s '
          'whole horror is that the chooser is consumed along with the choice, and a doctrine of '
          'guilt that requires an intact self to bear it will find, at stage three, no one home to '
          'convict. The law&rsquo;s answer &mdash; watches, rest, intervention &mdash; '
          'deliberately sidesteps the question: it treats the disease without ruling on the sin, '
          'medicine where philosophy would stall. Both schools accept the statute; they disagree '
          'about what it is for; and the Tradition, asked to settle it, points at the watches and '
          'changes the subject, which the tractate records as an answer.</p>\n'
          '        <p><span class="lemma">Owed the Tradition&rsquo;s whole ladder.</span> The '
          'intervention dispute. <span class="voice">Some say</span> the far-gone member is owed '
          'the Good Death itself if it comes to that &mdash; the license&rsquo;s final integrity '
          'is that it applies inward, and a Tradition that unmakes jammed things cannot exempt its '
          'own jammed workers without becoming the fallen house at scale. <span '
          'class="voice">Others say</span> the inward application is exactly where the license '
          'must stop: a body that may kill its sickened members has built the perfect oubliette '
          'for its critics, and every symptom on the verso&rsquo;s list &mdash; coldness, '
          'certainty, procedural speed &mdash; describes an inconvenient elder as well as a '
          'tainted one. The safeguards answer some of this &mdash; diagnosis, the full ladder, '
          'consent where consent can live &mdash; and the objection survives the safeguards, as '
          'good objections do. <span class="kw">TEYKU</span> &mdash; let the hardest page stay '
          'hard.</p>\n'
          '        <p><span class="lemma">However clean the hands.</span> A quieter difficulty: is '
          'jhor evidence against the whole mandate? <span class="voice">Some say</span> yes, read '
          'plainly &mdash; a work that reliably corrodes its workers is a work the world is '
          'telling you to put down; no other Tradition&rsquo;s daily practice carries a named '
          'disease. <span class="voice">Others say</span> the argument proves surgery wicked and '
          'mining foolish: the measure of a burden is not whether it costs but whether the cost is '
          'watched, shared, and paid by volunteers &mdash; and by that measure the Wheel&rsquo;s '
          'people, with their statutes and their watchers and their prescribed rests, are the '
          'best-audited danger in the tractate. The first reading would retire the license; the '
          'second funds its oversight; the bedside argument of the recto continues here at one '
          'remove, as it continues everywhere the Tradition goes. The registers, consulted, '
          'decline to settle even this: they show the watched lasting longer than the unwatched, '
          'and cannot show what either would have chosen.</p>',
 'outer_head': 'The Audit<span class="comm-sub">the outer commentary &middot; three difficulties: '
               'the guilt, the intervention, and the mandate&rsquo;s price</span>',
 'rubric': 'the disease of the work, and its watches',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of jhor &middot; the death-taint as law',
 'title': 'Tractate Aliyah · Folio 156b — Jhor: the disease of the work, and its watches',
 'type': 'daf'}
