# Folio 158b - The Houses. Verso of the Order of Hermes folio: the House
# roll, the Degrees, and the defection, per the wod-llm-wiki Order page.
FOLIO = {'bottom': '<p><span class="lemma">On choosing a House.</span> For a player, the House is the '
           'character sheet before the character sheet: pick it the way one picks a college and a '
           'surname at once. The war-House suits the player who wants righteous fire and its '
           'bills; the judges&rsquo; House, intrigue with subpoena power; the founders&rsquo; '
           'House, research and the burden of being everyone&rsquo;s library; the catch-all House, '
           'the joy of being underestimated by people with better bloodlines. Ask what the House '
           'expects of the character this season, and the Storyteller has a patron, a rival, and a '
           'to-do list before the chronicle starts.</p>\n'
           '        <p><span class="lemma">On the warlocks as antagonists.</span> The defected '
           'House&rsquo;s heirs are the rare enemy that makes a Hermetic chronicle personal: they '
           'know the Order&rsquo;s forms, predate its oaths, and wear a theft the Order still '
           'itemizes. Crossover scenes with the leeches&rsquo; tractate should feel like probate '
           'gone feral &mdash; two heirs to one estate, each holding documents. Use sparingly; the '
           'grudge is best as gravity, not as weekly content.</p>\n'
           '        <p><span class="lemma">On the ninth Degree.</span> Do not show the top of the '
           'pyramid casually. Masters of the World are the Order&rsquo;s load-bearing myths, and '
           'the chronicle spends them like Nodes: a summons from the ninth Degree should '
           'reorganize a season, and an actual appearance should reorganize the campaign. The '
           'pyramid&rsquo;s power over play is proportional to how rarely its apex is '
           'photographed.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on Houses as patrons, warlocks as '
                'gravity, and the unseen apex</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Houses are the Order&rsquo;s bones.</span> Thirteen persist, '
           'and the law knows two kinds: the ancient charters &mdash; the founders&rsquo; House of '
           'research, the war-House of righteous flame, the judges&rsquo; House that keeps the '
           'Code, the contrarians&rsquo; House that tests all things by opposition, the '
           'makers&rsquo; House of enchanted works, and the catch-all House that shelters every '
           'lineage too small to charter &mdash; and the newer seats, raised or adopted in reform: '
           'houses of fortune, of the dragon&rsquo;s blood, of the drum, of the scribe, of the '
           'eye, of the alchemists returned, and of chaos harnessed.<sup>a</sup> A magus advances '
           'by <span class="term">Degree</span>, nine in all, neophyte to Master of the World, '
           'each earned by examination and oath.<sup>b</sup> A House may be censured, suspended, '
           'or dissolved; the Order has done all three, and its law provides the '
           'forms.<sup>c</sup> Between Degrees stand the examinations called ordeals; between '
           'Houses, the transfers called, delicately, adoptions &mdash; and both have forms, the '
           'ordeal&rsquo;s sealed and the adoption&rsquo;s witnessed.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear what the '
           'forms have processed. A House of blood-scholars, hungry past its charter, worked a '
           'great working against death and became the deathless thing it studied; the Order woke '
           'to find a House of warlocks where a House of colleagues had been, and the theft '
           'included the library. That case is tried nightly in a sibling tractate, and the '
           'Order&rsquo;s copy of the file has never closed.<sup>d</sup> A House of janissaries, '
           'corrupted in living memory, was purged root and branch by the forms working as '
           'written. And a House of alchemists, fallen at the Council&rsquo;s very founding '
           '&mdash; folio 2b keeps the trial &mdash; was received back centuries later as heirs '
           'under a new name, their disgrace lapsed but not expunged; the ruling of folio 3a '
           'stands: the shame stayed with the guild, not the seat. <span class="kw">IT HAPPENED '
           'THAT</span> the catch-all House, asked why it tolerates lineages the great charters '
           'refuse, answered: because the Order&rsquo;s next centuries keep arriving through our '
           'door. The great charters have not stopped quoting the answer, mostly in irritation, '
           'which is how the Order preserves its best sayings.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Order&rsquo;s folio: the recto '
             'keeps the law, this side keeps the roll.',
 'folio': '158B',
 'glossL': '<p><span class="mark">a</span> On the thirteen persisting Houses and their charters, '
           'see the Lore of the Traditions chapter on the Order of Hermes; the roll here is '
           'restated, not reproduced, and the curious should read the originals.</p>\n'
           '        <p><span class="mark">b</span> On the nine Degrees, neophyte to Magister '
           'Mundi, see the same chapter; Awakening itself is induced by the third, which no other '
           'Tradition attempts on a syllabus.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the purge of House Janissary, '
           'see the same chapter&rsquo;s modern history.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Tremere defection and the '
           'clan it founded, see the sibling tractate&rsquo;s own books; on the Solificati&rsquo;s '
           'fall and return, folios 2b and 3a of this one.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The warlocks&rsquo; case is Tractate '
           'Masekha&rsquo;s to try; this folio keeps only the Order&rsquo;s standing in it. One '
           'lineage, two tractates &mdash; the Masoret said it on the recto and repeats it here, '
           'because the point improves with repetition and the Order would agree.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The alchemists&rsquo; return '
           'closes a loop this tractate opened at folio 2b: betrayal, exile, and readmission as '
           'heirs &mdash; the Wheel of folio 156a, worked in institutional time.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Awakening induced by syllabus '
           'touches the dispute of folio 38: whether the rousing can be scheduled at all. '
           'The Order&rsquo;s third Degree is that folio&rsquo;s standing exhibit.</p>',
 'h1': 'The Houses',
 'hagahah': 'Every House&rsquo;s charter describes the Order as it would be if the other twelve '
            'calmed down. Bind the thirteen charters together and one obtains either a '
            'contradiction or the Order itself; the Quaesitors have ruled, wearily, that these are '
            'the same document.',
 'inner': '<p><span class="lemma">The Order&rsquo;s bones.</span> Plain sense of the metaphor: the '
          'Houses bear load and set shape, and nothing else in the Order moves without them. '
          'Chantry seats, tribunal votes, teaching rights, even feud etiquette route through House '
          'standing; the unaffiliated Hermetic exists in law the way a stateless person does '
          '&mdash; possible, pitied, and paperwork-intensive.</p>\n'
          '        <p><span class="lemma">Two kinds.</span> The old-and-new distinction&rsquo;s '
          'plain sense: the ancient charters carry prestige and precedent; the newer seats carry '
          'the Order&rsquo;s apologies made structural &mdash; lineages once refused, absorbed, or '
          'wronged, chartered now as equals. The drum-House and the dragon-House did not petition '
          'into a European order so much as the Order conceded, late, that the High Art had never '
          'been only Europe&rsquo;s. The pyramid&rsquo;s newer stones sit lower than they should; '
          'the masons know; the subject is raised at tribunals by exactly the Houses one would '
          'predict.</p>\n'
          '        <p><span class="lemma">Earned by examination and oath.</span> The '
          'Degrees&rsquo; plain sense: rank in the Order is certified competence, not tenure '
          '&mdash; the examinations are real, failable, and occasionally lethal, and the oath at '
          'each Degree binds as the recto&rsquo;s law provides. The third Degree&rsquo;s induced '
          'Awakening is the syllabus&rsquo;s famous scandal: the Order alone claims to schedule '
          'the soul&rsquo;s rousing, and its success rate is the quietest number in its '
          'records.</p>\n'
          '        <p><span class="lemma">The forms working as written.</span> The purge&rsquo;s '
          'plain sense, for the recto&rsquo;s dispute: when the janissary House rotted, no hero '
          'saved the Order &mdash; a process did. Investigation, indictment, tribunal, sentence, '
          'all per the Code, all minuted. The defenders of the pyramid rest their whole case on '
          'this file; its latency &mdash; a generation of rot before the forms engaged &mdash; is '
          'the critics&rsquo; bookmark in the same file. Both read it correctly.</p>\n'
          '        <p><span class="lemma">Called, delicately, adoptions.</span> The transfer '
          'law&rsquo;s plain sense: a magus may change Houses, and the word chosen tells the '
          'politics &mdash; she is not hired but adopted, taking a new lineage with new oaths, and '
          'her old House&rsquo;s consent is required, negotiated, and priced. Adoptions ripple: '
          'the departing magus&rsquo;s students, debts, and name-deposit move with her by '
          'schedules the Code devotes a chapter to, and a contested adoption is the classic '
          'opening move of a feud, cheaper than cert&aacute;men and deniable, which is why the '
          'Quaesitors watch adoptions the way customs officers watch diplomatic luggage.</p>\n'
          '        <p><span class="lemma">The charter of no charter.</span> The catch-all&rsquo;s '
          'plain sense: the omnibus House exists so that the Order&rsquo;s claim to be <span '
          'class="aside">the</span> Order of the West&rsquo;s High Art can survive contact with '
          'the West&rsquo;s actual variety. Every lineage too small, too new, or too strange for a '
          'charter shelters there with full standing and second-class prestige, and the '
          'House&rsquo;s roll is the Order&rsquo;s census of its own future &mdash; read annually '
          'by the great charters&rsquo; recruiters, who arrive with adoption papers and leave, '
          'reliably, with fewer than they wanted.</p>',
 'inner_head': 'On the Roll<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; charters, Degrees, and forms</span>',
 'name': 'The Houses',
 'outer': '<p><span class="lemma">Became the deathless thing it studied.</span> What does the '
          'defection prove? <span class="voice">Some say</span> the pyramid&rsquo;s case: the '
          'warlock House fell <span class="aside">outside</span> the forms &mdash; secret '
          'workings, unsanctioned appetites, oaths evaded &mdash; and the lesson is that the Code '
          'is the wall between the Art and the abyss; climb over it and become a cautionary '
          'tractate. <span class="voice">Others say</span> the House fell through the forms&rsquo; '
          'own front door: it was ambitious, credentialed, and in excellent standing to the hour '
          'of its damnation, and the Order&rsquo;s machinery registered nothing until the library '
          'was gone. The wall, on this reading, keeps out only those poor at paperwork &mdash; '
          'which the genuinely dangerous never are. The two readings assign the Order opposite '
          'homework: thicker walls, or better windows.</p>\n'
          '        <p><span class="lemma">Received back as heirs.</span> The readmission dispute. '
          '<span class="voice">Some say</span> the alchemists&rsquo; return is the Order&rsquo;s '
          'law at its wisest: guilt personal, seats perpetual, and three centuries a sufficient '
          'statute of limitations for anything &mdash; the Wheel turns, and an Order that could '
          'not readmit would eventually be alone with its grudges. <span class="voice">Others '
          'say</span> the warlocks watch this precedent with interest: if lapse of time launders '
          'the alchemists, the Order has priced its forgiveness in centuries, and the clan across '
          'the gutter is patient and keeps excellent records too. The Quaesitors reply that the '
          'alchemists&rsquo; heirs repented and the warlocks did not, and repentance is not a '
          'waiting period; the critics reply that the Order has never tested whether it could tell '
          'a warlock&rsquo;s repentance from a warlock&rsquo;s patience. <span '
          'class="kw">TEYKU</span> &mdash; let the file stay open, as it would anyway.</p>\n'
          '        <p><span class="lemma">Through our door.</span> The catch-all&rsquo;s boast, '
          'pressed. <span class="voice">Some say</span> it is simply true: the Order&rsquo;s '
          'renewals &mdash; the newer charters, the returned alchemists, half the '
          'war-House&rsquo;s best blades &mdash; entered through the House with no standards, '
          'which is to say the House whose standard is promise rather than pedigree. <span '
          'class="voice">Others say</span> the boast indicts the pyramid it decorates: an Order '
          'whose future must be smuggled in through the servants&rsquo; entrance has arranged its '
          'front doors wrong, and knows it, and files the knowledge annually. The great '
          'charters&rsquo; irritation, the Gemara notes, is how the Order preserves its best '
          'sayings; the Masoret adds that preserving a criticism is not the same as obeying it, '
          'and that the Order&rsquo;s genius for the first has always been its substitute for the '
          'second. An objection, from the newer charters&rsquo; benches: the pyramid&rsquo;s '
          'stones were promised to settle with time &mdash; have they? <span class="voice">Answer, '
          'from the drum-House:</span> pyramids do not settle; they weather. The observation is '
          'entered in the minutes, annually, by the scribes&rsquo; House, which keeps its own '
          'counsel and everyone else&rsquo;s records &mdash; an arrangement the Order calls '
          'neutrality and the scribes call, privately, the long game. The scribes, asked directly, '
          'cite attorney&ndash;client privilege, a doctrine they claim to have invented.</p>',
 'outer_head': 'The Advocates<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the warlocks, the heirs, and the door</span>',
 'rubric': 'the thirteen charters, and what the forms have processed',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Houses of Hermes &middot; the roll, the Degrees, and the defection',
 'title': 'Tractate Aliyah · Folio 158b — The Houses: the thirteen charters',
 'type': 'daf'}
