# Folio 158a - The Order of Hermes. Avot mold; facts per the wod-llm-wiki
# Order of Hermes page (M20 pp.158-159; Lore of the Traditions ch.6).
FOLIO = {'bottom': '<p><span class="lemma">On playing a Hermetic.</span> The caricature is the robe and '
           'the Latin; the correction is that the Order is a bureaucracy that works miracles, and '
           'the character concept lives in that hyphen. Give the magus a position &mdash; a House, '
           'a Degree, an oath actually sworn, a superior actually obeyed or actually defied '
           '&mdash; and the grandeur takes care of itself; the Order&rsquo;s theater is '
           'load-bearing, and a Hermetic without institutional coordinates is just a Chorister who '
           'read different books. And let the confidence be real: the books&rsquo; own summary of '
           'the Order&rsquo;s core is confidence, knowledge, excellence, and Will, and a humble '
           'Hermetic is either a survivor of something or lying.</p>\n'
           '        <p><span class="lemma">On the pyramid at the table.</span> The hierarchy is a '
           'chronicle engine, not flavor: every Degree is a door someone guards, every advancement '
           'a scene, every certámen a duel with paperwork and an audience. Run the Order&rsquo;s '
           'politics as its members experience them &mdash; slow, procedural, deadly serious '
           '&mdash; and the player who games the forms is playing the Tradition correctly. The '
           'grudges are constitutional; the committee is eternal; the fireball is, as folio 515a '
           'rules, mostly a threat made credible by paperwork.</p>\n'
           '        <p><span class="lemma">On decline as premise.</span> The Order the books '
           'present has lost its great fortress, its greatest archmage, and a House to corruption '
           'within living memory, and is still the Council&rsquo;s spine. Play both facts. A '
           'chronicle that leans only on the grandeur gets a museum; only on the decline, a wake. '
           'The working Hermetic scene is a proud institution holding itself together on procedure '
           'and Will, which is to say: drama, pre-installed.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on position, procedure, and proud '
                'decline</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Order of Hermes holds</span> that reality obeys hidden law, '
           'and that the disciplined Will, correctly instructed, may command what it '
           'comprehends.<sup>a</sup> Their practice is the High Art: formulaic magick of ritual, '
           'true name, and sacred geometry, worked exactly or not at all; their instruments are '
           'the instruments of study &mdash; the grimoire, the circle, the word of power, the name '
           'that compels. Their seat among the Nine is <span '
           'class="term">Forces</span>.<sup>b</sup> Their internal law is the densest in the '
           'Council: the Order is divided into <span class="term">Houses</span>, each a lineage '
           'with its own charter; governed by the <span class="term">Code of Hermes</span> and its '
           'corrigenda; ranked through nine <span class="term">Degrees</span>, from neophyte to '
           'master of the world; bound by oaths that are themselves workings; and disciplined by '
           '<span class="term">cert&aacute;men</span>, the formal duel, which settles what '
           'committees cannot.<sup>c</sup> Great workings are chartered in advance and archived '
           'after &mdash; the Order&rsquo;s is the only magick in the Council with minutes &mdash; '
           'and a magus&rsquo;s true name is deposited under seal with her House, the deposit '
           'being the House&rsquo;s gravest trust and the Order&rsquo;s oldest.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> On a midwinter night '
           'in the year 767, a seer gathered the quarreling wizards of the West into one Order of '
           'twelve Houses, and the Order took itself a fortress beyond the world and began to '
           'legislate.<sup>d</sup> It has been legislating since: through the loss of a House to '
           'the deathless leeches &mdash; a defection tried in a sibling tractate, and the grudge '
           'is constitutional; through the burning centuries; through the tribunal its own master '
           'convened that began the Convocation of folio 2a. It gave the Council its law&rsquo;s '
           'grammar and the First Cabal its pride. And in living memory it has buried the '
           'fortress, the archmage who was its age&rsquo;s greatest, and a House corrupted from '
           'within and purged &mdash; and convened, each time, the appropriate committee. <span '
           'class="kw">OUR TEACHERS TOLD:</span> a neophyte asked her superior why the Order files '
           'a form to mourn. Because, said the magus, grief ends and the file remains; the Order '
           'has outlived everything it loved by exactly this method. The disputants opposite '
           'consider whether the method is the achievement or the disease.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; sixth of the Avot; the Houses are mustered '
             'overleaf.',
 'folio': '158A',
 'glossL': '<p><span class="mark">a</span> On the Order of Hermes entire, see M20, the Traditions '
           'chapter, folio 158, whence this page takes its number; the Order&rsquo;s history fills '
           'more shelves than any two siblings&rsquo; together.</p>\n'
           '        <p><span class="mark">b</span> On the seat of Forces and the Order&rsquo;s '
           'famous appetite for it, see folio 515a, which is bound, and its Masoret, which names '
           'them.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Code, the Degrees, and the '
           'thirteen persisting Houses, see the Lore of the Traditions chapter on the Order.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Trianoma&rsquo;s midwinter '
           'founding, Doissetep, and Mistridge&rsquo;s master La Salle, see the histories cited at '
           'folio 2a and the Order&rsquo;s own books.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Cert&aacute;men&rsquo;s institution is folio 143, bound behind this leaf, and its old-form mechanics are folio 430; this '
           'folio&rsquo;s law is their preamble.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The defected House became '
           'the warlock clan of Tractate Masekha, and the grudge runs across the seder&rsquo;s '
           'gutter: one lineage, two tractates, no peace. The Masoret finds this the '
           'corpus&rsquo;s finest cross-reference and declines to apologize for saying so.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The fallen House purged in '
           'living memory was exposed by the same Hermetic diligence that exposed the '
           'Chakravanti&rsquo;s &mdash; folio 156a; the Order audits its neighbors no more gently '
           'than itself, which its neighbors have noticed.</p>',
 'h1': 'The Order of Hermes',
 'hagahah': 'The Order has a form for schism. It is in triplicate; two copies file with the '
            'Quaesitors and one remains with the schismatic, for his records. The joke is old, '
            'Hermetic in origin, and told by the Order about itself &mdash; which is the detail '
            'outsiders reliably miss.',
 'inner': '<p><span class="lemma">Correctly instructed.</span> The paradigm&rsquo;s plain sense: '
          'Hermetic magick is jurisprudence practiced on the cosmos. The world is a text with '
          'rules; the magus masters the rules; the working is an argument the universe is obliged '
          'to accept because it is validly formed. Hence the exactness &mdash; a flawed ritual is '
          'not weak, it is <span class="aside">void</span> &mdash; and hence the Order&rsquo;s '
          'temperamental kinship with this tractate, which it would edit.</p>\n'
          '        <p><span class="lemma">Worked exactly or not at all.</span> The '
          'practice&rsquo;s plain sense at the table: preparation is the Hermetic&rsquo;s native '
          'tempo. Given a night and a library she is the most dangerous mage alive; ambushed in an '
          'alley she is a scholar with a staff. Play the tempo honestly &mdash; the rote prepared, '
          'the contingency inscribed, the true name researched three sessions early &mdash; and '
          'the character rewards exactly the kind of player the Tradition itself recruits.</p>\n'
          '        <p><span class="lemma">Each a lineage with its own charter.</span> The '
          'Houses&rsquo; plain sense: the Order is a federation wearing a uniform. A House is '
          'ancestry, curriculum, and faction at once, and two magi of rival Houses share a Code '
          'the way rival law firms share a bar association. The verso musters them; this page '
          'rules only that House membership is constitutional fact, not flavor &mdash; oaths run '
          'through it, and so do the grudges.</p>\n'
          '        <p><span class="lemma">Oaths that are themselves workings.</span> The plain '
          'sense, and the Order&rsquo;s teeth: a Hermetic oath is cast, not merely sworn. The word '
          'given binds as a pattern binds, which is why the Order&rsquo;s politics, however '
          'vicious, stay inside the forms &mdash; the forms are load-bearing walls, and everyone '
          'inside can feel them hold. A mage&rsquo;s word is her honor everywhere in the Council; '
          'here it is also, measurably, her pattern.</p>\n'
          '        <p><span class="lemma">Which settles what committees cannot.</span> '
          'Cert&aacute;men&rsquo;s plain sense in the constitution: the duel is the Order&rsquo;s '
          'safety valve, the licensed exception that keeps the hierarchy from rule by '
          'assassination. Its mechanics wait at folio 430; its law here is jurisdictional &mdash; '
          'what may be staked, who must consent, and the standing of the verdict, which binds as '
          'precedent binds. The Order taught the Council to duel instead of feud, and counts it '
          'among its gifts; the recipients&rsquo; gratitude varies.</p>\n'
          '        <p><span class="lemma">Deposited under seal.</span> The name custody&rsquo;s '
          'plain sense: the High Art works by true names, so every magus is, to a colleague with '
          'her name, a door with the key left in it. The deposit squares the circle &mdash; the '
          'Order must be able to find its own, and no individual may hold that power over another '
          '&mdash; so the name lies under seal, opened only by tribunal warrant, and the '
          'seal&rsquo;s integrity is audited by the judges&rsquo; House with the enthusiasm they '
          'bring to everything. The warlocks of the sibling tractate took their deposits with '
          'them, which is the theft the Order mentions third and minds first.</p>\n'
          '        <p><span class="lemma">The only magick with minutes.</span> The archive '
          'clause&rsquo;s plain sense: a Hermetic working of consequence exists three times '
          '&mdash; as charter, as act, and as record &mdash; and the record is law: precedent for '
          'the next petitioner, evidence for the next tribunal. The practical gift to a chronicle '
          'is enormous and double-edged; whatever the cabal needs to know, somewhere the Order has '
          'minutes, and whatever the cabal has done, someone is minuting.</p>',
 'inner_head': 'On the Art<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; law, tempo, and the forms</span>',
 'name': 'The Order of Hermes',
 'outer': '<p><span class="lemma">The densest in the Council.</span> Strength or sclerosis &mdash; '
          'the folio&rsquo;s central dispute. <span class="voice">Some say</span> the density is '
          'the Order: structure is why it alone spans twelve centuries with unbroken records, why '
          'its oaths hold when charisma dies, why the Council&rsquo;s own law is written in '
          'Hermetic grammar. Institutions are how the dead help the living fight; the Order is the '
          'Ascension War&rsquo;s standing army, and armies drill. <span class="voice">Others '
          'say</span> the density is the tomb: the Order&rsquo;s last unambiguous triumph predates '
          'the telegraph; its response to every catastrophe of the modern age &mdash; the fortress '
          'lost, the archmage gone, the House rotted &mdash; was a committee, correctly convened, '
          'minuting the decline in excellent Latin. The forms survive because forms are what '
          'survives when the thing they organized has left. An objection to the critics: the purge '
          'of the rotted House worked &mdash; the machinery caught its own corruption and cut it '
          'out. <span class="voice">Answer:</span> after a generation of rot; audit the latency, '
          'not the verdict. An objection to the defenders&rsquo; critics: name the Tradition that '
          'would have caught it faster. <span class="voice">Answer:</span> the room goes quiet, '
          'which the defenders enter into the minutes.</p>\n'
          '        <p><span class="lemma">The grudge is constitutional.</span> The Order&rsquo;s '
          'memory dispute. <span class="voice">Some say</span> the eternal grudges &mdash; the '
          'defected House, the purged one, the feuds between charters older than nations &mdash; '
          'are the price of the records: an institution that forgets nothing forgives on a '
          'geological schedule, and the warlock clan of the sibling tractate has earned every '
          'century of it. <span class="voice">Others say</span> a constitution of grudges '
          'conscripts the young into the dead&rsquo;s quarrels: the neophyte swears enmities she '
          'did not choose against heirs who did not choose either, and the Order&rsquo;s finest '
          'minds spend lifetimes prosecuting history instead of the Union. The defenders answer '
          'that the young swear the whole charter or none, and knew it; the critics answer that so '
          'does every heir to every feud, which is the problem stated, not solved.</p>\n'
          '        <p><span class="lemma">The method is the achievement or the disease.</span> The '
          'maaseh&rsquo;s question, put to the whole Tradition. <span class="voice">Some '
          'say</span> the form filed against grief is the deepest thing the Order knows: Will is '
          'the art of acting correctly while feeling otherwise, and the neophyte was shown the '
          'Tradition&rsquo;s actual secret &mdash; continuity is a discipline, and discipline is '
          'love with a filing system. <span class="voice">Others say</span> the magus answered a '
          'question about mourning with a theory of archives, which is the disease presenting as '
          'the cure; ask the Chakravanti, one folio back, what happens to workers who procedure '
          'their way past feeling. The Masoret notes the chapter&rsquo;s quiet rhyme &mdash; jhor '
          'for the death-mages, the file for the law-mages, each Tradition&rsquo;s strength '
          'curdling in its own direction &mdash; and the tractate, which is also a filing system '
          'built against loss, declines to vote. The file on that question remains, of course, '
          'open; it is the Order&rsquo;s longest.</p>',
 'outer_head': 'The Tribunal<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the pyramid, the grudges, and the file</span>',
 'rubric': 'the High Art, its law, and its ledgers',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Order of Hermes &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 158a — The Order of Hermes: the High Art, its law, and its '
          'ledgers',
 'type': 'daf'}
