# Folio 160b - Paradigma. Verso of the Society of Ether folio: the journal
# as tribunal, the Symposium, and the methodological schools, per the
# wod-llm-wiki Society of Ether page (LotT ch.7).
FOLIO = {'bottom': '<p><span class="lemma">On the journal as campaign.</span> A chronicle can be run '
           'entirely in Paradigma&rsquo;s margins: the disputed submission, the referee gone '
           'missing, the result nobody can replicate because the phenomenon has opinions, the '
           'letters column escalating toward a duel by demonstration. Academic procedure with '
           'lightning is a genre unto itself, and the Society is its only publisher; a troupe of '
           'rival Scientists racing to press is as complete a premise as any war.</p>\n'
           '        <p><span class="lemma">On the schools as texture.</span> Do not file the '
           'methodological schools as classes: they are temperaments, and their members argue like '
           'a family that shares one garage. The adventurer who thinks a theory untested against a '
           'lost world is hearsay; the cybernaut for whom flesh is legacy hardware; the utopian '
           'who reads every device as a draft of the better world &mdash; seat any three at one '
           'bench and the scene runs itself. The rule of thumb from the books: every school claims '
           'members of every politics, so no school is the villain and none is safe.</p>\n'
           '        <p><span class="lemma">On the expos&eacute; in play.</span> The 1935 reckoning '
           'is usable history: somewhere in the chronicle&rsquo;s city is a result still credited '
           'to the wrong Scientist, and the archives can prove it. A restitution plot &mdash; '
           'recover the notebook, re-run the demonstration, force the citation &mdash; lets a '
           'table play the Tradition&rsquo;s reform as detective work rather than discourse, which '
           'is how this Tradition would prefer to conduct it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on margins, temperaments, and '
                'restitution by citation</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The journal is the tribunal.</span> What the Society knows, it '
           'knows in print: a claim is made by submission, tried by referees who are rivals, and '
           'proven at the <span class="term">Symposium</span>, where the apparatus must run before '
           'the assembled &mdash; applause and catastrophe being the recognized '
           'verdicts.<sup>a</sup> Priority is sacred: the first to demonstrate holds the result, '
           'and theft of credit is the Society&rsquo;s gravest internal crime, tried harder than '
           'sabotage.<sup>b</sup> The schools of method stand equal before the journal &mdash; the '
           'explorers of lost worlds and deep waters, the engineers of flesh and machine, the '
           'ethernauts of the spaces between, the perfectors of the better world &mdash; and no '
           'school&rsquo;s standards bind another&rsquo;s submissions, only the demonstration '
           'binds.<sup>c</sup> And the archive is corrected, never expunged: a retracted result '
           'stays printed with its retraction stapled to it, that the record of error be itself a '
           'record.<sup>d</sup> Three findings are recognized: replicated, contested, and '
           'retracted; a contested result may be defended at any Symposium by any Scientist, not '
           'only its author, for the claim outlives the claimant. And the journal admits no '
           'anonymous submission &mdash; save one, which stands. Referees serve masked; authors '
           'serve named, always.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the severity '
           'about credit? From the year the journal tried itself. An anonymous number of '
           'Paradigma, in 1935, laid out with citations what everyone&rsquo;s laboratory already '
           'knew: that the gentlemen of the Society had for decades published the work of '
           'colleagues barred from the Symposium&rsquo;s floor &mdash; the wrong continents, the '
           'wrong sexes, the wrong dinners. The number was never withdrawn, its author never '
           'found, and its footnotes never refuted, which in this Tradition is the only verdict '
           'that matters. The Society answered as it answers everything: it published, corrected, '
           'and did not expunge &mdash; and the stapled retractions of that era are read aloud, by '
           'statute, at the opening of every Symposium since. <span class="kw">IT HAPPENED '
           'THAT</span> a young Scientist asked why the reading is repeated annually when everyone '
           'present has heard it. The chair answered: replication. The disputants opposite take '
           'the joke seriously, as it was meant.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Society&rsquo;s folio: the recto '
             'keeps the method, this side keeps the minutes.',
 'folio': '160B',
 'glossL': '<p><span class="mark">a</span> On Paradigma, the Symposium, and proof by '
           'demonstration, see the Society&rsquo;s entries in M20 and the Lore of the Traditions '
           'chapter.</p>\n'
           '        <p><span class="mark">b</span> On the methodological groups &mdash; '
           'adventurers, aquanauts, cybernauts, ethernauts, the mad, the progressivists, the '
           'utopians &mdash; see the Lore of the Traditions chapter&rsquo;s survey.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the anonymous expos&eacute; of '
           '1935 and the reckoning it opened, see the same chapter; the books quote its temper '
           'better than this page may.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the political divisions &mdash; '
           'establishment, futurist, and the great nonsectarian middle &mdash; see the same '
           'chapter.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto rules that rank follows publication; '
           'this verso is that clause&rsquo;s procedure. Read the pair as one law: the journal is '
           'the pyramid this Tradition built instead of the Order&rsquo;s, folio 158a, and the two '
           'structures criticize each other by existing.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Priority and credit rhyme '
           'with the Record of folio 148a &mdash; two Traditions that cannot falsify their '
           'archives, one by cosmology, one by statute. The statute is the more fragile and knows '
           'it; hence the stapling.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Symposium&rsquo;s '
           'duel-by-demonstration is cert&aacute;men&rsquo;s cousin, folio 143; stakes on '
           'the bench instead of the circle, and the apparatus as second.</p>',
 'h1': 'Paradigma',
 'hagahah': 'The journal&rsquo;s title is the Society&rsquo;s entire self-knowledge in one word: '
            'they know exactly what they are defending, they named it on the masthead, and they '
            'publish quarterly proof that a paradigm with referees is still a paradigm. No other '
            'Tradition is this honest on its own letterhead.',
 'inner': '<p><span class="lemma">Tried by referees who are rivals.</span> The plain sense of '
          'Etherite review: impartiality is not attempted &mdash; it is not believed in &mdash; '
          'and the system harnesses partiality instead. Your referee wants you wrong; if your '
          'apparatus survives him, it survives; and the reviewed who cries bias is handed the '
          'standard reply, which is a bench and a date. Adversarial to the bone, and therefore, '
          'the Society insists, honest.</p>\n'
          '        <p><span class="lemma">Applause and catastrophe being the recognized '
          'verdicts.</span> Plain sense: the Symposium admits no middle finding. A demonstration '
          'that neither works nor explodes is ruled <span class="aside">incomplete</span> and '
          'returns to the bench; the Society&rsquo;s folklore holds that the universe respects '
          'commitment, and its safety record holds that the folklore is expensive. Etherite '
          'Paradox, note, arrives disproportionately at Symposia &mdash; the one audience before '
          'whom nothing may be quietly coincidental.</p>\n'
          '        <p><span class="lemma">Priority is sacred.</span> The credit law&rsquo;s plain '
          'sense: in a Tradition without Degrees, the citation is the currency, the pension, and '
          'the tombstone. Theft of credit therefore steals a colleague&rsquo;s entire standing at '
          'one stroke &mdash; the 1935 number called it, precisely, the theft of lives &mdash; and '
          'the modern statute&rsquo;s severity is that history metabolized. Sabotage, by contrast, '
          'merely destroys apparatus, and apparatus can be rebuilt by anyone with the blueprint, '
          'which is why the blueprint&rsquo;s byline matters more.</p>\n'
          '        <p><span class="lemma">Corrected, never expunged.</span> The archive '
          'law&rsquo;s plain sense, and its wisdom: a journal that deleted its errors would be '
          'trusted exactly as far as its current editors, and the Society has met its current '
          'editors. The stapled retraction preserves both the error and the correction as one '
          'document &mdash; the method made visible &mdash; and the annual reading of the worst '
          'era&rsquo;s staples is the Tradition vaccinating itself with its own case history. '
          'Replication, as the chair said. The joke is load-bearing.</p>\n'
          '        <p><span class="lemma">The claim outlives the claimant.</span> The inheritance '
          'clause&rsquo;s plain sense: results are the Society&rsquo;s real estate, and they pass '
          'by intellectual descent &mdash; a dead Scientist&rsquo;s contested findings may be '
          'defended by her students, her rivals, or a stranger moved by the blueprints, and the '
          'defender earns the citation&rsquo;s interest without touching its principal. The estate '
          'sales of the great dead are the Symposium&rsquo;s quietest drama: benches of unproven '
          'wonders, claims half-defended, and the occasional apparatus that resumes running by '
          'itself, which the probate committee has learned to price in.</p>\n'
          '        <p><span class="lemma">Save one, which stands.</span> The exception&rsquo;s '
          'plain sense: the anonymity ban exists because demonstration requires a demonstrator '
          '&mdash; someone must stand at the bench and own the catastrophe &mdash; and the 1935 '
          'number is exempted not by kindness but by category: it demonstrated nothing and '
          'documented everything, a finding of record rather than of bench. The exemption is '
          'carved that narrowly on purpose, and the Society&rsquo;s law students &mdash; it has '
          'them &mdash; cut their teeth arguing whether it could ever apply twice.</p>',
 'inner_head': 'On the Minutes<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; review, priority, and the stapled archive</span>',
 'name': 'Paradigma',
 'outer': '<p><span class="lemma">Only the demonstration binds.</span> But what does a '
          'demonstration demonstrate? The verso inherits the recto&rsquo;s worst question in '
          'procedural dress. <span class="voice">Some say</span> the Symposium proves phenomena: '
          'the apparatus runs, the referees are hostile, the finding survives &mdash; epistemology '
          'has no higher court, and the Consensus&rsquo;s refusal to ratify Etherite results is '
          'politics, not physics. <span class="voice">Others say</span> the Symposium proves '
          'consensus &mdash; a small one, wearing goggles: an audience of believers watching a '
          'believer&rsquo;s device is folio 62&rsquo;s thesis in a lecture hall, and the finding '
          'that survives hostile Etherite review has established, rigorously, what Etherites can '
          'be made to believe. The Society&rsquo;s riposte &mdash; that this describes every '
          'laboratory on earth including the Union&rsquo;s &mdash; is correct, and is also the '
          'most Etherite sentence ever uttered: the defense that indicts everyone is still an '
          'indictment, published, with the Society&rsquo;s own name first in the citation '
          'order.</p>\n'
          '        <p><span class="lemma">Never withdrawn, never found, never refuted.</span> The '
          'expos&eacute;&rsquo;s three negatives, disputed. <span class="voice">Some say</span> '
          'the anonymity was the point&rsquo;s perfection: a Tradition of bylines was forced to '
          'weigh a claim with no author to punish, and the claim stood on footnotes alone &mdash; '
          'the method vindicated at the Society&rsquo;s expense, by the Society&rsquo;s own '
          'instrument. <span class="voice">Others say</span> the anonymity was the '
          'indictment&rsquo;s second count: a body where such a number required namelessness had '
          'already convicted itself of the retaliation everyone knew would follow a signature. '
          'Both readings are kept at the annual reading, which is presumably why the author '
          '&mdash; whoever, whichever school, however long-lived &mdash; has never claimed the '
          'priority that is, by the recto&rsquo;s own law, sacred. The one uncollected citation in '
          'the Society&rsquo;s history sits in its founding wound, and the Masoret declines to say '
          'whether that is penance or the finest irony in the seder.</p>\n'
          '        <p><span class="lemma">The schools stand equal.</span> A procedural difficulty '
          'with teeth. <span class="voice">Some say</span> the equality clause is the '
          'Society&rsquo;s pluralism perfected: no school&rsquo;s metaphysics gates '
          'another&rsquo;s bench, and the aquanaut&rsquo;s deep-sea impossible and the '
          'utopian&rsquo;s social one meet only at the demonstration, which cannot be lobbied. '
          '<span class="voice">Others say</span> the clause quietly decides the deepest fight in '
          'the Tradition: by ruling that only demonstration binds, the journal has ruled that what '
          'cannot be benched cannot be knowledge &mdash; and the utopians&rsquo; better world, the '
          'futurists&rsquo; reckoning, the whole reform, must forever submit as apparatus or '
          'remain editorial. The reformers&rsquo; answer has been to build apparatus &mdash; '
          'restitution engines, credit audits, the reading itself &mdash; which either proves the '
          'system absorbs its critics or proves the critics learned where the power sits. <span '
          'class="kw">TEYKU</span> &mdash; the referee reports are split, and the phenomenon, as '
          'ever, has opinions. The referees&rsquo; own reports on this question are, by long '
          'custom, unsigned &mdash; a custom nobody has dared submit to review, it being the one '
          'result the whole Society has replicated.</p>',
 'outer_head': 'The Referees<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the proof, the anonym, and the bench</span>',
 'rubric': 'the journal as tribunal, and its stapled memory',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of Paradigma &middot; peer review as law',
 'title': 'Tractate Aliyah · Folio 160b — Paradigma: the journal as tribunal',
 'type': 'daf'}
