# Folio 160a - The Society of Ether. Avot mold; facts per the wod-llm-wiki
# Society of Ether page (M20 pp.160-161; Lore of the Traditions ch.7).
FOLIO = {'bottom': '<p><span class="lemma">On playing a Scientist.</span> The pitfall is the goggles '
           'without the grief: mad science as aesthetic. The books&rsquo; Etherite is a genuine '
           'researcher whom orthodox science genuinely exiled, and the character needs both halves '
           '&mdash; the joyous certainty that the universe is stranger and better than the '
           'journals admit, and the wound of having been laughed out of the room that should have '
           'cheered. Give the character a theory she would die for and a rejection she has not '
           'forgiven, and the Ether flows; give her only a ray gun and you have costumed a '
           'Hermetic in brass.</p>\n'
           '        <p><span class="lemma">On demonstration as scene.</span> The Tradition&rsquo;s '
           'peer review &mdash; proof by working demonstration, before rivals, with applause or '
           'catastrophe on the table &mdash; is a ready-made set piece. Stage the Symposium: the '
           'cabal&rsquo;s Scientist presenting, the rival discreetly sabotaging, the review board '
           'of three magnificent egos, the demo that must merely work <span '
           'class="aside">once</span>. No other Tradition hands the Storyteller a scene where the '
           'magick system is itself the social system; spend it at least once a chronicle.</p>\n'
           '        <p><span class="lemma">On the Union across the bench.</span> Keep the special '
           'relationship live: the Etherites are the Technocracy&rsquo;s runaway sibling, and both '
           'sides remember the house rules. Technocrat NPCs should treat the Society with the '
           'exasperated familiarity of colleagues, not the horror they reserve for witches &mdash; '
           'offers of readmission, poached students, conference invitations with strings. The '
           'Tradition&rsquo;s best temptations arrive with a lanyard and a lab.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on wounds, symposia, and the sibling '
                'across the bench</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Society of Ether holds</span> that Science is not a '
           'catalogue but a frontier: the possible exceeds the published, and a theory is owed a '
           'hearing, not a consensus.<sup>a</sup> Their practice is Inspired Science &mdash; '
           'hypothesis worked in brass and lightning; their instruments are the built ones: the '
           'device, the laboratory, the blueprint, the demonstration. Their seat among the Nine is '
           '<span class="term">Matter</span>, held as heirs to the alchemists&rsquo; '
           'chair.<sup>b</sup> Their internal law is <span class="term">peer review by '
           'demonstration</span>: a claim stands when it is shown working before rivals, and falls '
           'when it is not, and rank follows publication &mdash; the Society&rsquo;s journal is '
           'its tribunal.<sup>c</sup> And one article of the old physics is kept by statute: the '
           '<span class="term">Ether</span> is affirmed &mdash; the subtle medium the Consensus '
           'deprecated &mdash; for the Society does not concede a truth merely because the world '
           'was argued out of it.<sup>d</sup> Catastrophe at the bench is an honorable verdict, '
           'mourned and cited; sabotage is tried harshly, and theft of credit more harshly still, '
           'as the verso provides; and a Scientist&rsquo;s apparatus is her own &mdash; the '
           'Society confiscates nothing, having been founded by people whose instruments were '
           'confiscated.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> They were of '
           'Reason&rsquo;s own order once: natural philosophers, then engineers of the electric '
           'age, standing inside the Union&rsquo;s walls. And when the Union&rsquo;s inner circle '
           'struck the Ether from the books &mdash; not disproven, the Society maintains, but '
           '<span class="aside">deprecated</span>, a budget line closed &mdash; the engineers '
           'walked out, in 1904, carrying their instruments and their affirmation, and petitioned '
           'the Council their ancestors had fought. The Council seated them in the '
           'alchemists&rsquo; long-empty chair, and folio 3a keeps the ruling: the seat outlived '
           'its disgrace, and the newcomers inherited the chair and not the guilt. <span '
           'class="kw">OUR TEACHERS TOLD:</span> a young Scientist asked her mentor why the '
           'Society affirms a substance the instruments cannot find. The mentor said: the '
           'instruments were built by the winners. Build better instruments. She did; the '
           'Symposium is still arguing about what they measure; and the disputants opposite '
           'consider whether that argument is the Society&rsquo;s vindication or its epitaph.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; seventh of the Avot; the journal itself is '
             'overleaf.',
 'folio': '160A',
 'glossL': '<p><span class="mark">a</span> On the Society of Ether entire &mdash; the Sons of '
           'Ether that were, the Etherites &mdash; see M20, the Traditions chapter, folio 160, '
           'whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the lineage &mdash; the Kitab-al-Alacir, '
           'House Golo, the Natural Philosophers, the Electrodyne Engineers &mdash; see the Lore '
           'of the Traditions chapter and the Revised Tradition book.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the 1904 secession over the '
           'Ether&rsquo;s deprecation, see the same chapters; the Society&rsquo;s account and the '
           'Union&rsquo;s differ in tone and not much in fact.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the seat inherited from the '
           'Solificati, see folio 3a, ruling ii, which this folio cites as its title deed.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 517; the conjunction fight it stages with Prime at folios 517 and 520 was promised by folio 515a&rsquo;s gloss and is kept at 515b.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The secession of 1904 is the '
           'mirror of folio 164&rsquo;s defection: two children of the Union at the '
           'Council&rsquo;s table, one that walked out over a theory, one that was driven out over '
           'a man. Chapter VI states the Union&rsquo;s side; the Masoret keeps the seating chart.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The alchemists&rsquo; fall '
           'itself is folio 2b&rsquo;s trial; their return as the Children of Knowledge stands '
           'among the unseated of folio 3b. One chair, three claimants across six centuries '
           '&mdash; the tractate&rsquo;s longest probate.</p>',
 'h1': 'The Society of Ether',
 'hagahah': 'The difference between mad science and Science is one accepted paper. The '
            'Society&rsquo;s founding grievance is that the acceptance committee was captured; its '
            'founding genius is that it responded by starting a journal. Revolutions have been '
            'declared over worse, but rarely with better citations.',
 'inner': '<p><span class="lemma">A frontier, not a catalogue.</span> The paradigm&rsquo;s plain '
          'sense: the Etherite&rsquo;s magick is hypothesis enacted. She does not petition hidden '
          'law like the Hermetic nor join a song like the Chorister; she proposes, builds, and '
          'tests, and the universe is her collaborator with review privileges. Failure is data; '
          'the explosion is a finding; and the Sphere of Matter answers her because matter is the '
          'laboratory&rsquo;s native tongue.</p>\n'
          '        <p><span class="lemma">Worked in brass and lightning.</span> The instrument '
          'law&rsquo;s plain sense: the device is the working. An Etherite&rsquo;s effect rides a '
          'machine that ought not function and does, which makes her magick conspicuously '
          'confiscatable &mdash; the inverse of the Brotherhood&rsquo;s naked-cell advantage two '
          'folios back. The compensation is that the device persists: a working mage sleeps, but '
          'the ray gun is still a ray gun in the morning, and Wonders are this Tradition&rsquo;s '
          'export crop.</p>\n'
          '        <p><span class="lemma">Rank follows publication.</span> The '
          'tribunal-journal&rsquo;s plain sense: the Society&rsquo;s hierarchy is a citation '
          'graph. No Degrees, no Curia &mdash; standing accrues to the demonstrated result, and '
          'the review is peer in the fullest sense: conducted by rivals, in public, with the '
          'apparatus running. The politics this breeds are vicious in the way of faculty politics '
          'everywhere, with the amendment that the faculty are armed.</p>\n'
          '        <p><span class="lemma">The Ether is affirmed.</span> The plain sense of the '
          'statute, and read it carefully: the Society does not affirm every discarded theory '
          '&mdash; it affirms this one, as the test case of its whole jurisprudence. The claim is '
          'that the Consensus deprecates truths for reasons that are not evidence &mdash; '
          'politics, parsimony, the Union&rsquo;s tidy-mindedness &mdash; and the Ether is the '
          'exhibit the Society will not let the court seal. Whether the exhibit is a truth or a '
          'relic is the disputants&rsquo; first case opposite.</p>\n'
          '        <p><span class="lemma">Heirs to the alchemists&rsquo; chair.</span> The '
          'inheritance&rsquo;s plain sense: the Society sits in a seat with a history, and knows '
          'it &mdash; the alchemists fell by treachery, the chair sat empty four centuries, and '
          'the engineers who filled it are heirs by ruling, not by blood. The Tradition&rsquo;s '
          'occasional defensiveness about pedigree is this fact metabolized; its genuine humility '
          'about seats and their guilt is folio 3a&rsquo;s ruling metabolized better.</p>\n'
          '        <p><span class="lemma">Catastrophe at the bench.</span> The honorable '
          'verdict&rsquo;s plain sense: an Etherite demonstration that explodes has still '
          'demonstrated &mdash; the theory engaged the world and the world answered, and the '
          'answer is data with a crater. The Society&rsquo;s obituaries read like abstracts, its '
          'abstracts like adventures, and its Paradox exposure clusters at Symposia, where nothing '
          'may be quietly coincidental before an audience professionally required to notice. The '
          'young are taught the distinction early: the disgrace is not the explosion; the disgrace '
          'is the explosion unrecorded.</p>\n'
          '        <p><span class="lemma">Her apparatus is her own.</span> The property '
          'clause&rsquo;s plain sense: the device is the Scientist&rsquo;s working, her '
          'publication, and her estate, and the Society&rsquo;s founding trauma &mdash; '
          'laboratories inventoried and sealed by the Union it fled &mdash; is written into the '
          'law as an absolute. Even tribunal sanctions run against the person, never the bench; '
          'the wonders of the disgraced are escrowed, not seized. The Council finds this '
          'eccentric; the Etherites find the Council&rsquo;s surprise instructive.</p>',
 'inner_head': 'On the Method<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; hypothesis, device, and journal</span>',
 'name': 'The Society of Ether',
 'outer': '<p><span class="lemma">Apostates or conscience.</span> What is the Society to Science? '
          '<span class="voice">Some say</span> its conscience in exile: the scientific method '
          'belongs to no committee, and the Etherites practice it purer than the Union does '
          '&mdash; hypothesis, demonstration, revision, without the Timetable&rsquo;s politics '
          'deciding in advance what may be found. On this reading the Society is what science '
          'looks like when it stays curious, and the Union is what it looks like captured. <span '
          'class="voice">Others say</span> apostates flattering themselves: science is precisely '
          'the discipline of submitting to the evidence <span class="aside">even when the '
          'committee is odious</span>, and a Society whose founding statute affirms a theory by '
          'law has renounced the method it claims to embody &mdash; keeping the Ether by statute '
          'is exactly what the Union did in reverse, a consensus of the minority. An objection: '
          'the Ether demonstrably works for them; their ships sail on it. <span '
          'class="voice">Answer:</span> in this setting everything demonstrably works for its '
          'believers; that is what folio 62 is about, and why the dispute cannot be settled '
          'by pointing at the ships. The Society knows this answer and hates it more than any '
          'other sentence in the tractate.</p>\n'
          '        <p><span class="lemma">All, or none.</span> The reform dispute, in the '
          'Society&rsquo;s registers. The chapter&rsquo;s pattern holds &mdash; here the reckoning '
          'is with the boys&rsquo; club: the anonymous expos&eacute; of 1935 documented the '
          'Society&rsquo;s European gentlemen publishing the stolen work of colleagues the '
          'gentlemen would not seat at dinner. <span class="voice">The futurists say</span> the '
          'Tradition&rsquo;s own method convicts its past &mdash; suppressed data is bad science, '
          'whoever suppresses it &mdash; and the re-Wondering of the world begins with '
          're-crediting it. <span class="voice">The establishment answers</span> variously and '
          'increasingly quietly; the largest faction, as the books dryly note, avoids the whole '
          'question by never leaving the lab, which is itself a position with a history. The '
          'journal, meanwhile, publishes the argument &mdash; which the futurists count as '
          'victory, since for this Tradition, publication is what existence means.</p>\n'
          '        <p><span class="lemma">Vindication or epitaph.</span> The mentor&rsquo;s '
          'maaseh, pressed. <span class="voice">Some say</span> &ldquo;build better '
          'instruments&rdquo; is the whole Tradition in four words: the winners&rsquo; instruments '
          'define the world, and the Society exists to keep one workshop outside that monopoly '
          '&mdash; its affirmed Ether is less a physics than a jurisdiction, the last laboratory '
          'the Consensus does not inspect. <span class="voice">Others say</span> the four words '
          'concede the case: instruments that must be built to find their phenomenon have reversed '
          'the method&rsquo;s arrow, and a jurisdiction defended forever is called, by everyone '
          'outside it, a paradigm &mdash; folio 567 files the Society there '
          'with terrible courtesy. The Symposium&rsquo;s standing reply is a demonstration; '
          'the demonstration works; the argument survives it; and the Society would not actually '
          'have it any other way, which may be the healthiest sentence in this chapter. The '
          'Symposium has voted twice on whether that sentence is admissible; the motion carried '
          'once each way; the demonstration continues.</p>',
 'outer_head': 'The Peer Review<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the method, the club, and the instruments</span>',
 'rubric': 'Inspired Science, its journal, and its affirmed Ether',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Society of Ether &middot; the Tradition as law, its lineage as '
             'aggada',
 'title': 'Tractate Aliyah · Folio 160a — The Society of Ether: Inspired Science and its affirmed '
          'Ether',
 'type': 'daf'}
