# Folio 162a - The Verbena. Avot mold; facts per the wod-llm-wiki Verbena
# page (M20 pp.162-163; Lore of the Traditions ch.8).
FOLIO = {'bottom': '<p><span class="lemma">On playing a witch.</span> Two caricatures guard this '
           'Tradition&rsquo;s door: the gentle herbalist with a cat, and the blood-soaked '
           'primitive. The books&rsquo; Verbena is neither and both &mdash; a healer whose '
           'medicine includes the knife, an archaist with a smartphone she resents, a member of '
           'the Council&rsquo;s most militant Tradition whose daily work is midwifery. Build the '
           'character on the cycle: what does she tend, what does she cull, and what has she paid '
           'in her own blood &mdash; the Tradition&rsquo;s rites begin at the practitioner&rsquo;s '
           'skin, and a Verbena who has never bled for a working is a tourist.</p>\n'
           '        <p><span class="lemma">On the rites at the table.</span> Blood, sacrifice, and '
           'the old fertility rites touch table limits as surely as the Ecstatics&rsquo; '
           'instruments, and the same procedure governs: lines and veils in session zero, on '
           'paper. Decide what the chronicle&rsquo;s covens actually do at Beltane and what stays '
           'firelight and implication; the Tradition&rsquo;s power to unsettle is real and should '
           'be spent deliberately, on the story, never on a player.</p>\n'
           '        <p><span class="lemma">On the Burning Times in play.</span> The remembered '
           'fires are the Tradition&rsquo;s spine and its trap: an NPC elder for whom every '
           'Technocrat is a witch-hunter reborn is historically coherent and dramatically alive, '
           'and a chronicle that endorses her without argument has flattened the folio&rsquo;s '
           'best dispute. Let the young witches argue back &mdash; the books give them the lines '
           '&mdash; and let the fires stay lit in memory without deciding, for the players, what '
           'the memory licenses.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the knife and the cradle, and on '
                'remembered fire</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Verbena hold</span> that Life is the oldest magick and the '
           'only text: creation is a cycle of birth, death, and return, and the witch&rsquo;s art '
           'is to stand in the cycle and work it, not above it.<sup>a</sup> Their practice is the '
           'Old Faith &mdash; witchcraft in its full ancient sense: blood and herb, moon and '
           'season, the shape changed and the weather called; their instruments are the grown and '
           'the handmade &mdash; the knife, the cauldron, the garden, the carved rune, and first '
           'of all the practitioner&rsquo;s own blood.<sup>b</sup> Their seat among the Nine is '
           '<span class="term">Life</span>. Their internal law is the coven and the price: covens '
           'gather by threes and multiples, led by priestess and priest of any body; the eight '
           'festivals are kept; initiation is a death and rebirth with the elements as witnesses; '
           'and every working of the old rites is paid for &mdash; the witch&rsquo;s own blood '
           'first, and greater prices by consent, freely and formally given.<sup>c</sup> No grove '
           'is without its World Tree, and no World Tree is unstained.<sup>d</sup> The festivals '
           'are not observances but appointments: the year is the coven&rsquo;s calendar of '
           'obligations, and a witch who misses Samhain owes the dead an explanation.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Old Faith calls '
           'itself the eldest lineage at the table, received from the first workers of the green '
           'world and handed down mother to daughter, grove to grove, through the drowning of '
           'temples and the burning of wise women. The fires of those centuries are the '
           'Tradition&rsquo;s founding grief &mdash; kept, not healed &mdash; and its founder at '
           'the Convocation was a survivor of them: the witch of folio 2a&rsquo;s aggada, who '
           'hunted the hunter who burned her coven and ended him, and buried her dead, and then '
           'built. She came to Mistridge with the ashes still in her hair, and the Council&rsquo;s '
           'founding owes as much to her rage as to any master&rsquo;s vision, which the polite '
           'histories reorder. <span class="kw">OUR TEACHERS TOLD:</span> a seeker asked an elder '
           'why the gentlest healers keep the sharpest knives. The elder set her to a '
           'season&rsquo;s midwifery and a season&rsquo;s slaughter and asked, after, which season '
           'had needed the better edge. The seeker could not say. <span class="aside">Neither can '
           'the year,</span> said the elder, and the disputants opposite have been sharpening the '
           'answer since.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; eighth of the Avot; the garden and its '
             'factions are overleaf.',
 'folio': '162A',
 'glossL': '<p><span class="mark">a</span> On the Verbena entire &mdash; the witch-folk, the Old '
           'Ways, blood and garden &mdash; see M20, the Traditions chapter, folio 162, whence this '
           'page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the Wyck, the Great Rite, and the Aeduna '
           '&mdash; the first true Awakened, as the Tradition tells it &mdash; see the Lore of the '
           'Traditions chapter on the Verbena.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On covens, the eight festivals, '
           'and initiation as death and rebirth, see the same chapter and the Revised Tradition '
           'book.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Nightshade of Harrogate, '
           'convener at Mistridge, see the histories cited at folio 2a; this folio&rsquo;s aggada '
           'leans on that one and adds the ashes.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 516; the healing it governs at folio 406. The Tradition&rsquo;s claim to '
           'eldest lineage is disputed by the Dreamspeakers of folio 154a without heat &mdash; the '
           'People predate the claim and decline the contest, which stings more.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The founding rage of folio '
           '2a is this Tradition&rsquo;s title deed: Nightshade convened before Valoran sang and '
           'before La Salle hosted, and the Masoret keeps her order of operations against the '
           'polite histories.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The consent law of the '
           'greater prices rhymes with the Code of folio 152a and the license of folio 156a: '
           'chapter V&rsquo;s Traditions each built statute exactly where their gift can devour '
           '&mdash; the chapter&rsquo;s quiet thesis, stated here for the third time.</p>',
 'h1': 'The Verbena',
 'hagahah': 'The gentlest healers keep the sharpest knives, and the inventory is not a paradox but '
            'a job description: nothing dull is merciful, in surgery or in sacrifice. The Verbena '
            'have known this since before the word surgery; they are still waiting for the rest of '
            'the Council to stop being impressed by it.',
 'inner': '<p><span class="lemma">In the cycle, not above it.</span> The paradigm&rsquo;s plain '
          'sense: Verbena magick is participation in a process the witch does not exempt herself '
          'from. She heals as part of the turning, kills as part of the turning, and ages, births, '
          'and dies inside the same wheel she works &mdash; the Tradition&rsquo;s contempt is '
          'reserved for mages who treat the world as a workbench they are not standing on. Hence '
          'the kinship with the Chakravanti two folios back, and the old alliance with the People '
          'of folio 154.</p>\n'
          '        <p><span class="lemma">Witchcraft in its full ancient sense.</span> The '
          'practice&rsquo;s plain sense: doing much with little, and paying for it. The Verbena '
          'toolkit is deliberately archaic &mdash; iron, wood, herb, blood &mdash; not from '
          'nostalgia but from doctrine: tools close to the cycle carry it, and a working grown is '
          'stronger than a working assembled. At the table this is the anti-Etherite tempo &mdash; '
          'no laboratory, no journal, just the garden, the season, and the price.</p>\n'
          '        <p><span class="lemma">The witch&rsquo;s own blood first.</span> The price '
          'law&rsquo;s plain sense, and the Tradition&rsquo;s core ethic hiding in a preposition: '
          '<span class="aside">first</span>. The old rites cost, and the witch pays before anyone '
          'else does &mdash; her blood on the rune, her years into the great working. Sacrifice of '
          'another that skipped the witch&rsquo;s own turn is not the Old Faith but its '
          'counterfeit, and the covens police the difference with the knife they are famous '
          'for.</p>\n'
          '        <p><span class="lemma">Greater prices by consent.</span> The hard clause, '
          'stated plainly because the books state it plainly: the old rites include sacrifice, of '
          'beasts and &mdash; in the oldest strata &mdash; of persons, and the law&rsquo;s gate is '
          'consent, formal, witnessed, and freely given. What consent can mean at that altitude is '
          'the disputants&rsquo; first case opposite, and the tractate does not pretend the clause '
          'is comfortable; it rules only that without the clause the Tradition is '
          'indistinguishable from what folio 224 catalogues, and the Verbena wrote the clause '
          'for exactly that reason.</p>\n'
          '        <p><span class="lemma">Priestess and priest of any body.</span> The modern '
          'clause, plainly: the old God-and-Goddess polarity is energies, not anatomy, and the '
          'books are explicit that the offices go to whoever carries the energy. The '
          'Tradition&rsquo;s own essentialists dispute it overleaf, and lose ground '
          'seasonally.</p>\n'
          '        <p><span class="lemma">The eight festivals are kept.</span> The '
          'calendar&rsquo;s plain sense: the wheel of the year is the Tradition&rsquo;s '
          'constitution in time &mdash; debts fall due at the cross-quarters, initiations wait for '
          'the turning, and the great workings are sworn at one festival and delivered at another, '
          'the year itself serving as witness and enforcement. A coven&rsquo;s power can be read '
          'in its calendar&rsquo;s fullness the way a chantry&rsquo;s is read in its library, and '
          'the Storyteller who keeps the real year&rsquo;s dates has the campaign&rsquo;s '
          'deadlines drawn already.</p>\n'
          '        <p><span class="lemma">No World Tree is unstained.</span> The grove&rsquo;s '
          'plain sense: the Tree is altar, archive, and ledger at once &mdash; every working of '
          'consequence feeds it a price, and the stains are the coven&rsquo;s history written in '
          'the only ink the Old Faith fully trusts. Elders read a strange grove&rsquo;s Tree the '
          'way Hermetics read minutes; and a Tree suspiciously clean is read too, as either a '
          'young coven or a lying one.</p>',
 'inner_head': 'On the Rite<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; cycle, price, and consent</span>',
 'name': 'The Verbena',
 'outer': '<p><span class="lemma">By consent, freely and formally given.</span> The blood-rite '
          'dispute, faced. <span class="voice">Some say</span> the consent gate holds: the Old '
          'Faith&rsquo;s sacrifices are covenant, not predation &mdash; the willing offering, the '
          'price named beforehand, the witness required &mdash; and a Tradition that pays with its '
          'own blood first has earned the right to accept another&rsquo;s freely offered. The '
          'hospice patient who wills her death to the grove&rsquo;s working has more agency in it, '
          'they observe, than in anything her hospital planned for her. <span class="voice">Others '
          'say</span> consent thins at the altitudes where the old rites fly: between a coven that '
          'raised you and an offering you were raised toward, between the desperate and the grove '
          'that can name its price &mdash; the gate is real and the ground around it is worn '
          'smooth by exceptions. The critics&rsquo; sharpest case is the bloodlines: a Tradition '
          'that prizes descent has members whose consent was, in some sense, bred. The '
          'defenders&rsquo; sharpest answer is the record: name the century in which the '
          'counterfeit &mdash; the unconsenting altar &mdash; was not hunted by the covens '
          'themselves, harder than any outsider hunted it. Both cases hold; the gate stands; the '
          'watch on it, as at folio 156, is the Tradition&rsquo;s own and permanent.</p>\n'
          '        <p><span class="lemma">Kept, not healed.</span> The memory dispute. <span '
          'class="voice">Some say</span> the Burning Times are the Tradition&rsquo;s charter: the '
          'fires were real, the hunters were organized, the heirs of the hunters run the world '
          '&mdash; chapter VI, by their reading &mdash; and a witch who relaxes has forgotten what '
          'relaxing cost the last ten generations. Militancy is just memory with a spine. <span '
          'class="voice">Others say</span> the grief has been curated into a license: the romantic '
          'Burning-Times telling flattens history&rsquo;s actual tangle &mdash; the burned were '
          'mostly Sleepers, the hunters mostly neighbors, the Order&rsquo;s hand real but lately '
          'inflated &mdash; and a Tradition that reads every modern enemy by firelight will strike '
          'first at shadows and call it inheritance. The books hold both: the fires burned, and '
          'the telling grew. A grief kept is not obliged to stay accurate, and the Verbena&rsquo;s '
          'has not; whether accuracy is what founding griefs are <span class="aside">for</span> is '
          'the harder question, and folio 2b&rsquo;s aggada &mdash; also a grief, also grown '
          '&mdash; sits in the gallery for this argument taking notes.</p>\n'
          '        <p><span class="lemma">Neither can the year.</span> The maaseh pressed, '
          'briefly, because it will not bear length. <span class="voice">Some say</span> the elder '
          'taught the unity of the offices: culling and midwifery are one competence, and the '
          'year&rsquo;s indifference is the deepest thing the Old Faith knows. <span '
          'class="voice">Others say</span> the year&rsquo;s indifference is exactly what a moral '
          'tradition exists to answer, not to imitate &mdash; and an ethic that defers to the '
          'seasons has abdicated to a calendar. The Verbena reply that the calendar was here first '
          'and will be here last, which is not an argument but is, as the whole Tradition is, a '
          'position with roots. The year, as ever, declines to comment, which the Verbena have '
          'always taken for agreement. The seasons, it observes, have kept every appointment since '
          'the first; no other party to any covenant in this tractate can say the same.</p>',
 'outer_head': 'The Grove<span class="comm-sub">the outer commentary &middot; three difficulties: '
               'the altar, the fires, and the year</span>',
 'rubric': 'the Old Faith, its prices, and its fires',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the Verbena &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 162a — The Verbena: the Old Faith, its prices, and its fires',
 'type': 'daf'}
