# Folio 162b - The Garden. Verso of the Verbena folio: bloodline and
# initiation, the three camps, and the green revolution, per the
# wod-llm-wiki Verbena page (LotT ch.8).
FOLIO = {'bottom': '<p><span class="lemma">On coven as troupe.</span> The coven is the chapter&rsquo;s '
           'best-fitted structure for an all-one-Tradition troupe: small by statute, bound by '
           'rite, gathered on a calendar the real world also keeps. Run the festivals as sessions '
           '&mdash; eight nights a year when the whole chronicle convenes, debts come due, and the '
           'season&rsquo;s workings are sworn &mdash; and the campaign acquires a liturgical '
           'rhythm no episodic structure matches. The quiet weeks between festivals are where the '
           'consequences grow; harvest them on schedule.</p>\n'
           '        <p><span class="lemma">On lineage at the table.</span> A bloodline character '
           'carries the folio&rsquo;s dispute in her body: the name opens doors her merit has not '
           'earned yet, and every elder who beams at her pedigree is quietly insulting her '
           'initiated covenmate. Pair them &mdash; the hereditary witch and the chosen one &mdash; '
           'and the Tradition&rsquo;s argument plays itself without a single NPC lecture. The '
           'books&rsquo; own line holds: the ancestors are to be lived up to, not leaned on.</p>\n'
           '        <p><span class="lemma">On the plant cyborgs.</span> The techno-witches are the '
           'Tradition&rsquo;s best bridge content: a Verbena who greenhouses on hydroponics and '
           'reads moon phases from an app scandalizes exactly the right elders and can talk shop '
           'with the Etherites of folio 160 and the technoshamans of folio 154b. Use her to stage '
           'the archaism dispute as comedy before it arrives as schism; the Tradition has survived '
           'worse than firmware, and the chronicle should know it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on festivals, pedigree, and '
                'firmware</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The garden is entered two ways:</span> by blood and by rite. The '
           '<span class="term">bloodlines</span> carry the Old Faith in descent, mother to '
           'daughter through the drowned centuries, and their lineages are honored and policed; '
           'the <span class="term">initiated</span> enter by the death-and-rebirth the recto '
           'rules, and stand equal in law from the rebirth on &mdash; the grove knows no '
           'half-members.<sup>a</sup> Three camps tend the garden: the bloodline keepers, who '
           'garden the lineages themselves; the traditionalists of rite, who hold the old ways '
           'open to any who survive them; and the urban witches, who work the Old Faith in the new '
           'world&rsquo;s soil &mdash; and a green current runs through the young of all three, '
           'grafting the craft onto wire and glass.<sup>b</sup> The offices of God and Goddess are '
           'energies, not anatomies; the essentialists dispute this and the law has ruled against '
           'them.<sup>c</sup> And the garden&rsquo;s oldest claim is kept with its oldest '
           'humility: the Wyck were first, and no one living has met them.<sup>d</sup> Fosterage '
           'binds the beds together: children of the blood are lent between covens, that no '
           'lineage close upon itself; and the lineage books are open to any member&rsquo;s '
           'reading, for a pedigree hidden is a pedigree suspected. The camps share the festivals, '
           'the books, and the Tree; the arguments are what grow between the beds, tended like '
           'everything else.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> <span class="kw">IT '
           'HAPPENED THAT</span> a bloodline elder refused a candidate at the grove&rsquo;s edge, '
           'saying the girl carried no drop of the old blood, and the coven&rsquo;s priestess '
           'overruled her at the fire, saying the elements would decide, as they decide for every '
           'initiate. The girl went down into the rite&rsquo;s death and came back with the green '
           'sight, and the elder, who was honest, recorded the outcome in the lineage book she '
           'kept &mdash; in the margin, in her own blood, where her granddaughters would have to '
           'read it. The margin note became a precedent, and the precedent a proverb: <span '
           'class="aside">the Tree grafts.</span> The disputants around this text quarrel over '
           'what the proverb licenses, and the green current quotes it at every elder who frowns '
           'at a circuit board.</p>',
 'chapter': 'Chapter the Fifth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Verbena&rsquo;s folio: the recto '
             'keeps the rites, this side keeps the garden.',
 'folio': '162B',
 'glossL': '<p><span class="mark">a</span> On the Wyckan bloodlines and the Gardeners of the Tree '
           'who police them, see the Lore of the Traditions chapter on the Verbena.</p>\n'
           '        <p><span class="mark">b</span> On the three camps &mdash; bloodline, '
           'traditionalist, urban &mdash; and the Lifeweavers, Moon-Seekers, and Twisters of Fate '
           'among them, see the same chapter.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the green revolution &mdash; '
           'techno-Wicca, the so-called plant cyborgs &mdash; and the essentialism ruling, see the '
           'same chapter&rsquo;s reckonings.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Wyck and the Great Rite, '
           'see the chapter&rsquo;s opening; the humility clause is this folio&rsquo;s reading of '
           'the Tradition&rsquo;s own phrasing.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The grafting proverb answers the Wheel of folio '
           '148b and the door of folio 154b in the chapter&rsquo;s running conversation about who '
           'may enter a lineage; three Traditions, three gates, one question.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The green current&rsquo;s '
           'wires run toward the technoshamans of folio 154b and the Web of folio 164; '
           'the Old Faith&rsquo;s youngest branch is closer to those neighbors than to its own '
           'grandmothers, which the grandmothers have noticed.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Descent as qualification is '
           'tried nowhere harder than in Tractate Masekha&rsquo;s clans, where blood is the whole '
           'constitution; the Masoret notes that the Verbena, who could have built that world, '
           'built the margin note instead.</p>',
 'h1': 'The Garden',
 'hagahah': 'The lineage books of the bloodlines are kept in blood, which is doctrine, and in '
            'excellent penmanship, which is pride. The margin notes are where the Tradition '
            'actually lives; the Verbena know this, and bind their books with wide margins on '
            'purpose.',
 'inner': '<p><span class="lemma">By blood and by rite.</span> The two doors&rsquo; plain sense: '
          'descent transmits aptitude and obligation &mdash; the old blood Awakens green more '
          'often than chance allows, and carries the family&rsquo;s debts with it &mdash; while '
          'the rite transmits membership entire. Note the law&rsquo;s care: blood makes a '
          'candidate likelier, never a member; the rite makes a member, never a pedigree. The two '
          'doors open into the same grove and the drafts between them are the verso&rsquo;s '
          'weather.</p>\n'
          '        <p><span class="lemma">Honored and policed.</span> The bloodline keepers&rsquo; '
          'plain sense: a lineage is a garden bed, and the Gardeners weed &mdash; tracking '
          'descent, arranging fosterage, and, at their worst, arranging more than fosterage. The '
          'recto&rsquo;s consent law reaches here too: matchmaking is custom, compulsion is '
          'counterfeit, and the line between them is patrolled by the same covens that patrol the '
          'altar.</p>\n'
          '        <p><span class="lemma">Equal in law from the rebirth on.</span> The equality '
          'clause&rsquo;s plain sense, and its bite: no office, festival role, or teaching is '
          'reserved to blood. The initiated priestess outranks the pedigreed novice, and the law '
          'has held every time it has been tested &mdash; the Gemara&rsquo;s margin note is the '
          'case the covens cite. What the law cannot reach is the beam in the elder&rsquo;s eye, '
          'which is why the dispute opposite still has fuel.</p>\n'
          '        <p><span class="lemma">In the new world&rsquo;s soil.</span> The urban '
          'witches&rsquo; plain sense: the Old Faith&rsquo;s claim was never about geography '
          '&mdash; the cycle turns in the city too, in rooftop gardens and hospital wards and the '
          'rat-and-hawk food chain of the financial district. The Moon-Seekers and the '
          'fate-twisters work exactly the recto&rsquo;s craft with exactly its prices; only the '
          'flora changed. Their elders&rsquo; suspicion of them is the suspicion every diaspora '
          'meets from the old country, and ages the same way.</p>\n'
          '        <p><span class="lemma">Energies, not anatomies.</span> The ruling&rsquo;s plain '
          'sense at the table: polarity is real in the rites and free in its carriers &mdash; the '
          'God-energy and Goddess-energy are roles taken, not assignments enforced, and the books '
          'say so in as many words. Play the losing essentialists as what they are: a faction with '
          'seniority and a case the law has already decided, which is the most dangerous kind of '
          'faction and the most familiar.</p>\n'
          '        <p><span class="lemma">Lent between covens.</span> Fosterage&rsquo;s plain '
          'sense: the bloodlines&rsquo; own antidote to themselves. A child raised only among her '
          'lineage learns its pride entire and its faults invisibly; the fostered child returns '
          'bilingual, and the web of fosterage makes cousins of rival groves &mdash; which is its '
          'quiet second office, since covens do not lightly feud with houses raising their '
          'daughters. The custom is older than the Tradition and the Tradition knows it, which is '
          'why fosterage disputes go to the eldest available priestess and not to anything '
          'resembling a court.</p>\n'
          '        <p><span class="lemma">Open to any member&rsquo;s reading.</span> The '
          'transparency clause&rsquo;s plain sense: the lineage books confer standing, so sealed '
          'books would mint aristocrats &mdash; and the Old Faith, which has buried actual '
          'aristocracies, wrote the shelf open instead. Any initiate may read any line, margins '
          'included, and the embarrassments preserved there &mdash; the grafts denied and proven, '
          'the matches arranged and regretted &mdash; are the law&rsquo;s real teeth: a family '
          'cannot lean on a book that documents its leanings.</p>',
 'inner_head': 'On the Beds<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; doors, camps, and offices</span>',
 'name': 'The Garden',
 'outer': '<p><span class="lemma">The Tree grafts.</span> But what does the proverb license? <span '
          'class="voice">The green current says</span> everything: if the Tree grafts flesh to '
          'lineage, it grafts silicon to craft &mdash; the hydroponic grove, the coded rune, the '
          'familiar with firmware are the margin note&rsquo;s heirs, and an Old Faith that '
          'survived the iron plow can survive the printed circuit. <span class="voice">The keepers '
          'answer</span> that the graft takes because the stock is living: the girl at the fire '
          'had blood and breath and could die the rite&rsquo;s death, and a working grown in glass '
          'and wire has no death in it to be reborn from &mdash; the cycle is the craft, and a '
          'craft without the cycle is Etherism with leaves. An objection to the keepers: the same '
          'was said of the city witches, and before them of the initiated, and before them, '
          'presumably, of the plow. <span class="voice">Answer:</span> and it was wrong each time '
          'it was wrong and right the times the graft died &mdash; the lineage books record both, '
          'in the margins, where this Tradition keeps its honesty. The current and the keepers '
          'agree on the test &mdash; does the cycle turn in it? &mdash; and disagree about every '
          'particular application, which the tractate recognizes as a functioning legal '
          'system.</p>\n'
          '        <p><span class="lemma">Honored and policed.</span> The lineage dispute, pressed '
          'to its point. <span class="voice">Some say</span> the bloodlines are the '
          'Tradition&rsquo;s deep root: continuity of flesh through the burning centuries is '
          'itself a great working, paid in every generation, and the families&rsquo; pride is a '
          'survivor&rsquo;s pride, earned at rates the initiated are spared. <span '
          'class="voice">Others say</span> a Tradition whose law says rite and whose culture says '
          'pedigree has two constitutions, and the quiet one governs: watch whose daughters lead '
          'the great festivals, whose sons are fostered to the famous groves, and the margin note '
          'starts to read less like precedent and more like exception, framed. The books side with '
          'neither and arm both &mdash; the ancestors to be lived up to, not leaned on &mdash; and '
          'the chapter&rsquo;s pattern completes: every Tradition&rsquo;s strength curdles in its '
          'own direction, and the Old Faith&rsquo;s strength was always the family.</p>\n'
          '        <p><span class="lemma">No one living has met them.</span> The Wyck dispute, '
          'briefly, at the folio&rsquo;s edge where it belongs. <span class="voice">Some '
          'say</span> the first workers are lineage&rsquo;s anchor: the bloodlines descend from '
          'the Aeduna and the Aeduna from the Wyck, and the chain of blood is the '
          'Tradition&rsquo;s apostolic succession. <span class="voice">Others say</span> the '
          'humility clause governs: a descent no one can audit from ancestors no one has met is '
          'exactly as verifiable as every other Tradition&rsquo;s founding myth, and the Old '
          'Faith&rsquo;s actual charter is the working garden, not the family tree&rsquo;s '
          'unreachable root. <span class="kw">TEYKU</span> &mdash; the root stays buried, as roots '
          'should. The books themselves, wide margins waiting, decline to close the question; that '
          'is what the margins are for.</p>',
 'outer_head': 'The Gardeners<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the graft, the pedigree, and the root</span>',
 'rubric': 'blood, rite, and the grafted Tree',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, continued '
             '&middot; of the garden &middot; lineage, initiation, and the green current',
 'title': 'Tractate Aliyah · Folio 162b — The Garden: blood, rite, and the grafted Tree',
 'type': 'daf'}
