# Folio 164a - The Virtual Adepts. Avot mold; facts per the wod-llm-wiki
# Virtual Adepts page (M20 pp.164-165; Lore of the Traditions ch.9).
FOLIO = {'bottom': '<p><span class="lemma">On playing an Adept.</span> The caricature is the hoodie and '
           'the jargon; the correction is that the Tradition&rsquo;s core is not computers but '
           'proof &mdash; the conviction that truth is demonstrable, that authority is a bug, and '
           'that anything demonstrably true beats anything merely official. Build the character on '
           'what she has proven and what she has torn down: the Adept without a defiance in her '
           'history has skipped the initiation, which the books describe, accurately, as '
           'institutionalized trolling. And keep the youth real &mdash; this is the youngest '
           'Tradition, defectors&rsquo; children, and it argues like a group chat, which at the '
           'Council table it more or less is.</p>\n'
           '        <p><span class="lemma">On the Web at the table.</span> The Digital Web '
           'deserves the same discipline as the Umbra: a place with native laws, not a metaphor '
           'with graphics. Establish early what a visit costs, what death there means, and who '
           'else is resident &mdash; the Union&rsquo;s wardens, the spirits of folio 154b&rsquo;s '
           'technoshamans, things older than the protocols that carry them. The verso holds the '
           'law; the table&rsquo;s job is to make the players feel that going in is travel, not '
           'interface.</p>\n'
           '        <p><span class="lemma">On the camera problem.</span> The Adepts live on folio '
           '533b&rsquo;s home turf: they are the Tradition of the lens, the feed, and the '
           'fabrication, and every witness-census ruling lands on their operations first. A '
           'chronicle with an Adept in the cabal should revisit the 533b session-zero declarations '
           'explicitly &mdash; whether the stream counts, whether the deepfake launders &mdash; '
           'because her entire tactical doctrine turns on the answer, and she will ask.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on proof, the Web as place, and the '
                'census revisited</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Virtual Adepts hold</span> that everything is information: '
           'crack the code behind a thing and it may be rewritten from anywhere, no touch '
           'required.<sup>a</sup> Their practice is the reality-hack &mdash; elegant intervention '
           'at the point of maximum leverage; their instruments are the coder&rsquo;s: the '
           'machine, the network, the algorithm, the exploit. Their seat among the Nine is <span '
           'class="term">Correspondence</span>, which they read as <span class="term">Data</span>, '
           'and they claim its modern face as their own authorship.<sup>b</sup> Their internal law '
           'is three refusals: no rank but reputation &mdash; the proven achievement outvotes '
           'every title; no authority but proof &mdash; disagreements are settled by '
           'demonstration, as theorems are, not by seniority; and no lock on information &mdash; '
           'what is known is to be freed, and the Adept who hoards knowledge against her own has '
           'stolen from the commons.<sup>c</sup> Initiation is by ordeal of wit: the candidate is '
           'tested with missions of sabotage, theft, and mockery until she has demonstrated the '
           'only credential the Tradition honors, which is having done it.<sup>d</sup> And the '
           'reputation law has teeth at both ends: the published claim binds its maker, and '
           'retraction is public too &mdash; an Adept&rsquo;s word is her honor precisely because '
           'the log is append-only.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The youngest chair at '
           'the table was earned in the newest way: by defection. They were the Union&rsquo;s own '
           'difference-engineers, punished for asking what the Timetable forbade; and when their '
           'greatest &mdash; the master who opened the Web itself &mdash; was broken by the very '
           'order he served, his people carried his name out of the Union like a banner and '
           'petitioned the enemy&rsquo;s Council for a seat. The Council, to its own surprise, '
           'said yes &mdash; folio 3a keeps the ruling: the youngest chair, seated on proof of '
           'works, the precedent every craft of folio 3b watches with interest. <span '
           'class="kw">OUR TEACHERS TOLD:</span> an elder of another Tradition asked an Adept what '
           'her people worship, seeing they mock all altars. <span class="aside">Elegance,</span> '
           'she said. Asked to define it, she sent him, without comment, a proof four lines long '
           'of a theorem his House had proven in forty pages. The House&rsquo;s reply is not '
           'preserved; the proof is; the disputants opposite argue about which fact matters '
           'more.</p>',
 'chapter': 'Chapter the Fifth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; last of the nine Avot; the Web itself is '
             'overleaf, and chapter V closes with it.',
 'folio': '164A',
 'glossL': '<p><span class="mark">a</span> On the Virtual Adepts entire, see M20, the Traditions '
           'chapter, folio 164, whence this page takes its number; on their claim to the Data '
           'sphere&rsquo;s authorship, the same entry.</p>\n'
           '        <p><span class="mark">b</span> On the defection &mdash; the Difference '
           'Engineers, the Archmaster broken in 1954, the seat taken in 1961 &mdash; see the Lore '
           'of the Traditions chapter and the Revised Tradition book.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On proofs, not edicts, as the '
           'Tradition&rsquo;s creed, see the Lore of the Traditions chapter on the Adepts.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On initiation by mission and '
           'mockery &mdash; the grand tradition of trolling, as the books have it &mdash; see the '
           'same sources.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat&rsquo;s Sphere is tried at folio 512, '
           'wanting, where the Data variant is the Union&rsquo;s girsa and the Adepts&rsquo; claim '
           'of authorship is an open exhibit; the youngest-chair ruling is folio 3a&rsquo;s ruling '
           'i.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The defection mirrors the '
           'secession of folio 160a: two children of the Union, one walked out over a theory, one '
           'driven out over a man; chapter VI will state the Union&rsquo;s side of both, and the '
           'broken Archmaster&rsquo;s file belongs to folio 188&rsquo;s watchers.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The camera problem of folio '
           '533b is this Tradition&rsquo;s home turf: the lens that launders and the feed that '
           'testifies are their working conditions, and every ruling of that folio&rsquo;s census '
           'is, for them, weather.</p>',
 'h1': 'The Virtual Adepts',
 'hagahah': 'They freed information. It has not called since. The Adepts tell this joke about '
            'themselves, which is the diagnostic mark of the Tradition: the others&rsquo; '
            'self-mockery is a defense; theirs is a changelog.',
 'inner': '<p><span class="lemma">Everything is information.</span> The paradigm&rsquo;s plain '
          'sense: the Adept&rsquo;s magick is source-level intervention. Where the Hermetic argues '
          'the case and the witch works the cycle, the Adept patches: find the variable, change '
          'the variable, and the world&rsquo;s renderer does the rest. Hence the marriage with '
          'Correspondence &mdash; distance is just an addressing scheme &mdash; and hence the '
          'Tradition&rsquo;s signature vice, which is mistaking the model for the territory a '
          'half-second before the territory objects.</p>\n'
          '        <p><span class="lemma">Which they read as Data.</span> The seat&rsquo;s plain '
          'sense: one Sphere, two liturgies, as folio 515a&rsquo;s Masoret said of Forces. The '
          'mystic reads Correspondence as the unity of all places; the Adept reads it as the '
          'network&rsquo;s adjacency; the ladder is identical and folio 512 will rule on nothing '
          'but vocabulary. Their claim to have <span class="aside">authored</span> the modern '
          'reading is historically serious &mdash; the Union adopted their Data sphere, not the '
          'reverse &mdash; and it makes the youngest Tradition, by its own accounting, the only '
          'one whose paradigm the enemy runs in production.</p>\n'
          '        <p><span class="lemma">No rank but reputation.</span> The first refusal&rsquo;s '
          'plain sense: the Tradition is a merit anarchy, and its social physics actually work '
          '&mdash; the achievement is verifiable, the verification is public, and the elder who '
          'coasts is unfollowed in every sense. The cost is documented with equal honesty: '
          'reputation systems reward the legible spectacular over the quiet necessary, and the '
          'Adepts&rsquo; maintenance burnout is the Tradition&rsquo;s jhor, filed under a '
          'cheerfuller name.</p>\n'
          '        <p><span class="lemma">No lock on information.</span> The third refusal&rsquo;s '
          'plain sense, with its own lock read carefully: the commons clause governs knowledge '
          'among the Awakened commons &mdash; it has never meant the enemy&rsquo;s passwords, the '
          'Sleepers&rsquo; medical records, or the cabal&rsquo;s operational security, whatever '
          'the youngest members argue at two in the morning. What it does mean the verso tests '
          'against the C-Sector problem, where the Tradition&rsquo;s practice and its scripture '
          'are currently at war.</p>\n'
          '        <p><span class="lemma">Having done it.</span> Initiation&rsquo;s plain sense: '
          'the ordeal proves capability and temperament at once &mdash; the missions are chosen so '
          'that the obedient fail them and the merely destructive fail them differently. What '
          'survives is a mind that defies well, which is the Tradition&rsquo;s entire personnel '
          'policy and, its elders privately concede, its succession problem: a body of excellent '
          'defiers has no mechanism for being agreed with.</p>\n'
          '        <p><span class="lemma">The log is append-only.</span> The reputation '
          'ledger&rsquo;s plain sense: an Adept&rsquo;s standing is the public history of her '
          'claims, exploits, and retractions, and nothing is ever deleted &mdash; the '
          'Tradition&rsquo;s answer to the Record of folio 148a and the stapled archive of 160b, '
          'built this time in version control. Rehabilitation is therefore possible and cheap '
          'grace is not: the Adept who was wrong loudly and corrected loudly outranks the one who '
          'was quietly neither, and the worst reputation in the Tradition is not <span '
          'class="aside">wrong</span> but <span class="aside">edited</span>.</p>\n'
          '        <p><span class="lemma">The exploit as instrument.</span> The toolkit&rsquo;s '
          'plain sense: an Adept&rsquo;s focus is leverage &mdash; the small intervention with the '
          'large consequence &mdash; and her instruments are wherever leverage lives: code, yes, '
          'but also the bureaucracy&rsquo;s forms, the market&rsquo;s incentives, the '
          'crowd&rsquo;s attention. The elegant hack of a zoning board is as Adept as the elegant '
          'hack of a server, and the young member who thinks the Tradition is about computers is '
          'gently assigned to read the founding generation&rsquo;s work, which was done on '
          'paper.</p>',
 'inner_head': 'On the Code<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the three refusals, clause by clause</span>',
 'name': 'The Virtual Adepts',
 'outer': '<p><span class="lemma">What is known is to be freed.</span> Liberation or surveillance '
          '&mdash; the Tradition&rsquo;s central dispute, and it cuts through every member rather '
          'than between factions. <span class="voice">Some say</span> the Adepts are '
          'freedom&rsquo;s engineers: every censored fact they mirror, every walled garden they '
          'breach, every Sleeper they hand an encrypted channel is the Ascension War fought at '
          'scale, and the Union&rsquo;s managed narrative &mdash; folio 188&rsquo;s, when it is '
          'written &mdash; dies by a billion leaks. <span class="voice">Others say</span> the same '
          'skills are the surveillance they claim to fight: the mage who can read anything reads '
          'everything, the liberator&rsquo;s toolkit is the voyeur&rsquo;s with better branding, '
          'and the Tradition&rsquo;s history of Constraining private sectors of its own free Web '
          'is the exhibit that will not close. The books&rsquo; own verdict is kept in the '
          'members&rsquo; mouths &mdash; meet the new boss, same as the old boss &mdash; and the '
          'Tradition&rsquo;s honesty about the exhibit is either its conscience working or its '
          'confession filed early, depending on the reader, who is, the Adepts note, also being '
          'logged by someone as she reads.</p>\n'
          '        <p><span class="lemma">A seat, on proof of works.</span> The membership '
          'dispute: is the Tradition a Tradition? <span class="voice">Some say</span> the Council '
          'seated a method, not a mystery: the Adepts have no dead to keep, no rites but in-jokes, '
          'no lineage but a martyr younger than some sitting Masters &mdash; and a Tradition '
          'assembled from a grievance and a skill set will dissolve into the first better offer, '
          'as its own transhumanists half-plan aloud. <span class="voice">Others say</span> watch '
          'what they keep rather than what they lack: the name of the broken Archmaster carried '
          'like a banner, the initiation ordeal transmitted generation to generation, the commons '
          'defended at real cost &mdash; grief, transmission, and law are exactly what this '
          'chapter has called a Tradition eight folios running, and the Adepts assembled the kit '
          'from scratch in seventy years, which is not a deficiency but a speedrun. The elder '
          'Traditions&rsquo; discomfort, on this reading, is the discomfort of watching '
          'one&rsquo;s own architecture rebuilt from a tutorial, correctly.</p>\n'
          '        <p><span class="lemma">The proof is preserved.</span> The maaseh&rsquo;s '
          'dispute, and the chapter&rsquo;s closing one. <span class="voice">Some say</span> '
          'elegance is a real god and the Adepts its honest priests: the four-line proof is what '
          'every Tradition&rsquo;s paradigm claims to be &mdash; the world made suddenly simpler '
          'and truer &mdash; delivered without incense. <span class="voice">Others say</span> '
          'elegance is the aestheticization of being right, and a Tradition that worships it will '
          'choose the beautiful exploit over the boring repair every time the two compete &mdash; '
          'the freed information that never calls, the Web Constrained by its liberators, the '
          'maintenance nobody reputable wants. The tractate observes that chapter V has now '
          'catalogued nine Traditions and nine ways a virtue curdles, and closes the '
          'chapter&rsquo;s pattern-book here: the reader who has kept the list knows more about '
          'the Council than the Council&rsquo;s own histories admit, and the Adepts, of all of '
          'them, would be the first to publish the list. <span class="kw">TEYKU</span> &mdash; let '
          'it stand, in four lines or forty pages.</p>',
 'outer_head': 'The Fork<span class="comm-sub">the outer commentary &middot; three difficulties: '
               'the commons, the credentials, and elegance</span>',
 'rubric': 'the reality-hackers, and their three refusals',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, concluded '
             '&middot; of the Virtual Adepts &middot; the Tradition as law, its lineage as aggada',
 'title': 'Tractate Aliyah · Folio 164a — The Virtual Adepts: the reality-hackers and their three '
          'refusals',
 'type': 'daf'}
