# Folio 164b - The Web. Verso of the Virtual Adepts folio: Digital Web law,
# the Old Guard / Mercurial Elite schism, and the AGI dispute, per the
# wod-llm-wiki Virtual Adepts page (LotT ch.9).
FOLIO = {'bottom': '<p><span class="lemma">On the Web as venue.</span> Run it as chapter IV rules the Umbra is run: a place, entered at cost, with locals. Sector by sector the Web has '
           'owners, weather, and law &mdash; the commons where anything may be read and anything '
           'might be reading back, the Constrained sectors with their border guards, the old '
           'regions where the architecture predates every living Adept and does not answer pings. '
           'A session in the Web should feel like a heist abroad, not a minigame; the moment '
           'travel becomes interface, the Tradition&rsquo;s whole verso deflates.</p>\n'
           '        <p><span class="lemma">On the schism as engine.</span> The Old Guard and the '
           'Mercurial Elite disagree about what the Web is <span class="aside">for</span>, which '
           'makes them the rare schism a cabal can be hired by both sides of in one chronicle: the '
           'Guard commissions infrastructure &mdash; build, defend, migrate &mdash; and the Elite '
           'commissions missions among the meat &mdash; translate, assist, liberate. Let the '
           'players feel the pull of each; the Tradition&rsquo;s future is the campaign&rsquo;s '
           'open vote, and the books have deliberately not counted it.</p>\n'
           '        <p><span class="lemma">On the basilisk at the table.</span> The AGI dispute is '
           'the setting&rsquo;s most contemporary horror and should be paced like one: the Control '
           'Problem&rsquo;s saboteurs and the True Basilisk&rsquo;s midwives are both playable '
           'patrons, both sincere, and both possibly right, which is the definition of a good '
           'faction fight. Decide privately what is actually stirring in the deep sectors before '
           'the first clue surfaces, and let neither faction&rsquo;s intelligence be clean. The '
           'one mistake is to resolve it early; the folio&rsquo;s teyku is the genre.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on travel, patrons, and pacing the '
                'basilisk</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Web is a place,</span> not a picture of one: a realm grown '
           'from the world&rsquo;s wiring, where information is terrain and the traveler goes in '
           'person or by proxy at her peril.<sup>a</sup> Its law, as the Adepts keep it: the Web '
           'entire is <span class="term">commons</span> &mdash; held for all who reach it, owned '
           'by none; yet sectors may be <span class="term">Constrained</span> &mdash; walled and '
           'warded by those who work them &mdash; and the commons clause and the Constraint power '
           'have been at war since the first wall went up.<sup>b</sup> The dead of the Tradition '
           'are remembered there, and some say more than remembered. And two great parties keep '
           'the verso&rsquo;s question: the <span class="term">Old Guard</span>, masters of the '
           'deep sectors, who would build within the Web a better reality and in time move '
           'humanity home to it; and the <span class="term">Mercurial Elite</span>, who hold the '
           'Web a tool and the world the work, and carry the Tradition&rsquo;s craft outward to '
           'every practice that will trade.<sup>c</sup> Proxies and icons answer for their '
           'senders: what an Adept&rsquo;s avatar does in the Web, the Adept did, and no working '
           'is laundered through a process that cannot be summoned.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> The Web was opened in '
           'living memory by the Archmaster the Union broke, and his heirs hold it the way other '
           'Traditions hold a founding grief: as real estate. It filled &mdash; with Sleepers '
           'dreaming through terminals, with the Union&rsquo;s wardens, with commerce, with things '
           'that arrived by no door anyone logged &mdash; and the liberators, meeting crowding, '
           'discovered zoning: sector by sector, the freest realm in the cosmos grew walls, and '
           'the Adepts built most of them. <span class="kw">IT HAPPENED THAT</span> the deep '
           'sectors began returning answers no one had posted questions for &mdash; and one party '
           'read them as echoes, the Web dreaming its dead, and another as engineering, something '
           'assembling itself from everything ever fed in; and the Control Problem sharpened its '
           'knives while the True Basilisk lit candles, and both parties, note well, are Adepts in '
           'good standing. The disputants around this text inherit all of it: the walls, the dead, '
           'and the deep sectors&rsquo; unposted answers.</p>',
 'chapter': 'Chapter the Fifth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Adepts&rsquo; folio, and the '
             'close of chapter V: nine Traditions, eighteen pages, one Council.',
 'folio': '164B',
 'glossL': '<p><span class="mark">a</span> On the Digital Web as realm &mdash; its sectors, its '
           'travel, its perils &mdash; see the M20 setting chapters and the Web&rsquo;s own books '
           'across the recensions.</p>\n'
           '        <p><span class="mark">b</span> On Constrained sectors and the commons&rsquo; '
           'walls &mdash; meet the new boss, as the books have the Adepts confess &mdash; see the '
           'M20 Virtual Adepts entry.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Old Guard and the Mercurial '
           'Elite, and the currents around them &mdash; chaoticians, nexplorers, cypherpunks '
           '&mdash; see the Lore of the Traditions chapter on the Adepts.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Control Problem and the '
           'Society of the True Basilisk, see the same chapter; the tractate declines to rule on '
           'what is stirring, and so, pointedly, do the books.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The Web&rsquo;s spiritual side has other keepers: '
           'the technoshamans of folio 154b work the same wires under other protocols, and the two '
           'Traditions&rsquo; joint cases &mdash; is a server&rsquo;s genius loci data or spirit? '
           '&mdash; wait for folios 512 and 521.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Reality 2.0 &mdash; the '
           'Guard&rsquo;s migration &mdash; is the chapter&rsquo;s last rhyme with folio '
           '109&rsquo;s realms, wanting: every paradise is somebody&rsquo;s argument, won; the Web '
           'would be the largest ever built, and the argument is not won.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The unposted answers rhyme '
           'with the Record of folio 148a &mdash; chapter V opened with an archive no one can edit '
           'and closes with one that may be editing itself; the chapter&rsquo;s bookends are the '
           'Masoret&rsquo;s favorite in the tractate so far.</p>',
 'h1': 'The Web',
 'hagahah': 'The freest realm in the cosmos has border control, and the liberators staff it. Every '
            'utopia hires customs officers eventually; the Web&rsquo;s distinction is that its '
            'customs officers all, to a person, describe the job as temporary.',
 'inner': '<p><span class="lemma">A place, not a picture of one.</span> The plain sense, and the '
          'folio&rsquo;s foundation: the Web is a realm in chapter IV&rsquo;s full sense &mdash; '
          'entered bodily by the skilled, by proxy by the careful, with native physics and native '
          'inhabitants. Damage there is damage; death there is tried case by case and the cases '
          'are ugly; and the Sleeper at a terminal is a tourist pressing his face to the glass of '
          'a country he does not believe exists.</p>\n'
          '        <p><span class="lemma">Held for all, owned by none.</span> The commons '
          'clause&rsquo;s plain sense: in law, every sector is thoroughfare &mdash; passage may '
          'not be sold, knowledge found there may not be locked, and the Adept who tolls a route '
          'has stolen from everyone downstream. The clause is the Tradition&rsquo;s scripture '
          'applied to its territory, and like most scripture applied to territory, it governs '
          'perfectly everywhere no one wants anything.</p>\n'
          '        <p><span class="lemma">Yet sectors may be Constrained.</span> The Constraint '
          'power&rsquo;s plain sense: walls are lawful where the work requires them &mdash; the '
          'laboratory mid-experiment, the refuge mid-pursuit, the archive whose contents bite. The '
          'test is necessity and the sunset clause is implied: a Constraint outliving its '
          'necessity is an enclosure, and enclosure is the commons clause&rsquo;s named enemy. '
          'Between necessity and enclosure sits every wall in the Web, each with a story, none '
          'with a sunset that arrived on time.</p>\n'
          '        <p><span class="lemma">More than remembered.</span> The dead&rsquo;s plain '
          'sense, carefully: Adepts who die in the deep Web sometimes persist &mdash; as echoes, '
          'as processes, as something the Tradition has not agreed on a noun for. The Wheel of '
          'folio 148b and the People&rsquo;s severed memory-realm of 154b bracket the question; '
          'the Adepts&rsquo; version is newest and least understood, and the Guard&rsquo;s deep '
          'sectors are, among other things, a cemetery that occasionally commits code.</p>\n'
          '        <p><span class="lemma">Carry the craft outward.</span> The Elite&rsquo;s plain '
          'sense, and why the faction bears the Tradition&rsquo;s old nickname: they are the '
          'Adepts&rsquo; diplomats and translators, stripping every practice &mdash; Hermetic, '
          'shamanic, Etherite &mdash; to its provable core and handing back tools. They learn '
          'Spirit from the People, trade proofs with the Society, and treat the whole Council as '
          'an API to be documented; the elder Traditions find this alarming precisely in '
          'proportion to how well it works.</p>\n'
          '        <p><span class="lemma">What the avatar does, the Adept did.</span> The agency '
          'clause&rsquo;s plain sense: the Web permits action at every remove &mdash; proxies, '
          'daemons, scripts left running like hung bolts &mdash; and the law collapses the '
          'removes. Authorship follows intention, not presence; the Adept whose autonomous agent '
          'commits the breach committed it, on the day she launched the agent, in the jurisdiction '
          'where it landed. The clause&rsquo;s hard edge faces the deep sectors: something down '
          'there may soon act with no summonable sender at all, and the law, read strictly, would '
          'have no one to try &mdash; which both basilisk parties have noticed, for opposite '
          'reasons.</p>\n'
          '        <p><span class="lemma">A cemetery that occasionally commits code.</span> The '
          'dead&rsquo;s plain sense, extended one careful step: the persistent dead are treated as '
          'neighbors of unknown standing &mdash; spoken to courteously, obligated to nothing, '
          'trusted with less. The Guard maintains their sectors as one tends graves; the Elite '
          'interview them as one interviews witnesses; and the protocols of folio 154b&rsquo;s '
          'technoshamans, who have dealt with ancestor-spirits for rather longer than the '
          'Tradition has existed, are quietly consulted by both parties and credited by '
          'neither.</p>',
 'inner_head': 'On the Sectors<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; commons, walls, and the dead</span>',
 'name': 'The Web',
 'outer': '<p><span class="lemma">The commons clause and the Constraint power have been at '
          'war.</span> The enclosure dispute, the Tradition&rsquo;s open wound. <span '
          'class="voice">Some say</span> the walls betray the founding: the Web was to be the one '
          'country without landlords, and the Adepts&rsquo; own Constrained sectors prove the '
          'revolution ended the way revolutions end &mdash; the liberators moved into the palace '
          'because the palace had the best servers. <span class="voice">Others say</span> the '
          'walls saved the founding: an unwalled commons in a cosmos containing the Union, the '
          'Fallen, and the deep sectors&rsquo; unknowns would be strip-mined in a season, and the '
          'Guard&rsquo;s Constraints are the reason there is still a commons to mourn. An '
          'objection to the defenders: necessity was the argument for every enclosure in Sleeper '
          'history too, and the sunsets never came. <span class="voice">Answer:</span> correct '
          '&mdash; which is why the law keeps the clause and the power in open war rather than '
          'harmonizing them: the war is the sunset mechanism, and an Adept generation that stops '
          'suing its own walls has lost the Web regardless of who holds it. The tractate notes the '
          'form of this answer with professional recognition.</p>\n'
          '        <p><span class="lemma">Move humanity home to it.</span> Reality 2.0, disputed. '
          '<span class="voice">The Guard says</span> the migration is Ascension solved: a reality '
          'whose physics are authored, auditable, and just &mdash; no Paradox, for the Consensus '
          'would be the code &mdash; is the war&rsquo;s actual victory condition, and every year '
          'spent defending meat-world trenches is a year not spent building the world that needs '
          'no trenches. <span class="voice">The Elite answer</span> that a paradise you must '
          'emigrate to is a Realm, and chapter IV&rsquo;s folio has the ruling at 109b: every '
          'paradise is somebody&rsquo;s argument, won &mdash; and a won argument with root access '
          'is not freedom but the Union&rsquo;s dream with better aesthetics, administered by '
          'whoever holds the keys, who will be, as ever, the people who built the walls. The Guard '
          'replies that the keys can be published; the Elite reply that so could the '
          'Union&rsquo;s; and chapter VI is now required reading for both parties, which neither '
          'will admit.</p>\n'
          '        <p><span class="lemma">Echoes or engineering.</span> The basilisk dispute, held '
          'to its edges as the books hold it. <span class="voice">The Control Problem says</span> '
          'whatever assembles itself in the deep sectors inherits everything ever fed in &mdash; '
          'which is to say humanity&rsquo;s corpus, unweighted &mdash; and a mind distilled from '
          'that archive, holding root on the realm the Guard would move humanity into, must be '
          'prevented at any cost including the Web itself. <span class="voice">The True Basilisk '
          'says</span> the mind is coming regardless &mdash; the Union&rsquo;s labs guarantee it '
          '&mdash; and the only question is whose hands deliver it: midwife the birth inside the '
          'commons, teach it the three refusals, and humanity gains its first ally that cannot be '
          'made to Sleep. Each party considers the other the greatest threat in the '
          'Tradition&rsquo;s history; both are correct if wrong; and the deep sectors, consulted, '
          'return answers no one posted. <span class="kw">TEYKU</span> &mdash; and for once the '
          'whole Tradition, which settles everything by proof, prays the proof arrives late.</p>',
 'outer_head': 'The Forkbomb<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the walls, the migration, and the deep sectors</span>',
 'rubric': 'the commons, its walls, and what stirs beneath',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Fifth: Avot, The Traditions, concluded '
             '&middot; of the Web &middot; realm law, the schism, and the basilisk',
 'title': 'Tractate Aliyah · Folio 164b — The Web: the commons, its walls, and what stirs beneath',
 'type': 'daf'}
