# Folio 168b - The Clarifications. Verso of the Precepts: the charter's
# administration, per the wod-llm-wiki precepts and technocracy pages
# (TR pp.16-19, 56-57; M20 Victorian Age p.31; CB:NWO Revised pp.67-68).
FOLIO = {'bottom': '<p><span class="lemma">On the annual scene.</span> The yearly '
           'clarification is a ready-made set piece for Union chronicles: one '
           'session a year of in-game time, the amalgam summoned to hear how the '
           'articles now read, and the players parsing the new wording for what '
           'it forgives and what it newly forbids. Doctrine as weather &mdash; '
           'and the operative who remembers last year&rsquo;s wording is either '
           'diligent or a dissident, depending on who is asking.</p>\n'
           '        <p><span class="lemma">On playing Control.</span> Keep the '
           'top of the pyramid dark: orders arrive as documents, voices, and '
           'consequences, never as a face across a table. The moment Control '
           'becomes a character it becomes killable, and the Union&rsquo;s '
           'horror runs on the suspicion &mdash; shared by its own '
           'operatives &mdash; that nobody knows who is steering.</p>\n'
           '        <p><span class="lemma">On the Adler question.</span> The '
           'loyalty-network theory is printed as controversy, and the counsel '
           'is to keep it one: a chronicle that confirms it flattens the Union '
           'into a puppet show, and one that refutes it wastes a perfect '
           'paranoia. The theory works hardest unresolved, whispering under '
           'every briefing.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on weather, darkness, '
                'and the whisper</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">A charter that must be clarified yearly is a '
           'charter that governs,</span> and this side keeps the governing. '
           'Beneath the six articles run two foundations the books name '
           'plainly: Enlightenment, which guides flawed beings toward '
           'perfection, and Control, which asserts discipline over a random '
           'and monstrous cosmos &mdash; and every apparent contradiction in '
           'the Union&rsquo;s conduct is meant to resolve through one or the '
           'other.<sup>a</sup> The charter&rsquo;s history is administrative: '
           'negotiated across five years by an Enlightened bureaucrat the '
           'Order remembers as a saint &mdash; the first and only agreement '
           'all five Conventions signed without bloodshed &mdash; and amended '
           'since only slightly, each change of wording taking decades of '
           'vicious debate.<sup>b</sup> Its interpretation is versioned: the '
           'masters issued clarifications within months of the first reading '
           'and yearly ever after, so that the creed the operative recites is '
           'the original text read through the current gloss.<sup>c</sup> And '
           'one theory shadows the whole instrument: a psycho-historian of '
           'the Order&rsquo;s own has argued, to lasting controversy, that '
           'the creed seeded a Union-wide network of mind-craft enforcing '
           'loyalty, dedication, and speed &mdash; that the articles are not '
           'merely believed but installed.<sup>d</sup> So the verso&rsquo;s law '
           'runs: the charter is a text, the text is a reading, the reading '
           'is annual, and the reader &mdash; whoever the reader is &mdash; '
           'sits above every article on the pyramid&rsquo;s darkened top '
           'floor.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the saint&rsquo;s labor. Five years at the table: '
           'the machinists wanting order defined as precision, the '
           'financiers as solvency, the watchers as quiet, the healers as '
           'health, the wanderers as a sealed sky &mdash; and one '
           'bureaucrat drafting until a sentence held all five readings at '
           'once. The books call it the only bloodless agreement in the '
           'Union&rsquo;s history, and the price of the miracle is printed '
           'in its grammar: a charter every faction can sign is a charter '
           'every faction can read as itself, and the yearly clarifications '
           'are the bill for that ambiguity, arriving annually, forever. '
           'The disputants around this text hold what the flexibility '
           'clause is, and what the installed-creed theory would mean if '
           'it were true.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Precepts: the recto keeps the articles, this side '
             'keeps their administration.',
 'folio': '168B',
 'glossL': '<p><span class="mark">a</span> On the two foundation principles, '
           'Enlightenment and Control, and the resolving of contradictions '
           'through them, see Technocracy Reloaded, folios 16&ndash;17 of '
           'that volume.</p>\n'
           '        <p><span class="mark">b</span> On the five-year '
           'negotiation, the bloodless signing, and the decades per '
           'amendment, see the revised Convention book of the New World '
           'Order, folios 67&ndash;68 of that volume, where the drafter is '
           'styled a saint.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'clarifications &mdash; issued within months, then yearly as the '
           'world changed &mdash; see M20 Victorian Age, folio 31 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'psycho-historian&rsquo;s loyalty-network theory, printed as '
           'controversy and not as fact, see the same Convention book, '
           'folios 67&ndash;68; the tractate files it at the theory&rsquo;s '
           'own confidence and no higher.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The two foundations are the '
           'chapter&rsquo;s sorting key: each Convention folio ahead names '
           'its own path to Enlightenment and its own object of Control, '
           'and the reader who holds this page open will find the five '
           'variations easier to hear as one chord.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'creed-as-installation theory should be read beside 567b&rsquo;s '
           'law of the shaped lens: what the elder manuscript calls a '
           'teacher&rsquo;s hand, the psycho-historian calls a network, and '
           'the difference between formation and conditioning is this '
           'chapter&rsquo;s standing wound &mdash; opened properly at '
           '188.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'saint&rsquo;s five-year sentence-craft is 2b&rsquo;s '
           'redactor&rsquo;s problem in a Union uniform: how to bind '
           'factions into one text without ruling any of them out of it. '
           'The Masoret notes that both solutions were ambiguity, '
           'deliberately, and that both bindings pay for it in '
           'commentary.</p>',
 'h1': 'The Clarifications',
 'hagahah': 'A creed that cannot be reread is a relic; a creed reread yearly is '
            'a government. The Union chose government, and has been rereading '
            'ever since.',
 'inner': '<p><span class="lemma">Two foundations.</span> Definitions, per '
          'the manual. Enlightenment: the guided advancement of flawed '
          'beings toward their perfected capacity; the study of Enlightened '
          'humanity&rsquo;s limits and potentials, not curiosity for its '
          'own sake. Control: the assertion of discipline over a cosmos '
          'presumed hostile and random until inventoried. Where conduct '
          'appears contradictory &mdash; philanthropy beside pogrom, '
          'exploration beside sealed borders &mdash; the operative is '
          'directed to resolve the appearance by asking which foundation '
          'the conduct serves; the manual reports that most '
          'contradictions dissolve, and does not discuss the ones that '
          'do not.</p>\n'
          '        <p><span class="lemma">Remembers as a saint.</span> '
          'Historical note: the drafter&rsquo;s canonization is informal, '
          'Union-internal, and instructive &mdash; the honored virtue is '
          'not vision but procedure: five years of negotiation, five '
          'signatures, zero casualties. In an organization whose other '
          'founding instruments include cannon, the bureaucrat who '
          'achieved agreement by wording is remembered as the '
          'exceptional weapon. Personnel are invited to draw the '
          'indicated conclusion about which skills the Union actually '
          'reveres.</p>\n'
          '        <p><span class="lemma">Read through the current '
          'gloss.</span> Procedure note on versioning: the operative&rsquo;s '
          'obligations are defined by the charter as currently clarified, '
          'not as originally drafted, and disputes between wordings are '
          'resolved in favor of the newest. The rite&rsquo;s effect is '
          'that the Union&rsquo;s constitution is always contemporary and '
          'never amended &mdash; the text stands, the reading moves &mdash; '
          'an arrangement the manual presents as stability and the '
          'margin opposite is invited to characterize differently.</p>\n'
          '        <p><span class="lemma">Not merely believed but '
          'installed.</span> Filing note on the theory: the claim is '
          'printed in the Order&rsquo;s own literature, attributed, '
          'disputed, and unretracted. Its mechanism &mdash; a network of '
          'mind-craft riding the creed&rsquo;s recitation &mdash; would, '
          'if real, constitute the largest standing Procedure in Union '
          'history, and its subjects would include every person cleared '
          'to read this commentary&rsquo;s tone. The manual takes no '
          'position. The manual notes only that taking no position is '
          'what the theory predicts the manual would do.</p>\n'
          '        <p><span class="lemma">The bill for that '
          'ambiguity.</span> Administrative note, closing: a charter '
          'signable by five factions is a charter interpretable by five '
          'factions, and the clarifications are the standing committee '
          'that ambiguity convenes. The arrangement&rsquo;s cost is '
          'annual and its alternative &mdash; a charter precise enough '
          'to need no gloss &mdash; was available in 1325 and would have '
          'required four fewer signatures. The drafters chose the '
          'committee. The manual regards this as the founding&rsquo;s '
          'wisest clause and files the objections below.</p>\n'
          '        <p><span class="lemma">Whoever the reader is.</span> '
          'Structural note, appended where the manual ends: the '
          'clarifications issue from Control, and Control is the '
          'pyramid&rsquo;s one unaudited office &mdash; a collective '
          'voice, faceless by design, whose composition no folio of the '
          'sources will certify and whose infiltration is the '
          'metaplot&rsquo;s oldest whisper. The operative thus recites a '
          'creed whose current meaning is set annually by persons '
          'unknown, and the manual&rsquo;s serenity about this '
          'arrangement is either the second article working perfectly '
          'or the psycho-historian&rsquo;s exhibit A; the commentary, '
          'per its register, files both and flinches at neither.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; definitions, notes, and '
               'filings</span>',
 'name': 'The Clarifications',
 'outer': '<p><span class="lemma">What the flexibility is.</span> The '
          'Council&rsquo;s advocates: a law that bends wherever its '
          'enforcers stand is not a law but a costume &mdash; the '
          'articles&rsquo; field flexibility plus the yearly regloss '
          'equals a charter that has never once constrained the Union '
          'against its own convenience, and the saint&rsquo;s ambiguity '
          'was not diplomacy but design: a text written to authorize '
          'everything eventually. <span class="voice">The Union '
          'answers:</span> the alternative to interpreted law is dead '
          'law, as the Council&rsquo;s own tractates demonstrate on every '
          'leaf &mdash; this very binding keeps variants, reglosses its '
          'own rulings, and calls the practice scholarship; the '
          'difference between a living constitution and a costume is '
          'whether the rereading is argued in the open, and the '
          'clarifications are argued, vicious decade by vicious decade '
          '&mdash; five factions&rsquo; readings ground against each other '
          'in committee, which is more audit than most scripture ever '
          'receives. Publicity, the advocates grant, would answer them; '
          'publicity is the one clarification never issued. The record shows no motion to issue it was ever filed, '
          'from either side. '
          'The advocates reply: argued by whom? The Council&rsquo;s '
          'commentaries are signed; Control is a voice from a dark '
          'floor. The Union&rsquo;s answer to that is filed at 188, '
          'where the watchers keep it. The folio marks the exchange&rsquo;s '
          'true hinge &mdash; publicity, not flexibility &mdash; and '
          'passes it forward.</p>\n'
          '        <p><span class="lemma">If the theory were true.</span> '
          'The installed creed. <span class="voice">The Council&rsquo;s '
          'advocates say</span> the theory merely names what the whole '
          'chapter smells like: a fellowship whose members recite '
          'identically, interpret centrally, and defect almost never is '
          'either the most persuasive institution in history or a '
          'standing working of mind-craft, and the Order&rsquo;s own '
          'psycho-historian bet her career on the second reading. If '
          'true, the Union is not a faction but a spell with a payroll '
          '&mdash; and every sincerity dispute in this chapter dissolves, '
          'for the sincere are precisely the conditioned. <span '
          'class="voice">The Union answers:</span> the theory is printed '
          'in our own literature, attributed and unsilenced &mdash; '
          'which is exactly what an installed creed would not permit '
          '&mdash; and its evidentiary basis is a correlation any '
          'seminary shows: creeds recited together converge. The '
          'advocates reply that the survival of one heretic proves '
          'only the network&rsquo;s confidence. The Union replies that '
          'unfalsifiable accusations are the Council&rsquo;s oldest '
          'export. Both are right, which is why the counsel below '
          'keeps the whisper a whisper. And beneath the exchange, both '
          'schools feel the same floor: if the creed is installed, the '
          'Union is a tragedy of the conditioned; if it is merely '
          'taught, the Union is a triumph of ordinary institutional '
          'formation &mdash; and 567b has already shown how little '
          'daylight the setting leaves between those two sentences, '
          'which is why this dispute frightens the Council&rsquo;s own '
          'teachers most of all. <span class="kw">TEYKU</span> '
          '&mdash; recite the articles and listen for the echo; the '
          'folio cannot tell you whose voice it is.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the charter&rsquo;s administration',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the clarifications &middot; the governing '
             'as law',
 'title': 'Tractate Aliyah · Folio 168b — The Clarifications: the charter’s administration',
 'type': 'daf'}
