# Folio 168a - The Precepts. Chapter VI opens: the Union's charter as
# law, per the wod-llm-wiki technocracy and precepts pages (M20
# pp.168-171; TR pp.14, 56-57; M20 Victorian Age p.31).
# Register swap trialed here per PLAN: inner = procedures-manual
# deadpan, outer = Tradition polemic with the Union answering.
FOLIO = {'bottom': '<p><span class="lemma">On playing the Union.</span> A Technocratic '
           'chronicle works when the six articles are played as sincerely held: '
           'the operative believes she is the adult in a burning nursery, and the '
           'horror arrives not despite the sincerity but through it. Cast the '
           'players as idealists inside the machine and let the machine&rsquo;s '
           'errands arrive on official paper; the best Union campaigns are '
           'paperwork with a body count, discovered gradually.</p>\n'
           '        <p><span class="lemma">On the mirror rule.</span> Whatever '
           'the table&rsquo;s allegiance, run the Union by 2a&rsquo;s mirror: '
           'every accusation the Council files here can be filed against some '
           'seat of chapter V, and the campaigns that admit it play richer than '
           'the ones that cast mirrorshades as orcs. The Union is most '
           'frightening exactly when it is most reasonable.</p>\n'
           '        <p><span class="lemma">On the whitewash line.</span> '
           'Sympathy is not absolution: the books keep the pogrom, the '
           'conditioning, and the erasures on the record even in the '
           'Union&rsquo;s friendliest printings, and so should the table. The '
           'protagonist Union is the one whose crimes the players must carry, '
           'not the one whose crimes the chronicle forgets.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on sincerity, mirrors, '
                'and the line</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The Union&rsquo;s charter runs six articles,</span> '
           'and every operative knows them by heart at the door. First: bring '
           'order and stasis to the universe, for predictability is safety, and '
           'when all is known, unity is won. Second: persuade the Masses of the '
           'benevolence of science, commerce, and governance &mdash; make the '
           'rational creed palatable. Third: preserve the Gauntlet and the '
           'Horizon, for the veil is a border and borders are kept. Fourth: '
           'define the nature of the universe &mdash; knowledge must be total, '
           'since whatever is left unknown is left to chaos. Fifth: destroy the '
           'Reality Deviant &mdash; destroy, the article says, and not kill, for '
           'the target is the threat and not merely the throat. Sixth: shepherd '
           'the Masses, and protect them from themselves and from '
           'others.<sup>a</sup> The charter carries its own dictionary: the '
           'ladder of the will is called Enlightenment, the inner spark Genius, '
           'the workings Procedures, and the court&rsquo;s two rates subtle and '
           'blatant &mdash; the law of 533a wearing a lanyard.<sup>b</sup> And '
           'the books record one clause the recruiters do not read aloud: in '
           'the field, the articles have always proven flexible &mdash; and '
           'that the whole world is accounted the Union&rsquo;s enemy, most of '
           'it merely not yet informed.<sup>c</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD the founding from inside. Before the Order had a '
           'name, cannon felled a wizard&rsquo;s white tower, and the men '
           'behind the guns called it the first shot of a war of mercy. At the '
           'tower&rsquo;s ruin, in the year the books give as 1325, eight '
           'fellowships sat down together and swore the promise: an end to '
           'mystical tyranny, protection for the common people, the arts of '
           'men raised over the arts of magick. Five centuries on, a '
           'professor stood before a queen and read her six articles as a new '
           'philosophy for a new era; within months the masters issued '
           'clarifications, and the clarifying became a yearly rite, for the '
           'world would not hold still. And the books&rsquo; own verdict '
           'stands in the record beside the promise: somewhere on the road, '
           'the promise went bad. The disputants around this text hold '
           'whether the articles describe the Union or excuse it, and '
           'whether the going-bad was betrayal or destination.<sup>d</sup></p>',
 'chapter': 'Chapter the Sixth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter VI opens: the charter here, its administration overleaf, '
             'and the five Conventions at 186 through 194.',
 'folio': '168A',
 'glossL': '<p><span class="mark">a</span> On the six precepts and their goals '
           '&mdash; order, training, security, surveillance, the pogrom, and '
           'the shepherded Masses &mdash; see M20, folios 168&ndash;171, whence '
           'this page takes its number; the drilled articles are Technocracy '
           'Reloaded&rsquo;s, folios 56&ndash;57 of that volume.</p>\n'
           '        <p><span class="mark">b</span> On the dictionary &mdash; '
           'Enlightenment, Genius, Procedures, subtle and blatant &mdash; see '
           'the same folios of M20.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'flexibility in the field, see Technocracy Reloaded, folio 56 of '
           'that volume, which prints the admission in so many words.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'founding &mdash; the tower, the convention of 1325, the promise '
           'and its souring &mdash; see Technocracy Reloaded, folio 14, and Convention Book: Syndicate Revised, folio 24 of that volume, on the White Tower convention of 1325; the professor before the queen is M20 Victorian Age, folio 31 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Read 2a again before reading '
           'this page: a convocation, a promise, a war justified by mercy. '
           'The rhyme is not subtle and the Masoret declines to pretend '
           'otherwise; the two founding stories are the binding&rsquo;s '
           'matched bookends, and each side files the other&rsquo;s as '
           'propaganda.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'court whose rates the charter renames is 533a&rsquo;s, and the '
           'Union&rsquo;s standing advantage there &mdash; its workings '
           'drafted inside the street&rsquo;s belief &mdash; is 607b&rsquo;s '
           'sanctioned shelf, argued at length where the Book of Magick '
           'closes.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'five Conventions execute the articles by division of labor: '
           'the perfected form at 186, the managed narrative at 188, the '
           'improvable draft at 190, the priced real at 192, and the kept '
           'border at 194. The charter is the chord; the folios are its '
           'notes.</p>',
 'h1': 'The Precepts',
 'hagahah': 'Both sides&rsquo; founding documents promise to save the world. '
            'The world was not consulted, and has yet to file a reply.',
 'inner': '<p><span class="lemma">Six articles.</span> Definitions, per the '
          'manual. The charter is a mission statement, not a metaphysic: '
          'each article names a deliverable &mdash; a stable reality, a '
          'persuaded population, a sealed border, a completed inventory of '
          'nature, a neutralized deviance, a managed flock &mdash; and '
          'every Union operation on record can be filed under at least '
          'one. Operatives are examined on the articles at induction and '
          'annually thereafter; familiarity is assumed at every rank and '
          'audited at most.</p>\n'
          '        <p><span class="lemma">Predictability is safety.</span> '
          'Procedure note on the first article: the Masses do not panic at '
          'what they believe they understand, and a population that '
          'believes it understands the world can be taught. Order is '
          'therefore not an aesthetic preference but a prerequisite of '
          'instruction; stasis is the classroom&rsquo;s closed door. The '
          'article&rsquo;s end state &mdash; all discovered, all known, '
          'unity won &mdash; is scheduled, not hoped for.</p>\n'
          '        <p><span class="lemma">Destroy, and not kill.</span> '
          'Procedure note on the fifth article, wording load-bearing: the '
          'deliverable is the elimination of the threat posed, of which '
          'the deviant&rsquo;s death is one instrument among several and '
          'not always the indicated one. Capture, conversion, '
          'conditioning, and erasure of standing all satisfy the article; '
          'the doctrine of necessary force governs selection. The '
          'article&rsquo;s verb is the charter&rsquo;s most examined word '
          'and the margin opposite holds the examination.</p>\n'
          '        <p><span class="lemma">Subtle and blatant.</span> '
          'Terminology note: the court of 533a is acknowledged in full '
          'and renamed in full. A subtle Procedure conforms to consensus '
          'expectation and is billed at the coincidental rate; a blatant '
          'one contradicts it and is billed accordingly. The renaming is '
          'itself an application of the second article: vocabulary is an '
          'instrument, and the operative who says Enlightened Science '
          'where another says magick has already begun persuading the '
          'Masses, starting with herself.</p>\n'
          '        <p><span class="lemma">Shepherd the Masses.</span> '
          'Procedure note on the sixth article, the charter&rsquo;s '
          'keystone: the Masses are classified as people, and people as '
          'requiring direction &mdash; given it, they build toward the '
          'scheduled Utopia; left alone, they self-destruct at rates the '
          'statisticians tabulate annually. The article therefore assigns '
          'the Enlightened a fiduciary posture: decisions taken on the '
          'flock&rsquo;s behalf, in the flock&rsquo;s interest, without '
          'the flock&rsquo;s knowledge, the last condition being '
          'load-bearing &mdash; a flock that knew of its shepherds would, '
          'per the first article, panic. The manual notes that every '
          'objection to this arrangement is anticipated in the '
          'literature, catalogued, and answered. The manual does not '
          'note that the flock has never been shown the catalogue, '
          'which is the sixth article applied to its own defense.</p>\n'
          '        <p><span class="lemma">Have always proven '
          'flexible.</span> Compliance note, filed without comment where '
          'the manual files it: the articles bind interpretation to '
          'circumstance, and circumstance in the field includes the '
          'operative&rsquo;s survival, the mission&rsquo;s completion, and '
          'the supervisor&rsquo;s report. The yearly clarifications '
          'exist because the charter&rsquo;s drafters knew the world '
          'moves; the field flexibility exists because the drafters&rsquo; '
          'successors know the paperwork arrives after the shooting '
          'stops. The two facts are printed on facing pages and the '
          'manual sees no tension.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; definitions, procedure '
               'notes, compliance notes</span>',
 'name': 'The Precepts',
 'outer': '<p><span class="lemma">Describe or excuse.</span> The '
          'Council&rsquo;s advocates open: read the six as one sentence and '
          'the sentence is a confession &mdash; we will decide what is '
          'real, persuade you to thank us, wall off the alternatives, '
          'inventory everything, destroy whoever objects, and call the '
          'whole arrangement your protection. Every tyranny in the '
          'Masses&rsquo; long history has issued this document; only the '
          'letterhead changes. <span class="voice">The Union '
          'answers:</span> read your own binding &mdash; chapter V is nine '
          'seats deciding what is real and gatekeeping who may learn it, '
          'and the tractate&rsquo;s own second folio is a war justified by '
          'a betrayal story. The difference between a charter and a '
          'confession is whether you believe the signers, and belief, as '
          'this binding keeps saying, is the whole game. The advocates '
          'reply that they at least never promised the world unity on a '
          'schedule; the Union replies that the world has clocks because '
          'somebody wound them. The folio files the exchange and moves '
          'the real question to the margin: not whether the articles '
          'could excuse &mdash; any creed can &mdash; but what this '
          'creed&rsquo;s daily administration actually produces, which '
          'the next five folios document Convention by Convention. One '
          'exchange more, for it recurs at every table: the advocates '
          'note that the sixth article calls people stupid in the '
          'training halls, whatever the parchment says; the Union '
          'answers that the Council&rsquo;s own elders say worse of the '
          'Sleepers in gentler fonts, and the binding&rsquo;s five '
          'chapters of gates and gatekeepers are entered as '
          'exhibit. The advocates take the point and sharpen it: the '
          'Council&rsquo;s contempt at least keeps no Timetable &mdash; a '
          'seat that despairs of the Sleepers merely waits, while a '
          'Union that plans for them plans them, and the difference '
          'between waiting and planning is the whole distance between '
          'a church and a ministry. Neither party, it will be noted, disputes the despair. The exhibit is accepted into the record over both '
          'objections, per the binding&rsquo;s custom.</p>\n'
          '        <p><span class="lemma">Betrayal or destination.</span> '
          'The sincerity dispute, the chapter&rsquo;s spine. <span '
          'class="voice">The Council&rsquo;s advocates say</span> '
          'destination: a charter whose first deliverable is stasis and '
          'whose last is a shepherded humanity was always going to '
          'arrive here &mdash; the idealist officer is real, and she is '
          'the institution&rsquo;s fuel, burned to move something that '
          'was never going where she believes; the promise did not go '
          'bad on the road, the road was the badness, surveyed and '
          'graded from the first cannon. <span class="voice">The Union '
          'answers</span> betrayal, and names its evidence: the '
          'founding&rsquo;s genuine universalism &mdash; any Enlightened '
          'soul, regardless of birth, in an age that permitted no such '
          'thing &mdash; the dissident cells the books document fighting '
          'for the Union&rsquo;s soul from inside, the reformations '
          'real and recurring; an institution that keeps producing its '
          'own reformers has not finished becoming anything. The '
          'advocates answer that the reformers keep losing; the Union '
          'answers that so do the Council&rsquo;s, and chapter VII is '
          'their ledger. <span class="kw">TEYKU</span> &mdash; and the '
          'yearly clarifications continue, which both schools claim as '
          'their proof.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the six articles, and the promise',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union '
             '&middot; of the precepts &middot; the charter as law',
 'title': 'Tractate Aliyah · Folio 168a — The Precepts: the six articles, and the promise',
 'type': 'daf'}
