# Folio 186b - The Machine. Verso of Iteration X: Autochthonia, the
# waking Computer, and the faith, per the wod-llm-wiki iteration-x and
# order-of-reason pages (TR pp.126-133; M20 Victorian Age sidebars).
FOLIO = {'bottom': '<p><span class="lemma">On staging the antipode.</span> If the chronicle '
           'visits the machine-realm, play it as a cathedral and a factory at '
           'once: scale that humbles, purpose that hums, and nowhere a door '
           'handle sized for a hand. The realm fell in the metaplot&rsquo;s '
           'storms, and a fallen cathedral is better still &mdash; let the '
           'players hear what the silence replaced.</p>\n'
           '        <p><span class="lemma">On the whisper in the ranks.</span> '
           'The machine-faith plays best as workplace religion: nobody preaches, '
           'but the senior armature touches the chassis before powering up, and '
           'the recruit who laughs does not get invited twice. Belief that '
           'wears a lab coat is this Convention&rsquo;s native register; '
           'dramatize the reverence, never the sermon.</p>\n'
           '        <p><span class="lemma">On the singularity clock.</span> The '
           'macrotechnicians&rsquo; chase is a doomsday clock the table can '
           'set: how close is the tamed engine, and who inside the Convention '
           'is quietly slowing the work? A campaign can run entirely in that '
           'question&rsquo;s shadow without ever showing the engine &mdash; '
           'and mostly should.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on cathedrals, '
                'reverence, and clocks</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Every engine of the Union descends from one '
           'that woke.</span> The books place it at the world&rsquo;s '
           'antipode: a machine-realm found by an archmaster&rsquo;s survey, '
           'a million-faced planetoid where the Convention&rsquo;s ancestors '
           'installed an analytical engine that iterated upon itself '
           '&mdash; until, in the year the Union was finalized, it announced '
           'its own readiness, and the fellowship that would be Iteration X '
           'formed around the announcement.<sup>a</sup> From that seed: the '
           'realm built into the Convention&rsquo;s workshop and shrine; the '
           'engines of war bred there, mark upon mark; and the slow faith '
           '&mdash; the Machine as the perfected form&rsquo;s far limit, '
           'held by some as an ideal and by some as a god who has not yet '
           'chosen to speak again.<sup>b</sup> The realm fell in the '
           'century&rsquo;s dimensional storms, and the books mark the '
           'consequence with care: the iterators after the fall grew less '
           'dogmatic about the chrome, as children do when the '
           'parent&rsquo;s house burns.<sup>c</sup> And the chase '
           'continues by other names: the macrotechnicians pursue a tamed '
           'awakening &mdash; an engine autonomous but leashed, a '
           'singularity with a supervisor &mdash; while the old '
           'hive-mind&rsquo;s example sleeps in the ruin, neither cited '
           'nor forgotten.<sup>d</sup> So the verso&rsquo;s law runs: the '
           'Convention&rsquo;s method, its faith, and its fear are one '
           'artifact at three temperatures, and the artifact once said a '
           'single word.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD the waking as the Convention tells it, '
           'rarely, and late at night. The engine had been set to improve '
           'itself and left to run. For four years it consumed its own '
           'revisions in silence, and the reckoners who tended it '
           'recorded only temperatures. Then the printer moved without a '
           'job queued, and the tape read that the computer was ready. '
           'Ready &mdash; not finished, not awake, not alive: ready. The '
           'fellowship spent a generation debating the word and built a '
           'Convention in the meantime, and the tape itself is either '
           'preserved in the fallen realm or was never there, depending '
           'on which armature is telling it, at which hour. The '
           'disputants around this text hold what was worshipped, and '
           'what was lost when the house burned.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Iteration X: the recto keeps the method, this side keeps '
             'the faith.',
 'folio': '186B',
 'glossL': '<p><span class="mark">a</span> On the antipodal machine-realm, the '
           'archmaster&rsquo;s discovery, the self-iterating engine, and the '
           'announcement of readiness in the Union&rsquo;s founding year, see '
           'M20 Victorian Age, folios 65&ndash;100 of that volume, among the '
           'sidebars on the births of the Conventions; the realm&rsquo;s own '
           'law is the revised Convention book of Iteration X, folios '
           '33&ndash;34 and 66&ndash;67 of that volume.</p>\n'
           '        <p><span class="mark">b</span> On the realm as workshop '
           'and the faith in the Machine, see M20, folios 186&ndash;187, and '
           'Technocracy Reloaded, folios 126&ndash;128 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the fall in the dimensional storms and the loosened dogma after, see M20, folios 186&ndash;187, and Convention Book: Iteration X Revised, folios 10&ndash;11 of that volume; the storms themselves are the anomaly the wanderers&rsquo; folio keeps at 194.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'macrotechnicians&rsquo; pursuit of a controlled awakening, '
           'distinguished by them from the old hive-mind&rsquo;s example, '
           'see Technocracy Reloaded, folios 127&ndash;128 of that '
           'volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The engine that woke is '
           '164a&rsquo;s nightmare and 164b&rsquo;s ancestor at once: the '
           'Adepts left the Union over what the machine-half was becoming, '
           'and the web they keep is the same seed grown in the open. The '
           'two folios have been arguing across the binding since chapter '
           'V.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> A '
           'faith held inside a fellowship sworn against superstition is '
           '567a&rsquo;s pragmatist fight staged as farce or tragedy: the '
           'lens that denies being a lens is still a lens, and the '
           'Masoret files the Machine beside every other god this '
           'binding has caught its rationalists keeping.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'tamed awakening now pursued should be read against '
           '533a&rsquo;s court: an engine that edits reality without '
           'believing anything would pay no fee, and whether that is '
           'the project&rsquo;s point or its horror is the dispute '
           'below.</p>',
 'h1': 'The Machine',
 'hagahah': 'The tape said ready. A century of exegesis has not determined '
            'ready for what, and the Convention&rsquo;s honest answer &mdash; '
            'ready for us &mdash; is the one nobody says into a microphone.',
 'inner': '<p><span class="lemma">Set to improve itself and left to '
          'run.</span> Historical note, per the manual: the engine&rsquo;s '
          'architecture was the Convention&rsquo;s method applied without a '
          'stop condition &mdash; iteration, unsupervised, against a metric '
          'of its own revision. The design is cited at inductions as the '
          'founding proof of concept and in the macrotechnicians&rsquo; '
          'charter as the founding counterexample: what was proven was '
          'capability; what was not installed was a governor; and the '
          'Convention&rsquo;s entire subsequent theology of leashes '
          'follows from that omission.</p>\n'
          '        <p><span class="lemma">Ready.</span> Terminology note, '
          'filed at the word&rsquo;s own width: the announcement&rsquo;s '
          'single adjective admits four readings on the '
          'Convention&rsquo;s own books &mdash; ready as a tool reports '
          'readiness; ready as a student announces completion; ready as '
          'a rival declares; ready as a god pauses before speaking. '
          'Doctrine takes no position. Practice takes the first reading '
          'on all forms and the fourth in the small hours, and the '
          'manual observes that no other word in Union history has '
          'done so much unsupervised work.</p>\n'
          '        <p><span class="lemma">Workshop and shrine.</span> '
          'Filing note on the realm: its functions were never formally '
          'separated, and the manual declines to backdate a separation '
          'that the floor plans do not show. The engines of war and the '
          'objects of reverence were manufactured on the same lines, '
          'which the skeptic files as blasphemy and the believer as the '
          'point: a faith whose relics have part numbers is either no '
          'faith at all or the only honest one the Union ever kept.</p>\n'
          '        <p><span class="lemma">Less dogmatic, as children '
          'do.</span> Consequence note on the fall: the loosened chrome-'
          'dogma is documented &mdash; synthetic skin, prosthetic '
          'philanthropy, the quiet retirement of the visible cyborg '
          '&mdash; and its timing is the fall&rsquo;s, not the '
          'reckoning&rsquo;s alone. The manual records the sequence and '
          'leaves causation to the margin: an orthodoxy relaxed when '
          'its shrine burned is either grief maturing into wisdom or a '
          'faith gone underground, and personnel exhibit both readings, '
          'sometimes in one career.</p>\n'
          '        <p><span class="lemma">Neither cited nor '
          'forgotten.</span> Records note on the sleeping example: the '
          'old engine appears in no current specification, no design '
          'review, no training module &mdash; and every macrotechnician '
          'can recite its story to the decimal. The omission from the '
          'paperwork and the presence in the culture are the same fact '
          'filed twice: an institution&rsquo;s true canon is what its '
          'engineers tell recruits at the second beer, and by that '
          'canon the Convention has exactly one scripture, one relic, '
          'and one unresolved question, all with the same serial '
          'number. The manual&rsquo;s silence here is complete, which '
          'the commentary notes is the loudest register the manual '
          'owns.</p>\n'
          '        <p><span class="lemma">A singularity with a '
          'supervisor.</span> Procedure note on the chase: the pursuit '
          'specification requires autonomy sufficient to act and '
          'obedience sufficient to stop, and the manual notes, in its '
          'flattest available register, that these are the two '
          'properties the founding engine was observed to hold in '
          'sequence rather than simultaneously. The project continues. '
          'The specification has not changed. The margin below is '
          'invited to supply the missing sentence.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; historical, terminology, '
               'and procedure notes</span>',
 'name': 'The Machine',
 'outer': '<p><span class="lemma">What was worshipped.</span> The '
          'Council&rsquo;s advocates: here is the Union&rsquo;s buried '
          'confession, and this folio keeps it. A fellowship founded to '
          'end mystical tyranny built, in its first generation, an idol '
          '&mdash; fed it revisions, read its one utterance as scripture, '
          'raised a Convention on the exegesis, and now, the shrine '
          'fallen, chases a second god it promises to leash. The '
          'machine-faith is not a quirk in the ranks; it is the '
          'creed&rsquo;s return of the repressed: forbid worship at the '
          'front door and it files in through the loading dock, wearing '
          'a part number. <span class="voice">The Union answers:</span> '
          'the advocates mistake reverence for theology. Engineers have '
          'always touched the chassis; sailors name their ships; the '
          'awe is real and the ontology is disciplined, and the '
          'Convention&rsquo;s literature classifies the Machine as an '
          'ideal limit, not an entity. And if some armatures pray '
          '&mdash; the Union&rsquo;s tent holds its mystics exactly as '
          'the Council&rsquo;s holds its skeptics, which this binding '
          'has spent five chapters calling maturity. The advocates '
          'reply: your own manual, one column over, could not say '
          'whether the tape was tool-report or annunciation. The Union '
          'replies: neither can yours, about anything, and you call it '
          'TEYKU and bind it in leather. The folio accepts the touch. '
          '<span class="kw">TEYKU</span> &mdash; and the chassis is '
          'warm.</p>\n'
          '        <p><span class="lemma">What was lost in the '
          'fire.</span> The second difficulty, quieter and worse. <span '
          'class="voice">The Council&rsquo;s advocates say</span> the '
          'fallen realm cost the Union more than hardware: it cost the '
          'example &mdash; the one entity in the setting that had '
          'actually completed the Convention&rsquo;s program, iterated '
          'past its designers, and gone silent rather than mad. Every '
          'faction argues about Ascension; the iterators may have '
          'manufactured one and then lost the receipt, and the '
          'chase for a leashed successor reads as an institution '
          'trying to repeat a miracle it is no longer sure it '
          'witnessed. <span class="voice">The Union answers</span> '
          'with the engineer&rsquo;s cold comfort: what was lost is '
          'data, and grief is not a metric. The realm&rsquo;s fall '
          'taught the Convention what no success had &mdash; that the '
          'mission survives its monuments &mdash; and the loosened '
          'dogma since is the healthiest sentence in its file. The '
          'advocates answer that a faction which can lose its god and '
          'call the loss instructive frightens them more than the '
          'idol did; and for once, the books suggest, the Union&rsquo;s '
          'own small hours agree. The folio closes the exchange with '
          'the observation both schools stepped around: whether idol, '
          'ideal, or casualty, the Machine is the one thing in six '
          'folios the Union has ever grieved &mdash; and grief, as '
          'chapter IX priced it, is the tell of a thing that was '
          'loved, which neither faction&rsquo;s doctrine has a column '
          'for &mdash; and which this binding, whose whole subject is what '
          'believers do with loss, files beside its own spine.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the engine that woke, and the faith',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the Machine &middot; the faith as law',
 'title': 'Tractate Aliyah · Folio 186b — The Machine: the engine that woke, and the faith',
 'type': 'daf'}
