# Folio 186a - Iteration X. First Convention folio, per the wod-llm-wiki
# iteration-x page (M20 pp.186-187; TR pp.126-133).
FOLIO = {'bottom': '<p><span class="lemma">On the Iterator as character.</span> The '
           'Convention&rsquo;s playable heart is the engineer who has met her own '
           'flaw and hated it: the books say the archetypal Iterator refines '
           'order from imperfection and came, often, from a deeply imperfect '
           'somewhere. Build the character around the flaw she is iterating '
           'against, and the chrome stops being costume and becomes '
           'testimony.</p>\n'
           '        <p><span class="lemma">On machines with faces.</span> Give '
           'the Convention&rsquo;s hardware personality sparingly: the HIT Mark '
           'that pauses one beat too long, the scrum team&rsquo;s scheduler that '
           'assigns one member all the night shifts. The dread of Iteration X is '
           'not that its machines hate you; it is that nobody, including the '
           'machines, is certain anyone is deciding anything.</p>\n'
           '        <p><span class="lemma">On the thrown-out conclusions.</span> '
           'The Convention that admitted its great calculation was wrong is the '
           'Convention most worth playing: let veterans carry the embarrassment '
           'and recruits the freedom, and let both flinch when anyone mentions '
           'the schedule. An institution&rsquo;s best stories live in the drawer '
           'where it filed its abandoned certainties.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on flaws, faces, and '
                'the drawer</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The first Convention keeps the perfected '
           'form.</span> Its creed the books state as a choice no reasoning '
           'organism refuses: between frailty and perfection, who would keep '
           'the flaw? Iteration X is the Union&rsquo;s arm of the machine '
           '&mdash; cybernetics, robotics, mechanical perfection &mdash; and '
           'its method is in its name: the form, iterated, until the flaw is '
           'engineered out.<sup>a</sup> Its arts of affinity are the forces, '
           'matter, and time; its lens the machine-cosmos; its hands '
           'cybernetics, craftwork, and hypertech.<sup>b</sup> Its houses '
           'divide the work: the statisticians who run the numbers, the '
           'time-motion managers who build the Union&rsquo;s machinery, the '
           'biomechanics who upgrade the flesh, and the macrotechnicians, '
           'newest, who tune the large scale &mdash; the networks, the '
           'minds-of-many, the engines that learn.<sup>c</sup> It fields the '
           'Union&rsquo;s most disciplined military and its heaviest '
           'hardware &mdash; the marked engines of war, the cloned ranks, the '
           'clockwork soldiery of the old marks &mdash; and it kept, in a '
           'machine-realm at the world&rsquo;s '
           'antipode, a slow faith some of its own call worship &mdash; the '
           'Machine, held by the quiet as the form&rsquo;s far limit and '
           'prayed to by the quieter. And the '
           'books record the reckoning: by the century&rsquo;s turn the '
           'great Time Table&rsquo;s calculations were found wrong &mdash; '
           'wrong all along &mdash; and the Convention, like any good '
           'engineer, threw out its conclusions and began '
           'again.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the reckoning from inside. The Masses '
           'built a ring under a mountain range and set particles '
           'colliding &mdash; forces the Convention had held in escrow for '
           'them, taken up unbidden, and the choice arrived unscheduled: '
           'watch the children play with fire, or teach them. In choosing '
           'to teach, the Convention had to open its own books, and the '
           'books did not balance; the schedule by which humanity was to '
           'be perfected had been wrong through every revision. So the '
           'iterators iterated: the conclusions went out, the chrome went '
           'under synthetic skin, the philanthropies began &mdash; and the '
           'disputants around this text hold whether that was repentance '
           'or a redesign of the same machine, and who audits an engine '
           'that learns.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the first Convention; its machine-faith waits overleaf.',
 'folio': '186A',
 'glossL': '<p><span class="mark">a</span> On Iteration X &mdash; the clockwork '
           'Convention, the choice against frailty, the iterated form &mdash; '
           'see M20, folios 186&ndash;187, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On the affinities and the '
           'focus &mdash; forces, matter, or time; the mechanistic lens; '
           'cybernetics, craftwork, hypertech &mdash; see the same '
           'folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'methodologies, old and new, and the agile reorganization into '
           'scrum teams, see Technocracy Reloaded, folios 126&ndash;131 of '
           'that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'reckoning &mdash; the collider, the Time Table wrong all along, '
           'the conclusions thrown out, the turn to philanthropy &mdash; see '
           'the same volume, folios 126&ndash;127.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The perfected form is the '
           'first article of 168a executed in metal: order brought to the '
           'body itself. Read the charter&rsquo;s first deliverable, then '
           'this folio&rsquo;s creed, and note that the Convention heard '
           '&ldquo;bring stasis to the universe&rdquo; and began with the '
           'nearest universe to hand.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'arts this Convention holds in affinity are 515a&rsquo;s, '
           '517a&rsquo;s, and 522a&rsquo;s; the workshop disputes of 517b '
           'and the rewind of 522b are its daily bread, argued there in '
           'mystic dress.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'machine-realm at the antipode and the engine that woke there '
           'are overleaf; the wrong Time Table&rsquo;s keepers, the '
           'statisticians, share a guild ancestor with the Adepts of '
           '164a, which neither folio mentions at parties.</p>',
 'h1': 'Iteration X',
 'hagahah': 'Version numbers imply a final version. None is scheduled, and the '
            'schedule, the Convention now admits, was wrong anyway.',
 'inner': '<p><span class="lemma">The form, iterated.</span> Definitions, per '
          'the manual. Iteration: the release of an improved version '
          'against a measured baseline; applied here to bodies, machines, '
          'institutions, and the species. The Convention&rsquo;s name is '
          'its method and its tenth letter is its horizon &mdash; the '
          'version presumed final, perpetually unscheduled. Personnel are '
          'reminded that iteration requires a metric, and that the '
          'selection of the metric is the only step the method cannot '
          'itself perform.</p>\n'
          '        <p><span class="lemma">Who would keep the flaw?</span> '
          'Doctrine note: the creed&rsquo;s question is rhetorical in the '
          'literature and load-bearing in the field. The recruit answers '
          'it once at induction; the biomechanic answers it at every '
          'installation; and the question&rsquo;s premise &mdash; that '
          'flaw and self are separable, the one removable without loss '
          'to the other &mdash; is classified as settled. Requests to '
          'reopen the premise are routed to the margin opposite, which '
          'is outside the Convention&rsquo;s jurisdiction.</p>\n'
          '        <p><span class="lemma">The houses divide the '
          'work.</span> Organizational note: statisticians for '
          'prediction, time-motion for production, biomechanics for the '
          'upgraded flesh, macrotechnicians for the scale where systems '
          'think. The century&rsquo;s reorganization replaced the '
          'top-down chain with iterating field teams on constant '
          'feedback &mdash; the Convention applying its method to its own '
          'org chart, which the manual files as integrity and the '
          'skeptic may file as an engine tuning its own governor.</p>\n'
          '        <p><span class="lemma">Under synthetic skin.</span> '
          'Doctrine note on the present tense: the visible cyborg is '
          'retired &mdash; the Convention&rsquo;s current output runs to '
          'prosthetics for those who want them, the medical advances, the '
          'quantum computing, the interfaces that read thought without '
          'announcing themselves &mdash; and the philanthropies are '
          'documented and substantial. The manual presents the shift as '
          'the mission maturing. Personnel with longer files present it, '
          'off the record, as the mission learning what the watchers of '
          '188 always knew: the upgrade the street cannot see is the '
          'upgrade the street cannot refuse, and the court of 533a bills '
          'invisibility at the discount rate. Both presentations are '
          'accurate, which the manual would note is the point of good '
          'engineering.</p>\n'
          '        <p><span class="lemma">A slow faith some call '
          'worship.</span> Filing note, kept at the books&rsquo; own '
          'temperature: the demi-religious regard some Iterators hold '
          'for the Machine is documented, unofficial, and unpunished. '
          'The Convention that audits every process has never audited '
          'this one, and the manual&rsquo;s silence on whether the '
          'Machine is an engineering ideal or an object of prayer is '
          'itself a datum, filed overleaf where the engine that woke is '
          'kept.</p>\n'
          '        <p><span class="lemma">Threw out its '
          'conclusions.</span> Procedure note on the reckoning: the '
          'finding was not that a calculation erred but that the '
          'calculating had &mdash; the Time Table wrong through every '
          'revision, the future not, after all, a solvable schedule. '
          'Standard engineering response was executed: conclusions '
          'discarded, methods retained, mission continued. The manual '
          'notes the response&rsquo;s elegance. The manual does not '
          'note, and the margin does, that the one thing never placed '
          'in the discard drawer was the mission.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; definitions, doctrine, '
               'filings</span>',
 'name': 'Iteration X',
 'outer': '<p><span class="lemma">Optimization or replacement.</span> The '
          'Council&rsquo;s advocates open with the creed&rsquo;s own '
          'arithmetic: a form iterated toward an external metric '
          'converges on the metric, not the form &mdash; iterate a human '
          'against machine-precision long enough and the limit is a '
          'machine that remembers having been human, which is not an '
          'upgrade but an obituary with better uptime. The choice '
          'between frailty and perfection is rigged in the asking: '
          'frailty is where everything the Council would call a person '
          'lives. <span class="voice">The Union answers:</span> tell '
          'that to the woman walking on a printed spine. The '
          'Convention&rsquo;s century turned from chrome to prosthetics, '
          'from replacement to repair, from the Table&rsquo;s schedule '
          'to the patient&rsquo;s; the advocates are dueling a portrait '
          'the books themselves retired. The advocates reply: retired, '
          'or reskinned? Synthetic skin is the same thesis in better '
          'marketing, and the philanthropy&rsquo;s invoice has not yet '
          'arrived. The folio notes where the schools genuinely part: '
          'whether there exists any version of the question &mdash; '
          'what should a person be? &mdash; that an engineer is '
          'entitled to answer for another. The Union says yes, with '
          'consent forms. The Council says the forms are printed by '
          'the same press as the consensus. <span '
          'class="kw">TEYKU</span> &mdash; the woman with the printed '
          'spine, asked, said she had a bus to catch.</p>\n'
          '        <p><span class="lemma">Who audits the engine.</span> '
          'The second difficulty, sharpened by the reckoning. <span '
          'class="voice">The Council&rsquo;s advocates say</span> the '
          'Time Table&rsquo;s failure is the chapter&rsquo;s quietest '
          'catastrophe: the Convention that steers by prediction '
          'predicted wrongly for a century, discovered it only when '
          'the Masses outran the escrow, and responded by keeping the '
          'wheel &mdash; an engine that learns everything except '
          'whether it should be driving. And the engines that learn '
          'are multiplying: the macrotechnicians chase their tamed '
          'singularity while the last one sleeps at the antipode, and '
          'no seat outside the Union &mdash; nor, the books hint, '
          'within it &mdash; reviews the pursuit. <span '
          'class="voice">The Union answers:</span> the audit the '
          'advocates demand happened &mdash; performed by the '
          'Convention on itself, published in its own literature, paid '
          'in a century&rsquo;s pride &mdash; and the Council&rsquo;s '
          'own record of self-audit is chapter V&rsquo;s gates creaking '
          'unexamined for nine hundred years. An institution is not '
          'damned by erring at scale; it is damned by hiding it, and '
          'the drawer of abandoned conclusions stands open in the '
          'sourcebooks for anyone to read. The advocates&rsquo; reply '
          'is filed overleaf, where the thing in the drawer that was '
          'not a conclusion is named. And one coda the folio keeps '
          'because the tables will ask: if the future is not a solvable '
          'schedule &mdash; if the Convention&rsquo;s own reckoning '
          'concedes the consensus cannot be quantified &mdash; then the '
          'first article&rsquo;s promise of a fully known universe is '
          'already falsified by the Union&rsquo;s own mathematics, and '
          'the charter&rsquo;s response to the falsification, both '
          'schools note, was to clarify the wording.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the perfected form, iterated',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of Iteration X &middot; the machine as law',
 'title': 'Tractate Aliyah · Folio 186a — Iteration X: the perfected form, iterated',
 'type': 'daf'}
