# Folio 188b - Room 101. Verso of the New World Order: the conditioning
# file, deferred here from 607b, per the wod-llm-wiki
# rotes-and-procedures page (M20 pp.605-607) and BoS pp.223-232.
FOLIO = {'bottom': '<p><span class="lemma">On consent before content.</span> This folio is the '
           'binding&rsquo;s heaviest and says so: conditioning run against player '
           'characters is an optional rule in the source and must be optional at '
           'the table &mdash; 384b&rsquo;s tools in full, discussed before the '
           'chronicle begins, never sprung. A table that skips this folio '
           'entirely has used it correctly; a table that uses it owes every '
           'player the exits.</p>\n'
           '        <p><span class="lemma">On the horror&rsquo;s address.</span> '
           'If the machinery enters play, keep the horror where it belongs: on '
           'the institution, never on the victim. The conditioned character is '
           'not a puppet to be laughed at but a person being stolen in '
           'installments, and the scenes that matter are the flickers &mdash; '
           'the old gesture surfacing, the friend&rsquo;s name almost '
           'caught.</p>\n'
           '        <p><span class="lemma">On the way back.</span> The books '
           'price the breaking-free, and the counsel is to make the price a '
           'campaign: five successes is a sentence on paper and a season at '
           'the table &mdash; allies holding the line, the self reassembled '
           'scene by scene. Run the recovery as heroism, for in this '
           'folio&rsquo;s territory it is the only heroism there is.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on consent, address, '
                'and the way back</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The Order&rsquo;s deepest procedure remakes the '
           'mind,</span> and the books print it as an optional rule with its '
           'gravity marked. The reconditioning climbs ten named stages, from '
           'indoctrination through submission, suspicion, ostracism, and '
           'pacifism, then conspiracy, alliance, rejection, devotion &mdash; '
           'and last a reverence the books name with a borrowed sentence '
           'about a man taught at the end to love his warder.<sup>a</sup> Its '
           'opening working sets enlightenment against the subject&rsquo;s '
           'will and three, each success stripping a point of the '
           'will&rsquo;s temporary store; the reinforcing runs as an extended '
           'working of the mind&rsquo;s fourth rank, a day per roll for the '
           'Union&rsquo;s own, two for the Fallen, a week for others, against '
           'the subject&rsquo;s resisting count.<sup>b</sup> The botch ruins '
           'the process outright. The conditioned may be broken free &mdash; '
           'by will or by a working of the mind turned inward, five '
           'successes to the freeing &mdash; or reconditioned in turn by a '
           'rival hand, for the machinery serves whoever operates '
           'it.<sup>c</sup> And the softening clauses are their own '
           'indictment: mundane persuasions lower the working&rsquo;s walls, '
           'gentle or brutal, and a devoted crowd of Sleepers can run the '
           'procedure&rsquo;s weak form with no art at all.<sup>d</sup> So the '
           'folio&rsquo;s law runs, and runs cold: the mind is a working '
           'surface, the working is priced, and the price list is in '
           'print.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS DECLINED to tell this one from inside, and the '
           'binding honors the refusal: no aggada walks the ten stages in '
           'the first person, for some corridors should be mapped and not '
           'toured. Instead, the record: the processors who staff the room '
           'are a house apart, of whom even the gray ranks cannot say '
           'whether they were born, grown, or built; the room&rsquo;s '
           'number is the Order&rsquo;s own joke, borrowed from the '
           'Masses&rsquo; best book about exactly this; and the machinery '
           'is billed, in the Union&rsquo;s ledgers, as a punishment one '
           'grade gentler than erasure. The disputants around this text '
           'hold why the books print the manual at all, and what the '
           'existence of the room does to every sincerity in the '
           'chapter.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the New World Order: the recto keeps the watching, this '
             'side keeps the room, behind the constitution&rsquo;s tools.',
 'folio': '188B',
 'glossL': '<p><span class="mark">a</span> On the ten stages and their names, '
           'and the borrowed closing sentence, see M20, the Book of Magick, '
           'folios 605&ndash;607; the optional-rule marking is the '
           'text&rsquo;s own.</p>\n'
           '        <p><span class="mark">b</span> On the opening working '
           'and the reinforcing &mdash; the walls, the stripping, the '
           'day-two-week clock &mdash; see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'ruining botch, the five-success freeing, and the rival&rsquo;s '
           'reconditioning, see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'mundane enhancements, gentle and brutal, and the Sleeper '
           'cult&rsquo;s weak form, see the same folios; the room, its '
           'processors, and the ledger of punishments are the Book of '
           'Secrets&rsquo;, folios 223&ndash;232 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This is the file 607b '
           'declined to shelve with the casebook, by this binding&rsquo;s '
           'own ruling, and the deferral is the ruling&rsquo;s point: a '
           'working that unmakes persons is not a precedent among '
           'precedents, and the Masoret records the refusal as doctrine.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Read '
           '567b&rsquo;s rebuilding of the student against this page and '
           'feel the floor tilt: the elder manuscript&rsquo;s pedagogy and '
           'the Order&rsquo;s procedure differ in consent, scale, and '
           'paperwork &mdash; and the chapter&rsquo;s honest question is '
           'whether they differ in kind. The wound stays open.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'trauma door of 554a &mdash; torture and conditioning among the '
           'mind&rsquo;s wounds that open into Quiet &mdash; is this '
           'folio&rsquo;s cross-reference in the court&rsquo;s own records: '
           'the room&rsquo;s work and the break inward share a border, '
           'and the books drew it first.</p>',
 'h1': 'Room 101',
 'hagahah': 'The room&rsquo;s number is borrowed from the Masses&rsquo; best '
            'book about it, which the Order read as a manual. The Masses '
            'wrote it as a warning. Both readings are correct, which is the '
            'problem.',
 'inner': '<p><span class="lemma">Ten named stages.</span> Specification, '
          'per the manual, filed at the manual&rsquo;s own temperature: the '
          'ladder runs from first contact to final reverence, each stage a '
          'measurable posture of the subject toward the Union, each '
          'transition a deliverable. The names are administrative and the '
          'administration is the horror: a person&rsquo;s interior life '
          'rendered as a progress bar. The manual notes that the '
          'ladder&rsquo;s length is a feature &mdash; ten stages permit '
          'ten reviews &mdash; and does not note who reviews the '
          'reviewers.</p>\n'
          '        <p><span class="lemma">Against the will and '
          'three.</span> Procedure note on the opening working: the '
          'subject&rsquo;s resistance is priced into the wall &mdash; will '
          'and three &mdash; and the working strips the temporary store '
          'point by point, success by success. The design is attrition, '
          'not conquest: the store refills slowly, the sessions repeat, '
          'and the arithmetic favors whichever party has more calendar. '
          'Institutions always have more calendar. That is what '
          'institutions are.</p>\n'
          '        <p><span class="lemma">A day, two, a week.</span> '
          'Scheduling note: the reinforcing clock runs fastest on the '
          'Union&rsquo;s own &mdash; a day per roll &mdash; slower on the '
          'Fallen, slowest on all others. The manual presents the '
          'gradient as familiarity: the conditioner works quickest on '
          'minds already shaped to the creed. The margin is invited to '
          'read the gradient again, slowly, and notice what it concedes '
          'about the creed.</p>\n'
          '        <p><span class="lemma">Five successes to the '
          'freeing.</span> Recovery note: the way back is priced and '
          'therefore possible &mdash; the subject&rsquo;s own will, or an '
          'ally&rsquo;s art turned to the unbinding, five successes '
          'gathered against the machinery&rsquo;s work. The manual '
          'records without comment that the freeing&rsquo;s wall does '
          'not scale with the conditioning&rsquo;s depth: the door out '
          'costs the same from every stage, which is either an '
          'oversight or the books&rsquo; one act of mercy in these '
          'pages, and the commentary knows which it chooses to '
          'believe.</p>\n'
          '        <p><span class="lemma">No art at all.</span> Closing '
          'note, the specification&rsquo;s widest clause: the weak form '
          'runs on charisma and persistence against a lonely '
          'will &mdash; no enlightenment required, a devoted circle '
          'sufficient. The manual files this under threat assessment '
          'for field reference. The commentary files it where the '
          'reader already has: the room is not a building in a '
          'Construct; it is a recipe, and the recipe&rsquo;s '
          'ingredients are everywhere.</p>\n'
          '        <p><span class="lemma">One grade gentler than '
          'erasure.</span> Ledger note, from the Order&rsquo;s own '
          'books of discipline: the conditioning sits in the '
          'punishment schedule between reassignment and the ending of '
          'the person outright &mdash; a sanction, administered to the '
          'Union&rsquo;s own, for offenses of loyalty rather than of '
          'craft. The manual records the placement without comment, '
          'and the commentary supplies the one the placement '
          'demands: an institution that lists the remaking of a '
          'colleague&rsquo;s mind as a moderate penalty has told its '
          'operatives, in schedule form, what they are to it &mdash; '
          'and every sincere officer in the chapter reads that '
          'schedule at induction, and stays. The staying is the '
          'chapter&rsquo;s deepest datum, and no school owns its '
          'reading.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; specification, procedure, '
               'and the notes between</span>',
 'name': 'Room 101',
 'outer': '<p><span class="lemma">Why print the manual.</span> The '
          'Council&rsquo;s advocates, quietly, for shouting is not '
          'possible on this page: a game that prints the ten stages, the '
          'walls, and the clock has written a torturer&rsquo;s procedural '
          'and sold it as an antagonist&rsquo;s dossier &mdash; and the '
          'optional-rule marking is a fig leaf, for the option printed '
          'is the option normalized. <span class="voice">The '
          'answer</span> &mdash; and here, for once, the Union&rsquo;s '
          'advocates and the Council&rsquo;s stand together &mdash; is '
          'the horror genre&rsquo;s oldest defense, and it holds: the '
          'machinery is printed because the machinery is real. The '
          'Masses&rsquo; own century built these rooms with no '
          'enlightenment at all, and a setting that omitted them would '
          'be lying about what institutions do with unaudited power. '
          'The rules&rsquo; precision is not endorsement but testimony '
          '&mdash; this is how it works, this is what it costs, this is '
          'the door out &mdash; and the fiction that names the '
          'machinery arms the reader the euphemism would have left '
          'naked. The advocates accept the defense and attach the '
          'condition the counsel below enforces: testimony is for '
          'witnesses, and a table that plays the room for fun has '
          'changed genres without telling its players. The defense holds '
          'one more clause, the genre&rsquo;s oldest: the room&rsquo;s '
          'fullest description in all the setting&rsquo;s literature is '
          'the door out, priced and printed, which no real room has '
          'ever posted. The advocates grant the clause its full weight. <span '
          'class="kw">TEYKU</span> &mdash; printed, but the folio keeps '
          'the pages turned face-down.</p>\n'
          '        <p><span class="lemma">What the room does to the '
          'chapter.</span> The last difficulty, and the chapter&rsquo;s '
          'hinge. <span class="voice">The Council&rsquo;s advocates '
          'say</span> the room retroactively poisons every folio behind '
          'it: the sincerity of 168a, the reckonings of 186, the '
          'watcher&rsquo;s drowning conscience &mdash; all of it stands '
          'unverifiable in an institution that can manufacture '
          'conviction, for the idealist officer&rsquo;s testimony is '
          'exactly what the machinery produces. The Union&rsquo;s '
          'sincerity is not disproven; it is worse &mdash; undiagnosable. '
          '<span class="voice">The Union answers,</span> and the answer '
          'is the chapter&rsquo;s bleakest sentence: the room&rsquo;s '
          'existence cuts every way &mdash; the Council&rsquo;s own '
          'converts, the reborn students of 567b, the reformed and the '
          'redeemed of every seat, stand equally shadowed the moment '
          'any faction holds such machinery, and the books put mind-'
          'craft in mystic hands nine folios before they put it in '
          'gray ones. Doubt of that depth devours its wielder&rsquo;s '
          'house too. The advocates reply: then let both houses burn '
          'the rooms. The Union replies: yours first. And the '
          'tractate, which promised honest teykus, files the '
          'exchange without one &mdash; for this dispute does not '
          'stand open; it stands guard, over every page that '
          'follows. The reader will meet it again at 190b&rsquo;s '
          'vats and 194b&rsquo;s unfiled drawer, wearing other coats; '
          'the binding marks the family resemblance here, once, so '
          'the later folios need only nod.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the polemic, joined for once by the '
               'Union &middot; two difficulties</span>',
 'rubric': 'the conditioned mind, under guard',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the room &middot; the remade mind as law',
 'title': 'Tractate Aliyah · Folio 188b — Room 101: the conditioned mind, under guard',
 'type': 'daf'}
