# Folio 188a - The New World Order. Second Convention folio, per the
# wod-llm-wiki new-world-order page (M20 pp.188-189; TR pp.134-143).
FOLIO = {'bottom': '<p><span class="lemma">On the Suit as scene.</span> The Black Suit works '
           'on camera because the books built the image to work on bystanders: '
           'nondescript, procedural, unhurried, already holding your file. Play '
           'the menace administrative &mdash; the Suit never threatens, the Suit '
           'schedules &mdash; and let players discover that politeness from '
           'someone with total information is the genre&rsquo;s coldest '
           'weather.</p>\n'
           '        <p><span class="lemma">On too much information.</span> The '
           'Convention&rsquo;s modern crisis &mdash; drowning in the data it '
           'prayed for &mdash; is a gift to Storytellers: the watchers miss '
           'things now, not for want of eyes but for surplus, and the '
           'players&rsquo; best cover is the noise itself. An NWO antagonist '
           'who cannot find the signal is scarier and truer than an omniscient '
           'one, because he must choose what to believe.</p>\n'
           '        <p><span class="lemma">On paranoia as budget.</span> The '
           'Order spends belief the way other factions spend essence: every '
           'rumor of its omniscience is a working that costs it nothing. Run '
           'the reputation as a character &mdash; sometimes the Suits '
           'genuinely were not there, and the table should never be sure '
           'which times.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on politeness, noise, '
                'and reputation</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The second Convention keeps the managed '
           'narrative.</span> Its premise the books state as the setting&rsquo;s '
           'own: consensus shapes reality, the world is what the Masses '
           'believe it to be &mdash; therefore govern the believing, and the '
           'world is governed.<sup>a</sup> The Order&rsquo;s strategy runs three '
           'prongs: eliminate deviance from the record, consolidate the '
           'Enlightened under discipline, and propagate everywhere the image '
           'of a world safely governed &mdash; and its instruments are '
           'custody of information, the trained watcher, and the conditioned '
           'mind.<sup>b</sup> Its arts of affinity are the mind and the arts '
           'of connection and data; its houses divide the seeing from the '
           'doing: the operatives &mdash; the black suits, gray above them, '
           'white above those &mdash; the ivory tower of the academies, the '
           'watchers of the feeds and lenses, and the quiet houses behind: '
           'the gadget-wrights, the net-riders, and the processors of whom '
           'even the gray ranks know little.<sup>c</sup> And the books record '
           'the Convention&rsquo;s own reckoning: it demanded information, '
           'information, information, and the century delivered too much '
           '&mdash; privacy died, conformity did not arrive, and the '
           'watchers&rsquo; work is now the managing of chaos by hands '
           'trained for the managing of silence &mdash; some of its veterans '
           'renaming themselves, in their own literature, agents of a new '
           'world.<sup>d</sup> So the folio&rsquo;s law runs: whoever '
           'controls the record controls the possible, and the possible, '
           'per 533a, is the tax base of every working in the '
           'binding.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the watcher&rsquo;s day. She reviews, '
           'before her coffee cools, more confessions than the inquisitors '
           'of three centuries extracted with iron &mdash; volunteered, '
           'timestamped, geotagged, adoringly self-filed. Nothing is '
           'hidden from her, and therefore nothing is legible: the '
           'deviant&rsquo;s trace runs somewhere through a torrent of '
           'birthday cakes and grievances, and her art &mdash; her whole '
           'art now &mdash; is deciding, hour by hour and unaudited, which needle in the stack of '
           'needles is the one that bleeds. Her grandmother in the Order '
           'stole secrets. She drowns in donations. The disputants around '
           'this text hold whether stability is mercy, and what the '
           'watcher&rsquo;s flood has done to the watching.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the second Convention; the conditioned mind waits overleaf, '
             'behind the constitution&rsquo;s consent tools.',
 'folio': '188A',
 'glossL': '<p><span class="mark">a</span> On the New World Order &mdash; '
           'consensus governed through belief, information, and '
           'possibility &mdash; see M20, folios 188&ndash;189, whence this '
           'page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the three-pronged '
           'strategy and the preference for covert action, conditioning, '
           'and cultivated paranoia, see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'methodologies &mdash; operatives, ivory tower, watchers, with '
           'the gadget division, the feed, and the processors behind '
           '&mdash; and the ascent of black to gray to white, see '
           'Technocracy Reloaded, folios 134&ndash;139 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'century&rsquo;s reckoning &mdash; information demanded and '
           'oversupplied, the turn to managing chaos &mdash; see the same '
           'volume, folios 135&ndash;136.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> These are the '
           'witness-makers: 533b&rsquo;s census counts what this '
           'Convention curates, and the court of 533a fines against a '
           'street whose expectations the Order landscapes professionally. '
           'The Masoret has waited five chapters to introduce the '
           'gardener.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'mind&rsquo;s own folio is 519a, and the seeming of 519b is '
           'this Convention&rsquo;s daily craft argued in mystic dress; '
           'the weaponized legal name promised by 586b is kept here, in '
           'the watchers&rsquo; drawers.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'processors of whom the gray ranks know little keep the '
           'overleaf: the conditioning file, deferred from 607b by this '
           'binding&rsquo;s own ruling, is opened at 188b under the '
           'Later Authorities&rsquo; guard.</p>',
 'h1': 'The New World Order',
 'hagahah': 'The Order files everything, including this page. Somewhere in the '
            'ivory tower is a marginal note on this marginal note, and the '
            'reviewer has questions.',
 'inner': '<p><span class="lemma">Govern the believing.</span> Doctrine, per '
          'the manual: the Convention&rsquo;s premise is not cynicism but '
          'the setting&rsquo;s physics taken seriously &mdash; if consensus '
          'shapes reality, then narrative is infrastructure, and its '
          'maintenance is a public utility the Masses never voted to '
          'fund. Information custody is the first article of 168a '
          'applied to the medium in which articles exist; personnel are '
          'reminded that the deliverable is a stable world-image, and '
          'that the world&rsquo;s conformity to the image is a separate '
          'department.</p>\n'
          '        <p><span class="lemma">Three prongs.</span> Procedure '
          'note: elimination, consolidation, propagation &mdash; the '
          'record cleansed of deviance, the Enlightened brought under '
          'one discipline, the governed-world image distributed at '
          'saturation. The prongs are concurrent, not sequential, and '
          'the second is prerequisite to nothing: the Order '
          'consolidates its own before all else, which is why its '
          'discipline cases outnumber its field losses in every '
          'audited decade. The manual regards the ratio as vigilance; '
          'the margin may consult the verso for its own view.</p>\n'
          '        <p><span class="lemma">Black, gray, white.</span> '
          'Organizational note: the ascent is styled a purification '
          '&mdash; the black suit&rsquo;s anonymity, the gray&rsquo;s '
          'adaptability, the white&rsquo;s authority &mdash; and the '
          'style is load-bearing: rank in this Convention is measured '
          'by how little of the person remains visible in the office. '
          'The watchers, largest of the houses and mostly unEnlightened, '
          'invert the ladder: maximum seeing, minimum standing, which '
          'the manual files as efficient and the margin may file '
          'otherwise.</p>\n'
          '        <p><span class="lemma">Trained for silence, assigned '
          'to chaos.</span> Reckoning note: the Convention&rsquo;s '
          'twentieth-century doctrine assumed scarcity of information '
          'and built extraction; the twenty-first delivered surplus and '
          'demanded triage. The retraining is documented and partial: '
          'the tools updated faster than the temperament, and the '
          'Order&rsquo;s characteristic modern failure is no longer the '
          'missed secret but the mischosen signal &mdash; a fact its '
          'adversaries exploit and its veterans, renamed agents of a '
          'new world, admit in their own literature.</p>\n'
          '        <p><span class="lemma">Paranoia as instrument.</span> '
          'Filing note, kept deadpan where the books keep it: the '
          'Convention cultivates belief in its own omniscience because '
          'belief tilts reality, and a Masses that assumes it is '
          'watched behaves as if it were &mdash; surveillance achieved '
          'at zero marginal cost. The manual classifies the technique '
          'as subtle, self-funding, and fully compliant with the '
          'second article. The manual does not classify what it does '
          'to the operatives, who also believe it.</p>\n'
          '        <p><span class="lemma">The quiet houses '
          'behind.</span> Organizational appendix: behind the three '
          'field houses stand the support divisions &mdash; the '
          'gadget-wrights who arm the suits, the net-riders formed '
          'when the century&rsquo;s hydra outgrew the old feeds, and '
          'the processors, of whom the manual records one fact and '
          'the ranks record one question. The fact: they staff the '
          'room the verso keeps. The question, asked below gray '
          'clearance and never above a whisper: whether the '
          'processors were born, grown, or built &mdash; and the '
          'manual&rsquo;s failure to answer a personnel question that '
          'simple is, per the commentary&rsquo;s standing method, '
          'itself the filing.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; doctrine, procedure, '
               'filings</span>',
 'name': 'The New World Order',
 'outer': '<p><span class="lemma">Stability as mercy.</span> The '
          'Council&rsquo;s advocates open at the premise: the Order&rsquo;s '
          'entire edifice rests on the claim that the Masses, told the '
          'truth &mdash; that reality is negotiable, that monsters are '
          'real, that belief is load-bearing &mdash; would shatter; '
          'therefore the kind lie, industrially maintained. But the claim '
          'has never been tested and never will be, because the tester '
          'holds the test: the Convention that owns the record gets to '
          'decide what the record shows the Masses can bear, and it has '
          'decided, every year for centuries, that the answer is '
          'nothing. Mercy that forbids the question is appetite in a '
          'gray suit. <span class="voice">The Union answers:</span> the '
          'test runs continuously, and the Council performs it: every '
          'vulgar working before witnesses is a dose of truth '
          'administered to the unconsenting, and the court of 533a '
          'records the result &mdash; the world itself convulses. The '
          'Masses&rsquo; own reality votes for the lie; the Order '
          'merely staffs the polling place. The advocates reply that a '
          'consensus curated for centuries is not a vote but a '
          'confession extracted at scale &mdash; the flock cannot choose '
          'a shepherd it has never been told exists. And there the '
          'chapter&rsquo;s deepest circle closes: the Order&rsquo;s '
          'proof requires the very consensus it manufactures. <span '
          'class="kw">TEYKU</span> &mdash; the Masses were not asked, '
          'which is both schools&rsquo; entire point. The dispute is docketed to reopen the day either school '
          'can produce an unmanaged Masses to consult, and the '
          'watchers, who would have to find one, are not optimistic '
          'on anyone&rsquo;s behalf.</p>\n'
          '        <p><span class="lemma">What the flood did to the '
          'watching.</span> The second difficulty, the Gemara&rsquo;s. '
          '<span class="voice">The Council&rsquo;s advocates say</span> '
          'the drowning watcher is the setting&rsquo;s justice arriving '
          'by irony: the Convention prayed for total information and '
          'was answered, and the answer abolished its craft &mdash; '
          'when everything is recorded, curation becomes belief, triage becomes theology, selection becomes doctrine, and '
          'the Order now runs on exactly the faculty it was built to '
          'replace: judgment, private, unauditable, one watcher&rsquo;s '
          'needle-choice at a time. The masters of consciousness have '
          'become its dependents. <span class="voice">The Union '
          'answers:</span> yes &mdash; and note who says so: the '
          'Convention&rsquo;s own literature, in its own voice, '
          'renaming its veterans for a new world. An institution that '
          'can describe its obsolescence has begun surviving it, and '
          'the Order&rsquo;s pivot from extraction to triage is the '
          'second such reinvention on the record. The advocates '
          'answer that a watcher who chooses what to believe is just '
          'a mage with a badge &mdash; welcome, at long last, to the '
          'argument. The Union does not reply, which the watchers '
          'log, and file, and schedule for later. The folio appends '
          'the practical coda: whichever school holds the table, the '
          'drowning is canon &mdash; the omniscient Order is a rumor '
          'the Order itself maintains, and the chronicle that '
          'remembers this will find the Convention at once weaker '
          'than its reputation and more dangerous, for an '
          'institution choosing its truths chooses yours too &mdash; and '
          'chooses, the advocates append, with tired eyes and a '
          'quota. Both sentences are true on the books&rsquo; own showing.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the managed narrative, and the watchers',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the New World Order &middot; custody as law',
 'title': 'Tractate Aliyah · Folio 188a — The New World Order: the managed narrative, and the watchers',
 'type': 'daf'}
