# Folio 190a - The Progenitors. Third Convention folio, per the
# wod-llm-wiki progenitors page (M20 pp.190-191; TR pp.144-151).
FOLIO = {'bottom': '<p><span class="lemma">On the healer&rsquo;s hands.</span> The Convention '
           'plays best through its clinics: the Progenitor NPC who genuinely '
           'cures &mdash; the regrown organ, the plague stopped &mdash; and whose '
           'invoice arrives later, in fine print. Let players owe the Union '
           'their lives before they learn its ledgers, and the chapter&rsquo;s '
           'whole difficulty sits down at their bedside.</p>\n'
           '        <p><span class="lemma">On the passion.</span> The books call '
           'these the most human of Technocrats &mdash; passionate, curious, '
           'chip-shouldered from centuries as feared pariahs &mdash; and the '
           'register matters: play them warm. A cold Progenitor is a slasher '
           'trope; a warm one, delighted by your recovery and taking notes, is '
           'the Convention the books actually wrote.</p>\n'
           '        <p><span class="lemma">On the shift&rsquo;s witnesses.</span> '
           'The great redirection &mdash; old projects defunded, the vats '
           'decommissioned &mdash; happened inside living memory, and the '
           'Convention&rsquo;s middle ranks remember both regimes. Every '
           'senior Progenitor is a reconstruction-era character: what did she '
           'do before the directive, and who has her old lab notes? The '
           'chronicle&rsquo;s best hooks hang in that closet.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on bedsides, warmth, '
                'and closets</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The third Convention keeps life as an '
           'improvable draft.</span> Its creed the books give in one sentence '
           'of doctrine: gods do not create and destroy life &mdash; scientific '
           'laws do; and its trade is the body of the world &mdash; medicine, '
           'the grown and the cloned, the edited seed, the accelerated '
           'change.<sup>a</sup> Its descent the books trace to the healer of '
           'Kos and his circle, kin at the root to the witches of 162a, '
           'reframed by the centuries of anatomy and the wars; its arts of '
           'affinity are life and the essence that fuels it; its lens the '
           'living creation read as a system, or might-is-right in a lab '
           'coat.<sup>b</sup> Its houses are an academy: the facade-wrights '
           'who grow and alter the Union&rsquo;s bodies, the gene-wrights who '
           'draft organisms whole, the pharmacists whose cures fund the '
           'floor, the applied who make it work in the field, and damage '
           'control, who clean up &mdash; often after their own; rank is '
           'thesis and publication, and the perishing for failure is not '
           'entirely a figure of speech.<sup>c</sup> And the books record the '
           'great shift: with little warning the funding turned, the '
           'created-species vats were decommissioned, the waste-lines cut, '
           'and the Convention reoriented toward protecting the humanity it '
           'had lately been improving upon &mdash; so lately that its newest '
           'recruits do not know what the oldest freezers hold.<sup>d</sup> So '
           'the folio&rsquo;s law runs: the clinic is real, the vat is real, '
           'and the Convention is the argument between them, conducted in '
           'living tissue.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the directive&rsquo;s morning. It arrived '
           'as funding decisions arrive, without thunder: a memorandum from '
           'grants and requisitions, and by quarter&rsquo;s end the long '
           'projects were orphans &mdash; the made species unmade from the '
           'budget, the vat-halls dark, the mercy missions of the old '
           'circle suddenly restaffed. No apology was published, for '
           'institutions do not repent; they reallocate. The elders kept '
           'their heads down and their notebooks; the recruits arrived '
           'bright to a Convention of healers and were told no different. '
           'The disputants around this text hold the healing against the '
           'authorship, and the forgetting against the mercy.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the third Convention; what the vats made waits overleaf.',
 'folio': '190A',
 'glossL': '<p><span class="mark">a</span> On the Progenitors &mdash; the '
           'doctrine of laws over gods, and the trade in life&rsquo;s '
           'sciences &mdash; see M20, folios 190&ndash;191, whence this page '
           'takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the descent from the '
           'Kosian circle, the kinship with the Verbena, and the affinities '
           'and lens, see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'methodologies and the academic ladder &mdash; thesis, '
           'publication, and the perishing &mdash; see M20, folios '
           '190&ndash;191, and Technocracy Reloaded, folios 145&ndash;149 of '
           'that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the great '
           'shift &mdash; the redirection of grants, the decommissioned '
           'constructs, the cut waste-lines, and the recruits kept '
           'unknowing &mdash; see Technocracy Reloaded, folios '
           '144&ndash;145 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The kinship with 162a is the '
           'chapter&rsquo;s tenderest scar: one root, two gardens &mdash; the '
           'witches keeping the cycle, the Kosians editing it &mdash; and '
           'each folio&rsquo;s disputes are the other&rsquo;s read in a '
           'mirror. The Masoret seats the cousins facing.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'life-arts this Convention holds are 516a&rsquo;s, and the '
           'healing of 516b runs through its clinics at scale; the essence '
           'that fuels the vats is 520a&rsquo;s well, drawn industrially.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'directive&rsquo;s unpublished reasons &mdash; the projected '
           'decline, the hungry decades ahead &mdash; are the '
           'statisticians&rsquo; arithmetic of 186a working downstream, '
           'and the Masoret notes the chapter&rsquo;s machinery turning: '
           'one Convention&rsquo;s forecast is another&rsquo;s '
           'reformation.</p>',
 'h1': 'The Progenitors',
 'hagahah': 'First, do no harm; second, define harm; the committee is in '
            'session, has been since Kos, and the minutes are sealed.',
 'inner': '<p><span class="lemma">An improvable draft.</span> Doctrine, per '
          'the manual: life is a system exhibiting design flaws &mdash; '
          'senescence, susceptibility, scarcity &mdash; and flaws in a '
          'system are work orders. The Convention&rsquo;s path to '
          'Enlightenment is the evolution of the biological form; its '
          'object of Control is the purging of design flaws by managed '
          'change. Personnel are reminded that the draft metaphor '
          'assigns humanity an editor, and that the editorship is the '
          'Convention&rsquo;s claim, not its discovery.</p>\n'
          '        <p><span class="lemma">Kin at the root.</span> '
          'Historical note: the shared descent with the witches of 162a '
          'is documented and undenied &mdash; one healing root, split '
          'over the question of whether the garden is tended or '
          'redesigned. The Convention&rsquo;s centuries as feared '
          'pariahs &mdash; graverobbers, vivisectionists, the '
          'anatomists&rsquo; old bad name &mdash; are likewise '
          'documented, and the chip on the institutional shoulder is '
          'load-bearing: a fellowship long accused of monstrosity '
          'learned to answer accusation with results, and the reflex '
          'outlived the accusers.</p>\n'
          '        <p><span class="lemma">Thesis and publication.</span> '
          'Organizational note: the academy&rsquo;s ladder is climbed by '
          'defended research, and the perishing-for-failure clause is '
          'the books&rsquo; own dark joke with a personnel file. The '
          'structure selects for brilliance under review and audits '
          'method more closely than any house in the Union &mdash; and '
          'audits mission, the margin will note, not at all: the ladder '
          'reviews how, never whether.</p>\n'
          '        <p><span class="lemma">The houses in brief.</span> '
          'Organizational note: the facade-wrights grow and alter the '
          'Union&rsquo;s bodies and trade the surplus for '
          'inter-Convention favors; the gene-wrights draft organisms '
          'whole, a bespoke soldier within the year; the pharmacists '
          'fund the floor, their epigenetic remedies sold with a '
          'straight face to the very markets that distrust the '
          'laboratories that made them; the applied make theory work '
          'in soil and field; and damage control answers the '
          'outbreaks, the rogue constructs, and &mdash; the manual&rsquo;s '
          'phrasing preserved &mdash; the Convention&rsquo;s own messes, '
          'a portfolio which has lately included a rising line-item '
          'of walking plagues whose sourcing is a question for '
          'chapter VII&rsquo;s folios. The academy&rsquo;s output is '
          'the Union&rsquo;s entire biological floor, and the floor '
          'holds.</p>\n'
          '        <p><span class="lemma">Without thunder.</span> '
          'Procedure note on the shift: the redirection was executed '
          'through grants and requisitions &mdash; funding as the '
          'Union&rsquo;s true instrument of doctrine &mdash; and its '
          'completeness is measured in the waste-lines cut by more '
          'than half within the decade. The manual records the '
          'mechanism with approval: no purge, no schism, no memo of '
          'confession; the past was not repudiated but defunded, '
          'which is how an institution changes its mind without '
          'admitting it has one.</p>\n'
          '        <p><span class="lemma">Do not know what the freezers '
          'hold.</span> Filing note, flattest available: the '
          'recruits&rsquo; ignorance of the created-species era is '
          'maintained by omission, not falsification &mdash; the '
          'records exist, classified; the curriculum simply does not '
          'route through them. The manual classifies the arrangement '
          'as onboarding efficiency. The manual&rsquo;s classification '
          'is quoted here in full so the margin can weigh it '
          'unparaphrased.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; doctrine, history, '
               'filings</span>',
 'name': 'The Progenitors',
 'outer': '<p><span class="lemma">Healing against authorship.</span> The '
          'Council&rsquo;s advocates open at the bedside: the cure is real '
          '&mdash; the grown organ, the stopped plague, the fed billions '
          '&mdash; and the cure is the argument, for every miracle '
          'performed on a patient who cannot understand it is a clause '
          'added to a contract she never read. The Convention heals at '
          'scale and thereby authors at scale: what a body should be, '
          'how long a life should run, which seeds may grow &mdash; '
          'decided in committee, delivered as medicine, and the '
          'patient&rsquo;s consent procured by the oldest trick there '
          'is: being dying at the time. <span class="voice">The Union '
          'answers:</span> the advocates&rsquo; alternative is the '
          'plague. The witches&rsquo; garden buries its failures under '
          'wildflowers and calls the burying a cycle; the Convention '
          'counts its failures, publishes them to its own ladder, and '
          'feeds twenty billion people while the Council debates the '
          'ethics of the plow. Authorship is not seized &mdash; it is '
          'abandoned by everyone unwilling to hold the pen, and the '
          'sick have never once, in the whole history of the argument, '
          'voted for the debate over the cure. The advocates reply: '
          'ask the made species how the pen votes. And that reply the '
          'recto cannot answer; it is the verso&rsquo;s to keep. '
          '<span class="kw">TEYKU</span> &mdash; held open across the '
          'leaf, where the vats are.</p>\n'
          '        <p><span class="lemma">Forgetting against '
          'mercy.</span> The second difficulty, the Gemara&rsquo;s '
          'morning. <span class="voice">The Council&rsquo;s advocates '
          'say</span> the shift proves the chapter&rsquo;s bleakest '
          'reading: even the Union&rsquo;s repentance is a budget line '
          '&mdash; no confession, no reckoning, the recruits raised '
          'innocent above sealed freezers &mdash; and an institution '
          'that cannot say what it did has not stopped being the '
          'institution that did it; it has only stopped paying for '
          'the department. <span class="voice">The Union '
          'answers:</span> and yet the vats are dark. The advocates '
          'demand the theater of contrition; the Convention performed '
          'the substance &mdash; projects ended, lines cut, mission '
          'rewritten &mdash; and the substance holds whether or not '
          'anyone wept on the record. Institutions do not have souls '
          'to save; they have behaviors to change, and this one '
          'changed. The advocates reply that behaviors defunded can '
          'be refunded, and that a repentance stored as a reversible '
          'memorandum is a threat wearing mercy&rsquo;s coat. Both '
          'schools then turn, together, to the only witnesses with '
          'standing &mdash; and find the freezers sealed, which is '
          'the verso&rsquo;s first sentence. The folio adds the coda '
          'the cousins of 162a would insist on: the witches&rsquo; '
          'garden also keeps graves, and also does not label them '
          '&mdash; the difference, they say, is that a grave admits '
          'what it is, and a freezer is a grave that has kept its '
          'options open. The Union declines to answer the cousins '
          'directly, and the Masoret records the decline: some '
          'kinships are conducted entirely in what is not said at '
          'the funeral.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'life as an improvable draft',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the Progenitors &middot; the clinic as law',
 'title': 'Tractate Aliyah · Folio 190a — The Progenitors: life as an improvable draft',
 'type': 'daf'}
