# Folio 190b - The Vat. Verso of the Progenitors: the created and their
# standing, per the wod-llm-wiki progenitors and technocracy pages (TR
# pp.144-149; BoS pp.227-229).
FOLIO = {'bottom': '<p><span class="lemma">On playing the made.</span> A clone, construct, or '
           'grown agent in the party is the chapter&rsquo;s best character '
           'concept: every session asks the folio&rsquo;s question from inside. '
           'Give the made character one inarguable personhood scene early '
           '&mdash; a preference nobody designed, a joke nobody installed &mdash; '
           'and let the institution&rsquo;s paperwork disagree with what the '
           'table has already seen.</p>\n'
           '        <p><span class="lemma">On the freezer episode.</span> If the '
           'chronicle opens the sealed past, open it as archaeology, not '
           'expos&eacute;: an old facility, a manifest that does not match the '
           'official record, and one survivor &mdash; of whichever kind &mdash; '
           'whose existence is the argument. The horror is quieter and truer '
           'when the discovery implicates the discoverers&rsquo; own '
           'paychecks.</p>\n'
           '        <p><span class="lemma">On the duplication clause.</span> The '
           'punishment that erases an agent and issues a copy is the '
           'setting&rsquo;s cruelest paragraph, and it should be used the way '
           'the books use it: as a rumor, a fear, and at most once &mdash; '
           'confirmed only when the table is ready to ask whether the '
           'returning colleague is the colleague. Some drawers open once per '
           'chronicle.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the made, the dig, '
                'and the copy</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">What the vats made, the ledgers kept:</span> '
           'the Union&rsquo;s bodies have long been grown to order &mdash; the '
           'cloned ranks and lesser suits traded between Conventions as '
           'favors; the enhanced agents; the constructs of the old program, '
           'whole species drafted sentient and put to labor.<sup>a</sup> The '
           'trade in the grown is a currency between Conventions &mdash; '
           'clones exchanged for favors as another house would exchange '
           'funding &mdash; and the waste of the making, in the old years, ran '
           'to the machinists&rsquo; furnaces by the ton, a line the ledgers '
           'cut by more than half within a decade of the shift. The '
           'books say the quiet part in their own voice: the sordid past of '
           'creating sentient kinds as workforce is real, decommissioned, and '
           'withheld from the new intake.<sup>b</sup> The made live under a '
           'made law: the grown agent&rsquo;s lifespan runs shorter, for the '
           'court of 533a taxes even birth when birth is impossible; and the '
           'ledger of punishments includes the paragraph the ranks whisper '
           '&mdash; the agent erased outright and replaced by his own '
           'unenlightened copy, identical in ability, docile by '
           'design.<sup>c</sup> Against this stands the Convention&rsquo;s '
           'present tense, honestly kept: the injection that regrows an '
           'organ in days, the crops that feed billions, the plagues met and '
           'the mercies restaffed &mdash; the same hands, the same vats, '
           'turned.<sup>d</sup> So the verso&rsquo;s law runs: the made are in '
           'the world, the world taxes them for it, and the ledger that '
           'records both is the only party to the question with clean '
           'handwriting.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the manifest. In a decommissioned '
           'facility&rsquo;s intake book, between the reagents and the '
           'glassware, a line: units, viable, forty. No species column, '
           'for the column would have named a decision; no disposition '
           'column, for the disposition was the decommissioning itself. '
           'Forty of something that ate, learned its handlers&rsquo; '
           'shift-schedule, and was viable. The elders who kept the book '
           'kept it accurately, for they were scientists; and accurately '
           'is how we know. The disputants around this text hold the '
           'standing of the made, and whether an institution&rsquo;s '
           'children can indict it.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Progenitors: the recto keeps the clinic, this side '
             'keeps the vats.',
 'folio': '190B',
 'glossL': '<p><span class="mark">a</span> On the grown ranks &mdash; clones, '
           'lesser suits, enhanced agents, and the constructs of the old '
           'program &mdash; see Technocracy Reloaded, folios 144&ndash;147 of '
           'that volume, with M20&rsquo;s Convention folios 190&ndash;191.</p>\n'
           '        <p><span class="mark">b</span> On the sordid past in the '
           'books&rsquo; own words &mdash; sentient species as labor, '
           'decommissioned, unknown to recruits &mdash; see Technocracy '
           'Reloaded, folios 144&ndash;145 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the grown '
           'agent&rsquo;s shortened span under Paradox, and the punishment '
           'of duplication &mdash; erasure and the docile copy &mdash; see '
           'the Book of Secrets, folios 227&ndash;229 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'present tense &mdash; the regrown organ, the engineered '
           'harvests, the restaffed mercies &mdash; see Technocracy '
           'Reloaded, folios 145&ndash;149 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto&rsquo;s TEYKU '
           'arrives here for its answer and finds the freezers sealed: the '
           'authorship dispute&rsquo;s missing witnesses are this '
           'folio&rsquo;s subject, and the two sides of the leaf should be '
           'read in one sitting, as the binding intends.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'court that shortens the clone&rsquo;s years is 533a&rsquo;s, '
           'taxing the impossible birth as it taxes every impossibility; '
           'the deep law is 516a&rsquo;s &mdash; life as pattern &mdash; and '
           'the pattern copied without a soul&rsquo;s consent is that '
           'folio&rsquo;s dispute industrialized.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'erased-and-copied agent is the room of 188b&rsquo;s work taken '
           'to its limit &mdash; the mind remade past the need for a mind '
           '&mdash; and the Masoret files the two paragraphs as one law at '
           'two depths, which neither Convention&rsquo;s manual will '
           'confirm or deny.</p>',
 'h1': 'The Vat',
 'hagahah': 'The manifest said viable. Viability is the vat&rsquo;s whole '
            'theology: it measures everything about a life except whether '
            'anyone asked for it.',
 'inner': '<p><span class="lemma">Grown to order.</span> Inventory, per the '
          'manual: the Union&rsquo;s biological assets include cloned '
          'personnel in standard grades, enhancement recipients, and '
          '&mdash; historically &mdash; designed organisms up to and '
          'including sentient kinds. Production is the facade-wrights&rsquo; '
          'portfolio; allocation runs through inter-Convention favor, the '
          'clone trade being among the Union&rsquo;s stable internal '
          'currencies. The manual&rsquo;s own word for the historical '
          'program&rsquo;s output is workforce, and the manual&rsquo;s '
          'word is preserved here as evidence preserves.</p>\n'
          '        <p><span class="lemma">Taxes even birth.</span> '
          'Actuarial note: the grown agent&rsquo;s shortened span is the '
          'court&rsquo;s standing levy on manufactured life &mdash; the '
          'world, unpersuaded that such a birth is possible, collects '
          'the difference in years. The clause is the chapter&rsquo;s '
          'quietest cruelty: the made pay Paradox for existing, '
          'continuously, in the one currency that cannot be '
          'requisitioned &mdash; and the manual carries the deduction '
          'as a known production cost, which is the sentence the '
          'margin should read twice.</p>\n'
          '        <p><span class="lemma">Docile by design.</span> '
          'Specification note on the duplication paragraph: the '
          'punishment produces a copy of the erased agent &mdash; '
          'abilities retained, enlightenment absent, independence '
          'absent, span shortened &mdash; and issues it back into '
          'service. The procedure is classified as a sanction of last '
          'resort, one grade beside outright erasure in the ledger. '
          'The manual notes the copy&rsquo;s operational equivalence. '
          'The manual does not note, anywhere in its pages, what the '
          'copy is equivalent to, and the omission is the '
          'specification&rsquo;s true content.</p>\n'
          '        <p><span class="lemma">Kept it accurately.</span> '
          'Records note, on the Gemara&rsquo;s manifest: the '
          'Convention&rsquo;s documentation culture &mdash; thesis, '
          'audit, intake book &mdash; preserved precisely the evidence '
          'an institution bent on forgetting would have burned, and '
          'the preservation was not conscience but method: scientists '
          'record. The manual cites the culture as integrity. The '
          'commentary concurs, and adds the corollary the manual '
          'omits: method without mission-review produces perfect '
          'records of unexamined acts, filed by the finest minds of '
          'every generation.</p>\n'
          '        <p><span class="lemma">The same vats, turned.</span> '
          'Present-tense note: the working assets of the old program '
          '&mdash; facilities, techniques, the accumulated craft of '
          'making &mdash; were not destroyed but redirected, and the '
          'harvests and cures of the current mission run on them. The '
          'manual presents the continuity as efficiency. The margin '
          'will observe that it is also the folio&rsquo;s entire '
          'question in mechanical form: whether hands are cleaned by '
          'what they presently hold.</p>\n'
          '        <p><span class="lemma">Traded between '
          'Conventions.</span> Currency note: the clone trade&rsquo;s '
          'unit of account is the favor, and its clearing-house is the '
          'inter-Convention requisition &mdash; a lesser suit for a '
          'satellite window, a Victor for a season of funding &mdash; '
          'and the manual carries the trade under logistics. The '
          'commentary carries it under the folio&rsquo;s question, '
          'restated in accounting: whatever the made are, they are '
          'liquid, and liquidity is the one status no party to the '
          'dispute proposes for persons &mdash; a sentence the manual '
          'would flag as editorializing, and the commentary flags as '
          'arithmetic.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; inventories, '
               'specifications, records</span>',
 'name': 'The Vat',
 'outer': '<p><span class="lemma">The standing of the made.</span> The '
          'Council&rsquo;s advocates put the question the manifest '
          'could not: what were the forty? If persons, the old program '
          'was slavery practiced by the setting&rsquo;s best-documented '
          'institution, and the decommissioning &mdash; the word itself '
          '&mdash; was its second crime. If products, then personhood '
          'in this setting is a license the powerful issue, and every '
          'folio of this binding that speaks of souls is negotiating '
          'with counterfeiters. There is no third box, and the '
          'intake book&rsquo;s missing species column is the '
          'Union&rsquo;s admission that it knew. <span '
          'class="voice">The Union answers,</span> carefully, for its '
          'best people have asked the same question in worse rooms: '
          'the program ended &mdash; ended by the Union&rsquo;s own '
          'hand, defunded before any Council writ compelled it, and '
          'the ending is the only answer an institution can give. As '
          'for standing: the Convention&rsquo;s literature grants the '
          'made their abilities, their training, their operational '
          'personhood entire &mdash; the Union treats its grown agents '
          'as agents. The advocates reply: as agents, yes &mdash; the '
          'one category your ledgers possess. The question was '
          'persons, and your own duplication paragraph answers it: an '
          'institution that can reissue a man docile has told the '
          'court what it thinks a man is. <span '
          'class="kw">TEYKU</span> &mdash; the forty were viable; the '
          'folio can certify nothing further, and grieves it.</p>\n'
          '        <p><span class="lemma">Whether the children can '
          'indict.</span> The second difficulty, pressed home. <span '
          'class="voice">The Council&rsquo;s advocates say</span> the '
          'made are the chapter&rsquo;s verdict walking: every clone '
          'paying the court&rsquo;s birth-tax, every construct in the '
          'old freezers, is testimony the Union manufactured against '
          'itself, and a fellowship judged by its own creations has '
          'received the only judgment that cannot be appealed as '
          'polemic. <span class="voice">The Union answers:</span> then '
          'let the testimony in &mdash; all of it. The made who serve, '
          'choose, rise, and are mourned by their amalgams testify '
          'too; the recto&rsquo;s cures testify; and if the '
          'Council would call the witnesses, it must call the ones '
          'now living, not only the ledger&rsquo;s dead. The advocates '
          'agree, on one condition the Union cannot grant while the '
          'freezers stay sealed: that all the witnesses be called. '
          'And so the folio ends where the chapter&rsquo;s honest '
          'folios end &mdash; the record open, the intake book '
          'preserved, accurately, which is how we know. The folio '
          'grants the last word to neither faction but to the form '
          'itself: a tractate is a machine for keeping questions '
          'alive, and this question, of all the binding holds, is '
          'the one it most owes the courtesy. For the freezers are '
          'patient, the intake book is accurate, and somewhere in the '
          'setting&rsquo;s long night the forty &mdash; or their heirs, '
          'or their absence &mdash; are still viable, which is the only '
          'word the record ever granted them and the one word no '
          'reader of this folio will use carelessly again.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the made, and their standing',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the vat &middot; the made as law',
 'title': 'Tractate Aliyah · Folio 190b — The Vat: the made, and their standing',
 'type': 'daf'}
