# Folio 192a - The Syndicate. Fourth Convention folio, per the
# wod-llm-wiki syndicate page (M20 pp.192-193; TR pp.152-157).
FOLIO = {'bottom': '<p><span class="lemma">On money as screen presence.</span> The Syndicate '
           'antagonist never draws a weapon: he buys the building, the debt, the '
           'landlord, and the players&rsquo; favorite bar, in that order, and '
           'sends a card. Play the Convention as consequences with a good suit '
           '&mdash; the horror is liquidity, and liquidity has no dodge '
           'roll.</p>\n'
           '        <p><span class="lemma">On the wink.</span> Alone among '
           'Conventions, this one admits its work is magick and grins about '
           'it; use the candor. A Syndicate contact who talks shop honestly '
           '&mdash; who calls the Effect an Effect and the fee a fee &mdash; is '
           'disarming, useful, and twice as unsettling when the invoice '
           'arrives, because he never once lied.</p>\n'
           '        <p><span class="lemma">On playing the gangster '
           'wrong.</span> The mob cliché is the Convention&rsquo;s own '
           'camouflage, worn deliberately; a chronicle that stops at the '
           'trope has been managed by its own antagonist. Behind the '
           'enforcers stand the financiers, and behind the financiers the '
           'idea that value is real &mdash; aim the campaign at the idea and '
           'the trope becomes what it is in the books: a front.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on liquidity, candor, '
                'and fronts</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The fourth Convention keeps the priced '
           'real.</span> Its creed the books give as the oldest rule of '
           'power: whoever makes the gold makes the rules; and its deep '
           'doctrine runs past the creed &mdash; money is a lie so powerful '
           'it became universal truth, and value, believed at scale, '
           'generates its own reality.<sup>a</sup> The books name that '
           'generated reality: the Convention&rsquo;s reading of the '
           'essence-art is called Primal Utility &mdash; worth as the measure '
           'of the real &mdash; and its craft, the Art of Desire, works by '
           'the subtle engines: the nudge, the debt, the seduction, the '
           'price discovered to have been paid already.<sup>b</sup> Its '
           'descent is the High Guild&rsquo;s, whose gold cast the '
           'Order&rsquo;s first cannon and hired its first ships; its houses '
           'are a corporation&rsquo;s: the disbursers who hold the '
           'Union&rsquo;s purse and are loved accordingly, the enforcers '
           'whose criminal fronts are the face outsiders meet, the '
           'financiers who tend the global engine, the media house forever '
           'at war with the watchers of 188 over who owns the story, and '
           'the special projects nobody discusses.<sup>c</sup> Alone of the '
           'five it calls its work magick, with a wink the books record '
           '&mdash; its adepts styled magic men &mdash; and alone of the '
           'five it confesses the crisis plainly: near-absolute power has '
           'not bought a commensurate control, and the world&rsquo;s '
           'ledger runs ever more chaotic under management.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the lie that came true. Once, the books say, '
           'value sat in things &mdash; grain, iron, the coin&rsquo;s own '
           'metal &mdash; and the guild that would become the Syndicate '
           'made its discovery not in a vault but in a sentence: that the '
           'promise of the coin outperforms the coin, if enough hands '
           'believe the promise. Everything after is compounding: the '
           'note, the ledger, the market, the derivative of the '
           'derivative &mdash; a tower of agreements standing on no floor '
           'but agreement, taller every century, and the world&rsquo;s '
           'actual bread priced from its upper windows. The Masses call '
           'the tower the economy and believe in it more firmly than in '
           'weather. The disputants around this text hold whether the '
           'tower is a prosperity engine or a hunger with a ledger, and '
           'what the wink is worth.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the fourth Convention; the shareholder heresy waits '
             'overleaf.',
 'folio': '192A',
 'glossL': '<p><span class="mark">a</span> On the Syndicate &mdash; the '
           'gold-and-rules creed, and money as the lie that became truth '
           '&mdash; see M20, folios 192&ndash;193, whence this page takes its '
           'number, and Technocracy Reloaded, folios 152&ndash;153 of that '
           'volume.</p>\n'
           '        <p><span class="mark">b</span> On Primal Utility as the '
           'Convention&rsquo;s reading of the essence-art, and the Art of '
           'Desire with its subtle engines, see the same folios of '
           'both volumes.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the High '
           'Guild descent and the five houses &mdash; disbursements, '
           'enforcers, financiers, media, and the unspoken projects &mdash; '
           'see M20, folios 192&ndash;193, and Technocracy Reloaded, folios '
           '152&ndash;155 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'magic-men wink and the confessed crisis of power without '
           'control, see Technocracy Reloaded, folios 152&ndash;153 of '
           'that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Primal Utility is '
           '520a&rsquo;s well drawn through a different pipe: where the '
           'mystic sees the world&rsquo;s essence, the Syndicate sees its '
           'price, and the two folios disagree about everything except the '
           'flow. The Masoret seats them across the aisle and watches.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'craft of desire is 572a&rsquo;s dealer-country raised to a '
           'Convention, and the fortune-arts it leans on are 514a&rsquo;s; '
           'the media war with 188&rsquo;s watchers is the chapter&rsquo;s '
           'liveliest internal border, patrolled from both sides.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'wink &mdash; the one Convention saying magick aloud &mdash; '
           'should be read against 607a&rsquo;s registers: a faction that '
           'names its workings honestly has surrendered the vocabulary '
           'war the second article commands, and either lost something '
           'or seen through it. The dispute below prices which.</p>',
 'h1': 'The Syndicate',
 'hagahah': 'Everything has a price; the price also has a price; and somewhere '
            'at the bottom of that regress, the books insist, sits something '
            'real. The Syndicate&rsquo;s entire fortune says otherwise.',
 'inner': '<p><span class="lemma">The priced real.</span> Doctrine, per the '
          'manual: the Convention&rsquo;s path to Enlightenment is the '
          'material advancement of the human condition; its object of '
          'Control is commerce and the desires that drive it. Its premise '
          '&mdash; that value is not found but made, and made real by '
          'belief at scale &mdash; is the setting&rsquo;s consensus '
          'doctrine applied to one instrument, and personnel are reminded '
          'that the premise is symmetrical: what belief inflates, belief '
          'can crash.</p>\n'
          '        <p><span class="lemma">Primal Utility.</span> '
          'Terminology note: the essence-art as this Convention reads it '
          '&mdash; the world&rsquo;s fuel perceived as worth, gathered as '
          'investment, spent as liquidity. The reading is licensed, '
          'examined, and unique among the five: no other Convention '
          'renamed one of the nine arts outright, and the renaming is '
          'the Convention&rsquo;s deepest claim &mdash; that the '
          'mystic&rsquo;s sacred essence and the ledger&rsquo;s bottom '
          'line were always one substance, awaiting honest '
          'accounting.</p>\n'
          '        <p><span class="lemma">The subtle engines.</span> '
          'Procedure note on the Art of Desire: the craft works through '
          'wants &mdash; cultivated, priced, and leveraged &mdash; and its '
          'standard forms are social: the introduction, the obligation, '
          'the appetite fed until it steers. Blatant procedures are '
          'classified a last resort, not from scruple but from '
          'economics: a working the street believes costs nothing at '
          'the court, and the Convention did not get rich paying '
          'retail. Its operatives&rsquo; motto-grade rule: never buy '
          'what a debt will rent.</p>\n'
          '        <p><span class="lemma">The gangster front.</span> '
          'Camouflage note: the criminal stereotype the Convention '
          'wears &mdash; the enforcers&rsquo; hollow men, the black '
          'markets it staffs at the lower echelons &mdash; is maintained '
          'deliberately, as misdirection priced like any other asset: '
          'an adversary studying the mob is not studying the central '
          'banks. The manual notes that the front costs reputation and '
          'buys obscurity at favorable rates. The commentary notes the '
          'front&rsquo;s second function, unpriced in the manual: it '
          'gives the Union somewhere to point when the Council asks '
          'where the Syndicate&rsquo;s dirt is kept, and the pointing '
          'has worked for five centuries. Its cost the manual books as '
          'zero; the enforcers, who live in the pointed-at rooms, '
          'book it differently.</p>\n'
          '        <p><span class="lemma">Loved accordingly.</span> '
          'Organizational note: the disbursers hold the Union&rsquo;s '
          'purse-strings and are, per the books, the most internally '
          'despised house in the Technocracy &mdash; a datum the manual '
          'reports as morale information and the commentary files as '
          'structural: the Union runs on requisitions, requisitions run '
          'through the Syndicate, and every Convention&rsquo;s '
          'independence ends at a counter staffed by this one. The '
          'purse is the Union&rsquo;s true chain of command, and '
          'everyone in the pyramid knows it, which is what the '
          'despising is made of.</p>\n'
          '        <p><span class="lemma">The confessed crisis.</span> '
          'Filing note: the Convention&rsquo;s own literature states '
          'that near-absolute power has not yielded commensurate '
          'control &mdash; the engine&rsquo;s outputs grow chaotic, the '
          'theories multiply (infiltration, intractable humanity, a '
          'flawed model), and the house is divided over remedies. The '
          'manual notes the candor&rsquo;s rarity in Union filings. '
          'The commentary notes what the candor is: a solvency '
          'disclosure, made by the one Convention constitutionally '
          'incapable of hiding a bad quarter from itself.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; doctrine, terminology, '
               'filings</span>',
 'name': 'The Syndicate',
 'outer': '<p><span class="lemma">Engine or hunger.</span> The '
          'Council&rsquo;s advocates open at the tower&rsquo;s base: a '
          'reality made of belief can be farmed, and the Syndicate farms '
          'it &mdash; wants manufactured, scarcities curated, the '
          'Masses&rsquo; appetite cultivated like a crop and harvested '
          'as power. Call the tower prosperity if you like; its '
          'foundation is a hunger that must never be fed to fullness, '
          'for a satisfied Masses generates no yield. The Convention '
          'whose craft is desire has an actuarial interest in '
          'dissatisfaction, and the world&rsquo;s ledger reads '
          'accordingly. <span class="voice">The Union answers:</span> '
          'the hunger predates the farmer. Want is the human baseline '
          'the Council&rsquo;s own folios document from every century, '
          'and the Syndicate&rsquo;s engine is the first in history to '
          'feed billions of the wanting on purpose &mdash; the harvests '
          'funded, the plagues bought down, the material floor raised '
          'decade over decade by exactly the machinery under '
          'indictment. Dissatisfaction is not the engine&rsquo;s '
          'product; it is its fuel gauge. The advocates reply: a gauge '
          'the operator profits by keeping on empty. And there the '
          'dispute rests on the books&rsquo; own confession &mdash; '
          'power without commensurate control &mdash; which each school '
          'reads as its proof: the advocates, that hunger has outgrown '
          'its farmer; the Union, that the farmer at least keeps '
          'books. <span class="kw">TEYKU</span> &mdash; the invoice is '
          'in the mail, addressed to everyone.</p>\n'
          '        <p><span class="lemma">What the wink is worth.</span> '
          'The second difficulty, the chapter&rsquo;s strangest. <span '
          'class="voice">The Council&rsquo;s advocates say</span> the '
          'magic-men wink is the most damning candor in the Union: the '
          'Syndicate admits the work is magick &mdash; admits, that is, '
          'that the second article&rsquo;s whole vocabulary war is '
          'theater &mdash; and keeps fighting the war anyway, because '
          'the theater is profitable. The other Conventions believe '
          'their own renaming; this one sells tickets to it. Cynicism '
          'at that altitude is not a flaw in the creed; it is the '
          'creed, unmasked. <span class="voice">The Union '
          'answers:</span> or it is the creed, matured. The wink '
          'concedes what this binding&rsquo;s own chapter XI proved '
          'folio by folio &mdash; that the difference between a '
          'Procedure and a spell is register, not substance &mdash; and '
          'the Convention that can say so aloud while remaining loyal '
          'has achieved the thing the Council keeps demanding of the '
          'Union: self-knowledge. The advocates reply that '
          'self-knowledge without repentance is just better '
          'bookkeeping. The Union replies that repentance without '
          'solvency feeds no one. The folio, noting that both '
          'sentences would look at home in either faction&rsquo;s '
          'scripture, files the wink where the Syndicate would want '
          'it: as an asset, appreciating. One appendix, because the '
          'tables will need it: whichever reading holds, the wink '
          'makes the Syndicate the chapter&rsquo;s best interlocutor '
          '&mdash; the one Convention a Tradition mage can talk shop '
          'with across the war &mdash; and the books&rsquo; canniest '
          'campaigns are built on exactly that conversational '
          'door. Every other Convention must be fought or fled; this '
          'one can be negotiated with, which is more dangerous and '
          'better drama, and the wink is the doorbell.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'value as the measure of the real',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the Syndicate &middot; the ledger as law',
 'title': 'Tractate Aliyah · Folio 192a — The Syndicate: value as the measure of the real',
 'type': 'daf'}
