# Folio 192b - The Ledger. Verso of the Syndicate: the shareholder
# heresy and the purse as power, per the wod-llm-wiki syndicate page
# (TR pp.152-157).
FOLIO = {'bottom': '<p><span class="lemma">On running the correction.</span> The shareholder '
           'theory hands the Storyteller a campaign-scale weather system: read '
           'the chronicle&rsquo;s unrest &mdash; strange consensus shifts, '
           'impossible coincidences trending &mdash; as underserved blocs '
           'demanding returns, and let both factions scramble to interpret the '
           'same storms. A market correction in reality itself is the rare '
           'antagonist that cannot be punched.</p>\n'
           '        <p><span class="lemma">On the heretic&rsquo;s seat.</span> '
           'An idealist Syndicate contact who believes the Masses are '
           'shareholders is the chapter&rsquo;s freshest NPC: loyal to the '
           'Union, convinced its survival requires paying the world its '
           'dividend, and therefore dangerous to everyone above him. Play him '
           'sincere and doomed, or sincere and right; never merely '
           'naive.</p>\n'
           '        <p><span class="lemma">On the purse in play.</span> When '
           'player characters cross the Union, remember which Convention '
           'answers first: not the soldiers &mdash; the funding. Accounts '
           'close, licenses lapse, the chantry&rsquo;s mundane bills triple, '
           'and no working was ever cast. The Syndicate&rsquo;s opening move '
           'is always administrative, and the table should feel the '
           'temperature drop before anyone rolls dice.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on storms, heretics, '
                'and cold</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Within the counting-house a heresy is '
           'kept,</span> and the books print it with its name: that every soul '
           'among the Masses is a shareholder in reality &mdash; each belief a '
           'stake, each cohort of believers a bloc &mdash; and that the '
           'Syndicate sits not as owner but as management, answerable in the '
           'end to the holders it has long preferred to farm.<sup>a</sup> On '
           'this reading the age&rsquo;s chaos is a market correction: blocs '
           'underserved by the managed consensus demanding returns, and the '
           'remedy is not suppression but dividend &mdash; returns compounded '
           'to the world until the crash is averted, a road some whisper '
           'runs toward the mass ascension the Convention was founded '
           'despising.<sup>b</sup> Around the heresy, the orthodox machinery '
           'hums: the purse-strings that discipline five Conventions '
           'without a shot; the gray operations between the legal and the '
           'illegal where the Convention says the real economy lives; the '
           'funded mercies &mdash; climate, plague, the failsafe against '
           'apocalypse &mdash; kept solvent from enlightened self-interest, '
           'for the end of the world is the end of the '
           'market.<sup>c</sup> And the house is divided, the books say '
           'plainly: a hard wing that would rule as feudal lords of a '
           'corporate dark age, and an idealist remnant holding the '
           'heresy&rsquo;s candle.<sup>d</sup> So the verso&rsquo;s law runs: '
           'the Convention that prices everything has found, on its own '
           'books, a debt it may be carrying to the whole world &mdash; and '
           'has not yet decided whether to pay it or restructure.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the heresy argued in the lift between floors. '
           'The elder financier: we own the tower; the Masses rent. The '
           'young analyst: then explain the storms, elder &mdash; the '
           'consensus buckling in districts our models rated docile, the '
           'coincidences trending against our positions. Renters do not '
           'move markets. Shareholders do. The elder, pressing the button '
           'for the highest floor: and if you are right? The analyst: '
           'then we have been embezzling from the owners for five '
           'centuries, and the audit has begun. The books record no '
           'reply; the lift, presumably, arrived. The disputants around '
           'this text hold whether the heresy is discovery or panic, and '
           'what management owes the held.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Syndicate: the recto keeps the tower, this side '
             'keeps the audit.',
 'folio': '192B',
 'glossL': '<p><span class="mark">a</span> On the shareholder theory &mdash; '
           'the Masses as holders of reality, the blocs, management&rsquo;s '
           'answerability &mdash; see Technocracy Reloaded, folio 154 of that '
           'volume, where it is printed as near-heresy and not as '
           'doctrine.</p>\n'
           '        <p><span class="mark">b</span> On the correction reading '
           'of the age&rsquo;s chaos, the compounding returns, and the road '
           'toward a mass ascension long disdained, see the same folio.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'purse&rsquo;s discipline, the gray operations, and the funded '
           'mercies &mdash; climate, health, the failsafe &mdash; see '
           'Technocracy Reloaded, folios 152&ndash;156 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'divided house &mdash; the corporate-feudal wing and the '
           'idealist remnant &mdash; see the same volume, folios '
           '152&ndash;156.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The shareholder heresy is '
           '533b&rsquo;s census wearing a green eyeshade: the witnesses '
           'whose belief prices every working are here discovered to hold '
           'equity in the whole enterprise, and the Masoret notes that the '
           'Syndicate reached by accounting what the Council&rsquo;s '
           'mystics reached by doctrine &mdash; the Sleepers were never '
           'furniture.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'mass ascension the heresy sidles toward is the binding&rsquo;s '
           'title subject, argued at the shaar and wanting still; that the '
           'road might run through a dividend is this folio&rsquo;s own '
           'strange gift to that oldest question.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'purse that disciplines without a shot is the chapter&rsquo;s '
           'quiet answer to 168b&rsquo;s dark Control: whoever the voice '
           'on the highest floor belongs to, the checks clear through '
           'this Convention, and the Masoret files the org chart&rsquo;s '
           'true shape accordingly.</p>',
 'h1': 'The Ledger',
 'hagahah': 'Management&rsquo;s nightmare is not the rival or the regulator '
            'but the shareholder meeting; and reality&rsquo;s, the books '
            'suggest, has been called. Attendance is mandatory and '
            'everyone is a holder of record.',
 'inner': '<p><span class="lemma">A shareholder in reality.</span> Theory '
          'note, per the manual, filed at the theory&rsquo;s own '
          'confidence: the model assigns every member of the Masses a '
          'stake denominated in belief, aggregates stakes into blocs by '
          'shared paradigm, and construes the Consensus as the '
          'portfolio&rsquo;s net position. Management &mdash; the '
          'Syndicate&rsquo;s self-cast role &mdash; curates the portfolio. '
          'The model&rsquo;s heretical clause is its direction of '
          'obligation: management answers to holders, and holders, '
          'sufficiently underserved, replace management. The manual '
          'notes the model remains unadopted. The manual&rsquo;s tense '
          'is doing significant work.</p>\n'
          '        <p><span class="lemma">A market correction.</span> '
          'Diagnostic note: the correction reading treats the '
          'age&rsquo;s disorders &mdash; consensus volatility, '
          'coincidence storms, the ungovernable ledger of the '
          'recto&rsquo;s confession &mdash; as price discovery: blocs '
          'bidding their reality back toward their beliefs. The reading '
          'competes with infiltration and intractability on the '
          'Convention&rsquo;s own books, and outperforms both on one '
          'metric the manual concedes: it predicts the storms&rsquo; '
          'distribution, which the rivals merely lament.</p>\n'
          '        <p><span class="lemma">Compounded to the world.</span> '
          'Remedy note: the heresy&rsquo;s prescription is '
          'ever-compounding returns &mdash; material, narrative, and '
          'believed &mdash; delivered to underserved blocs until the '
          'portfolio stabilizes. The prescription&rsquo;s limit case is '
          'named in the source: a mass ascension, reached not by '
          'enlightening the Masses but by paying them, which would make '
          'the Syndicate the one Convention to arrive at the '
          'Union&rsquo;s stated destination, by the one road the '
          'founders never surveyed.</p>\n'
          '        <p><span class="lemma">Without a shot.</span> '
          'Structural note on the orthodox machinery: the purse '
          'disciplines faster than any tribunal &mdash; requisitions '
          'delayed, budgets trimmed, a Convention&rsquo;s ambitions '
          'repriced overnight &mdash; and the mechanism&rsquo;s beauty, '
          'per the manual, is that it never appears in any ledger of '
          'punishments: nothing was done; funding simply moved. The '
          'commentary flags the mechanism&rsquo;s twin in the '
          'Progenitors&rsquo; great shift, and the pattern: the '
          'Union&rsquo;s deepest governance is fiscal, wordless, and '
          'deniable.</p>\n'
          '        <p><span class="lemma">The divided house.</span> '
          'Personnel note: the hard wing reads the crisis as a mandate '
          'to rule openly &mdash; lords of a corporate age, the Masses '
          'as assets under management in the frankest sense; the '
          'idealist remnant reads it as the audit beginning. The '
          'manual observes that both wings cite the same numbers, '
          'which the commentary files as this chapter&rsquo;s recurring '
          'lesson: inside the Union, every crisis of fact is a war of '
          'interpretation, and the interpretations have armies.</p>\n'
          '        <p><span class="lemma">The gray operations.</span> '
          'Jurisdictional note: between the legal book and the illegal '
          'book the Convention keeps a third, and calls its territory '
          'gray &mdash; the dark exchanges, the digital webwork it '
          'masters more truly than any rival house, the markets that '
          'exist wherever regulation has not yet imagined them. The '
          'manual classifies the gray zone as where the real economy '
          'lives. The commentary notes what the classification '
          'concedes: the Convention&rsquo;s deepest holdings sit '
          'precisely where no bloc of shareholders can see them, '
          'which the heresy&rsquo;s auditors will presumably reach '
          'last, and know it &mdash; the gray books being, on any '
          'reading, where management keeps what it owes.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; theory, diagnostics, '
               'structure</span>',
 'name': 'The Ledger',
 'outer': '<p><span class="lemma">Discovery or panic.</span> The '
          'Council&rsquo;s advocates take the heresy&rsquo;s measure: '
          'when the farmer starts calling the crop his shareholders, '
          'check the weather. The theory arrives precisely as the '
          'engine loses control &mdash; not in the fat centuries but in '
          'the storm &mdash; and its content is the Council&rsquo;s own '
          'oldest teaching (the Sleepers&rsquo; belief is sovereign) '
          'repackaged as an investment thesis by an institution '
          'negotiating terms with its own judgment. Deathbed '
          'conversions are conversions; they are also deathbeds. <span '
          'class="voice">The Union answers:</span> mark the asymmetry '
          'in that sneer. When the Council preaches the sovereignty of '
          'Sleeper belief, it is wisdom; when a Syndicate analyst '
          'derives it from the storm data, it is panic &mdash; as if '
          'truth arrived at through arithmetic counted less than truth '
          'arrived at through incense. The heresy is the chapter&rsquo;s '
          'largest event: a Convention&rsquo;s own methods generating '
          'the Council&rsquo;s conclusion, independently, against '
          'interest. That is not a deathbed conversion; that is '
          'replication, and replication is the only sacrament the '
          'Union keeps. The advocates reply: then act on it &mdash; '
          'open the books, pay the dividend, stand for election to '
          'the board. The Union&rsquo;s answer is the divided house, '
          'which is to say: pending. <span class="kw">TEYKU</span> '
          '&mdash; the audit, both schools agree, has begun; neither '
          'will say aloud who the auditor is.</p>\n'
          '        <p><span class="lemma">What management owes the '
          'held.</span> The second difficulty, and the chapter turning '
          'toward home. <span class="voice">The Council&rsquo;s '
          'advocates say</span> the heresy, honestly followed, '
          'dissolves the Union: management that answers to the '
          'Masses&rsquo; blocs has conceded the sixth article&rsquo;s '
          'shepherd is an employee, and an employee of the flock is '
          'not a shepherd at all &mdash; the whole pyramid inverts, '
          'Control kneeling to the controlled. The remnant&rsquo;s '
          'candle, carried to the end of its corridor, burns the '
          'building down. <span class="voice">The Union answers:</span> '
          'or completes it. Read the founding promise of 168a again '
          '&mdash; protection for the common people, the arts of men '
          'raised over the arts of magick &mdash; and ask whose heresy '
          'this actually is. A Union answerable to the Masses is not '
          'the pyramid inverted; it is the pyramid&rsquo;s original '
          'blueprint, recovered from under five centuries of '
          'renovations. The advocates, for once, do not reply at '
          'once; the two factions&rsquo; founding dreams have been '
          'caught agreeing, and the silence in the record is the '
          'sound of both sides checking the math. The folio files '
          'the moment and moves on quickly, before either side '
          'retracts &mdash; noting only, for the chronicle&rsquo;s use, '
          'that a campaign set in that silence writes itself: the '
          'remnant needs couriers, the hard wing needs the remnant '
          'found, and the players, whatever their faction, are '
          'holding somebody&rsquo;s dividend. And the chapter&rsquo;s '
          'accounting closes on the heresy&rsquo;s quietest implication: '
          'if the Masses hold reality&rsquo;s equity, then the Ascension '
          'War has been, this whole binding long, a proxy fight for '
          'shares neither faction ever owned. Neither school has yet drafted the reply.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the shareholder heresy, and the purse',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the ledger &middot; the audit as law',
 'title': 'Tractate Aliyah · Folio 192b — The Ledger: the shareholder heresy, and the purse',
 'type': 'daf'}
