# Folio 194b - The Unfiled. Verso of the Void Engineers: Threat Null and
# what the patrol will not file, per the wod-llm-wiki void-engineers
# page (TR pp.158-167; Convention Book: Void Engineers Revised).
FOLIO = {'bottom': '<p><span class="lemma">On the mirror as endgame.</span> The corrupted '
           'twin beyond the veil is campaign-final material: reveal it late, '
           'in fragments &mdash; a patrol&rsquo;s wreckage with Union serial '
           'numbers that were never issued, a distress code one revision out of '
           'date &mdash; and let the players assemble the truth the Convention '
           'pays to keep unassembled. The horror is not the thing outside; it '
           'is the org chart it kept.</p>\n'
           '        <p><span class="lemma">On the secret&rsquo;s weight.</span> '
           'A Void Engineer player character who learns of the twin becomes '
           'the folio&rsquo;s dispute in person: disclosure would arm the '
           'Union&rsquo;s enemies and shatter its ranks; silence makes her the '
           'newest clerk of the unfiled. Give the character both letters to '
           'write and no safe address, and the chapter&rsquo;s machinery '
           'closes around one desk.</p>\n'
           '        <p><span class="lemma">On ending the chapter here.</span> '
           'The binding closes the Union&rsquo;s chapter at the border on '
           'purpose: after the charter, the machine, the watchers, the vats, '
           'and the ledger, the last image is a fellowship guarding humanity '
           'from something wearing its own face. Let the table sit with that '
           'before chapter VII&rsquo;s inquisitions begin; the sequence is '
           'the argument.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on fragments, desks, '
                'and endings</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Some files the patrol keeps by not '
           'keeping.</span> The books name the dread one: beyond the veil '
           'stands a corrupted mirror of the Union itself &mdash; its '
           'fortresses, its uniforms, its procedures, bent &mdash; and the '
           'Convention that found it guards the finding as it guards no '
           'other border, for the twin is the one enemy whose existence '
           'indicts the original.<sup>a</sup> Around the great secret, the '
           'lesser unfiled gather: the deep world&rsquo;s hollow country, '
           'which this Convention would seal and the Etherites of 160a '
           'would explore &mdash; two verbs, one door, the chapter&rsquo;s '
           'whole argument in a border dispute; the far patrols&rsquo; '
           'contact logs, holed where holes are policy; and the '
           'renegade&rsquo;s storm, whose full accounting no archive '
           'admits to holding.<sup>b</sup> The keeping has a cost the books '
           'tally in personnel: the hollow-eyed returns, the institute&rsquo;s '
           'quiet intake, the veterans who know what the wreckage&rsquo;s '
           'serial numbers mean and file their reports in the passive '
           'voice.<sup>c</sup> And the Convention keeps one more thing '
           'unfiled, the books imply, because filing it would name a '
           'question: whether the border&rsquo;s far side went wrong on its '
           'own &mdash; or caught something from the near one.<sup>d</sup> So '
           'the chapter&rsquo;s last law runs: every institution in this '
           'binding keeps an unfiled drawer, and the Union&rsquo;s is '
           'simply the one with a fleet.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the wreck with the wrong numbers. A '
           'border cutter found it drifting where nothing drifts: a hull '
           'of Union pattern, crewed by nothing anyone debriefed, its '
           'serial plates stamped in a sequence the quartermasters swear '
           'was never issued. The salvage report exists in two versions. '
           'The long one was filed, reviewed, and reclassified until its '
           'own author lost the clearance to read it. The short one says '
           'debris, recovered; hazard, contained; recommend no further '
           'survey &mdash; and the recommendation, the elders note, is the '
           'only sentence in the Convention&rsquo;s history where the '
           'wanderers recommended not looking. It passed review, '
           'unanimously, which is the part the elders tell last. The disputants around '
           'this text hold what the silence protects, and what it '
           'costs.</p>',
 'chapter': 'Chapter the Sixth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Void Engineers, and the Union&rsquo;s last leaf: '
             'the chapter ends at the border, facing out, and in.',
 'folio': '194B',
 'glossL': '<p><span class="mark">a</span> On the corrupted mirror beyond the '
           'veil &mdash; the Union&rsquo;s dread twin, its secret closely '
           'held &mdash; see Technocracy Reloaded, folios '
           '220&ndash;227 of that volume, with M20, folio 170, and the revised '
           'Convention book of the Void Engineers, folios 16 and '
           '65&ndash;69 of that volume; the tractate names it no further, per '
           'the sources&rsquo; own discretion.</p>\n'
           '        <p><span class="mark">b</span> On the hollow country '
           'contested with the Etherites, and the policy of the holed '
           'logs, see M20, folios 194&ndash;195; the hollow '
           'country&rsquo;s own law is M20, folios 102&ndash;103, and Beyond '
           'the Barriers, folios 91&ndash;99 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'personnel cost &mdash; the returns, the institute, the passive '
           'voice &mdash; see Technocracy Reloaded, folios 158&ndash;163 of '
           'that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the implied question &mdash; corruption native to the far side, or carried &mdash; no source rules; the inference is the tractate&rsquo;s own, drawn from the arrangement of Technocracy Reloaded, folios 220&ndash;227 of that volume, set beside M20, folios 114&ndash;115.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The twin completes the '
           'chapter&rsquo;s mirror-work: 168a opened with the Union as the '
           'Council&rsquo;s reflection, and the chapter closes with the '
           'Union meeting its own &mdash; the Masoret notes that every '
           'faction in this binding eventually funds a border against '
           'itself, and that only this Convention pays in person.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'hollow country&rsquo;s two verbs &mdash; seal and explore '
           '&mdash; restage 160a&rsquo;s whole defection in miniature, and '
           'the Masoret files the border dispute as that folio&rsquo;s '
           'unfinished sentence.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'question this folio leaves unfiled &mdash; native rot or '
           'carried &mdash; is chapter VII&rsquo;s opening question wearing '
           'a spacesuit, and the binding walks there next but one: the Fallen&rsquo;s folio, 224, holds the landward half.</p>',
 'h1': 'The Unfiled',
 'hagahah': 'The wanderers&rsquo; one rule was go and see. The day they '
            'recommended not looking, the Convention learned what every '
            'archivist knows: the heaviest files are the empty '
            'folders.',
 'inner': '<p><span class="lemma">By not keeping.</span> Records doctrine, '
          'per the manual: the Convention distinguishes the classified '
          '&mdash; filed, restricted, auditable &mdash; from the unfiled, '
          'which has no folder to restrict. Classification protects '
          'information from enemies; unfiling protects the institution '
          'from the information. The manual does not contain this '
          'distinction. The commentary&rsquo;s ability to state it '
          'anyway is the distinction&rsquo;s one weakness, and the '
          'margin&rsquo;s whole opening.</p>\n'
          '        <p><span class="lemma">The one enemy whose existence '
          'indicts.</span> Threat note, at the sources&rsquo; own '
          'altitude: every other horror past the veil confirms the '
          'mission &mdash; the dark is dangerous, the border justified. '
          'The twin alone inverts the syllogism: a corrupted Union '
          'wearing Union procedure implies the procedure can corrupt, '
          'and a Convention built on protocols cannot metabolize an '
          'enemy that is a protocol, gone wrong. Hence the unfiling: '
          'not cowardice but triage &mdash; the finding would not '
          'merely frighten the ranks; it would audit them.</p>\n'
          '        <p><span class="lemma">Two verbs, one door.</span> '
          'Border note on the hollow country: the sealing case is the '
          'commandment &mdash; defend from everything outside; the '
          'exploring case is the founding verb the commandment '
          'replaced; and the Etherites at the same door are the '
          'Convention&rsquo;s own discarded answer, embodied and '
          'cheerful. The dispute is administrative on paper and '
          'theological in fact, and the manual&rsquo;s term for the '
          'standoff &mdash; jurisdictional &mdash; is the passive voice '
          'doing its usual work.</p>\n'
          '        <p><span class="lemma">Holes where holes are '
          'policy.</span> Procedure note: the contact logs&rsquo; '
          'redactions follow pattern, and the pattern is the message '
          '&mdash; personnel learn to read the shape of the missing as '
          'fluently as the present, and the Convention&rsquo;s working '
          'epistemology becomes negative space: what we met is what '
          'the log does not say. The manual calls this operational '
          'security. The veterans, per the sources, call it the '
          'passive voice, and file accordingly.</p>\n'
          '        <p><span class="lemma">Or caught something.</span> '
          'The unfiled question, stated once, flatly, as the '
          'commentary&rsquo;s duty: if the twin is native to the far '
          'dark, the border holds meaning; if the twin is the '
          'Union&rsquo;s own reflection returned &mdash; its procedures '
          'carried out, corrupted, and now patrolling back &mdash; then '
          'the border is a mirror&rsquo;s frame, and the Convention '
          'guards humanity from a consequence. The sources decline to '
          'resolve the question. The commentary notes that both '
          'readings assign the same duty tomorrow morning, which is '
          'how the Convention survives holding it.</p>\n'
          '        <p><span class="lemma">The institute&rsquo;s '
          'intake.</span> Personnel appendix, closing the chapter&rsquo;s '
          'books: the sanity division&rsquo;s records are the '
          'Union&rsquo;s most honest ledger &mdash; a running census of '
          'what the mission costs the missionaries, kept by the one '
          'Convention that could not hide it if it tried, since the '
          'wounded come home on its own ships. The manual files the '
          'institute under welfare. The commentary files it under '
          'evidence: an organization&rsquo;s true beliefs are what it '
          'budgets for, and the Union budgets, quietly, perennially, '
          'for the fact that looking outward breaks people &mdash; '
          'which is the nearest thing to a confession six folios of '
          'manuals have produced.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual, and past its edge &middot; records, '
               'thresholds, the question</span>',
 'name': 'The Unfiled',
 'outer': '<p><span class="lemma">What the silence protects.</span> The '
          'Council&rsquo;s advocates close the chapter as they opened it, '
          'at a founding document: the wanderers&rsquo; verb was see, and '
          'the unfiled folder is the verb renounced &mdash; the '
          'Convention that met the Union&rsquo;s reflection chose the '
          'institution over the finding, and thereby joined every '
          'orthodoxy this binding has indicted: the gates of chapter V, '
          'the sealed freezers of 190, the drawer of names at 188. The '
          'silence protects nothing but the org chart; the ranks it '
          'spares are the ranks it lies to; and a border patrolled by '
          'the deceived is weaker, not stronger, for the day the '
          'wreckage drifts home with the wrong numbers showing. <span '
          'class="voice">The Union answers,</span> and for the last '
          'time in the chapter the answer is quiet: yes. The silence '
          'is a wound, self-inflicted, chosen by people who saw the '
          'alternative &mdash; a Union that learns its own procedures '
          'can walk back through the door wearing its face, before it '
          'has any remedy to offer them &mdash; and judged the wound '
          'survivable and the alternative not. The advocates may call '
          'that the institution choosing itself; the choosers call it '
          'triage at the border, made by the only people who have '
          'stood there. The folio does not arbitrate. It notes only '
          'that the chapter&rsquo;s every folio has ended at this same '
          'desk &mdash; the sincere official, the unbearable file, the '
          'two letters &mdash; and that the Union is, finally, that '
          'desk, staffed forever. <span class="kw">TEYKU</span> &mdash; '
          'the long report exists; its author cannot read it; the '
          'binding cannot improve on that sentence.</p>\n'
          '        <p><span class="lemma">What it costs.</span> The '
          'chapter&rsquo;s closing dispute, brief as an epitaph. <span '
          'class="voice">The Council&rsquo;s advocates say</span> the '
          'cost is the Convention&rsquo;s soul on the installment plan: '
          'every unfiled finding buys another hollow-eyed rotation, '
          'another veteran fluent in negative space, and the '
          'institute&rsquo;s intake is the interest schedule. <span '
          'class="voice">The Union answers:</span> the cost is real '
          'and the ledger public &mdash; alone of the five, this '
          'Convention counts its wounded where the Union can read '
          'them &mdash; and a fellowship that pays for its silences in '
          'its own people, knowingly, has at least not outsourced the '
          'bill. The advocates reply that this is the noblest '
          'sentence anyone has said about the Union in six folios, '
          'and that it describes a tragedy. The Union does not '
          'disagree. And the binding, closing the chapter, notes '
          'what six folios of polemic and manual have converged on '
          'without either side conceding: the Union&rsquo;s crimes are '
          'documented, its sincerities are real, its reformers keep '
          'coming, and its drawers stay shut &mdash; all four at once, '
          'which is what an institution is. The Council&rsquo;s advocates do not dispute the definition; '
          'they dispute, to the last leaf, whether anything so '
          'defined should hold the pen that writes the world. On that question the chapter rests its case, and the '
          'binding turns the leaf toward the chapters where the '
          'pen&rsquo;s other claimants wait their turn at the same '
          'bench. The chapter ends.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the polemic, answered quietly &middot; '
               'two difficulties, and the chapter&rsquo;s end</span>',
 'rubric': 'what the patrol will not file',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'concluded &middot; of the unfiled &middot; the silence as law',
 'title': 'Tractate Aliyah · Folio 194b — The Unfiled: what the patrol will not file',
 'type': 'daf'}
