# Folio 194a - The Void Engineers. Fifth Convention folio, per the
# wod-llm-wiki void-engineers page (M20 pp.194-195; TR pp.158-167).
FOLIO = {'bottom': '<p><span class="lemma">On the one shared trait.</span> The books name it '
           'plainly: whatever a Void Engineer is &mdash; clipboard techie, space '
           'marine, dimension-hacker &mdash; the common denominator is courage. '
           'Cast every VE NPC with that spine and the Convention plays itself: '
           'these are the Union&rsquo;s people who volunteered for the dark, and '
           'even their bureaucrats have been somewhere the players have '
           'not.</p>\n'
           '        <p><span class="lemma">On the rivalry played warm.</span> '
           'The Etherite feud is the setting&rsquo;s best frenemy material: two '
           'fellowships in love with the same sky, one filing flight plans, one '
           'refusing on principle. Stage their encounters as family arguments '
           'at the frontier &mdash; rescue first, recriminations after &mdash; '
           'and both factions come out truer than either&rsquo;s '
           'propaganda.</p>\n'
           '        <p><span class="lemma">On the malcontents.</span> The '
           'hollow-eyed veterans with their own sanity division are the '
           'Convention&rsquo;s pastoral question: the Union sends people past '
           'the sky and files what comes back. Give returning characters the '
           'institute&rsquo;s appointment card and let the table decide what '
           'was seen; the folio&rsquo;s horror works best unspecified.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on spines, family, and '
                'appointment cards</span>',
 'center': '<p class="noindent"><span class="dropcap">S</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The fifth Convention keeps the border.</span> '
           'Its charge is everything beyond the veil: the void the books name '
           'it for, charted, and the countries of spirit the Union calls '
           'dimensions, contained; its art of affinity is the spirit-art '
           'renamed Dimensional Science, with the connecting and the forcing '
           'arts beside.<sup>a</sup> Its descent is a marriage of griefs: the '
           'celestial masters who found that heaven above was a lie with a '
           'void behind it, wed to the explorers of earth&rsquo;s far places '
           'when the far places ran out &mdash; wanderers both, agreed on one '
           'commandment: defend humanity from everything outside.<sup>b</sup> '
           'Its houses hold the line: the border corps at the veil, the '
           'earth frontier in the deep places of the world, the '
           'neutralization specialists where something has already crossed, '
           'the pan-dimensional corps in the far dark with spotty success '
           'the books do not varnish, and research-and-execution building '
           'the ships; the Union owes this Convention its horizon '
           'fortresses, its sentinels, and its essence supply.<sup>c</sup> '
           'And two shadows walk its file: the many who come back '
           'hollow-eyed, tended by a sanity institute of the '
           'Convention&rsquo;s own; and the renegade of its ranks whose '
           'stolen spirit-weapon, many sources say, tore the storm that '
           'scarred the age.<sup>d</sup> So the folio&rsquo;s law runs: the '
           'Union&rsquo;s bravest Convention is also its saddest, and both '
           'facts were issued at the same induction.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'OUR TEACHERS TOLD of the two griefs&rsquo; wedding. The '
           'celestial masters had spent centuries climbing toward heaven '
           'and arrived to find no throne, no choir &mdash; a cold that '
           'went on forever, inhabited. The explorers had spent the same '
           'centuries mapping the earth for the glory of knowing it, and '
           'ran out of blank spaces the same decade. Two fellowships '
           'built for outward, standing at the edge of an outward '
           'neither wanted: they married their fleets, renamed the '
           'climb a patrol, and the patrol has not come home since. '
           'For a patrol, unlike a climb, is not the kind of journey '
           'that ends. The '
           'disputants around this text hold what became of the '
           'exploring, and whether a border can be kept by the '
           'heartbroken.</p>',
 'chapter': 'Chapter the Sixth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the fifth Convention; what the patrol will not file waits '
             'overleaf, and the chapter closes there.',
 'folio': '194A',
 'glossL': '<p><span class="mark">a</span> On the Void Engineers &mdash; the '
           'charted void, the contained dimensions, and Dimensional Science '
           'as the spirit-art renamed &mdash; see M20, folios 194&ndash;195, '
           'whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the merged descent '
           '&mdash; the celestial masters&rsquo; discovery, the explorers, '
           'the late marriage, and the one commandment &mdash; see the same '
           'folios and Technocracy Reloaded, folio 158 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'methodologies and the Convention&rsquo;s dues to the Union '
           '&mdash; fortresses, sentinels, essence &mdash; see M20, folios '
           '194&ndash;195, and Technocracy Reloaded, folios 158&ndash;163 '
           'of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'hollow-eyed returns and their institute, and on the renegade, '
           'the stolen weapon, and the storm many sources blame on them, '
           'see the same volumes; the storm itself is the age&rsquo;s '
           'scar, kept where the events of the end-times are kept.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The spirit-art this '
           'Convention licenses is 521a&rsquo;s, and the crossing of 521b '
           'is its daily commute; the countries it patrols are chapter '
           'IV&rsquo;s, folios 89 through 109, wanting, and this folio '
           'posts their border guard in advance.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'rivalry with the Etherites of 160a is the binding&rsquo;s '
           'gentlest war: one seat left the Union rather than deny the '
           'ether, and this Convention stayed and patrols it; the two '
           'folios&rsquo; marginalia have been corresponding in both '
           'directions since chapter V.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'renegade&rsquo;s storm touches every folio that speaks of the '
           'veil&rsquo;s weather, and the avatar-scarring the sources '
           'describe belongs to the events of the end-times, wanting; '
           'the Masoret marks the debt and the address.</p>',
 'h1': 'The Void Engineers',
 'hagahah': 'The map&rsquo;s edge used to say here be dragons; now it says '
            'clearance required. The dragons, for their part, have '
            'noticed the checkpoint.',
 'inner': '<p><span class="lemma">Everything beyond the veil.</span> '
          'Jurisdiction, per the manual: the Convention&rsquo;s writ runs '
          'from the veil outward &mdash; the near countries of spirit, the '
          'far dark, the deep places of the world &mdash; and its path to '
          'Enlightenment is the satisfaction of curiosity at the frontier '
          'of the knowable, paired with an object of Control the manual '
          'states with unusual candor: exposing hidden things, and hiding '
          'things best unseen. Personnel are reminded that the two clauses '
          'are one job, and that the second is the one with a '
          'clearance level.</p>\n'
          '        <p><span class="lemma">Dimensional Science.</span> '
          'Terminology note: the spirit-art relicensed &mdash; the '
          'shaman&rsquo;s crossing instrumented, the umbra renamed in '
          'coordinates. The renaming is the second article working at '
          'the frontier: a crew that phases through the veil on a '
          'quantum protocol pays less at the court than one that walks '
          'through on a drum, and the Convention&rsquo;s ships are, '
          'among their other functions, the largest witness-management '
          'devices ever built.</p>\n'
          '        <p><span class="lemma">Spotty success.</span> '
          'Assessment note, kept at the books&rsquo; own temperature: '
          'the pan-dimensional corps&rsquo; record against the far '
          'dark&rsquo;s inhabitants is described in the source as '
          'spotty, and the manual declines to improve the adjective. '
          'The Convention that owes the Union its fortresses and its '
          'essence also owes it the age&rsquo;s honest casualty lists, '
          'and files them; courage, the shared trait, is not a '
          'performance metric but a hiring requirement.</p>\n'
          '        <p><span class="lemma">Hollow-eyed.</span> Personnel '
          'note: the off-world rotations return a measurable fraction '
          'of staff altered &mdash; the manual&rsquo;s word is '
          'malcontents; the institute&rsquo;s intake forms are more '
          'careful &mdash; and the Convention maintains, alone in the '
          'Union, a dedicated sanity division for its own. The '
          'commentary notes what the institute&rsquo;s existence '
          'concedes: the border&rsquo;s far side is not empty, the work '
          'of looking at it has a dosage, and the Convention has been '
          'measuring the dose since before the Masses had a word for '
          'trauma.</p>\n'
          '        <p><span class="lemma">Fortresses, sentinels, '
          'essence.</span> Logistics note: the Convention&rsquo;s dues to '
          'the Union are structural &mdash; the horizon fortresses that '
          'anchor the far holdings, the sentinel constellations that '
          'watch the veil, and the essence supply lines on which every '
          'Convention&rsquo;s heavy work runs. The manual presents the '
          'portfolio as service. The commentary presents its corollary: '
          'the Union&rsquo;s whole extramural existence rides on the '
          'Convention it trusts least with a secret and taxes hardest '
          'in personnel, an arrangement whose stability the manual '
          'attributes to professionalism and the margin to the fact '
          'that wanderers do not unionize.</p>\n'
          '        <p><span class="lemma">The renegade.</span> Incident '
          'note, filed at the sources&rsquo; own confidence: a weapon of '
          'the Convention&rsquo;s design, stolen by one of its own and '
          'discharged beyond the veil, is blamed by many accounts for '
          'the storm that scarred the age&rsquo;s crossings. The '
          'Convention&rsquo;s losses in the aftermath were material and '
          'reputational, and its manuals have carried a new appendix '
          'since: on the securing of instruments whose test range is '
          'everywhere. The margin holds what the appendix does not '
          'say.</p>',
 'inner_head': 'Standard Commentary<span class="comm-sub">the inner commentary '
               '&middot; per the manual &middot; jurisdiction, assessments, '
               'incidents</span>',
 'name': 'The Void Engineers',
 'outer': '<p><span class="lemma">What became of the exploring.</span> The '
          'Council&rsquo;s advocates open gently, for this Convention is '
          'the one they almost love: the wanderers were the Union&rsquo;s '
          'best self &mdash; curiosity with courage, the only Convention '
          'whose founding verb was go and see &mdash; and the border ate '
          'them. Explorers became guards; the survey became a patrol; '
          'the one commandment &mdash; defend humanity from everything '
          'outside &mdash; quietly replaced a better one, and the books&rsquo; '
          'own phrase for the change is the folio&rsquo;s indictment: '
          'they seal what the curious would open, and hide things best '
          'unseen, a curator&rsquo;s phrase in a jailer&rsquo;s mouth. '
          '<span class="voice">The Union answers:</span> the advocates '
          'romanticize a frontier they have never stood. The exploring '
          'did not die; it was triaged &mdash; by casualty lists, by '
          'the far dark&rsquo;s actual inhabitants, by what the '
          'celestial masters found where the choir should have been. '
          'The Convention still goes and sees; it has simply learned, '
          'at rates the institute tallies, that some of what it sees '
          'looks back. A border kept by the curious is the only kind '
          'that holds, and the Council&rsquo;s own spirit-masters ward '
          'their circles before they call. The advocates reply: a '
          'circle is not a checkpoint, and warding is not '
          'jurisdiction. The Union replies: at scale, it is nothing '
          'else. <span class="kw">TEYKU</span> &mdash; the patrol has '
          'not come home to answer.</p>\n'
          '        <p><span class="lemma">A border kept by the '
          'heartbroken.</span> The second difficulty, the '
          'Gemara&rsquo;s. <span class="voice">The Council&rsquo;s '
          'advocates say</span> the wedding of griefs explains the '
          'Convention and disqualifies it: a fellowship that climbed '
          'to heaven and found the void has an unhealed wound where '
          'its cosmology was, and humanity&rsquo;s border should not '
          'be staffed by the bereaved &mdash; grief generalizes, and a '
          'guard who has lost heaven sees invaders in every light '
          'past the wire. <span class="voice">The Union answers:</span> '
          'who else? The unbereaved are the ones who have not '
          'looked. Every seat in the Council that has genuinely '
          'crossed the veil keeps its own institute by other names '
          '&mdash; the dreamspeakers&rsquo; long silences, the '
          'death-scholars&rsquo; watches &mdash; and the folio of Quiet '
          'stands in this binding because looking costs everyone. The '
          'Convention&rsquo;s distinction is not that its people break; '
          'it is that it budgets for them, openly, in the one ledger '
          'the Union keeps with something like tenderness. The '
          'advocates concede the tenderness and keep the question, '
          'for it is the chapter&rsquo;s own: what the Union does to '
          'the people who do its believing. The verso holds the '
          'part of the answer nobody files &mdash; and the folio, '
          'closing, notes what the two disputes share: both are '
          'arguments about whether an institution can love the '
          'world on the world&rsquo;s behalf, and the border is '
          'where that question stops being rhetorical and starts '
          'carrying a sidearm. The Convention, asked, holsters the question and files the '
          'flight plan, which is its entire character in one motion.</p>',
 'outer_head': 'The Council&rsquo;s Objections<span class="comm-sub">the outer '
               'commentary &middot; the Traditions&rsquo; polemic, with the '
               'Union answering &middot; two difficulties</span>',
 'rubric': 'the border, and its keepers',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Sixth: The Union, '
             'continued &middot; of the Void Engineers &middot; the frontier as law',
 'title': 'Tractate Aliyah · Folio 194a — The Void Engineers: the border, and its keepers',
 'type': 'daf'}
