# Folio 197a - The Silent Alliance. Chapter VII opens: the Disparate
# compact, per the wod-llm-wiki disparate-alliance page (M20 pp.196-223;
# Forbidden and Forgotten Orders pp.5-13; Book of Secrets pp.233-240).
FOLIO = {'bottom': '<p><span class="lemma">On chronicles of the crafts.</span> The '
           'alliance is the line&rsquo;s best underdog frame: a party drawn '
           'from two or three crafts inherits mutual defense, mutual '
           'suspicion, and a war they cannot fight in the open &mdash; which '
           'is a campaign engine with no assembly required. Run the '
           'compact&rsquo;s frailty honestly: every session should feel like '
           'the experiment might not hold.</p>\n'
           '        <p><span class="lemma">On crafts without tokens.</span> '
           'Each craft is a whole tradition&rsquo;s depth in a smaller room: '
           'give it interiority &mdash; its own quarrels, its own bad '
           'decades, members who embarrass it &mdash; and never reduce it to '
           'its aesthetic. The folio&rsquo;s counsel is structural: write the '
           'craft&rsquo;s NPC roster before its look, and the look will '
           'behave.</p>\n'
           '        <p><span class="lemma">On the menu of histories.</span> '
           'The sources offer the alliance&rsquo;s origin as options, not '
           'settled record &mdash; the purge that did or did not happen, the '
           'fraud who did or did not lead the young to ruin &mdash; and the '
           'counsel is to choose deliberately and early: which telling is '
           'true in the chronicle decides who owes whom an apology, and '
           'that ledger is half the chapter&rsquo;s drama.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on underdogs, interiors, '
                'and chosen histories</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The refusers made a compact.</span> The '
           'crafts that would not take a seat &mdash; not at the nine '
           'chairs, not at the Union&rsquo;s table &mdash; were reported '
           'dead by both great houses, and went everywhere instead; in '
           'the last age the scattered banded quietly together, and the '
           'law names the result the <span class="term">Disparate '
           'Alliance</span>, a name its members chose for its '
           'sarcasm.<sup>a</sup> Its law is thin on purpose: mutual '
           'defense, secrecy, and membership by craft &mdash; each sect '
           'self-governed, no protocols, no central seat, no shared '
           'doctrine of the summit; the compact binds fellowships, '
           'never souls.<sup>b</sup> Its conviction is not thin: several '
           'of the allies hold that the Union is a glove on the '
           'Beast&rsquo;s hand &mdash; the adversary of the next folio '
           'wearing the adversary of chapter VI &mdash; and whether or '
           'not the charge is true, the belief built the '
           'compact.<sup>c</sup> And its war is a whisper: too small to '
           'meet the master head-on, the alliance wears him down from '
           'inside &mdash; sabotage, subversion, misdirection, exposure '
           '&mdash; while its own name stays out of the histories.<sup>d</sup> So the compact&rsquo;s law runs: many crafts, one refusal, and a treaty whose first clause is that nobody signs anything.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear how the solitary joined hands. For centuries '
           'each craft kept its own country and its own grief &mdash; '
           'the mystic kings of one continent, the wish-smiths of '
           'another, the alchemists the nine chairs still blame, the '
           'children in black who never got a chair to refuse &mdash; '
           'and solitude was doctrine, for company had cost each of '
           'them dearly at least once. What ended the solitude the '
           'tellings dispute: a purge that swept the scattered like a '
           'drift-net, say some; the rumor of one, say others, doing '
           'the same work cheaper. However it began, the survivors '
           'reasoned alike: whatever hunts us does not check '
           'affiliation. Five fellowships joined first; others came '
           'wary, in tiers, some standing in the doorway to this day &mdash; and the doorway, the tellings agree, is the compact&rsquo;s most crowded room. '
           'The disputants around this text hold whether a compact is '
           'a Council in denial, and whether hiding is a war '
           'footing.</p>',
 'chapter': 'Chapter the Seventh',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter VII opens: the compact here, its courts overleaf, the '
             'Fallen at 224, and the Mad at 234.',
 'folio': '197A',
 'glossL': '<p><span class="mark">a</span> On the crafts, their refusals, '
           'their reported death and actual dispersal, and the '
           'alliance&rsquo;s sarcastic name, see M20, folios '
           '196&ndash;223, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the thin law &mdash; '
           'mutual defense, secrecy, self-governance, no shared summit '
           '&mdash; see the same folios, and Forbidden and Forgotten '
           'Orders, folios 5&ndash;13 of that volume, with the '
           'commitment tiers.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'binding conviction &mdash; the Union as the Beast&rsquo;s '
           'glove &mdash; see M20, folios 196&ndash;223; the charge is '
           'the setting&rsquo;s open question and is filed here at the '
           'believers&rsquo; own confidence.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'whisper war and the menu of origin tellings, see Forbidden '
           'and Forgotten Orders, folios 6&ndash;10 of that volume, '
           'which offers the histories as options and says so.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is 3b&rsquo;s '
           'promise kept: the unseated answer argued the case in the '
           'abstract, and the compact here is the case walking; the '
           'empty chairs of that page and the refused chairs of this '
           'one should be read in one sitting.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'convocation the crafts declined is 2a&rsquo;s chamber, and '
           'the threshold cases of chapter V &mdash; the society that '
           'turned back at 154b, the houses that went in and half '
           'regret it &mdash; bracket this folio from the seated '
           'side.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'glove charge is tried nowhere in this binding: the Union '
           'answers for itself in chapter VI, the Beast is arraigned '
           'at 224, and the margin keeps the accusation where the '
           'sources keep it &mdash; standing, unproven, and '
           'load-bearing.</p>',
 'h1': 'The Silent Alliance',
 'hagahah': 'Nine seats taught the crafts one lesson: bring your own '
            'chair.',
 'inner': '<p><span class="lemma">By craft, not seat.</span> The '
          'membership clause&rsquo;s plain sense: the unit of the '
          'compact is the fellowship entire &mdash; a craft joins or '
          'stands apart as itself, governing itself, keeping its own '
          'law and gods and grudges &mdash; and no individual holds '
          'alliance rank, for there is no rank to hold. Five '
          'fellowships form the foundation and others came after, '
          'and the sources sort the whole by investment: those who '
          'staked their future on the experiment and shepherd it, '
          'those giving it a fair shake with old blood unforgotten, '
          'and those standing at the edges expecting it to fail '
          '&mdash; a taxonomy of trust the chronicle should steal '
          'whole.</p>\n'
          '        <p><span class="lemma">Secrecy, the strength and '
          'the wound.</span> The second clause&rsquo;s plain sense: '
          'the alliance&rsquo;s one weapon is that neither great '
          'house believes it exists, and the price is everything '
          'secrecy costs &mdash; no open recruitment, no standing '
          'structure, no redress in any court but its own. The '
          'law&rsquo;s own commentators concede the wound: a stable '
          'frame is the thing the compact most needs and least '
          'possesses, the gulfs between its members being what '
          'they are &mdash; millennialist knights, pagan sisters, '
          'imperial dragons, wish-smiths &mdash; and the margin will '
          'press whether a frame that thin can hold a war that '
          'long.</p>\n'
          '        <p><span class="lemma">The conviction, at its '
          'own confidence.</span> The third clause&rsquo;s plain '
          'sense, handled with the binding&rsquo;s gloves: some '
          'allies believe the Union is worn by the Beast as a '
          'glove is worn, and the folio files the belief as '
          'belief &mdash; unproven in the sources, denied by its '
          'object, and sufficient regardless, for shared histories '
          'of conquest and betrayal wanted only a name for the '
          'enemy. The clause teaches the chronicle&rsquo;s subtlest '
          'lesson: a compact does not need a true accusation, '
          'only a believed one, and the difference is a fuse laid '
          'through every later folio.</p>\n'
          '        <p><span class="lemma">The hands-off '
          'registers.</span> The protectorate custom, plainly: an '
          'ally may declare a people under its protection, and '
          'the compact&rsquo;s working protocol is bare courtesy '
          '&mdash; if a fellowship has said hands off, keep hands '
          'off unless harmed first. The grand versions failed, '
          'the sources admit &mdash; no one craft may claim half '
          'the world &mdash; and the surviving custom is the small '
          'one, which works because it asks little and shames much; and the two allies who agree on almost nothing else enforce it together, which the sources note as the custom&rsquo;s quiet miracle.</p>\n'
          '        <p><span class="lemma">The whisper war&rsquo;s '
          'arsenal.</span> The method clause&rsquo;s plain sense: '
          'the alliance fights as the small fight the large &mdash; '
          'the operation spoiled from inside, the funder '
          'misdirected, the atrocity exposed to the one audience '
          'that will punish it &mdash; and its deepest reserves are '
          'not martial at all: faith and the loyal poor, old '
          'gold in deep cellars, courts and clubs and streets, '
          'the affections of everyone the great houses '
          'overlooked. The folio&rsquo;s accounting is the '
          'sources&rsquo;: the overlooked now outnumber the '
          'overlookers, and if the compact holds, it may set '
          'terms.</p>',
 'inner_head': 'On the Compact<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the members, the secrecy, and the '
               'whisper war</span>',
 'name': 'The Silent Alliance',
 'outer': '<p><span class="lemma">A Council in denial.</span> The '
          'absorption dispute. <span class="voice">Some say</span> the '
          'compact is the ninefold frame reinvented by people who '
          'swore they never would: it keeps courts, it lists '
          'offenses, it appoints officers with swords &mdash; give it '
          'a century and it will have seats, and the crafts will '
          'have become the thing their grandmothers refused, '
          'proving the nine chairs right about everything except '
          'the upholstery. <span class="voice">Others say</span> the '
          'differences are the whole point and load-bearing: no '
          'shared doctrine of the summit, no standing court '
          '&mdash; justice convened per case and dissolved after '
          '&mdash; no seat that outranks a fellowship, and a name '
          'chosen to mock the very idea of being a Council; a '
          'scaffold is not a temple because you can take a '
          'scaffold down. The first school answers that every '
          'temple began as a scaffold somebody forgot to take '
          'down. The second answers that this is why the '
          'compact&rsquo;s architects built the forgetting in: '
          'structures that dissolve by default die of neglect, '
          'not of empire. The stakes are 3b&rsquo;s question made '
          'flesh &mdash; whether refusing the frame is a doctrine '
          'or a delay &mdash; and the folio notes which way the '
          'evidence has moved: the compact has already grown '
          'offices its founders swore off, and has already '
          'dissolved bodies a Council would have kept. <span '
          'class="kw">TEYKU</span> &mdash; ask again in a century, '
          'if it has a name by then.</p>\n'
          '        <p><span class="lemma">Whether hiding is a war '
          'footing.</span> The posture dispute. <span '
          'class="voice">Some say</span> the whisper war is the '
          'only war the small can win and the compact fights it '
          'superbly: the master worn down from inside loses to '
          'no visible enemy, and the crafts&rsquo; centuries of '
          'surviving unseen are exactly the drill for it; to '
          'stand up and be counted is to stand up and be '
          'counted by the artillery. <span class="voice">Others '
          'say</span> hiding is dying slowly and calling it '
          'strategy: a war no one knows you are fighting wins '
          'you nothing anyone must honor &mdash; no treaty, no '
          'seat, no history &mdash; and the young of every craft '
          'bleed for a victory that will be booked, if it '
          'comes, to somebody else&rsquo;s account. The first '
          'school answers that the dead of the visible wars '
          'would take that trade. The second answers that the '
          'crafts have been taking that trade for five '
          'centuries and are still described, in every history '
          'both great houses print, as extinct &mdash; and asks '
          'how many more won wars the alliance can survive. '
          'The folio files the girsa unharmonized and hands '
          'the chronicle the dial: how loud the compact dares '
          'to be is the campaign&rsquo;s own throttle, and the sources, deliberately, refuse to set it. One rider both schools sign: whatever the volume, the compact&rsquo;s young must be told the war exists &mdash; a fellowship that hides its war from its own children, the teachers ruled, has chosen not quiet but sleep, and sleep is the other side&rsquo;s whole product.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the frame, and the volume</span>',
 'rubric': 'the compact of the refused',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen &middot; of the Disparate compact',
 'title': 'Tractate Aliyah · Folio 197a — The Silent Alliance: the compact of the refused',
 'type': 'daf'}
