# Folio 197b - The Wise Hearts. The alliance's justice, per the
# wod-llm-wiki disparate-alliance page (Book of Secrets pp.233-240).
FOLIO = {'bottom': '<p><span class="lemma">On trying a case at the table.</span> An '
           'Adjudication Court is a ready-made session: the party as '
           'advocates, the eight seats to fill, the verdict to live with. '
           'Because the court dissolves afterward, the chronicle keeps the '
           'consequences without inheriting a supreme bench &mdash; run one '
           'trial a season and the compact&rsquo;s law will feel real without '
           'ever feeling settled.</p>\n'
           '        <p><span class="lemma">On the weak seat.</span> The '
           'statute that one judge per fellowship must be young or weak is '
           'the folio&rsquo;s best NPC generator: the apprentice seated '
           'beside the elders, obliged to judge them. Give that seat a '
           'face and a doubt, and the trial scene writes itself &mdash; the '
           'law put a child at the bench on purpose, and the purpose is '
           'drama as much as justice.</p>\n'
           '        <p><span class="lemma">On severity and consent.</span> '
           'The punishments on this leaf run dark, and the counsel is '
           '384b&rsquo;s twice over: agree with the table how dark the '
           'chronicle&rsquo;s justice runs before any player faces it, and '
           'keep the worst sentences offscreen unless the table asks '
           'otherwise. The law can be harsh and the session still '
           'kind.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on trials, benches, '
                'and dark run gently</span>',
 'center': '<p class="noindent"><span class="dropcap">W</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The compact keeps no court,</span> and '
           'therefore keeps courts: when a grave matter crosses craft '
           'lines, a tribunal is convened for the case and dissolved '
           'after &mdash; each fellowship lends eight trusted souls, '
           'called <span class="term">Wise Hearts</span>, and the '
           'statute requires at least one of each eight be young, or '
           'weak, or both, that justice never favor the '
           'strong.<sup>a</sup> Three advocates are seated &mdash; for '
           'the accused, for the wronged, for the compact itself, the '
           'first two drawn from fellowships not party to the quarrel '
           '&mdash; and they vet the Hearts until eight judges sit; '
           'five of eight convict, five of eight sentence, and no '
           'appeal lies from either.<sup>b</sup> The offenses the '
           'compact tries itself are few and named: corruption &mdash; '
           'any dealing with the Fallen that is not killing them '
           '&mdash; betrayal, murder of allies, violation of a '
           'protected people, and the breakings of faith an unstable '
           'union cannot survive.<sup>c</sup> Sentence is carried out '
           'by an office called the <span class="term">Sword of the '
           'Law</span>, three kept by every fellowship, sworn to '
           'execute with neither mercy nor cruelty &mdash; and the '
           'scale runs from reparation of two-thirds of all the '
           'offender owns, through torments rare and enumerated, to '
           'death; the compact keeps no soul-unmaking, though one '
           'penalty stands on its books unused: the imprisonment of '
           'a soul in a jar.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear why the court dissolves. The architects of '
           'the compact had all seen standing benches before &mdash; '
           'seen them captured, seen them staffed by the same names '
           'for a century, seen justice become a district of '
           'politics with better robes. So they built a court that '
           'dies at verdict: no bench to capture, no docket to '
           'inherit, no judge whose career is judging. The teachers '
           'preserved the design&rsquo;s cost beside its cleverness: '
           'a court convened per case remembers nothing, so every '
           'trial argues first principles again, and the '
           'compact&rsquo;s law grows no wiser with age &mdash; which '
           'one architect called the price, and another called the '
           'point. The disputants around this text hold whether '
           'severity is justice or fear, and what a law never used '
           'is for.</p>',
 'chapter': 'Chapter the Seventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the compact: its courts and sentences; the Fallen '
             'wait at folio 224.',
 'folio': '197B',
 'glossL': '<p><span class="mark">a</span> On the convened courts, the '
           'eight Wise Hearts per fellowship, and the statute of the '
           'weak seat, see the Book of Secrets, folios 233&ndash;234 of '
           'that volume.</p>\n'
           '        <p><span class="mark">b</span> On the three '
           'advocates, the vetting, the five-of-eight rules, and the '
           'absence of appeal, see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'named offenses &mdash; corruption first among them &mdash; '
           'and the protected peoples, see folios 234&ndash;236 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'Swords of the Law, the scale of sentences, the absence of '
           'soul-unmaking, and the jar on the books unused, see folios '
           '234&ndash;236 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Read the jar against '
           '2b&rsquo;s Gilgul: the nine chairs keep a sentence that '
           'unmakes the soul and have used it; the compact keeps a '
           'sentence that merely detains one and never has. The two '
           'ledgers are this binding&rsquo;s whole argument about '
           'power, kept in its margins.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'convened-and-dissolved design answers 3a&rsquo;s standing '
           'judgments point for point: what that folio&rsquo;s court '
           'remembers, this one forgets on purpose, and the two '
           'should be taught as one lesson in institutional '
           'design.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'corruption offense &mdash; first on the list, harshest on '
           'the scale &mdash; is folio 224&rsquo;s subject arraigned in '
           'advance; and the influence the compact wields through '
           'faith, gold, and streets is the whisper war of the recto, '
           'funded.</p>',
 'h1': 'The Wise Hearts',
 'hagahah': 'The compact&rsquo;s court dies at verdict, which is the only '
            'sentence it passes on itself.',
 'inner': '<p><span class="lemma">A court for the case alone.</span> The '
          'design&rsquo;s plain sense: the compact&rsquo;s justice is '
          'deliberately stateless &mdash; no standing bench, no '
          'permanent judges, no doctrine of precedent &mdash; because '
          'a standing thing can be captured and a captured court is '
          'worse than none. Every trial builds its machine from '
          'parts held in trust, runs it once, and melts it down; the '
          'fellowships keep the parts, never the machine.</p>\n'
          '        <p><span class="lemma">The statute of the weak '
          'seat.</span> The eight&rsquo;s strangest rule, plainly: one '
          'judge in eight must be young, or weak, or both &mdash; '
          'seated not despite the weakness but because of it, a '
          'standing reminder that justice which favors the strong '
          'is the disease the compact formed to survive. The rule '
          'is numerology&rsquo;s gift too &mdash; eight being '
          'auspicious in half the members&rsquo; cosmologies &mdash; '
          'and the folio notes the craft in that: a court whose '
          'very seat-count flatters every faith at the table has '
          'done half its diplomacy before the gavel.</p>\n'
          '        <p><span class="lemma">Five of eight, and no '
          'appeal.</span> The verdict clause&rsquo;s plain sense: '
          'conviction and sentence each want a majority of five, '
          'argued until reached, and the ruling is final &mdash; not '
          'from arrogance but from architecture, for an appeals '
          'bench would be the standing court the design forbids. '
          'The finality is priced honestly: the advocates&rsquo; '
          'vetting is the only error-correction the system owns, '
          'so the vetting is where the law spends its '
          'paranoia.</p>\n'
          '        <p><span class="lemma">Corruption first.</span> '
          'The offense list&rsquo;s plain sense, and its order: '
          'dealing with the Fallen in any register but violence '
          'heads the list and carries the whole weight of the '
          'law, above betrayal, above murder &mdash; because the '
          'compact&rsquo;s founding conviction holds corruption to '
          'be the enemy&rsquo;s actual weapon, beside which armies '
          'are theater. The margin of 224 will show the list&rsquo;s '
          'wisdom; this folio only notes that a young alliance '
          'legislated against seduction before it legislated '
          'against knives.</p>\n'
          '        <p><span class="lemma">Neither mercy nor '
          'cruelty.</span> The executor clause&rsquo;s plain sense: '
          'the Swords are an office built to be unenviable &mdash; '
          'sworn to carry out whatever the court rules, forbidden '
          'to enjoy it, the cold and the sadistic barred from '
          'holding the blade by statute. The design reads the '
          'oldest lesson of punishment correctly: the danger is '
          'never only the sentence but the sentencer, and a law '
          'that screens its executioners for appetite has understood its own worst case.</p>\n        <p><span class="lemma">Two-thirds, and the ledger&rsquo;s stairs.</span> The scale&rsquo;s plain sense, climbed in order: reparation strips two-thirds of all the offender owns to the wronged party, rises by fractions for deceit about the worth, and ends at death for the persistent &mdash; and the sources record its popularity among the compact&rsquo;s poorer fellowships, whom it endows. The design&rsquo;s economy is visible: a justice with no prisons must punish in property, person, or life, and the scale climbs those three stairs in order, spending the irreversible ones last. Between them sits the statute for the violator &mdash; insisted on jointly by the two allies who agree on nothing else &mdash; absolute in kind, exhaustively verified before application, sparing the ill and the unknowing by rule; and the sources attest the offense has been rare among the fellowships since the statute was cut.</p>',
 'inner_head': 'On the Court<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the seats, the majorities, and the '
               'swords</span>',
 'name': 'The Wise Hearts',
 'outer': '<p><span class="lemma">Severity, or fear in robes.</span> The '
          'harshness dispute. <span class="voice">Some say</span> the '
          'scale is justice fitted to its circumstances: a compact '
          'with no prisons, no police, and no second chances cannot '
          'afford gentle error &mdash; reparation beggars, the rare '
          'torments deter, death removes, and the uniform weight '
          'across fellowships is itself the fairness, for a law '
          'harsh to everyone favors no one. The cultures of the '
          'compact, the sources add, largely concur &mdash; zero '
          'tolerance is a doctrine many of them brought from home. '
          '<span class="voice">Others say</span> read the scale&rsquo;s '
          'shape, not its weight: punishments this theatrical are '
          'messages, and messages are sent by the frightened &mdash; '
          'the compact cannot survive one deep betrayal and knows '
          'it, so it prices betrayal beyond any rational actor&rsquo;s '
          'budget and calls the pricing law. Fear is a sound reason '
          'to legislate; it is a poor judge of proportion, and a '
          'court with no appeal has no way to learn it '
          'overreached. The first school answers that the '
          'record is short and clean &mdash; few trials, fewer '
          'atrocities, the worst sentences counted on one hand. '
          'The second answers that young laws always have clean '
          'records, and the question is what this one does in its '
          'first real famine. The folio files the dispute beside '
          'the design&rsquo;s own concession: a court that remembers '
          'nothing cannot notice its own drift, so severity here '
          'is forever year one. <span class="kw">TEYKU</span> &mdash; '
          'the record is too short to convict the law, which is '
          'the law&rsquo;s own argument, made uncomfortable.</p>\n'
          '        <p><span class="lemma">The jar on the books.</span> '
          'The unused-law dispute. <span class="voice">Some say</span> '
          'a penalty never used is a flaw in drafting or a lie in '
          'waiting: laws are promises about consequences, and a '
          'promise no one has ever kept teaches the compact&rsquo;s '
          'members that its books contain at least one bluff &mdash; '
          'and a court known to bluff once is suspected of '
          'bluffing always; strike it, or use it, but do not shelve '
          'it. <span class="voice">Others say</span> the unused '
          'sentence is the shelf&rsquo;s whole dignity: the compact '
          'wrote down the worst thing it could imagine doing, '
          'looked at it, and has declined every occasion since '
          '&mdash; which is not a bluff but a boundary, renewed at '
          'every trial that ends short of it. Read it against the '
          'neighbors: the nine chairs wrote their soul-sentence '
          'and used it within a generation, and the difference '
          'between the two ledgers is the difference the crafts '
          'built the compact to keep. The first school answers '
          'that boundaries unpoliced move in the night. The '
          'second answers that this boundary has a police: every '
          'Wise Heart who has ever voted a lesser sentence while '
          'the jar sat on the table &mdash; and that the '
          'jar&rsquo;s work is done precisely by sitting there. '
          'The folio, for once, records where the weight of the '
          'commentary falls: on the shelf, unopened, and watched.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the scale, and the jar</span>',
 'rubric': 'the compact&rsquo;s justice',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen, continued &middot; of courts convened and '
             'dissolved',
 'title': 'Tractate Aliyah · Folio 197b — The Wise Hearts: the compact&rsquo;s justice',
 'type': 'daf'}
