# Folio 224b - The Deep Game. The Fallen's method and the hunt, per the
# wod-llm-wiki nephandi and descent pages (M20 pp.230-232; Book of the
# Fallen pp.60-62; Book of Secrets pp.239-242; Book of Madness pp.36-45).
FOLIO = {'bottom': '<p><span class="lemma">On the six moves at the table.</span> The '
           'predator&rsquo;s craft is a Storyteller&rsquo;s toolkit exactly as far '
           'as the table has consented to it and no further: the folio&rsquo;s '
           'law is drawn from the anatomy of real abuse, the sources say so '
           'openly, and material of that weight is run with 384b&rsquo;s tools '
           'on the table &mdash; lines agreed, exits marked, and the '
           'right to stop absolute.</p>\n'
           '        <p><span class="lemma">On playing the long game '
           'long.</span> The deep game only frightens if it is actually '
           'deep: plant the enemy&rsquo;s asset two seasons before the reveal, '
           'let him be helpful the whole way, and let the reveal '
           'reorganize the chronicle&rsquo;s memory rather than its evening. '
           'A tempter met and unmasked in one session is a monster of '
           'the week; the folio&rsquo;s monster is a friendship '
           'audited too late.</p>\n'
           '        <p><span class="lemma">On leaving the war '
           'winnable.</span> The sources flirt with the possibility that '
           'the enemy has already won, and the counsel is to flirt and '
           'never marry: a chronicle where corruption is everywhere and '
           'resistance is futile stops being horror and becomes weather. '
           'Keep the enemy&rsquo;s victories real, local, and reversible at '
           'cost, and the dread stays load-bearing.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on consent, patience, '
                'and winnable wars</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The enemy&rsquo;s craft is a hunter&rsquo;s,</span> '
           'and the law restates it so the hunted may read it: indulge '
           '&mdash; offer what the prey craves; deceive &mdash; tell them '
           'what they already wished true; isolate &mdash; thin the '
           'trusted company until one voice remains; escalate &mdash; '
           'gift becoming flood, pressure becoming force; corrupt '
           '&mdash; teach that the laws are for lesser people; and '
           'force last, when the rest have done their work. The wise '
           'enemy alternates; only amateurs push one door.<sup>a</sup> '
           'The strategy above the craft is occupation without '
           'banners: while the great houses fight, the enemy buys the '
           'horses and sells artillery to both sides, seeding '
           'appetites and grievances and letting people do the rest '
           'unassisted.<sup>b</sup> The law of exile stands behind '
           'both: in living memory the fellowships joined hands once '
           '&mdash; the one alliance of Union and Council the histories '
           'record &mdash; and drove the enemy&rsquo;s masters past the '
           'outer wall, thickening it behind them; the abandoned '
           'mazes they left are trapped, and their owners have begun '
           'to come back.<sup>c</sup> And the hunt&rsquo;s procedure is '
           'quarantine before quarrel: suspicion is reported, never '
           'pursued alone; contact is contamination; and the '
           'investigator&rsquo;s first casualty, the sources warn, is always her certainty that she would know.<sup>d</sup> So the verso&rsquo;s law runs: the method is patience, the defense is company, and the ledger is read by its beneficiaries.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear what the wall purchased. When the masters '
           'were driven out, the fellowships kept the young ones&rsquo; '
           'gratitude for a generation &mdash; the sky swept, the '
           'mazes emptied, the long war shortened, it was said, by '
           'centuries. The teachers preserved the audit beside the '
           'triumph. The masters&rsquo; absence made the servants '
           'ambitious; the emptied mazes made fine real estate for '
           'whoever reached them first; and the wall that keeps the '
           'exiles out keeps their letters moving in, for a wall '
           'stops armies and has never yet stopped a whisper. The '
           'greatest purge in the setting&rsquo;s history, the audit '
           'runs, converted an occupation into an inheritance '
           'dispute &mdash; and the heirs are patient. The disputants '
           'around this text hold what the exile bought, and '
           'whether the deep game can be lost.</p>',
 'chapter': 'Chapter the Seventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Fallen: the method and the hunt; the Mad wait '
             'at folio 234, and the chapter closes there.',
 'folio': '224B',
 'glossL': '<p><span class="mark">a</span> On the six moves and the '
           'counsel against single doors, see M20, folios '
           '230&ndash;232, and the Book of the Fallen, folios '
           '60&ndash;62 of that volume, which names its own dark '
           'anatomy openly.</p>\n'
           '        <p><span class="mark">b</span> On occupation without '
           'banners &mdash; the field bought, the appetites seeded '
           '&mdash; see the Book of Secrets, folios 241&ndash;242 of '
           'that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'joint expulsion past the outer wall, the thickened veil, '
           'the trapped mazes, and the beginning returns, see the '
           'Book of Madness, folios 36&ndash;37 of that volume, and '
           'Book of Worlds, folio 186 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'quarantine procedure and the investigator&rsquo;s '
           'certainty, see Initiates of the Art, folios 69&ndash;73 '
           'of that volume, whose counsel to the threatened is '
           'flight in company.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The exile is the '
           'chapter&rsquo;s door into 109a: the outer wall&rsquo;s '
           'quarantine reading is this folio&rsquo;s history restated '
           'as architecture, and the deep&rsquo;s builders on the far '
           'rocks are the driven-out of this Gemara, building.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'six moves are the dark twin of 188a&rsquo;s managed '
           'narrative, and the margin files the resemblance as the '
           'compact of 197 files its conviction: the methods '
           'converge, whatever the masters intend, and the '
           'convergence is the accusation.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'consent tools this folio&rsquo;s counsel leans on are '
           '384b&rsquo;s; the conditioning file behind 188b is this '
           'leaf&rsquo;s nearest neighbor in the binding, and both '
           'stay behind the same locked drawer for the same '
           'reasons.</p>',
 'h1': 'The Deep Game',
 'hagahah': 'The enemy&rsquo;s best soldiers never enlisted, and his best '
            'victories are filed under other names.',
 'inner': '<p><span class="lemma">Six doors, one house.</span> The '
          'craft&rsquo;s plain sense, and why the law prints it: the '
          'six moves are published not to teach the hunter but to '
          'arm the prey &mdash; each move is ordinary kindness or '
          'ordinary pressure until sequenced, and the sequence is '
          'the tell. The sources name their model plainly: this is '
          'the anatomy of abuse, studied from the world&rsquo;s own '
          'records, and the folio keeps the naming &mdash; for the '
          'setting&rsquo;s horror is the real thing wearing robes, '
          'and pretending otherwise disarms the reader the law '
          'means to arm.</p>\n'
          '        <p><span class="lemma">The field bought '
          'quietly.</span> The strategy clause&rsquo;s plain sense: '
          'the enemy&rsquo;s war aim is not victory in any battle '
          'the great houses stage but the staging itself &mdash; '
          'both armies horsed, both armories stocked, every '
          'grievance on every side gently fed &mdash; and his '
          'ledger books despair and division as revenue wherever '
          'it occurs, unsigned. The consequence is the '
          'chapter&rsquo;s hardest discipline: the enemy&rsquo;s '
          'presence cannot be inferred from harm alone, since '
          'harm is the world&rsquo;s own product line; only the '
          'sequence, and the profit, betray a hand.</p>\n'
          '        <p><span class="lemma">The one alliance.</span> '
          'The exile clause&rsquo;s plain sense: the setting&rsquo;s '
          'sole recorded concord of Union and Council was for '
          'this &mdash; the masters driven past the wall, the wall '
          'thickened after &mdash; and the folio underlines what '
          'the fact implies: the two great houses that agree on '
          'nothing agreed on this enemy, once, completely. The '
          'audit&rsquo;s fine print stands beside it: exile is not '
          'ending, the mazes were left trapped and tenanted with '
          'patience, and the returns have begun. The clause&rsquo;s lesson for the chronicle is calendrical: the setting&rsquo;s present is the inheritance dispute&rsquo;s late innings, and every trapped maze, silent patron, and ambitious orphan sect is a hook already baited.</p>\n'
          '        <p><span class="lemma">Reported, never '
          'pursued alone.</span> The procedure&rsquo;s plain sense: '
          'the hunt&rsquo;s first rule is company &mdash; suspicion '
          'goes to the fellowship, not the corridor &mdash; and '
          'the second is humility about detection: the hollow '
          'read as warm because they are warm, the tell is '
          'never the sneer but the sequence, and the '
          'investigator who trusts her nose has already been '
          'chosen for her confidence. The counsel to the '
          'young is the sources&rsquo; own and the folio repeats '
          'it unimproved: get your teacher, and go together. The procedure&rsquo;s third rule is the file: what the investigation learns is written for the fellowship, never carried in one head &mdash; for the enemy&rsquo;s oldest counter to a lone witness is patience, and to a written record, nothing good.</p>\n'
          '        <p><span class="lemma">The mirror, '
          'again.</span> The last clause&rsquo;s plain sense, '
          'carried from the recto: the enemy&rsquo;s deepest '
          'investment is the habit of hunting evil in the '
          'other fellow &mdash; the despised sect, the rival '
          'house, the strange neighbor &mdash; while the '
          'reflection goes unexamined. Every fellowship in '
          'this binding owns a purge it is ashamed of, and '
          'the folio files the pattern as the enemy&rsquo;s '
          'signature: wherever certainty ran ahead of '
          'evidence, his ledger shows a deposit.</p>',
 'inner_head': 'On the Method<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the moves, the field, and the '
               'exile</span>',
 'name': 'The Deep Game',
 'outer': '<p><span class="lemma">What the exile bought.</span> The '
          'audit dispute. <span class="voice">Some say</span> '
          'centuries: the masters&rsquo; absence is the reason the '
          'long war still has two sides &mdash; the young enemy is '
          'ambitious but orphaned, his patrons silent past the '
          'wall, his sects quarreling over the inheritance &mdash; '
          'and the one alliance proved the essential thing, that '
          'the houses can unite when the stakes are named; the '
          'wall is the setting&rsquo;s one unambiguous victory and '
          'should be taught as such. <span class="voice">Others '
          'say</span> the audit reads differently below the line: '
          'an enemy whose method is whispers lost nothing that '
          'matters when his armies were exiled &mdash; the letters '
          'still cross, the ledger still fills, and the great '
          'houses&rsquo; certainty that the war was shortened is '
          'itself the sort of comfortable belief the enemy '
          'farms; meanwhile the victory&rsquo;s price included the '
          'wall&rsquo;s thickening, which the age&rsquo;s travelers '
          'and the storm&rsquo;s casualties have paid ever since. '
          'The first school answers that a war against masters '
          'present would have been shorter still and lost. The '
          'second answers that this is unfalsifiable, which is '
          'the problem with every claim in this folio, and both '
          'schools pause at having agreed on something. The '
          'folio files the concord: against this enemy, '
          'certainty itself is contested ground. <span '
          'class="kw">TEYKU</span> &mdash; the audit cannot close '
          'while the auditors may be entries.</p>\n'
          '        <p><span class="lemma">Whether the deep game '
          'can be lost.</span> The despair dispute. <span '
          'class="voice">Some say</span> the sources&rsquo; darkest '
          'reading is the honest one: the state of the world '
          'argues a pending victory &mdash; the appetites fed, '
          'the divisions dividend-bearing, the mirror trick '
          'installed at scale &mdash; and a horror setting owes '
          'its readers the truth that the enemy may simply be '
          'winning; hope sold cheap is the other genre. <span '
          'class="voice">Others say</span> the same sources '
          'sign the rebuttal in their own hand: the enemy&rsquo;s '
          'victories require our appetite, his nudges need our '
          'hands, and a war whose weapon is consent is lost '
          'only by consenting &mdash; the darkest line in the '
          'books is conditional, if they win it is because we '
          'let them, and a conditional is a door. The first '
          'school answers that doors close, and that betting '
          'the world on collective virtue has a record. The '
          'second answers that the binding&rsquo;s whole subject '
          'is will against the weight of the world, and that '
          'this folio is not where it will start '
          'flinching. The folio sides with the second and '
          'says so &mdash; per the counsel below, the war stays '
          'winnable at the table whatever the cosmos '
          'decides &mdash; and notes for honesty that the first '
          'school&rsquo;s reading remains printed, standing, and patient, like its subject. And the schools share one discipline the folio makes binding: whichever reading the chronicle adopts, it must be adopted &mdash; a table that drifts between winnable and lost wars by session teaches its players that despair is weather, and despair as weather is the enemy&rsquo;s own forecast, delivered free. The teachers closed the chapter&rsquo;s darkest leaf with its plainest instruction, and the folio keeps their order of operations: name the enemy rarely, check the mirror often, keep the company close &mdash; and when the long game finally shows its hand at the table, let the players discover that the counters were in the folio all along, printed in the law&rsquo;s own list, one door back from wherever the enemy knocked.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the audit, and the ending</span>',
 'rubric': 'the method and the hunt',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen, continued &middot; of the deep game',
 'title': 'Tractate Aliyah · Folio 224b — The Deep Game: the method and the hunt',
 'type': 'daf'}
