# Folio 224a - The Fallen. The law of the barabbi and the caul, per the
# wod-llm-wiki nephandi, caul, and descent pages (M20 pp.41, 224-233;
# Book of the Fallen pp.46-49, 55-59; Initiates of the Art pp.69-73).
FOLIO = {'bottom': '<p><span class="lemma">On horror used sparingly.</span> The '
           'Fallen are the setting&rsquo;s one adversary that should never '
           'become routine: one true Nephandus per chronicle, met three '
           'times, outweighs a legion met weekly. The books&rsquo; own '
           'counsel is scarcity &mdash; the sect is small and its influence '
           'legion &mdash; and the table&rsquo;s dread should be built the '
           'same way: from absence, implication, and the one charming '
           'friend who was never quite wrong.</p>\n'
           '        <p><span class="lemma">On corruption arcs and '
           'consent.</span> A player character&rsquo;s slide toward the '
           'caul is the line&rsquo;s heaviest material and must be '
           'volunteered, never imposed: agree the arc, its limits, and '
           'its exits with the player in the open, per 384b&rsquo;s tools. '
           'The books advise against Fallen player characters at all; a '
           'chronicle that goes near the edge anyway owes the table the '
           'safety gear.</p>\n'
           '        <p><span class="lemma">On the charming friend.</span> '
           'Play the tempter as genuinely useful, genuinely warm, and '
           'right about small injustices &mdash; for that is the pattern: '
           'the law&rsquo;s six moves begin with gifts and truths. If the '
           'players never liked the Nephandus, the Storyteller has '
           'skipped the folio&rsquo;s whole mechanism, and the horror '
           'arrives unearned.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on scarcity, consent, '
                'and the warm hand</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">There is a fall, and it is chosen.</span> '
           'The law names them the <span class="term">Fallen</span>: '
           'mages who embrace corruption and unmaking as their summit, '
           'walking a descent that mirrors ascension step for inverted '
           'step.<sup>a</sup> The gate of the fall is the <span '
           'class="term">caul</span>: the dark passage through which '
           'the candidate&rsquo;s inmost spark is turned inside out and '
           'reassembled in service to the void &mdash; entered '
           'willingly, the sources insist, neither tricked nor '
           'dragged.<sup>b</sup> Three roads reach the gate: the <span '
           'class="term">barabbi</span>, turncoats from every seat and '
           'craft, who commonly remain in their old fellowships to '
           'poison them; the caul-born, who wake through the gate '
           'itself and owe no prior loyalty; and the born-damned, '
           'carrying a fallen spark from a prior life &mdash; of whom '
           'the law keeps one mercy: the child not yet passed through '
           'the gate may still be saved.<sup>c</sup> And contact '
           'contaminates: no fellowship in the setting sanctions any '
           'dealing with the Fallen save killing them &mdash; the '
           'compact of 197 heads its offense list with exactly this '
           '&mdash; for the enemy&rsquo;s weapon is not armies but '
           'nudges, and its favorite door is the friend&rsquo;s face.<sup>d</sup> So the folio&rsquo;s law runs: the fall is real, chosen, and patient &mdash; and the reader&rsquo;s first defense is the pattern, printed here so it may be recognized on arrival.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear a fall, told as pattern and not as any one '
           'name. A mage of standing was owed more than she was '
           'paid &mdash; every fall in the records begins with a true '
           'grievance &mdash; and a friend agreed with her, warmly, '
           'for a year. The friend&rsquo;s gifts were real; the '
           'friend&rsquo;s doors opened; the friend&rsquo;s counsel, '
           'step by step, relocated her conscience to somewhere '
           'less convenient. When at last she went through the '
           'gate she went, as the sources insist all of them go, '
           'willingly &mdash; and came back to her chantry smiling, '
           'reliable, generous, and hollow, and served another '
           'nine years before anyone counted the cost of her '
           'counsel. The disputants around this text hold whether '
           'the fall is one-way, and how to hunt what wears a '
           'friend.</p>',
 'chapter': 'Chapter the Seventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the Fallen named; the hunt and its dangers overleaf, and the '
             'Mad at 234.',
 'folio': '224A',
 'glossL': '<p><span class="mark">a</span> On the Fallen and the descent '
           'that mirrors ascension, see M20, folio 41 and folios '
           '224&ndash;233, whence this page takes its number, and the '
           'Book of the Fallen, folios 46&ndash;49 of that volume.</p>\n'
           '        <p><span class="mark">b</span> On the caul &mdash; the '
           'passage, the inversion of the spark, and the willing entry '
           '&mdash; see the Book of the Fallen, folios 46&ndash;47 and '
           '105&ndash;106 of that volume, and Initiates of the Art, '
           'folios 70&ndash;71 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'three roads &mdash; turncoat, caul-born, born-damned &mdash; '
           'and the mercy of the unpassed child, see M20, folio 227, '
           'and the Book of the Fallen, folios 55&ndash;59 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'universal shoot-on-sight custom and the influence of '
           'nudges, see the Book of Secrets, folios 239&ndash;242 of '
           'that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Read the gate against '
           '38a&rsquo;s Epiphany: the sources build the fall as the '
           'waking&rsquo;s exact negative &mdash; survived versus '
           'surrendered, the spark opened versus the spark inverted '
           '&mdash; and the two folios should be taught as one diagram '
           'read in both directions.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'trial of 2b tried betrayal and pronounced Gilgul; the '
           'charge this folio names was never proven there, and the '
           'margin keeps the acquittal&rsquo;s discomfort: the '
           'binding&rsquo;s first villain may belong to this folio or '
           'merely to 2b&rsquo;s, and the manuscripts disagree.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'break inward is 554a&rsquo;s Quiet and the break downward is '
           'this folio&rsquo;s; the third break, outward into weather, '
           'is folio 234&rsquo;s &mdash; and the chapter&rsquo;s design '
           'files all three where the seated can compare them.</p>',
 'h1': 'The Fallen',
 'hagahah': 'The abyss also keeps records; it cites ours.',
 'inner': '<p><span class="lemma">A summit, inverted.</span> The '
          'definition&rsquo;s plain sense: the fall is not failure but '
          'doctrine &mdash; a chosen path with its own discipline, its '
          'own nine-runged ladder read downward, its own patient '
          'masters &mdash; and the folio&rsquo;s first correction is '
          'aimed at the table&rsquo;s comfort: the shrieking cultist '
          'is the breed&rsquo;s least member, kept forward as decoy, '
          'while the true practitioner is the enemy one wants to '
          'trust &mdash; charismatic, generous, certain, and '
          'poisonous by appointment.</p>\n'
          '        <p><span class="lemma">Willingly, the sources '
          'insist.</span> The gate clause&rsquo;s plain sense, and its '
          'hardest word: the passage is entered by choice &mdash; not '
          'tricked, not dragged &mdash; and the insistence is '
          'load-bearing for the whole chapter, for it locates the '
          'fall&rsquo;s horror in the will and not in any ambush. '
          'What the year of warm counsel does is move the will, '
          'inch by justified inch, until the choice at the gate is '
          'real and freely made and entirely manufactured &mdash; '
          'the law&rsquo;s quiet teaching on how consent can be true and stolen at once; the counsel below spends the clause at the table, where it marks the difference between horror and blame.</p>\n'
          '        <p><span class="lemma">The turncoat&rsquo;s '
          'mask.</span> The first road&rsquo;s plain sense: the '
          'barabbi&rsquo;s customary posting is home &mdash; the old '
          'seat kept, the old friendships worked, the poisoning '
          'done from inside over years &mdash; and the consequence '
          'for the setting is structural paranoia: every '
          'fellowship in this binding must reckon that some of '
          'its own are hollow, and the reckoning itself, the '
          'margin will note, does half the enemy&rsquo;s work.</p>\n'
          '        <p><span class="lemma">The mercy of the '
          'unpassed child.</span> The third road&rsquo;s plain '
          'sense, and the law&rsquo;s one soft clause: the '
          'born-damned carry a fallen spark not yet surrendered '
          'to, and the sources rule plainly that the child who '
          'has not passed the gate is not yet of the Fallen '
          '&mdash; someone likely to become, which is a category '
          'the living can still argue with. The clause is small '
          'and the folio underlines it, because it is the only '
          'place in the chapter where the door swings the other '
          'way by statute.</p>\n'
          '        <p><span class="lemma">Nudges, not '
          'armies.</span> The contamination clause&rsquo;s plain '
          'sense: the sect is small &mdash; there are not Fallen '
          'everywhere &mdash; and its influence is legion anyway, '
          'because its method needs no soldiers: the whispered '
          'word at the wrong time, the appetite flattered, the '
          'despair confirmed, and people do the rest unassisted. '
          'The law&rsquo;s image is the mirror: the enemy&rsquo;s '
          'oldest trick is teaching the world to hunt its evil '
          'in the other fellow, and the folio files the trick '
          'where every later hunt can read it first. The scale clause completes the arithmetic: because the hands are borrowed, the enemy&rsquo;s reach is bounded only by the world&rsquo;s appetite &mdash; pulpits and boardrooms, broadcasts and bar-stools &mdash; and the folio&rsquo;s census discipline follows: count the Fallen rarely, count their fingerprints often, and never mistake the second number for the first.</p>',
 'inner_head': 'On the Fall<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the gate, the roads, and the '
               'nudges</span>',
 'name': 'The Fallen',
 'outer': '<p><span class="lemma">Whether the fall is one-way.</span> '
          'The return dispute. <span class="voice">Some say</span> the '
          'no-return doctrine is the law&rsquo;s plain sense and its '
          'mercy: the gate does not bend a soul but rebuilds it '
          '&mdash; the spark turned inside out is not the old spark '
          'misled, and there is nothing left to redeem, only '
          'something new to stop; every tale of the repentant '
          'Fallen in the records ends badly, and the sources '
          'themselves note that among the Fallen the sincere wish '
          'to repent is counted the worst of crimes &mdash; which '
          'their own law would not bother forbidding if it were '
          'impossible. <span class="voice">Others say</span> that '
          'last clause is the heresy&rsquo;s whole case, filed by '
          'the enemy&rsquo;s own clerks: a crime statute implies '
          'offenders, so the wish exists, and where the wish '
          'exists the door is not sealed but guarded &mdash; add '
          'the statute of the unpassed child, the one place the '
          'law swings the door by right, and the no-return '
          'doctrine shrinks from metaphysics to policy. The first '
          'school answers that the wish to repent is not the '
          'power to, and that the guarded door has eaten every '
          'rescuer who tried it. The second answers that the '
          'binding&rsquo;s whole faith is that will moves worlds, '
          'and finds it strange to except the one case where it '
          'matters most. The stakes are a chronicle&rsquo;s '
          'darkest scene &mdash; what the party may rightly do '
          'with a Fallen friend who asks for help &mdash; and the '
          'sources hold the question open on purpose. <span '
          'class="kw">TEYKU</span> &mdash; the stories about them '
          'don&rsquo;t end well; the stories are not over.</p>\n'
          '        <p><span class="lemma">Hunting without becoming '
          'the hunt.</span> The Pogrom dispute. <span '
          'class="voice">Some say</span> the shoot-on-sight custom '
          'is the one law every fellowship shares and the only '
          'sane one: the enemy&rsquo;s weapon is contact, so the '
          'counter is quarantine &mdash; no parley, no study, no '
          'clever exceptions, for every exception in the records '
          'is a corpse or a convert. Harshness here is hygiene. '
          '<span class="voice">Others say</span> the custom is the '
          'enemy&rsquo;s second victory: a law of kill-on-suspicion '
          'is a machine for atrocity waiting for bad intelligence '
          '&mdash; and the intelligence is always eventually bad; '
          'the purges of this setting&rsquo;s history were all '
          'conducted by people certain they were burning the '
          'hollow, and the mirror trick&rsquo;s finest work is a '
          'righteous mob. The first school answers that the '
          'alternative &mdash; tribunals for the untriable, '
          'evidence from the unfalsifiable &mdash; is a door held '
          'open for the patient. The second answers with '
          '197b&rsquo;s bench: the compact tries corruption with '
          'advocates and majorities precisely because its '
          'members have been on the wrong end of certainty, and '
          'its short record is cleaner than any purge&rsquo;s. The '
          'folio hands the chronicle the tension whole: the hunt '
          'is necessary, the hunt is corruptible, and the '
          'enemy profits from both errors &mdash; which is why he is the enemy. The folio&rsquo;s last word goes to procedure: suspicion in company, verdicts by bench, and the mirror checked first &mdash; not because the checks are safe, but because their absence never is.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the door, and the hunt</span>',
 'rubric': 'the chosen descent',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen, continued &middot; of the Fallen &middot; the '
             'descent as law',
 'title': 'Tractate Aliyah · Folio 224a — The Fallen: the chosen descent',
 'type': 'daf'}
