# Folio 234a - The Mad. The law of the Marauders, per the wod-llm-wiki
# marauders and quiet pages (M20 pp.41, 234-243; Book of Madness
# pp.50-63; Initiates of the Art pp.67-68).
FOLIO = {'bottom': '<p><span class="lemma">On the Mad as weather.</span> Run '
           'Marauders as fronts, not factions: they arrive like storms, '
           'reorganize the landscape, and pass &mdash; and the party&rsquo;s '
           'business is shelter, salvage, and the neighbors, not victory. '
           'A Marauder statted as a boss fight has been misfiled; the '
           'encounter&rsquo;s verbs are survive, redirect, and grieve.</p>\n'
           '        <p><span class="lemma">On the sympathy clause.</span> '
           'The books insist each of the Mad was a person &mdash; burned by '
           'cosmic truth, with a life and loved ones left behind &mdash; and '
           'the table should meet the person at least once: the photograph '
           'in the wallet, the sister still searching, the lucid minute '
           'that ends. Horror without the person is spectacle; with the '
           'person, it is the folio.</p>\n'
           '        <p><span class="lemma">On the bounced backlash.</span> '
           'The Mad One&rsquo;s insulation makes the party the lightning rod, '
           'and the Storyteller should say so out loud the first time: '
           'fighting a Marauder with vulgar art means billing the '
           'court&rsquo;s fees to yourself. The tactical puzzle &mdash; how to '
           'act at all when acting is priced double &mdash; is the '
           'encounter&rsquo;s real content.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on storms, persons, '
                'and lightning rods</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">There is a break that walks.</span> The '
           'law names them the <span class="term">Mad</span>: mages '
           'lost to the broken mirror of 554a made permanent &mdash; '
           'worn no longer as an episode but as a world, carried '
           'wherever the wearer goes.<sup>a</sup> Their law is '
           'counter-rational, not irrational: within the carried '
           'world everything follows, and the sources&rsquo; sympathy '
           'clause is statute &mdash; each was an enlightened soul '
           'burned by truth, with a life left behind.<sup>b</sup> The '
           'break wears two faces: the actualized, whose world '
           'spills outward and drinks bystanders into its weather; '
           'and the perceptual, who walk unremarked among the '
           'masses, the world staying whole around a mind that is '
           'not &mdash; the more feared face, being '
           'invisible.<sup>c</sup> And the court&rsquo;s writ fails at '
           'their border: the fees of 533a strike the walking world '
           'and are absorbed by it, the remainder leaping to the '
           'nearest woken bystander; the agreement bends around '
           'them and snaps back at their leaving; and no treaty '
           'holds, for no signature means the same thing on both sides of the glass.<sup>d</sup> So the folio&rsquo;s law runs: the break is a person wearing a world, and every response the chapter can offer must fit through that doorway or not go in.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the case the courts decline. A Mad One '
           'was brought &mdash; the records do not say how &mdash; '
           'before a tribunal of the seated, charged with what her '
           'weather had done to a town. She answered every '
           'question courteously, in perfect order, from inside a '
           'world where the town was grateful, the tribunal were '
           'her gardeners, and the charge was a bouquet. The '
           'advocates conferred. To try her, the court must reach '
           'her; to reach her, it must enter a world where its '
           'writ read as flowers; and a verdict pronounced in a '
           'language the condemned cannot inhabit, the eldest '
           'judge ruled, is not law but noise with robes on. They '
           'adjourned without verdict, posted wards, and paid the '
           'town&rsquo;s rebuilding from the bench&rsquo;s own purse '
           '&mdash; which the record calls, without irony, the only '
           'sentence available. The disputants around this text '
           'hold pity against containment, and whether the break '
           'was ever a choice.</p>',
 'chapter': 'Chapter the Seventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the Mad named; their fellowships and far ends overleaf, and '
             'the chapter closes there.',
 'folio': '234A',
 'glossL': '<p><span class="mark">a</span> On the Mad as permanent Quiet '
           'worn as a world, see M20, folio 41 and folios '
           '234&ndash;243, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On counter-rationality '
           'and the sympathy clause, see the same folios; the elder '
           'recension&rsquo;s degrees of divergence are the Book of '
           'Madness, folios 55&ndash;57 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'two faces, actualized and perceptual, see M20, folios '
           '234&ndash;243, and the Book of Madness, folios '
           '57&ndash;58 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'absorbed fees and the leap to the nearest woken &mdash; '
           'three points shed per degree of the carried world, the '
           'remainder striking the neighbor &mdash; see the Book of '
           'Madness, folios 58&ndash;60 of that volume, and Initiates '
           'of the Art, folios 67&ndash;68 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is 554a&rsquo;s '
           'far end by design: the mirror that cracks there is worn '
           'here, and the three faces of 554b &mdash; including the '
           'shared-descent testimony its margin preserved &mdash; are '
           'this page&rsquo;s clinical prehistory.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'adjourned tribunal is 3a&rsquo;s limit case: that folio '
           'built the court&rsquo;s ladder, and this one finds the rung '
           'that is not there. The bench&rsquo;s purse as the only '
           'sentence available should be read beside 3a&rsquo;s '
           'preserved-grief clause.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'absorbed fees are 533a&rsquo;s court refused at the '
           'door, and the bystander who catches the remainder is '
           'that folio&rsquo;s witness law inverted &mdash; the margin '
           'has warned both pages.</p>',
 'h1': 'The Mad',
 'hagahah': 'The Mad are perfectly consistent; consult any two of their '
            'realities.',
 'inner': '<p><span class="lemma">Worn as a world.</span> The '
          'definition&rsquo;s plain sense: the difference between the '
          'break of 554a and this folio is tense &mdash; an episode '
          'has an exit, a world has a resident &mdash; and the '
          'carried world is complete: weather, history, physics, '
          'and a role in it for everyone the wearer meets. The '
          'elder recension grades the divergence by degrees, from '
          'one small wrongness to a pulp cosmos with its own '
          'wars, and the grading is the encounter&rsquo;s first '
          'question: how far from the street does this weather run &mdash; and the second is the wearer&rsquo;s: what role the visitors have been assigned.</p>\n'
          '        <p><span class="lemma">Counter-rational.</span> '
          'The second clause&rsquo;s plain sense: nothing in the '
          'carried world is random &mdash; it follows its own law '
          'faithfully, which is why negotiation is possible and '
          'treaties are not: the visitor can learn the local '
          'physics, trade in the local currency, and be '
          'genuinely safe exactly as long as the world&rsquo;s '
          'logic holds her guest &mdash; and the logic can '
          'reassign her role without notice, which is the '
          'clause&rsquo;s cold second half.</p>\n'
          '        <p><span class="lemma">The two faces.</span> '
          'The taxonomy&rsquo;s plain sense: the actualized break '
          'is visible catastrophe &mdash; the street rewritten, '
          'bystanders drunk into the weather, the sink of '
          'shared madness widening &mdash; and the perceptual '
          'break is the quiet one, a clerk or a neighbor whose '
          'world diverges invisibly until the divergence acts. '
          'The sources fear the second more and say why: the '
          'first announces itself, and the second is discovered by consequence; the records&rsquo; worst entries are all of the second face, found late.</p>\n'
          '        <p><span class="lemma">The fees '
          'absorbed.</span> The insulation clause&rsquo;s plain '
          'sense: the carried world eats the court&rsquo;s '
          'lightning &mdash; each degree of its depth shedding a '
          'measured share of any backlash &mdash; and the '
          'remainder leaps to the nearest woken soul, colored '
          'by the world it passed through. The tactical '
          'consequence is the counsel below&rsquo;s whole '
          'subject; the doctrinal consequence is stranger: '
          'the court of 533a, which this binding has treated '
          'as cosmic, has a jurisdiction, and these are its '
          'city limits.</p>\n'
          '        <p><span class="lemma">And snaps back.</span> '
          'The last clause&rsquo;s plain sense: the agreement '
          'bends around the carried world and reasserts at its '
          'departure &mdash; the street remembers itself, mostly '
          '&mdash; and the mostly is the folio&rsquo;s quiet dread: '
          'residues persist, witnesses keep what they lived, '
          'and a town that spent a week in somebody&rsquo;s world '
          'does not entirely come home. The chronicle&rsquo;s aftermath scenes live in that clause.</p>\n        <p><span class="lemma">The widening sink.</span> The contagion clause, plainly: the actualized world recruits &mdash; bystanders held long enough begin to see as the wearer sees, the shared madness pooling into sinks that persist and widen &mdash; and the elder recension prices the drift as a contest of resonances, the visitor&rsquo;s stillness set against the world&rsquo;s dynamism. The clause turns geography into triage: the sink&rsquo;s edge is the encounter&rsquo;s real front line, and the folio&rsquo;s counsel counts the neighbors before the wearer.</p>',
 'inner_head': 'On the Break<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the world, the faces, and the '
               'fees</span>',
 'name': 'The Mad',
 'outer': '<p><span class="lemma">Pity against containment.</span> The '
          'response dispute. <span class="voice">Some say</span> pity '
          'first and policy after: the sympathy clause is statute '
          '&mdash; each of the Mad is a casualty of the very truths '
          'this binding studies, burned where every reader of it '
          'stands to burn &mdash; and a fellowship that answers its '
          'own wounded with kill-teams has adopted the '
          'Union&rsquo;s worst reflex under a mystic accent; ward, '
          'shelter, and the patient search for the person still '
          'inside are the only responses the clause permits. '
          '<span class="voice">Others say</span> the clause '
          'describes the patient and not the weather: pity the '
          'wearer and count the town &mdash; the carried world '
          'harms at scale, without malice and therefore without '
          'limit, and containment is not cruelty but triage; the '
          'adjourned tribunal&rsquo;s wards-and-purse ruling is the '
          'model, and its honesty about having no better '
          'sentence is the beginning of wisdom. The first '
          'school answers that triage which never attempts a '
          'cure is abandonment with paperwork. The second '
          'answers that every attempted cure in the records '
          'either failed or fed the weather, and asks the first '
          'school for its case list. The folio notes what the '
          'schools share &mdash; neither will say kill, and '
          'neither will say heal &mdash; and files the silence as '
          'the chapter&rsquo;s saddest datum. <span '
          'class="kw">TEYKU</span> &mdash; the person inside is '
          'the question; no answer reaches her.</p>\n'
          '        <p><span class="lemma">Fate, or a choice made '
          'once.</span> The origin dispute. <span '
          'class="voice">Some say</span> fate: nobody chooses the '
          'break &mdash; it arrives as the waking arrived, '
          'unbidden, at the traumatic waking or the unbearable '
          'truth, and the elder counsel to apprentices treats '
          'it as a hazard of the road, not a doctrine of it; '
          'to call it chosen is to blame the struck for the '
          'lightning. <span class="voice">Others say</span> the '
          'records keep a quieter pattern: the break follows '
          'the burden, and the burden was in every case '
          'carried past warnings &mdash; the fees hoarded, the '
          'mirror&rsquo;s first cracks unreported, the retreat '
          'into the private world begun as a comfort long '
          'before it closed as a wall; not a choice made '
          'once, perhaps, but a hundred small consents, each '
          'reversible at the time. The first school answers '
          'that this is how the comfortable always describe '
          'the drowned. The second answers that it is how '
          'the drowned&rsquo;s own testimony reads, where any '
          'was recovered &mdash; and both schools stand '
          'uneasily over 554b&rsquo;s preserved cases, which '
          'support each exactly where the other is weakest. '
          'The stakes are pastoral: what a fellowship owes '
          'the member whose mirror is cracking now, and '
          'whether watchfulness is care or the first stone '
          'of the wall. The folio commends the chapter&rsquo;s '
          'one sure counsel &mdash; report the cracks, '
          'together, early &mdash; and declines to promise it will be enough. For the chapter&rsquo;s symmetry is exact: the fall of 224 is entered by consent manufactured, and the break of this folio by burdens unshared &mdash; and both doors, the teachers noted, are cheapest to hold shut from the outside, early, in company.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the response, and the origin</span>',
 'rubric': 'the break that walks',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen, continued &middot; of the Mad &middot; the break '
             'as law',
 'title': 'Tractate Aliyah · Folio 234a — The Mad: the break that walks',
 'type': 'daf'}
