# Folio 234b - The Weather. The Mad's fellowships and far ends, per the
# wod-llm-wiki marauders page (M20 pp.234-243; Book of Secrets
# pp.242-252; Book of Madness pp.50-71).
FOLIO = {'bottom': '<p><span class="lemma">On fronts with faces.</span> When the '
           'chronicle needs organized madness, borrow the sources&rsquo; '
           'spectrum whole: the gentle underground smuggling wonders to '
           'safety at one end, the genocidal storm at the other, and the '
           'quiet saboteur cells between. Pick one band, learn its logic, '
           'and let the party meet it twice &mdash; organized weather is '
           'still weather, but it has a forecast.</p>\n'
           '        <p><span class="lemma">On the deniers.</span> The '
           'walking negations &mdash; the Mad whose world simply has no '
           'magick in it &mdash; are the line&rsquo;s subtlest antagonists: '
           'run one as a perfectly reasonable neighbor whose presence '
           'dampens every art in the room, and let the party diagnose '
           'the impossibility before they meet its face. No other '
           'encounter teaches the agreement&rsquo;s weight so cheaply.</p>\n'
           '        <p><span class="lemma">On endings for the Mad.</span> '
           'A Marauder arc should end as weather ends &mdash; passed, not '
           'defeated: escorted past the wall, settled into a far country, '
           'sealed behind wards the party maintains at cost, or simply '
           'gone one morning with the lawn rearranged. Reserve killing '
           'for the storms that leave no choice, and let the table feel '
           'the cost of even those.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on forecasts, deniers, '
                'and endings</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The Mad keep no order, and order '
           'happens anyway.</span> The law knows their gatherings as '
           'weather knows fronts: bands that form and shed members '
           'with the season; fusions, where several carried worlds '
           'merge into one shared storm; and confluxes, strangers '
           'moved by one subconscious tide &mdash; and a few old '
           'ringleaders can steer such fronts where no outsider ever '
           'has.<sup>a</sup> The spectrum of the bands runs the whole '
           'moral sky: at one end an old underground that spirits '
           'wonder-beasts across the wall to countries safe from '
           'disbelief, work its founders called rescue; at the other, '
           'a storm dedicated to shattering the agreement by '
           'slaughter, whose surviving cells the histories name with '
           'dread; between them, cells of quiet sabotage and holy '
           'armament the great houses list by kill '
           'priority.<sup>b</sup> One face the law files apart: the '
           'deniers, Mad whose carried world contains no magick at '
           'all &mdash; walking assertions of the agreement whose mere '
           'presence blunts every art in reach, mistaken daily for '
           'the Union&rsquo;s own.<sup>c</sup> And the break has a far '
           'end: at the world&rsquo;s deepest wearing the Mad One is '
           'shed from the street entire, passing into the deeps to '
           'reshape their stuff into a country of the dream &mdash; '
           'which some call exile, and some call the only summit '
           'this road owns.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear the two undergrounds. One began with a '
           'knight of the old faith who could not watch the '
           'believed-in beasts die of disbelief, and moved them '
           '&mdash; a shepherd&rsquo;s work, station by station, across '
           'the wall to safe country; his order outlived his name, '
           'and its members still find the budding Mad and turn '
           'their weather toward rescue. The other began as a cry '
           'for a broken world and became a fist: its cells took '
           'the storm&rsquo;s logic to its end, and the histories '
           'that will not print their works print their names as '
           'warnings. The teachers set the two side by side '
           'without comment, for the comment is the setting&rsquo;s: '
           'madness is a force, and a force takes the shape of '
           'the vessel &mdash; and the vessel, even broken, was a '
           'person, and persons differ. The disputants around '
           'this text hold whether the weather can be an ally, '
           'and what the far country&rsquo;s summit is worth.</p>',
 'chapter': 'Chapter the Seventh &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter VII closes; the order of making waits at folio 250, '
             'and the histories of the fallen countries with the end-times, '
             'wanting.',
 'folio': '234B',
 'glossL': '<p><span class="mark">a</span> On bands, fusions, confluxes, '
           'and the few ringleaders, see M20, folios 234&ndash;243, and '
           'the Book of Secrets, folios 243&ndash;246 of that '
           'volume.</p>\n'
           '        <p><span class="mark">b</span> On the underground of '
           'rescue, the storm of slaughter, and the cells between, see '
           'the Book of Secrets, folios 243&ndash;246 of that volume, '
           'and the Book of Madness, folios 64&ndash;67 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'deniers and their blunting presence, see the Book of '
           'Secrets, folios 246&ndash;251 of that volume, with the '
           'optional rule for their unconscious counter-art.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'shedding into the deeps and the dream-countries at the '
           'break&rsquo;s far end, see the Book of Madness, folios '
           '56&ndash;57 of that volume, and the dream-realm entries '
           'of the otherworld sources.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The underground&rsquo;s '
           'smuggling road runs through 82a&rsquo;s crossings and '
           '91a&rsquo;s wilds to safe country past the reach of '
           '62a&rsquo;s water &mdash; the one operation in this binding '
           'that uses the whole atlas of chapters III and IV for '
           'mercy.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'deniers are 62a&rsquo;s baseline given feet: the agreement '
           'walking as a person, blunting art as the laboratory of '
           '82a blunts crossings &mdash; and the margin notes the '
           'irony that the Union of chapter VI cannot claim '
           'them.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'far country of the shed Mad borders 91a&rsquo;s deeps and '
           'the dream-roads its sources map; and the chapter&rsquo;s '
           'three breaks &mdash; inward at 554, downward at 224, '
           'outward here &mdash; close as one lesson, filed for the '
           'seated to compare.</p>',
 'h1': 'The Weather',
 'hagahah': 'Two prophets of the Mad agree on nothing except that you '
            'are standing in the forecast.',
 'inner': '<p><span class="lemma">Fronts, not ranks.</span> The '
          'gathering clause&rsquo;s plain sense: the Mad hold no '
          'councils and issue no ranks, and their groupings obey '
          'meteorology &mdash; the band is a front of compatible '
          'weathers traveling together; the fusion is deeper, '
          'several carried worlds merged into one shared delusion '
          'with the firepower of all its members; the conflux is '
          'strangest, strangers converging on one act as a tide '
          'converges, no two aware of the choreography. The '
          'ringleaders are the exception that proves the law: a '
          'handful of old, half-lucid Mad can steer such fronts '
          'from inside, and every outside attempt in the records '
          'ends as weather ends the unsheltered.</p>\n'
          '        <p><span class="lemma">The shepherd&rsquo;s '
          'end.</span> The spectrum&rsquo;s bright pole, plainly: the '
          'old underground&rsquo;s work is rescue by smuggling &mdash; '
          'the believed-out beasts, the budding Mad, the wonders '
          'disbelief is killing, moved station by station past the '
          'wall to countries that will keep them &mdash; and its '
          'method is the chapter&rsquo;s quiet miracle: madness '
          'recruited to mercy, the carried worlds turned toward '
          'shelter, a training the sources say continues. The '
          'folio files it as the dispute below&rsquo;s best '
          'evidence.</p>\n'
          '        <p><span class="lemma">The storm&rsquo;s end.</span> '
          'The dark pole, plainly and briefly: the genocidal '
          'front&rsquo;s logic is the break&rsquo;s worst arithmetic '
          '&mdash; if the agreement is the prison, its keepers are '
          'the masses, and the cells that accepted the conclusion '
          'are named in the histories as weapons, not '
          'fellowships. The folio declines the catalog of their '
          'works and keeps the taxonomy&rsquo;s point: the same '
          'break, the same freedom, the same fees absorbed &mdash; '
          'and the difference is entirely the person the world '
          'was carried by.</p>\n'
          '        <p><span class="lemma">The walking no.</span> '
          'The deniers&rsquo; clause, plainly: their carried world '
          'is the street&rsquo;s own, minus every miracle &mdash; a '
          'madness of pure agreement &mdash; and their presence '
          'enforces it, blunting mystic art and the Union&rsquo;s '
          'science alike, which is the joke the margin has '
          'already filed: the agreement&rsquo;s perfect citizens '
          'are Mad, and neither great house can recruit them. '
          'The optional rule prices the blunting as unconscious '
          'counter-art, and the folio commends it: a denier in '
          'the room makes every caster feel the water&rsquo;s '
          'weight.</p>\n'
          '        <p><span class="lemma">Shed into the '
          'dream.</span> The far end&rsquo;s plain sense: past the '
          'deepest wearing the street releases the Mad One '
          'entirely &mdash; the carried world too heavy for the '
          'agreement to hold &mdash; and the released pass into '
          'the deeps, where the stuff of that country obeys '
          'them and their world becomes a place with an '
          'address. What that promotion is &mdash; exile, death, '
          'apotheosis, or all three filed under one stamp '
          '&mdash; is the verso&rsquo;s last dispute, and the '
          'binding&rsquo;s geography at least is settled: the countries are real, mapped among the dream-roads of chapter IV&rsquo;s deeps, and visitors have returned. The far country&rsquo;s law is the carried world&rsquo;s, enthroned: what bent the street as weather rules the province as physics, and the pilgrim who paid the deeps&rsquo; tolls arrives in a nation exactly as sane as its founder &mdash; which the dispute below will price.</p>',
 'inner_head': 'On the Fronts<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the bands, the poles, and the far '
               'end</span>',
 'name': 'The Weather',
 'outer': '<p><span class="lemma">Whether the weather can be an '
          'ally.</span> The alliance dispute. <span class="voice">Some '
          'say</span> never: an ally whose logic can reassign your '
          'role without notice is not an ally but a loaded sky, '
          'and every fellowship that has tried to aim the Mad '
          '&mdash; and the records hold several &mdash; ended holding '
          'the bill for weather it claimed to command; the '
          'shepherd&rsquo;s underground is no counter-example, being '
          'the Mad steering the Mad, which is exactly the '
          'law&rsquo;s point: the steering wheel is on the inside. '
          '<span class="voice">Others say</span> the inside has '
          'proven reachable: the underground finds the budding '
          'and turns their weather toward mercy, the '
          'half-lucid ringleaders parley and keep bargains by '
          'their own strange bookkeeping, and a chronicle&rsquo;s '
          'refusal to treat with the Mad at all forfeits the '
          'chapter&rsquo;s best material &mdash; the negotiation '
          'conducted in the other party&rsquo;s physics, paid in '
          'the other party&rsquo;s coin. The first school answers '
          'that every such bargain in the records is honored '
          'until the world&rsquo;s logic turns, and no diviner '
          'reads that calendar. The second answers that the '
          'same is said of princes, weather, and the Union, '
          'and the binding treats with all three. The folio '
          'prices the middle honestly: treat, never rely; '
          'accept gifts, never schedules; and keep the exits '
          'the counsel below demands. <span '
          'class="kw">TEYKU</span> &mdash; the steering wheel is '
          'on the inside, and sometimes the inside waves.</p>\n'
          '        <p><span class="lemma">What the far summit is '
          'worth.</span> The apotheosis dispute. <span '
          'class="voice">Some say</span> the shedding is the '
          'road&rsquo;s only honest ending and possibly its glory: '
          'the world too heavy for the street becomes a country '
          'in the deeps &mdash; sovereign, stable, sometimes '
          'visited &mdash; and if the binding honors the summit of '
          '46a, it must at least depose this one: a will that '
          'argued until the cosmos gave it a province. Some of '
          'the shed, the deep sources attest, sit among the '
          'dream&rsquo;s own lords. <span class="voice">Others '
          'say</span> read what was shed: the street, the '
          'sister still searching, the person the sympathy '
          'clause protected &mdash; the province is a hospice '
          'with sovereignty, and calling it a summit teaches '
          'the chronicle&rsquo;s cracking mages that the wall&rsquo;s '
          'far side is a promotion; the chapter&rsquo;s three '
          'breaks are three losses, and dressing the third in '
          'apotheosis is the one edit this folio must refuse. '
          'The first school answers that the same charge was '
          'read against every ascension this binding honors '
          '&mdash; the summit always sheds the street. The '
          'second answers that the honored summits are chosen '
          'with open eyes, and the shedding is a fall with '
          'better scenery &mdash; and there the chapter closes, '
          'on the difference between a summit and a place you '
          'can no longer leave, which is the difference the whole tractate exists to argue. The chapter&rsquo;s last rider binds both schools: whatever the summit is worth, the road to it is strewn with the chapter&rsquo;s three breaks, and the binding&rsquo;s counsel across all three is one sentence &mdash; nobody breaks alone who was accompanied, and the accompaniment is the fellowship&rsquo;s whole reason for existing, whatever chair it refuses.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the parley, and the summit</span>',
 'rubric': 'the fronts of the Mad',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Seventh: The Unseated '
             'and the Fallen, concluded &middot; of the Mad&rsquo;s fellowships',
 'title': 'Tractate Aliyah · Folio 234b — The Weather: the fronts of the Mad',
 'type': 'daf'}
