# Folio 250a - The Seder of Creation (seder; the ordered-procedure proof).
# The five steps per the wod-llm-wiki character-creation page
# (M20 pp.250-266). Arithmetic exiled to the inner commentary per the brief.
FOLIO = {'bottom': '<p><span class="lemma">On running the seder in session zero.</span> The order '
           'of making is the contract&rsquo;s natural companion: run them the same '
           'evening, characters built together at one table, each step spoken aloud in '
           'turn so the cabal is drafted as a body &mdash; who covers what, who knows '
           'whom, whose mentor owes whose a favor. The troupe that creates together '
           'has already played its first session; the sheets are the minutes.</p>\n'
           '        <p><span class="lemma">On the prelude.</span> The books counsel a '
           'short diceless scene of each mage&rsquo;s Awakening before play begins, '
           'and the counsel is good law: the prelude converts the sheet&rsquo;s '
           'choices into memories the player actually has, and the focus declared in '
           'step four stops being a list the moment she has cast through it once, '
           'even in flashback. Keep it short, keep it diceless, and end it at the '
           'moment the world first said yes.</p>\n'
           '        <p><span class="lemma">On the finished sheet.</span> The player '
           'who arrives with a completed character has done the seder alone, which '
           'is not a crime but a head start in the wrong race. Walk her sheet back '
           'through the steps at the table anyway &mdash; aloud, with the others '
           '&mdash; not to audit the arithmetic but to weave the concept into the '
           'cabal&rsquo;s; the numbers were never the point, and the walking-back '
           'is how she finds that out gently.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the zeroth evening, the '
                'prelude, and the early arrival</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The making of a mage is an order,</span> and the '
           'order is the law: each step before the next, and the person before them '
           'all.<sup>a</sup></p>\n'
           '        <p class="step"><span class="term">Step One.</span> Choose who she '
           'is before what she can do: the concept, the seat she answers to or the '
           'orphanhood she doesn&rsquo;t, the Essence of her Avatar, and the two '
           'faces of her temperament &mdash; the Nature she is and the Demeanor she '
           'shows.<sup>b</sup></p>\n'
           '        <p class="step"><span class="term">Step Two.</span> Weigh the '
           'body, the presence, and the mind against each other, first among them '
           'chosen, and the dots dealt by the priorities as the commentary '
           'keeps them.</p>\n'
           '        <p class="step"><span class="term">Step Three.</span> Weigh what '
           'she has learned: the talents that came free, the skills that came by '
           'practice, the knowledges that came by study, prioritized and dealt '
           'likewise.</p>\n'
           '        <p class="step"><span class="term">Step Four.</span> Give her a '
           'place in the world and a way of working it: the Backgrounds by their '
           'allowance, the Spheres by theirs &mdash; the first dot always in an '
           'affinity &mdash; her line&rsquo;s, or the orphan&rsquo;s own choosing '
           '&mdash; and no Sphere ever above her Arete, the dots '
           'prudently held open until the fifth step settles what Arete is '
           '&mdash; and the focus declared whole: the paradigm believed, the practice kept, the '
           'instruments held, seven at the least, all free of charge, for belief is not bought '
           'with points.<sup>c</sup></p>\n'
           '        <p class="step"><span class="term">Step Five.</span> Finish what '
           'makes her Awake: one dot of Arete given, more purchasable and capped '
           'low; the will at its starting strength; Quintessence pooled to the '
           'Avatar&rsquo;s measure; and Paradox at nothing, where it never '
           'stays.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence an '
           'order, and not a heap? Come and hear the seder&rsquo;s own logic: '
           'concept precedes numbers because the numbers describe her and a '
           'description needs a subject; the mundane precedes the magickal because '
           'the mage was a person first, and the Awakening broke into a life '
           'already furnished; and the focus costs nothing because it is not a '
           'possession but a grammar &mdash; the mage does not own her beliefs any '
           'more than a speaker owns her language. The steps are a liturgy in the '
           'plain sense: an order of service that builds a self, recited once per '
           'character and remembered at every advancement after. The disputants '
           'opposite hold the recensions&rsquo; quarrel over how the dots should '
           'be dealt, and the older quarrel over what should come first.</p>',
 'chapter': 'Chapter the Eighth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the first '
             'seder of the binding: the steps are the Text, and the arithmetic is '
             'exiled to the margins where it belongs. The freebies and the '
             'experience wait overleaf.',
 'folio': '250A',
 'glossL': '<p><span class="mark">a</span> On the five-step making, see M20, the '
           'character chapter, folios 250&ndash;266, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On concept, faction, Essence, '
           'and the two-faced temperament, see folios 250&ndash;256; the '
           'archetypes are catalogued in the same chapter.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On Backgrounds, '
           'Spheres, the affinity requirement, the Arete ceiling, and the free '
           'focus, see folios 256&ndash;259; the luachs of 273, 275, and 303, '
           'wanting, will chart what this seder deals.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the finishing '
           'touches &mdash; Arete&rsquo;s given dot and creation cap, the '
           'will&rsquo;s start, the Avatar-measured pool &mdash; see folio '
           '259; the supplementary manual&rsquo;s option adds a starting dot '
           'of Resonance among these touches, see the Book of Secrets at '
           'folios 133&ndash;134 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seder consults its luachs as '
           'a reader consults charts: Attributes at 273, Abilities at 275, '
           'Backgrounds at 303, all wanting and all promised against the '
           'chart-mold 435 proved. The Masoret keeps the shopping list.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The Essence '
           'chosen in step one is the Avatar&rsquo;s business, folio 43; the affinity dot of step four is the first sentence of a conversation 500 finishes.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Paradox at '
           'nothing, where it never stays: the joke is 533a&rsquo;s, told '
           'here at the one moment in a mage&rsquo;s existence when her '
           'account with the court is clean.</p>',
 'h1': 'The Seder of Creation',
 'hagahah': 'The character exists before the numbers, and the numbers exist to '
            'be argued with. Every table has one player who reads the seder '
            'backward, sheet-first, and the seder&rsquo;s first step is '
            'drafted, gently, to be her cure.',
 'inner': '<p><span class="lemma">Each step before the next.</span> The '
          'order&rsquo;s arithmetic, kept here as the brief exiles it: the '
          'traits of the body, presence, and mind are dealt seven, five, and '
          'three by chosen priority, each starting from its first dot &mdash; '
          'and the dealing may stack a gift high, as the book&rsquo;s own '
          'example raises one presence to its fourth; the learned things are '
          'dealt thirteen, nine, and five, from nothing, and none of those '
          'past its third at the making. The cap on the learned is the '
          'seder&rsquo;s quiet doctrine &mdash; talent may arrive outsized; '
          'expertise is earned &mdash; and the newly made mage is competent, '
          'not finished, the room left to grow the chronicle&rsquo;s '
          'fuel.</p>\n'
          '        <p><span class="lemma">The Nature she is and the Demeanor she '
          'shows.</span> The two faces&rsquo; plain sense: the temperament is '
          'entered twice &mdash; the archetype she truly is and the one she '
          'performs &mdash; and the gap between the entries is the sheet&rsquo;s '
          'first piece of drama, declared before a single die is dealt. The '
          'archetypes are the book&rsquo;s catalogued personalities, and the '
          'inner one is load-bearing: it is the self the will refreshes from, '
          'which makes honesty about it a resource decision as well as a '
          'literary one.</p>\n'
          '        <p><span class="lemma">The Essence of her Avatar.</span> Step '
          'one&rsquo;s deepest entry, plainly: the Essence names the temperament '
          'of the thing that Awakened her, chosen now and answered for across a '
          'whole career &mdash; the seder asks for it first because everything '
          'after is negotiable and this is not. Its full account is the '
          'Avatar&rsquo;s own folio, 43; the seder needs only the '
          'declaration, and the humility to know what it is declaring.</p>\n'
          '        <p><span class="lemma">By their allowance.</span> Step '
          'four&rsquo;s numbers: seven dots of Backgrounds, six of Spheres, '
          'the affinity dot mandatory among them, and the ceiling absolute '
          '&mdash; no Sphere above Arete, which at the making means no '
          'Sphere above three and usually none above two. The allowance is '
          'declared in this step and spent wisely in the next: the '
          'book&rsquo;s own example holds its six dots until the finishing '
          'touches raise Arete, then places them under the settled ceiling '
          '&mdash; the order names the budget before the purchase, as '
          'orders do. The allowance '
          'makes the young mage broad or deep but not both, and the '
          'choosing between them is the first thing her build says about '
          'her soul.</p>\n'
          '        <p><span class="lemma">All free of charge.</span> The '
          'focus clause&rsquo;s plain sense: the paradigm, the practice, '
          'and the seven instruments cost nothing because they are the '
          'terms on which everything else is possible &mdash; charging for '
          'them would price the language a character thinks in. The '
          'declaration is nonetheless binding: what is written in step four '
          'is what 533a&rsquo;s court will hold her to, and free is not '
          'the same as optional.</p>\n'
          '        <p><span class="lemma">One dot of Arete given.</span> '
          'Step five&rsquo;s numbers: the first dot of enlightenment comes '
          'with Awakening itself, the second and third are purchasable at '
          'the making and no more &mdash; the famous low cap, disputed '
          'opposite &mdash; the will starts at five, the Quintessence pool '
          'equals the Avatar background, and Paradox opens at zero. The '
          'finishing touches are short because they are the whole point: '
          'everything before them was a person, and these four numbers are '
          'what the Awakening did to her.</p>\n'
          '        <p><span class="lemma">Remembered at every advancement '
          'after.</span> The seder&rsquo;s afterlife, plainly: the order of '
          'making is also the order of growth &mdash; the same traits, '
          'raised by the experience ladder the verso keeps &mdash; and the '
          'discipline holds: concept governs purchases, or the sheet '
          'drifts into a toolkit. The Storyteller&rsquo;s cheapest test of '
          'any advancement is the seder&rsquo;s own first question, asked '
          'again: who is she, that she would learn this?</p>',
 'inner_head': 'On the Steps<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the arithmetic, exiled here</span>',
 'name': 'The Seder of Creation',
 'outer': '<p><span class="lemma">How the dots should be dealt.</span> The '
          'girsa, as the brief promised: the recensions quarrel over the '
          'dealing. The line this binding follows deals by priority &mdash; '
          'the categories ranked, the allowances fixed &mdash; and other '
          'manuscripts of the wider tradition have dealt freeform pools, '
          'point-buys, and hybrid schemes, each with its partisans. <span '
          'class="voice">Some say</span> priority is the wiser deal: it '
          'forces the shape of a person &mdash; strong somewhere, weak '
          'somewhere &mdash; where the freeform pool midwifes the smooth '
          'grey competence of the optimizer. <span class="voice">Others '
          'say</span> the priorities are training wheels that insult a '
          'thoughtful table: the player who would build a believable '
          'unevenness needs no scaffold, and the one who wouldn&rsquo;t '
          'will game any scheme you print. The tractate files the variants '
          'unharmonized, noting only that the priority deal survived every '
          'recension that tried to replace it, and that survival, in '
          'rules as in species, is data. A third culture deals no dots at all '
          'and narrates the sheet into being across a long-played prelude; the '
          'tractate mentions it because its partisans exist, and because the '
          'seder absorbs even this &mdash; the steps become scenes, and the '
          'order holds. The quarrel over dealing is older than any single '
          'scheme, and will outlive this one too.</p>\n'
          '        <p><span class="lemma">What should come first.</span> The '
          'older quarrel: concept-first against mechanics-first, the two '
          'table cultures. <span class="voice">Some say</span> the '
          'seder&rsquo;s own first step settles it &mdash; the person '
          'before the numbers, by law &mdash; and the player who opens the '
          'book at the freebie chart has recited the liturgy backward. '
          '<span class="voice">Others say</span> the settlement mistakes '
          'how imagination works for how it should work: many a beloved '
          'character began as a mechanic that intrigued &mdash; a Sphere '
          'pairing, an odd Background &mdash; and grew a soul around it, '
          'as pearls grow around grit. The first school keeps the '
          'liturgy; the second keeps the grit; and the seder, read '
          'closely, keeps both &mdash; for step one demands a concept and '
          'says nothing about where the concept came from. The tractate '
          'rules the quarrel a matter of doors, not destinations &mdash; and '
          'posts, for the table&rsquo;s peace, the one rule both cultures '
          'accept: whatever door she entered by, the character answers step '
          'one&rsquo;s question before the dice ever meet her.</p>\n'
          '        <p><span class="lemma">An order of service that builds a '
          'self.</span> The last difficulty is the form&rsquo;s: is the '
          'liturgical framing earned, or is this a spreadsheet in vestments? '
          '<span class="voice">Some say</span> vestments: the seder is a '
          'budget, the steps are line items, and dressing allocation as '
          'ritual is this binding&rsquo;s one running affectation. <span '
          'class="voice">Others say</span> attend to what the procedure '
          'actually does at a table: a group of people speak a person into '
          'existence in ordered turns, witnessing each other&rsquo;s '
          'choices, and at the end something exists that will be mourned '
          'if it dies &mdash; if that is not liturgy, the word has no '
          'referent. The tractate, which has bet its whole form on the '
          'second reading, declares its interest and lets the objection '
          'stand in print &mdash; an almanac, note, would have deleted '
          'it. <span class="kw">TEYKU</span> &mdash; the seder '
          'builds either way.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the deal, the door, and the '
               'vestments</span>',
 'rubric': 'the five steps, in their order',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making &middot; of the seder of creation &middot; the making as '
             'liturgy',
 'title': 'Tractate Aliyah · Folio 250a — The Seder of Creation: the five steps, in their order',
 'type': 'seder'}
