# Folio 250b - The Fifteen. Verso of the Seder of Creation: freebie
# points and the experience ladder, per the wod-llm-wiki
# character-creation page (M20 pp.250-266).
FOLIO = {'bottom': '<p><span class="lemma">On watching the fifteen.</span> The freebies are '
           'where a sheet confesses: the points scattered to round a person out, or '
           'stacked to sharpen a weapon. Neither is a sin, but the Storyteller should '
           'read the spending before the chronicle starts &mdash; the build that '
           'converts every liberty into combat reach is announcing which game its '
           'player came to play, and session zero is the time to answer the '
           'announcement, not the third session&rsquo;s ambush.</p>\n'
           '        <p><span class="lemma">On pricing growth in play.</span> The '
           'ladder&rsquo;s multipliers do the pacing if the awards are steady: a few '
           'points a session, a few more at a story&rsquo;s close, and the '
           'cheap-wide purchases stay tempting while the tall ones stay slow. '
           'Resist the lump-sum award; the ladder&rsquo;s whole design assumes '
           'drip, and a season&rsquo;s hoard spent at once turns the seder&rsquo;s '
           'liturgy back into shopping.</p>\n'
           '        <p><span class="lemma">On earning what money can&rsquo;t.</span> '
           'The option the books offer &mdash; Backgrounds grown by story instead '
           'of points &mdash; is the better custom where the table can sustain it: '
           'the ally courted, the sanctum built stone by stone, the mentor&rsquo;s '
           'trust earned in scenes. Charge points where the fiction was thin and '
           'nothing where it was thick; the sheet should lag the story, never '
           'lead it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on confessions, drip, '
                'and the better custom</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">After the dealing come the liberties.</span> '
           'Fifteen points are given free, and more may be borrowed against '
           'Flaws to the borrowing&rsquo;s cap; they buy at posted prices &mdash; '
           'dearest the Spheres, then the traits of the person, cheaper the '
           'learned things and the standing, cheapest the will &mdash; and '
           'Arete&rsquo;s creation ceiling holds against them: no liberty '
           'raises it past the third dot.<sup>a</sup> And after the making, '
           'growth is priced by the ladder of experience: the new thing cheap '
           'to begin and dear to deepen, each rise costing its current measure '
           'multiplied &mdash; the affinity Sphere kinder than the foreign '
           'one, enlightenment dearest of all, the will cheapest &mdash; and '
           'the Backgrounds, at the Storyteller&rsquo;s option, not bought at '
           'all but earned. The heaviest of the worldly entries &mdash; the '
           'body&rsquo;s enhancements, the sanctum, the totem &mdash; pay double '
           'where points buy them at all. And the ledger closes where the recto '
           'opened: no price on this page buys the first question&rsquo;s '
           'answer.<sup>b</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear one making, retold from the book&rsquo;s own worked '
           'example. A street kid with a wiseass mouth, no seat and no '
           'lineage, Awakens in the half-second a car does not kill her '
           '&mdash; entropy&rsquo;s child, evidently, and the dots follow the '
           'person: presence first, body second, mind last; the talents '
           'thick, the knowledges scraped together from libraries and '
           'screens, the skills thin as street learning is. Her Background '
           'is almost all Avatar &mdash; the accident of her survival was '
           'not an accident &mdash; and her focus is the gutter&rsquo;s own '
           'grammar: cards and blood and small offerings to a world of gods '
           'and monsters. Then the fifteen: a second... a third dot of '
           'enlightenment, the brawling rounded up, the streets deepened, '
           'an ally promoted to a mentor for a single point &mdash; and the '
           'sheet is a person, which was the assignment. The prelude the books '
           'commend would begin hers at the curb, in the half-second the world '
           'said yes.<sup>c</sup> The '
           'disputants opposite hold the two quarrels the liberties invite: '
           'what the fifteen do to fairness, and what the ladder&rsquo;s '
           'curve says about enlightenment.</p>',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Seder of Creation: the recto keeps the liturgy, this '
             'side keeps the ledger.',
 'folio': '250B',
 'glossL': '<p><span class="mark">a</span> On the fifteen freebie points, the '
           'Flaw cap, and the posted prices, see M20, the character chapter, '
           'folio 252; the creation ceiling on Arete is the same page&rsquo;s.</p>\n'
           '        <p><span class="mark">b</span> On the experience ladder, its '
           'current-rating multipliers, the affinity discount, and the '
           'earned-Backgrounds option, see the same folio; the doubled-cost '
           'Backgrounds are the text&rsquo;s own short list.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the worked '
           'example retold in the Gemara, see folios 260&ndash;261, where the '
           'book builds her step by step; the retelling honors the '
           'binding&rsquo;s first law and sends the reader there for the '
           'numbers.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the prelude '
           'that should follow any making, see folios 261&ndash;262 and the '
           'recto&rsquo;s counsel.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The ledger&rsquo;s dearest line '
           'is 328&rsquo;s subject, wanting: Arete priced at eight times its '
           'measure is the system&rsquo;s statement that enlightenment is not '
           'a purchase, and the Masoret files the multiplier beside the '
           'seekings that folio will keep.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'affinity discount is the seder&rsquo;s first-dot requirement '
           'paying dividends for a career: the line a mage belongs to '
           'shapes her prices forever, which the Traditions of chapter V '
           'would call doctrine and the Adepts would call lock-in.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'earned-Background custom is 303&rsquo;s dispute in advance, '
           'wanting: the only stats the Storyteller co-owns, and the only '
           'ones the ladder lets her refuse to sell.</p>',
 'h1': 'The Fifteen',
 'hagahah': 'Fifteen points, the price of three dots of will or two of '
            'magick: the system&rsquo;s last gift is small on purpose. A '
            'liberty that could buy anything would unmake the choosing, and '
            'the choosing &mdash; ask any player who has stared at the '
            'fifteen for an hour &mdash; is the character.',
 'inner': '<p><span class="lemma">Dearest the Spheres.</span> The price '
          'ladder&rsquo;s plain sense: the liberties buy magick at seven a '
          'dot, the person&rsquo;s traits at five, enlightenment at four '
          'under its hard ceiling, the learned things at two, standing at '
          'one, the will at one, and the Quintessence by fours. The '
          'gradient is doctrine in miniature: what you are costs more than '
          'what you know, and what bends the world costs most of all '
          '&mdash; the freebie chart is the setting&rsquo;s value theory '
          'printed as a shopping list.</p>\n'
          '        <p><span class="lemma">Borrowed against Flaws.</span> The '
          'borrowing&rsquo;s plain sense: weaknesses taken at the making pay '
          'out points to their printed cap of seven, and the cap is the '
          'clause&rsquo;s whole wisdom &mdash; enough to reward a character '
          'with real edges, too little to fund a monster built from '
          'disposable inconveniences. The Flaw that never appears in play '
          'was a loan the table forgot to collect, and the Storyteller is '
          'the collections office, with the chronicle&rsquo;s full term to '
          'call it in.</p>\n'
          '        <p><span class="lemma">Its current measure '
          'multiplied.</span> The ladder&rsquo;s plain sense: growth is '
          'priced convex &mdash; the fourth dot of anything costs more than '
          'the second, the multiplier keyed to what the trait already is '
          '&mdash; so breadth stays cheap for a career while height '
          'grows dear. The design pushes veterans wide, which is why old '
          'mages in this setting are interesting: the ladder made '
          'renaissance cheaper than perfection, and the characters '
          'followed the prices, as characters do.</p>\n'
          '        <p><span class="lemma">The will cheapest.</span> The '
          'ledger&rsquo;s kindest line, plainly: will is priced at one per dot '
          'at the making and at its bare current measure in play &mdash; the '
          'cheapest growth on either chart &mdash; and the pricing is an '
          'invitation the drafters meant: the trait every chapter of this '
          'binding leans on, from the purchased success to the breath '
          'underwater, is the one no build should ever need to skimp. The '
          'sheet that arrives will-poor was not economizing; it was misreading '
          'the game.</p>\n'
          '        <p><span class="lemma">The affinity Sphere kinder.</span> '
          'The discount&rsquo;s plain sense: the Sphere of one&rsquo;s line '
          'rises at seven times its measure against the foreign '
          'eight, a small kindness with a long doctrine inside it &mdash; '
          'the mage grows fastest along the grain of her own paradigm, and '
          'the price difference is the Consensus of her community working '
          'in her favor. The margin files the two readings; the arithmetic '
          'is indifferent to both.</p>\n'
          '        <p><span class="lemma">Not bought at all but '
          'earned.</span> The option&rsquo;s plain sense: Backgrounds are '
          'the sheet&rsquo;s only worldly entries &mdash; allies, standing, '
          'sanctums, wealth &mdash; and the books allow their growth to be '
          'story&rsquo;s alone, with the doubled prices for the heaviest of '
          'them where points are used at all. The clause makes the '
          'ledger&rsquo;s edge porous where the world is, and only there: '
          'no story earns a Sphere, and no purchase earns a friend worth '
          'the name.</p>',
 'inner_head': 'On the Ledger<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; prices, loans, and the curve</span>',
 'name': 'The Fifteen',
 'outer': '<p><span class="lemma">What the fifteen do to fairness.</span> The '
          'liberty dispute. <span class="voice">Some say</span> the freebies '
          'are the seder&rsquo;s loophole: the priorities force a shape and '
          'the fifteen sand it off, and between two players of unequal '
          'system mastery the same allowance builds characters of unequal '
          'power &mdash; the chart rewards exactly the fluency it never '
          'asks for. <span class="voice">Others say</span> the loophole is '
          'the valve: fifteen points is deliberately too few to rebuild a '
          'character, enough only to underline her &mdash; the optimizer '
          'gains an edge measured in single dice, and the table&rsquo;s '
          'real defense was never the chart but the recto&rsquo;s first '
          'step, enforced. The schools agree the danger scales with the '
          'points, which is why the borrowing is capped; the tractate adds '
          'the empirical note that every long chronicle&rsquo;s roster '
          'converges anyway, as play files the min-maxed sheet&rsquo;s '
          'edges smooth &mdash; the chronicle is long, the chart was one '
          'evening, and no fifteen points survive contact with three seasons '
          'of consequences.</p>\n'
          '        <p><span class="lemma">What the curve says about '
          'enlightenment.</span> The ladder dispute, and the verso&rsquo;s '
          'real subject. Arete rises at eight times its current measure '
          '&mdash; the steepest line on the chart &mdash; and the books '
          'elsewhere hedge it with seekings and trials no points can '
          'shortcut. <span class="voice">Some say</span> the price is '
          'pacing and nothing deeper: enlightenment is the game&rsquo;s '
          'throttle, and the multiplier is the drafters governing power '
          'curves, not preaching. <span class="voice">Others say</span> '
          'read the whole ledger: everything a mage can buy grows convex, '
          'but only Arete&rsquo;s purchases are also gated by story &mdash; '
          'the number is necessary and not sufficient, the points spend '
          'only when the soul has done the work, and the chart is thereby '
          'the one place the system says aloud that its deepest trait '
          'cannot actually be purchased. The first school runs smoother '
          'campaigns; the second is why 328 and the seekings exist, '
          'wanting; and the tractate notes that both schools charge the '
          'same eight. <span class="kw">TEYKU</span> &mdash; the ladder '
          'holds while the schools climb it.</p>\n'
          '        <p><span class="lemma">The sheet is a person.</span> A '
          'last difficulty, inherited from the Gemara&rsquo;s retelling: '
          'the book teaches its ledger through a worked example with a '
          'name and a nearly fatal afternoon, and the choice is doctrine. '
          '<span class="voice">Some say</span> the example is pedagogy, '
          'no more: numbers teach badly in the abstract. <span '
          'class="voice">Others say</span> the drafters were making the '
          'recto&rsquo;s argument in their own medium &mdash; the '
          'arithmetic arrives pre-attached to a person because it should '
          'never exist otherwise, and a rulebook that builds its sample '
          'character soul-first has taken sides in the door quarrel '
          'opposite. The tractate concurs, and observes that it retold '
          'the example as aggada for exactly the same reason. The '
          'example&rsquo;s other lesson goes unspoken in the book and is '
          'recorded here: she spent her liberties on what she already was '
          '&mdash; the streets deepened, the fists steadied, the luck made '
          'formal &mdash; and a table could do worse than adopt the rule her '
          'sheet implies: the fifteen underline; they do not revise.</p>',
 'outer_head': 'The Auditors<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the valve, the curve, and the '
               'example</span>',
 'rubric': 'the liberties, and the ladder of growth',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the fifteen &middot; the liberties '
             'as law',
 'title': 'Tractate Aliyah · Folio 250b — The Fifteen: the liberties, and the ladder of growth',
 'type': 'daf'}
