# Folio 273b - The Ladder (luach). The one-to-five scale, specialties,
# and the measures past five, per the wod-llm-wiki attributes hub and
# character-creation page (M20 ch.6; Background Traits Over Five p.301).
FOLIO = {'bottom': '<p><span class="lemma">On saying the epithet aloud.</span> The '
           'ladder&rsquo;s words are table tools: announce the epithet, not the '
           'number, when a trait is tested &mdash; a good climber, an '
           'exceptional liar &mdash; and the fiction stays in front of the '
           'arithmetic. Players who hear words respond with description; '
           'players who hear numbers respond with more numbers.</p>\n'
           '        <p><span class="lemma">On earning the specialty.</span> '
           'Let specialties arrive from play when possible: the fourth dot '
           'bought after the campaign&rsquo;s great chase deserves to be '
           '<span class="aside">Dexterity: pursuit driving</span>, and a '
           'specialty with a scene behind it is characterization the '
           'sheet did for free. Assigned specialties work; earned ones '
           'sing.</p>\n'
           '        <p><span class="lemma">On the fives at the '
           'table.</span> A five deserves staging: the peerless surgeon, '
           'the once-a-generation beauty, the strategist banks retain. '
           'When a five rolls badly, narrate interference, not '
           'incompetence &mdash; the chart&rsquo;s top rung does not '
           'stumble; it is stumbled into &mdash; and the table&rsquo;s '
           'faith in the ladder survives the dice.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on epithets, earned '
                'edges, and staging the top rung</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The ladder runs one to five,</span> and '
           'the chart names its rungs; at the fourth and above a measure '
           'takes a <span class="term">specialty</span> &mdash; a named '
           'edge within the trait &mdash; and past the fifth the ladder continues only for the inhuman, by the standing rule the margin cites. Each rung is one die in the hand of 385a; the epithets below are the dice translated into promises.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Rung</th><th>Epithet</th><th>Its sense</th></tr>\n'
           '          <tr><td class="num">&bull;</td><td><span class="term">Poor</span></td>'
           '<td>below the street&rsquo;s average; the trait is a liability the '
           'character manages</td></tr>\n'
           '          <tr><td class="num">&bull;&bull;</td><td><span class="term">Average</span></td>'
           '<td>the crowd&rsquo;s own measure; most of everyone, most of the '
           'time</td></tr>\n'
           '          <tr><td class="num">&bull;&bull;&bull;</td><td><span class="term">Good</span></td>'
           '<td>noticeably able; the friend you call when this trait is the '
           'problem</td></tr>\n'
           '          <tr><td class="num">&bull;&bull;&bull;&bull;</td><td><span class="term">Exceptional</span></td>'
           '<td>the professional&rsquo;s professional; a specialty names the '
           'edge</td></tr>\n'
           '          <tr><td class="num">&bull;&bull;&bull;&bull;&bull;</td><td><span class="term">Peerless</span></td>'
           '<td>the mortal summit; one in a generation stands here, and the '
           'street tells stories</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear what the ladder is for. A number alone is a wall socket; '
           'the epithet is the appliance. When the chart says three it means '
           'the friend you call, when it says five it means the stories the '
           'street tells &mdash; and the whole apparatus of pools and walls '
           'built at 385a stands on these five words meaning the same thing '
           'at every table. The rungs are a shared language before they are '
           'arithmetic, which is why the chart spends its ink on epithets '
           'and leaves the probabilities to the folio that loves them. The '
           'commentaries hold the edges: the specialty&rsquo;s law, the '
           'inhuman&rsquo;s ladder, and the question of what a five means in a world that contains mages. One more service the ladder renders: it is the binding&rsquo;s unit of comparison across every chart &mdash; the walls of 82a, the grades of the deeps, the ranks of the arts all borrow this five-runged grammar &mdash; so the reader who internalizes these epithets has learned to read not one page but the whole shelf, which is why the chapter posts the ladder before anything climbs it. And the posting is timed: the reader arrives here between the measures and the learnings, so the rungs are learned once and spent twice, recto and verso alike.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso '
             'of the nine measures: the rungs named, the edges priced; the '
             'learnings wait at folio 275.',
 'folio': '273B',
 'glossL': '<p><span class="mark">a</span> On the one-to-five ladder and its '
           'epithets, see M20, the sixth chapter&rsquo;s trait entries, '
           'restated here in the binding&rsquo;s own words per its standing '
           'law.</p>\n'
           '        <p><span class="mark">b</span> On specialties at the '
           'fourth dot &mdash; the named edge, its reroll custom on tens '
           '&mdash; see the same chapter; the custom&rsquo;s grain is the '
           'source&rsquo;s and the margin keeps only the band.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On traits '
           'past five for the inhuman and the great, see the standing rule '
           'at folio 301, whose neighbors are the Backgrounds this '
           'chapter charts at 303.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'measures&rsquo; testing &mdash; pools, walls, and the count of '
           'successes &mdash; see the dice folio of this binding, 385a, '
           'and its sources.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The ladder&rsquo;s arithmetic '
           'lives at 385a &mdash; each rung one die in the hand &mdash; and '
           'the epithets live here; the two folios are one trait read as '
           'word and as number, and the Masoret binds them as such.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'specialty&rsquo;s cousin in the arts is the affinity of 500a and '
           'the instrument&rsquo;s intimacy at 586a: the binding prices '
           'named closeness everywhere, and the margin collects the '
           'family resemblance.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'inhuman ladders past five belong to the sibling tractates on '
           'the shelf &mdash; the night-lords&rsquo; elders, the '
           'wolves&rsquo; totems &mdash; and to the enthroned of 91b; this '
           'binding&rsquo;s mortals stop at five and argue below about '
           'what that means.</p>',
 'h1': 'The Ladder',
 'hagahah': 'Five means one in a generation. The generation, notably, was '
            'not consulted.',
 'inner': '<p><span class="lemma">Words before numbers.</span> The '
          'epithet row&rsquo;s plain sense: the chart defines its rungs in '
          'language because the rungs are promises between strangers '
          '&mdash; a three written by one Storyteller must mean a three '
          'to the next table &mdash; and the shared meanings are what '
          'let the binding&rsquo;s hundreds of numbered claims travel. '
          'The arithmetic is portable because the poetry is standard, '
          'which is the reverse of how the design is usually '
          'praised.</p>\n'
          '        <p><span class="lemma">The crowded second '
          'rung.</span> The average&rsquo;s plain sense: two is where '
          'the world lives &mdash; the crowd&rsquo;s own measure &mdash; '
          'and the consequence for staging is statistical: the '
          'chronicle&rsquo;s streets are full of twos, its named cast '
          'threes, and a single four changes a room. The ladder is '
          'steep on purpose; the counsel opposite spends the '
          'steepness.</p>\n'
          '        <p><span class="lemma">The named edge.</span> The '
          'specialty&rsquo;s plain sense: at the fourth dot the trait '
          'stops being general &mdash; the exceptional are exceptional '
          '<span class="aside">at something</span> &mdash; and the '
          'named edge carries the custom of the rerolled tens within '
          'its province, banded here per the standing rule. The '
          'design&rsquo;s claim is about mastery itself: past a '
          'certain height, ability has a shape, and the sheet makes the shape a word the table can stage. The custom of the rerolled tens within the specialty&rsquo;s province is the mechanical dividend, banded here per the standing rule; the characterization is the real interest.</p>\n'
          '        <p><span class="lemma">Past five, the '
          'inhuman.</span> The ceiling&rsquo;s plain sense: the mortal '
          'ladder ends at peerless, and the rungs above are reserved '
          '&mdash; elders of the night, spirits enthroned, the great '
          'and the monstrous &mdash; by the standing rule the margin '
          'cites. The reservation is load-bearing for the whole '
          'binding: when a folio says a thing rolls eight dice of '
          'Strength, it is saying <span class="aside">not '
          'mortal</span> in the chart&rsquo;s own grammar, no adjective '
          'required.</p>\n'
          '        <p><span class="lemma">One die per rung.</span> The '
          'conversion&rsquo;s plain sense, stated once for the shelf: '
          'each dot is a die in the hand of 385a, the epithets are '
          'therefore also probabilities, and the good and the '
          'peerless differ at the table by two dice and at the '
          'street by a career. The gap between how large the words '
          'feel and how small the dice run is the design&rsquo;s '
          'known tension, and the dice folio&rsquo;s margins have '
          'already argued it; this chart only supplies the words.</p>\n        <p><span class="lemma">The borrowed grammar.</span> The ladder&rsquo;s reach, plainly: every system in the binding borrows these five rungs &mdash; the backgrounds scale scope on them, the arts rank on them, and the sibling tractates on the shelf rate their elders by the same dots &mdash; so the five-dot scale is the press&rsquo;s one universal currency and this chart is its mint. The consequence compounds for the reader: every folio&rsquo;s numbers are this folio&rsquo;s words, and a binding that glossed three dots afresh on every page would be twice as long and half as read.</p>',
 'inner_head': 'On the Rungs<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; rung by rung, edge by edge</span>',
 'name': 'The Ladder',
 'outer': '<p><span class="lemma">What a five means in a world with '
          'mages.</span> The summit dispute, as the brief demands. <span '
          'class="voice">Some say</span> the ladder is untouched by the '
          'Awakening: five means the mortal summit and means it still '
          '&mdash; the mage&rsquo;s advantage is the arts, not the '
          'measures, and a peerless Sleeper out-lifts, out-argues, and '
          'out-thinks an average willworker all day long; the chart is '
          'the one democracy the setting keeps, and the binding should '
          'guard it. <span class="voice">Others say</span> the '
          'democracy is nominal: the arts of chapter XI rewrite the '
          'body of 516a and the mind of 519a, the pattern-smiths '
          'wear whatever measures they can afford, and a summit '
          'anyone with the right folio can visit by lunch is a '
          'scenic overlook, not a peak &mdash; the five still prices '
          'mortal effort, but mortal effort is no longer the only '
          'currency at the counter. The first school answers that '
          'the bought summit is temporary, priced, and billed by '
          '533a&rsquo;s court, while the earned one is free forever '
          '&mdash; the democracy holds precisely because the '
          'shortcuts are taxed. The second answers that a tax is '
          'not a wall, and asks the first school what the epithet '
          'peerless means on a street where peers can be '
          'manufactured. The folio files the dispute where the '
          'setting files it &mdash; unresolved, and load-bearing for '
          'every scene where a mortal excellence meets a bought '
          'one &mdash; and notes which school every player '
          'character has already voted for with their build. <span '
          'class="kw">TEYKU</span> &mdash; the generation&rsquo;s one '
          'stands where she stood; the question is who else is '
          'standing there, and how they got up.</p>\n'
          '        <p><span class="lemma">The ladder&rsquo;s missing '
          'zero.</span> The floor dispute. <span class="voice">Some '
          'say</span> the missing zero is the chart&rsquo;s deepest '
          'kindness: no living soul rates nothing in any measure, '
          'the baseline dot is a statement about persons before it '
          'is a rule, and the learnings overleaf keep the zeros so '
          'that absence of training never reads as absence of '
          'worth. <span class="voice">Others say</span> the kindness '
          'is also a flattening: the setting holds beings whose '
          'measures genuinely fail &mdash; the disembodied, the '
          'broken, the made things of 190b before the vats finish '
          '&mdash; and a chart with no floor beneath poor must '
          'handle them by exception, which the books duly, '
          'awkwardly, do. The schools agree the exception list is '
          'short and the kindness worth its price; the folio '
          'records the agreement &mdash; rare on this shelf &mdash; '
          'and the margin moves on to the learnings, where the zeros live and the asymmetries begin. And the floor&rsquo;s last footnote is the summit&rsquo;s mirror: as the ladder caps mortals at five, it floors persons at one &mdash; the chart brackets the human at both ends, and every folio that prices the more-than or the less-than does so by leaving this page, visibly, which is what a baseline is for. The brackets, the surveyors note, are the chart&rsquo;s real product; the rungs merely furnish the room between them.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the summit, and the floor</span>',
 'rubric': 'the rungs, named',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the ladder &middot; the scale as chart',
 'title': 'Tractate Aliyah · Folio 273b — The Ladder: the rungs, named',
 'type': 'luach'}
