# Folio 273a - Attributes (luach). The nine measures, per the
# wod-llm-wiki attributes hub (M20 ch.6; the Abilities open at p.274).
FOLIO = {'bottom': '<p><span class="lemma">On rating strangers quickly.</span> The '
           'chart&rsquo;s best table use is triage: most people are ones and '
           'twos in everything, the memorable have one three, and the '
           'chronicle&rsquo;s named cast get a single column that matters. '
           'Rate NPCs by what the scene will test and leave the rest '
           'unwritten &mdash; a bouncer is a Strength, a fence is a '
           'Manipulation, and neither needs the other seven filled in.</p>\n'
           '        <p><span class="lemma">On not rolling the '
           'obvious.</span> The baseline dot means everyone can try '
           'everything, and the counsel is its converse: do not roll what '
           'a one can simply do. Climbing stairs, recalling a name, '
           'making small talk &mdash; the dice come out when the outcome '
           'is in doubt and the doubt is interesting, which the measures '
           'chapter says in its own voice and Storytellers forget '
           'weekly.</p>\n'
           '        <p><span class="lemma">On the column as '
           'character.</span> The 7/5/3 priority is the sheet&rsquo;s '
           'first characterization: which house got the seven says what '
           'the character trusts when plans fail. Ask the player to '
           'answer in fiction &mdash; muscle, charm, or wits first? '
           '&mdash; before any dot is placed, and the arithmetic will '
           'follow the person instead of leading.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on triage, doubt, '
                'and the first seven</span>',
 'center': '<p class="noindent"><span class="dropcap">N</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Nine measures, three houses.</span> An '
           'Attribute measures what a soul is before any training '
           'touches it &mdash; the raw stock &mdash; and every living '
           'character holds each of the nine at one dot by right of '
           'being alive; the ladder runs one to five, the ordinary to '
           'the peerless, as the chart provides.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Measure</th><th>House</th><th>What it weighs</th></tr>\n'
           '          <tr><td><span class="term">Strength</span></td><td>the body</td>'
           '<td>the frame&rsquo;s raw power &mdash; what can be lifted, broken, '
           'and struck through</td></tr>\n'
           '          <tr><td><span class="term">Dexterity</span></td><td>the body</td>'
           '<td>quickness and precision of limb &mdash; grace under motion</td></tr>\n'
           '          <tr><td><span class="term">Stamina</span></td><td>the body</td>'
           '<td>the endurance that absorbs punishment &mdash; the root of the '
           'soak</td></tr>\n'
           '          <tr><td><span class="term">Charisma</span></td><td>the company</td>'
           '<td>the warmth that draws others in &mdash; presence, not '
           'prettiness</td></tr>\n'
           '          <tr><td><span class="term">Manipulation</span></td><td>the company</td>'
           '<td>the craft of steering others &mdash; persuasion with the '
           'gloves on or off</td></tr>\n'
           '          <tr><td><span class="term">Appearance</span></td><td>the company</td>'
           '<td>the first impression the body makes before a word is '
           'said</td></tr>\n'
           '          <tr><td><span class="term">Perception</span></td><td>the mind</td>'
           '<td>the attention that notices &mdash; senses and intuition '
           'together</td></tr>\n'
           '          <tr><td><span class="term">Intelligence</span></td><td>the mind</td>'
           '<td>reasoning and recall &mdash; the thought that holds complexity '
           'still</td></tr>\n'
           '          <tr><td><span class="term">Wits</span></td><td>the mind</td>'
           '<td>the mind&rsquo;s reflexes &mdash; the answer found while the '
           'question is still moving</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why '
           'nine, and why three houses? Come and hear: because the sheet is '
           'a census of the whole person taken three ways &mdash; what the '
           'body can do, what the company will grant, what the mind can '
           'hold &mdash; and each way asked three times: the power, the '
           'finesse, the resistance of each house in turn. The grid is '
           'older than this game and the chart does not pretend otherwise; '
           'what the chart adds is the priority of houses, seven and five '
           'and three, which is the first question the making of a character asks and the seder of 250a asks it. The houses also school the reader in the grid&rsquo;s grammar: within each, one measure forces, one finesses, one endures &mdash; three questions asked three ways &mdash; and a sheet read down its columns is a portrait taken from three angles, which is the census&rsquo;s quiet ambition. What a single dot is worth, and what five, the ladder overleaf will say. The commentaries hold the houses&rsquo; edges and the '
           'ladder&rsquo;s meaning, which waits overleaf.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'second luach of the binding, batched against the proof of 435: '
             'the nine measures here, their ladder overleaf.',
 'folio': '273A',
 'glossL': '<p><span class="mark">a</span> On the nine Attributes and their '
           'three groupings, see M20, the sixth chapter, whose Attribute '
           'entries run to folio 273, whence this page takes its number; '
           'the Abilities open at 274, overleaf of this chart in both '
           'books.</p>\n'
           '        <p><span class="mark">b</span> On the baseline dot and '
           'the one-to-five ladder, see the same entries; the '
           'ladder&rsquo;s epithets are charted overleaf with their own '
           'apparatus.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'priority of houses &mdash; seven, five, and three &mdash; see '
           'the making of characters, folios 250&ndash;266, and the seder '
           'bound at 250a.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'specialties at the fourth dot and the measures past five kept '
           'for the inhuman, see folios 270&ndash;273 and 301, abridged '
           'here per the luachs&rsquo; standing rule.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The chart is the first '
           'shelf the seder of 250a consults: step two of the making is '
           'this page read with a pencil, and the arithmetic exiled from '
           'that folio&rsquo;s center lives in these margins, as its '
           'Masoret promised.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Every '
           'row above is half a pool: the measures join the learnings of '
           '275 to make the hands of 385a, and the three folios should '
           'be shelved within reach of one another, as the dice folio '
           'already noted.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'soak rooted in Stamina is 406a&rsquo;s law; the Initiative '
           'seated in Wits is 409a&rsquo;s; and the first impressions of '
           'Appearance are argued wherever the company gathers, which '
           'is every chapter with a court in it.</p>',
 'h1': 'Attributes',
 'hagahah': 'The sheet asks what you are before it asks what you know. '
            'The order is the game&rsquo;s first theology.',
 'inner': '<p><span class="lemma">The house of the body.</span> The first '
          'column&rsquo;s plain sense: Strength, Dexterity, and Stamina '
          'are the flesh&rsquo;s three verdicts &mdash; power, precision, '
          'persistence &mdash; and the chart&rsquo;s order within the '
          'house repeats across all three houses: what forces, what '
          'finesses, what endures. A reader who learns the pattern '
          'once owns the whole grid, which is the design&rsquo;s quiet gift to the table. The body&rsquo;s house also carries the chapter&rsquo;s most-audited numbers: the soak of 406a stands on Stamina, the ladders of 409a open on Dexterity, and a chronicle&rsquo;s violence is priced almost entirely in this column, which the counsel of chapter X will spend in full.</p>\n'
          '        <p><span class="lemma">The house of the '
          'company.</span> The second column&rsquo;s plain sense, and its '
          'famous asymmetry: Charisma is the pull that needs no plan, '
          'Manipulation the plan that needs no pull, and Appearance '
          'the verdict rendered before either can speak. The three '
          'are priced separately because the setting means them '
          'separately: the beloved, the persuasive, and the striking '
          'are three careers, and every court in this binding can '
          'name members who hold one at five and the others at '
          'one.</p>\n'
          '        <p><span class="lemma">The house of the mind.</span> '
          'The third column&rsquo;s plain sense: Perception is the '
          'gate, Intelligence the warehouse, Wits the corridor '
          'between them at speed. The chart seats the '
          'chronicle&rsquo;s two most-rolled numbers here &mdash; the noticing that begins scenes and the reflexes that begin fights &mdash; and the counsel below spends the fact. Perception&rsquo;s pairing with Awareness at 275a is the hidden world&rsquo;s doorbell, and the folio notes the design&rsquo;s kindness: the measure that notices is mundane, so anyone &mdash; Sleeper, walker, or watcher &mdash; may stand at the door.</p>\n'
          '        <p><span class="lemma">One dot by right of being '
          'alive.</span> The baseline&rsquo;s plain sense: no living '
          'character rates zero in any measure &mdash; the first dot '
          'is not bought but granted &mdash; and the grant is the '
          'chart&rsquo;s statement about persons: everyone can lift, '
          'charm, and notice something. The zeros of this binding '
          'are reserved for the learnings overleaf, which may be '
          'absent in a way that being alive cannot.</p>\n'
          '        <p><span class="lemma">Seven, five, and '
          'three.</span> The priority&rsquo;s plain sense: the making '
          'ranks the houses, not the measures &mdash; the seven '
          'spread within the favored house as the player pleases, '
          'atop the granted ones &mdash; and the ranking is '
          'permanent enough to matter: experience raises single '
          'measures dearly, but no later purchase re-ranks the '
          'houses&rsquo; first statement. The sheet&rsquo;s opening '
          'arithmetic is thus its least reversible sentence, '
          'which the seder&rsquo;s counsel already flagged.</p>\n        <p><span class="lemma">Rolled in company.</span> The pairing clause, plainly: most pools join a measure to a learning of 275, but the measures also pair with one another where no training applies &mdash; the lift, the chase, the first impression &mdash; and the paired-measure roll is the chart&rsquo;s proof that the nine are complete tools rather than half-tools awaiting their partners. The grammar is 385a&rsquo;s; the chart supplies the left hand.</p>',
 'inner_head': 'On the Houses<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; column by column</span>',
 'name': 'Attributes',
 'outer': '<p><span class="lemma">Why nine and not ten.</span> The census '
          'dispute. <span class="voice">Some say</span> the grid is '
          'complete by construction: three houses, each asked for its '
          'power, finesse, and endurance, closes a square no tenth '
          'measure can enter without breaking &mdash; the missing '
          'candidates are all learnings in disguise, and the chart&rsquo;s '
          'discipline is what keeps the sheet a census instead of a '
          'shopping list. <span class="voice">Others say</span> the grid '
          'shows its age at the corners: the setting&rsquo;s own folios '
          'lean on measures the nine only approximate &mdash; the '
          'sensitivity the waking runs on, the composure the duels of '
          '430b wound &mdash; and the sibling games of the same press '
          'have counted differently in every generation, which is '
          'evidence the square is convention, not geometry. The first '
          'school answers that convention held for three decades of '
          'printings is what geometry looks like in publishing. The '
          'second answers that the wild talents and will-measures '
          'the books keep adding are the tenth measure knocking. The '
          'folio files the grid as the binding&rsquo;s standing frame '
          'and the knocking as its margin, which is where this binding keeps all its knocking. The dispute&rsquo;s practical face is the open shelf of 275b: what the nine cannot hold, the learnings absorb &mdash; and the grid survives precisely because its neighbor sprawls, a division of labor the surveyors commend to every taxonomy with a door.</p>\n'
          '        <p><span class="lemma">Born, or built.</span> The '
          'nature dispute. <span class="voice">Some say</span> the '
          'measures are stock: what a soul brought to the table, '
          'trained at the edges but issued at birth &mdash; the chart '
          'says raw for a reason, and the learnings overleaf exist '
          'precisely to hold everything acquired. <span '
          'class="voice">Others say</span> the sheet itself refutes '
          'the stock reading: experience raises measures, years in '
          'the gym raise Strength and years at court raise '
          'Manipulation, and a trait that grows by practice is a '
          'practice &mdash; the raw is just the learned too old to '
          'remember learning. The stakes are a table&rsquo;s: whether '
          'the campaign narrates attribute growth as revelation of '
          'what was always there or as construction of what was '
          'not, and the books, read closely, print both narrations '
          'in different chapters without blushing. The folio files '
          'the girsa unharmonized and notes the wager both schools '
          'take: whichever reading holds, the number on the sheet '
          'is what rolls &mdash; and the chapter&rsquo;s deeper measures, the will and the spark at 328, inherit this dispute with interest, as their folio confesses in its turn. One rider both schools sign for the table: whichever theology holds, growth should be narrated &mdash; the raised measure deserves its montage, revelation or construction as the chronicle prefers &mdash; for a number that changes silently teaches the players that the sheet is paperwork, and the whole chapter exists to argue otherwise. The montage, the surveyors add, doubles as the table&rsquo;s audit: growth narrated is growth witnessed, and witnessed numbers stay honest longer than logged ones.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the census, and the stock</span>',
 'rubric': 'the nine measures',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the Attributes &middot; the raw stock '
             'as chart',
 'title': 'Tractate Aliyah · Folio 273a — Attributes: the nine measures',
 'type': 'luach'}
