# Folio 275a - Abilities (luach). Talents and Skills, per the
# wod-llm-wiki abilities hub (M20 ch.6 pp.274-289).
FOLIO = {'bottom': '<p><span class="lemma">On reading the sheet as biography.</span> '
           'The learnings are where a character&rsquo;s history lives: every dot '
           'is a year spent somewhere, and the Storyteller who asks '
           '<span class="aside">where did you learn that?</span> at character '
           'creation harvests a backstory the player did not know they were '
           'writing. Three questions per sheet is a prelude for free.</p>\n'
           '        <p><span class="lemma">On the untrained attempt.</span> '
           'Let players try things they have no dots in whenever the kind '
           'permits: the untrained brawl, the fumbled lockpick at a higher '
           'wall. The asymmetry between the kinds is the system teaching '
           'through play what talent, training, and study mean &mdash; and '
           'a table that feels the difference has learned the '
           'chapter.</p>\n'
           '        <p><span class="lemma">On the missing column.</span> '
           'When a chronicle needs a learning the chart omits, the '
           'books&rsquo; own answer is the open categories the verso '
           'glosses: name it, place its kind, and play. The chart is a '
           'floor, not a fence &mdash; but place new learnings sparingly, '
           'for a sheet of bespoke columns defeats the shared language '
           'the luachs exist to keep.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on biography, fumbles, '
                'and the open categories</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The learnings come in three kinds,</span> '
           'and the kinds differ at the untrained hand: a <span '
           'class="term">Talent</span> is innate, attempted freely by '
           'anyone; a <span class="term">Skill</span> is trained, and the '
           'untrained attempt climbs one wall higher; a <span '
           'class="term">Knowledge</span> is studied, and without a dot it '
           'is commonly not attempted at all. The first two kinds the '
           'chart gives here; the third waits overleaf.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Learning</th><th>Kind</th><th>Its province</th></tr>\n'
           '          <tr><td><span class="term">Alertness</span></td><td>talent</td>'
           '<td>noticing what approaches before it announces itself</td></tr>\n'
           '          <tr><td><span class="term">Art</span></td><td>talent</td>'
           '<td>making beauty in any medium the maker owns</td></tr>\n'
           '          <tr><td><span class="term">Athletics</span></td><td>talent</td>'
           '<td>the run, the climb, the swim, the thrown ball</td></tr>\n'
           '          <tr><td><span class="term">Awareness</span></td><td>talent</td>'
           '<td>the prickle at the hidden world&rsquo;s edges</td></tr>\n'
           '          <tr><td><span class="term">Brawl</span></td><td>talent</td>'
           '<td>fighting with what you were born holding</td></tr>\n'
           '          <tr><td><span class="term">Empathy</span></td><td>talent</td>'
           '<td>reading hearts, and moving them</td></tr>\n'
           '          <tr><td><span class="term">Expression</span></td><td>talent</td>'
           '<td>saying it so the room remembers</td></tr>\n'
           '          <tr><td><span class="term">Intimidation</span></td><td>talent</td>'
           '<td>winning by the promise of losing badly</td></tr>\n'
           '          <tr><td><span class="term">Leadership</span></td><td>talent</td>'
           '<td>being followed, and deserving it enough to keep it</td></tr>\n'
           '          <tr><td><span class="term">Streetwise</span></td><td>talent</td>'
           '<td>the city&rsquo;s underside navigated as a native</td></tr>\n'
           '          <tr><td><span class="term">Subterfuge</span></td><td>talent</td>'
           '<td>wearing faces, and seeing through worn ones</td></tr>\n'
           '          <tr><td><span class="term">Crafts</span></td><td>skill</td>'
           '<td>making and mending by hand, trade by trade</td></tr>\n'
           '          <tr><td><span class="term">Drive</span></td><td>skill</td>'
           '<td>the vehicle held steady when steady is hard</td></tr>\n'
           '          <tr><td><span class="term">Etiquette</span></td><td>skill</td>'
           '<td>the right fork, the right bow, the right silence</td></tr>\n'
           '          <tr><td><span class="term">Firearms</span></td><td>skill</td>'
           '<td>guns kept, carried, and used</td></tr>\n'
           '          <tr><td><span class="term">Martial Arts</span></td><td>skill</td>'
           '<td>the schooled fight, form by form</td></tr>\n'
           '          <tr><td><span class="term">Meditation</span></td><td>skill</td>'
           '<td>the mind stilled on purpose; the well of 78a refreshed</td></tr>\n'
           '          <tr><td><span class="term">Melee</span></td><td>skill</td>'
           '<td>the armed hand at arm&rsquo;s length</td></tr>\n'
           '          <tr><td><span class="term">Research</span></td><td>skill</td>'
           '<td>finding what is written down, wherever it hid</td></tr>\n'
           '          <tr><td><span class="term">Stealth</span></td><td>skill</td>'
           '<td>being elsewhere as far as anyone can tell</td></tr>\n'
           '          <tr><td><span class="term">Survival</span></td><td>skill</td>'
           '<td>living where the city ends, or where it fails</td></tr>\n'
           '          <tr><td><span class="term">Technology</span></td><td>skill</td>'
           '<td>the everyday machine understood and repaired</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why do '
           'the kinds differ at the untrained hand? Come and hear: because the '
           'chart is a theory of how competence enters a person. The talent '
           'was always there, needing only occasion; the skill entered '
           'through hours, and its absence shows as a higher wall; the study '
           'entered through books, and its absence is a closed one. The commentaries hold the rows and the theory&rsquo;s edges. The kinds also stage the sheet&rsquo;s second priority &mdash; thirteen, nine, and five, ranked as the houses were &mdash; and the margin keeps the arithmetic where the seder exiled it.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'talents and the skills; the knowledges and the open categories '
             'wait overleaf.',
 'folio': '275A',
 'glossL': '<p><span class="mark">a</span> On the Abilities entire and their '
           'three kinds, see M20, the sixth chapter, folios 274&ndash;289, '
           'within whose span this page takes its number; the one-line '
           'provinces are this binding&rsquo;s own restatements per its '
           'standing law.</p>\n'
           '        <p><span class="mark">b</span> On the untrained laws by '
           'kind &mdash; the talent&rsquo;s free attempt, the skill&rsquo;s '
           'higher wall, the knowledge&rsquo;s closed door &mdash; see the '
           'chapter&rsquo;s own head-matter at folio 274.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'talents severally, folios 274&ndash;278; on the skills, folios '
           '279&ndash;282; the priorities of the making &mdash; thirteen, '
           'nine, five &mdash; are the seder&rsquo;s, folios '
           '250&ndash;266.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'faction-bound learnings the chart omits &mdash; the '
           'Akashayana&rsquo;s Do first among them &mdash; see folio 423 of '
           'this binding and the secondary lists glossed overleaf.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Every row is the second '
           'half of a pool: the measures of 273a join these learnings in '
           'the hands of 385a, and the specialty law of 273b runs here '
           'from the fourth dot as there.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> '
           'Awareness is the chart&rsquo;s one door into the hidden world '
           '&mdash; the half-roused census of 38a runs on it &mdash; and '
           'Meditation refreshes the well the blood folio of 78a '
           'meters; the mundane sheet touches the Awakened binding at '
           'exactly these two rows, which the Masoret finds tidy.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'fighting rows are chapter X&rsquo;s: Brawl and Martial Arts '
           'and Melee feed the ladders of 409a, and the schooled '
           'fight&rsquo;s deep form, Do, is tried at 423 and gated to '
           'one Tradition, as its folio explains at length.</p>',
 'h1': 'Abilities',
 'hagahah': 'The sheet&rsquo;s theology, verse two: what you know was '
            'learned somewhere, and the somewhere is on the sheet if '
            'anyone asks.',
 'inner': '<p><span class="lemma">Innate, trained, studied.</span> The '
          'three kinds&rsquo; plain sense: the chart sorts learnings by '
          'how they enter &mdash; the talent by temperament, the skill '
          'by repetition, the knowledge by instruction &mdash; and the '
          'sorting is enforced at exactly one point, the untrained '
          'attempt, where entry shows. Everywhere else the kinds are '
          'identical in law: one to five, one die per dot, specialty '
          'at four.</p>\n'
          '        <p><span class="lemma">The talent&rsquo;s free '
          'hand.</span> The first kind&rsquo;s plain sense: anyone may '
          'swing, notice, charm, or lie without a single dot, at no '
          'penalty but the missing dice &mdash; for the talents are '
          'refinements of equipment every person carries. The row to '
          'watch is Awareness: the one talent whose subject is the '
          'hidden world, carried untrained by every Sleeper, which '
          'is how the setting explains the prickle at the '
          'neck&rsquo;s back that the Masses never follow up.</p>\n'
          '        <p><span class="lemma">The skill&rsquo;s higher '
          'wall.</span> The second kind&rsquo;s plain sense: the '
          'untrained skill is attempted against a wall one step '
          'higher &mdash; the borrowed car drives, badly &mdash; and '
          'the step is the design&rsquo;s measure of what training '
          'buys: not permission but reliability. The band is the '
          'source&rsquo;s; the margin keeps the principle.</p>\n'
          '        <p><span class="lemma">The knowledge&rsquo;s closed '
          'door.</span> The third kind&rsquo;s plain sense: without a '
          'dot, the study is commonly not rolled at all &mdash; the '
          'law does not price the attempt; it denies the '
          'vocabulary &mdash; and the commonly is load-bearing: the '
          'Storyteller may allow the general-knowledge exception '
          'where the question is truly common. The door&rsquo;s '
          'hinge is overleaf with the knowledges themselves.</p>\n'
          '        <p><span class="lemma">Thirteen, nine, five.</span> '
          'The making&rsquo;s second priority, plainly: the kinds are '
          'ranked as the houses were, the dots spread within each '
          'kind, and the caps of the making &mdash; no learning past '
          'three before the finishing points &mdash; keep the '
          'starting sheet honest. The arithmetic is the '
          'seder&rsquo;s and exiled here per its law; the counsel '
          'keeps only the characterization: which kind got the '
          'thirteen is the character&rsquo;s education in one number.</p>\n        <p><span class="lemma">The fighting three.</span> Brawl, Martial Arts, and Melee sort violence by its tools &mdash; the born hands, the schooled form, the armed reach &mdash; and chapter X&rsquo;s ladders draw on all three. The sorting matters at the seam: anyone may swing, but the schooled form untrained is a higher wall, which is the chart pricing what a dojo sells, and the deep form past the wall is 423&rsquo;s gated art.</p>\n        <p><span class="lemma">The social quartet.</span> Empathy and Subterfuge are one perception aimed two ways &mdash; the heart read to help, the face read to beat &mdash; and the chart files both as talents: the setting holds that people-reading is temperament before it is training, which every con artist&rsquo;s biography confirms and every etiquette tutor resents. Expression and Leadership complete the quartet, the saying and the being-followed, and the four together are the company&rsquo;s house of 273a translated into verbs. The translation is the chart&rsquo;s habit throughout: the measures name what a person is, the learnings name what the person does about it, and the pools of 385a require one of each.</p>',
 'inner_head': 'On the Kinds<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the three entries of '
               'competence</span>',
 'name': 'Abilities',
 'outer': '<p><span class="lemma">The asymmetry, defended and '
          'doubted.</span> The untrained dispute, as the brief demands. '
          '<span class="voice">Some say</span> the three-tier law is the '
          'chart&rsquo;s finest teaching: it prices the difference '
          'between trying, training, and schooling in a single '
          'mechanic, and every table that has watched a brawler '
          'attempt surgery understands the closed door without a '
          'lecture. <span class="voice">Others say</span> the tiers '
          'crack at the seams the moment cases are pressed: why is '
          'the fistfight free to the librarian while the driven car '
          'climbs a wall &mdash; is fighting truly temperament and '
          'driving truly training, or did the chart sort by genre '
          'convenience and call it theory? The first school answers '
          'that the sorting follows harm and habit: the body '
          'improvises what bodies always did, and machines punish '
          'improvisation &mdash; the genre and the theory agree '
          'because the genre was drawn from life. The second '
          'answers with the borderline rows &mdash; the art that '
          'reads as talent but trains like a skill, the '
          'street-craft filed innate that every immigrant learned '
          'the hard way &mdash; and notes that the sibling '
          'recensions re-sort exactly these rows between kinds, '
          'edition by edition, which is what a convention looks '
          'like when it is not geometry. The folio files the '
          'girsa unharmonized per the binding&rsquo;s law: the kinds '
          'hold, the borderlines wander, and the untrained laws '
          'are the one place the sorting bites &mdash; so the table should rule its borderline rows once, aloud, and early. The rider the schools co-sign is pedagogical: whatever the sorting&rsquo;s truth, the untrained laws teach faster than any essay &mdash; one session of attempting the unlearned maps the three kinds onto the player&rsquo;s instincts, and the theory of entry becomes table knowledge without a lecture, which is the design earning its keep. <span class="kw">TEYKU</span> &mdash; the '
          'librarian, for the record, won the fistfight; the '
          'brawler is recovering.</p>\n'
          '        <p><span class="lemma">What the sheet cannot '
          'hold.</span> The completeness dispute, brief and '
          'structural. <span class="voice">Some say</span> '
          'twenty-two rows and eleven more overleaf cannot census '
          'human competence, and the proof is every campaign&rsquo;s '
          'first week: the player who cooks, sails, or midwifes '
          'finds no row and files under Crafts, which is a drawer '
          'named miscellaneous wearing a bow. <span '
          'class="voice">Others say</span> the chart never claimed '
          'census &mdash; it claims coverage of what the genre '
          'rolls, and the open categories the verso glosses are '
          'the honest overflow: name the learning, place its '
          'kind, play on. The schools converge, as this '
          'chapter&rsquo;s schools do, on the same practice and '
          'differ on its dignity; the folio notes only that a '
          'chart which ships its own escape hatch has conceded '
          'the point graciously, and that the concession is printed, which is more than most systems manage. And the escape hatch&rsquo;s discipline is the chart&rsquo;s real defense: what enters, enters by kind, with the kinds&rsquo; own walls &mdash; the census may grow, but the theory does not bend, and a theory that survives its own exceptions is the only kind worth printing. The kinds, in short, are a curriculum wearing a chart&rsquo;s clothes, and the sheet grades by entry.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the tiers, and the census</span>',
 'rubric': 'the learnings, two kinds of three',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the Abilities &middot; talents and '
             'skills as chart',
 'title': 'Tractate Aliyah · Folio 275a — Abilities: the talents and the skills',
 'type': 'luach'}
