# Folio 275b - The Knowledges (luach). The studied kind and the open
# categories, per the wod-llm-wiki abilities hub (M20 ch.6 pp.282-300).
FOLIO = {'bottom': '<p><span class="lemma">On the scholar&rsquo;s spotlight.</span> The '
           'knowledges reward staging as revelation: let the dots deliver '
           'briefings, translations, and diagnoses in the character&rsquo;s '
           'voice, not the Storyteller&rsquo;s summary. A player reading her '
           'own Occult 4 aloud to the table is the row doing its job; a '
           'handout does the same work with none of the pride.</p>\n'
           '        <p><span class="lemma">On the common-knowledge '
           'exception.</span> The closed door opens for the truly common '
           'question &mdash; what year the war ended, what a fever means '
           '&mdash; and the counsel is to use the exception generously at '
           'the shallow end and never at the deep: no dots, no diagnosis. '
           'The door&rsquo;s hinge is whether a Sleeper on the street '
           'could answer, which is a test any table can apply in a '
           'second.</p>\n'
           '        <p><span class="lemma">On gating the esoterica.</span> '
           'The practical-arcana row and the secondary lists behind it '
           'are where focus lives on the mundane sheet: gate the deep '
           'disciplines to teachers, scenes, and time, per the focus '
           'folios&rsquo; counsel, and a new column earned in play '
           'becomes an arc instead of a purchase.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on spotlights, hinges, '
                'and earned columns</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The third kind is studied,</span> and its '
           'law was given overleaf: without a dot the door is commonly '
           'closed, for the studies speak in vocabularies absence cannot '
           'improvise. The chart gives the eleven; below them, the open categories hold everything the eleven miss. Each study is a vocabulary, priced by the dot as depth of fluency, and the chart speaks its provinces in the binding&rsquo;s own words.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Study</th><th>Its province</th></tr>\n'
           '          <tr><td><span class="term">Academics</span></td>'
           '<td>the lettered humanities &mdash; history, letters, tongues, and the '
           'mathematics that binds them</td></tr>\n'
           '          <tr><td><span class="term">Computer</span></td>'
           '<td>the thinking machines and the cultures that tend them</td></tr>\n'
           '          <tr><td><span class="term">Cosmology</span></td>'
           '<td>the countries past the wall, mapped as chapter IV maps them; the '
           'Union files it as subdimensions</td></tr>\n'
           '          <tr><td><span class="term">Enigmas</span></td>'
           '<td>riddles, paradoxes, and the leap that lands where logic '
           'stops</td></tr>\n'
           '          <tr><td><span class="term">Esoterica</span></td>'
           '<td>the practical arcana &mdash; the disciplines a focus is built from, '
           'craft by craft</td></tr>\n'
           '          <tr><td><span class="term">Investigation</span></td>'
           '<td>evidence read backward to the deed</td></tr>\n'
           '          <tr><td><span class="term">Law</span></td>'
           '<td>the courts, codes, and constabularies of the street&rsquo;s own '
           'justice</td></tr>\n'
           '          <tr><td><span class="term">Medicine</span></td>'
           '<td>the body&rsquo;s failures and their mending</td></tr>\n'
           '          <tr><td><span class="term">Occult</span></td>'
           '<td>the hidden world as the street rumors it &mdash; part truth, part '
           'costume, sorted by the dots</td></tr>\n'
           '          <tr><td><span class="term">Politics</span></td>'
           '<td>power&rsquo;s official plumbing and where the valves are</td></tr>\n'
           '          <tr><td><span class="term">Science</span></td>'
           '<td>the hard disciplines; the soft ones board with '
           'Academics</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> And '
           'when the chart runs out? The books keep three open categories '
           '&mdash; hobby talents, professional skills, expert knowledges '
           '&mdash; and behind them a long shelf of secondary learnings, '
           'named, gated, and optional: the flying, the carousing, the '
           'high ritual, and the one the margin must flag &mdash; Do, the '
           'schooled fight&rsquo;s deep form, kept to one Tradition by law. '
           'The open categories are the chart&rsquo;s confession and its '
           'mercy: competence outruns any census, so the census ships '
           'with blank rows. The commentaries hold the eleven&rsquo;s edges and the shelf&rsquo;s sprawl. And the closed door&rsquo;s deepest reading is the chart&rsquo;s last teaching: the studies map what must be received &mdash; no talent improvises Law, no training alone yields Medicine &mdash; so the third kind is the social kind, every dot of it somebody&rsquo;s teaching received and kept, which the biographical counsel opposite has been assuming all along.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso '
             'of the learnings: the studies and the open shelf; the '
             'Backgrounds wait at folio 303.',
 'folio': '275B',
 'glossL': '<p><span class="mark">a</span> On the Knowledges severally, see '
           'M20, folios 282&ndash;289; the provinces are this '
           'binding&rsquo;s restatements per its standing law, and the '
           'Union&rsquo;s renamings ride in the rows where they '
           'differ.</p>\n'
           '        <p><span class="mark">b</span> On the closed door and '
           'its common-knowledge hinge, see the chapter&rsquo;s head-matter '
           'at folio 274, with the counsel opposite.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'secondary abilities and the three open categories, see folios '
           '289&ndash;300, kept by the book at its own grain; the chart '
           'holds only the confession.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'Esoterica as the focus&rsquo;s learned floor &mdash; the '
           'blend&rsquo;s gate at the fourth dot &mdash; see the Book of Secrets, folios 167&ndash;175 of that volume; the blend itself is 572b&rsquo;s subject in this binding.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Cosmology is chapter '
           'IV&rsquo;s atlas carried as a study &mdash; the maps of 91a '
           'sold in the gift shop, courtesies and all &mdash; and Occult '
           'is 62a&rsquo;s water read as a syllabus: what the street '
           'believes about the hidden, graded for accuracy by the '
           'dots.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> '
           'Esoterica is the one study the whole Book of Magick leans '
           'on: the practice folios of 572 price their blends against '
           'its fourth dot, and the margin has been routing readers '
           'there since chapter XI was bound.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'shelf&rsquo;s gated column, Do, is tried at 423 with its '
           'Tradition&rsquo;s whole folio for context; and the '
           'demolisher&rsquo;s craft the hazards chart of 435a flagged '
           'is the professional-skill category doing its quiet '
           'work.</p>',
 'h1': 'The Knowledges',
 'hagahah': 'The sheet&rsquo;s theology, verse three: some doors open only '
            'from the inside, and the inside is a library.',
 'inner': '<p><span class="lemma">Vocabularies, not permissions.</span> '
          'The closed door&rsquo;s plain sense, restated where it lives: '
          'the studies are not forbidden to the untrained &mdash; they '
          'are unavailable, as a language unspoken is unavailable, and '
          'the law&rsquo;s refusal to price the attempt is accuracy, not '
          'harshness. What the common-knowledge hinge admits is '
          'exactly the shared vocabulary: what any street could '
          'answer, any sheet may.</p>\n'
          '        <p><span class="lemma">The two atlases.</span> '
          'Cosmology and Occult, read together as the chart intends: '
          'one is the far country surveyed from inside the hidden '
          'world, the other is the hidden world rumored from the '
          'street &mdash; and a character may hold either without the '
          'other, which the binding finds true to life. The '
          'Union&rsquo;s renaming of the first is the chart&rsquo;s one '
          'political row: subdimensions is Cosmology wearing a '
          'badge, and both factions&rsquo; scholars pass the same '
          'exams.</p>\n'
          '        <p><span class="lemma">The focus&rsquo;s learned '
          'floor.</span> Esoterica&rsquo;s plain sense, and why the row '
          'matters past its wording: the practical arcana are where '
          'the mundane sheet touches the paradigm chapters &mdash; the '
          'yoga, the alchemy, the astrology that a focus is built '
          'from &mdash; and the blend law of 572 gates its widest '
          'doors on this row&rsquo;s fourth dot. A mage&rsquo;s Esoterica '
          'is her practice&rsquo;s scholarship, and the binding&rsquo;s '
          'whole focus doctrine stands partly on this unglamorous '
          'column.</p>\n'
          '        <p><span class="lemma">The graded rumor.</span> '
          'Occult&rsquo;s inner clause, worth its own lemma: the study '
          'is deliberately impure &mdash; part truth, part costume '
          '&mdash; and the dots grade the sorting, not the collecting: '
          'the one-dot dabbler owns the costume shop entire, the '
          'four-dot scholar knows which masks have faces behind '
          'them. The design keeps the Sleeper world&rsquo;s books '
          'wrong on purpose, per 62a&rsquo;s water, and this row is '
          'where the wrongness is bought and sold. The row&rsquo;s table use is triage: what the player knows and the character does not is the campaign&rsquo;s dramatic irony, metered in dots.</p>\n'
          '        <p><span class="lemma">The open shelf.</span> The '
          'secondary lists&rsquo; plain sense: behind the eleven stand '
          'dozens of named optional learnings and three open '
          'categories to hold the rest, gated by the '
          'Storyteller&rsquo;s leave &mdash; and the gate is the point: '
          'the shelf sprawls by design, and the leave is what keeps '
          'the sprawl from resorting the chart. The one column with '
          'a law of its own is Do, gated to the Akashayana entire, whose folio, 423, will argue the gate at length.</p>\n        <p><span class="lemma">The pairings of habit.</span> Each study keeps a customary partner: Intelligence carries the recall of Academics and Science, Perception the reading of Investigation, Wits the diagnosis improvised under fire &mdash; and the customs are defaults, not law, for the pools of 385a pair freely by the task. The table that varies the pairings has learned the system&rsquo;s real grammar: the measure is how the character works, and the learning is what she works with.</p>',
 'inner_head': 'On the Studies<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the eleven, and the shelf '
               'behind</span>',
 'name': 'The Knowledges',
 'outer': '<p><span class="lemma">Why the door locks.</span> The '
          'asymmetry&rsquo;s deep half, held from the recto. <span '
          'class="voice">Some say</span> the closed door is the '
          'chart&rsquo;s realism at its best: nobody improvises '
          'jurisprudence or organic chemistry, and a system that let '
          'raw Intelligence roll surgery would price study at nothing '
          'and insult every character who paid for it &mdash; the lock '
          'is what the dots are worth. <span class="voice">Others '
          'say</span> the lock proves too much in a binding where '
          'chapter XI stands: the mind-arts of 519a pour whole '
          'vocabularies into a skull by the scene, the '
          'pattern-clerks copy learnings as the workshop of 517b '
          'copies anything, and a door the arts can carry through '
          'wholesale is a door in name &mdash; the mundane lock '
          'survives only because most of the street cannot afford '
          'the locksmith. The first school answers as 273b&rsquo;s '
          'summit school answered: the carried vocabulary is '
          'priced, temporary, and billed by the court, while the '
          'studied one is owned &mdash; the lock holds because the '
          'shortcuts rent and never sell. The second answers that '
          'a rented degree passes the exam all the same, and asks '
          'what the closed door means to the fellowship that '
          'keeps the key-cutting machine. The folio files the '
          'dispute beside its twin on the ladder&rsquo;s summit and '
          'notes the pattern the chapter is assembling: every '
          'mundane wall in the Order of Making has an Awakened '
          'staff door, and the binding&rsquo;s honest answer &mdash; '
          'per the whole of chapter XI &mdash; is that the doors '
          'are real, taxed, and watched, which is the setting&rsquo;s '
          'entire economy in one sentence. <span '
          'class="kw">TEYKU</span> &mdash; the library&rsquo;s inside '
          'remains the cheap way in, for now, at most '
          'counters.</p>\n'
          '        <p><span class="lemma">The sprawl, licensed.</span> '
          'The shelf dispute. <span class="voice">Some say</span> the '
          'secondary lists are the chart&rsquo;s slow death: every '
          'optional column is a bespoke subsystem, every campaign '
          'accretes its own dialect, and the shared language the '
          'luachs keep &mdash; a three is a three at every table '
          '&mdash; erodes one hobby at a time; the open categories '
          'should have stayed shut. <span class="voice">Others '
          'say</span> the sprawl is the census breathing: '
          'competence genuinely outruns any list, the gate of the '
          'Storyteller&rsquo;s leave is the licensing the first '
          'school wants, and a chart that refused new columns '
          'would not stop the dialects &mdash; it would only stop '
          'recording them. The schools split exactly as the '
          'recto&rsquo;s census schools split, and the folio, '
          'having filed that agreement once, files this one by '
          'reference and adds the practical rider both sides '
          'sign: whatever enters by the open categories enters '
          'at the kinds&rsquo; own laws &mdash; innate, trained, or '
          'studied, with the untrained walls to match &mdash; for '
          'the shelf may sprawl, but the theory of entry does not &mdash; and the chapter&rsquo;s charts run on that constancy &mdash; six pages of rows governed by one small theory, the assets of 303 still to post &mdash; which is as near to elegance as bookkeeping comes.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the lock, and the shelf</span>',
 'rubric': 'the studies, and the shelf behind',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the Knowledges &middot; the studied '
             'kind as chart',
 'title': 'Tractate Aliyah · Folio 275b — The Knowledges: the studied kind',
 'type': 'luach'}
