# Folio 303b - The Awakened Assets (luach). The mystic and Technocratic
# backgrounds, per the wod-llm-wiki backgrounds hub (M20 pp.303-327).
FOLIO = {'bottom': '<p><span class="lemma">On the load-bearing three.</span> Avatar, '
           'Node, and Sanctum are the sheet&rsquo;s deep infrastructure: the '
           'first meters the soul&rsquo;s economy, the second feeds it, the '
           'third shelters the work. A starting cabal that pools toward one '
           'well and one workshop has bought the campaign&rsquo;s home base '
           'with its background dots, and the chronicle should honor the '
           'purchase by threatening it regularly and losing it never '
           'without a war.</p>\n'
           '        <p><span class="lemma">On wonders at chargen.</span> The '
           'wonder row puts an artifact in a starting hand, and the counsel '
           'is the workshop&rsquo;s: give the item a maker, a history, and '
           'one inconvenient opinion. A wonder that arrived from a row '
           'behaves like equipment; one that arrived from a story behaves '
           'like the chapter it came from, and the difference costs the '
           'Storyteller a paragraph.</p>\n'
           '        <p><span class="lemma">On the leash rows.</span> Play the '
           'Technocratic variants exactly as issued: the requisitioned gear '
           'arrives with paperwork, the enhancement with maintenance '
           'schedules, and the return policy is real. An operative&rsquo;s '
           'sheet is partly the Union&rsquo;s property, and the best '
           'Technocracy chronicles are about which parts.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on infrastructure, '
                'provenance, and return policies</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The Awakened keep assets the street has no '
           'ledger for,</span> and the chart prices them beside the worldly '
           'rows: the spark&rsquo;s measure, the wells and workshops, the '
           'made things and the fates &mdash; with the Union&rsquo;s issued '
           'variants riding the same rows under their own names, per the '
           'register this binding keeps.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Asset</th><th>Its province</th></tr>\n'
           '          <tr><td><span class="term">Arcane</span></td>'
           '<td>the art of being forgotten; the Union issues it as cloaking</td></tr>\n'
           '          <tr><td><span class="term">Avatar</span></td>'
           '<td>the spark&rsquo;s rating &mdash; essence held and drawn by the turn; '
           'the Union files it as Genius</td></tr>\n'
           '          <tr><td><span class="term">Blessing</span></td>'
           '<td>a mythic patron&rsquo;s standing favor, never martial</td></tr>\n'
           '          <tr><td><span class="term">Chantry</span></td>'
           '<td>the shared house of 2a&rsquo;s law, bought in common</td></tr>\n'
           '          <tr><td><span class="term">Demesne</span></td>'
           '<td>a dream-country of one&rsquo;s own, held while sleeping</td></tr>\n'
           '          <tr><td><span class="term">Destiny</span></td>'
           '<td>a fate on file; the will refreshed by knowing it</td></tr>\n'
           '          <tr><td><span class="term">Dream</span></td>'
           '<td>the collective memory dipped for answers not studied</td></tr>\n'
           '          <tr><td><span class="term">Enhancement</span></td>'
           '<td>the body improved by the vats and the shop; dearly priced</td></tr>\n'
           '          <tr><td><span class="term">Familiar</span></td>'
           '<td>a companion spirit that eats what the court bills</td></tr>\n'
           '          <tr><td><span class="term">Legend</span></td>'
           '<td>an archetype worn until the world feeds it</td></tr>\n'
           '          <tr><td><span class="term">Node</span></td>'
           '<td>a well of 78b&rsquo;s law, held and defended</td></tr>\n'
           '          <tr><td><span class="term">Past Lives</span></td>'
           '<td>the spark&rsquo;s prior tenants, consulted across deaths</td></tr>\n'
           '          <tr><td><span class="term">Sanctum</span></td>'
           '<td>the room where the paradigm is house rules; dearly priced</td></tr>\n'
           '          <tr><td><span class="term">Secret Weapons</span></td>'
           '<td>the Union&rsquo;s prototype shelf, signed for</td></tr>\n'
           '          <tr><td><span class="term">Requisitions</span></td>'
           '<td>the Union&rsquo;s stores, drawn by rank and returned</td></tr>\n'
           '          <tr><td><span class="term">Totem</span></td>'
           '<td>a spirit-patron bonded to the circle; dearly priced</td></tr>\n'
           '          <tr><td><span class="term">Wonder</span></td>'
           '<td>a made thing of the workshop&rsquo;s law, owned outright</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear the chart&rsquo;s quiet argument. The worldly rows '
           'overleaf price what anyone might have; these rows price what '
           'only the hidden world grants &mdash; and the two lists share one '
           'pool, one allowance, one arithmetic. A starting mage chooses '
           'between the ally and the well, the fortune and the fate, at par. '
           'The commentaries hold what that par implies, and the margin holds the pooling and the leashes. The chart also closes the making&rsquo;s arithmetic: after this page the seven dots are spent, the freebies wait, and the sheet turns from what the character has to what the character is worth &mdash; the deep measures of 328, where the chapter ends. One page remains, then, between the making and the meaning, and the chart commends the reader to it without detour.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso '
             'of the assets: the Awakened side; the will&rsquo;s own measures '
             'wait at folio 328, and the chapter closes there.',
 'folio': '303B',
 'glossL': '<p><span class="mark">a</span> On the Awakened Backgrounds '
           'severally, see M20, folios 303&ndash;327, at each row&rsquo;s '
           'own entry; the chart ends where the book&rsquo;s does, at the '
           'wonder of folio 327.</p>\n'
           '        <p><span class="mark">b</span> On the dearly priced '
           'rows &mdash; enhancement, sanctum, totem at two points the dot '
           '&mdash; see folios 313, 323, and 325&ndash;327 in turn; the Technocrat-only rows, the requisitions and the prototype shelf, at 321 and 324.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'Avatar row&rsquo;s three jurisdictions &mdash; essence held, '
           'essence by the turn, the Seekings&rsquo; depth &mdash; see '
           'folios 305 and 330&ndash;331, with the folio bound at 43a.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'node&rsquo;s ratings and the sanctum&rsquo;s coincidental '
           'interior, see the entries and the folios bound at 78b and '
           '567a; the wonder&rsquo;s kinds are 517b&rsquo;s subject and '
           'the Kelim tractate&rsquo;s, wanting.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Five rows of this chart '
           'are bound folios wearing point costs: the Avatar at 43a, the '
           'node at 78b, the chantry at 2a&rsquo;s law and 109b&rsquo;s '
           'anchors, the wonder at 517b, the familiar at 521a&rsquo;s '
           'bargains &mdash; and the Masoret reads the chart as the '
           'binding&rsquo;s index sold by the dot.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'sanctum row is 567a&rsquo;s paradigm given a room of its own '
           '&mdash; the one address where the lens is landlord &mdash; and '
           'the demesne is 91a&rsquo;s dream-roads held privately; the '
           'chart&rsquo;s geography is chapter IV&rsquo;s, subdivided and '
           'sold.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'Genius filing of the Avatar row is 43a&rsquo;s laundered name '
           'with a price tag, and the requisition rows are chapter '
           'VI&rsquo;s quartermasters at the counter; the leash the '
           'counsel below prices is that chapter&rsquo;s whole '
           'argument, itemized.</p>',
 'h1': 'The Awakened Assets',
 'hagahah': 'The street&rsquo;s ledgers stop at the fence line. The '
            'fence line, per this chart, is negotiable at one point '
            'the dot.',
 'inner': '<p><span class="lemma">One pool, two worlds.</span> The '
          'chart&rsquo;s plain sense, and its deepest clause: the '
          'worldly and the Awakened assets are priced at par from one '
          'allowance, so every starting sheet states an exchange rate '
          'between the street and the hidden world &mdash; the ally '
          'against the well, the fortune against the fate. The par '
          'is the design&rsquo;s philosophy of grounding: a mage is a '
          'person with assets on both sides of the fence, and the '
          'sheet refuses to let the fence cut the ledger.</p>\n'
          '        <p><span class="lemma">The spark&rsquo;s row.</span> '
          'The Avatar entry&rsquo;s plain sense: the rating meters the '
          'essence economy &mdash; held to the rating, drawn by the '
          'turn to the rating &mdash; and deepens the Seekings, per '
          'the folio the margin cites; it is the one row every mage '
          'holds whether or not a dot was bought, for the spark '
          'arrives with the waking. The bought dots deepen what '
          'the waking granted, which makes this the chart&rsquo;s '
          'only row that prices more of oneself.</p>\n'
          '        <p><span class="lemma">The infrastructure '
          'rows.</span> Node, sanctum, chantry, and demesne, read '
          'together as the counsel reads them: the chart sells the '
          'made-country law of 109b in residential sizes &mdash; the '
          'well that feeds, the room where the lens is landlord, '
          'the shared house, the dream held privately &mdash; and '
          'the anchors&rsquo; warning scales down intact: what is '
          'bought must be fed, defended, and connected, or it '
          'drifts. The dear pricing of the sanctum is the '
          'design&rsquo;s honesty about what a private reality '
          'costs.</p>\n'
          '        <p><span class="lemma">The made and the '
          'fated.</span> Wonder, familiar, blessing, destiny, '
          'legend, dream, and past lives, read together: the chart '
          'prices provenance &mdash; things with makers, companions '
          'with appetites, favors with patrons, fates with files '
          '&mdash; and every row trails a story obligation the '
          'worldly side does not: the wonder has a history, the '
          'familiar has a diet, the destiny has an author. The '
          'counsel opposite spends the obligations; the chart '
          'notes only that nothing on this side of the fence is merely money. The two fate rows are the strangest purchases in the game: destiny and past lives buy narrative authority &mdash; a claim on the story&rsquo;s shape &mdash; and the counsel prices them as shared authorship rather than prophecy, which keeps the rows playable and their authors humble.</p>\n'
          '        <p><span class="lemma">The issued column.</span> '
          'The Union&rsquo;s variants, read as one clause: arcane '
          'cloaked, Avatar filed as Genius, gear requisitioned and '
          'signed for, prototypes shelved by clearance &mdash; the '
          'same machinery in the Union&rsquo;s livery, with one '
          'structural difference the chart marks plainly: the '
          'mystic&rsquo;s rows are owned and the operative&rsquo;s are '
          'issued, and issue implies return. The leash is priced '
          'as a discount and collected as obedience, which is chapter VI&rsquo;s economy in a single column of rows. The one issued row with no mystic twin is enhancement, and the asymmetry is deliberate: the vats improve what they then hold a lien on, per the manifest of 190b, and the margin files the lien beside the leash.</p>',
 'inner_head': 'On the Hidden Ledger<span class="comm-sub">the inner commentary '
               '&middot; the plain sense &middot; the spark, the '
               'infrastructure, and the issue</span>',
 'name': 'The Awakened Assets',
 'outer': '<p><span class="lemma">The par, disputed.</span> The exchange '
          'dispute. <span class="voice">Some say</span> the single pool '
          'is the chart&rsquo;s wisdom: pricing the well against the '
          'ally forces every starting mage to decide how deep in the '
          'hidden world she lives, and the sheet&rsquo;s first economy '
          'teaches the setting&rsquo;s first lesson &mdash; the Awakened '
          'remain people, and people have rent, friends, and '
          'paperwork. <span class="voice">Others say</span> the par is '
          'a fiction the campaign falsifies by the third session: the '
          'well appreciates and the ally does not &mdash; the node '
          'feeds every casting forever while the fortune buys '
          'dinners &mdash; and a par that survives only at chargen is '
          'a pricing error the experienced exploit, which is why '
          'every veteran sheet in the setting is heavy on the '
          'Awakened side. The first school answers that the ally '
          'appreciates in the only currency that cannot be minted '
          '&mdash; loyalty &mdash; and that the veteran sheets heavy on '
          'wells and light on friends describe half the '
          'binding&rsquo;s tragedies by inventory alone. The second '
          'answers that tragedy is not a rebate. The folio files '
          'the dispute as the chapter&rsquo;s economics in miniature '
          'and notes what both schools concede: the chart&rsquo;s par '
          'is normative, not descriptive &mdash; a statement about '
          'what a person should weigh, printed in a book about people who weigh wrongly for a living. Both schools also grant the table&rsquo;s correction: a Storyteller who lets the worldly rows act with the initiative of persons has repriced the par midgame, in the ally&rsquo;s favor, at no cost but attention. <span '
          'class="kw">TEYKU</span> &mdash; the exchange rate floats; '
          'the fence line holds; the ledger, as always, is kept '
          'by the survivors.</p>\n'
          '        <p><span class="lemma">Owned, issued, or '
          'grown.</span> The tenure dispute, closing the chart. <span '
          'class="voice">Some say</span> the chart&rsquo;s three tenures '
          '&mdash; the mystic&rsquo;s owned, the operative&rsquo;s issued, '
          'and the third the rows only imply: the grown, the cult '
          'and legend and destiny that accrete rather than '
          'purchase &mdash; are the setting&rsquo;s property law entire, '
          'and the background chapter is secretly its '
          'constitutional one. <span class="voice">Others say</span> '
          'the tenures blur on inspection: the owned node can be '
          'taken by the arithmetic of allies, as 78b&rsquo;s Gemara '
          'took it; the issued enhancement outlasts many a '
          'defection, as chapter VI&rsquo;s deserters attest; and the '
          'grown legend can be worn by an impostor until the '
          'world forgets the difference. Property here is as '
          'contested as everywhere else in the binding, which is '
          'to say: the chart prices possession, and possession '
          'is a story&rsquo;s opening claim, never its verdict. The '
          'schools converge on the practice the hagahah already '
          'posted &mdash; both signatures, every use &mdash; and the '
          'chapter&rsquo;s luachs close on that convergence: four '
          'charts, one allowance, and every row of all of them '
          'co-owned with the world it is bought from. The '
          'will&rsquo;s own measures wait at 328, where the chapter ends with the one asset nobody issues &mdash; and which, the last margin will argue, nobody entirely owns either.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the par, and the tenure</span>',
 'rubric': 'the hidden ledger',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the Awakened assets &middot; the hidden '
             'side as chart',
 'title': 'Tractate Aliyah · Folio 303b — The Awakened Assets: the hidden ledger',
 'type': 'luach'}
