# Folio 303a - Backgrounds (luach). The worldly assets, per the
# wod-llm-wiki backgrounds hub (M20 pp.301, 303-327).
FOLIO = {'bottom': '<p><span class="lemma">On the rows as cast list.</span> Every '
           'worldly row is an NPC the player commissioned: the ally has a '
           'name, the mentor has an agenda, the contacts have day jobs. '
           'Write them down at character creation &mdash; a sentence each '
           '&mdash; and the chronicle opens with a supporting cast the '
           'players already care about, purchased at chargen prices.</p>\n'
           '        <p><span class="lemma">On spending the network.</span> '
           'Backgrounds are scene generators, not vending machines: the '
           'resources arrive as errands, the influence as favors called in, '
           'the spies as meetings in bad coffee shops. A background '
           'consulted offscreen is arithmetic; consulted onscreen it is '
           'the campaign.</p>\n'
           '        <p><span class="lemma">On the co-owned stats.</span> '
           'The hagahah&rsquo;s claim is table law: these rows live half on '
           'the player&rsquo;s sheet and half in the Storyteller&rsquo;s world, '
           'and both signatures are on every use. Agree early what a '
           'background can and cannot be asked to do, and revisit the '
           'agreement when the chronicle&rsquo;s stakes climb &mdash; the '
           'rows grow with the game, or they calcify.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on cast lists, errands, '
                'and double signatures</span>',
 'center': '<p class="noindent"><span class="dropcap">A</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">What a character has is also a trait.</span> '
           'The <span class="term">Backgrounds</span> chart the assets: '
           'people, standing, goods, and access, rated one to five as the '
           'measures are &mdash; though some rows climb higher by the '
           'standing rule &mdash; and priced at the making from their own '
           'pool. The worldly rows the chart gives here; the Awakened '
           'assets wait overleaf.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Asset</th><th>Its province</th></tr>\n'
           '          <tr><td><span class="term">Allies</span></td>'
           '<td>friends who help because they are friends; the chart&rsquo;s first '
           'row and its warmest</td></tr>\n'
           '          <tr><td><span class="term">Alternate Identity</span></td>'
           '<td>a second self with papers that hold</td></tr>\n'
           '          <tr><td><span class="term">Backup</span></td>'
           '<td>organizational muscle on call, faceless and punctual</td></tr>\n'
           '          <tr><td><span class="term">Certification</span></td>'
           '<td>the license, the badge, the letters after the name</td></tr>\n'
           '          <tr><td><span class="term">Contacts</span></td>'
           '<td>people who know things and owe you a phone call</td></tr>\n'
           '          <tr><td><span class="term">Cult</span></td>'
           '<td>devotees whose belief is a resource, lent to the work</td></tr>\n'
           '          <tr><td><span class="term">Fame</span></td>'
           '<td>being recognized, with everything that opens and closes</td></tr>\n'
           '          <tr><td><span class="term">Influence</span></td>'
           '<td>the quiet hand on the street&rsquo;s official levers</td></tr>\n'
           '          <tr><td><span class="term">Library</span></td>'
           '<td>an archive that answers questions, at its size&rsquo;s speed</td></tr>\n'
           '          <tr><td><span class="term">Mentor</span></td>'
           '<td>an elder invested in your becoming; agenda included</td></tr>\n'
           '          <tr><td><span class="term">Patron</span></td>'
           '<td>a benefactor whose face you may never see</td></tr>\n'
           '          <tr><td><span class="term">Rank</span></td>'
           '<td>title in a Sleeper institution, with its keys</td></tr>\n'
           '          <tr><td><span class="term">Resources</span></td>'
           '<td>money and what money buys, allowance by allowance</td></tr>\n'
           '          <tr><td><span class="term">Retainers</span></td>'
           '<td>loyal hands in your service, mundane and steady</td></tr>\n'
           '          <tr><td><span class="term">Spies</span></td>'
           '<td>a network that watches where you cannot</td></tr>\n'
           '          <tr><td><span class="term">Status</span></td>'
           '<td>standing among your own kind, spendable as respect</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why '
           'does the sheet chart what a character has, when the world already '
           'keeps such ledgers? Come and hear: because the chronicle is a '
           'contract, and these rows are its co-signed clauses &mdash; the '
           'player buys the ally, the Storyteller plays her, and neither '
           'owns her outright. The measures and learnings answer to dice; '
           'the assets answer to story, which is why their folio arrives '
           'last in the making and first in the campaign. The commentaries hold the rows&rsquo; edges and the pooling of shared purchases. One more law the chart keeps quietly: the assets are the sheet&rsquo;s only rows that act offscreen &mdash; the spies watch while the cabal sleeps, the influence files papers between sessions &mdash; so the seven dots of step four are also the player&rsquo;s delegation budget, spent on what the character need not personally do.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'worldly assets; the Awakened ones wait overleaf.',
 'folio': '303A',
 'glossL': '<p><span class="mark">a</span> On the Backgrounds entire, see '
           'M20, folios 303&ndash;327, whence this page takes its number '
           'from their first leaf; the provinces are this binding&rsquo;s '
           'restatements per its standing law.</p>\n'
           '        <p><span class="mark">b</span> On the rows that climb '
           'past five &mdash; allies, contacts, influence, resources, and '
           'their peers &mdash; see the standing rule at folio 301.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'pooling of purchases &mdash; a cabal&rsquo;s shared chantry, '
           'library, or backup, bought in common &mdash; see the chantry&rsquo;s entry at folio 307, whose dots are pooled construction points; the anchor-pooling custom entire is the dreaming cousins&rsquo; law, folios 171&ndash;172 of their binding.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'making&rsquo;s allowance &mdash; seven dots of Backgrounds, '
           'spent from their own pool &mdash; see the seder&rsquo;s '
           'folios, 250&ndash;266.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seder of 250a deals '
           'these rows at step four, and its Masoret promised this chart; '
           'the shopping list is now posted, worldly side first, as the '
           'chart-mold of 435 proved it could be.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'cult&rsquo;s lent belief is 62a&rsquo;s water bottled for '
           'private use, and the influence row is the whisper war of '
           '197a fought at retail; the worldly chart touches every '
           'faction folio somewhere, which is what assets are for.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'mentor&rsquo;s agenda is chapter II&rsquo;s retrieval race '
           'wearing a kind face &mdash; 38a&rsquo;s margin already priced '
           'the kindness &mdash; and the patron unseen has a folio of '
           'candidates in every chapter from V through VII, which the '
           'counsel below declines to find comforting.</p>',
 'h1': 'Backgrounds',
 'hagahah': 'The only stats the Storyteller co-owns. Both signatures, every '
            'use, no exceptions worth keeping.',
 'inner': '<p><span class="lemma">Assets, rated like measures.</span> The '
          'chart&rsquo;s plain sense: the rows run one to five as '
          'everything runs, but the rungs price scope, not skill &mdash; '
          'the one-dot ally is a person, the five-dot allies are a '
          'faction&rsquo;s worth of persons &mdash; and the rows that '
          'climb past five do so under the standing rule, for wealth '
          'and networks scale as flesh does not. The pool is the '
          'making&rsquo;s own: seven dots, spent here and nowhere '
          'else.</p>\n'
          '        <p><span class="lemma">People are not '
          'equipment.</span> The first six rows&rsquo; plain sense, '
          'stated as the chart means it: allies, contacts, cult, '
          'mentor, patron, and retainers are persons with the '
          'dots&rsquo; worth of loyalty, not the dots&rsquo; worth of '
          'obedience &mdash; they have days off, opinions, and '
          'breaking points, and the Storyteller holds their half of '
          'the signature. The design is deliberate: bought people '
          'who behaved like tools would teach the table that '
          'people are tools, and the setting has a faction for that lesson already. The dots&rsquo; loyalty is also bounded: the ally helps as friends help, at friendship&rsquo;s prices &mdash; she will hide you, lie a little, and drive all night; she will not die on schedule, and the sheet that expects it has misread the row and deserves the scene that follows.</p>\n'
          '        <p><span class="lemma">The paper rows.</span> '
          'Alternate identity, certification, and rank, read '
          'together: the chart prices the street&rsquo;s paperwork as '
          'an asset class of its own &mdash; the self that '
          'withstands scrutiny, the license that opens the '
          'regulated door, the title that comes with keys &mdash; '
          'and the pricing is the setting&rsquo;s realism about '
          'institutions: in a managed world, papers are armor, '
          'and the Union&rsquo;s own folios say so from the other '
          'side of the desk.</p>\n'
          '        <p><span class="lemma">The reach rows.</span> '
          'Influence, spies, backup, and status, read together: '
          'these are the faction folios&rsquo; machinery sold '
          'retail &mdash; the quiet hand, the watching network, the '
          'muscle on call, the respect that spends &mdash; and '
          'their ceilings past five are where player characters '
          'begin to resemble the institutions the binding '
          'audits. The counsel opposite prices the resemblance; '
          'the chart only notes that the rows exist, and that '
          'every great house in this binding started as somebody&rsquo;s background dots. The ceilings past five change the rows&rsquo; genre: at six and beyond the asset stops being personal and becomes institutional &mdash; held by charters and lieutenants, attackable through both &mdash; and the standing rule prices the transition honestly: past five, you no longer have a network; you administer one.</p>\n'
          '        <p><span class="lemma">Bought once, played '
          'forever.</span> The pooling clause&rsquo;s plain sense: a '
          'cabal may buy in common what it will hold in common '
          '&mdash; the shared library, the shared backup &mdash; and '
          'the pooled purchase binds the buyers as the '
          'chantry&rsquo;s four anchors bind a realm: jointly, and '
          'at everyone&rsquo;s risk. The arithmetic is the '
          'source&rsquo;s; the margin keeps the warning, which is '
          'the same warning 109b carved over the made '
          'countries.</p>',
 'inner_head': 'On the Assets<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; persons, papers, and reach</span>',
 'name': 'Backgrounds',
 'outer': '<p><span class="lemma">Story-currency, or points.</span> The '
          'refund dispute, as the brief demands. <span '
          'class="voice">Some say</span> the rows are points and points '
          'are property: the player paid the making&rsquo;s scarce '
          'allowance for the ally, and a Storyteller who kills, turns, '
          'or bankrupts the purchase without refund has taxed the '
          'sheet for playing the game &mdash; assets lost to story '
          'should return as points, or the prudent player buys dice '
          'instead of people, and the chronicle starves. <span '
          'class="voice">Others say</span> the rows are story-currency '
          'and the purchase is a stake, not a safe: the ally can die '
          'because the ally is a person, and her death is the '
          'campaign paying out, not confiscating &mdash; a background '
          'that cannot be lost cannot be threatened, and a stake '
          'nobody can lose is scenery. The first school answers '
          'that stakes are chosen at the table, not at the point of '
          'purchase, and that surprise confiscation teaches players '
          'to stop investing in the world. The second answers that '
          'refund-on-loss teaches them to invest like accountants, '
          'and that the sheet&rsquo;s warmest rows deserve better '
          'than actuarial love. The folio files the practice both '
          'schools converge on, as this chapter&rsquo;s schools do: '
          'losses wired to story pay out in story &mdash; the dead '
          'ally&rsquo;s successor, the burned network&rsquo;s survivor '
          'with a grudge and a debt &mdash; and losses that were '
          'merely bookkeeping errors give the points back. The '
          'double signature cuts both ways, which is what the '
          'hagahah has been saying all along. <span '
          'class="kw">TEYKU</span> &mdash; the ally, consulted, '
          'declined to be either currency; she wants to know why '
          'she is always the one who gets kidnapped.</p>\n'
          '        <p><span class="lemma">The Union&rsquo;s '
          'variants.</span> The register dispute, brief and '
          'necessary. <span class="voice">Some say</span> the '
          'Technocratic rows overleaf &mdash; the requisitions, the '
          'issued weapons, the cloaking filed where the mystics '
          'file the arcane &mdash; prove the chart is faction-neutral '
          'infrastructure: same machinery, different livery, and '
          'the binding&rsquo;s register swap of chapter VI was '
          'already implicit in the background chapter&rsquo;s '
          'parallel columns. <span class="voice">Others say</span> '
          'the parallel hides an asymmetry worth naming: the '
          'mystic&rsquo;s rows are owned and the operative&rsquo;s are '
          'issued &mdash; the Union&rsquo;s assets come with a return '
          'policy written by the quartermaster &mdash; and an asset '
          'that can be recalled is a leash charted as a perk. '
          'The folio lets chapter VI&rsquo;s own folios argue the '
          'leash and keeps the chart&rsquo;s finding: both '
          'liveries are printed, both are played, and the rows '
          'read differently depending on which side of the desk '
          'holds the pen &mdash; which is this binding&rsquo;s whole method applied to property. The rider for crossover tables is practical: when liveries meet &mdash; the operative&rsquo;s requisitions against the mystic&rsquo;s retainers &mdash; price the difference in failure modes, for the issued fails by recall and the owned by grief, and a chronicle that stages both has taught the two economies in one scene. The scene, the surveyors add, is worth staging early, before either economy has hardened into habit.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the refund, and the livery</span>',
 'rubric': 'the worldly assets',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of the Backgrounds &middot; the worldly '
             'side as chart',
 'title': 'Tractate Aliyah · Folio 303a — Backgrounds: the worldly assets',
 'type': 'luach'}
