# Folio 328a - Arete and Will. The chapter's deep measures, per the
# wod-llm-wiki arete, willpower, and quintessence pages (M20 pp.328-331,
# 394; the worked example at pp.250-266).
FOLIO = {'bottom': '<p><span class="lemma">On the will at the table.</span> The '
           'spent point is the player&rsquo;s one guaranteed sentence: honor it '
           'loudly. When Willpower buys the success, narrate the gritted '
           'teeth, the held breath, the refusal &mdash; the trait is the '
           'character&rsquo;s authorship made mechanical, and a table that '
           'sees the authorship spends the pool on what matters instead '
           'of hoarding it like ammunition.</p>\n'
           '        <p><span class="lemma">On refreshing by nature.</span> '
           'The refresh rules reward the Storyteller who knows each '
           'character&rsquo;s springs: the rest that restores, the ideal '
           'served, the scene that fed the soul. Post each '
           'character&rsquo;s refresh conditions beside the table&rsquo;s '
           'constitution and pay them visibly &mdash; a will economy the '
           'players can see is a motivation engine at no design '
           'cost.</p>\n'
           '        <p><span class="lemma">On the four pools as '
           'dashboard.</span> Arete fixed, Willpower spent, Quintessence '
           'cycled, Paradox accrued: the four numbers are the '
           'mage&rsquo;s whole state at a glance, and the counsel is to '
           'read them aloud at session start like weather. The dashboard '
           'tells the Storyteller what tonight&rsquo;s temptations are '
           'worth, which is more than most prep buys.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on authorship, springs, '
                'and the dashboard</span>',
 'center': '<p class="noindent"><span class="dropcap">F</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Four numbers govern the Awakened '
           'sheet,</span> and the chapter closes on their law. <span '
           'class="term">Arete</span>, the enlightenment&rsquo;s measure: it '
           'is the casting hand entire, no art may be held above it, and '
           'a permanent will lower than it caps both hand and arts at '
           'the will&rsquo;s own height; it begins at one, granted with '
           'the waking, and climbs only through the trials of '
           '43b.<sup>a</sup> <span class="term">Willpower</span>, the '
           'self&rsquo;s treasury: a point spent buys one certain success '
           'or holds the self against override, one such purchase a '
           'turn; the permanent rating resists what would move the '
           'soul; and the pool refills from rest, from nature served, '
           'from scenes that feed.<sup>b</sup> <span '
           'class="term">Quintessence</span>, the blood of 78a pooled '
           'against the Avatar&rsquo;s rating: held to it, drawn by the '
           'turn to it, and spent to lower a working&rsquo;s wall by one '
           'per point, three at the most.<sup>c</sup> And <span '
           'class="term">Paradox</span>, pooled against nothing: it has '
           'no rating to buy and no ceiling to raise, for it is not an '
           'asset but an account, billed by the court of 533a and '
           'discharged on the court&rsquo;s schedule, not the sheet&rsquo;s.<sup>d</sup> So the chapter&rsquo;s last law runs: three pools and an account, and the person is the ledger they share.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and walk the numbers once. A newly woken mage stands at '
           'the making&rsquo;s end: her Arete two &mdash; one granted, one '
           'bought dear &mdash; her Willpower five, her Quintessence '
           'filled to her Avatar&rsquo;s two, her Paradox at zero and '
           'staying there exactly as long as her discretion holds. She '
           'casts within her arts, spends a point of the blood to '
           'lower the wall, spends a point of will when the roll must '
           'not fail, and ends the night poorer in pools and richer in the one number no pool tracks. Run the walk again a season later and the numbers tell the campaign&rsquo;s story unaided: the Arete climbed once, dearly; the will deeper; the blood pooled against a grown Avatar; the account at the court standing wherever her discretion left it. Four numbers, read twice, are a biography. The disputants around this '
           'text hold what the will is, and how the summit is '
           'climbed.</p>',
 'chapter': 'Chapter the Eighth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'the chapter&rsquo;s deep measures: the law here, the prices '
             'overleaf, and the chapter closes there.',
 'folio': '328A',
 'glossL': '<p><span class="mark">a</span> On Arete &mdash; the casting '
           'hand, the arts&rsquo; ceiling, and the will&rsquo;s gate '
           'beneath both &mdash; see M20, folios 328&ndash;329, whence '
           'this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On Willpower &mdash; '
           'the certain success, one a turn, the resistance of the '
           'permanent rating, and the refresh &mdash; see folios 330 and '
           '394.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On '
           'Quintessence pooled against the Avatar &mdash; held, drawn by '
           'the turn, and spent against the wall to the third point '
           '&mdash; see folios 330&ndash;331.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'Paradox as account rather than asset, see folio 331 and the '
           'court&rsquo;s own folio, 533a of this binding, which holds '
           'the law entire.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The four numbers are '
           'four bound folios wearing a summary: Arete&rsquo;s ladder at '
           '46a, the Seekings at 43b, the blood at 78a, the court at '
           '533a &mdash; and this leaf is the chapter&rsquo;s clasp, '
           'closing the making around measures the binding built '
           'elsewhere.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'will&rsquo;s gate beneath the arts &mdash; the permanent '
           'rating capping hand and Spheres alike &mdash; is '
           '46a&rsquo;s dispute armed: whatever the will is, the law '
           'makes it load-bearing, and the verso&rsquo;s schools '
           'inherit the weight.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'certain success is the one purchase in this binding the '
           'court of 533a never bills: the will spent is the self '
           'asserted, not the world argued with, and the margin files '
           'the exemption as the setting&rsquo;s kindest ruling.</p>',
 'h1': 'Arete and Will',
 'hagahah': 'Enlightenment has a price in points; the points are the '
            'least of it.',
 'inner': '<p><span class="lemma">The hand and its ceiling.</span> '
          'Arete&rsquo;s plain sense, gathered from the folios it '
          'governs: the number is the whole casting hand &mdash; every '
          'working of chapter XI rolls it &mdash; and the ceiling on '
          'the arts, for no Sphere may be held above the '
          'enlightenment that holds it. The granted first dot is the '
          'waking&rsquo;s own gift; the climb is 43b&rsquo;s trials and '
          'no other road, per the standing law the verso prices. The granted dot also seats the binding&rsquo;s egalitarian floor: every mage, however new, holds the whole engine of chapter XI in miniature &mdash; one die of enlightenment is still enlightenment, and the folios of casting never ask for more than the hand can hold.</p>\n'
          '        <p><span class="lemma">The gate beneath.</span> The '
          'will-gate&rsquo;s plain sense, easy to read past and ruinous '
          'to miss: a permanent Willpower lower than Arete caps the '
          'casting hand and the arts&rsquo; maxima at the will&rsquo;s '
          'height &mdash; enlightenment outrunning selfhood is '
          'clipped to selfhood&rsquo;s measure. The clause is the '
          'chapter&rsquo;s quiet doctrine: the summit is climbed by '
          'the whole person, and the sheet enforces the '
          'wholeness.</p>\n'
          '        <p><span class="lemma">The treasury&rsquo;s two '
          'faces.</span> Willpower&rsquo;s plain sense: the pool spends '
          '&mdash; one certain success a turn, or the self held '
          'against frenzy, fear, and override &mdash; and the '
          'permanent rating resists, rolled where the soul itself '
          'is the target. The two faces are one trait seen as '
          'purse and as spine, and the refresh clauses feed both: '
          'rest, nature served, the scene that restores. The '
          'certain success&rsquo;s finest print is its mercy: the '
          'bought success also bars the botch, which makes the '
          'point the game&rsquo;s only insurance against its own '
          'worst die.</p>\n'
          '        <p><span class="lemma">The metered blood.</span> '
          'Quintessence&rsquo;s plain sense at the sheet: the '
          'Avatar&rsquo;s rating meters the whole economy &mdash; the '
          'pool&rsquo;s depth and the turn&rsquo;s draw alike &mdash; and '
          'the spend is the wall lowered, one per point to three, '
          'per the casting law of 500a. The free and the committed '
          'blood differ as cash and mortgage differ, per 78a&rsquo;s meters; the sheet tracks the cash. The meter&rsquo;s genre consequence is patience: the deep workings of 500b bank essence across scenes, and the Avatar&rsquo;s rating is the banking speed &mdash; the slow soul saves slowly, which the long rituals of the binding stage as virtue.</p>\n'
          '        <p><span class="lemma">The account with no '
          'asset.</span> Paradox&rsquo;s plain sense, and why the '
          'chapter files it here at all: the fourth number sits on '
          'the sheet beside the three pools precisely because it '
          'is not one &mdash; nothing buys it down in advance, no '
          'rating gates it, and its zero is a behavior, not a '
          'purchase. The making hands every character the same '
          'empty account, and the campaign fills it at the rate '
          'of the character&rsquo;s own audacity, which is the system&rsquo;s cleanest piece of moral bookkeeping. The account&rsquo;s one mercy is the court&rsquo;s own, filed at 533a and echoed here: the fees discharge &mdash; the backlash, the quiet, the slow bleed &mdash; and the discharged account reopens at zero, so the number is a season&rsquo;s weather rather than a life sentence, unless the audacity is a habit.</p>',
 'inner_head': 'On the Four Numbers<span class="comm-sub">the inner commentary '
               '&middot; the plain sense &middot; the hand, the gate, and the '
               'pools</span>',
 'name': 'Arete and Will',
 'outer': '<p><span class="lemma">Soul, or stamina.</span> The '
          'will&rsquo;s dispute, as the brief demands. <span '
          'class="voice">Some say</span> Willpower is the soul&rsquo;s own '
          'measure: the trait that resists possession, refuses the '
          'six moves of 224b, and gates enlightenment itself is '
          'plainly the self&rsquo;s depth &mdash; the sheet&rsquo;s one '
          'number for who the character is when everything else is '
          'stripped, which is why the binding&rsquo;s darkest folios '
          'all roll it. <span class="voice">Others say</span> the '
          'trait&rsquo;s own economy argues lower: it spends by the '
          'point, refills from a night&rsquo;s sleep, and buys '
          'successes at the pool table as readily as it holds the '
          'soul at the brink &mdash; a trait that budgets is a '
          'stamina, the psyche&rsquo;s endurance rather than its '
          'essence, and calling every spent point a fragment of '
          'soul makes the sheet&rsquo;s most-used mechanic '
          'unplayably solemn. The first school answers that the '
          'refresh clauses refute the battery reading: the pool '
          'refills from meaning &mdash; nature served, ideals fed '
          '&mdash; and a battery charged by purpose is what soul '
          'means operationally. The second answers that '
          'operational definitions are the Union&rsquo;s whole '
          'epistemology, and enjoys the first school&rsquo;s '
          'discomfort at the company. The folio files the girsa '
          'unharmonized and notes the stakes the will-gate '
          'raises: whichever reading holds, the law caps '
          'enlightenment at the will&rsquo;s height &mdash; so the '
          'question of what Willpower is becomes the question of '
          'what the summit is climbed with, and the chapter closes with that question deliberately open. The schools also share a casualty list: the folios of Quiet and the fall both begin, their margins note, with wills spent past refresh &mdash; whichever reading holds, the empty treasury is where the chapter&rsquo;s dangers shop, and the counsel below prices the vigilance. <span '
          'class="kw">TEYKU</span> &mdash; the trait, spent to the '
          'last point, leaves a person either exhausted or '
          'hollow, and the sheet does not say which.</p>\n'
          '        <p><span class="lemma">The unclimbable '
          'shortcut.</span> The advancement dispute, opened here '
          'and priced overleaf. <span class="voice">Some say</span> '
          'the Seeking-only road is the setting&rsquo;s spine: '
          'enlightenment that could be purchased with experience '
          'points would make the summit a savings plan, and the '
          'trials of 43b exist precisely so that the '
          'sheet&rsquo;s deepest number answers to the soul&rsquo;s '
          'work, not the ledger&rsquo;s. <span class="voice">Others '
          'say</span> the road&rsquo;s exclusivity is softer in the '
          'sources than the doctrine admits: the recensions have '
          'priced the climb differently across editions, tables '
          'house-rule the gate daily, and the verso holds the '
          'variant manuscripts at length. The folio here keeps '
          'only the baseline&rsquo;s plain sense &mdash; the trials '
          'gate the climb, the points price it &mdash; and hands '
          'the girsa&rsquo;ot overleaf, where the prices are the subject and the arguments can spread. One boundary stone is set here because both folios need it: whatever the editions rule about purchase, no recension has ever let the summit be bought without the mountain noticing &mdash; the trials appear in every printing, differing only in their weight, and the constancy is the doctrine.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the will&rsquo;s nature, and the '
               'road&rsquo;s gate</span>',
 'rubric': 'the four numbers',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, continued &middot; of Arete and Will &middot; the deep '
             'measures as law',
 'title': 'Tractate Aliyah · Folio 328a — Arete and Will: the four numbers',
 'type': 'daf'}
