# Folio 328b - The Price. Advancement's economy and its variant
# manuscripts, per the wod-llm-wiki character-creation and arete pages
# (M20 pp.250-266, 328-329; the experience chart).
FOLIO = {'bottom': '<p><span class="lemma">On paying experience aloud.</span> Spend '
           'the advancement scene onscreen: the teacher found, the practice '
           'montage, the trial survived. Points paid at the table&rsquo;s end '
           'in silence buy numbers; points paid in scenes buy the '
           'campaign&rsquo;s continuity &mdash; and the multiplier&rsquo;s '
           'steepness reads as drama instead of bookkeeping when the '
           'climb is visible.</p>\n'
           '        <p><span class="lemma">On choosing the gate '
           'openly.</span> The Arete question &mdash; trials only, or '
           'points with a trial&rsquo;s blessing &mdash; is session-zero '
           'material: pick a girsa, post it with the constitution, and '
           'hold it. A summit whose admission rules change midway '
           'teaches players the mountain is negotiable, and the one '
           'thing every recension agrees on is that it must not '
           'be.</p>\n'
           '        <p><span class="lemma">On the cheap will.</span> '
           'Willpower&rsquo;s gentle price is a design gift: encourage its '
           'purchase, for the will-gate makes it the quiet prerequisite '
           'of every summit &mdash; and a party that raises its will is '
           'raising its stakes tolerance, which the Storyteller can '
           'spend. The cheapest number on the sheet is the one the '
           'whole chapter leans on, and the books priced it kindly on '
           'purpose.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on visible climbs, '
                'posted gates, and kind prices</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The making ends; the paying begins.</span> '
           'The finishing points of the making buy dear: the freebies '
           'price each kind at its own rate, and Arete costs four the dot '
           'against a creation ceiling of three &mdash; one granted, two '
           'bought at most, whatever the points remaining.<sup>a</sup> '
           'After the making, the experience chart governs, and its law '
           'is the multiplier: each trait climbs at a price scaled to its '
           'current height, so the ladder steepens as it rises &mdash; and '
           'Arete&rsquo;s multiplier is the chart&rsquo;s steepest, eight '
           'times the current rating, the priciest number on the '
           'sheet.<sup>b</sup> The climb is doubly gated: the points pay '
           'for the rank the trials of 43b unlock, and neither '
           'suffices alone &mdash; the wallet without the Seeking buys '
           'nothing, the Seeking without the wallet waits.<sup>c</sup> '
           'And the will&rsquo;s price is the chart&rsquo;s gentlest: '
           'raised cheaply, spent freely, recovered by living well '
           '&mdash; the one deep measure the design begs the sheet to grow.<sup>d</sup> So the chapter&rsquo;s accounting closes: the making&rsquo;s allowances spent, the chart&rsquo;s multipliers posted, and the two gates &mdash; wallet and trial &mdash; standing where the summit road narrows, checked in that order by no one and in both orders by everyone.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> '
           'Come and hear why the summit costs eight to one. The '
           'teachers asked: if enlightenment is the point of the game, '
           'why is it priced like contraband? And answered from the '
           'design&rsquo;s own grain: because the multiplier is the '
           'setting speaking &mdash; every rank of the hand doubles the '
           'possible, so the price walks with the power; and because '
           'scarcity is the teacher &mdash; the mage who spends a '
           'season&rsquo;s points on one dot of Arete has enacted, in '
           'bookkeeping, the very discipline the dot represents. The chart is a syllabus disguised as a toll booth. And the teachers appended the corollary for Storytellers: a price that steep is a promise that the number matters &mdash; the campaign that hands out Arete like coupons has not been generous; it has repealed the mountain. The '
           'disputants around this text hold the creation ceiling and '
           'the editions&rsquo; quarrel over the gate.</p>',
 'chapter': 'Chapter the Eighth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'chapter VIII closes; the measures priced, the making complete, '
             'and the Middot of chapter IX standing ready to roll it all.',
 'folio': '328B',
 'glossL': '<p><span class="mark">a</span> On the freebie rates and '
           'Arete&rsquo;s creation ceiling &mdash; four the dot, three at '
           'most &mdash; see M20, the making&rsquo;s folios, '
           '250&ndash;266.</p>\n'
           '        <p><span class="mark">b</span> On the experience '
           'chart and its multipliers, Arete&rsquo;s eight-times-current '
           'at the summit of the scale, see the same chapter&rsquo;s '
           'advancement table, abridged here to its principle per the '
           'luachs&rsquo; standing rule.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'double gate &mdash; the points and the trials together '
           '&mdash; see folios 328&ndash;329 and 367&ndash;369, with the '
           'Seekings&rsquo; folio at 43b of this binding.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On '
           'Willpower&rsquo;s gentle pricing and its recovery, see the '
           'advancement table and folio 394; the design&rsquo;s '
           'intention is argued below at its own confidence.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This leaf closes the '
           'chapter&rsquo;s circuit as 82b closed the World&rsquo;s: the '
           'seder dealt at 250, the charts posted at 273 through 303, '
           'and the deep measures priced here &mdash; the Order of '
           'Making is one folio of ten sides, and the Masoret binds '
           'them as such.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'multiplier&rsquo;s theology &mdash; scarcity as teacher '
           '&mdash; is 250b&rsquo;s eight-times ruling kept where that '
           'folio promised it would be argued; and the '
           'trials&rsquo; gate is 43b&rsquo;s law priced at last, as '
           'its Masoret has expected since chapter II.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'editions&rsquo; quarrel below is filed per the '
           'binding&rsquo;s standing law: variant manuscripts, never '
           'harmonized &mdash; and the house girsa&rsquo;ot the '
           'counsel opposite blesses are the same law extended to '
           'the table&rsquo;s own recensions.</p>',
 'h1': 'The Price',
 'hagahah': 'The chart prices the climb in points and the mountain '
            'prices it in persons; only one of the two gives '
            'receipts.',
 'inner': '<p><span class="lemma">Four the dot, three at most.</span> '
          'The creation ceiling&rsquo;s plain sense: the making sells '
          'Arete dear and cuts the sale off at three &mdash; whatever '
          'points remain, the starting summit is capped &mdash; and '
          'the cap is doctrine before it is balance: the newly '
          'woken have not lived enough to be masters, and the '
          'sheet enforces the biography. The freebie rates around '
          'it price the rest of the finishing: the arts, the '
          'measures, the will, each at its own gentle or dear '
          'rate, per the making&rsquo;s table.</p>\n'
          '        <p><span class="lemma">The multiplier&rsquo;s '
          'grammar.</span> The experience chart&rsquo;s plain sense: '
          'prices scale with current height &mdash; the fourth dot of '
          'anything costs more than the second &mdash; so the chart '
          'is a curve, not a menu, and the curve&rsquo;s statement '
          'is universal: growth slows as mastery nears, in '
          'measures, learnings, and arts alike. Arete&rsquo;s '
          'eight-times crown is the curve&rsquo;s far end, and the '
          'Gemara has already read its sermon.</p>\n'
          '        <p><span class="lemma">Neither gate alone.</span> '
          'The double gate&rsquo;s plain sense: the trials unlock and '
          'the points purchase, in that order and only together '
          '&mdash; a Seeking passed with an empty wallet is a rank '
          'earned and unpaid, held in escrow until the points '
          'arrive; points banked without the trial are a wallet '
          'pressed against a locked door. The law&rsquo;s two keys '
          'keep both economies honest: the soul&rsquo;s work cannot '
          'be bought and the bookkeeping cannot be skipped, and '
          'every table that drops one key discovers why the other was load-bearing. The escrow reading is the practical one: trials and points arrive on different calendars, and the sheet holds whichever came first until its partner lands &mdash; a bookkeeping mercy the table should adopt aloud, for nothing sours a Seeking like a surcharge announced after the mountain.</p>\n'
          '        <p><span class="lemma">The kind price.</span> '
          'Willpower&rsquo;s plain sense at the counter: the '
          'chart&rsquo;s gentlest multiplier sits under the '
          'sheet&rsquo;s most-spent number, and the kindness is '
          'architecture &mdash; the will-gate of the recto makes '
          'Willpower the summit&rsquo;s quiet prerequisite, so the '
          'design prices the prerequisite within every '
          'campaign&rsquo;s reach. The counsel opposite spends the '
          'intention; the margin only certifies it visible in '
          'the arithmetic.</p>\n'
          '        <p><span class="lemma">What the points cannot '
          'buy.</span> The chart&rsquo;s silences, read as law: no '
          'price is printed for the Avatar&rsquo;s deepening beyond '
          'its background row, none for the resonance the work '
          'accretes, none for the reputation the chronicle '
          'assigns &mdash; the sheet&rsquo;s deepest changes arrive '
          'unpurchased, by play, and the chart&rsquo;s omissions '
          'are its honest map of where bookkeeping ends. The '
          'binding&rsquo;s advancement doctrine in one sentence: '
          'everything on the chart is for sale, and nothing off it. The silences also mark the chapter&rsquo;s handoff: what the chart declines to price, the chronicle prices in scenes &mdash; and the middot of chapter IX take up exactly there, with the dice that measure what the points have bought.</p>',
 'inner_head': 'On the Counter<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the rates, the gates, and the '
               'silences</span>',
 'name': 'The Price',
 'outer': '<p><span class="lemma">The ceiling&rsquo;s girsa&rsquo;ot.</span> '
          'The creation-cap dispute, with its house recensions. <span '
          'class="voice">Some say</span> the three-dot ceiling is '
          'canon&rsquo;s wisdom: a starting master unbalances every '
          'table he joins, the cap keeps the campaign&rsquo;s first '
          'season about becoming, and the recensions that raised or '
          'waived it &mdash; the elder-game tables, the archmage '
          'chronicles &mdash; all constructed elaborate scaffolding to '
          'survive their own generosity. <span class="voice">Others '
          'say</span> the ceiling is a default, not a commandment: '
          'the sources themselves stage games above it, the '
          'scaffolding exists because the books built it, and a '
          'table of experienced players opening at Arete five is '
          'playing the same game at a different altitude &mdash; the '
          'cap protects new tables and merely patronizes old ones. '
          'The schools converge, as the making&rsquo;s schools do, on '
          'the posted constitution: whatever ceiling the table '
          'sets, set it aloud and hold it &mdash; and the folio files '
          'the girsa&rsquo;ot as the binding files all its variants, '
          'unharmonized, with the baseline&rsquo;s three marked as the printed floor beneath the arguing. One more girsa the survey must file: the elder tables that open above the ceiling inherit the will-gate at altitude, and their scaffolding is mostly Willpower &mdash; the recensions agree, wherever they set the door, that the frame must be strong before the house is tall, which is the recto&rsquo;s doctrine surviving every renovation. The survey files the renovations as it files all girsa&rsquo;ot: unranked, attributed, and open to the next table&rsquo;s carpentry.</p>\n'
          '        <p><span class="lemma">Points, or trials '
          'only.</span> The gate dispute, the chapter&rsquo;s last. '
          '<span class="voice">Some say</span> the editions have '
          'quarreled in the open and the binding must file the '
          'quarrel: one recension&rsquo;s summit answers to points '
          'with the trial as color, another&rsquo;s to trials with '
          'the points as paperwork, and the baseline&rsquo;s double '
          'gate is a treaty between the two &mdash; workable, '
          'printed, and philosophically restless, for a treaty '
          'is not an answer. <span class="voice">Others say</span> '
          'the restlessness is the design&rsquo;s finest feature: '
          'the double gate makes the table decide, every '
          'campaign, whether its summit is earned inward or '
          'outward &mdash; and the deciding is the Ascension '
          'question itself, smuggled into the bookkeeping where '
          'no player can dodge it. The first school answers '
          'that load-bearing ambiguity is still ambiguity, and '
          'the second answers that so is the setting, by '
          'charter. The folio closes the chapter on their '
          'agreement: the chart prices what can be priced, the '
          'trials guard what cannot, and the sheet&rsquo;s last line &mdash; the one the hagahah has been reading all along &mdash; is that the mountain keeps its own books. And the chapter&rsquo;s true last word belongs to the seder that opened it: the character exists before the numbers, the numbers exist to be argued with, and ten sides of charts and prices have been, on inspection, one long argument conducted in the character&rsquo;s favor. <span class="kw">TEYKU</span> &mdash; the '
          'receipts are in points; the climb, on inspection, '
          'was always in persons.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the ceiling, and the gate</span>',
 'rubric': 'the advancement&rsquo;s economy',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eighth: The Order of '
             'Making, concluded &middot; of the price of growth',
 'title': 'Tractate Aliyah · Folio 328b — The Price: the advancement&rsquo;s economy',
 'type': 'daf'}
