# Folio 384b - The Contract. Verso of the Golden Rule: the table's social
# contract - session zero, lines and veils, stakes, and review - gathering
# the tractate's standing procedures into one law.
FOLIO = {'bottom': '<p><span class="lemma">On running session zero.</span> Treat it as a session: '
           'scheduled, attended, and played &mdash; not a form circulated by message. The '
           'agenda writes itself from this tractate&rsquo;s standing orders: the vulgarity '
           'standard and witness census of 533a and 533b; the consent procedures of 519a '
           'and 152a&rsquo;s mirror; the genre declarations scattered through the Sphere '
           'folios; lines and veils on paper; and the review clause &mdash; when and how '
           'the table revisits all of it. Two hours of session zero buy back twenty of '
           'mid-chronicle argument, at an exchange rate no other preparation matches.</p>\n'
           '        <p><span class="lemma">On the living document.</span> The contract '
           'drifts or it dies: characters change, players change, the chronicle darkens or '
           'lightens past its founding assumptions, and the table that never re-opens its '
           'session-zero rulings is running on a treaty nobody rereads. Calendar the '
           'review &mdash; between stories is natural &mdash; and normalize the mid-scene '
           'invocation: any player may call for the fade, the veil, or the pause, and the '
           'call is honored first and discussed later, in that order, always.</p>\n'
           '        <p><span class="lemma">On the Storyteller&rsquo;s seat at the '
           'table.</span> The contract binds her too, and drafting it is not '
           'self-limitation but self-defense: the posted standard is what stands between '
           'her judgment calls and the appearance of caprice, and the Storyteller who '
           'rules from a published constitution spends her rule-zero capital only where '
           'she means to. The recto gave her the override; this verso is how she keeps '
           'the table&rsquo;s consent to hold it, which is the only tenure the office '
           'has.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the zeroth session, the '
                'review, and the office&rsquo;s tenure</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The table has a law of its own,</span> and it is made, '
           'not found: before the chronicle&rsquo;s first scene, the troupe convenes and '
           'agrees its terms, and the agreement is the game&rsquo;s true '
           'foundation.<sup>a</sup> Its clauses the tractate has been issuing piecemeal '
           'and here gathers: the standards of vulgarity and witness, posted; the '
           'consent procedures for the arts that enter minds and bodies, written; the '
           'genre declared &mdash; what kind of night, what kind of fear, what kind of '
           'victory; and the <span class="term">lines</span> and <span '
           'class="term">veils</span> recorded &mdash; what never appears, and what '
           'appears only behind the curtain.<sup>b</sup> The contract binds every seat '
           'including the largest; it is invoked mid-scene by any player without '
           'argument, the call honored first and discussed after; and it is reviewed at '
           'intervals the troupe sets, for a contract that cannot be reopened is not '
           'agreement but archaeology.<sup>c</sup> Stakes are set before dice are '
           'rolled: no roll is made whose meanings the table has not '
           'heard.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence a '
           'whole folio of law the rulebooks print as advice? Come and hear the '
           'tractate&rsquo;s own evidence: forty dafs into this binding, every chapter '
           'has ended at the same bench &mdash; the Sphere folios post standards, the '
           'Tradition folios post warnings, the witness folios post censuses, and the '
           'Later Authorities of every page say <span class="aside">decide in session '
           'zero</span> so reliably that the phrase is this tractate&rsquo;s heartbeat. '
           'A directive issued forty times is not advice; it is law that lacked a '
           'folio, and the redactor, arriving at the chapter of measures, gave it one. '
           'The verso position is the argument: rule zero and the contract are one '
           'leaf, two sides &mdash; the power and its terms, printed so that neither '
           'can be cited without turning past the other. The disputants opposite take '
           'up what the gathering changes, and whether writing the table&rsquo;s law '
           'down strengthens the table or the law. And note what the gathering is not: '
           'it invents nothing. Every clause on this page was already binding at some '
           'table somewhere as unspoken custom; the folio&rsquo;s whole work is '
           'conversion &mdash; custom into text, text into terms, terms into a thing a '
           'stranger can be handed on the first night and sign.</p>',
 'chapter': 'Chapter the Ninth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; verso of the Golden '
             'Rule, and its terms: the recto grants the power, this side writes the '
             'lease.',
 'folio': '384B',
 'glossL': '<p><span class="mark">a</span> On session zero, troupe style, and the '
           'table&rsquo;s shared authorship, see M20&rsquo;s storytelling chapters and '
           'the Book of Secrets&rsquo; chronicle material.</p>\n'
           '        <p><span class="mark">b</span> On lines and veils and kindred '
           'consent tools, see the storyteller-craft literature the books cite and '
           'the safety material of the hobby&rsquo;s later recensions; the tractate '
           'restates the practice as law without reproducing any one system.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the standing '
           'session-zero directives gathered here, see folios 533a/b, 519a, 152a, '
           '154a, 156a, 512a, 515a, and 522a of this binding &mdash; the '
           'Gemara&rsquo;s forty citations, abridged.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On stakes before '
           'dice, see the duel law of folio 143, wanting, whose brief already '
           'promises the clause; combat&rsquo;s folio 409 will repeat it, on '
           'purpose.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto&rsquo;s loaded-gun dispute '
           'is answered here as fully as it can be: the contract is the safety, and '
           'the disputants of 384a signed this page as their treaty. The Masoret '
           'witnesses the signatures.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'contract&rsquo;s in-fiction mirror is the Council&rsquo;s own law: '
           'Protocols, parley, and the tenth chair of folio 2a &mdash; a troupe and '
           'a Convocation solve the same problem, which is how strangers share a '
           'world without a war.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'mid-scene invocation rhymes with 152b&rsquo;s seer protections and '
           '519a&rsquo;s consent floor: the tractate&rsquo;s three '
           'stop-the-scene laws, one per audience &mdash; character, player, '
           'table &mdash; and all three honored first, discussed after.</p>',
 'h1': 'The Contract',
 'hagahah': 'The tractate said &ldquo;decide in session zero&rdquo; forty times before '
            'noticing it was legislating. Commentaries are like that: the law arrives '
            'disguised as repetition, and the redactor&rsquo;s whole art is catching '
            'the disguise. This folio is the catch, filed where the measures could '
            'not miss it.',
 'inner': '<p><span class="lemma">Made, not found.</span> The plain sense, against the '
          'romantic error: good tables are drafted, not discovered. The troupe that '
          'clicks without a contract is running on lucky congruence &mdash; similar '
          'assumptions, compatible nerve &mdash; and lucky congruence survives '
          'until the first genuinely hard scene, which in this game&rsquo;s genre '
          'arrives on schedule. The contract converts luck into structure while the '
          'luck still holds; that is all it does, and it is enough.</p>\n'
          '        <p><span class="lemma">Lines and veils.</span> The pair&rsquo;s '
          'plain sense: a line is content that does not enter the fiction at all; '
          'a veil is content that occurs offstage &mdash; established, consequential, '
          'undepicted. The instrument&rsquo;s genius is granularity: the table '
          'need not agree about what is fearsome, only about what is played, and '
          'the horror chronicle keeps its teeth while every player keeps her '
          'exits. Written, the list protects without exposure &mdash; no one '
          'explains a line, ever; the writing is the whole explanation owed.</p>\n'
          '        <p><span class="lemma">The genre declared.</span> The clause&rsquo;s '
          'plain sense: what kind of night names the register &mdash; street or '
          'cosmic, survival or intrigue; what kind of fear names the horror&rsquo;s '
          'address &mdash; the body, the mind, the ones you love; what kind of '
          'victory names the win condition the chronicle honors, for a table '
          'expecting triumph and a table expecting dignified loss are playing '
          'different games with the same dice. The declaration costs three sentences '
          'and prevents the commonest wreck in the hobby, which is not offense but '
          'genre collision, discovered at speed.</p>\n'
          '        <p><span class="lemma">Before the chronicle&rsquo;s first '
          'scene.</span> The timing, plainly: the contract precedes play because '
          'consent gathered mid-scene is gathered under duress of momentum &mdash; '
          'the story already moving, the table already watching, the cost of any '
          'objection already visible to the objector. Session zero is the one '
          'meeting where nothing is yet at stake, which is exactly what makes '
          'everything decidable there.</p>\n'
          '        <p><span class="lemma">Honored first and discussed '
          'after.</span> The invocation order, plainly, because the order is the '
          'law: the call stops the scene, then the table talks, and never the '
          'reverse. A safety tool that opens a debate at the moment of use is a '
          'debate tool; the deferral of discussion is what makes invocation '
          'cheap enough to actually happen, and the table that has never had a '
          'call is either blessed or &mdash; more often &mdash; priced the call '
          'too high.</p>\n'
          '        <p><span class="lemma">Not agreement but archaeology.</span> '
          'The review clause&rsquo;s plain sense: consent is tensed &mdash; it '
          'was given then, about that, by those people &mdash; and a chronicle '
          'is long. The scheduled review re-tenses the whole document, and its '
          'quiet second function is amnesty: the standing appointment lets any '
          'player raise what mid-session courage would not, which is most of '
          'what needs raising.</p>\n'
          '        <p><span class="lemma">No roll whose meanings the table has '
          'not heard.</span> The stakes clause, plainly: dice allocate outcomes, '
          'so the outcomes must exist before the allocation &mdash; what success '
          'buys, what failure costs, said aloud. The clause kills the '
          'gotcha roll and the retroactive stake alike, and it is the '
          'contract&rsquo;s daily working face: most tables will invoke no line '
          'for months, and will use this clause forty times a night, which is '
          'why it is drafted last and remembered first.</p>',
 'inner_head': 'On the Terms<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; clause by clause, seat by seat</span>',
 'name': 'The Contract',
 'outer': '<p><span class="lemma">Advice into law.</span> The promotion dispute. '
          '<span class="voice">Some say</span> the redactor overreached: the books '
          'print this material as counsel precisely because tables differ &mdash; '
          'the one-shot among old friends needs no charter, the convention game '
          'needs a waiver, and codifying kindness makes it brittle: a table '
          'lawyering its safety tools has lost the safety and kept the tools. '
          '<span class="voice">Others say</span> the difference between advice '
          'and law is what happens when it fails: advice unfollowed is a pity, '
          'law unfollowed is a breach, and the players this folio protects are '
          'exactly the ones who cannot afford for the protection to be a pity. '
          'The gathering changes the default &mdash; from opt-in care to opt-out '
          '&mdash; and defaults, as the Adepts&rsquo; folio taught, are where '
          'power actually lives. The first school keeps the flexibility; the '
          'second keeps the floor; and the folio&rsquo;s own drafting takes the '
          'second side while granting the first its clause: the troupe sets its '
          'terms, including terse ones &mdash; but it <span '
          'class="aside">sets</span> them, aloud, which is the law&rsquo;s '
          'irreducible core.</p>\n'
          '        <p><span class="lemma">Binds every seat including the '
          'largest.</span> The secrecy dispute: what may the Storyteller withhold? '
          '<span class="voice">Some say</span> everything but the terms: mystery '
          'is her stock in trade, the hidden clock and the masked antagonist are '
          'the genre&rsquo;s load-bearing walls, and a contract that demands '
          'disclosure of content has confused safety with spoilers. <span '
          'class="voice">Others say</span> the line is real but finer: content '
          'may be hidden, category may not &mdash; the player owed no warning '
          'about the traitor is owed warning that betrayal is on the menu, and '
          'the lines-and-veils list is precisely a categorical disclosure the '
          'Storyteller makes about her own locked drawers. The schools agree at '
          'the extremes and blur in the middle, where every table&rsquo;s '
          'horror lives; the review clause is their standing arbitration; and '
          'the tractate notes that this exact dispute, at Council scale, is '
          'folio 188&rsquo;s whole brief, which is either an irony or '
          'the setting doing its job. A third voice adds the working test: whatever '
          'the Storyteller keeps locked, the drawer itself is declared &mdash; a '
          'table told there are drawers stops rattling the furniture, and one told '
          'there are none deserves the truth of it.</p>\n'
          '        <p><span class="lemma">Strengthens the table or the '
          'law.</span> The last difficulty, the redactor&rsquo;s own. <span '
          'class="voice">Some say</span> writing the table&rsquo;s law into a '
          'folio strengthens tables: the practice travels, the newcomers '
          'inherit it, and the forty scattered directives become one page a '
          'troupe can actually adopt. <span class="voice">Others say</span> '
          'the page strengthens mostly the tractate: gathered law flatters the '
          'gatherer, and the real contract lives in the room, unwritable, in '
          'tones of voice and glances the finest folio cannot bind. The '
          'tractate concedes the point with unusual speed &mdash; it is paper, '
          'and knows what paper cannot hold &mdash; and answers only that the '
          'unwritable contract has always needed a written porch to stand on, '
          'and that every tradition in this binding, from the Record to the '
          'lineage books to the stapled journal, made the same bet. <span '
          'class="kw">TEYKU</span> &mdash; let the room keep the last word, '
          'as rooms do.</p>',
 'outer_head': 'The Signatories<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the promotion, the drawer, and the porch</span>',
 'rubric': 'the table&rsquo;s law, gathered and signed',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'continued &middot; of the contract &middot; session zero as law',
 'title': 'Tractate Aliyah · Folio 384b — The Contract: the table’s law, gathered and signed',
 'type': 'daf'}
