# Folio 384a - The Golden Rule. Chapter IX opens; facts per the
# wod-llm-wiki dice-pools page (M20 p.384).
FOLIO = {'bottom': '<p><span class="lemma">On overriding visibly.</span> The rule&rsquo;s best '
           'practice is candor at one remove: the Storyteller who must set the dice aside '
           'says so &mdash; not always in the moment, for suspense has its rights, but by '
           'session&rsquo;s end or story&rsquo;s, in the open. The override concealed '
           'forever becomes a habit, the habit a style, and the style a game whose dice are '
           'scenery; the override confessed becomes what the law intends: a judgment call, '
           'reviewable, rare. The verso&rsquo;s contract holds the procedure; this '
           'page&rsquo;s counsel is only the disposition &mdash; rule zero is exercised '
           'best by tables that would be told.</p>\n'
           '        <p><span class="lemma">On rarity.</span> The rule invoked weekly is not '
           'rule zero but house style, and should be written down as such &mdash; a table '
           'that routinely ignores soak or initiative has amended its rules, not '
           'suspended them, and owes itself the honesty of the amendment. Reserve the '
           'naked override for the cases it was drafted for: the dice about to ruin a '
           'story everyone is enjoying, the rule about to punish a player for the '
           'system&rsquo;s gap, the once-a-chronicle moment where the mechanics and the '
           'meaning part ways.</p>\n'
           '        <p><span class="lemma">On reading this chapter.</span> Everything that '
           'follows in Middot &mdash; the pools, the walls, the ones, the track &mdash; '
           'is law subject to this folio, and the chapter is ordered accordingly: the '
           'repeal is printed before the statutes, so that no reader mistakes the '
           'statutes for the point. Learn them anyway, and learn them cold; the '
           'Storyteller who overrides what she has mastered is exercising judgment, and '
           'the one who overrides what she never learned is improvising a different '
           'game, and the players can always tell which.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on candor, rarity, and mastering '
                'what you may repeal</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The rules serve the story,</span> and may be set aside by '
           'the one who serves the table.<sup>a</sup> This is the whole law; the rest of '
           'the chapter is commentary, and knows it. The setting-aside is bounded by its '
           'own purpose: it is exercised for the story&rsquo;s sake and the table&rsquo;s, '
           'never for the server&rsquo;s; it is exercised fairly, as the books themselves '
           'insist, or it is not this rule but its counterfeit;<sup>b</sup> and it is '
           'exercised over rules mastered, for one cannot suspend what one never '
           'held.<sup>c</sup> The dice may be used, bent, or dispensed with entirely as '
           'the troupe&rsquo;s confidence allows; the story&rsquo;s needs outrank every '
           'statute printed after this folio; and no combination of statutes printed '
           'after this folio may be read to repeal it.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why does a book '
           'of rules legislate its own suspension &mdash; and legislate it <span '
           'class="aside">first</span>? Come and hear the drafting problem: a game about '
           'reality being negotiable cannot open with non-negotiable reality, or the '
           'form would refute the content on page one. The drafters&rsquo; solution was '
           'the one their own setting proposes &mdash; make the highest law a law about '
           'who may rewrite law, and put it before the statutes as the Consensus stands '
           'before physics. So the rulebook Awakens its reader in its first ruling: the '
           'system you are about to learn is a consensus, the Storyteller is its local '
           'reality, and the dice, like the Sleepers they will later be compared to, '
           'enforce an agreement exactly as far as the agreement holds. The disputants '
           'around this text quarrel over whether this is wisdom or a loaded gun on the '
           'table, and the tractate observes that it is a rule, so the answer is '
           'presumably both. And the license is a ladder, not a switch: the books extend '
           'it in degrees &mdash; use the dice, bend them fairly, set them aside &mdash; '
           'and each rung is climbed by the troupe&rsquo;s confidence, not the '
           'Storyteller&rsquo;s appetite. Nor does the rule appear once and retire: the '
           'later chapters remember it aloud, telling the reader in so many words that '
           'what follows may be modified or discarded outright. A statute that keeps '
           'announcing its own repealability is not modest; it is consistent, and the '
           'consistency is the argument.</p>',
 'chapter': 'Chapter the Ninth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in '
             'the form of a daf; no rules text is reproduced &middot; set in Abbess &amp; '
             'Goudy Old Style after the M20 interior &middot; chapter IX of Middot opens '
             'here, with the law that outranks the chapter.',
 'folio': '384A',
 'glossL': '<p><span class="mark">a</span> On the Golden Rule &mdash; the rules as servants '
           'of the story, to be used, fudged fairly, or abandoned &mdash; see M20, the '
           'systems chapter&rsquo;s opening, folio 384, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On fairness as the rule&rsquo;s own '
           'internal bound, see the same passage; the books say fudge if you must, and '
           'say fairly in the same breath.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On abandoning the rules '
           'only when the group&rsquo;s confidence allows, see the same; the license is '
           'graduated, not absolute.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On every recension '
           'printing some form of this rule first or near-first, see the systems '
           'chapters of each; the placement is the doctrine.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is cited by silence '
           'throughout the tractate: every Later Authorities band that says decide, '
           'post, or rule is this law exercised, and the Masoret has counted the '
           'citations and given up counting.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The rule&rsquo;s '
           'setting-side rhyme is folio 62, wanting: the Consensus is rule zero worked '
           'at cosmic scale, and the Storyteller&rsquo;s table is a reality zone with '
           'snacks. The comparison is the Gemara&rsquo;s and the tractate stands by '
           'it.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'contract that makes the rule safe to hold is overleaf at 384b; read the '
           'pair as one law, for the recto without the verso is exactly the loaded '
           'gun the disputants fear.</p>',
 'h1': 'The Golden Rule',
 'hagahah': 'A law permitting its own repeal, printed first: the drafters knew their '
            'audience. What is less noticed is that they also knew their setting &mdash; '
            'the first rule of a game about consensual reality is a consensus about '
            'rules, and nobody Awakens by accident.',
 'inner': '<p><span class="lemma">The one who serves the table.</span> The plain sense '
          'of the office: rule zero vests in the Storyteller not as owner but as '
          'servant &mdash; the phrasing is the law&rsquo;s whole theory of authority. '
          'She holds the override because someone must hold it for the story to have '
          'a working spine, and she holds it in trust: for the table&rsquo;s '
          'enjoyment, the story&rsquo;s shape, and the game&rsquo;s continued '
          'existence, in that order on a good night and reversed on a desperate '
          'one.</p>\n'
          '        <p><span class="lemma">Never for the server&rsquo;s.</span> The '
          'self-dealing bound, plainly: the override exercised to win, to punish, to '
          'protect a pet plot from the players&rsquo; better idea, or to spare the '
          'Storyteller preparation she owed is the counterfeit the Mishnah names. '
          'The test is beneficiary analysis, and it is usually easy: ask who the '
          'ruling served, and if the honest answer is the person who made it, the '
          'rule was not this rule.</p>\n'
          '        <p><span class="lemma">Over rules mastered.</span> The competence '
          'clause, plainly: the license is graduated &mdash; the books extend it as '
          'the group&rsquo;s confidence grows &mdash; and its floor is knowledge. '
          'Suspending the initiative ladder because the scene sings without it is '
          'rule zero; suspending it because nobody learned it is a house rule '
          'wearing a borrowed halo, and should be promoted honestly to what it '
          'is.</p>\n'
          '        <p><span class="lemma">Used, bent, or dispensed with.</span> The '
          'three modes, plainly, and they are rungs: a new table uses the rules as '
          'written, because the written rule is the only trust it has yet built; a '
          'seasoned one bends them fairly, the fairness being the visible half of the '
          'bending; and a troupe grown confident may set them aside altogether, '
          'because it has replaced the statute with the thing the statute was '
          'scaffolding for. The ladder is climbed together or not at all &mdash; one '
          'player&rsquo;s mastery does not license the table&rsquo;s suspension, and '
          'the books&rsquo; phrasing puts the confidence in the group, where it '
          'belongs.</p>\n'
          '        <p><span class="lemma">Printed after this folio.</span> The '
          'territorial clause, plainly: the law claims the chapter that follows it, '
          'and by extension the book &mdash; the pools of 385, the retries and their '
          'rising walls, the ones of 393, the track of 406 are all named subjects of '
          'this sentence before they are ever stated. A reader who meets the statutes '
          'first has read the book backward; the drafters bound them in this order '
          'on purpose.</p>\n'
          '        <p><span class="lemma">May not be read to repeal it.</span> The '
          'entrenchment clause, plainly: no accumulation of specific rules &mdash; '
          'combat&rsquo;s ladders, magick&rsquo;s procedures, the track&rsquo;s '
          'arithmetic &mdash; outranks the general law of their purpose. The '
          'clause exists because rules accrete gravity: a table three years into a '
          'chronicle can forget that its bookkeeping is optional, and the '
          'entrenchment is the drafters reaching forward in time to remind them. '
          'The tractate, which is itself an accretion of rules commentary, prints '
          'the reminder extra large.</p>\n'
          '        <p><span class="lemma">And knows it.</span> The chapter&rsquo;s '
          'self-awareness, plainly: everything after this folio is subordinate '
          'legislation, and the folios themselves will say so at intervals &mdash; '
          'the walls of 385 bend, the track of 406 fades to black, the ones of '
          '393 serve the story or serve nothing. Middot is a chapter of measures '
          'under a law that outranks measurement, which is either a paradox or '
          'the design, and the design, as ever in this tractate, is the '
          'paradox kept honest.</p>',
 'inner_head': 'On the Law<span class="comm-sub">the inner commentary &middot; the plain '
               'sense &middot; the office, its bounds, and its entrenchment</span>',
 'name': 'The Golden Rule',
 'outer': '<p><span class="lemma">Wisdom or a loaded gun.</span> The trust dispute, '
          'stated at full strength because the folio can bear it. <span '
          'class="voice">Some say</span> rule zero is the honest name for what every '
          'game already is: no rulebook adjudicates itself, someone always holds '
          'the override, and a system that admits it &mdash; bounds it, names its '
          'beneficiary, prints it first &mdash; has armored the table against the '
          'covert version, which is worse everywhere it operates. The rule does not '
          'create the Storyteller&rsquo;s power; it discloses it, and disclosure is '
          'the only regulation power accepts. <span class="voice">Others say</span> '
          'the disclosure is the danger dressed as the cure: a printed license '
          'reads, to the wrong holder, as permission &mdash; and the wrong holders '
          'are precisely the ones who quote it. Every table that has watched a '
          'story railroaded past the dice, a death annulled for a favorite, a '
          'failure invented for pacing has heard this folio cited in the '
          'wreckage. The first school answers that abusers abuse unlicensed too, '
          'and at least the license names the standard they violated; the second '
          'answers that standards without enforcement are stationery; and the '
          'verso&rsquo;s contract is both schools&rsquo; treaty &mdash; the '
          'enforcement being the table itself, which can always, as the '
          'disputants note with respect, get up.</p>\n'
          '        <p><span class="lemma">The story&rsquo;s needs outrank.</span> '
          'But whose story? <span class="voice">Some say</span> the '
          'Storyteller&rsquo;s: the office and the word share a root, the '
          'chronicle is her composition in the way the working is the '
          'mage&rsquo;s, and the players&rsquo; protection is the contract, not '
          'co-authorship. <span class="voice">Others say</span> the possessive is '
          'plural or the rule is misdrafted: the story that outranks the dice is '
          'the one the table is telling together &mdash; the books&rsquo; own '
          'troupe-style counsel &mdash; and a Storyteller who reads &ldquo;the '
          'story&rdquo; as &ldquo;my outline&rdquo; has confused the container '
          'with the thing contained. The dispute is as old as the hobby and '
          'wears this folio as its favorite coat; the tractate notes only that '
          'every Later Authorities band in this binding says <span '
          'class="aside">the table</span> where it could have said the '
          'Storyteller, and that the drafting was not careless.</p>\n'
          '        <p><span class="lemma">The form would refute the '
          'content.</span> The form-paradox, faced as the brief demands. <span '
          'class="voice">Some say</span> the Gemara&rsquo;s reading is too '
          'clever: the rule is a practical apology to overwhelmed novices, not a '
          'metaphysical gesture, and finding the Consensus in a sidebar is this '
          'tractate&rsquo;s occupational disease. <span class="voice">Others '
          'say</span> the disease is diagnosis: a game that models reality as '
          'negotiated agreement, published with a first rule making its own '
          'reality negotiable, has either built the finest formal joke in the '
          'hobby or built it by accident &mdash; and the drafters&rsquo; thirty '
          'years of keeping the rule first, recension after recension, argues '
          'against accident. The tractate, a Talmud about a rulebook, is '
          'structurally incapable of neutrality here and admits it: the '
          'form-paradox is the reason this binding exists, and the reader '
          'holding a commentary on a game inside a commentary on commentary is '
          'invited to rule on it herself, from experience. <span '
          'class="kw">TEYKU</span> &mdash; printed, as is fitting, where the '
          'chapter&rsquo;s statutes can all see it.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the gun, the possessive, and the form</span>',
 'rubric': 'the law that outranks the chapter',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures '
             '&middot; of the Golden Rule &middot; rule zero as law',
 'title': 'Tractate Aliyah · Folio 384a — The Golden Rule: the law that outranks the chapter',
 'type': 'daf'}
