# Folio 385b - The Count. Verso of the Dice: degrees of success and the
# action economy, per the wod-llm-wiki dice-pools and actions pages
# (M20 pp.387-391).
FOLIO = {'bottom': '<p><span class="lemma">On the extended action as scene.</span> The target '
           'number of successes is a pacing dial: set it, announce the interval, and the '
           'research montage or the ritual night becomes a scene with a visible clock '
           'instead of a single anticlimactic roll. Cap the attempts &mdash; time '
           'pressure is the form&rsquo;s whole flavor &mdash; and honor the botch '
           'clause when it lands: the effort collapsing at roll four of five is the '
           'system handing the table a story, and softening it to a lost interval '
           'spends the form&rsquo;s only real threat.</p>\n'
           '        <p><span class="lemma">On teamwork&rsquo;s edges.</span> Merged '
           'successes make cooperation genuinely strong, which is the point &mdash; '
           'and the abuse case is the crowd: ten assistants merging onto every roll '
           'turns the count into bookkeeping. Rule the helpers as the fiction rules '
           'them &mdash; who can actually fit hands on this task? &mdash; and enforce '
           'the shared botch honestly, for the risk is the price of the merge. The '
           'volunteer who takes the botch on herself is the mechanic&rsquo;s finest '
           'moment; when it happens, let it cost and let it count.</p>\n'
           '        <p><span class="lemma">On the retry question.</span> Trying again '
           'is lawful where the fiction allows another attempt and the stakes have '
           'moved &mdash; time spent, noise made, nerves frayed. The classic '
           'discipline: each retry after failure raises the wall or thins the hand '
           'as frustration mounts, and some doors close entirely, for the world is '
           'not obliged to hold still. A table that retries freely has repealed '
           'failure; a table that forbids retries has repealed persistence; the '
           'craft, as ever in Middot, is the space between, declared before the '
           'dice come out.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on clocks, crowds, and '
                'second tries</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The count has degrees, and the deed has '
           'kinds.</span> One success is the deed done barely; two, done soundly; '
           'three, done cleanly; four, done notably; five and beyond, done as the '
           'stories will tell it.<sup>a</sup> The kinds of deed the law names: the '
           '<span class="term">reflexive</span>, costing no time and usually no '
           'roll; the <span class="term">simple</span>, one roll, one turn, one '
           'success sufficing; the <span class="term">multiple</span>, several '
           'deeds crowded into one turn &mdash; take the smallest of their hands '
           'and divide it among them; the <span class="term">extended</span>, '
           'successes gathered roll by roll toward a set target, each roll an '
           'interval of time, a failure gaining nothing and a botch collapsing '
           'all; and the <span class="term">resisted</span>, two wills rolling '
           'against each other, the greater count winning by its '
           'margin.<sup>b</sup> Helpers may join an extended deed and merge their '
           'successes, each rolling her own hand &mdash; and any helper&rsquo;s '
           'botch ruins the whole, save the helper who can take her botch upon '
           'herself alone.<sup>c</sup> And the will itself may be spent: one point '
           'of Willpower buys one success, certain, before the dice '
           'speak.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear the kinds sorted by one night&rsquo;s work. A scribe '
           'transcribes a grimoire against a deadline: extended &mdash; the target '
           'set by the text&rsquo;s length, the interval an hour, the candle '
           'burning down the attempts. Her rival argues she should be elsewhere: '
           'resisted &mdash; two tongues, the greater count carries the room by '
           'its margin. She writes while arguing: multiple &mdash; the smallest '
           'hand divided, and both suffer. Her apprentice joins the transcription '
           'at midnight: teamwork, successes merged &mdash; until the '
           'apprentice&rsquo;s botch at the third hour threatens the whole '
           'manuscript, and the apprentice, who is honest, takes the spoiled '
           'quire on herself and burns only her own night&rsquo;s work. And at '
           'dawn, one page short, the scribe spends the last of her will for the '
           'certain success and sleeps. The disputants around this text hold the '
           'seams: where the multiple deed&rsquo;s old law went, what the '
           'extended form invites, and what it means that will can buy what '
           'dice only promise.</p>',
 'chapter': 'Chapter the Ninth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso of '
             'the Dice: the recto keeps the roll, this side keeps the ledger.',
 'folio': '385B',
 'glossL': '<p><span class="mark">a</span> On the degrees from marginal to '
           'phenomenal, see M20, the systems chapter, folio 387.</p>\n'
           '        <p><span class="mark">b</span> On the kinds of action &mdash; '
           'reflexive, simple, multiple, extended, resisted, and their '
           'combinations &mdash; see folios 388&ndash;391 of the same '
           'chapter.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On teamwork&rsquo;s '
           'merged successes and the shared botch, see folio 391; the taking-on '
           'clause is the same page&rsquo;s mercy.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Willpower&rsquo;s '
           'purchased success, see the trait&rsquo;s treatment in the same '
           'chapter and folio 328, wanting, where the will&rsquo;s whole economy '
           'will be tried.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The extended deed is the '
           'ritual&rsquo;s engine: folio 500 runs castings on this '
           'form, and 533a&rsquo;s botch-accumulation warning already assumes '
           'it. The scribe&rsquo;s candle is every ritual mage&rsquo;s '
           'clock.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'resisted deed&rsquo;s margin is how workings are fought: dodging '
           'and resistance subtract successes from effects, as the Sphere '
           'folios assumed throughout &mdash; the shield of 512b and the '
           'thickened walls of 522a are this clause wearing armor.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'multiple deed&rsquo;s simplified law replaced the old '
           'pool-splitting of earlier recensions &mdash; a girsa the disputants '
           'try opposite; Time&rsquo;s third rank, folio 522a, buys out of the '
           'penalty entirely, which is why duelists fear the Sphere more than '
           'the sword.</p>',
 'h1': 'The Count',
 'hagahah': 'The will buys one success, certain, before the dice speak. Every '
            'other clause on this page is arithmetic; that one is theology, '
            'smuggled in wearing a number, and the tractate is confident the '
            'drafters knew &mdash; a game about enlightened will was always '
            'going to let will outvote chance exactly once per scene.',
 'inner': '<p><span class="lemma">Done as the stories will tell it.</span> The '
          'degrees&rsquo; plain sense: successes past the first buy quality, '
          'and the ladder gives the table a shared vocabulary for how well '
          '&mdash; the marginal squeak, the clean professional job, the '
          'five-success triumph that enters the chronicle&rsquo;s folklore. '
          'For workings, the count is also quantity: successes are the '
          'currency every Sphere folio spent &mdash; duration, targets, '
          'reach, damage &mdash; and this ladder is where that currency is '
          'minted.</p>\n'
          '        <p><span class="lemma">Costing no time and usually no '
          'roll.</span> The reflexive kind&rsquo;s plain sense: the deed beneath '
          'deliberation &mdash; the will spent, the blow soaked, the thing '
          'noticed because it is in front of you &mdash; takes no turn and '
          'interrupts nothing. The qualifier is load-bearing: some reflexes '
          'carry dice within them, the soak above all, and the class marks not '
          'the absence of rolling but the absence of cost &mdash; a reflexive '
          'deed never crowds the turn, and never joins the multiple '
          'deed&rsquo;s division.</p>\n'
          '        <p><span class="lemma">One point, one success, '
          'certain.</span> The purchase&rsquo;s bounds, plainly: once in a '
          'turn, no more &mdash; but across an extended deed the points may be '
          'spent again and again, roll by roll, which is why the long ritual '
          'drinks will like water. And the bought success carries a second gift '
          'the drafters priced in: the roll it anchors cannot botch, for a '
          'botch requires no successes at all, and one is now guaranteed. The '
          'valve, in other words, is also a rail.</p>\n'
          '        <p><span class="lemma">The smallest of their hands.</span> '
          'The multiple deed&rsquo;s plain sense, in its modern drafting: the '
          'crowded turn is priced by the actor&rsquo;s weakest relevant '
          'craft, then divided &mdash; a clean simplification of the old '
          'splitting law, and deliberately punishing. Doing two things means '
          'doing both worse; the system is on the side of the single '
          'committed act, and every action hero the table admires is, in '
          'these measures, a Time adept or a liar.</p>\n'
          '        <p><span class="lemma">Each roll an interval.</span> The '
          'extended form&rsquo;s plain sense: the target measures the task, '
          'the interval measures the world&rsquo;s patience, and the cap on '
          'attempts &mdash; dawn, the deadline, the guard&rsquo;s rounds '
          '&mdash; is what makes the form a drama rather than an inevitability. '
          'Uncapped extended rolls always succeed eventually, which is why '
          'the Later Authorities call the cap the form&rsquo;s flavor and '
          'the disputants call its absence an invitation.</p>\n'
          '        <p><span class="lemma">Winning by its margin.</span> The '
          'resisted deed&rsquo;s plain sense: the loser&rsquo;s successes are '
          'not wasted but subtracted &mdash; resistance degrades the '
          'winner&rsquo;s result rather than nullifying the contest &mdash; '
          'and the margin, not the victory, is what the fiction renders. The '
          'clause matters most where the Sphere folios already spent it: a '
          'working resisted lands at net strength, and a stubborn will is '
          'armor that never needs donning.</p>\n'
          '        <p><span class="lemma">Take her botch upon herself.</span> '
          'The mercy clause&rsquo;s plain sense: the helper whose effort is '
          'separable may absorb her own catastrophe &mdash; the spoiled '
          'quire, the contaminated sample &mdash; sparing the merged work. '
          'The clause rewards exactly the structure good collaboration has '
          'anyway, discrete contributions honestly owned, and the tractate '
          'suspects the drafters of teaching project management through a '
          'dice rule, successfully.</p>',
 'inner_head': 'On the Ledger<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; degrees, kinds, and mercies</span>',
 'name': 'The Count',
 'outer': '<p><span class="lemma">Where the old law went.</span> The '
          'pool-splitting girsa, tried as promised. The elder manuscripts '
          'divided each deed&rsquo;s own hand; the modern text takes the '
          'smallest hand once and divides that &mdash; simpler, harsher at '
          'the edges, kinder in bookkeeping. <span class="voice">Some '
          'say</span> the revision lost a truth: the old law let the master '
          'of one craft stay masterful while fumbling another, and the new '
          'law drags every crowded turn down to the actor&rsquo;s worst '
          'skill, which slanders the genuinely versatile. <span '
          'class="voice">Others say</span> the revision found a deeper '
          'truth: divided attention is a global tax, not a local one '
          '&mdash; ask anyone who has driven while arguing &mdash; and the '
          'smallest-hand rule models the mind&rsquo;s actual bottleneck '
          'better than the flattering old arithmetic. Both schools '
          'keep their manuscripts; tables blend them, as tables do; and the '
          'tractate files the variant per its standing law, unharmonized, '
          'noting only that this is the rare girsa where the newer text is '
          'the stricter parent.</p>\n'
          '        <p><span class="lemma">What the extended form '
          'invites.</span> The abuse dispute. <span class="voice">Some '
          'say</span> the form is the system&rsquo;s termite: given '
          'intervals enough, every wall falls to patient rolling, so '
          'players learn to convert drama into paperwork &mdash; the '
          'un-cappable research, the ritual stretched across downtime, '
          'success by attrition. <span class="voice">Others say</span> the '
          'termite is a misreading with a missing clause: the form as '
          'written caps attempts by time pressure, collapses on a botch, '
          'and exists precisely to make long work dramatic &mdash; the '
          'abuse requires a Storyteller who deleted the cap, and the '
          'remedy is the folio&rsquo;s own text, applied. The schools '
          'agree, in practice, on the fix and differ on the blame, which '
          'the tractate has learned to read as a dispute already settled '
          'and enjoying itself. A quieter voice notes the form&rsquo;s honest '
          'sibling: where one deed aids another, the craft literature lets '
          'success at the first shave the second&rsquo;s wall, a step per '
          'surplus success and never more than three &mdash; cooperation '
          'between a character&rsquo;s own deeds, priced like everything '
          'else.</p>\n'
          '        <p><span class="lemma">Will can buy what dice only '
          'promise.</span> The purchased success, pressed. <span '
          'class="voice">Some say</span> the clause is a pressure valve and '
          'no more: one certain success per point keeps the incompetent '
          'roll from ruining the competent character, and reading doctrine '
          'into a convenience is the hagahah&rsquo;s joke taken seriously. '
          '<span class="voice">Others say</span> take it seriously: in a '
          'game whose cosmology runs on enlightened will imposing itself '
          'upon a resisting consensus, the one mechanic that lets a '
          'character&rsquo;s will overrule the randomness of the world is '
          'not a convenience but the entire setting in miniature &mdash; '
          'every Willpower point spent is a coincidental magick worked '
          'against the dice&rsquo;s own Consensus, and the mage&rsquo;s '
          'path from spending will to bending reality is a difference of '
          'degree, exactly as her Traditions claim. The first school runs '
          'smoother tables; the second has noticed what game it is '
          'playing; and the folio of Arete and Will, 328, wanting, is '
          'reserved the deciding vote it will decline to cast. <span '
          'class="kw">TEYKU</span> &mdash; certain, before the dice '
          'speak.</p>',
 'outer_head': 'The Auditors<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the split, the termite, and the '
               'will</span>',
 'rubric': 'degrees, kinds, and the purchased success',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'continued &middot; of the count &middot; the action economy as law',
 'title': 'Tractate Aliyah · Folio 385b — The Count: degrees, kinds, and the purchased success',
 'type': 'daf'}
