# Folio 385a - The Dice. Facts per the wod-llm-wiki dice-pools page
# (M20 pp.384-387).
FOLIO = {'bottom': '<p><span class="lemma">On when not to roll.</span> The drama clause is the '
           'folio&rsquo;s working half, and the Storyteller&rsquo;s craft is mostly its '
           'application: the roll reserved for moments where both outcomes are stories, '
           'the trivial waved through, the impossible declined without dice. A table '
           'rolling constantly has delegated pacing to a random number generator; a '
           'table rolling rarely arrives at each roll with the whole session&rsquo;s '
           'attention. Aim for the second table, and let the sound of dice hitting the '
           'surface mean something is genuinely at stake &mdash; the players will learn '
           'the sound the way theatergoers learn a lighting change.</p>\n'
           '        <p><span class="lemma">On the wall&rsquo;s honesty.</span> Set '
           'difficulty before the roll and say it aloud: the wall declared is a promise, '
           'and the wall discovered afterward is the recto of 384 exercised covertly, '
           'which that folio&rsquo;s own counsel forbids. The modifiers are where '
           'judgment lives &mdash; circumstances raising the wall, injuries thinning '
           'the pool &mdash; and judgment spoken is judgment the table can trust, '
           'roll after roll, for years.</p>\n'
           '        <p><span class="lemma">On the four-dice floor.</span> The '
           'books&rsquo; own threshold &mdash; a decent pool starts near four dice '
           '&mdash; is the character sheet&rsquo;s plainest advice: a mage attempting '
           'her specialty should be rolling a real handful, and the player whose '
           'concept keeps producing two-die rolls has built a character the system '
           'will grind. Say so at creation, kindly, with this folio open; the '
           'seder of making, chapter VIII, will say it again with worksheets.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the sound of dice, '
                'declared walls, and decent pools</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The pool is the hand, the wall is the task,</span> '
           'and the count between them is the deed. For an act in doubt, gather one '
           'die for each dot of the governing Traits &mdash; Attribute and Ability '
           'together, as the act requires &mdash; and roll against the <span '
           'class="term">difficulty</span>: each die that meets or beats the wall is '
           'a <span class="term">success</span>, one success does the deed, and more '
           'do it better.<sup>a</sup> The wall unstated is six. The perfect ten '
           'succeeds always, save against the impossible, which no die reaches. The '
           'trivial wall of three or four is no wall at all &mdash; grant the deed '
           'unrolled unless the stakes are dire or the hand is thin.<sup>b</sup> '
           'Circumstance moves the measures by kind: the world&rsquo;s conditions '
           'raise or lower the wall; the body&rsquo;s conditions &mdash; wounds, '
           'fear, exhaustion &mdash; take dice from the hand itself.<sup>c</sup> And '
           'the dice come out only where the outcome makes a difference the story '
           'can feel: the deed without drama is narrated, not rolled.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear the measures at work. A locksmith picks a common lock in her shop: '
           'no roll &mdash; the wall is trivial and nothing rides on it. The same '
           'lock in a guard&rsquo;s hallway at midnight: her hand of Dexterity and '
           'larceny&rsquo;s craft against a wall of six, one success and the door '
           'sighs open. The same lock with her fingers broken: dice gone from the '
           'hand before the roll, for the wound is hers, not the world&rsquo;s. And '
           'the same lock underwater, in the dark, in another&rsquo;s workshop: the '
           'wall climbs toward nine, where only the finest dice stand &mdash; and '
           'where, as the next folio warns, the ones outnumber the nines for '
           'everyone who is not very good or very lucky. The disputants around this '
           'text hold the wall itself: what the number six is, who moved it across '
           'the recensions, and what the dice are doing when nobody is '
           'watching. And mark the ladder of hands before the disputes begin: the '
           'mortal Traits run to five dots, a fifth dot rare and a sixth legendary, '
           'so the walls were drawn for handfuls, not armfuls &mdash; the whole '
           'engine sits in the span between one die and ten, and its drama lives '
           'there too.</p>',
 'chapter': 'Chapter the Ninth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; the count of '
             'successes waits overleaf.',
 'folio': '385A',
 'glossL': '<p><span class="mark">a</span> On the pool, the difficulty, and the count '
           'of successes, see M20, the systems chapter, folios 384&ndash;387, whence '
           'this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the default six, the perfect '
           'ten, and the trivial walls granted unrolled, see the same pages&rsquo; '
           'difficulty discussion.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On external '
           'modifiers to the wall against internal costs to the hand, see the same; '
           'wound penalties are the chief internal case, and folio 406 keeps their '
           'ladder.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On rolling only for '
           'dramatic difference, see the actions material at folio 388 of the same '
           'chapter.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The dice are the only Sleepers at '
           'the table, and they witness everything &mdash; folio 533b&rsquo;s '
           'census, cited here grinning, as the briefs required. The Masoret adds '
           'soberly what the grin covers: the system&rsquo;s randomness is the '
           'game&rsquo;s Consensus, the resistance no player&rsquo;s will '
           'overrides, except as folio 384a provides.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'hand&rsquo;s Traits are chapter VIII&rsquo;s business &mdash; the '
           'attributes at folio 273 and abilities at 275 catalogue what this folio only counts.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The ones that '
           'stalk every roll are folio 393&rsquo;s, overleaf-but-one; the wall for '
           'magick is set by 533a&rsquo;s vulgarity and cast by Arete, folio 500, '
           'wanting &mdash; one engine, many hoods.</p>',
 'h1': 'The Dice',
 'hagahah': 'The dice are the only Sleepers at the table: they enforce the '
            'agreement, they cannot be argued with, and they have never once read '
            'the rules. Every table keeps one player who believes the dice punish '
            'hubris. The tractate takes no position beyond noting that this player '
            'is never entirely wrong at the moments it matters.',
 'inner': '<p><span class="lemma">One die for each dot.</span> The pool&rsquo;s plain '
          'sense: the hand is the character &mdash; her nature and her training '
          'summed in dice &mdash; and the system&rsquo;s first elegance is that '
          'improvement is literal: learn, and there is more of you to roll. The '
          'pairing of Attribute and Ability is chosen per deed, not per sheet: the '
          'same brawling is Strength-led in the clinch and Dexterity-led on the '
          'ropes, and choosing the pairing well is half the '
          'Storyteller&rsquo;s adjudication and most of the player&rsquo;s '
          'advocacy.</p>\n'
          '        <p><span class="lemma">And more do it better.</span> The '
          'count&rsquo;s plain sense, and the verso&rsquo;s whole subject in '
          'advance: success is not binary but graded &mdash; one success scrapes '
          'by, two or three do the deed cleanly, five astonish &mdash; and the '
          'count is the narration&rsquo;s dial, the difference between the lock '
          'opening and the lock opening silently, in the dark, faster than the '
          'guard&rsquo;s glance. The system pays out story in successes, which is '
          'why the next folio counts them like coin.</p>\n'
          '        <p><span class="lemma">Raise or lower the wall.</span> The span, '
          'plainly: the printed walls run from the trivial three to the desperate '
          'nine &mdash; a creek hopped, a meal cooked, a punch thrown at six, a '
          'difficult instrument mastered toward eight &mdash; and the craft is '
          'that the ladder is short: a single step of wall is a real change in '
          'odds, and two are a different deed. The Storyteller who reaches past '
          'nine should usually be reaching for the extended action instead.</p>\n'
          '        <p><span class="lemma">The wall unstated is six.</span> The '
          'default&rsquo;s plain sense: six is the system&rsquo;s sea level '
          '&mdash; the even chance for each die, near enough &mdash; and every '
          'stated wall is a departure from it that means something. Raising the '
          'wall starves successes and breeds ones together, which the next folio '
          'makes doctrine; the practical craft is therefore to prefer pool '
          'modifiers for personal circumstance and wall modifiers for the '
          'world&rsquo;s, exactly as the Mishnah divides them, and to move '
          'either sparingly.</p>\n'
          '        <p><span class="lemma">Save against the impossible.</span> The '
          'ten&rsquo;s limit, plainly: the perfect die crowns a possible deed and '
          'cannot create an impossible one &mdash; no ten shoots the moon down. '
          'The clause is the system&rsquo;s quiet compact with the setting: the '
          'dice operate inside the Consensus, and what stands outside it is not '
          'a hard roll but a different chapter of this tractate, with its own '
          'court and its own prices.</p>\n'
          '        <p><span class="lemma">Grant the deed unrolled.</span> The '
          'triviality clause, plainly: competence is mostly invisible, and the '
          'system says so &mdash; professionals do professional things without '
          'dice, and the roll marks the exceptional case by existing. The two '
          'exceptions are the Mishnah&rsquo;s own: dire stakes, where even the '
          'easy deed deserves witnesses, and the thin hand, where nothing is '
          'trivial &mdash; both restating the same principle, that the dice '
          'measure doubt, and appear where doubt does.</p>\n'
          '        <p><span class="lemma">Narrated, not rolled.</span> The drama '
          'clause&rsquo;s plain sense, and the folio&rsquo;s center of gravity: '
          'rolling is a spotlight, not a physics engine. The system simulates '
          'nothing when nothing is at stake; it allocates attention and risk at '
          'the moments that deserve them, and a Storyteller who internalizes '
          'this clause has learned most of what the chapter teaches &mdash; the '
          'rest is arithmetic, and the arithmetic is overleaf.</p>',
 'inner_head': 'On the Measures<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; hand, wall, and spotlight</span>',
 'name': 'The Dice',
 'outer': '<p><span class="lemma">What the number six is.</span> The default&rsquo;s '
          'dispute. <span class="voice">Some say</span> six is ergonomics: a '
          'near-half chance per die, chosen so that decent hands succeed at '
          'ordinary deeds often enough to keep stories moving, and any deeper '
          'reading decorates a design decision. <span class="voice">Others '
          'say</span> the default is the system&rsquo;s anthropology: the wall of '
          'six says the world resists everything a little &mdash; even the easy '
          'deed can fail, even the desperate one can land &mdash; and a game '
          'about consensual reality chose, for its baseline, a universe that is '
          'neither hostile nor kind but merely <span '
          'class="aside">unconvinced</span>. The bystander of 533a, these readers '
          'note, is difficulty six wearing a face. The first school builds '
          'better houses; the second gives better sermons; and the system, '
          'characteristically, supports both without settling either. A third '
          'school reads the six through the ten: the perfect die that always '
          'lands, whatever the wall, is the system&rsquo;s one unconditional '
          'grace, and its pairing with the one &mdash; which the next folio '
          'sharpens into a knife &mdash; makes every roll a small morality play, '
          'hubris and mercy printed on opposite faces of the same die.</p>\n'
          '        <p><span class="lemma">Who moved it across the '
          'recensions.</span> The girsa fight, as the brief promised. The '
          'manuscripts diverge famously here: one era moves the wall itself, '
          'task by task; another anchors walls and scales the successes '
          'demanded; the counting of tens, the pricing of specialties, the '
          'threshold of the trivial &mdash; each recension redraws some line, '
          'and every long-running table plays a private blend it half-remembers '
          'assembling. <span class="voice">Some say</span> the drift is decay: '
          'a resolution system should be load-bearing and boring, and thirty '
          'years of adjustment betray a mechanism never quite sound. <span '
          'class="voice">Others say</span> the drift is the hobby breathing '
          '&mdash; each era&rsquo;s blend fits its era&rsquo;s play, the blends '
          'are variant manuscripts in the tractate&rsquo;s full sense, and the '
          'table&rsquo;s half-remembered assembly is, quietly, every '
          'tradition&rsquo;s origin story told in miniature. The tractate keeps '
          'the variants without harmonizing, per its standing law, and notes '
          'only that the system&rsquo;s spine &mdash; hand, wall, count &mdash; '
          'has never moved, which is the part that was load-bearing all '
          'along.</p>\n'
          '        <p><span class="lemma">When nobody is watching.</span> The '
          'metaphysical tease, briefly, because the table deserves it: do the '
          'dice model the world&rsquo;s uncertainty or create it? <span '
          'class="voice">Some say</span> model &mdash; the fiction&rsquo;s '
          'events are what they are, and dice approximate the unknowns honestly. '
          '<span class="voice">Others say</span> create: nothing in the fiction '
          'exists until the roll resolves it, the unrolled world is genuinely '
          'indeterminate, and the game is therefore a small Consensus running '
          'on a kitchen table &mdash; folio 62&rsquo;s cosmology, '
          'played out nightly with snacks. The dispute is unfalsifiable and '
          'delightful, which in this tractate is a genre, and the reader is '
          'reminded that the folio of witnesses already ruled on who the dice '
          'are: the only Sleepers at the table, agreeing on reality one roll '
          'at a time &mdash; and that no Sleeper, and no die, has ever been '
          'argued out of a verdict already rendered. <span '
          'class="kw">TEYKU</span> &mdash; let it ride.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the six, the drift, and the kitchen '
               'Consensus</span>',
 'rubric': 'hand, wall, and count',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'continued &middot; of the dice &middot; the pool and the wall as law',
 'title': 'Tractate Aliyah · Folio 385a — The Dice: hand, wall, and count',
 'type': 'daf'}
