# Folio 393a - The Rule of One. Facts per the wod-llm-wiki dice-pools page
# (M20 pp.392-393).
FOLIO = {'bottom': '<p><span class="lemma">On narrating the botch.</span> The botch is the '
           'system&rsquo;s one guaranteed plot delivery, and it deserves better than '
           'slapstick: the catastrophic failure should flow from the deed attempted '
           '&mdash; the lock that jams with the pick inside it, the incantation that '
           'reaches the wrong listener &mdash; and it should change the situation, not '
           'merely embarrass the actor. The books&rsquo; own standard is the '
           'measure: worse off than before, memorably, without death by paperwork. '
           'A table&rsquo;s botch stories are its folklore; author them like '
           'folklore.</p>\n'
           '        <p><span class="lemma">On the high wall&rsquo;s shadow.</span> The '
           'arithmetic the Mishnah teaches has a table-side corollary: every point of '
           'difficulty added is botch risk added, because the success-bearing faces '
           'thin while the ones stay constant. The Storyteller who raises walls '
           'casually is not merely making deeds harder; she is seeding catastrophes, '
           'and should raise walls the way this chapter raises everything &mdash; '
           'declared, sparingly, and on purpose.</p>\n'
           '        <p><span class="lemma">On mercy&rsquo;s bounds.</span> The '
           'law&rsquo;s own limit &mdash; no death by random chance, real cost '
           'nonetheless &mdash; is the adjudication corridor. The botch waved off '
           'teaches the table that ones are noise; the botch that kills teaches the '
           'table to stop attempting anything; and the corridor between is where the '
           'form lives: consequence with a future in it. The magick botch&rsquo;s '
           'special weight belongs overleaf, and the Storyteller should read both '
           'sides before the first Arete roll comes up snake-eyed.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on authored catastrophe, '
                'seeded walls, and the corridor</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Every one erases a success.</span> The die that '
           'shows its lowest face is not a blank but a debt: each one rolled cancels '
           'one success from the count, and a hand whose successes are all eaten '
           'fails, ending where it began.<sup>a</sup> But the hand that shows no '
           'success at all and at least one one has done worse than fail: it has '
           '<span class="term">botched</span>, and the botch is an event, not an '
           'absence &mdash; the deed miscarries in a way that leaves the doer worse '
           'than she started, and the wreckage is the Storyteller&rsquo;s to '
           'shape.<sup>b</sup> The botch scales: one one stings, and the triple botch '
           'is spoken of in the books with respect, for impressive failures merit '
           'impressive consequences.<sup>c</sup> Two bounds govern the shaping. '
           'Chance alone does not kill: the botch may maim a plan, a reputation, a '
           'body&rsquo;s ease, but the death of a character is not dealt by dice '
           'alone. And the botch is never nothing: the table that shrugs it off has '
           'repealed the clause, and with it the reason anyone fears a desperate '
           'roll.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence a '
           'tenth face that works against the roller? Come and hear the '
           'chapter&rsquo;s own cosmology, offered half in earnest as this chapter '
           'offers everything: the pool is ambition quantified, and the world taxes '
           'ambition &mdash; one face in ten reserved for entropy&rsquo;s comment, '
           'the same tithe every gambler pays and every engineer allows for. Note '
           'the arithmetic&rsquo;s malice: the tax bites hardest at the highest '
           'walls, where successes are scarce and the ones stand out &mdash; the '
           'desperate deed is not only harder but more dangerous, and the system '
           'has thereby written tragedy&rsquo;s oldest rule into its dice: '
           'reaching past your grasp is exactly when the fall is worst. One '
           'recension of a sibling tractate even deals mercy in paper: a card per '
           'session, its werewolves rule, to demote a single botch to a plain '
           'failure when the whole pack&rsquo;s night has curdled &mdash; a '
           'kindness this tractate files as girsa, not law, noting that even the '
           'kindest recension would not delete the tenth face, only ransom it. The '
           'disputants around this text hold the girsa the recensions never '
           'settled &mdash; what the ones cancel, and when &mdash; and the deeper '
           'question of whom the tenth face is working for.</p>',
 'chapter': 'Chapter the Ninth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'entropy&rsquo;s comment on the working mage waits overleaf.',
 'folio': '393A',
 'glossL': '<p><span class="mark">a</span> On the Rule of One &mdash; each one '
           'cancelling a success &mdash; see M20, the systems chapter, folios '
           '392&ndash;393, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the botch as catastrophic '
           'failure leaving the character worse off, see the same pages.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the triple botch '
           'and impressively terrible results, see the same; the respect is the '
           'text&rsquo;s.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the bound '
           'against death by flat chance, see the same pages&rsquo; counsel; the '
           'corridor between mercy and teeth is the Later Authorities&rsquo; '
           'below.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The tithe&rsquo;s collector has a '
           'folio: Entropy, 514a, whose first rank reads the currents these ones '
           'ride, and whose gloss promised that the botch it tithes would be tried '
           'here. Promise kept; the Sphere&rsquo;s masters, note well, predict '
           'dice for a living.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'magick botch&rsquo;s special weight &mdash; the backlash bridge to '
           '533a &mdash; is the verso&rsquo;s whole subject; this side keeps the '
           'mundane wreckage.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'extended deed&rsquo;s botch collapses all gathered successes, folio '
           '385b, which is why ritual mages fear this folio more than any '
           'soldier does; the candle burns, and every interval is another '
           'audience with the tenth face.</p>',
 'h1': 'The Rule of One',
 'hagahah': 'The universe reserves one face in ten for its own comment. The comment '
            'is usually brief, always timely, and never flattering &mdash; and the '
            'players who curse it loudest are the ones who would not play a world '
            'without it, which the universe, presumably, has also noticed.',
 'inner': '<p><span class="lemma">Not a blank but a debt.</span> The '
          'cancellation&rsquo;s plain sense: ones are counted against successes '
          'before the result is read, so the roll&rsquo;s outcome is a net figure '
          '&mdash; a hand of three successes and two ones lands one, barely. The '
          'clause makes big pools honest: more dice mean more successes and more '
          'exposure to the tenth face together, and the master&rsquo;s huge '
          'handful is powerful but never safe, which the system clearly '
          'intends.</p>\n'
          '        <p><span class="lemma">Shows no success at all.</span> The '
          'trigger&rsquo;s plain sense, drawn fine because the stakes are: the '
          'botch requires the empty hand &mdash; no die over the wall anywhere '
          '&mdash; plus the tenth face&rsquo;s signature. A success scored and '
          'then eaten leaves a plain failure: the ones spent themselves on the '
          'cancellation, and the catastrophe never assembles. The sibling '
          'manuscripts state the clause in so many words, and this tractate '
          'reads its own text the same way: the botch is not bad luck '
          'compounded but ambition wholly unanswered, met by comment.</p>\n'
          '        <p><span class="lemma">Worse than she started.</span> The '
          'standard&rsquo;s plain sense: the botch&rsquo;s floor is the status '
          'quo ante, lost &mdash; not mere failure to gain but a step backward '
          'the scene can feel. The measure keeps the form honest in both '
          'directions: a botch that leaves the situation unchanged is a failure '
          'misfiled, and one that ends the story is the mercy bound breached; '
          'between them runs the corridor the Later Authorities pace '
          'below.</p>\n'
          '        <p><span class="lemma">An event, not an absence.</span> The '
          'botch&rsquo;s plain sense, and the clause the whole folio guards: '
          'failure means the deed did not happen; the botch means something else '
          'happened. The distinction is narrative jurisdiction &mdash; failure '
          'returns the scene to the players, the botch hands it to the '
          'Storyteller with a mandate &mdash; and the mandate&rsquo;s terms are '
          'the Mishnah&rsquo;s two bounds, mercy and teeth, held together.</p>\n'
          '        <p><span class="lemma">The botch scales.</span> Severity&rsquo;s '
          'plain sense: the count of uncancelled ones is the catastrophe&rsquo;s '
          'budget &mdash; one buys a setback, two a disaster, three the story the '
          'table tells for years. The scaling is judged, not tabulated, in the '
          'modern manuscripts; older recensions kept charts, and the tables that '
          'miss them keep house charts still, a girsa the disputants file '
          'without prejudice.</p>\n'
          '        <p><span class="lemma">Chance alone does not kill.</span> The '
          'mercy bound&rsquo;s plain sense: death is a story decision, and the '
          'dice may demand the decision be faced but not make it themselves '
          '&mdash; the triple botch on the cliff face leaves the climber hanging '
          'by a failing rope, and what happens next is played, not read off the '
          'die. The bound protects the game&rsquo;s stakes as much as its '
          'characters: a world where ones execute is a world where nobody '
          'climbs, and the genre needs its climbers.</p>\n'
          '        <p><span class="lemma">Never nothing.</span> The teeth '
          'bound&rsquo;s plain sense, stated as bluntly as the mercy&rsquo;s: '
          'the botch shrugged off unravels the whole chapter &mdash; without the '
          'tenth face&rsquo;s threat, high walls are merely slow, desperation '
          'is merely tedious, and the drama clause of 385a loses its floor. The '
          'clause is small and load-bearing, like most floors, and the '
          'Storyteller who honors it buys every future roll its full '
          'weight.</p>',
 'inner_head': 'On the Tenth Face<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; debts, events, and bounds</span>',
 'name': 'The Rule of One',
 'outer': '<p><span class="lemma">What the ones cancel, and when.</span> The girsa '
          'fight, the chapter&rsquo;s oldest. The manuscripts diverge at the '
          'seams: whether ones cancel any success or only the unmodified kind; '
          'whether the perfect ten, in eras where it counts double, can be eaten '
          'whole or only by half; whether a hand of one die showing one botches '
          'absolutely or merely fails; whether the purchased Willpower success '
          'stands above cancellation &mdash; each recension rules some subset and '
          'is silent on the rest, and thirty years of tables have filled the '
          'silences each in their own hand. <span class="voice">Some say</span> '
          'the divergence is a defect the drafters never repaired: a rule this '
          'central should have one text. <span class="voice">Others say</span> '
          'the silences are load-bearing: each table&rsquo;s fills tune the '
          'game&rsquo;s cruelty to the table&rsquo;s taste, the drafters left '
          'the dials unlabeled on purpose, and the proof is that no two '
          'long-running chronicles play the same game and all of them play '
          'this one. The tractate files the variants unharmonized, per its '
          'law, and notes the pattern it has seen nine times now: where the '
          'text goes quiet, the tradition speaks, and calls itself the '
          'text.</p>\n'
          '        <p><span class="lemma">Whom the tenth face is working '
          'for.</span> The theology, pressed. <span class="voice">Some '
          'say</span> nobody: the one is a uniform random outcome, the '
          '&ldquo;tithe&rdquo; is a poet&rsquo;s gloss on arithmetic, and the '
          'chapter&rsquo;s cosmology is charming exactly as far as it stays in '
          'the hagahah where it belongs. <span class="voice">Others say</span> '
          'the game&rsquo;s own setting refuses the shrug: in a world where '
          'entropy is a Sphere, probability has currents, and a Tradition&rsquo;s '
          'masters read tells in falling dice, the tenth face is '
          'in-fiction weather &mdash; the botch is the Wheel&rsquo;s small '
          'tax collected at the table&rsquo;s scale, and the player who '
          'believes the dice punish hubris, the recto&rsquo;s hagahah&rsquo;s '
          'player, is playing the setting with unusual fidelity. The first '
          'school keeps the wall between game and fiction; the second has '
          'noticed the wall is exactly what this game is about; and the '
          'tractate, which lives on that wall, declines the vote it most '
          'wants to cast &mdash; noting only, for the record, that the Sphere '
          'which reads probability&rsquo;s currents charges its first rank '
          'nothing to watch the dice fall, and that its masters are not known '
          'to gamble.</p>\n'
          '        <p><span class="lemma">Tragedy&rsquo;s oldest rule.</span> A '
          'last difficulty, structural: is the high-wall botch curve design or '
          'accident? <span class="voice">Some say</span> accident '
          'immortalized: the curve falls out of the arithmetic, the drafters '
          'inherited it, and the tragic reading is retrofit. <span '
          'class="voice">Others say</span> the retrofit is thirty years '
          'ratified: every recension kept the curve when any could have '
          'flattened it, the books&rsquo; own examples lean into the desperate '
          'roll&rsquo;s danger, and a system that punishes overreach '
          'proportionally to the reach has earned its reading whether or not '
          'it was born with it. Design or accident, the table lives under the '
          'curve either way &mdash; and the tractate observes that this is '
          'also the setting&rsquo;s position on the Consensus, which is '
          'either the folio&rsquo;s best joke or its thesis. <span '
          'class="kw">TEYKU</span> &mdash; let the tenth face keep its own '
          'counsel.</p>',
 'outer_head': 'The Assessors<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the girsa, the theology, and the '
               'curve</span>',
 'rubric': 'the tenth face, and its tithe',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'continued &middot; of the Rule of One &middot; the botch as law',
 'title': 'Tractate Aliyah · Folio 393a — The Rule of One: the tenth face, and its tithe',
 'type': 'daf'}
