# Folio 393b - The Comment. Verso of the Rule of One: the magick botch and
# the bridge to 533a's backlash, per the wod-llm-wiki dice-pools and
# magick pages.
FOLIO = {'bottom': '<p><span class="lemma">On the Arete botch as scene.</span> The working '
           'botched is the setting&rsquo;s signature disaster and should be staged with '
           'its full inheritance: the effect miscarried in the paradigm&rsquo;s own '
           'vocabulary &mdash; the ritual&rsquo;s circle inverted, the code compiling '
           'something else, the prayer answered by the wrong department &mdash; and '
           'the Paradox arriving as 533a provides, immediate or pooled. Resist the '
           'generic explosion; the botch that speaks the mage&rsquo;s own symbolic '
           'language teaches the table her paradigm better than any lore dump, and '
           'frightens her player more.</p>\n'
           '        <p><span class="lemma">On the ritual&rsquo;s long '
           'exposure.</span> The extended casting multiplies audiences with the '
           'tenth face &mdash; every interval is a fresh roll, and the botch at hour '
           'five collapses the night&rsquo;s gathered successes with the backlash '
           'scaled to everything already invested. Say so before the ritual starts; '
           'let the players feel each interval as the wager it is; and when the '
           'collapse comes, spend it as the set-piece the odds have been '
           'purchasing all evening.</p>\n'
           '        <p><span class="lemma">On authorship at the table.</span> The '
           'botch&rsquo;s narration is the Storyteller&rsquo;s by law, but the '
           'wisest tables borrow the victim&rsquo;s voice: ask the mage&rsquo;s '
           'player what going wrong looks like in her paradigm, then make it worse '
           'than she offered. The player&rsquo;s contribution buys investment; the '
           'Storyteller&rsquo;s escalation keeps the teeth; and the resulting '
           'catastrophe belongs to the whole table, which is where the '
           'chapter&rsquo;s law has been sending everything all along.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on paradigm-fluent '
                'disaster, long wagers, and borrowed voices</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The working botched is a working still.</span> '
           'When the dice of Arete come up ones and empty, the magick does not '
           'fizzle &mdash; it miscarries: power raised, aimed, and delivered '
           'wrong, and the law of 533a attends the wreck as it attends every '
           'working.<sup>a</sup> The botched coincidental working stays a private '
           'grief where fortune allows; the botched vulgar working gathers its '
           'Paradox with a botch&rsquo;s interest, for the offense was attempted '
           'and the attempt has now also failed loudly.<sup>b</sup> The extended '
           'working multiplies the exposure: each interval&rsquo;s roll is its own '
           'audience with the tenth face, and the ritual&rsquo;s botch collapses '
           'all it gathered, the backlash proportioned to the '
           'investment.<sup>c</sup> And the botch&rsquo;s shape follows the '
           'paradigm: the working miscarries in its own symbolic tongue, and the '
           'Storyteller who authors the wreck authors it fluently or wastes '
           'it.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why '
           'does the mage&rsquo;s botch outweigh the locksmith&rsquo;s? Come and '
           'hear the chapter&rsquo;s arithmetic joined to the Book of '
           'Magick&rsquo;s: the locksmith&rsquo;s failed hand held a pick, and the '
           'mage&rsquo;s held the world. A working is ambition at the largest '
           'scale the system prices, so entropy&rsquo;s tithe on it is collected '
           'at the same scale &mdash; the tenth face&rsquo;s comment, addressed '
           'for once to someone who was asking the universe a direct question. '
           'And the chapter&rsquo;s earlier mercy holds here with special force: '
           'the will spent before the dice buys its one certain success, and the '
           'roll that holds a success cannot botch &mdash; so the prudent caster '
           'pays Willpower before the working that matters, not because she '
           'doubts her art but because one point of will is the cheapest '
           'insurance the Consensus sells, and the masters buy it by habit, '
           'which is how you can tell the masters. '
           'The recensions&rsquo; famous examples are all of this shape: the '
           'healer&rsquo;s botch that seals the poison in, the scryer&rsquo;s that '
           'shows the enemy her own eye, the ritualist&rsquo;s sixth hour '
           'undone by the seventh. The disputants around this text hold what '
           'remains: whether the botched working&rsquo;s backlash is 393&rsquo;s '
           'law or 533a&rsquo;s wearing a borrowed number, and who, in the '
           'moment of miscarriage, is actually speaking.</p>',
 'chapter': 'Chapter the Ninth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of the Rule of One: the recto keeps the tithe, this side keeps '
             'the comment addressed to mages.',
 'folio': '393B',
 'glossL': '<p><span class="mark">a</span> On magick&rsquo;s botches carrying '
           'special weight, see M20&rsquo;s systems chapter at the Rule of One '
           'and the casting procedures of the Book of Magick.</p>\n'
           '        <p><span class="mark">b</span> On the botched vulgar working '
           'and its Paradox, see 533a&rsquo;s law &mdash; a botch worsens every '
           'case, as that folio&rsquo;s Mishnah provides.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On extended '
           'rituals, their intervals, and the collapsing botch, see the ritual '
           'rules of M20&rsquo;s tenth chapter and folio 385b&rsquo;s extended '
           'form.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On miscarriage '
           'in the paradigm&rsquo;s tongue, see the focus material of the same '
           'chapter; the fluency counsel is the Later Authorities&rsquo;, '
           'drawn from the books&rsquo; own examples.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This verso is the bridge the '
           'briefs promised: 393&rsquo;s tenth face and 533a&rsquo;s backlash '
           'meet here, and the join is deliberately visible &mdash; the '
           'chapter of measures handing the Book of Magick its bill.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'Entropy masters of 514a, who predict dice, are conspicuously '
           'careful casters: the Sphere that reads the tenth face&rsquo;s '
           'currents treats this folio as weather forecasting, and their '
           'seat&rsquo;s watchers, 156b, treat a run of botches as a '
           'symptom worth naming.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'nullification clause of 520a stands over this page too: the '
           'master of Prime may unweave even the botch&rsquo;s backlash, at '
           'prices that folio&rsquo;s disputants have already priced in '
           'trust.</p>',
 'h1': 'The Comment',
 'hagahah': 'The universe&rsquo;s comment, addressed to a mage, is the only '
            'peer review the Consensus ever conducts in person. The '
            'Etherites of 160b, asked whether it counts as publication, '
            'ruled after long debate that it counts as a rejection letter '
            'with unusually good notes.',
 'inner': '<p><span class="lemma">A working still.</span> The plain sense that '
          'governs the verso: the botched casting is not a null result but a '
          'completed event &mdash; power moved, the world answered, the answer '
          'was no and then some. Hence the law&rsquo;s indifference to the '
          'mage&rsquo;s intent at the moment of wreck: what she meant stopped '
          'mattering when the dice spoke, and what she <span '
          'class="aside">did</span> is what the scene now contains, which is '
          'the recto&rsquo;s event-not-absence clause wearing robes.</p>\n'
          '        <p><span class="lemma">The dice of Arete.</span> The '
          'hand&rsquo;s plain sense, and the verso&rsquo;s quiet scandal: the '
          'casting pool is the mage&rsquo;s enlightenment, not her training, and '
          'enlightenment comes in small numbers &mdash; a young mage rolls fewer '
          'dice to remake the world than to win a fistfight, and the four-dice '
          'floor that 385a calls a decent hand is a luxury most workings never '
          'see. Every Arete roll therefore lives in the tenth face&rsquo;s '
          'neighborhood, and the system means it to: the thin hand is the price '
          'of asking direct questions, and the chapter&rsquo;s whole tragedy '
          'curve is compressed, for mages, into every single roll.</p>\n'
          '        <p><span class="lemma">As it attends every working.</span> '
          'The continuity clause, plainly: the botch suspends none of '
          '533a&rsquo;s ordinary law &mdash; vulgarity is judged as cast, '
          'witnesses are counted as present, and the court&rsquo;s fee is '
          'assessed on the working attempted before the interest is added. The '
          'clause forecloses a table error the drafters evidently met: the '
          'botch is not a separate crime with a separate court but the same '
          'working gone wrong before the same judge, and the mage who argues '
          'her miscarried magick was no magick at all is arguing against the '
          'first lemma of this page.</p>\n'
          '        <p><span class="lemma">With a botch&rsquo;s interest.</span> '
          'The vulgar botch&rsquo;s plain sense, restating 533a&rsquo;s own '
          'clause from this chapter&rsquo;s side: the vulgar working gathers '
          'Paradox succeed or fail, and the botch worsens every case &mdash; '
          'the offense compounded by the fumble, the court&rsquo;s attention '
          'drawn by the noise. The coincidental botch&rsquo;s privacy is '
          'correspondingly conditional: fortune allowed the working to pass as '
          'the world&rsquo;s own doing, and a spectacular miscarriage can '
          'revoke the cover mid-scene, converting the private grief to a '
          'public one with witnesses counted per 533b.</p>\n'
          '        <p><span class="lemma">Proportioned to the '
          'investment.</span> The ritual clause&rsquo;s plain sense: the '
          'collapse spends everything gathered &mdash; hours, successes, '
          'quintessence staged, and the backlash scales to the working '
          'attempted, not the interval fumbled. The arithmetic is the '
          'recto&rsquo;s tragedy curve at its steepest: the greatest workings '
          'demand the most intervals, each interval risks the face, and the '
          'masters&rsquo; famous caution before great rites is this clause '
          'internalized as temperament.</p>\n'
          '        <p><span class="lemma">In its own symbolic tongue.</span> '
          'The fluency clause&rsquo;s plain sense: magick miscarries along the '
          'channels it was cast through &mdash; the instrument turns, the '
          'practice inverts, the paradigm&rsquo;s metaphor literalizes wrong '
          '&mdash; because the working never stopped being made of those '
          'things. The clause is mechanically toothless and narratively '
          'load-bearing, the chapter&rsquo;s recurring proportion, and the '
          'Later Authorities&rsquo; counsel opposite is its whole '
          'application.</p>',
 'inner_head': 'On the Wreck<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; miscarriage, interest, and '
               'fluency</span>',
 'name': 'The Comment',
 'outer': '<p><span class="lemma">Whose law is the backlash.</span> The '
          'jurisdiction dispute, the verso&rsquo;s spine. <span '
          'class="voice">Some say</span> 533a&rsquo;s entirely: Paradox is the '
          'world&rsquo;s answer to offense, the botch merely enlarges the '
          'offense, and this folio is a footnote to that one &mdash; the '
          'measures chapter does not own the court, it only rolls the dice '
          'that summon it. <span class="voice">Others say</span> the '
          'traffic runs both ways and the join is realer than a footnote: the '
          'botch exists in every deed, mundane or worked, so the backlash is '
          'the general law of the tenth face expressed at magick&rsquo;s '
          'scale &mdash; Paradox is what a botch <span class="aside">is'
          '</span> when the deed was a working, and 533a&rsquo;s whole '
          'court is this chapter&rsquo;s arithmetic given an institution. '
          'The dispute is the tractate arguing about its own binding order, '
          'which the Masoret finds fitting: the chapter of measures and the '
          'Book of Magick each claim the other as appendix, and the reader '
          'who has followed the cross-references knows the truth is a '
          'circle, as it usually is in this binding.</p>\n'
          '        <p><span class="lemma">Who is actually speaking.</span> '
          'The voice dispute, inherited from the recto and sharpened: when '
          'the working miscarries, is the wreck the world&rsquo;s comment or '
          'the mage&rsquo;s own? <span class="voice">Some say</span> the '
          'world&rsquo;s: the Consensus answers the failed assertion as it '
          'answers the successful one, with resistance, and the botch is '
          'that resistance arriving through the breach the mage herself '
          'opened. <span class="voice">Others say</span> listen closer to '
          'the famous examples: the healer&rsquo;s botch seals the poison '
          '<span class="aside">in</span>, the scryer&rsquo;s shows the enemy '
          '<span class="aside">her</span> eye &mdash; the wrecks are too '
          'fluent in each mage&rsquo;s fears to be the world&rsquo;s generic '
          'no. On this reading the botch is the mage&rsquo;s own Avatar, or '
          'her doubt, or the unswept corners of her paradigm speaking with '
          'her own borrowed power &mdash; and folio 43 is '
          'reserved the question of whether those are three names for one '
          'speaker. The first school comforts; the second explains too '
          'much, which in this tractate is the mark of a reading that '
          'will not go away.</p>\n'
          '        <p><span class="lemma">A rejection letter with good '
          'notes.</span> The hagahah&rsquo;s joke, taken up because the '
          'chapter&rsquo;s law hides in it: is the botch informative? <span '
          'class="voice">Some say</span> no doctrine should be built on '
          'wreckage &mdash; the botch is noise, and mages who read their '
          'disasters for guidance end in the Quiet of folio 554, '
          'where all noise is signal. <span class="voice">Others say</span> '
          'the setting&rsquo;s own pedagogy disagrees: every Tradition&rsquo;s '
          'training stories turn on instructive catastrophe, the '
          'Etherites&rsquo; entire method survives on honored explosions, '
          'and a universe that comments &mdash; even cruelly, even once in '
          'ten &mdash; is a universe in conversation, which is more than '
          'the Sleepers&rsquo; universe admits to. The line between reading '
          'one&rsquo;s botches and being read by them is thin, patrolled, '
          'and folio 554&rsquo;s to draw; this folio only marks where it '
          'begins. <span class="kw">TEYKU</span> &mdash; and may the '
          'reader never roll it.</p>',
 'outer_head': 'The Reviewers<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the jurisdiction, the voice, and the '
               'notes</span>',
 'rubric': 'the botched working, and who speaks through it',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'continued &middot; of the comment &middot; the magick botch as law',
 'title': 'Tractate Aliyah · Folio 393b — The Comment: the botched working',
 'type': 'daf'}
