# Folio 406a - Health. Facts per the wod-llm-wiki health page
# (M20 pp.334, 406).
FOLIO = {'bottom': '<p><span class="lemma">On pacing injury.</span> The track is the '
           'chronicle&rsquo;s tempo written on the character sheet: the descent from '
           'Bruised to Crippled should feel like a story tightening, each level&rsquo;s '
           'penalty a change the table can hear in the player&rsquo;s choices. Narrate '
           'the levels as conditions, not numbers &mdash; the limp, the breath that '
           'catches, the hands that will not steady &mdash; and the mechanics do the '
           'horror unassisted; the mage&rsquo;s fragility is the genre&rsquo;s, and the '
           'books built it on purpose.</p>\n'
           '        <p><span class="lemma">On the fade to black.</span> Incapacitated is '
           'a door, not a destination: the fight ends, and what follows &mdash; capture, '
           'rescue, the long convalescence of the verso&rsquo;s tables &mdash; is scene '
           'framing, chosen with 384b&rsquo;s contract in reach. Fading past the '
           'gruesome is not softness but aim; the genre&rsquo;s horror lives in '
           'consequence, not anatomy, and the track&rsquo;s bottom rows deliver more '
           'dread implied than described. Reserve the on-screen worst for the moments '
           'the story has earned it, per the lines and veils already posted.</p>\n'
           '        <p><span class="lemma">On the caster at the bottom.</span> The '
           'exemption clause &mdash; penalties sparing Arete, soak, and Avatar &mdash; '
           'is the setting&rsquo;s signature image and should be staged as such: the '
           'mage broken on the floor who is nonetheless not finished, will burning '
           'where the body has quit. The image has its own bound: at Incapacitated '
           'the body sleeps, and only the will&rsquo;s own payment &mdash; folio '
           '328&rsquo;s price, wanting &mdash; holds the caster conscious to use '
           'what the exemption preserves. Enforce the exemption exactly; it is what makes '
           'mage horror different from mortal horror, and the scene where the players '
           'realize the dying enemy magus can still speak a working is the folio '
           'earning its place in the binding.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on tempo, the fade, and the '
                'will at the bottom of the track</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The body keeps a ledger of seven lines,</span> and an '
           'eighth that closes it. From Bruised the track descends through Hurt and '
           'Injured, Wounded and Mauled, to Crippled, to Incapacitated &mdash; and past '
           'the last line is death, the ledger closed and the soul passed beyond '
           'the chart&rsquo;s jurisdiction.<sup>a</sup> Each line exacts its toll as the mage descends: the '
           'bruise costs nothing; the hurt and the injured lose one die; the wounded '
           'and the mauled, two; the crippled, five &mdash; and the body slows with '
           'the dice, from full stride to half, to the walk, to the hobble, to the '
           'crawl, to stillness.<sup>b</sup> Damage is marked on the ledger by its '
           'kind, for the kinds heal differently and kill differently, as the verso '
           'provides.<sup>c</sup> And one exemption governs the whole descent: the '
           'wound&rsquo;s penalty never touches the soak of the body, the roll of '
           'Arete, or the Avatar&rsquo;s work &mdash; the flesh fails by degrees, and '
           'the will does not.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear an injury walked down the track. A mage takes a beating in an alley: '
           'bruised, then hurt &mdash; one die gone, her hands still sure enough. The '
           'second exchange leaves her injured, half her stride lost with the second '
           'die; wounded, and she cannot run from what is coming; mauled, and she '
           'hobbles three paces a turn while it comes anyway. Crippled, five dice '
           'torn from every hand she has &mdash; and here the exemption speaks: her '
           'body crawls, her locks and lies and ladders are all but gone, and her '
           'Arete rolls whole, will undimmed in the wreck of its house. What she '
           'casts from the ground is her business and 533a&rsquo;s; that she can '
           'cast at all is this folio&rsquo;s point, and the books&rsquo; own: the '
           'harm a war-form shrugs away will bury a willworker, and the mage '
           'was never dangerous because of her body. And note the ledger&rsquo;s '
           'democracy: seven lines for everyone &mdash; the archmage and the '
           'alley&rsquo;s other party keep identical charts, and no dot of any '
           'Trait adds an eighth. What varies is everything around the chart: '
           'what can be soaked, what can be healed, who is holding the will when '
           'the body gives out. The disputants around this '
           'text hold the ledger&rsquo;s design: why seven lines, why these '
           'penalties, and why the fragility is the game.</p>',
 'chapter': 'Chapter the Ninth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the kinds '
             'of harm and their healing wait overleaf, and Middot closes with '
             'them.',
 'folio': '406A',
 'glossL': '<p><span class="mark">a</span> On the Health track&rsquo;s seven levels '
           'and the death past them, see M20, the systems chapter, folio 406, '
           'whence this page takes its number; the chart&rsquo;s entry for the '
           'last line is a single gentle sentence, cited here and left in the '
           'book.</p>\n'
           '        <p><span class="mark">b</span> On the penalties and the '
           'slowing stride, see the chart at folios 334 and 406 of the same '
           'book.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On marking damage '
           'by kind, see the same pages; the kinds themselves are the '
           'verso&rsquo;s law.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the exemption '
           'of soak, Arete, and Avatar from wound penalties, see folio 406; the '
           'clause is small in the text and large in the game.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The mage&rsquo;s fragility is '
           'the setting&rsquo;s oldest design confession: the werewolf who '
           'laughs off her wounds has a tractate of his own on the shelf, '
           'Acharit, and the difference in their ledgers is the difference in '
           'their genres &mdash; his is a war story, hers is a horror story '
           'that contains wars.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'healing this track begs for is 516b&rsquo;s law &mdash; once a '
           'scene, aggravated always vulgar &mdash; and the two folios should '
           'be read stacked: the track is the problem, the healer&rsquo;s '
           'ladder the rationed answer.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'penalties this folio exacts are the internal modifiers of 385a '
           '&mdash; dice from the hand, not height on the wall &mdash; and '
           'the distinction earns its keep here: the world did not get '
           'harder when the mage was hurt; she got smaller, which is '
           'worse.</p>',
 'h1': 'Health',
 'hagahah': 'The track ends in a word processors soften and mages do not. The '
            'books write Dead, plainly, at the bottom of every character sheet '
            '&mdash; the one Trait every character holds at the same rating, '
            'the setting&rsquo;s quietest memento mori, printed under the '
            'dots.',
 'inner': '<p><span class="lemma">A ledger of seven lines.</span> The '
          'track&rsquo;s plain sense: health is not a pool but a position '
          '&mdash; the character stands at a line, and damage moves her down '
          'it, each line a qualitative state with its own truths. The design '
          'rejects the bag-of-points model on purpose: there is no such thing '
          'as being eighty percent fine, and the second wound matters '
          'differently than the first because it lands on a different '
          'body.</p>\n'
          '        <p><span class="lemma">Marked by its kind.</span> The '
          'notation&rsquo;s plain sense: the slash for the bruising blow, the '
          'cross for the cutting one, the star for the harm that unmakes &mdash; '
          'three marks, one ledger, and the ledger thereby keeps history as '
          'well as position: a glance at the sheet says not only how hurt but '
          'how, which the verso&rsquo;s healing law will read like a physician '
          'reads a chart. The kinds are the verso&rsquo;s whole subject; the '
          'recto needs only their marks, and the rule that no line holds more '
          'than one.</p>\n'
          '        <p><span class="lemma">The bruise costs nothing.</span> The '
          'first line&rsquo;s plain sense, and its mercy read correctly: '
          'Bruised takes no dice because it is the warning shot &mdash; the '
          'system&rsquo;s way of landing a hit that changes nothing but the '
          'sheet, so the table feels contact before contact costs. The grace '
          'is single: every line below it taxes, and the player who treats '
          'the free line as armor has misread a countdown as a cushion.</p>\n'
          '        <p><span class="lemma">And an eighth that closes it.</span> '
          'The last line&rsquo;s plain sense: death is on the '
          'chart, named without euphemism, because the chart is honest about '
          'where it points. The line has no penalty to list; its listing is '
          'the penalty, and the book marks it with a sentence of unexpected '
          'gentleness &mdash; cited at the margin, left unquoted here &mdash; '
          'placed at the bottom of the hardest column.</p>\n'
          '        <p><span class="lemma">Each line exacts its toll.</span> The '
          'penalty ladder&rsquo;s plain sense: the wound taxes the hand, per '
          '385a&rsquo;s division &mdash; internal circumstance, dice removed '
          '&mdash; and the tax compounds the danger: the hurt mage rolls less, '
          'succeeds less, and descends faster, the track&rsquo;s own gravity. '
          'The cliff at Crippled &mdash; two dice to five &mdash; is the '
          'chart&rsquo;s deliberate horror: the second-to-last line is not a '
          'warning but a verdict mostly delivered.</p>\n'
          '        <p><span class="lemma">From full stride to the crawl.</span> '
          'The movement ladder&rsquo;s plain sense, and its tactical weight: '
          'the descending mage loses the ability to leave &mdash; half stride, '
          'the walk, three yards, one &mdash; and the track is therefore also '
          'a trap that closes in stages. Retreat is a health level&rsquo;s '
          'privilege; the chronicle&rsquo;s survivors learn to spend it two '
          'lines early, and the ones who learn it late are the Gemara&rsquo;s '
          'alley, replayed.</p>\n'
          '        <p><span class="lemma">The will does not.</span> The '
          'exemption&rsquo;s plain sense, and the folio&rsquo;s theology '
          'stated as mechanics: Arete, soak, and the Avatar&rsquo;s work roll '
          'whole at every line above death, because they were never faculties '
          'of the failing body &mdash; the will is not in the wreck, only '
          'housed there. An Incapacitated mage conscious enough to push '
          'through &mdash; the will&rsquo;s own folio, 328, wanting, prices '
          'the push &mdash; can still work; the flesh&rsquo;s collapse '
          'silences the locksmith and never the magus; and every horror '
          'the setting builds on that sentence, it builds fairly, for the '
          'players hold the same clause.</p>',
 'inner_head': 'On the Track<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; lines, tolls, and the exemption</span>',
 'name': 'Health',
 'outer': '<p><span class="lemma">Why seven lines.</span> The design dispute. '
          '<span class="voice">Some say</span> ergonomics again: seven levels '
          'is the span a pencil and a scene can track, the penalties grid '
          'to memorable pairs, and the chart is a play aid, not an anatomy. '
          '<span class="voice">Others say</span> the chart is the '
          'genre&rsquo;s skeleton: seven descending states, each named for '
          'what it takes &mdash; your ease, your speed, your exits, your '
          'competence, your consciousness &mdash; is a horror structure, the '
          'closing trap in table form, and the arithmetic serves the '
          'dread rather than the other way around. The schools converge, as '
          'this chapter&rsquo;s schools do, on identical play and opposite '
          'sermons; the tractate notes only that the chart has outlived '
          'every mechanic printed beside it, which is what skeletons '
          'do.</p>\n'
          '        <p><span class="lemma">The fragility is the game.</span> '
          'The design confession, pressed. <span class="voice">Some '
          'say</span> the mage&rsquo;s glass body is a balance patch wearing '
          'a theme&rsquo;s clothes: the will that bends reality had to cost '
          'something, and the designers taxed the flesh because the '
          'alternative was taxing the magick into tedium. <span '
          'class="voice">Others say</span> the tax is the theme: the '
          'setting&rsquo;s whole argument is that enlightenment does not '
          'armor you &mdash; the Awakened die of the same bullets as the '
          'Sleepers they would save, the body stays mortal while the will '
          'stays infinite, and the exemption clause is that argument '
          'compressed to a rules line. A mage, the books keep saying, is a '
          'person who noticed reality is negotiable &mdash; and the track '
          'is reality&rsquo;s counter-offer, unnegotiable, printed on '
          'every sheet. The first school balances encounters; the second '
          'writes the setting&rsquo;s epitaphs; both are using the chart '
          'correctly. A third reading splits the difference by pointing at the '
          'shelf: every tractate of the order keeps this same chart &mdash; the '
          'vampire descends it toward torpor rather than the Mystery, the '
          'werewolf regrows lines as fast as the world cuts them &mdash; and '
          'the constant chart with variable exits is the design actually '
          'speaking: flesh is one system, and what haunts it is many, and the '
          'mage&rsquo;s haunting is the only one that lives entirely in her '
          'will.</p>\n'
          '        <p><span class="lemma">Not finished.</span> The '
          'exemption&rsquo;s dispute, last because the chapter ends on it. '
          '<span class="voice">Some say</span> the unbroken will at the '
          'track&rsquo;s bottom is the game&rsquo;s noblest image and its '
          'mechanical proof: the setting means what it says about '
          'enlightenment, and the dying mage who works one more wonder is '
          'Middot&rsquo;s whole chapter vindicated &mdash; the measures '
          'measure everything but the thing that matters. <span '
          'class="voice">Others say</span> look at what the image '
          'licenses: a genre where the broken body keeps fighting is a '
          'genre that romances attrition, and the exemption&rsquo;s dark '
          'twin is the interrogation scene it underwrites &mdash; the '
          'setting&rsquo;s villains also cast from the floor, and also '
          'never stop &mdash; and the Storyteller owes the table the symmetry '
          'declared, for a clause that only villains remember is not a rule '
          'but an ambush. The clause cuts both ways because it was drafted '
          'to; the contract of 384b holds the scenes it makes possible; '
          'and the chapter of measures closes, fittingly, on the one '
          'measure it declines to take. <span class="kw">TEYKU</span> '
          '&mdash; the will&rsquo;s depth is not on the chart.</p>',
 'outer_head': 'The Examiners<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the chart, the glass body, and the '
               'unmeasured will</span>',
 'rubric': 'the seven lines, and the will beneath them',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'concluded &middot; of health &middot; the track as law',
 'title': 'Tractate Aliyah · Folio 406a — Health: the seven lines, and the will beneath them',
 'type': 'daf'}
