# Folio 406b - The Wound. Verso of Health: the kinds of damage, soak, and
# healing times, per the wod-llm-wiki health page (M20 pp.406-409).
FOLIO = {'bottom': '<p><span class="lemma">On the calendar as consequence.</span> The healing '
           'tables are the chronicle&rsquo;s conscience: eleven days for three lethal '
           'levels, months for the deep wounds, the arithmetic cumulative and '
           'deliberately sobering. Run downtime honestly and injury becomes strategy '
           '&mdash; the cabal that picks fights it cannot afford learns in weeks of '
           'story time, and the Life adept&rsquo;s rationed mercies, 516b&rsquo;s, '
           'become the treasures the design intends. The table that hand-waves '
           'recovery has quietly deleted half the genre&rsquo;s pressure; do it '
           'knowingly or not at all.</p>\n'
           '        <p><span class="lemma">On the patch treadmill.</span> The optional '
           'field-medicine of the books &mdash; the medic&rsquo;s desperate roll that '
           'buys wounded levels back at mounting future cost &mdash; is a doom spiral '
           'sold as a lifeline, and it plays best when the table can see the spiral: '
           'each patch doubling the convalescence, the patched fighter rolling '
           'thinner, the Flaw waiting at the bottom. Use it in wars and long '
           'retreats, where its arithmetic tells the story of bodies spent faster '
           'than they mend; decline it in street games, where it merely launders '
           'the track.</p>\n'
           '        <p><span class="lemma">On the aggravated ruling.</span> Post the '
           'margins in session zero with the rest of 384b&rsquo;s constitution: what '
           'this chronicle counts as pattern-tearing &mdash; the books&rsquo; fire '
           'and fangs and radiation, plus whatever the table&rsquo;s antagonists '
           'bring &mdash; and who can soak it, which is nearly no one. The '
           'ruling decides every hard fight in advance, and the players deserve to '
           'know which enemies write in ink.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on calendars, spirals, and '
                'ink</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Harm has three kinds, and the ledger marks '
           'each.</span> The <span class="term">bashing</span> wound &mdash; fist, '
           'fall, club, the knockout&rsquo;s trauma &mdash; is the kind flesh '
           'answers: soaked by Stamina, healed in hours, and deadly only by '
           'accumulation, for the ledger overfilled converts the bruises to worse '
           'from the top down.<sup>a</sup> The <span class="term">lethal</span> '
           'wound &mdash; blade, bullet, poison, the long fall &mdash; the average '
           'body cannot soak and cannot shrug: untreated it worsens by the day '
           'until stabilized by a healer&rsquo;s craft, and past the last line it '
           'kills.<sup>b</sup> The <span class="term">aggravated</span> wound tears '
           'the pattern itself &mdash; fire, acid, radiation, the fangs and claws '
           'of the night&rsquo;s other tractates, and the arts of Life and Entropy '
           'at their harming ranks &mdash; unsoakable by ordinary flesh, marked '
           'apart, and healed by time and magick only.<sup>c</sup> Healing is '
           'priced by line and kind, the times cumulative: the bashing ledger '
           'clears in hours; the lethal and the torn climb from days through weeks '
           'to months, and the deep wounds are seasons &mdash; and a healer&rsquo;s '
           'attention is not a courtesy but a clause, for the untended body mends '
           'wrong or not at all.<sup>d</sup> And one wound needs no touch: the '
           'mind&rsquo;s assault deals the bruising kind unmarked, soaked by '
           'Willpower and not Stamina &mdash; torment without a scratch, priced '
           'in the first ink.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence '
           'three kinds and not one? Come and hear the ledger&rsquo;s theory of '
           'harm: the kinds are sorted not by pain but by what argues with the '
           'body&rsquo;s pattern. The bruise argues with nothing &mdash; the '
           'pattern absorbs it, hence Stamina&rsquo;s vote and the quick '
           'mending. The blade argues with the body&rsquo;s arrangement &mdash; '
           'the pattern must rebuild what was severed, hence the days and the '
           'doctor. And the fire argues with the pattern itself &mdash; the '
           'template scorched, not merely the copy &mdash; hence no soak, the '
           'separate mark, and the healing that needs magick, for only magick '
           'works at the depth the harm was done. The kinds are the '
           'Sphere folios&rsquo; jurisdictions read as wounds, which is why '
           'Life&rsquo;s harming rank and Entropy&rsquo;s write in the third '
           'ink. The disputants around this text hold the margins, where the '
           'sorting frays.</p>',
 'chapter': 'Chapter the Ninth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Health, and the close of Middot: the chapter of measures '
             'ends at the body&rsquo;s ledger, where measures end.',
 'folio': '406B',
 'glossL': '<p><span class="mark">a</span> On bashing harm, its soak, and the '
           'overfilled ledger&rsquo;s conversion, see M20, the systems chapter, '
           'folios 406&ndash;408.</p>\n'
           '        <p><span class="mark">b</span> On lethal harm, daily '
           'worsening, and stabilization by the healer&rsquo;s craft, see the '
           'same pages.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On aggravated '
           'harm &mdash; the pattern torn, the sources catalogued, the '
           'unsoakability &mdash; see the same; on Life 3 and Entropy 4 as its '
           'working sources, folios 516a and 514a of this binding.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the healing '
           'tables, their cumulative times, and the medic&rsquo;s optional '
           'field-patch with its doubling costs, see folios 408&ndash;409 of '
           'the same chapter.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The third ink is the '
           'seder&rsquo;s crossover currency: the fangs of Tractate Masekha and '
           'the claws of Tractate Acharit write aggravated in every line&rsquo;s '
           'books, and a crossover chronicle&rsquo;s first house ruling is '
           'usually this folio&rsquo;s margins.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'healer&rsquo;s answer to this whole page is 516b, rationed as that '
           'folio provides; the aggravated clause there &mdash; always vulgar, '
           'half-speed &mdash; is this folio&rsquo;s third ink read from the '
           'other side of the bed.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Middot '
           'closes here, and the Masoret takes the chapter&rsquo;s roll: the '
           'rule that outranks rules, the contract, the hand and the wall, the '
           'count, the tenth face, the comment, the track, the wound &mdash; '
           'eight dafs of measures, every one deferring at its edge to the '
           'table. The chapter taught what it could count and confessed what '
           'it could not, which is all a chapter of measures owes.</p>',
 'h1': 'The Wound',
 'hagahah': 'The ledger&rsquo;s three inks are the setting&rsquo;s taxonomy of '
            'enemies in disguise: what your foe writes in tells you what your '
            'foe is, before any lore roll &mdash; and the things that write in '
            'the third ink are, without exception, the things this seder keeps '
            'other tractates about.',
 'inner': '<p><span class="lemma">The kind flesh answers.</span> Bashing&rsquo;s '
          'plain sense: the body votes &mdash; Stamina soaks, the hours heal, '
          'and the brawl is survivable by design, which is why the genre can '
          'afford fistfights. The accumulation clause is the kind&rsquo;s '
          'hidden edge: the ledger overfilled converts downward, bruises '
          'becoming breaks, and the books say plainly that a body can be '
          'beaten to death &mdash; slowly, visibly, with every chance to '
          'stop, which is the clause&rsquo;s moral design as much as its '
          'arithmetic.</p>\n'
          '        <p><span class="lemma">Worsens by the day.</span> The lethal '
          'clock&rsquo;s plain sense: the untreated blade wound is not stable '
          '&mdash; below the shallow lines it deteriorates daily until a '
          'healer&rsquo;s craft stabilizes it, and the clock makes medicine a '
          'scene rather than a footnote. The clause carries the '
          'setting&rsquo;s quiet realism: the wounded do not walk it off, '
          'the cabal needs its medic or its Life adept, and the '
          'stabilization roll at a bad hour is Middot&rsquo;s whole '
          'machinery &mdash; hand, wall, tenth face &mdash; bent over a '
          'bleeding friend.</p>\n'
          '        <p><span class="lemma">Marked apart.</span> The third '
          'ink&rsquo;s plain sense: aggravated harm is tracked separately '
          'because it is ontologically separate &mdash; the pattern&rsquo;s '
          'template torn, beyond the body&rsquo;s own arguments, resistant '
          'even to magick&rsquo;s ordinary mercies. Nearly nothing soaks it; '
          'armor of the mundane kind does not apply; and the short list of '
          'what resists &mdash; the hardened substances, the warded flesh, '
          'Prime&rsquo;s second-rank workings per 520a &mdash; is short on '
          'purpose, for the ink exists to make some enemies matter.</p>\n'
          '        <p><span class="lemma">Soaked by Willpower and not '
          'Stamina.</span> The mind-wound&rsquo;s plain sense: the assault that '
          'arrives through the Mind arts bruises without touching, and the '
          'trait that answers it is will, for the target&rsquo;s body was '
          'never the battlefield. Such attacks run long and resisted, as the '
          'count&rsquo;s law provides, and the unAwakened fare worst against '
          'them &mdash; the sleeping mind has never had to hold its own shape '
          'before, and the specialists of several factions have built whole '
          'doctrines on that softness. The rare death by horror alone is the '
          'clause&rsquo;s dark corner: a weak will can be stopped like a '
          'heart.</p>\n'
          '        <p><span class="lemma">Healed by time and magick.</span> '
          'The monopoly&rsquo;s price list, plainly: the third ink yields to '
          'the calendar&rsquo;s slowest columns or to Life&rsquo;s third rank '
          'working vulgar, and the working pays as it heals &mdash; the torn '
          'template charges the healer line by line in quintessence, for the '
          'repair is done at the depth of the tear. The clause completes the '
          'ink&rsquo;s design: harm that costs the healer something real '
          'cannot be waved away, and the cabal&rsquo;s stock of essence '
          'becomes, in wars, a second health track kept in common.</p>\n'
          '        <p><span class="lemma">Not a courtesy but a clause.</span> '
          'The attention requirement&rsquo;s plain sense: the tables assume '
          'care &mdash; rest, treatment, the healer&rsquo;s periodic craft '
          '&mdash; and the body denied them mends crooked or not at all, the '
          'books&rsquo; own permanent-impairment warning. The clause makes '
          'convalescence a place in the story: the safehouse, the long '
          'quiet, the enemy&rsquo;s knowledge of where the wounded must be '
          '&mdash; and the genre&rsquo;s best sieges are built on it.</p>',
 'inner_head': 'On the Inks<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; kind by kind, clock by clock</span>',
 'name': 'The Wound',
 'outer': '<p><span class="lemma">Where the sorting frays.</span> The margins '
          'dispute, as the brief demands. The electrical burn is lethal in the '
          'books and fire is aggravated; the virulent toxin is third ink and '
          'the deadly poison second; the psychic assault bruises and the '
          'psychic surgery of 519a&rsquo;s fifth rank does what, exactly? '
          '<span class="voice">Some say</span> the margins prove the taxonomy '
          'arbitrary: three bins for a continuum of harm, sorted by the '
          'drafters&rsquo; dramatic instincts and defended after the fact '
          '&mdash; rule the edge cases fast and identically, and stop looking '
          'for the physics. <span class="voice">Others say</span> the '
          'Gemara&rsquo;s theory holds if held correctly: the test is never '
          'the source but the depth &mdash; does the harm argue with the '
          'copy or the template &mdash; and the same flame is lethal at the '
          'skin and aggravated in the pattern, which is why the books '
          'sort by trauma and not by element. The second school&rsquo;s test '
          'decides the psychic surgery question the first school ducks, and '
          'the tractate leans there while filing both, noting that every '
          'table&rsquo;s margin rulings drift toward the depth test given '
          'years, like water finding grade.</p>\n'
          '        <p><span class="lemma">Nearly nothing soaks it.</span> The '
          'soak girsa. The manuscripts drift here as everywhere: eras and '
          'options where the tough soak lethal, where armor eats the third '
          'ink, where the cinematic dial turns bullets to bruises &mdash; '
          'each a deliberate re-tuning of how much the world is allowed to '
          'hurt. <span class="voice">Some say</span> the dials are the '
          'design working: the same chassis runs the street horror and the '
          'pulp adventure, and the soak rules are the suspension. <span '
          'class="voice">Others say</span> the mage&rsquo;s chassis was '
          'tuned once, on purpose, to fragile &mdash; and every dial toward '
          'toughness is a genre transplant that the rest of the '
          'system quietly rejects, the fights lengthening, the dread '
          'thinning, the track&rsquo;s trap unsprung. The tractate files '
          'the variants per its law and adds its one empirical note: the '
          'chronicles the hobby remembers longest ran the glass '
          'settings, and the tables know why even when the players '
          'grumble, which they do, which is also the design '
          'working.</p>\n'
          '        <p><span class="lemma">Time and magick only.</span> The '
          'closing difficulty, where Middot hands off its last case. The '
          'third ink&rsquo;s healing monopoly makes the Life adept &mdash; '
          'and her rationed, always-vulgar mercy per 516b &mdash; the only '
          'door out of the setting&rsquo;s worst wounds, and the monopoly '
          'has a politics: whoever holds the healer holds the wounded. '
          '<span class="voice">Some say</span> this is the genre&rsquo;s '
          'gift economy at its best &mdash; healing as treasure, the '
          'adept as the cabal&rsquo;s true center, gratitude as plot. '
          '<span class="voice">Others say</span> read the chantry '
          'histories: monopolies on mercy become instruments of '
          'obligation, the healer&rsquo;s ladder becomes a creditor&rsquo;s, '
          'and 520b&rsquo;s dirty-fuel economics have a sibling here that '
          'the Traditions discuss less. Both readings are true in '
          'different houses; the contract of 384b decides which house '
          'the table plays in; and the chapter of measures ends where it '
          'began &mdash; at a law that defers, deliberately, to the '
          'people holding it. <span class="kw">TEYKU</span> &mdash; and '
          'so Middot rests.</p>',
 'outer_head': 'The Coroners<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the margins, the dials, and the '
               'monopoly</span>',
 'rubric': 'the three inks, and their clocks',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Ninth: Middot, Measures, '
             'concluded &middot; of the wound &middot; the kinds of harm as law',
 'title': 'Tractate Aliyah · Folio 406b — The Wound: the three inks, and their clocks',
 'type': 'daf'}
