# Folio 409a - Combat. Chapter X opens; facts per the wod-llm-wiki combat
# and initiative pages (M20 pp.399-401, 409-413).
FOLIO = {'bottom': '<p><span class="lemma">On combat as scene.</span> The ladder is a camera '
           'rig, not a physics engine: it exists to make violence legible, and the '
           'Storyteller who runs it as accounting has traded the genre&rsquo;s dread for '
           'its spreadsheet. Narrate the rungs as moments &mdash; the draw, the sidestep, '
           'the wet sound of the third phase &mdash; and keep the turns short in the '
           'telling as they are in the fiction; three seconds of story should not take '
           'ten minutes of table.</p>\n'
           '        <p><span class="lemma">On stakes before initiative.</span> The '
           'contract&rsquo;s clause, repeated here on purpose as 384b promised: before '
           'the first die of the ladder, the table hears what the fight is for and what '
           'losing means &mdash; capture, humiliation, the track of 406, the fade. '
           'Violence in this game is fast, cheap, and mostly lethal to the people the '
           'genre is about; the roll of initiative is the last calm moment in which '
           'anyone can ask whether this scene is a fight at all, and the Storyteller '
           'should let the question be heard.</p>\n'
           '        <p><span class="lemma">On choosing the custom.</span> The books offer '
           'two initiative customs &mdash; roll each turn, or roll once and keep the '
           'order &mdash; and command only that the table pick before the action and '
           'not switch mid-scene. Per-turn rolling breathes; per-scene rolling moves. '
           'Declare the custom in session zero with the rest of the constitution, and '
           'if the troupe cannot agree, run per-scene for wars and per-turn for duels, '
           'which is most tables&rsquo; blend anyway.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on cameras, stakes, and the '
                'two customs</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The fight is a ladder of four rungs,</span> climbed '
           'each turn. First the order: each rolls one die and adds quickness and wits '
           'together, and the highest acts first &mdash; ties to the higher rating, then '
           'the quicker mind, then the quicker hand, and if all tie, together.<sup>a</sup> '
           'Second the attack: the hand is quickness joined to the craft &mdash; the '
           'trigger&rsquo;s craft for guns, the blade&rsquo;s for steel, the '
           'athlete&rsquo;s for the thrown, the brawler&rsquo;s for the body &mdash; and '
           'for workings, Arete, as the verso provides.<sup>b</sup> Third the defense: '
           'whoever still holds an action may spend it dodging, blocking, or parrying, '
           'and every defending success erases an attacking one; the action already '
           'promised is bought back only by will, rolled or spent; the parry that '
           'out-rolls the blow may answer it at full strength; and the bare hand blocks '
           'only the bruising kind, for steel is not stopped by skin.<sup>c</sup> Fourth '
           'the damage: the blow that lands rolls its pool against six, each success a '
           'line of 406&rsquo;s ledger, and each attacking success past the first adds a '
           'die &mdash; then the body answers with Stamina, soaking the bruising kind at '
           'six, the cutting kind not at all for mortal flesh, and the third ink '
           'never.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear '
           'one exchange, climbed rung by rung. Two rivals in a parking structure; the '
           'die and the summed wits give the knife-man the turn. He strikes: quickness '
           'and the blade&rsquo;s craft, three successes. She has held her action for '
           'exactly this and dodges &mdash; quickness and the athlete&rsquo;s art '
           'against a wall of five, two successes &mdash; and two of his three are '
           'erased. One success lands: his damage pool rolls against six with no bonus '
           'dice, for the dodge ate the surplus, and one line of the ledger fills with '
           'the cutting mark. She cannot soak it; she is not a werewolf; the chapter of '
           'measures said so and meant it. Next turn the order holds, and she is '
           'deciding &mdash; as the reader should be &mdash; whether this scene was '
           'ever winnable, and what the exits cost. The disputants around this text '
           'hold the ladder&rsquo;s joints: who defends and when, what the abort '
           'price buys, and how lethal the baseline was meant to be.</p>',
 'chapter': 'Chapter the Tenth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; chapter X of Strife '
             'opens here; the magick in the fight waits overleaf.',
 'folio': '409A',
 'glossL': '<p><span class="mark">a</span> On initiative &mdash; one die plus Dexterity '
           'and Wits, the tie ladder, and the once-or-every-turn customs &mdash; see '
           'M20, the systems chapter, folios 399&ndash;401.</p>\n'
           '        <p><span class="mark">b</span> On the attack pools by weapon kind, '
           'see folios 409&ndash;410 of the same chapter, whence this page takes its '
           'number.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On defenses &mdash; '
           'dodge, block, parry, the desperate defense, the abort by Willpower, and '
           'the rebounding parry &mdash; see folios 410&ndash;411; the bare '
           'hand&rsquo;s limit yields to trained arts, folio 423.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On damage pools, bonus '
           'dice, soak by kind, and the optional cinematic soak of lethal harm at a '
           'harder wall, see folios 412&ndash;413.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The ladder&rsquo;s fourth rung empties '
           'into 406&rsquo;s ledger, and the two folios should be run as one machine: '
           'this page deals the marks, that page prices them, and the exemption of '
           'Arete from wound penalties is why the fight against a mage is never over '
           'when it looks over.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The multiple '
           'deed&rsquo;s division, 385b, governs the fighter who attacks and defends '
           'in one turn: the smallest hand, divided &mdash; which is why the books '
           'call the desperate defense desperate.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The trained '
           'exceptions to every rung &mdash; the art that blocks steel, the way that '
           'strikes lethal barehanded &mdash; are folio 423&rsquo;s; the duel with '
           'rules of its own is 430&rsquo;s; the world&rsquo;s own violence, needing '
           'no attacker, is 435&rsquo;s chart.</p>',
 'h1': 'Combat',
 'hagahah': 'The ladder has four rungs, and most fights end on the first: the side '
            'that wins the order usually writes the rest. The books know this, the '
            'veterans know this, and the Time adepts, who cannot be surprised, have '
            'built a Sphere on knowing it first.',
 'inner': '<p><span class="lemma">A ladder of four rungs.</span> The structure&rsquo;s '
          'plain sense: the turn is decomposed so that every question is asked once '
          'and in order &mdash; who moves, what is attempted, what is prevented, what '
          'it cost. The decomposition is the system&rsquo;s mercy to the table: '
          'violence is the scene where everyone talks at once, and the ladder is a '
          'speaking order imposed on chaos, which is also, note, what initiative is '
          'in the fiction.</p>\n'
          '        <p><span class="lemma">Quickness and wits together.</span> The '
          'order&rsquo;s plain sense: reaction is body and mind summed, so the '
          'fastest hand at the table may still move second behind the quicker read. '
          'The tie ladder rewards the same pairing in miniature &mdash; rating, then '
          'wits, then hand &mdash; and the simultaneous case is real law, not a '
          'shrug: two blades landing together both land, and the table that has '
          'seen mutual ruin once respects the order roll forever after.</p>\n'
          '        <p><span class="lemma">Whoever still holds an action.</span> The '
          'defense economy&rsquo;s plain sense: protection is not free &mdash; it is '
          'purchased with the turn&rsquo;s action, split from the attack by '
          '385b&rsquo;s division, or bought back from a promise already made at the '
          'will&rsquo;s price. The design pushes fighters to choose commitment or '
          'caution before the dice speak, and the fighter who wants both pays for '
          'both, which is the whole moral of the middle rungs.</p>\n'
          '        <p><span class="lemma">Bought back only by will.</span> The '
          'abort&rsquo;s plain sense: the action already declared is a promise, '
          'and unmaking a promise under fire costs nerve &mdash; the will rolled '
          'against six, or a point of it spent outright to be sure. The clause '
          'is the ladder&rsquo;s one moment of psychology: the fighter mid-swing '
          'who sees the counter coming must find, in half a second, the '
          'discipline to stop &mdash; and the system prices the finding, which '
          'is more respect than most rules pay to changing one&rsquo;s '
          'mind.</p>\n'
          '        <p><span class="lemma">May answer it at full strength.</span> '
          'The rebound&rsquo;s plain sense: the parry whose successes beat the '
          'blow&rsquo;s converts defense into attack on the spot &mdash; the '
          'full pool, a bonus for every point of surplus &mdash; and the books '
          'append the folk wisdom in their own voice: do not swing at the one '
          'holding the better weapon. The rebound is the middle rungs&rsquo; '
          'only profit motive, and duelists build whole styles on it.</p>\n'
          '        <p><span class="lemma">Every defending success erases an '
          'attacking one.</span> The subtraction&rsquo;s plain sense, and its reach: '
          'the erasure eats the surplus first, so a good defense does not merely '
          'survive the blow but starves its damage of bonus dice &mdash; the '
          'difference between a hit and a wound is usually decided here, in the '
          'third rung, not the fourth. The desperate defense extends the logic to '
          'its limit: everything spent on not being hit, full strength against the '
          'first blow and a die less against each after, nothing left for '
          'answering.</p>\n'
          '        <p><span class="lemma">For mortal flesh.</span> The soak '
          'clause&rsquo;s plain sense, and the chapter&rsquo;s continuity: the '
          'wound taxonomy of 406b governs here unchanged &mdash; Stamina answers '
          'the bruise, nothing mortal answers the blade, and the optional cinematic '
          'dial that lets heroes soak steel at a harder wall is a genre transplant '
          'the books offer openly and this tractate&rsquo;s coroners have already '
          'judged. The mage at the ladder&rsquo;s foot is exactly as fragile as '
          'the chapter of measures promised, which is why the verso exists.</p>',
 'inner_head': 'On the Ladder<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; rung by rung, price by price</span>',
 'name': 'Combat',
 'outer': '<p><span class="lemma">Who defends and when.</span> The economy dispute. '
          '<span class="voice">Some say</span> the defense rules are the '
          'system&rsquo;s finest pressure: making protection cost an action turns '
          'every turn into a wager between hurting and not being hurt, and the '
          'abort price &mdash; will rolled or spent to unmake a promise &mdash; is '
          'the rare mechanic that models courage failing gracefully. <span '
          'class="voice">Others say</span> the economy overprices caution: the '
          'system already starves defenders through the smallest-hand division, '
          'and a baseline where the prudent fighter falls behind the reckless one '
          'teaches tables that the best defense is shooting first &mdash; which '
          'the genre&rsquo;s body count then documents. The first school answers '
          'that the genre <span class="aside">is</span> the body count: a horror '
          'game where caution won would be a different shelf. The second concedes '
          'the shelf and keeps the house rules; the tractate files both and notes '
          'that the rebounding parry &mdash; the one defense that answers back '
          '&mdash; is the drafters&rsquo; own tell that they, too, wanted defense '
          'to occasionally win.</p>\n'
          '        <p><span class="lemma">How lethal the baseline.</span> The '
          'tuning dispute, with its famous dial. The printed law leaves mortal '
          'flesh unable to soak steel; the printed option opens the cinematic '
          'valve at a harder wall and the Storyteller&rsquo;s discretion. <span '
          'class="voice">Some say</span> run the law: the mage&rsquo;s glass body '
          'is the setting&rsquo;s thesis, 406a&rsquo;s examiners already ruled the '
          'fragility is the game, and every point of soak granted to heroes is a '
          'point of dread taxed from the chronicle. <span class="voice">Others '
          'say</span> the valve is printed because the thesis has a counter-thesis: '
          'a war chronicle, a pulp chronicle, a chronicle of Adepts in powered '
          'armor wants bodies that survive act one, and the books&rsquo; own '
          'options page is the drafters granting the transplant a license &mdash; '
          'and a hedged one: the cinematic valve opens at a harder wall, and the '
          'printed counsel lets the Storyteller reserve it for the genuinely '
          'tough, so even the transplant arrives pre-rationed. The '
          'schools agree the dial must be set in session zero and never mid-fight; '
          'the tractate adds only that whichever setting is chosen, the villains '
          'get it too, per 406a&rsquo;s symmetry rule.</p>\n'
          '        <p><span class="lemma">The ladder&rsquo;s joints.</span> A last '
          'difficulty, structural: is the four-rung turn a simulation or a genre '
          'grammar? <span class="voice">Some say</span> simulation, roughly: three '
          'seconds, one exchange, the phases in causal order &mdash; the ladder '
          'approximates a fight as well as dice approximate anything. <span '
          'class="voice">Others say</span> grammar: real violence has no turns, '
          'and the ladder&rsquo;s true referent is the fight <span '
          'class="aside">scene</span> &mdash; beat, counter-beat, consequence '
          '&mdash; which is why it reads better than it simulates and why every '
          'attempt to make it more realistic makes it worse at the table. The '
          'dispute is the recto&rsquo;s form-paradox wearing brass knuckles, and '
          'the tractate rules as it ruled at 384a: the grammar reading explains '
          'more, including why the chapter that follows keeps deferring to the '
          'story &mdash; and why the veterans of both schools, asked to choose, '
          'reach for the same word: the ladder is not how fights work; it is '
          'how fights are told. <span class="kw">TEYKU</span> &mdash; and keep '
          'your guard up.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the economy, the dial, and the grammar</span>',
 'rubric': 'the four rungs, and their prices',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife &middot; of '
             'combat &middot; the fight as law',
 'title': 'Tractate Aliyah · Folio 409a — Combat: the four rungs, and their prices',
 'type': 'daf'}
