# Folio 409b - The Gun and the Word. Verso of Combat: magick in violence,
# per the wod-llm-wiki combat page (M20 pp.407, 413-418).
FOLIO = {'bottom': '<p><span class="lemma">On adjudicating the three doors.</span> Ask which came '
           'first in the fiction and rule from the answer: the working that is the '
           'attack takes the first door and one action; the blow struck to power the '
           'working takes the second and rolls the attack first; the working cast to '
           'guide the blow takes the third and rolls Arete first. The commonest table '
           'error is granting the first door&rsquo;s economy with the third '
           'door&rsquo;s ordering; the doors are alternatives, and the mage who wants '
           'all three at once wants three turns.</p>\n'
           '        <p><span class="lemma">On the coincidence of gunfire.</span> The '
           'fight is the friendliest venue coincidental magick ever gets: bullets '
           'miss, guns jam, gas tanks ignite, and a working dressed as any of these '
           'passes the bystanders of 533b without a second glance. Reward the player '
           'who casts in the fight&rsquo;s own vocabulary, and price the fireball '
           'honestly &mdash; the vulgar working mid-brawl is still vulgar, and '
           'witnesses at a gunfight are still witnesses, however distracted.</p>\n'
           '        <p><span class="lemma">On the mook dial.</span> The optional '
           'general-action rules &mdash; a whole skirmish resolved as one resisted '
           'roll, nameless foes reduced to four health lines &mdash; are pacing '
           'tools, and their honest use is declared genre: the war story cuts '
           'through its checkpoints to reach its horrors. Never quietly promote a '
           'mook to a person mid-fight or demote a person to a mook; the table can '
           'tell, and the difference is exactly the difference this game is '
           'about.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on doors, coincidence, and '
                'extras</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Magick enters the fight by three doors.</span> By the '
           'first, the violence is the working&rsquo;s own instrument &mdash; the gun '
           'and trigger her focus &mdash; and one act serves both: Arete is rolled for '
           'the working and the attack rolled to land it; the Arete that fails casts '
           'nothing, the Arete that botches answers to 533a, and the working that is '
           'not delivered does not arrive.<sup>a</sup> By the second, the violence '
           'feeds the working: strike first, and each success eases the '
           'casting&rsquo;s wall by one, to three at most. By the third, the working '
           'feeds the violence: cast first, and each success eases the attack&rsquo;s '
           'wall by one, to three at most &mdash; coincidental where the help could '
           'pass for luck, vulgar where the sword catches fire.<sup>b</sup> The '
           'working improvised mid-fight pays one more on the wall, save for those '
           'whose art or weapon is their practice.<sup>c</sup> And the fight has '
           'circumstances the law prices: the ambush won by stealth against '
           'watchfulness, a free blow before the order; many attackers raising every '
           'wall by their count, to four; the aimed blow paying wall for damage, '
           'small targets dearest; and the spirit unbodied, which attacks and soaks '
           'by will, wounds by rage, and is touched only by enchanted '
           'blows.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why three '
           'doors and not one? Come and hear the design walking its own tightrope: '
           'the fight is the Consensus at its most alert, and the drafters needed '
           'magick present without magick abolishing the ladder. So the doors are '
           'priced as disciplines &mdash; the first door taxes failure twice, for '
           'the working and the shot each have their dice; the second and third '
           'convert successes into eased walls at a fixed, capped rate, never into '
           'automatic ruin; and the improviser&rsquo;s surcharge sends every '
           'fighting mage toward a focus she has actually trained, which is to say '
           'toward character. The old recensions made the focused working wait a '
           'turn between word and effect; the modern text deletes the delay and '
           'keeps the prices, and the disputants opposite hold what the deletion '
           'changed, and whom the doors favor.</p>',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; verso of Combat: '
             'the recto keeps the ladder, this side keeps the doors cut into it.',
 'folio': '409B',
 'glossL': '<p><span class="mark">a</span> On violence as a focus &mdash; one action, '
           'Arete plus the attack, failure and botch cases &mdash; see M20, the '
           'systems chapter, folios 413&ndash;414.</p>\n'
           '        <p><span class="mark">b</span> On violence enhancing magick and '
           'magick enhancing violence, each success easing the other&rsquo;s wall by '
           'one to a limit of three, see the same pages; the coincidence test is '
           '533a&rsquo;s, applied.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On fast-casting&rsquo;s '
           'surcharge and its exemption for the martial practice and the weapon '
           'focus, see folio 414; the exemption is 423&rsquo;s door into this '
           'page.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On ambush, multiple '
           'opponents, targeting, and the unbodied spirit&rsquo;s combat, see folios '
           '415&ndash;418; the spirit rules point onward to the courts of folio 91.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The countermagick named on the recto '
           'as a mystic dodge is cast by Arete and judged by 533a&rsquo;s law; the '
           'Prime master&rsquo;s unweaving, 520a, stands over the fight as it '
           'stands over everything, at prices already priced.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The second and '
           'third doors are 385b&rsquo;s complementary rolls wearing armor &mdash; '
           'success at one deed easing another, a step per surplus, never more than '
           'three; the Masoret notes the same arithmetic in both places and calls '
           'it a design signature.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Time '
           'master&rsquo;s immunity to ambush, and the third rank that buys out of '
           'the crowded turn entirely, are 522a&rsquo;s; the duelists of 430 fear '
           'that Sphere for reasons this page makes obvious.</p>',
 'h1': 'The Gun and the Word',
 'hagahah': 'The gun is a focus, the trigger a mantra, the muzzle flash a sigil the '
            'Sleepers taught themselves to believe in. The Consensus will accept a '
            'miracle at a crime scene it would riot against in a cathedral, and '
            'every fighting mage in the setting has quietly noticed.',
 'inner': '<p><span class="lemma">One act serves both.</span> The first door&rsquo;s '
          'plain sense, and its double jeopardy: the working and the attack are one '
          'motion in the fiction and two pools on the table, and either can fail '
          'alone &mdash; the shot that flies true carrying no magick, the magick '
          'primed in a bullet that misses. The economy is generous &mdash; one '
          'action where the unfocused mage needs two &mdash; and the tax is '
          'variance, which is the system&rsquo;s way of saying the gun-mage has '
          'married her art to her aim, for better and worse.</p>\n'
          '        <p><span class="lemma">To three at most.</span> The cap&rsquo;s '
          'plain sense, on both assisting doors: help converts at one success to '
          'one step of wall and stops at three, so no pile of successes turns '
          'assistance into automation. The cap is the same figure the '
          'complementary-roll law wears in Middot, and its function is identical '
          '&mdash; cooperation between deeds is real, bounded, and never a '
          'substitute for the deed itself.</p>\n'
          '        <p><span class="lemma">Whose art or weapon is their '
          'practice.</span> The exemption&rsquo;s plain sense: the fast-casting '
          'surcharge falls on improvisation, and the fighter whose paradigm '
          '<span class="aside">is</span> the fight &mdash; the martial way, the '
          'gun-focus, the blade sanctified by practice &mdash; is not improvising '
          'when she casts through it. The clause is the system&rsquo;s reward for '
          'coherent character build over toolbox opportunism, and 423&rsquo;s '
          'whole folio walks through the door it opens.</p>\n'
          '        <p><span class="lemma">A free blow before the order.</span> The '
          'ambush&rsquo;s plain sense: stealth against watchfulness, resisted, the '
          'winner striking outside the ladder entirely with a die per surplus '
          'success &mdash; and the tie&rsquo;s mercy, first blow but defensible, '
          'is the drafters saying the half-noticed ambush is a different thing '
          'than the unseen one. The listed immunities &mdash; the armored '
          'sentinel, the master of Time &mdash; are less exceptions than '
          'boundary markers: surprise is an information condition, and some '
          'beings have no information deficit to exploit.</p>\n'
          '        <p><span class="lemma">By will, by rage, by enchanted '
          'blows.</span> The unbodied clause&rsquo;s plain sense: the spirit '
          'fight runs on different currencies &mdash; will where flesh would '
          'soak, rage where strength would wound, and ordinary matter passing '
          'through uselessly unless the blow is enchanted to touch it. The '
          'clause is a border checkpoint with the Worlds Beyond, folios 89 through 109, and this folio keeps only the toll booth: what a fighter '
          'needs to know at the ladder&rsquo;s speed, which is chiefly that her '
          'gun does nothing and her Avatar might.</p>\n'
          '        <p><span class="lemma">The mystic dodge.</span> '
          'Countermagick&rsquo;s plain sense, kept brief because its law lives in '
          'the Book of Magick: the working aimed at a mage may be answered by '
          'Arete itself, the rival&rsquo;s effect unwoven mid-flight as a body '
          'would dodge a blow. The recto lists it among the defenses because that '
          'is what it is &mdash; a reaction, priced like the others in actions '
          'and attention &mdash; and the fighter who forgets she has it has '
          'forgotten that her whole art is, among other things, armor.</p>',
 'inner_head': 'On the Doors<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; door by door, price by price</span>',
 'name': 'The Gun and the Word',
 'outer': '<p><span class="lemma">What the deletion changed.</span> The girsa, tried '
          'first because it is clean. The elder manuscripts made the focused '
          'working wait &mdash; word this turn, effect the next &mdash; and the '
          'modern text lets the spell ride the bullet home. <span '
          'class="voice">Some say</span> the wait was load-bearing: it made combat '
          'magick a commitment the enemy could see coming, kept the gun-mage '
          'honest, and its deletion quietly crowned the fighting mystic over the '
          'fighting soldier. <span class="voice">Others say</span> the wait was a '
          'penalty on exactly the wrong art: the setting&rsquo;s whole premise is '
          'will acting on world, a turn of lag made the premise feel bureaucratic, '
          'and the modern pricing &mdash; double variance, capped assists, the '
          'improviser&rsquo;s surcharge &mdash; disciplines the gun-mage better '
          'than the calendar ever did. The tractate files the variant '
          'unharmonized and observes only that the deletion moved the '
          'balance-point from time to risk, which is the modern text&rsquo;s '
          'signature move everywhere.</p>\n'
          '        <p><span class="lemma">Whom the doors favor.</span> The equity '
          'dispute. <span class="voice">Some say</span> the doors favor the '
          'prepared: every price in this folio &mdash; the surcharge waived for '
          'practice, the assists capped, the focus married to the aim &mdash; '
          'rewards the mage who built for violence and taxes the scholar dragged '
          'into it, and the result is a combat chapter that quietly tells '
          'half the Traditions to stay home. <span class="voice">Others '
          'say</span> read the doors again: the scholar&rsquo;s door is the '
          'third &mdash; cast first, from cover, and hand the fighter beside her '
          'an eased wall &mdash; and the chapter&rsquo;s real lesson is division '
          'of labor: the cabal fights as a body, the assists are its ligaments, '
          'and the lone gun-adept the first school fears is out-performed at '
          'every table by a witch and a soldier who trust each other. The '
          'schools disagree about a fantasy of self-sufficiency, the tractate '
          'notes, and the setting has been against that fantasy since folio '
          '2a, where nine strangers built a Council because none of them '
          'could win alone.</p>\n'
          '        <p><span class="lemma">The friendliest venue.</span> The last '
          'difficulty, half in the Later Authorities&rsquo; jurisdiction and '
          'pulled up here because it has teeth: does the fight&rsquo;s cover for '
          'coincidence corrupt the art? <span class="voice">Some say</span> yes, '
          'and deliciously: the mage who learns that bullets hide miracles '
          'drifts toward scenes with bullets in them, the paradigm bends toward '
          'the venue, and the Chakravanti of 156b would name the drift a '
          'symptom. <span class="voice">Others say</span> the venue is neutral '
          'and the drift is chosen: coincidence lives wherever the world is '
          'already loud &mdash; hospitals, markets, storms &mdash; and the mage '
          'who only hears the gunfire has told the table about herself, not '
          'about the law. The dispute is a character sheet arguing with a '
          'cosmology, and the tractate lets them argue, noting only that both '
          'schools cite the same hagahah and neither finds it funny. <span '
          'class="kw">TEYKU</span> &mdash; hold your fire.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the wait, the equity, and the venue</span>',
 'rubric': 'the three doors, and their tolls',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of the gun and the word &middot; magick in violence as law',
 'title': 'Tractate Aliyah · Folio 409b — The Gun and the Word: magick in violence',
 'type': 'daf'}
