# Folio 423a - The Martial Arts and Do. Facts per the wod-llm-wiki
# martial-arts page (M20 pp.420-429).
FOLIO = {'bottom': '<p><span class="lemma">On pricing the maneuvers.</span> The maneuver list is '
           'a menu, not a script: two per dot means a fighter knows a handful of named '
           'moves and improvises the rest as plain blows, and the Storyteller should let '
           'the named moves feel named &mdash; the sweep that ends a duel, the lock that '
           'ends an argument. Enforce the minimum Abilities exactly; they are the '
           'system&rsquo;s apprenticeship, and the fighter who wants the death strike '
           'buys the discipline before the trick.</p>\n'
           '        <p><span class="lemma">On the drunken option.</span> The broken-rhythm '
           'school &mdash; harder to hit, harder to land, live only while initiative is '
           'won &mdash; is the rare optional rule that prices its own flavor correctly: '
           'chaos as a stance, bought with unpredictability&rsquo;s tax. Allow it for '
           'the specialist who roleplays the rhythm, and remember the printed edges: '
           'the Time-armed defender reads through it; the mind-reader does not.</p>\n'
           '        <p><span class="lemma">On the Way at the table.</span> Do is a '
           'commitment mechanic wearing a belt: the daily hour, the decay clause, the '
           'teacher requirement are all fuel for story &mdash; the practice missed on '
           'the run, the sifu&rsquo;s displeasure, the schism over an unworthy student. '
           'Run them as scenes, not bookkeeping; a discipline that only appears as '
           'erosion on the sheet has wasted the best hook the chapter gives the '
           'Akashayana&rsquo;s players.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on menus, rhythm, and the '
                'daily hour</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The empty hand has schools,</span> and the schools '
           'have law. The arts divide by temperament: the hard styles strike through, '
           'the soft styles turn the striker&rsquo;s force against him, and a fighter '
           'learns two named maneuvers for every dot of her art, the advanced maneuvers '
           'demanding their minimum training as written.<sup>a</sup> Above the arts '
           'stands <span class="term">Do</span>, the complete way, of which the arts '
           'are called descendants: held by the Akashayana and their nearest allies '
           'alone, begun no higher than its second dot, taught only by a master of its '
           'third and proper standing, and kept by daily practice or lost by the '
           'fortnight.<sup>b</sup> The way confers what the arts cannot: the '
           'devotee&rsquo;s bare hand strikes the cutting kind at her choosing and '
           'blocks it barehanded; the general maneuvers come one wall easier; any '
           'art&rsquo;s maneuver is hers if her Do suffices; and each dot past the '
           'first grants a technique of the way itself.<sup>c</sup> But the way is '
           'not a fighting art with extras: to raise Do is to raise the whole life '
           '&mdash; two dots of the eight limbs&rsquo; learning for every dot of the '
           'way, combat one limb among eight &mdash; and the dirty trick is forbidden '
           'the devotee outright.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear the way&rsquo;s day, for the mechanics describe a life. Before dawn, '
           'the hour of practice that the law will not waive &mdash; miss a '
           'fortnight and the way itself withdraws, dot by dot, as water leaves an '
           'unworked field. Then the limbs in their rotation: meditation, the '
           'healer&rsquo;s hands, the humble labor, the ethics argued at breakfast, '
           'the weapons, the empty body moving unseen, the triple struggle balanced, '
           'and combat &mdash; one limb, note, of eight. The fist that can kill is '
           'schooled beside the hand that mends, and the law&rsquo;s refusal of '
           'dirty fighting is not squeamishness but definition: the way is what it '
           'is by what it will not do. The disputants around this text hold the two '
           'quarrels the brief promised: whether the way&rsquo;s price buys too much '
           'power, and whether one Tradition may own the mother of all arts.</p>',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; the eight limbs '
             'and the techniques of the way wait overleaf.',
 'folio': '423A',
 'glossL': '<p><span class="mark">a</span> On the hard and soft styles, the two '
           'maneuvers per dot, and the minimum Abilities, see M20, the systems '
           'chapter, folios 420&ndash;426, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On Do&rsquo;s restriction, its '
           'starting cap, the teacher&rsquo;s requirements, and the decay of '
           'neglected practice, see folios 426&ndash;427.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the way&rsquo;s '
           'advantages &mdash; lethal option, hardened defense, the eased general '
           'maneuvers, borrowed maneuvers, and the techniques &mdash; see folios '
           '426&ndash;428.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the eight limbs '
           'and their two-dots-per-dot study, and the ban on dirty fighting, see '
           'folios 427&ndash;428.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is 148&rsquo;s outer '
           'commentary continued by other means: the Akashayana&rsquo;s daf holds '
           'the way&rsquo;s theology and this one its jurisprudence, and the '
           'gatekeeping dispute below cites that folio&rsquo;s wheel '
           'directly.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The martial '
           'practice as focus &mdash; a dot of art per dot of channeled Sphere, '
           'and the fast-casting surcharge waived &mdash; is the door 409b cut; '
           'the mage-tricks of the way, bullets caught by conjoined Spheres, '
           'wait overleaf with the techniques.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'Wu Lung&rsquo;s dragon style and its double-counted tens, folio 197, '
           'wanting, keep the Masoret&rsquo;s reminder that the Akashayana&rsquo;s '
           'claim of descent has neighbors who dispute the genealogy in '
           'kind.</p>',
 'h1': 'The Martial Arts and Do',
 'hagahah': 'The deadliest art in the setting teaches mostly standing still: an hour '
            'a day of it, by law, forever. The students who quit are the ones who '
            'wanted the death strike; the masters are the ones who stopped '
            'noticing the standing still was the point.',
 'inner': '<p><span class="lemma">The hard styles strike through.</span> The '
          'division&rsquo;s plain sense: hard and soft are stances toward force '
          'itself &mdash; meet it or redirect it &mdash; and the maneuver list '
          'wears the division openly, the sweeps and deflections soft, the death '
          'strike hard as its name. The walls differ by style for the same '
          'maneuver where both teach it, which is the system quietly saying that '
          'how you do a thing is part of what the thing is.</p>\n'
          '        <p><span class="lemma">Two named maneuvers for every '
          'dot.</span> The menu&rsquo;s plain sense: named technique is rationed, '
          'so mastery reads as repertoire &mdash; the three-dot fighter holds six '
          'moves the way a mage holds rotes, and the comparison is the '
          'chapter&rsquo;s own: practiced forms, reliably priced, against the '
          'improvised blow&rsquo;s plain arithmetic. The minimum Abilities gate '
          'the lethal end of the menu behind training the sheet must actually '
          'show, and the gate is load-bearing: the art&rsquo;s killing edge is '
          'earned in dots, not declared in fiction.</p>\n'
          '        <p><span class="lemma">Or lost by the fortnight.</span> The '
          'decay clause&rsquo;s plain sense, unique in the book: Do is the one '
          'Trait that rusts, roughly a dot per two weeks of neglect, because it '
          'is a practice before it is a power &mdash; the rating measures a '
          'relationship maintained, not a fact acquired. No other number on the '
          'sheet behaves this way; the drafters made the exception to teach what '
          'kind of thing the way is, and the mechanic is the doctrine.</p>\n'
          '        <p><span class="lemma">Taught only by a master of its '
          'third.</span> The transmission clause&rsquo;s plain sense: the way '
          'moves only through a living teacher of real attainment and proper '
          'standing, so every devotee&rsquo;s sheet implies a lineage and every '
          'lineage implies a community with opinions. The clause is the '
          'gatekeeping dispute&rsquo;s mechanical anchor and the '
          'chronicle&rsquo;s gift: the teacher is a relationship the '
          'Storyteller holds, and the way can be granted, withheld, or '
          'grieved over, which no experience-point purchase can be.</p>\n'
          '        <p><span class="lemma">At her choosing.</span> The lethal '
          'option&rsquo;s plain sense: the devotee&rsquo;s hand deals the cutting '
          'kind or the bruising kind as she wills, reflexively, which makes her '
          'the only fighter in the chapter who chooses her blow&rsquo;s ink after '
          'a lifetime of choosing everything else. The hardened defense is the '
          'mirror mercy &mdash; the bare hand that blocks steel, though never '
          'bullets &mdash; and together they make the empty hand a complete '
          'weapon-set, which is the way&rsquo;s claim stated as mechanics.</p>\n'
          '        <p><span class="lemma">One limb among eight.</span> The '
          'limbs&rsquo; plain sense, and the folio&rsquo;s center of gravity: the '
          'way taxes advancement in breadth &mdash; meditation, healing, labor, '
          'ethics, weapons, stealth, balance, and only then the fist &mdash; at '
          'two dots of learning per dot of Do, so the master is expensive by '
          'design and educated by definition. The tax is why the way&rsquo;s '
          'combat edge survives the balance dispute opposite: the death touch '
          'comes bundled with a philosophy degree, and the setting prices the '
          'bundle, not the touch.</p>',
 'inner_head': 'On the Way<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; styles, rations, and the rusting dot</span>',
 'name': 'The Martial Arts and Do',
 'outer': '<p><span class="lemma">Whether the price buys too much.</span> The '
          'balance fight, as old as the way&rsquo;s first printing. <span '
          'class="voice">Some say</span> Do is the book&rsquo;s best-armored '
          'power creep: lethal barehanded, steel blocked barehanded, every '
          'art&rsquo;s maneuver on loan, eased walls, private techniques &mdash; '
          'stack it beside the plain brawler and the plain brawler is a '
          'training dummy, and no daily-practice clause rebalances what happens '
          'when the dice come out. <span class="voice">Others say</span> price '
          'the whole invoice: the two-dot creation cap, the teacher who must be '
          'found and satisfied, the eight limbs&rsquo; double tax, the decay '
          'clock, the dirty-fighting ban &mdash; the way costs a character '
          'concept, not a purchase, and the fighter who pays it has bought less '
          'power than the gun-adept bought with one dot of Firearms and a '
          'paradigm. The schools have argued this across every recension; the '
          'tractate notes only that both agree the way is unmatched <span '
          'class="aside">at its own game</span>, and that the game &mdash; the '
          'empty hand, the standing still &mdash; is one the rest of the '
          'setting mostly declines to play.</p>\n'
          '        <p><span class="lemma">Whether one Tradition may own the '
          'mother of arts.</span> The gatekeeping dispute, 148&rsquo;s quarrel '
          'continued as promised. <span class="voice">Some say</span> the '
          'restriction is theft dressed as reverence: the claim that all arts '
          'descend from Do, held by one seat, converts the world&rsquo;s '
          'fighting heritage into a Tradition&rsquo;s intellectual property '
          '&mdash; and the neighbors named in the margin, who kept their own '
          'lineages through their own catastrophes, have never signed the '
          'genealogy. <span class="voice">Others say</span> the restriction is '
          'the definition: Do is not the best kung fu but a specific whole way '
          '&mdash; the limbs, the ethics, the lifetime &mdash; transmitted '
          'master to student inside a living community, and what cannot be '
          'learned from a book cannot be owed to the public. A mechanic that '
          'let anyone buy the way would be describing a different thing wearing '
          'its name. The first school answers that definitions drawn by the '
          'powerful are still fences; the second, that some fences are the '
          'thing fenced. The wheel of 148b turns under the whole exchange, and '
          'the tractate declines to stop it. <span class="kw">TEYKU</span> '
          '&mdash; the lineage question outlives every court that hears '
          'it.</p>\n'
          '        <p><span class="lemma">The mother of all others '
          'supposedly.</span> A third difficulty, textual, and the '
          'tractate&rsquo;s favorite kind: the books&rsquo; own phrasing hedges '
          '&mdash; the descent of all arts from Do is what is <span '
          'class="aside">said</span>, not what is certified. <span '
          'class="voice">Some say</span> the hedge is mere politeness to '
          'history. <span class="voice">Others say</span> the hedge is the '
          'setting keeping its deepest habit: every origin claim in this '
          'binding &mdash; the Record, the lineages, the first city &mdash; '
          'arrives as testimony, not fact, and the way&rsquo;s genealogy joins '
          'the Akashic Record itself in the file of things asserted by those '
          'who benefit and unverifiable by those who don&rsquo;t. The reading '
          'changes no dice and every conversation, which is this '
          'tractate&rsquo;s definition of aggada.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the invoice, the fence, and the '
               'hedge</span>',
 'rubric': 'the schools of the empty hand, and the complete way',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of the martial arts and Do &middot; the empty hand as law',
 'title': 'Tractate Aliyah · Folio 423a — The Martial Arts and Do',
 'type': 'daf'}
