# Folio 423b - The Eight Limbs. Verso of the Martial Arts and Do: the
# limbs, the techniques, and the mage-tricks, per the wod-llm-wiki
# martial-arts page (M20 pp.427-429).
FOLIO = {'bottom': '<p><span class="lemma">On running the limbs.</span> Give each limb a scene '
           'before it gives a bonus: the healer&rsquo;s hands earn their dots at a '
           'bedside, the empty body in a corridor the guards never checked, the humble '
           'labor in a kitchen where a master washes dishes badly and learns something. '
           'The two-dots-per-dot tax reads as bookkeeping until the chronicle shows the '
           'learning happening; after that it reads as a life, which is what the '
           'drafters wrote it to be.</p>\n'
           '        <p><span class="lemma">On the peaceful way.</span> The optional '
           'rule that turns Do toward mundane excellence &mdash; will spent, the way '
           'rolled, successes lent to a limb&rsquo;s task and never to violence &mdash; '
           'is the verso&rsquo;s thesis as a mechanic, and tables that adopt it report '
           'the same discovery: the Akashic player starts looking for non-combat '
           'scenes to be excellent in, which is the way working as designed on the '
           'player herself.</p>\n'
           '        <p><span class="lemma">On catching bullets.</span> The famous '
           'trick &mdash; arrow-cutting raised by conjoined Spheres to the gun&rsquo;s '
           'speed &mdash; is a paradigm negotiation, not a purchase: vulgar where '
           'reality disbelieves it, coincidental exactly where the kung-fu cinema '
           'paradigm holds, never against the weapons the books except. Rule the '
           'reality zone first and the dice second, and let the scene where it works '
           'be the scene the table remembers all year.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on scenes, peace, and the '
                'catch</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The way stands on eight limbs,</span> and combat is '
           'one. The devotee studies unarmed struggle and meditation, the '
           'healer&rsquo;s work and the humble labor, ethics and the way of weapons, '
           'the empty body that moves unseen, and the triple struggle that balances '
           'the world&rsquo;s three pulls &mdash; two dots of the limbs&rsquo; '
           'learning bought for every dot of the way, beyond the fighting limb '
           'itself.<sup>a</sup> Each dot past the first grants a technique of the '
           'way: the arrow cut from the air though never the bullet unaided; the '
           'shirt of iron that turns blows aside, save always one line from the blow '
           'that overmatches the body; the shout that stuns, terrifies, or '
           'persuades; the throw that gathers the whirlwind; the leap of the plum '
           'blossom; the soft fist that hands an attack to another foe; the ten '
           'thousand weapons, by which anything held is armed; the typhoon kick, '
           'once in five turns; and the weapon art, by which the familiar blade '
           'comes easier and cuts deeper.<sup>b</sup> The way may be turned from '
           'violence entirely: will spent and the way rolled lends its successes to '
           'any labor of the limbs, and never to a blow.<sup>c</sup> And where the '
           'paradigm of the fighting arts holds reality&rsquo;s floor, the '
           'conjoined Spheres may raise a technique past the human &mdash; the '
           'bullet caught &mdash; coincidental there and vulgar '
           'elsewhere.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why '
           'eight limbs for one fist? Come and hear the design read backward: '
           'every technique on this page is a limb&rsquo;s lesson worn as a move. '
           'The arrow is cut by the meditation that slowed the moment; the iron '
           'shirt is the body schooled by labor until blows find nothing loose; '
           'the shout is ethics and breath in one syllable; the ten thousand '
           'weapons are the kitchen&rsquo;s lesson that nothing is only what it '
           'is. The limbs are not prerequisites for the techniques; the techniques '
           'are the limbs, glimpsed at fighting speed &mdash; and the law&rsquo;s '
           'insistence that the way rusts without practice is this same reading in '
           'reverse: stop living the limbs, and their fruits unlearn themselves. '
           'The disputants around this text hold the seams: the shirt&rsquo;s '
           'guaranteed line, the shout&rsquo;s three faces, and what the '
           'bullet-catch does to the border between art and working.</p>',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso of '
             'the Martial Arts and Do: the recto keeps the schools, this side keeps '
             'the way&rsquo;s own body.',
 'folio': '423B',
 'glossL': '<p><span class="mark">a</span> On the eight limbs and their study, two '
           'dots per dot of the way, see M20, the systems chapter, folios '
           '427&ndash;428.</p>\n'
           '        <p><span class="mark">b</span> On the special techniques, one '
           'per dot above the first, see folios 428&ndash;429; the iron '
           'shirt&rsquo;s guaranteed line and the typhoon&rsquo;s five-turn rest '
           'are the text&rsquo;s own bounds.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the peaceful '
           'way &mdash; will spent, the way rolled at a hard wall, successes lent '
           'to the limbs&rsquo; labors only &mdash; see folio 427.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On catching '
           'bullets by Time, Forces, and Life conjoined, its reality-zone '
           'pricing, and the excepted weapons, see folio 428.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The triple struggle&rsquo;s three '
           'pulls are the wheel of 148b turning in miniature, and the limb&rsquo;s '
           'name is that folio&rsquo;s cosmology assigned as homework; the '
           'Masoret reads the curriculum as the Tradition in small.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'reality-zone test that prices the bullet-catch is 533a&rsquo;s '
           'vulgarity law wearing a gi; the zones themselves are folio 62&rsquo;s, '
           'wanting, and the Masoret keeps the promise that they will be '
           'mapped.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'shout&rsquo;s persuading face borders 519a&rsquo;s consent floor '
           'where it bends a listener; the folio of the Mind has already posted '
           'the standard, and the way&rsquo;s ethics limb, note, would have '
           'posted it first.</p>',
 'h1': 'The Eight Limbs',
 'hagahah': 'Ten thousand weapons, and the first the way hands its student is a '
            'broom. The masters insist this is not a metaphor, and the students '
            'who believe them sweep their way to the second dot noticeably '
            'faster.',
 'inner': '<p><span class="lemma">Two dots of the limbs&rsquo; learning.</span> '
          'The tax&rsquo;s plain sense: advancement in the way is metered by the '
          'whole curriculum &mdash; the sheet must show meditation and medicine, '
          'craft and ethics, weapons and stealth and balance growing alongside '
          'the fist &mdash; and the tax is paid in Abilities the fighter would '
          'never otherwise buy. The mechanic manufactures exactly the character '
          'the fiction describes, which is the cleanest trick in the chapter: '
          'the rules cannot make a player wise, but they can make her sheet '
          'refuse to be narrow.</p>\n'
          '        <p><span class="lemma">Save always one line.</span> The iron '
          'shirt&rsquo;s bound, plainly: the technique turns blows, but the blow '
          'that overmatches the body lands at least its single line &mdash; no '
          'shirt makes flesh a wall, and the chapter&rsquo;s glass-body doctrine '
          'holds even for its hardest disciples. The bound is the same shape as '
          '406a&rsquo;s democracy: the ledger is seven lines for everyone, and '
          'the way&rsquo;s mastery narrows the door without ever quite closing '
          'it.</p>\n'
          '        <p><span class="lemma">Stuns, terrifies, or persuades.</span> '
          'The shout&rsquo;s plain sense: one technique, three faces &mdash; the '
          'body staggered, the nerve broken, the mind moved &mdash; chosen at '
          'use, which makes the shout the way&rsquo;s whole range in one breath: '
          'force, fear, and speech as points on a single art. The third face is '
          'the quietly radical one, and the margin&rsquo;s note about the '
          'consent floor is not decoration; the way&rsquo;s own ethics limb '
          'holds the shout to standards the technique&rsquo;s power would '
          'otherwise let slip.</p>\n'
          '        <p><span class="lemma">Never to a blow.</span> The peaceful '
          'way&rsquo;s plain sense, and its lovely asymmetry: the way&rsquo;s '
          'excellence flows outward to any of the limbs&rsquo; labors &mdash; '
          'the surgery steadied, the argument won honestly, the wall climbed '
          '&mdash; but the tap is sealed toward violence, where the way already '
          'has its own doors. The seal makes the option safe to say yes to, and '
          'the drafters clearly wanted the yes: it is the one mechanic in the '
          'chapter that pays a fighter to leave the fight.</p>\n'
          '        <p><span class="lemma">The ten thousand weapons.</span> The '
          'technique&rsquo;s plain sense, and the verso&rsquo;s best joke told '
          'straight: to the sufficiently practiced hand, anything held is armed '
          '&mdash; the broom, the teacup, the folding chair &mdash; because '
          'weapon was always a description of the wielder, not the object. The '
          'weapon art is its disciplined sibling: the familiar blade, drilled '
          'until it comes one wall easier and cuts the deeper kind, one weapon '
          'per dot of the blade&rsquo;s own craft. Between them the two '
          'techniques bracket the way&rsquo;s claim about tools: mastery makes '
          'everything a weapon, and devotion makes one thing an heirloom.</p>\n'
          '        <p><span class="lemma">Coincidental there and vulgar '
          'elsewhere.</span> The bullet-catch&rsquo;s plain sense: the trick is '
          'three Spheres conjoined riding a technique, and its price floats on '
          'the local paradigm &mdash; where the crowd believes in masters who '
          'catch death, the catch is the world agreeing with itself; where it '
          'believes in ballistics, the catch is an offense the court of 533a '
          'bills in full. The excepted weapons &mdash; the scatter and the '
          'storm of automatic fire &mdash; are the books keeping the trick a '
          'miracle rather than an armor class, and the keeping is wise.</p>',
 'inner_head': 'On the Limbs<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; limb by limb, bound by bound</span>',
 'name': 'The Eight Limbs',
 'outer': '<p><span class="lemma">The shirt&rsquo;s guaranteed line.</span> The '
          'first difficulty, small and telling. <span class="voice">Some '
          'say</span> the always-one-line clause is a balance patch with no '
          'fiction under it: either the shirt turns the blow or it does not, '
          'and a guaranteed leak reads as the designers&rsquo; thumb. <span '
          'class="voice">Others say</span> the leak is the fiction: the iron '
          'shirt is conditioning, not armor plate &mdash; the master rides the '
          'blow, and riding costs &mdash; and a technique that made its holder '
          'unhittable would break the way&rsquo;s own first teaching, that the '
          'body is mortal and the mortality is the teacher. The tractate sides '
          'with the second reading and notes its evidence: every technique on '
          'this page carries a printed bound &mdash; the bullet unaided, the '
          'typhoon&rsquo;s rest, the shout&rsquo;s wall &mdash; and bounds this '
          'consistent are doctrine, not patches. The way teaches limits by '
          'having them, and the chart of 406, which spares no one, is cited in '
          'every dojo of the setting as the first and final text.</p>\n'
          '        <p><span class="lemma">Art or working.</span> The border '
          'dispute, sharpened by the catch. <span class="voice">Some say</span> '
          'the bullet-catch settles it: the moment three Spheres ride a '
          'technique, the technique is a focus and the way is revealed as one '
          'more instrument in 533a&rsquo;s economy &mdash; magick all the way '
          'down, the gi just a robe by another cut, tailored slower. <span class="voice">Others '
          'say</span> the settlement runs the other way: the way works for its '
          'unAwakened devotees too &mdash; the maneuvers, the shirt, the shout '
          'ask no Arete &mdash; so the art stands on its own floor and the '
          'Spheres merely visit, and what the catch reveals is the '
          'setting&rsquo;s deepest courtesy: practice is real before magick '
          'touches it, which is why practice can carry magick at all. The '
          'dispute is 567&rsquo;s focus doctrine arguing with itself early, '
          'wanting, and the Masoret has filed the reservation &mdash; noting, '
          'for the record, that the recto&rsquo;s decay clause cuts for the '
          'second school: a power would keep; only a practice rusts.</p>\n'
          '        <p><span class="lemma">One fist, eight limbs, whose '
          'count?</span> The last difficulty, comparative. The books name the '
          'limbs in the Akashayana&rsquo;s own tongue, and the neighboring '
          'lineages &mdash; the dragon school&rsquo;s, the temple styles&rsquo;, '
          'the arts that never signed the genealogy &mdash; keep counts of '
          'their own. <span class="voice">Some say</span> the tractate should '
          'harmonize: the limbs are universal athletics of the spirit wearing '
          'one culture&rsquo;s names, and the binding should say so plainly. '
          '<span class="voice">Others say</span> the '
          'refusal to harmonize is the whole method of this binding: the counts '
          'differ because the ways differ, the ways differ because the peoples '
          'do, and a universal curriculum is exactly the imperial move the '
          'gatekeeping quarrel opposite warns against. The tractate keeps the '
          'eight as the Akashayana&rsquo;s eight, unharmonized, per its '
          'standing law &mdash; and observes that the law has never been '
          'easier to keep: no rival lineage has asked to be harmonized, and '
          'the dragon school&rsquo;s masters are said to count their own '
          'limbs at a number they decline to publish. <span '
          'class="kw">TEYKU</span> &mdash; and practice anyway.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the leak, the border, and the count</span>',
 'rubric': 'the limbs, the techniques, and the catch',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of the eight limbs &middot; the way&rsquo;s body as law',
 'title': 'Tractate Aliyah · Folio 423b — The Eight Limbs: the way’s body as law',
 'type': 'daf'}
