# Folio 430b - The Wager. Verso of Duels, Old Form: contests, ordeals,
# core wars, and the Reality Challenge, per the wod-llm-wiki
# magickal-duels page (M20 pp.430-433).
FOLIO = {'bottom': '<p><span class="lemma">On choosing the field.</span> The contest&rsquo;s '
           'first move is its best scene: let the rivals negotiate the field of battle '
           'in character &mdash; the riddle match against the drinking bout, the '
           'debate against the race &mdash; for the negotiation is where each reveals '
           'what she thinks excellence is. Set stakes and witnesses per the '
           'recto&rsquo;s counsel, run the field on the feats tables, and let the '
           'extended form&rsquo;s clock do the pacing it was built for.</p>\n'
           '        <p><span class="lemma">On running the core war.</span> The '
           'Adepts&rsquo; duel is bookkeeping-heavy by design &mdash; cores, viruses, '
           'power-ups, the race to twenty-five &mdash; and it plays best as montage '
           'with spikes: narrate the runs, roll the exchanges, and slow to real time '
           'only when a botch draws blood. Keep the stakes literal; the pot of '
           'Quintessence changing hands is the form&rsquo;s whole gravity, and the '
           'table should feel the pot.</p>\n'
           '        <p><span class="lemma">On judging the challenge.</span> The '
           'Reality Challenge is a story hook wearing a duel&rsquo;s clothes, and the '
           'books say so plainly: set the Sleeper problem, name the goals, enforce '
           'the one rule, and judge as reality would &mdash; by what actually got '
           'better. Resist scoring it in dice; the form exists so that two enemies '
           'can spend a season doing good out of spite, and the spite converting to '
           'something else mid-story is the entire point of offering it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on fields, montages, and '
                'judgment</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Not every quarrel needs a circle.</span> Rivals may '
           'meet in a <span class="term">contest</span>: a field of battle agreed '
           '&mdash; riddles or races, debate or daring &mdash; stakes declared, '
           'witnesses and seconds seated, and the match run as the count&rsquo;s '
           'extended forms provide.<sup>a</sup> Or in an <span '
           'class="term">ordeal</span>: both undertake the same suffering, and the '
           'first to yield loses &mdash; the courage rolled as will, the harm real, '
           'bruising and worse.<sup>b</sup> Or online, where the flame war sheds '
           'temporary will from its losers, and the Adepts&rsquo; <span '
           'class="term">core war</span> is fought in earnest: each rival banks '
           'Quintessence in a fortified core, writes viruses at a point of essence '
           'apiece, and races by extended and resisted rolls to five-and-twenty '
           'successes; the breached core yields its whole treasure, the failed roll '
           'kills a virus and bruises its author, and the botch cuts &mdash; core '
           'warriors have died at the keyboard.<sup>c</sup> And highest of the forms '
           'stands the <span class="term">Reality Challenge</span>: rivals adopt a '
           'Sleeper affliction &mdash; a poisoned block, a hungry district, a ring '
           'of traffickers &mdash; and compete to mend it best, under one rule '
           'only: no vulgar working before witnesses, on pain of a forfeited goal, '
           'and a backlash forfeits all. Its judge is reality itself, and mystic '
           'and Technocrat may share its field, alone of every form.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear the forms ranked by what they wager. The contest stakes pride and '
           'the named prize; the ordeal stakes the body&rsquo;s ease; the flame war '
           'stakes composure, which its veterans insist is a real organ; the core '
           'war stakes wealth and, at the botch&rsquo;s edge, life. And the '
           'challenge stakes the quarrel itself: two enemies pour a season&rsquo;s '
           'art into a street the Consensus forgot, and whichever wins, the street '
           'is mended &mdash; the wager the setting cannot lose. The old duel '
           'opposite made harm into property; these forms make rivalry into '
           'currency, spendable on anything from vanity to a neighborhood&rsquo;s '
           'salvation. The disputants around this text hold the ladder&rsquo;s two '
           'ends: whether the ordeal is a duel or a pathology, and whether the '
           'challenge&rsquo;s judge can be trusted to exist.</p>',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso of '
             'Duels, Old Form: the recto keeps the circle, this side keeps every '
             'field the circle cannot hold.',
 'folio': '430B',
 'glossL': '<p><span class="mark">a</span> On contests, their fields, stakes, '
           'witnesses, and seconds, see M20, the systems chapter, folio 430; the '
           'feats they run on are the dramatic-feats tables of the same '
           'chapter.</p>\n'
           '        <p><span class="mark">b</span> On ordeals and their real harm, '
           'see folios 430&ndash;431.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On flame wars and '
           'the core war &mdash; the banked cores, the priced viruses, the race to '
           'five-and-twenty, the lethal botch &mdash; see folio 431.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Reality '
           'Challenge, its one rule, and its shared field, see folios '
           '431&ndash;433; the reality zones that give the rule teeth are the '
           'Book of Magick&rsquo;s, folio 62 of this binding.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The core war is 164b&rsquo;s web '
           'fought at duel scale: the Adepts&rsquo; whole cosmology &mdash; '
           'information as territory, wealth as bandwidth &mdash; compressed into '
           'a sport that can kill. The Masoret notes that every Tradition&rsquo;s '
           'duel is its paradigm with a scoreboard.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'ordeal&rsquo;s harm runs on 406&rsquo;s ledger unsoftened, and the '
           'will rolled against yielding is 328&rsquo;s trait at full price, '
           'wanting; the tractate&rsquo;s physicians have already noted which '
           'Tradition&rsquo;s seat watches ordeals with professional '
           'concern.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'challenge&rsquo;s one rule is 533a&rsquo;s vulgarity law hired as a '
           'referee, and its shared field is the tractate&rsquo;s only law under '
           'which the Union of chapter VI and the Council compete '
           'without treason: the Masoret marks the folio as load-bearing for '
           'any chronicle of detente.</p>',
 'h1': 'The Wager',
 'hagahah': 'The Adepts looked at the glass meadow, the marshalls, and the '
            'thousand years of protocol, and built a duel you can lose from a '
            'folding chair in a basement. The Order calls this decadence. The '
            'Adepts call it latency, and both are correct, which is why the '
            'shelf keeps them three spines apart.',
 'inner': '<p><span class="lemma">A field of battle agreed.</span> The '
          'contest&rsquo;s plain sense: the form&rsquo;s law is almost entirely '
          'procedural &mdash; agreement, stakes, witness &mdash; because its '
          'engine is borrowed whole from Middot: the extended race to a target, '
          'the extended-and-resisted grind of skill on skill. What the '
          'agreement adds is jurisdiction: a contest is a duel because both '
          'said so beforehand, and the saying is what lets the loser lose '
          'without feud, which is the entire technology.</p>\n'
          '        <p><span class="lemma">The first to yield loses.</span> The '
          'ordeal&rsquo;s plain sense: the contest of endurance inverts the '
          'ladder of 409a &mdash; no attack, no defense, only the fourth rung '
          'shared equally and the will measured against it. The harm is real by '
          'law, not flavor: the ledger fills as it would in any fight, and the '
          'form&rsquo;s honesty is exactly that its price cannot be staged. '
          'What it measures &mdash; the disputants opposite take the question '
          '&mdash; is the one thing certamen&rsquo;s bloodless circle '
          'structurally cannot.</p>\n'
          '        <p><span class="lemma">Sheds temporary will from its '
          'losers.</span> The flame war&rsquo;s plain sense, filed without the '
          'smirk it invites: the online duel is fought in social and '
          'intellectual feats, and its wound is composure &mdash; temporary '
          'will burned away by the argument lost in public &mdash; which its '
          'veterans insist is a real organ, and the trait&rsquo;s own law, 328, '
          'wanting, will back them. The form is the contest miniaturized and '
          'made ambient: no stakes declared, no seconds seated, and therefore, '
          'note the drafters&rsquo; quiet warning, no way to lose '
          'cleanly.</p>\n'
          '        <p><span class="lemma">A point of essence apiece.</span> The '
          'core war&rsquo;s plain sense: the form is an economy before it is a '
          'fight &mdash; Quintessence banked, spent on armament, won whole by '
          'the breach &mdash; and its arithmetic is the count&rsquo;s law '
          'compounded: extended and resisted, a fixed target, failure priced in '
          'dead viruses and bruises, the botch in blood. The five-and-twenty is '
          'the longest race in the book, and deliberately: the form rewards '
          'logistics and nerve across hours, which is the Adepts&rsquo; '
          'definition of a soul laid bare.</p>\n'
          '        <p><span class="lemma">Under one rule only.</span> The '
          'challenge&rsquo;s plain sense: a duel of repair needs almost no law '
          'because reality supplies the scoring &mdash; the block either '
          'heals or does not &mdash; and the single printed rule guards the '
          'only thing the form could break: the Sleepers it serves. Vulgar '
          'display before witnesses costs a goal; the backlash that hurts the '
          'watchers forfeits everything; and the rule&rsquo;s shape confesses '
          'the form&rsquo;s deepest premise, that the audience is not '
          'spectators but the stake itself.</p>\n'
          '        <p><span class="lemma">Alone of every form.</span> The '
          'shared field&rsquo;s plain sense: mystic and Technocrat cannot share '
          'a certamen circle &mdash; the forms, the realm, the paradigm are '
          'partisan to their bones &mdash; but a mended street is a mended '
          'street under every paradigm at once, so the challenge alone gives '
          'the war a venue where winning does not require the other side&rsquo;s '
          'world to be false. The clause is small and the setting&rsquo;s '
          'whole endgame is folded inside it, which the margin has already '
          'marked.</p>',
 'inner_head': 'On the Fields<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; form by form, stake by stake</span>',
 'name': 'The Wager',
 'outer': '<p><span class="lemma">Duel or pathology.</span> The ordeal&rsquo;s '
          'trial. <span class="voice">Some say</span> the ordeal is the oldest '
          'and honestest form on the page: pain is the one currency no rhetoric '
          'inflates, every culture&rsquo;s courts once used it, and two rivals '
          'who share a suffering end knowing something true about each other '
          'that no contest of wit reveals. <span class="voice">Others '
          'say</span> the tractate&rsquo;s own physicians have named this '
          'romance before: a form whose engine is self-harm, dressed as '
          'jurisprudence, is jhor&rsquo;s waiting room &mdash; and the seat '
          'that watches death&rsquo;s students for exactly this drift, 156b, '
          'would read a chronicle of escalating ordeals as a case file, not a '
          'rivalry. The first school answers that danger is not disease, and '
          'that the form&rsquo;s consent, witnesses, and yield-point are '
          'precisely what distinguish ordeal from compulsion. The second '
          'grants the distinction and keeps the watch, which is, the tractate '
          'notes, exactly what 156b&rsquo;s law would prescribe: the line is '
          'real, and it is patrolled, and the patrol is not optional.</p>\n'
          '        <p><span class="lemma">Whether the judge exists.</span> The '
          'challenge&rsquo;s trial, and the verso&rsquo;s deepest. The form '
          'names reality itself as arbiter &mdash; the worthier faction shown '
          'by the world&rsquo;s own mending. <span class="voice">Some '
          'say</span> the judge is a poet&rsquo;s fiction: the world does not '
          'score, outcomes are tallied by whoever set the goals, and the '
          'challenge is two propagandas sharing a soup kitchen &mdash; '
          'better than a war, worse than honesty. <span class="voice">Others '
          'say</span> the setting is not neutral on this: in a cosmos where '
          'consensus is the substance of the real, a street that stays mended '
          'is a verdict in the fullest sense &mdash; belief moved, the '
          'paradigm&rsquo;s needle bent a degree &mdash; and the form is the '
          'only duel whose outcome is literally made of the thing the whole '
          'war is about. The first school keeps the table honest; the second has read folio 62; and the tractate, having since bound that folio, files the question where '
          'the setting filed it &mdash; at the top of the mountain, '
          'unresolved. <span class="kw">TEYKU</span> &mdash; and mend the '
          'street regardless.</p>\n'
          '        <p><span class="lemma">Rivalry into currency.</span> A last '
          'difficulty, economic. <span class="voice">Some say</span> the '
          'verso&rsquo;s ladder proves the setting&rsquo;s optimism: given '
          'forms enough, even hatred becomes fuel, and the challenge sits at '
          'the ladder&rsquo;s top as rivalry&rsquo;s highest refinement. '
          '<span class="voice">Others say</span> read the ladder downward: '
          'every form on this page is the war continued by other means, the '
          'challenge merely launders enmity through charity, and the '
          'street&rsquo;s mending is real while the peace is counterfeit. '
          'The tractate answers from its own binding: counterfeit peace that '
          'mends streets is the Council&rsquo;s founding technology, folio '
          '2a, and the setting has run on it for five hundred years. Whether '
          'that is optimism or indictment is the reader&rsquo;s to rule &mdash; '
          'and the chapter, closing, declines to rule it for her.</p>',
 'outer_head': 'The Seconds<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the ordeal, the judge, and the '
               'currency</span>',
 'rubric': 'contests, ordeals, and the challenge',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of the wager &middot; the duels beyond the circle as law',
 'title': 'Tractate Aliyah · Folio 430b — The Wager: the duels beyond the circle',
 'type': 'daf'}
