# Folio 430a - Duels, Old Form. Old-form certamen per the wod-llm-wiki
# magickal-duels page (M20 pp.432-433) and certamen page (institution).
FOLIO = {'bottom': '<p><span class="lemma">On staging the circle.</span> The duel is theater by '
           'design &mdash; the realm, the marshalls, the audience are printed in the '
           'law &mdash; so stage it as theater: let the manifested spheres be described '
           'in each duelist&rsquo;s paradigm, let the crowd react, let the marshall be '
           'a character with rulings and a temper. A certamen resolved as bare dice '
           'wastes the one combat form the books built entirely out of spectacle.</p>\n'
           '        <p><span class="lemma">On the stakes and the seconds.</span> '
           'Certamen is 384b&rsquo;s stakes clause at its most formal: the wager is '
           'declared before the circle is drawn, witnessed, and enforced by parties '
           'whose whole office is fairness. Use the form for disputes the chronicle '
           'needs settled without bodies &mdash; precedence, insult, custody of a '
           'Node&rsquo;s tithe &mdash; and let the loser lose the stake, exactly and '
           'only: a duel whose outcome gets relitigated afterward teaches the table '
           'that the form is decoration.</p>\n'
           '        <p><span class="lemma">On the expanded manual.</span> The '
           'supplementary tactics &mdash; blocks and disarms, the locus dodged, '
           'spheres reshaped mid-match, the grudge fought to the pain &mdash; are an '
           'optional arms race, and their honest use is symmetrical: introduce them '
           'as the circuit&rsquo;s living meta, known to duelists who follow the '
           'form, opaque to the challenger who learned certamen from a book. The '
           'veteran&rsquo;s edge should be lore, and lore is earnable.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on theater, wagers, and '
                'the meta</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The old duel is fought in a circle beyond the '
           'world,</span> for its energies are vulgar past any street&rsquo;s '
           'tolerance, and the earthly match is undone by the court itself in '
           'displays the books call theatrical.<sup>a</sup> The form requires the '
           'rivals, the circle, one to three marshalls to keep protocol, and '
           'customarily a crowd. Each duelist pours her whole store of Quintessence '
           'into a single burning <span class="term">Locus</span>, and the duel is '
           'fought against the Locus, never the mage; each manifests one glowing '
           'sphere for every dot of Arete &mdash; excellence made visible, not '
           'Sphere-lore &mdash; and wields two at a time, a <span '
           'class="term">Gladius</span> to strike and an <span '
           'class="term">Aegis</span> to ward, their shapes cosmetic and their '
           'Traits real.<sup>b</sup> Each turn the duelist chooses her footing '
           '&mdash; quickness with Arete, wits with Arete, or bare will &mdash; and '
           'strikes by wits joined to the Gladius&rsquo;s Sphere against a wall of '
           'the defender&rsquo;s Aegis and three; every success drains a point of '
           'the defender&rsquo;s Locus into the attacker&rsquo;s, and Prime soaks at '
           'six.<sup>c</sup> The first to empty the rival&rsquo;s Locus wins the '
           'stake. And one art is banished outright: Time bent to slow the opponent '
           'forfeits the duel on the spot.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear a match, called as the marshalls would. Two Hermetics, an insult '
           'three decades old, a circle cut in a Horizon Realm&rsquo;s glass '
           'meadow. She manifests five spheres to his four &mdash; Arete made '
           'visible, and the crowd counts aloud &mdash; and shapes a heron for her '
           'Gladius, a ring of hands for her Aegis; his are a hammer and a wall of '
           'text. First turn: she takes her footing by wits, strikes '
           'heron-into-wall, three successes; his Prime turns one at the soak, and '
           'two points of his hoarded Quintessence stream across the circle into '
           'her Locus, the crowd reading the flow like a scoreboard. He answers '
           'with the hammer and takes one back. So it runs, turn over turn, wealth '
           'bleeding between suns until one Locus gutters &mdash; and no body has '
           'been touched, which is the entire invention. The disputants around '
           'this text hold what the form measures, and whether its bloodlessness '
           'was ever the whole truth.</p>',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'duels that need no circle wait overleaf.',
 'folio': '430A',
 'glossL': '<p><span class="mark">a</span> On old-form certamen &mdash; the Horizon '
           'circles, the marshalls, the vulgarity of its energies &mdash; see M20, '
           'the systems chapter, folios 432&ndash;433, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On the Locus, the spheres per '
           'Arete dot, and the Gladius and Aegis, see the same pages.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the turn &mdash; '
           'the chosen footing, the strike against Aegis-and-three, the drain, and '
           'the Prime soak &mdash; see the same; the expanded tactics are the Book '
           'of Secrets&rsquo; optional manual, folios 112&ndash;115 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the Time ban '
           'and its automatic forfeit, see folio 433; on the institution&rsquo;s '
           'law, its inventors, and its precedents, see the Order&rsquo;s own '
           'literature &mdash; folio 143 of this binding, wanting, will try '
           'them.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The institution behind the form '
           '&mdash; devised by Bonisagus and Tremere, governed by the Code&rsquo;s '
           'peripheral rulings, contested by reformers who would retire it &mdash; '
           'is folio 143&rsquo;s brief, wanting; this page keeps only the arena. '
           'The Masoret notes the elder custom that archmagi have fought such '
           'duels to the death, and files it under the dispute opposite.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'Locus&rsquo;s currency is 520b&rsquo;s well economics staked on a '
           'table: hoarded Quintessence made visible, wagered, and drained. The '
           'duel is the only law in the binding where wealth is literally the '
           'health track.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Time '
           'ban is 522a&rsquo;s power acknowledged by prohibition &mdash; the '
           'one Sphere the form cannot price, so the form forbids it; the '
           'duelists&rsquo; fear of that seat, 409b&rsquo;s margin already '
           'noted, is here written into law.</p>',
 'h1': 'Duels, Old Form',
 'hagahah': 'Two mages enter; one paradigm leaves, briefly. The crowd goes home '
            'arguing about the heron, the loser goes home poor, and the winner '
            'goes home knowing that five glowing spheres told every rival in '
            'the realm exactly how tall she stands. Intelligence work, with '
            'applause.',
 'inner': '<p><span class="lemma">Against the Locus, never the mage.</span> The '
          'form&rsquo;s plain sense and its whole invention: the duel relocates '
          'harm from the body to the wealth, so rivals may fight at full art and '
          'both walk home. The blow against the person is the form&rsquo;s one '
          'unforgivable foul &mdash; the marshall halts, awards, charges, and '
          'bans &mdash; and the severity is structural: the entire peace rests '
          'on the target being property, and the form defends its premise more '
          'fiercely than its contestants.</p>\n'
          '        <p><span class="lemma">One sphere for every dot of '
          'Arete.</span> The manifestation&rsquo;s plain sense: the count '
          'displays enlightenment itself, not learning &mdash; a master of many '
          'Spheres at modest Arete stands behind fewer lights than a young '
          'prodigy of pure will &mdash; and the display is information warfare '
          'before the first strike: the expanded manual&rsquo;s intimidation '
          'rules merely price what every witness already feels. Two wielded at '
          'a time is the form&rsquo;s discipline: whatever your height, you '
          'fight with a sword and a shield like everyone else.</p>\n'
          '        <p><span class="lemma">Their shapes cosmetic and their '
          'Traits real.</span> The aesthetic clause, plainly: the heron and the '
          'hammer are paradigm made visible, and the law beneath the pageantry '
          'is indifferent to it &mdash; a third-rank Gladius strikes at third '
          'rank whatever it resembles. The clause protects both halves: the '
          'duelist&rsquo;s style is sovereign, and the marshall&rsquo;s ruling '
          'is arithmetic. Every culture that keeps dueling forms invents this '
          'same separation, and the drafters knew whose genre they were '
          'writing in.</p>\n'
          '        <p><span class="lemma">Her footing each turn.</span> The '
          'initiative clause&rsquo;s plain sense: the duelist chooses her basis '
          '&mdash; body, mind, or will joined to excellence &mdash; and may '
          'choose anew each turn, which makes the order itself a layer of play '
          'absent from the street fight of 409a. The choice is '
          'characterization at mechanical speed: the duelist who opens on will '
          'and shifts to wits is telling the crowd a story, and the crowds of '
          'this form are fluent readers.</p>\n'
          '        <p><span class="lemma">One to three marshalls.</span> The '
          'office&rsquo;s plain sense: the marshall is the form&rsquo;s living '
          'constitution &mdash; protocol enforced, fouls called, the match '
          'halted and awarded where the law is breached &mdash; and the '
          'expanded manual&rsquo;s sneakier tactics all route through her '
          'discretion, which is the manual quietly admitting that a duel of '
          'pure rules would be gamed to death in a season. The office is also '
          'the form&rsquo;s best table role: a marshall with judgment and a '
          'history is worth three pages of tactics.</p>\n'
          '        <p><span class="lemma">Forfeits the duel on the spot.</span> '
          'The Time ban&rsquo;s plain sense: the form prices every art through '
          'one gate &mdash; the strike, the ward, the drain &mdash; and the '
          'Sphere that attacks the turn structure itself cannot pass through a '
          'gate made of turns. What cannot be priced must be banned, and the '
          'automatic forfeit, harsher than any difficulty, marks the '
          'form&rsquo;s honest limit: certamen is a game, games are made of '
          'time, and the mage who bends time has declined to play.</p>',
 'inner_head': 'On the Circle<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; locus, lights, and footing</span>',
 'name': 'Duels, Old Form',
 'outer': '<p><span class="lemma">What the form measures.</span> The measurement '
          'dispute, as the brief demands. <span class="voice">Some say</span> '
          'certamen is the Order&rsquo;s claim made flesh: greater command of '
          'the Spheres as the surest voice, tested under rules that strip away '
          'ambush, allies, and luck of terrain until only excellence remains '
          '&mdash; the duel is Arete&rsquo;s laboratory, and its rankings are '
          'the closest thing the Traditions have to an honest census of '
          'mastery. <span class="voice">Others say</span> the laboratory '
          'measures the laboratory: footing tactics, sphere-craft, the '
          'circuit&rsquo;s meta, nerve before a crowd &mdash; a specialized '
          'sport whose champions excel at certamen the way fencers excel at '
          'fencing, which is to say gloriously, expensively, and without proving anything '
          'about the war outside the circle. The first school points to the '
          'spheres-per-Arete law: the form counts enlightenment itself. The '
          'second points to the same law: it counts, and then the counting is '
          'gamed, as counts are &mdash; the expanded manual&rsquo;s own pages '
          'teach the concealing of one&rsquo;s height and the sudden '
          'manifesting of it mid-match, which is to say the census has '
          'learned to lie. The tractate observes that both schools show '
          'up to watch, and both bet.</p>\n'
          '        <p><span class="lemma">Whether the bloodlessness was ever '
          'whole.</span> The legality dispute, inherited from the elder '
          'manuscripts. The modern form is bloodless by construction; the old '
          'testimony records archmagi who fought such duels to the death, and '
          'the grudge variant of the expanded manual &mdash; the match to the '
          'pain, will staked after wealth &mdash; still lets a duel reach '
          'unconsciousness and a broken self. <span class="voice">Some '
          'say</span> the lethal duel is dead law: the Code&rsquo;s rulings '
          'fixed the parameters, the precedents that enforced service from the '
          'defeated were overturned, and what archmagi did in another age '
          'binds no circle now. <span class="voice">Others say</span> dead law '
          'with living roots: the form was built to channel exactly the '
          'violence it forbids, the reformers who would retire certamen argue '
          'it keeps might-makes-right alive in ceremonial dress, and the '
          'to-the-pain variant is the old blood showing through the new skin. '
          'Folio 143, wanting, is reserved the institution&rsquo;s full trial; '
          'this page keeps the arena and the doubt.</p>\n'
          '        <p><span class="lemma">Excellence made visible.</span> The '
          'last difficulty, the tractate&rsquo;s own: is a duel of pure display '
          'the Traditions at their best or their oldest vice? <span '
          'class="voice">Some say</span> best: two wills settling a quarrel '
          'with wealth and artistry under law, no bodies, no feud &mdash; the '
          'Council&rsquo;s whole project in miniature. <span '
          'class="voice">Others say</span> vice: the form converts standing '
          'into spectacle and spectacle back into standing, rewards exactly '
          'the aristocratic theater the young Traditions resent, and the '
          'Adepts of 164a &mdash; who settle their duels in server cores, '
          'overleaf &mdash; regard the glass meadow the way punks regard an '
          'opera house. The dispute is generational, which in this binding '
          'means permanent &mdash; and the verso, where the young '
          'Traditions&rsquo; own forms wait, is its continuation by other '
          'venues. <span class="kw">TEYKU</span> &mdash; the circle '
          'holds either way.</p>',
 'outer_head': 'The Marshalls<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the measure, the blood, and the '
               'opera</span>',
 'rubric': 'the circle, the locus, and the two lights',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of the old duel &middot; certamen as law',
 'title': 'Tractate Aliyah · Folio 430a — Duels, Old Form: the circle, the locus, and the two lights',
 'type': 'daf'}
