# Folio 435b - The Breaking (luach). Verso of Hazards: drowning,
# suffocation, and the breaking of things, per the wod-llm-wiki
# environmental-hazards page (M20 pp.439-441).
FOLIO = {'bottom': '<p><span class="lemma">On the clock underwater.</span> The breath ladder is '
           'a scene timer the table can feel: announce the Stamina&rsquo;s allowance '
           'when the water closes, count the will&rsquo;s extensions aloud, and let '
           'every turn past the limit land its automatic line where everyone can see '
           'the arithmetic. Drowning scenes run on dread, and dread runs on visible '
           'clocks; the chart is the clock, published.</p>\n'
           '        <p><span class="lemma">On breaking scenery honestly.</span> Post '
           'the toughness of anything the players will predictably hit: the door, the '
           'floor, the idol, the server rack. The ladder&rsquo;s two numbers &mdash; '
           'what a thing shrugs off, what it can absorb before failing &mdash; '
           'resolve nine-tenths of the how-do-I-smash-it questions before they are '
           'asked, and the tenth is a Matter working, which is 517&rsquo;s business '
           'and priced there.</p>\n'
           '        <p><span class="lemma">On the revival window.</span> The chart '
           'ends at the hardest adjudication in the book: the drowned body, the '
           'minutes passing, and the ranks of Life that reach further and further '
           'past the line. Rule the window before the chronicle needs it &mdash; '
           'session zero again, as ever &mdash; for the moment itself is the wrong '
           'time to discover the table disagrees about when dead is dead.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on clocks, scenery, and '
                'the window</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The slow harms keep their own charts.</span> The '
           'breath is measured by Stamina and extended by will; past its end the '
           'body pays a line a turn, unsoakable, and past the last line it dies '
           'within the turn &mdash; unless reached in time, by craft or by '
           'Life.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Stamina</th><th>The breath held</th><th>Provisions</th></tr>\n'
           '          <tr><td class="num">1</td><td>half a minute</td>'
           '<td rowspan="4">each point of Willpower spent adds half a minute; past '
           'the limit, one line a turn, automatic and beyond soak; the suffocated '
           'mend as the bruised do, the drowned sometimes as the cut; the '
           'healer&rsquo;s craft within minutes may call the body back, the third '
           'rank of Life within more, and the fifth past the brain&rsquo;s own '
           'surrender<sup>b</sup></td></tr>\n'
           '          <tr><td class="num">2</td><td>one minute</td></tr>\n'
           '          <tr><td class="num">4&ndash;5</td><td>some ten to fifteen '
           'minutes</td></tr>\n'
           '          <tr><td class="num">10</td><td>an hour, the legendary '
           'limit</td></tr>\n'
           '        </table>\n'
           '        <p class="noindent">And the things of the world break by two '
           'numbers: <span class="term">toughness</span>, the harm a substance '
           'shrugs point for point, and <span class="term">structure</span>, the '
           'ledger a thing keeps &mdash; exceeded once it fails, exceeded twice '
           'over it is destroyed. The arts that argue with structure itself '
           '&mdash; decay&rsquo;s, matter&rsquo;s, essence&rsquo;s &mdash; pass '
           'two points of toughness at the threshold, and the transmuter pays a '
           'success for every point when remaking a substance '
           'whole.<sup>c</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th class="num">Ladder</th><th>The stuff of the '
           'world</th></tr>\n'
           '          <tr><td class="num">1</td><td>the fragile: thin glass, '
           'cheap goods</td></tr>\n'
           '          <tr><td class="num">3&ndash;5</td><td>the household: doors, '
           'furnishings, machines</td></tr>\n'
           '          <tr><td class="num">6&ndash;9</td><td>the built: brick, '
           'timber, the city&rsquo;s bones</td></tr>\n'
           '          <tr><td class="num">10+</td><td>the fortified: vaults, '
           'engines of war</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence '
           'a chart that cannot be soaked? Come and hear the row&rsquo;s quiet '
           'theology: every other harm in the chapter argues with the body, and '
           'the body argues back &mdash; Stamina&rsquo;s vote, armor&rsquo;s, the '
           'iron shirt&rsquo;s. Suffocation argues with nothing; it is merely the '
           'world declining to provide, and against a withheld gift there is no '
           'defense, only a deadline. The breaking ladder is the same lesson for '
           'things: the harming arts of Entropy, Matter, and Prime thin a '
           'substance&rsquo;s toughness by two, for they argue at the depth the '
           'substance is made &mdash; and the commentaries hold what remains: the '
           'unsoakable&rsquo;s meaning, and where the mending arts&rsquo; reach '
           'honestly ends.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Tenth &middot; concluded',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Hazards, and the close of Strife: the chapter of violence '
             'ends underwater, where violence is beside the point.',
 'folio': '435B',
 'glossL': '<p><span class="mark">a</span> On drowning and suffocation &mdash; the '
           'Stamina ladder, the will&rsquo;s extensions, the automatic harm '
           '&mdash; see M20, the systems chapter, folios 440&ndash;441.</p>\n'
           '        <p><span class="mark">b</span> On resuscitation by craft '
           'within minutes and by Life&rsquo;s ranks beyond them, see folio 441; '
           'the rationing of the healer&rsquo;s art is 516b&rsquo;s law.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On toughness and '
           'structure, the failure and destruction thresholds, the '
           'harming-arts&rsquo; discount, and the transmuter&rsquo;s price of one '
           'success per point of toughness, see folios 439&ndash;440.</p>\n'
           '        <p class="drop"><span class="mark">d</span> The ladder&rsquo;s '
           'rungs are abridged here to their bands; the book&rsquo;s own chart '
           'grades them finely, and the Ein Mishpat trusts the reader to the '
           'source, per this binding&rsquo;s first law.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The breath ladder is the one '
           'chart in Strife where the will outbids the body twice &mdash; '
           'extending the breath, then refusing the panic &mdash; and 328, '
           'wanting, holds the trait&rsquo;s full account; the Masoret marks the '
           'row as that folio&rsquo;s best advertisement.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'toughness discount for the harming arts is the borderline of 514a '
           'and 517a made mechanical: the Spheres that argue with structure '
           'argue past its defenses, exactly as the wound taxonomy of 406b '
           'promised for flesh.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Strife '
           'closes here, and the Masoret takes the chapter&rsquo;s roll: the '
           'four rungs, the three doors, the empty hand and the complete way, '
           'the circle and the wager, the world&rsquo;s posted prices &mdash; '
           'eight sides of violence, every one deferring at its edge to the '
           'table, and the last word going to water, which needed no '
           'chapter.</p>',
 'h1': 'The Breaking',
 'hagahah': 'The chart&rsquo;s quietest row kills the most careful mages: water '
            'is patient, unsoakable, and everywhere, and it has never once '
            'read the vulgarity rules. The Void Engineers, who work where '
            'there is no water and no air either, are said to find the row '
            'nostalgic.',
 'inner': '<p><span class="lemma">Measured by Stamina and extended by '
          'will.</span> The ladder&rsquo;s plain sense: the breath is the '
          'body&rsquo;s allowance and the will&rsquo;s loan &mdash; half a '
          'minute per point lent &mdash; and the two-trait structure makes the '
          'drowning scene a portrait in miniature: what you are buys the '
          'first minutes, what you insist on buys the last ones. The ladder '
          'tops out at the legendary hour because the chart, like the trait '
          'scale of 385a, was drawn for humans; the things that wait longer '
          'underwater are other tractates&rsquo; business.</p>\n'
          '        <p><span class="lemma">Automatic and beyond soak.</span> The '
          'unsoakable&rsquo;s plain sense, and the chart&rsquo;s hardest '
          'clause: suffocation is the only harm in Strife that no trait '
          'answers, because it is not a blow but an absence &mdash; nothing '
          'strikes the drowning body; the world simply stops giving, and '
          'Stamina cannot soak a gift withheld. The clause&rsquo;s mercy is '
          'its bookkeeping: the harm mends like bruising once air returns, '
          'for the body forgives the debt the moment it is repaid.</p>\n'
          '        <p><span class="lemma">By craft or by Life.</span> The '
          'window&rsquo;s plain sense: the drowned are recoverable in rings '
          '&mdash; the medic&rsquo;s minutes, the third rank&rsquo;s longer '
          'reach, the fifth rank&rsquo;s reach past the brain&rsquo;s own '
          'quitting &mdash; and each ring outward raises the stakes of the '
          'question the Later Authorities post below: when is dead dead? The '
          'chart answers only in ranks and minutes; the answer in meaning '
          'belongs to 516b&rsquo;s rationed mercies and, past the last ring, '
          'to nobody in this binding at all.</p>\n'
          '        <p><span class="lemma">Toughness and structure.</span> The '
          'two numbers&rsquo; plain sense: a thing&rsquo;s toughness is a '
          'standing soak that never rolls &mdash; point for point, tireless '
          '&mdash; and its structure is a ledger like flesh keeps, with '
          'failure at one threshold and ruin at twice. The pairing gives '
          'objects exactly the dignity the system gives bodies, minus the '
          'dice: the world resists by what it is made of, and the door that '
          'holds three blows was always going to hold three blows.</p>\n'
          '        <p><span class="lemma">Exceeded once it fails.</span> The '
          'two thresholds&rsquo; plain sense: the thing whose ledger is '
          'exceeded stops working &mdash; the door ajar on one hinge, the '
          'engine seized &mdash; and the thing exceeded twice over stops '
          'being a thing. Between the thresholds lives the whole craft of '
          'repair, by tools and time or by Matter&rsquo;s arts at '
          '517&rsquo;s prices; past the second lives only replacement, and '
          'the distinction gives the chronicle&rsquo;s vandals and defenders '
          'alike a vocabulary the fiction can honor.</p>\n'
          '        <p><span class="lemma">Thin a substance&rsquo;s toughness by '
          'two.</span> The discount&rsquo;s plain sense: the arts that argue '
          'with structure itself &mdash; decay, transmutation, the '
          'pattern-arts of matter and essence &mdash; bypass what mere force '
          'must batter, two points of toughness waived at the threshold. The '
          'transmuter&rsquo;s full price &mdash; a success per point of '
          'toughness to remake a substance whole &mdash; closes the loop: '
          'the harder the world made a thing, the more argument its unmaking '
          'costs, which is the Consensus&rsquo;s masonry stated as '
          'arithmetic.</p>',
 'inner_head': 'On the Charts<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; breath, toughness, and the '
               'window</span>',
 'name': 'The Breaking',
 'outer': '<p><span class="lemma">The harm no trait answers.</span> The '
          'unsoakable dispute. <span class="voice">Some say</span> the clause '
          'breaks the system&rsquo;s own covenant: every harm in the book '
          'meets some defense &mdash; that is what traits are &mdash; and a '
          'damage no roll can touch is the designers reaching past the dice '
          'to guarantee an outcome, which the Golden Rule permits but the '
          'chapter of measures should blush at. <span class="voice">Others '
          'say</span> the covenant was never harm-meets-defense but '
          'doubt-meets-dice, per 385a&rsquo;s drama clause: there is no doubt '
          'about what airlessness does, only about how long the swimmer '
          'lasts and who reaches her &mdash; and the chart spends its dice '
          'exactly there, on the breath and the rescue, where the story '
          'actually lives. The second school reads the whole luach form in '
          'this row: the certainties charted, the doubts rolled, and the '
          'line between them drawn with unusual care.</p>\n'
          '        <p><span class="lemma">Where the mending arts end.</span> '
          'The window dispute, the chapter&rsquo;s last. The chart lets the '
          'fifth rank of Life reach past the brain&rsquo;s surrender, and the '
          'reader who has followed this binding knows what waits behind the '
          'clause: the question of what, exactly, comes back. <span '
          'class="voice">Some say</span> the rank speaks plainly &mdash; the '
          'pattern restored is the person restored, and the setting&rsquo;s '
          'materialism about bodies is one of its quiet mercies: no soul '
          'clause, no horror rider, just medicine at a depth the Consensus '
          'has not approved yet. <span class="voice">Others say</span> the '
          'binding&rsquo;s own shelf argues back: an entire sibling tractate '
          'stands three spines away on the premise that what returns is not '
          'always what left, and the healer of the fifth rank who has never '
          'wondered has not read her neighbors. The dispute cannot be '
          'settled from this folio, and the tractate declines to pretend '
          'otherwise; it notes only that the window&rsquo;s rings are '
          'printed in minutes, and that every tradition on the shelf agrees '
          'the minutes matter. <span class="kw">TEYKU</span> &mdash; and so '
          'Strife rests, at the water line.</p>\n'
          '        <p><span class="lemma">Abridged to their bands.</span> A '
          'closing difficulty of form, raised by the gloss&rsquo;s own '
          'confession: this chart compresses the book&rsquo;s fine-grained '
          'ladder into bands, where the recto transcribed its rows entire. '
          '<span class="voice">Some say</span> the compression breaks the '
          'luach&rsquo;s young covenant: a chart folio exists to be the '
          'reference, and a reference that sends the reader back to the '
          'source for the middle rungs is a daf wearing a table&rsquo;s '
          'clothes. <span class="voice">Others say</span> the covenant was '
          'never transcription: the binding&rsquo;s first law keeps the '
          'source&rsquo;s text in the source, the Ein Mishpat cites the '
          'folio where the full ladder lives, and the bands preserve exactly '
          'what the table needs at speed &mdash; which tier of the world is '
          'being hit, and how hard that tier hits back. The tractate rules '
          'for the bands and records the rule for the luachs to come: '
          'restate the structure, cite the grain, and let the book keep '
          'what the book does best.</p>',
 'outer_head': 'The Assessors<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the unsoakable, the window, and the '
               'bands</span>',
 'rubric': 'breath, toughness, and the window',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, concluded '
             '&middot; of the breaking &middot; the slow harms as chart',
 'title': 'Tractate Aliyah · Folio 435b — The Breaking: breath, toughness, and the window',
 'type': 'luach'}
