# Folio 435a - Hazards (luach; the chart-folio proof). The world's own
# violence, per the wod-llm-wiki environmental-hazards page
# (M20 pp.435-439).
FOLIO = {'bottom': '<p><span class="lemma">On the third combatant.</span> The chart is the '
           'Storyteller&rsquo;s ally in every fight scene worth keeping: the burning '
           'floor, the live rail, the long drop are combatants that need no stats and '
           'take no sides, and a brawl staged among them is twice the scene at no '
           'added bookkeeping. Read the terrain rows before staging violence, and let '
           'the environment make the arguments the enemies are too busy to make.</p>\n'
           '        <p><span class="lemma">On what the chart omits.</span> Poisons, '
           'drugs, and disease are kept by the book in the same chapter and cut from '
           'this folio by its standing law &mdash; their ladders are long, their '
           'flavors many, and the gloss opposite says where they live. The cut is '
           'jurisdictional, not judgmental: the slow harms belong to scenes the '
           'chart&rsquo;s fast harms would only crowd.</p>\n'
           '        <p><span class="lemma">On the sphere-dodge.</span> The optional '
           'metaphysical dodge &mdash; the adept of the right Spheres reading the '
           'blast a half-second early &mdash; is the rare option that flatters '
           'mastery without armoring it: half damage on a success, nothing on five, '
           'never against the blast that levels the building. Allow it, describe it '
           'in the paradigm&rsquo;s own tongue, and keep the printed ceiling; the '
           'genre needs its close calls more than its immunities.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on terrain, cuts, and '
                'close calls</span>',
 'center': '<p class="noindent"><span class="dropcap">T</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The world needs no Sphere to hurt you.</span> The '
           'harms that follow ask no attack roll and hold no grudge; they are priced '
           'by kind and measure, as the chart provides, and the ledger of 406 '
           'receives their marks like any blow&rsquo;s.<sup>a</sup></p>\n'
           '        <table class="luach">\n'
           '          <tr><th>Hazard</th><th>Measure</th><th>Kind</th><th>Provisions</th></tr>\n'
           '          <tr><td><span class="term">Fire</span></td>'
           '<td>one to three lines a turn, by the blaze&rsquo;s size</td>'
           '<td>the third ink</td>'
           '<td>flame-proofed cloth halves the burning and nothing else; metal armor '
           'conducts and counts for nothing; the great fire is a well the third rank '
           'of Prime may draw from<sup>b</sup></td></tr>\n'
           '          <tr><td><span class="term">Explosion</span></td>'
           '<td>a pool of the charge&rsquo;s power, rolled against six &mdash; four '
           'for the fireball &mdash; full within the blast&rsquo;s area, one success '
           'shed per yard beyond</td>'
           '<td>bruising or cutting; the fiery and the catastrophic, third ink</td>'
           '<td>cover eats successes by its substance&rsquo;s toughness, then shrapnel '
           'takes its cut; going prone sheds two, save against fireballs; armor eats '
           'the cutting kind point for point and none of the concussion<sup>c</sup></td></tr>\n'
           '          <tr><td><span class="term">Electrocution</span></td>'
           '<td>by the source: the contained charge stings, the mains and the sky '
           'kill</td>'
           '<td>bruising from batteries; cutting from the grid</td>'
           '<td>each line taken stuns a turn; the grip of the current is broken only '
           'by main strength against a wall of nine; the shock that fells may maim '
           'past healing<sup>d</sup></td></tr>\n'
           '          <tr><td><span class="term">The fall</span></td>'
           '<td>one die per ten feet, to a hundred; past a hundred, ten dice and no '
           'more</td>'
           '<td>bruising near the ground; cutting from the true heights; the sharp '
           'landing, third ink</td>'
           '<td>armor counts half against the ground, which respects no '
           'tailor</td></tr>\n'
           '          <tr><td><span class="term">The ram</span></td>'
           '<td>one die per ten feet of speed at the meeting</td>'
           '<td>bruising, mostly</td>'
           '<td>the harder body adds a line when its substance beats the '
           'victim&rsquo;s Stamina; the thrown thing sheds dice with distance unless '
           'it drives itself</td></tr>\n'
           '        </table>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why does '
           'a chapter of strife end at a chart of weather? Come and hear: because '
           'the world outfights everyone. The enemies of chapter X roll dice; the '
           'fire does not, the fall does not, the current does not &mdash; their '
           'harm is automatic, their patience infinite, and their law is exactly '
           'this page. The fighter who has learned the four rungs and the three '
           'doors learns here that the deadliest things in the setting never took '
           'initiative in their lives. The commentaries hold the rows&rsquo; '
           'edges, and the one dispute the brief demands: why the house fire and '
           'the fireball differ in law.</p>',
 'center_w': '44%',
 'chapter': 'Chapter the Tenth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'first luach of the binding: the chart is the Text, and the '
             'commentaries surround it as they surround any law. The slow harms '
             'wait overleaf.',
 'folio': '435A',
 'glossL': '<p><span class="mark">a</span> On the environmental hazards generally, '
           'see M20, the systems chapter, folios 435&ndash;441, whence this page '
           'takes its number; the harms are many other ways to die, as the text '
           'has it, restated here as chart.</p>\n'
           '        <p><span class="mark">b</span> On fire&rsquo;s sizes, its '
           'aggravated burning, and the Prime draw, see folios 435&ndash;436.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On blast areas, '
           'blast power, cover, and the optional sphere-dodge, see folios '
           '436&ndash;437; demolitions as a craft is the same page&rsquo;s.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On electrocution, '
           'the fall, and the ram, see folios 437&ndash;439; on the poisons, '
           'drugs, and diseases this folio cuts, see the chapter&rsquo;s '
           'following pages, kept by the book and not by this binding.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Every row lands on 406&rsquo;s '
           'ledger and heals by 406b&rsquo;s calendars; the fire&rsquo;s third '
           'ink is the same ink the fangs of the sibling tractates write in, '
           'which the crossover chronicles should note before staging '
           'anything ambitious near a gas main.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'terrain walls of 409a &mdash; rough weather and ground raising '
           'difficulty by one to three &mdash; are this chart&rsquo;s mild '
           'cousins, and the Storyteller&rsquo;s counsel below treats them as '
           'one family.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'fireball&rsquo;s law is 515a&rsquo;s: Forces harms by its own '
           'measures, and the dispute opposite is the border between that '
           'folio and this one, surveyed at last.</p>',
 'h1': 'Hazards',
 'hagahah': 'Gravity is the Consensus&rsquo;s oldest enforcer, and it has never '
            'once been bribed. The Adepts have petitioned it, the Etherites '
            'have appealed it, and the Sons of Ether maintain the appeal is '
            'still pending, which is what the cast on the presenting '
            'author&rsquo;s arm was about.',
 'inner': '<p><span class="lemma">No attack roll and no grudge.</span> The '
          'chart&rsquo;s plain sense, and its one governing difference: '
          'hazard harm is automatic where combat harm is contested &mdash; '
          'the fire does not roll to hit, the fall cannot be parried, and '
          'defense against the world is positioning, not reaction. The '
          'chart&rsquo;s numbers are therefore prices, not odds, and the '
          'reader should feel the temperature change from the recto folios: '
          'here the only die that matters is the soak, where any soak is '
          'allowed at all.</p>\n'
          '        <p><span class="lemma">By the blaze&rsquo;s size.</span> The '
          'fire row&rsquo;s plain sense: the burning scales one to three lines '
          'a turn with the fire&rsquo;s reach, automatic each turn of contact, '
          'and the kind is the third ink because fire argues with the Pattern '
          'itself &mdash; the same depth-test the coroners of 406b '
          'established. The armor clauses are the row&rsquo;s realism: cloth '
          'made for flame halves the count, and the knight&rsquo;s steel, '
          'which conducts, is a cooking vessel.</p>\n'
          '        <p><span class="lemma">One success shed per yard.</span> '
          'The blast&rsquo;s plain sense: the explosion is a pool with '
          'geometry &mdash; full force within its area, decaying by the yard '
          'beyond &mdash; and every defense on the row is geometry too: cover '
          'interposes substance, proneness shrinks the target, and distance '
          'is the only armor that eats concussion. The fireball&rsquo;s '
          'easier wall is the row&rsquo;s one flourish: flame fills its '
          'space more faithfully than shock, and the chart prices the '
          'physics without a lecture.</p>\n'
          '        <p><span class="lemma">Stuns a turn for each line.</span> '
          'The current&rsquo;s plain sense: electricity&rsquo;s signature is '
          'seizure &mdash; the body locked while the harm continues &mdash; '
          'and the row&rsquo;s two clauses build its particular horror: the '
          'stun that outlasts the shock, and the grip that must be broken by '
          'strength against the chart&rsquo;s hardest wall. The permanent '
          'maiming of the felling shock is the chart&rsquo;s only '
          'open-ended price, and rightly: the grid is the one hazard on '
          'this page the modern Consensus built for itself.</p>\n'
          '        <p><span class="lemma">Cover eats successes by its '
          'substance.</span> The interposition&rsquo;s plain sense, and the '
          'chart&rsquo;s handshake with its verso: cover absorbs the blast by '
          'the toughness-and-structure the overleaf charts for everything '
          '&mdash; the oak table eats what an oak table can, then splinters '
          'into the shrapnel clause &mdash; so the two sides of this folio are '
          'one system read from opposite ends: what the world does to bodies, '
          'and what bodies can put between themselves and the world.</p>\n'
          '        <p><span class="lemma">The demolisher&rsquo;s craft.</span> '
          'A row&rsquo;s footnote worth its own lemma: the building, analyzing, '
          'and defusing of charges is a learned Knowledge rolled on the usual '
          'hands, and the books&rsquo; counsel on botching it is one word long '
          'and correct. The craft&rsquo;s presence on the chart matters: the '
          'explosion is the single row a character can author, and the law '
          'treats authorship as expertise, not as a genre right.</p>\n'
          '        <p><span class="lemma">Ten dice and no more.</span> The '
          'fall&rsquo;s plain sense, with its famous ceiling: the dice climb '
          'with the height until the body outruns its own harm &mdash; '
          'terminal, in both senses &mdash; and past a hundred feet the '
          'chart caps the pool and changes the ink, for the long fall kills '
          'by arrangement, not bruising. The half-armor clause closes the '
          'row: the ground is the one attacker that strikes everywhere at '
          'once, and no suit covers everywhere.</p>',
 'inner_head': 'On the Rows<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; row by row, edge by edge</span>',
 'name': 'Hazards',
 'outer': '<p><span class="lemma">The house fire and the fireball.</span> The '
          'border dispute, surveyed as the brief demands. Both burn by this '
          'chart&rsquo;s row; only one answers to 533a. <span '
          'class="voice">Some say</span> the difference is merely '
          'procedural: harm is harm, the fireball&rsquo;s vulgarity taxes '
          'its caster and not its victim, and the chart&rsquo;s indifference '
          '&mdash; the same three lines a turn whoever lit the match &mdash; '
          'proves the law sees one fire, not two. <span class="voice">Others '
          'say</span> the indifference is the finding: the chart prices what '
          'fire does, and 533a prices what the fire <span '
          'class="aside">is</span> &mdash; the house fire is the '
          'Consensus&rsquo;s own weather, the conjured flame is an argument '
          'against the world wearing weather&rsquo;s clothes, and the victim '
          'burns identically because the world, having been argued into the '
          'flame, keeps its side of every bargain it is forced to make. The '
          'second reading is the setting&rsquo;s, and the tractate notes its '
          'elegance: magick&rsquo;s products are real precisely because the '
          'court charged for them &mdash; the fee is the receipt, and the '
          'arsonist of either kind answers afterward to the same chart, the '
          'same calendars, and the same coroners.</p>\n'
          '        <p><span class="lemma">Automatic, and therefore '
          'what?</span> The design dispute. <span class="voice">Some '
          'say</span> the chart&rsquo;s automatic harm is the system at its '
          'most honest: no drama clause, no spotlight economics, just the '
          'world&rsquo;s prices posted &mdash; and the honesty is the '
          'horror, for the genre&rsquo;s truest dread is indifference. '
          '<span class="voice">Others say</span> the chart is the drama '
          'clause fulfilled, not suspended: nobody rolls for the fire '
          'because the fire is never in doubt &mdash; the doubt, and '
          'therefore the dice, belong entirely to the people fleeing it, '
          'and a chart of fixed prices is what lets the Storyteller stage '
          'an inferno without refereeing one. The schools converge on '
          'identical tables, as this chapter&rsquo;s schools do, and the '
          'tractate files the convergence as evidence that the luach form '
          'itself is sound: a page can be all prices and still be all '
          'story &mdash; the fire&rsquo;s row has no drama in it, and every '
          'scene it appears in is nothing else.</p>\n'
          '        <p><span class="lemma">The chart as a form.</span> The '
          'last difficulty is the folio&rsquo;s own: may a tractate&rsquo;s '
          'center be a table? The precedent is the printed page&rsquo;s own '
          '&mdash; the old editions set their diagrams mid-text and wrapped '
          'the commentary around them &mdash; and the objection is the '
          'purist&rsquo;s: law is argument, a chart argues nothing at all, and '
          'a binding that opens its arms to charts will end its days as an '
          'almanac with footnotes. <span '
          'class="voice">Some say</span> exactly so, and welcome: half of '
          'M20 is charts, and a tractate that cannot hold a table cannot '
          'hold its source, whatever else it holds. <span '
          'class="voice">Others say</span> the '
          'commentaries are the answer standing right here: the chart '
          'states, the flows dispute, and the form is only the '
          'Mishnah&rsquo;s terseness taken to its limit. The reader holding '
          'this page is holding the ruling: if the commentary she is reading '
          'has argued with a table and lost nothing by it, the form works, '
          'and the folios of making, chapter VIII, wanting, may batch against '
          'this proof as the dafs batched against theirs. <span '
          'class="kw">TEYKU</span> &mdash; but the luach, evidently, '
          'builds.</p>',
 'outer_head': 'The Surveyors<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the border, the silence, and the '
               'form</span>',
 'rubric': 'the world&rsquo;s prices, posted',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Tenth: Strife, continued '
             '&middot; of hazards &middot; the world&rsquo;s violence as chart',
 'title': 'Tractate Aliyah · Folio 435a — Hazards: the world’s prices, posted',
 'type': 'luach'}
