# Folio 500a - Casting. Chapter XI's procedure folio, per the wod-llm-wiki
# casting-magick page (M20 pp.499-547). The Book of Magick's engine as law.
FOLIO = {'bottom': '<p><span class="lemma">On the rhythm.</span> Rule, then roll, never reverse '
           '&mdash; 533a&rsquo;s procedure, cited here because casting is where tables '
           'break it: the vulgarity call, the modifier count, and the success target '
           'are all declared before the Arete dice leave the hand, and the working '
           'judged after its roll is a working judged by its outcome, which is exactly '
           'the corruption the court&rsquo;s law exists to prevent. Say the difficulty '
           'aloud; the saying is the adjudication.</p>\n'
           '        <p><span class="lemma">On judging the bystander.</span> The '
           'hypothetical average bystander is the table&rsquo;s most-consulted '
           'imaginary person, and session zero should give her a biography: what does '
           'this chronicle&rsquo;s street believe is possible? Post the answer with '
           '384b&rsquo;s constitution and the vulgarity calls become predictable, '
           'which is what players need them to be &mdash; the coincidence game is '
           'only fun when its referee is consistent.</p>\n'
           '        <p><span class="lemma">On the process rule.</span> The '
           'books&rsquo; second stance &mdash; the process used determines the '
           'result &mdash; is the Storyteller&rsquo;s shield against the '
           'coincidence-launderer: no mage hails a taxi into existence by calling it '
           'luck; she finds one with the arts of connection or builds one at '
           'creation&rsquo;s full price. Enforce the process and the clever players '
           'stay clever; wave it and the whole difficulty ladder quietly '
           'collapses.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on rhythm, bystanders, and '
                'process</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Every working walks four steps.</span> First, conceive '
           'the <span class="term">Effect</span>: what is willed, named by the Spheres '
           'it requires, and rated by the highest among them.<sup>a</sup> Second, ask '
           'whether her way of working believes it: the paradigm must permit, the '
           'practice must fit, the instruments must be in hand &mdash; and here the '
           'working is judged coincidental or vulgar by 533a&rsquo;s law, before any '
           'die is cast.<sup>b</sup> Third, roll Arete, once in a turn and for one '
           'working only, against a wall of the highest Sphere and three &mdash; four '
           'where the working is vulgar unseen, five where Sleepers watch &mdash; the '
           'wall never below three nor above ten, its movements capped at three in '
           'either direction; will spent beforehand buys its certain success, and '
           'essence spent eases the wall a step per point, to the Avatar&rsquo;s '
           'measure in a turn and three at most; the working improvised in '
           'haste pays one more upon the wall, as Strife already '
           'taught.<sup>c</sup> Fourth, read the count: '
           'the personal working asks one success, the working upon another at least '
           'two, the world-altering five and beyond; and the count is spent as damage '
           'or duration, never both, save where the successes are divided line by '
           'line.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear two castings, walked. A witch wants a pursuer&rsquo;s car stopped: '
           'entropy&rsquo;s second rank, her coin flipped and caught, and the engine '
           'throws a rod &mdash; possible things happen possibly, the wall stands at '
           'rank and three, and the world files the working under bad luck, no fee '
           'assessed. The same witch, cornered in the same parking garage with '
           'watchers on the ramp, pulls fire from her empty hand: forces and prime at '
           'the third and second, the wall at rank and five, and the fee assessed '
           'whether she succeeds or fails, for the offense is the impossibility '
           'witnessed, not the outcome. Note what changed between the castings: not '
           'her art, not her Spheres, not her need &mdash; only the story the world '
           'could tell itself afterward. The disputants around this text hold the '
           'engine&rsquo;s seams: the modifier pile, the speed of the work, and '
           'what the four steps assume about belief.</p>',
 'chapter': 'Chapter the Eleventh',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work '
             'in the form of a daf; no rules text is reproduced &middot; set in Abbess '
             '&amp; Goudy Old Style after the M20 interior &middot; the Book of '
             'Magick&rsquo;s engine, stated as law; the long workings and the answers '
             'to magick wait overleaf.',
 'folio': '500A',
 'glossL': '<p><span class="mark">a</span> On the four-step casting procedure, see '
           'M20, the Book of Magick, folios 499&ndash;501 and 528&ndash;547, whence '
           'this page takes its number; the Effect as the working&rsquo;s game name '
           'is the text&rsquo;s own usage, never the fiction&rsquo;s.</p>\n'
           '        <p><span class="mark">b</span> On focus, coincidence, and the '
           'bystander&rsquo;s judgment, see folios 528&ndash;534; the vulgarity law '
           'itself is 533a&rsquo;s and is cited, not restated.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the difficulty '
           'ladder, its floor and ceiling, the capped modifiers, and the spending '
           'of will and essence, see folios 503 and 535&ndash;537.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the feats ladder, '
           'the damage-or-duration chart, and the dividing of successes, see folios '
           '502&ndash;504 and 537&ndash;538.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is the hub the Sphere '
           'folios promised: every ladder of 512&ndash;522 is cast through this '
           'engine, every vulgarity call runs on 533a&rsquo;s law, and the witnesses '
           'are counted by 533b&rsquo;s census &mdash; including its rulings that '
           'the camera is no witness and the Night-Folk never are.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The mundane '
           'skill that eases the casting &mdash; a success of craft shaving the '
           'wall, a step to three at most &mdash; is Middot&rsquo;s complementary '
           'law working its third appearance in this binding; the Masoret files '
           'the design signature again.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The focus '
           'that step two consults &mdash; paradigm, practice, instruments '
           '&mdash; is chapter XI&rsquo;s remaining business: folios 567, 572, '
           'and 586, wanting, and the rotes of 607 with them.</p>',
 'h1': 'Casting',
 'hagahah': 'Four steps, of which the dice are the least interesting: the first '
            'step is philosophy, the second is theology, the fourth is '
            'consequences, and the third is the only one the Sleepers would '
            'recognize as a game.',
 'inner': '<p><span class="lemma">Named by the Spheres it requires.</span> The '
          'first step&rsquo;s plain sense: the working is designed before it is '
          'attempted &mdash; which arts, at which ranks, toward what end &mdash; '
          'and the highest rank sets the wall, for the working is as hard as its '
          'hardest part. One working may be cast in a turn and no more, whatever '
          'the mage&rsquo;s speed; the workings already running ride along, each '
          'pair of them raising every new wall by one, for attention is a '
          'budget the engine audits without mercy. The rote &mdash; the working '
          'already known &mdash; is the exception that proves nothing: familiar, '
          'unpriced, unlimited in number, it is still cast through this engine '
          'at these walls, only without the stranger&rsquo;s fumbling.</p>\n'
          '        <p><span class="lemma">Whether her way of working believes '
          'it.</span> The second step&rsquo;s plain sense, and the '
          'engine&rsquo;s heart: the Spheres are necessary and not sufficient '
          '&mdash; the working must be castable in the mage&rsquo;s own grammar, '
          'through instruments her paradigm honors, and the suit who cannot '
          'snap her fingers for fire can burn the same fire from a lighter and '
          'lacquer, the arts identical and the theater everything. The mage '
          'grown past her tools may still hold them for the eased wall the '
          'books grant to unneeded instruments, which is the engine quietly '
          'rewarding humility.</p>\n'
          '        <p><span class="lemma">The wall never below three nor above '
          'ten.</span> The ladder&rsquo;s plain sense: rank-and-three for the '
          'coincidental working, rank-and-four for the vulgar unseen, '
          'rank-and-five before witnesses &mdash; the three-step ladder is '
          '533a&rsquo;s whole jurisprudence priced, and the caps hold it '
          'honest: the modifiers may move the wall three steps at most, the '
          'wall past ten converts to extra successes owed, and the floor of '
          'three keeps even the gentlest working a working. The modifiers '
          'themselves are a catalogue the margin cites &mdash; tools '
          'personalized and unique, time taken, nodes near, targets distant '
          '&mdash; and the craft is remembering they net, not stack.</p>\n'
          '        <p><span class="lemma">One success, at least two, five and '
          'beyond.</span> The count&rsquo;s plain sense: the feats ladder '
          'prices ambition &mdash; the personal trick at one, the touch upon '
          'another at two (whence a single success harms no one), the mighty '
          'work at five, the outlandish at ten, the godlike past twenty '
          '&mdash; and the partial count is not nothing: half the asking '
          'yields the imperfect working, resumable at a stiffer wall, and '
          'three past the asking yields the extraordinary. The ladder is the '
          'engine&rsquo;s honesty about scale: nothing forbids the young '
          'mage the mighty work except arithmetic, patiently.</p>\n'
          '        <p><span class="lemma">As damage or duration, never '
          'both.</span> The spending&rsquo;s plain sense: the count converts '
          'to harm by the chart or to persistence by the chart, and the '
          'election is exclusive unless the successes are divided &mdash; '
          'each above the base buying a target, two lines of harm, or a '
          'step of time &mdash; whence the slow poisons and standing curses '
          'of the setting&rsquo;s folklore, their harm bought line by line '
          'across the calendar. The chart&rsquo;s far end is the '
          'Storyteller&rsquo;s, as far ends are.</p>',
 'inner_head': 'On the Engine<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; step by step, wall by wall</span>',
 'name': 'Casting',
 'outer': '<p><span class="lemma">The modifier pile.</span> The stacking dispute. '
          'The catalogue is long &mdash; the personalized tool, the unique '
          'tool, the tool unneeded, the resonance aligned, the essence spent, '
          'the time taken, the node&rsquo;s nearness, the research done &mdash; '
          'and every discount hunter at every table has assembled the '
          'full-course meal. <span class="voice">Some say</span> the net cap of '
          'three settles it: the engine invites the assembly and then taxes it '
          'into irrelevance, and the hunt is harmless character texture. <span '
          'class="voice">Others say</span> the cap settles the arithmetic and '
          'not the fiction: a mage who genuinely works with personalized, '
          'unique, beloved instruments at her node with time taken is not '
          'gaming the chart, she is <span class="aside">described</span> by it '
          '&mdash; the discounts exist to make the fiction&rsquo;s best '
          'practice the table&rsquo;s best practice, and the players they '
          'annoy are the ones treating focus as a coupon book. The schools '
          'agree on the cap and split on the sermon, which is this '
          'binding&rsquo;s oldest weather; the tractate notes only that every '
          'discount on the list is a way of caring about the work, and that '
          'the chart, read whole, is a theory of craftsmanship.</p>\n'
          '        <p><span class="lemma">The speed of the work.</span> The '
          'fast-against-ritual dispute. <span class="voice">Some say</span> '
          'the engine favors speed unfairly: one roll, one turn, the surcharge '
          'a single step of wall &mdash; while the ritual pays Paradox by the '
          'roll, botches catastrophically, and drinks hours &mdash; so the '
          'rational mage snap-casts everything and the setting&rsquo;s '
          'circles and sanctums are set dressing. <span class="voice">Others '
          'say</span> read the ceilings: the fast working caps at what one '
          'roll of a thin Arete hand can count, and everything the setting '
          'actually fears &mdash; the ward that holds a chantry, the healing '
          'past the third ink, the mighty and outlandish rungs &mdash; lives '
          'above that ceiling, purchasable only by the long form&rsquo;s '
          'gathered successes. The engine does not favor speed; it prices '
          'scope, and the circles are where scope is paid for. The verso '
          'keeps the long form&rsquo;s law, and the dispute continues '
          'there.</p>\n'
          '        <p><span class="lemma">What the four steps assume.</span> '
          'The last difficulty, the folio&rsquo;s deepest. The engine prices '
          'every working by what an imaginary average person would believe '
          '&mdash; and so builds the whole game&rsquo;s physics on a '
          'consensus it never lets the players inspect directly. <span '
          'class="voice">Some say</span> this is the design&rsquo;s glory: '
          'the difficulty ladder makes sociology into physics, the '
          'bystander&rsquo;s imagination is the real terrain of the war, and '
          'no other engine in the hobby prices belief at all. <span '
          'class="voice">Others say</span> the glory is load-bearing '
          'hand-waving: the bystander is whoever the Storyteller needs her '
          'to be tonight, the same working passes in one scene and bills in '
          'the next, and an engine whose central constant is adjudicated '
          'per-table is a style guide wearing physics&rsquo; clothes. The '
          'first school answers: so is reality, in this setting &mdash; that '
          'is the thesis. The second answers: then post the constant, per '
          'the Later Authorities, and stop calling it discovered. Both are '
          'right, which is why the counsel below exists. <span '
          'class="kw">TEYKU</span> &mdash; the bystander declines to '
          'testify.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the pile, the speed, and the '
               'bystander</span>',
 'rubric': 'the four steps, and the walls between',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick &middot; of casting &middot; the working as law',
 'title': 'Tractate Aliyah · Folio 500a — Casting: the four steps, and the walls between',
 'type': 'daf'}
