# Folio 500b - The Long Working. Verso of Casting: rituals, acting in
# concert, and countermagick, per the wod-llm-wiki casting-magick page
# (M20 pp.538-547).
FOLIO = {'bottom': '<p><span class="lemma">On staging the ritual.</span> The long working is a '
           'scene by construction &mdash; the clock of rolls, the rising walls, the '
           'Paradox accruing like interest &mdash; and it plays best when the table '
           'can see all three: name the successes gathered aloud, mark the fees '
           'pending, and let the interference clause make every knock at the door a '
           'threat. The ritual run as offstage bookkeeping wastes the most dramatic '
           'machine the Book of Magick owns.</p>\n'
           '        <p><span class="lemma">On the concert&rsquo;s casting call.</span> '
           'The requirements are strict on purpose &mdash; every collaborator '
           'schooled in every art of the working, present, and compatible &mdash; so '
           'treat the assembly as story: the specialist courted, the rival trusted at '
           'the circle&rsquo;s edge, the apprentice permitted her single automatic '
           'success and the terror of the shared botch. A concert whose members were '
           'gathered in one line of narration has spent the mechanic without buying '
           'the scene.</p>\n'
           '        <p><span class="lemma">On answering magick.</span> Post the '
           'countermagick options in session zero with the rest of the constitution: '
           'who at the table can counter, what the base art costs, and which of the '
           'optional answers &mdash; the guard, the reflection, the unweaving &mdash; '
           'this chronicle admits. The defenses are the setting&rsquo;s real arms '
           'race, and a table that discovers them mid-duel discovers them '
           'angrily.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on clocks, casting calls, '
                'and answers</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The working too great for a turn is gathered.</span> '
           'The ritual runs as the count&rsquo;s extended form, its rolls bounded by '
           'the caster&rsquo;s will and Arete together; the roll that fails gathers '
           'nothing and stiffens every wall after it by one; the roll that botches '
           'may be held together once &mdash; a turn, a point of will, a gathered '
           'success spent &mdash; and the second botch is disaster outright.<sup>a</sup> '
           'Every roll past the first accrues a point of the court&rsquo;s fee, '
           'forgiven if the working lands and joined to the wreck if it does not; '
           'the flesh works an hour per point of Stamina before the body itself is '
           'rolled; and the work disturbed demands the will at a high wall or '
           'collapses.<sup>b</sup> Mages may work in concert: each schooled in every '
           'art of the working, rolling together and summing their count, or lending '
           'a single certain success apiece to the leader&rsquo;s &mdash; and the '
           'leader&rsquo;s botch is everyone&rsquo;s.<sup>c</sup> And magick may be '
           'answered: the full action spent, one art of the assault held, Arete '
           'rolled against seven, each success erasing one of the attacker&rsquo;s '
           '&mdash; with dearer answers in the margins: the guard cast over another, '
           'the assault reflected, the standing working unwoven strand by '
           'strand.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'hear the long form&rsquo;s arithmetic of dread. A ward to hold a '
           'chantry&rsquo;s door wants successes by the score, and the score is '
           'gathered a roll at a time: each roll an hour, each hour a fresh audience '
           'with the tenth face, each audience a point of the fee held in escrow. '
           'At the ninth hour the caster&rsquo;s hands shake &mdash; Stamina&rsquo;s '
           'allowance spent, the body now rolled alongside the soul &mdash; and at '
           'the eleventh a knock at the door demands her will at the high wall '
           'while the gathered successes tremble. The ward that stands at dawn '
           'cost a night, a candle&rsquo;s worth of nerve, and nothing else; the '
           'ward that collapsed at the eleventh hour cost the same night and the '
           'whole escrowed fee, paid at once. The disputants around this text hold '
           'the form&rsquo;s two edges: whether the concert centralizes what magick '
           'was meant to scatter, and what it means that every answer to magick is '
           'more magick.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; verso of '
             'Casting: the recto keeps the four steps, this side keeps the works '
             'that take all night and the arts that say no.',
 'folio': '500B',
 'glossL': '<p><span class="mark">a</span> On rituals as extended workings &mdash; '
           'the roll ceiling, the stiffening walls, the held botch and the fatal '
           'second &mdash; see M20, the Book of Magick, folios 538&ndash;542.</p>\n'
           '        <p><span class="mark">b</span> On the ritual&rsquo;s accruing '
           'Paradox, the Stamina hours, and the interference clause, see the same '
           'folios; the optional rite, ceremony, and great work are the same '
           'pages&rsquo; graded forms.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On acting in '
           'concert &mdash; the schooling requirement, summed counts, lent '
           'successes, the shared botch, and the hundred participants who can '
           'render the vulgar coincidental &mdash; see folios 542&ndash;543.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On countermagick '
           'basic and optional &mdash; the sevens wall, the protective and '
           'reflected forms, the anti-magick dice, and the unweaving with its '
           'named exceptions &mdash; see folios 545&ndash;546.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The ritual&rsquo;s escrowed fee is '
           '533a&rsquo;s law on installment: the court forgives the patient and '
           'ruins the unlucky, and the botch-accumulation warning that folio '
           'posted is this page&rsquo;s whole Gemara.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'hundred-voice concert that renders the vulgar coincidental is '
           '533b&rsquo;s census inverted: witnesses turned participants, the '
           'crowd&rsquo;s belief conscripted &mdash; the Masoret marks it as the '
           'engine&rsquo;s single most setting-revealing clause.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'unweaving&rsquo;s named refusals &mdash; the workings no art '
           'dismantles &mdash; are the binding&rsquo;s short list of true '
           'permanence, and 520a&rsquo;s master of Prime, who does most of the '
           'unweaving, keeps the list posted in her folio&rsquo;s margins.</p>',
 'h1': 'The Long Working',
 'hagahah': 'The first botch can be held together with a turn, a point of will, '
            'and a success already gathered. The second cannot. Every ritualist '
            'in the setting knows exactly how much night lies between those two '
            'sentences, and none of them will tell you.',
 'inner': '<p><span class="lemma">Bounded by will and Arete together.</span> The '
          'ceiling&rsquo;s plain sense: the ritual&rsquo;s attempts are counted '
          'before it begins &mdash; permanent will and enlightenment summed '
          '&mdash; so the long form is finite by law, and the caster knows her '
          'whole allowance at the first candle. The design is the extended '
          'form of 385b given a soul: the cap is not time pressure borrowed '
          'from outside but the mage&rsquo;s own depth, spent visibly, which '
          'is why watching a great ritual is watching a person emptied.</p>\n'
          '        <p><span class="lemma">Held together once.</span> The '
          'botch clause&rsquo;s plain sense: the first catastrophe may be '
          'caught &mdash; a turn surrendered, a point of will burned, a '
          'gathered success sacrificed &mdash; and the work continues at a '
          'stiffer wall with the table&rsquo;s hearts in their throats. The '
          'clause exists to create exactly that moment: the near-ruin '
          'survived is the long form&rsquo;s signature scene, and the second '
          'botch&rsquo;s absolute finality is what keeps the first '
          'one&rsquo;s survival from cheapening. Mercy that repeats is not '
          'mercy but rules-lawyering; the drafters allowed it once, and priced '
          'it in the currency the ritualist is already spending fastest.</p>\n'
          '        <p><span class="lemma">A point of the fee, held.</span> '
          'The escrow&rsquo;s plain sense: each roll past the first banks a '
          'point of Paradox that success forgives entirely and failure pays '
          'at once &mdash; so the long working is a wager that compounds, '
          'the stake rising with every hour invested. The arithmetic makes '
          'patience expensive in exactly one currency, risk, and the '
          'masters&rsquo; famous preference for preparation over improvisation '
          'is this clause internalized: everything that can be settled '
          'before the first roll &mdash; tools, helpers, walls &mdash; is a '
          'point of escrow that never accrues. The graded forms the books '
          'offer &mdash; the brief rite, the hour-rolled ceremony, the great '
          'work of days with its perilous breaks &mdash; are this same law '
          'dressed for three occasions, and even the breaks are priced, for '
          'in the long form rest itself is a roll.</p>\n'
          '        <p><span class="lemma">Each schooled in every art.</span> '
          'The concert&rsquo;s plain sense: collaboration demands genuine '
          'shared competence &mdash; a dot in every Sphere of the working, '
          'presence, compatibility of approach &mdash; and pays two ways: '
          'equals sum their rolled counts, and the schooled assistant lends '
          'one certain success, five such at most. The shared botch is the '
          'form&rsquo;s honesty: a circle multiplies hands and multiplies '
          'exposure in the same gesture, and the leader who recruits '
          'carelessly has recruited her own backlash&rsquo;s '
          'congregation.</p>\n'
          '        <p><span class="lemma">Each success erasing one.</span> '
          'Countermagick&rsquo;s plain sense: the answer to a working is a '
          'working &mdash; a full action, a dot held in one of the '
          'assault&rsquo;s own arts, Arete against the sevens wall, the '
          'counts colliding &mdash; and the mystic dodge that 409a listed '
          'among the defenses is revealed here in full dress. The dearer '
          'forms price their reach: the guard cast over another asks Prime '
          'and essence at a stiffer wall, the reflection stiffer yet, and '
          'the unweaving of standing works asks tens of successes and '
          'respects its list of refusals &mdash; the engine&rsquo;s quiet '
          'promise that some finished things stay finished.</p>',
 'inner_head': 'On the Night&rsquo;s Work<span class="comm-sub">the inner '
               'commentary &middot; the plain sense &middot; ceilings, '
               'escrows, and answers</span>',
 'name': 'The Long Working',
 'outer': '<p><span class="lemma">Whether the concert centralizes.</span> The '
          'circle dispute. <span class="voice">Some say</span> acting in '
          'concert is the setting&rsquo;s communal heart given rules: the '
          'great work demands the gathered cabal, the chantry exists because '
          'the concert clause makes it necessary, and the hundred-voice '
          'crowd that renders the impossible ordinary is the '
          'Consensus&rsquo;s own machinery borrowed for an hour &mdash; '
          'magick at its largest is magick at its least private, which is '
          'the whole rebuke to the lone-wizard fantasy. <span '
          'class="voice">Others say</span> look at who holds the circle: the '
          'schooling requirement means concerts assemble around whoever '
          'already commands the rarest arts, the lent successes flow upward '
          'to the leader&rsquo;s roll, and the shared botch distributes his '
          'risk onto his juniors &mdash; the clause builds hierarchies and '
          'calls them fellowship, and every chantry&rsquo;s politics folio, '
          '2a forward, documents the result. The first school reads the '
          'mechanism&rsquo;s hope; the second reads its history; and the '
          'tractate, which has bound both since its first leaf, declines to '
          'pretend they disagree about the rules rather than about '
          'people.</p>\n'
          '        <p><span class="lemma">Every answer is more magick.</span> '
          'The escalation dispute, and the verso&rsquo;s deepest. '
          'Countermagick, anti-magick, unweaving, the warding guard &mdash; '
          'the entire defensive suite runs on Arete and Spheres, so the '
          'war of workings has no civilian exit: the only shield against '
          'will is will. <span class="voice">Some say</span> this is simply '
          'true and the engine honest about it &mdash; belief contests '
          'belief, the Sleepers&rsquo; protection is the Consensus itself, '
          'and the innate counters the books scatter (the Union&rsquo;s '
          'null-metal, the faithful&rsquo;s conviction) are the setting '
          'granting exactly the exceptions its cosmology predicts. <span '
          'class="voice">Others say</span> the design writes an arms race '
          'with no armistice: every defense being an art, the arts '
          'concentrate, the concentrated grow unanswerable save by their '
          'peers, and the setting&rsquo;s archmage problem &mdash; folio '
          '109&rsquo;s, wanting &mdash; is this clause compounded across '
          'centuries. The first school calls that the genre; the second '
          'calls it the tragedy; the tractate observes that the setting '
          'calls it both, in so many words, on its first page. <span '
          'class="kw">TEYKU</span> &mdash; and ward your door '
          'regardless.</p>\n'
          '        <p><span class="lemma">A wager that compounds.</span> A '
          'last difficulty, actuarial. <span class="voice">Some say</span> '
          'the ritual&rsquo;s escrowed Paradox is the engine&rsquo;s finest '
          'clause: risk priced to ambition, the great work genuinely '
          'frightening to attempt, and the forgiveness on success the '
          'exact shape of the setting&rsquo;s grace &mdash; the world '
          'forgives what works. <span class="voice">Others say</span> the '
          'clause punishes precisely the mages the setting claims to '
          'honor: the patient, the ceremonial, the traditional, whose '
          'every hour of reverence is a banked point of ruin, while the '
          'snap-caster&rsquo;s exposure ends with her turn. The answer '
          'from the first school is the recto&rsquo;s: scope lives above '
          'the fast ceiling, and the fee is scope&rsquo;s price. The '
          'answer from the second is a house rule in half the '
          'setting&rsquo;s chantries, which the tractate files as girsa '
          'and the chantries file as self-defense. The tractate&rsquo;s own '
          'counsel stands with the printed law and the visible escrow: the '
          'wager should at least be an informed one, and informed wagers are '
          'the genre.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the circle, the escalation, and the '
               'escrow</span>',
 'rubric': 'rituals, concerts, and the arts that answer',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of the long working &middot; the ritual '
             'as law',
 'title': 'Tractate Aliyah · Folio 500b — The Long Working: rituals, concerts, and the arts that answer',
 'type': 'daf'}
