# Folio 512a - Correspondence. Sphere mold (f515a); facts per the
# wod-llm-wiki Correspondence page (M20 pp.512-513, chart p.504).
FOLIO = {'bottom': '<p><span class="lemma">On the third dot.</span> The rank that steps through is the '
           'rank that breaks site-based adventure design, and the Storyteller should welcome the '
           'breakage on schedule: once a cabal&rsquo;s mage can gate, the locked door stops being '
           'an obstacle and starts being a question about wards, witnesses, and what is waiting on '
           'the far side. Price the step honestly &mdash; the blind jump&rsquo;s successes, the '
           'vulgarity of appearing from nothing, the load limits that leave the cabal&rsquo;s '
           'muscle walking &mdash; and the Sphere improves the game it seems to threaten: travel '
           'becomes tactics, and arrival becomes a scene instead of a transition.</p>\n'
           '        <p><span class="lemma">On four dots and past.</span> Wards and pocket spaces '
           'change the chronicle&rsquo;s architecture: the chantry that cannot be scried, the '
           'vault that is nowhere, the master in three meetings at once. Give the players the same '
           'tools their enemies enjoy, and let the Correspondence war be fought as it canonically '
           'is &mdash; quietly, in the walls, every faction&rsquo;s sanctum a hole in every other '
           'faction&rsquo;s map. The Union&rsquo;s version is coverage; the Adepts&rsquo; is '
           'topology; the folio overleaf holds the reach charts both sides consult.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Post the connection standard in '
           'session zero beside 533a&rsquo;s vulgarity rulings: what counts as a body sample, a '
           'possession, a described place; whether a photograph is a visit; whether a video call '
           'is line of sight. The Sphere&rsquo;s whole balance lives in that table &mdash; '
           'generous readings make every stranger reachable and every secret short-lived; strict '
           'ones keep distance meaningful &mdash; and the ruling, as ever, is a genre choice '
           'wearing a rules face.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on doors, wards, and the connection '
                'standard</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Correspondence is the Sphere of the between:</span> distance, '
           'direction, and connection &mdash; the ties that make two places neighbors whatever the '
           'map says.<sup>a</sup> Its ladder climbs from knowing to unmaking. At the first rank '
           'the mage <span class="term">perceives</span> the near unseen: distances judged true, '
           'the hidden thing noticed, the warp in space felt like a draft. At the second she <span '
           'class="term">reaches</span>: her senses extend across any distance her connections '
           'allow, and space may be thickened against the reaching of others.<sup>b</sup> At the '
           'third she <span class="term">passes</span>: small gates torn and stepped through, '
           'herself and little more. At the fourth she <span class="term">rends and wards</span>: '
           'gates made lasting, places sealed against sight and passage, the self stood in two '
           'rooms at once. At the fifth she <span class="term">unmakes the between</span>: spaces '
           'folded, distant things joined, two places made one place &mdash; and the law calls '
           'this last deeply vulgar in almost every telling.<sup>c</sup> Two laws attend the '
           'ladder. The Sphere works on whole patterns only: it moves the gun, never the hand from '
           'the wrist. And in any joint working, the mage&rsquo;s Correspondence caps her '
           'partners: no Sphere reaches farther than her mastery of reach itself.<sup>d</sup> And '
           'the first rank&rsquo;s perception is the gate: no rung above works blind, and every '
           'reaching leaves a ripple the perceiving rank can feel.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'cases. A mage watches her enemy across an ocean, holding his glove: the second rank, '
           'eased by the connection &mdash; the glove is a rope tied to its owner. She steps from '
           'her sanctum to a street she has never seen, described to her once over a bad line: the '
           'third rank, and the successes of a blind jump, and the law prices her ignorance in '
           'dice. She seals her chantry so that no reaching finds it: the fourth, and the seal is '
           'only as good as her seniority in this Sphere over every seeker&rsquo;s. And the master '
           'who folds the warehouse into the alley behind her enemies &mdash; two places made one, '
           'briefly, horribly &mdash; is the fifth rank, and the disputants opposite have been '
           'asked to rule what the witnesses of both places saw.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; second of the Sphere folios; its reach charts '
             'wait overleaf.',
 'folio': '512A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Correspondence entire, see M20, the '
           'Spheres chapter, folios 512&ndash;513, whence this page takes its number; the older '
           'recensions called it Connection, which the Mishnah&rsquo;s first clause '
           'remembers.</p>\n'
           '        <p><span class="mark">b</span> On the reach of the second rank and the '
           'connections that ease it, see the ranges chart of M20&rsquo;s systems chapter; the '
           'verso restates it as law.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On co-location and spatial '
           'mutation as the fifth rank&rsquo;s province, see the same entry; on its vulgarity, no '
           'recension disagrees.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the whole-patterns rule and the '
           'Correspondence cap in conjunctional workings, see M20&rsquo;s Sphere entry; the cap is '
           'this folio&rsquo;s gift to folio 515b&rsquo;s law of partnerships.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Virtual '
           'Adepts&rsquo;, folio 164a, who read it as Data and claim the reading&rsquo;s '
           'authorship; the Union runs their girsa in production, which folio 164a&rsquo;s Masoret '
           'has already savored.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The One-Point problem argued '
           'opposite is folio 515b&rsquo;s rating law under pressure: the cap clause here is the '
           'law&rsquo;s own answer, and whether it suffices is the dispute.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Wards against sight are '
           'witness-management made architecture: folios 533a and 533b govern what the unwarded '
           'world sees, and folio 3a&rsquo;s thesis &mdash; all law is the law of who is watching '
           '&mdash; was never truer than here.</p>',
 'h1': 'Correspondence',
 'hagahah': 'The Sphere&rsquo;s old name was Connection, and the renaming is the rare one nobody '
            'protests: Correspondence is what letters do, and the Sphere is, at every rank, a '
            'postal service &mdash; sight mailed, bodies mailed, places mailed to each other. The '
            'fifth rank is merely the post office losing a package into another package, forever.',
 'inner': '<p><span class="lemma">The ties that make two places neighbors.</span> The jurisdiction '
          'test: Correspondence owns betweenness &mdash; not the thing, not the energy, but the '
          'adjacency. Where a working seems to share ground with another Sphere, ask what changed: '
          'if both ends stayed themselves and only their distance lied, this ladder worked alone. '
          'The Sphere&rsquo;s deep claim, which its seat&rsquo;s Tradition states as doctrine, is '
          'that distance was always a convention &mdash; space is information about relationships, '
          'and information can be edited.</p>\n'
          '        <p><span class="lemma">As her connections allow.</span> The second rank&rsquo;s '
          'plain sense: reach is priced in intimacy. The verso&rsquo;s chart is the law&rsquo;s '
          'arithmetic &mdash; line of sight cheap, the stranger&rsquo;s unvisited room dear, and a '
          'connection carried in the hand discounts everything. Note the symmetrical clause: space '
          'thickened against a seeker cancels the seeker&rsquo;s successes one for one, which '
          'makes counter-surveillance a duel of ranks conducted in perfect silence, the '
          'Sphere&rsquo;s native form of war.</p>\n'
          '        <p><span class="lemma">Herself and little more.</span> The third rank&rsquo;s '
          'load clause: the gate that passes a mage balks at her luggage, and the heavy or the '
          'many wait for the fourth rank&rsquo;s rending. The plain sense for the table is '
          'party-splitting as physics: the Sphere moves scouts, thieves, and messengers long '
          'before it moves cabals, and a chronicle&rsquo;s logistics stay interesting exactly as '
          'long as the Storyteller enforces the freight rules.</p>\n'
          '        <p><span class="lemma">Whole patterns only.</span> The mercy clause, and read '
          'it as one: the Sphere that could teleport a heart out of a chest is ruled unable, '
          'alone, to do so &mdash; the pattern resists division, and dividing it wants '
          'Life&rsquo;s consent in the partnership. The law&rsquo;s structure repeats 515b&rsquo;s '
          'lesson: the Spheres&rsquo; borders are drawn where the horrors are, and every '
          'conjunction requirement is a checkpoint with a reason.</p>\n'
          '        <p><span class="lemma">No Sphere reaches farther.</span> The cap clause&rsquo;s '
          'plain sense: reach is a skill, not a rider. The mage who would throw fire across the '
          'city needs Correspondence equal to the throwing, not merely Forces equal to the fire '
          '&mdash; mastery of the between is never borrowed from mastery of the payload. The '
          'disputants opposite test the clause against the famous cheap reading; the clause, '
          'plainly read, was written to stop it.</p>\n'
          '        <p><span class="lemma">Leaves a ripple.</span> The counter-intelligence '
          'clause&rsquo;s plain sense: reaching disturbs the between, and the disturbance is '
          'legible &mdash; a first-rank sentry feels the second-rank spy&rsquo;s extended senses '
          'pass like a draft under a door. The Sphere&rsquo;s wars are silent, as the verso will '
          'rule, but they are not traceless: the reached place remembers being reached, and the '
          'mage who checks her rooms nightly is not paranoid, she is literate. Every '
          'chantry&rsquo;s standing watch is built on this clause, and every successful '
          'infiltration on its neglect.</p>\n'
          '        <p><span class="lemma">Deeply vulgar in almost every telling.</span> The fifth '
          'rank&rsquo;s qualifier, plainly: <span class="aside">almost</span>. The folded space, '
          'the joined rooms, the stretched corridor &mdash; these have no coincidental reading in '
          'any ordinary scene, but the law leaves the qualifier standing for the places where '
          'space is already agreed to be strange: the funhouse, the dream, the deep Web of folio '
          '164b, the realms of chapter IV where local consensus differs. Mastery of the between '
          'includes mastery of where the between is already loose, and the Sphere&rsquo;s elders '
          'spend their fifth-rank workings, almost exclusively, there.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; rank by rank, clause by clause</span>',
 'name': 'Correspondence',
 'outer': '<p><span class="lemma">No Sphere reaches farther than her mastery of reach.</span> The '
          'One-Point problem, the Sphere&rsquo;s oldest fight. <span class="voice">Some say</span> '
          'a single dot of Correspondence, on the old loose reading, turned every other Sphere '
          'into artillery: perceive a target anywhere, they argued, and the fireball follows the '
          'sight &mdash; one point purchased as range-extender for a whole arsenal. <span '
          'class="voice">Others say</span> the reading was always a misreading, and the cap clause '
          'is its tombstone: the first rank perceives the <span class="aside">near</span> unseen, '
          'reach begins at the second, and a working thrown along a sensing needs the '
          'thrower&rsquo;s Correspondence to equal the task &mdash; the payload rides the rank, '
          'never the other way. The manuscripts&rsquo; drift favors the strict school, and the '
          'loose school&rsquo;s best case was always economy rather than text: cheap reach made '
          'cheap chronicles, and the Storyteller who misses the old artillery is invited to reread '
          'what it did to her predecessors&rsquo; campaigns, the accounts being preserved and '
          'rueful.</p>\n'
          '        <p><span class="lemma">The self stood in two rooms at once.</span> '
          'Co-location&rsquo;s sanity dispute. <span class="voice">Some say</span> the fourth '
          'rank&rsquo;s doubling is bookkeeping: one mind attending two windows, no stranger than '
          'a driver watching mirrors &mdash; the mirrored selves are puppets of one will unless '
          'the partnership with Life grants them independence, and the law&rsquo;s conjunction '
          'requirements say exactly where the person stops and the copies start. <span '
          'class="voice">Others say</span> the bookkeeping is the horror: a will that can inhabit '
          'two rooms has already conceded that presence is negotiable, and the masters of this '
          'Sphere are famous, even among mages, for a certain difficulty with the word <span '
          'class="aside">here</span>. The Quiet of folio 554, when it is written, will want this '
          'paragraph as evidence; the disputants lend it in advance.</p>\n'
          '        <p><span class="lemma">What the witnesses of both places saw.</span> The '
          'folded-space case, and the census under strain. When two places are made one, the crowd '
          'in each sees the other arrive &mdash; or sees nothing, or sees wrongness without name, '
          'and the standards of 533a were not drafted for a working whose witnesses stand in two '
          'consensuses at once. <span class="voice">Some say</span> price it as two workings '
          'witnessed severally: each crowd taxes the working by its own lights, and the master '
          'pays both bills, which is why the fifth rank&rsquo;s users prefer empty warehouses. '
          '<span class="voice">Others say</span> the folding is one assertion against the world '
          'entire, and the world answers once, hugely &mdash; the Paradox of joined places arrives '
          'not as two fines but as one verdict on the idea that places are negotiable. The '
          'manuscripts support either arithmetic; the survivors&rsquo; accounts support caution; '
          'and the tractate notes that this is the second folio running in which the '
          'Sphere&rsquo;s masters end up arguing with the concept of location itself. <span '
          'class="kw">TEYKU</span> &mdash; let the two places stand apart. The strict school adds '
          'a coda for the record: the cap clause is why the Union&rsquo;s coverage doctrine never '
          'conquered the world &mdash; even the all-seeing must rank the seeing, and budgets, as '
          'ever, are the true counter-magick.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the one point, the doubled self, and the folded room</span>',
 'rubric': 'the Sphere of the between, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Correspondence &middot; the dot ladder as law, '
             'with its boundary disputes',
 'title': 'Tractate Aliyah · Folio 512a — Correspondence: the Sphere of the between',
 'type': 'daf'}
