# Folio 512b - The Reach. Verso of the Correspondence folio: the range and
# connection law, thickened space, and wards, per the wod-llm-wiki
# Correspondence page (M20 p.504 charts).
FOLIO = {'bottom': '<p><span class="lemma">On running the chart.</span> The reach law plays best when the '
           'players can see it: post the ladder of intimacy &mdash; sight, the familiar, the '
           'visited, the described, the blind &mdash; and let them plan against it. Heists in a '
           'Correspondence chronicle are collection expeditions: the enemy&rsquo;s glove, his '
           'coffee cup, an hour in his lobby, each acquisition discounting the working to come. '
           'The Sphere turns preparation into drama, and a Storyteller who makes the players earn '
           'their connections has made three sessions out of what a looser table spends in one '
           'roll.</p>\n'
           '        <p><span class="lemma">On the quiet war.</span> Thickening and warding are the '
           'setting&rsquo;s invisible arms race, and the chronicle should feel it: every chantry, '
           'Construct, and node sits behind somebody&rsquo;s seniority, and the question <span '
           'class="aside">who can see us right now</span> has a real answer that changes when '
           'staff changes. Let the players buy, rent, and lose coverage; let a dead master&rsquo;s '
           'wards lapse on a schedule; and the Sphere&rsquo;s fourth rank becomes the '
           'campaign&rsquo;s real estate market, which canonically it is.</p>\n'
           '        <p><span class="lemma">On the sample in the safe.</span> The connection law '
           'cuts both ways, and the table should honor the paranoia it canonically breeds: mages '
           'burn their hair, launder their possessions, and treat a lost glove as a security '
           'breach, because it is one. A cabal&rsquo;s own discards are plot hooks pointed '
           'backward; spend one per chronicle and the players will develop, unprompted, the '
           'operational hygiene the setting&rsquo;s elders are famous for &mdash; at which point '
           'the Storyteller&rsquo;s work is done and the genre has changed to espionage, '
           'correctly.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on earned connections, the coverage '
                'market, and hygiene</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Reach is priced in intimacy.</span> The law of the between '
           'counts successes against closeness: what stands in sight is one; the deeply familiar, '
           'two; the familiar, three; the once-visited, four; the merely described, five; the '
           'wholly strange, six and beyond.<sup>a</sup> A <span class="term">connection</span> '
           'discounts the count: the body&rsquo;s own leavings reach as sight does; the close '
           'possession as the familiar; the touched thing, the met stranger, each has its rung '
           '&mdash; and the discount is the law&rsquo;s whole teaching, that intimacy is a '
           'place.<sup>b</sup> Stepping through is priced by the same ladder, and blindness is '
           'priced worst: the mage who leaps to a place she knows only by hearsay pays nearly the '
           'stranger&rsquo;s full fare and arrives owning whatever she finds.<sup>c</sup> Against '
           'all reaching stands the thickening: space made dense cancels the seeker success for '
           'success, and the <span class="term">ward</span> is thickening made permanent &mdash; a '
           'seal upon a place against sight, against passage, or against both, holding while its '
           'maker&rsquo;s mastery outranks the world&rsquo;s curiosity.<sup>d</sup> Two further '
           'measures govern. The reaching that fails learns nothing of why &mdash; cancelled, '
           'blocked, or merely short, the silence is uniform. And every connection cuts both ways: '
           'the rope tied to the target is tied also to the holder, and the wise burn the glove '
           'after the working.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the pricing? '
           'The law reasons from the tie, not the mileage: the mother reaches her child across an '
           'ocean more cheaply than a spy reaches the next room, because the world itself keeps '
           'accounts of who belongs to whom, and the Sphere merely reads the ledger. <span '
           'class="kw">IT HAPPENED THAT</span> a young Adept mocked the chart as sentiment &mdash; '
           'distance is data, she said, and data does not care whose glove you hold &mdash; and '
           'her elder set her to reach a server she administered daily and then a stranger&rsquo;s '
           'identical machine one rack over. The first answered like a friend; the second like a '
           'fortress. <span class="aside">The network cares,</span> said the elder, <span '
           'class="aside">it merely calls caring adjacency.</span> The disputants around this text '
           'take up what the ledger is, and who audits the auditors of belonging.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Correspondence folio: the recto '
             'keeps the ladder, this side keeps the fare table.',
 'folio': '512B',
 'glossL': '<p><span class="mark">a</span> On the ranges of reach &mdash; sight to the wholly '
           'strange &mdash; see the Correspondence ranges chart of M20&rsquo;s systems chapter; '
           'the rungs are restated here, not reproduced.</p>\n'
           '        <p><span class="mark">b</span> On connections and their discounts &mdash; the '
           'sample, the possession, the touched thing &mdash; see the same chart&rsquo;s second '
           'column.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On stepping through and the price '
           'of blindness, see the teleportation table beside it.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On thickened space cancelling a '
           'seeker&rsquo;s successes, and on wards against patterns and against Resonance, see the '
           'Sphere&rsquo;s second and fourth ranks in the M20 entry.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The fare table is folio 522&rsquo;s cousin: Time '
           'prices its reaching by years as this Sphere prices by intimacy, and the two charts are '
           'the Book of Magick&rsquo;s twin meditations on how far away anything really is.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The connection law is '
           'sympathy&rsquo;s law, and the witch of folio 162a has worked it since before this '
           'Sphere had a name: the poppet with the enemy&rsquo;s hair is a connection worn openly. '
           'One chart, many liturgies, as this chapter keeps finding.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The ward against sight is '
           'folio 533b&rsquo;s census inverted &mdash; witness management by subtraction &mdash; '
           'and the Union&rsquo;s coverage doctrine, chapter VI&rsquo;s business, is the same '
           'chart read as a budget.</p>',
 'h1': 'The Reach',
 'hagahah': 'The chart&rsquo;s deepest rung prices reaching a total stranger at six successes, and '
            'reaching one&rsquo;s own beloved at one glance. Every romantic tradition on earth '
            'arrived at this arithmetic first; the Sphere&rsquo;s contribution was footnotes.',
 'inner': '<p><span class="lemma">Priced in intimacy.</span> The plain sense of the fare table: '
          'the successes measure estrangement, not distance &mdash; a described place across the '
          'street costs what a described place across the world costs, because the mage&rsquo;s '
          'ignorance is identical. Players misread this as metaphor; it is mechanism, and the '
          'chart is consulted per working, with the connection in hand at the casting or not '
          'counted at all.</p>\n'
          '        <p><span class="lemma">The body&rsquo;s own leavings.</span> The sample '
          'clause&rsquo;s plain sense, and its coldness: hair, blood, and nail-parings collapse '
          'the whole ladder to a single rung, which is why the setting&rsquo;s professionals treat '
          'biology as classified material. Note the law&rsquo;s indifference to consent &mdash; '
          'the sample stolen reaches as well as the sample given &mdash; and note that the ethics '
          'the law declines to supply are billed instead by folio 533a, since reaching a wary '
          'target coincidentally is its own art.</p>\n'
          '        <p><span class="lemma">Arrives owning whatever she finds.</span> The blind '
          'jump&rsquo;s plain sense: the successes buy passage, never safety, and the law&rsquo;s '
          'phrase for materializing in an unknown room is deliberately commercial &mdash; the mage '
          'purchases the destination as-is, sight unseen, no warranty. The chronicle&rsquo;s best '
          'Correspondence stories live in that clause, and so do its shortest.</p>\n'
          '        <p><span class="lemma">Success for success.</span> The thickening&rsquo;s plain '
          'sense: counter-reach is subtraction, not contest &mdash; each success of the defender '
          'simply deletes one of the seeker&rsquo;s, and a fully cancelled working finds nothing '
          'and reports nothing, the seeker unaware she was blinded rather than unlucky. The '
          'silence is the point: the Sphere&rsquo;s wars leave no casings, and two masters may '
          'duel for a season with neither certain the other exists.</p>\n'
          '        <p><span class="lemma">While its maker&rsquo;s mastery outranks.</span> The '
          'ward&rsquo;s plain sense: permanence is tenancy, not freehold. A ward holds against the '
          'world&rsquo;s ordinary curiosity indefinitely and against a superior seeker not at all; '
          'wards therefore age like fortifications, strong the day the mason died and weaker every '
          'year the art advances. The chronicle&rsquo;s ancient sealed places are sealed by dead '
          'seniority, and opening them is less archaeology than probate.</p>\n'
          '        <p><span class="lemma">The silence is uniform.</span> The failure '
          'clause&rsquo;s plain sense: a reach that finds nothing reports nothing &mdash; not '
          'distance, not defense, not whether the target exists. The uniformity is the law&rsquo;s '
          'gift to defenders and its tax on intelligence work: no probe distinguishes the warded '
          'from the absent, and the seeker&rsquo;s map of the world is forever pocked with '
          'silences that might be fortresses and might be nothing. The Union&rsquo;s coverage '
          'doctrine calls these dark zones; the Adepts call them interesting; both budget '
          'accordingly.</p>\n'
          '        <p><span class="lemma">Tied also to the holder.</span> The symmetry '
          'clause&rsquo;s plain sense, and the tradecraft it writes: a connection is a standing '
          'channel, and channels carry traffic both ways &mdash; the mage reaching through the '
          'enemy&rsquo;s glove has told the enemy&rsquo;s own reachers where her hand is. Working '
          'connections are therefore handled like live wires: gripped briefly, grounded after, '
          'destroyed when spent. The poppet-burning of folio 162a&rsquo;s witches is this clause '
          'as folk hygiene, older than the chart and exactly as correct.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; fares, samples, and seals</span>',
 'name': 'The Reach',
 'outer': '<p><span class="lemma">The world itself keeps accounts.</span> But what is the ledger? '
          '<span class="voice">Some say</span> the chart reads the Consensus: belonging is a fact '
          'about minds &mdash; the mother&rsquo;s reach is cheap because everyone agrees mothers '
          'reach &mdash; and the fare table is folio 62&rsquo;s thesis applied to geography, local '
          'custom hardened into physics. On this reading the chart could differ in other ages and '
          'places, and the recensions&rsquo; steady numbers measure only how slowly humanity '
          'revises intimacy. <span class="voice">Others say</span> the ledger is deeper than '
          'agreement: the ties are real patterns in the world&rsquo;s weave &mdash; the Adepts '
          'call them edges, the witches call them sympathy, the Masoret calls the convergence '
          'suspicious &mdash; and consensus merely discovers them, as it discovers gravity. The '
          'first school predicts the chart drifts; the second that it holds; and the tractate, '
          'which has watched the chart hold across every recension, reports the evidence and '
          'declines the inference, since holding is also what well-enforced conventions do.</p>\n'
          '        <p><span class="lemma">Who audits the auditors of belonging.</span> The sample '
          'dispute, pressed where it hurts. <span class="voice">Some say</span> the connection law '
          'is morally inert &mdash; a rope does not ask who tied it, and the ethics of stolen '
          'intimacy belong to the stealing, not the Sphere. <span class="voice">Others say</span> '
          'the law teaches theft by pricing it: a system in which the beloved and the burgled '
          'reach identically has told its students what intimacy is worth stripped of its consent, '
          'and the Traditions&rsquo; codes &mdash; the Ecstatics&rsquo; consent root, the '
          'witches&rsquo; own-blood-first &mdash; exist precisely because the charts will not '
          'carry the weight. The dispute is the chapter&rsquo;s oldest pattern in new clothes: '
          'every Sphere&rsquo;s law is strictest where its gift is strongest, except this one, '
          'whose law is silent there &mdash; and the silence, both sides agree, is assignment '
          'enough for the Traditions that hold it.</p>\n'
          '        <p><span class="lemma">Neither certain the other exists.</span> A last '
          'difficulty, half in jest and wholly serious: the quiet war has no verification. The '
          'thickener who cancels a seeker learns nothing; the seeker cancelled learns nothing; and '
          'two paranoid masters may fortify against each other&rsquo;s phantoms for decades '
          '&mdash; the Sphere&rsquo;s economy runs on unfalsifiable threat, which is to say on '
          'faith, which is to say the Adepts&rsquo; proof-worship and their favorite Sphere are at '
          'war in their own hands. <span class="voice">Some say</span> this is the Sphere&rsquo;s '
          'hidden governor, thrift by uncertainty; <span class="voice">others say</span> it is the '
          'Union&rsquo;s actual victory condition, every mystic&rsquo;s budget bled by shadows. '
          'The deep sectors of folio 164b, asked to confirm, returned no answer, which proves '
          'either reading, as ever. <span class="kw">TEYKU</span> &mdash; let the watchers watch. '
          'A coda from the quartermasters, both sides: the unverifiable war is at least cheap to '
          'lose politely &mdash; the cancelled probe costs a working, the panicked fortress costs '
          'a fortune, and the Sphere&rsquo;s true masters are distinguishable less by reach than '
          'by the discipline of not checking twice.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the ledger, the sample, and the unverifiable war</span>',
 'rubric': 'the fare table of the between',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of reach and its prices &middot; connection, thickening, and '
             'wards',
 'title': 'Tractate Aliyah · Folio 512b — The Reach: the fare table of the between',
 'type': 'daf'}
