# Folio 514a - Entropy. Sphere mold (f515a); facts per the wod-llm-wiki
# Entropy page (M20 pp.513-514).
FOLIO = {'bottom': '<p><span class="lemma">On the second dot.</span> Probability control is the quietest '
           'game-changer in the book: nothing an Entropy 2 mage does looks like anything, and a '
           'Storyteller who prices it accordingly &mdash; coincidental almost by definition, '
           'cheap, deniable &mdash; discovers the Sphere&rsquo;s real table problem, which is not '
           'power but pace. Herded dice make every scene negotiable, so set the herding&rsquo;s '
           'grain early: small events cheap, large ones dear, and the declared outcome always a '
           'nudge, never a script. The mage tilts the table; she does not deal the hand.</p>\n'
           '        <p><span class="lemma">On the fourth dot and past.</span> When Entropy touches '
           'the living, the chronicle&rsquo;s tone is on the table: sudden disease and gifted '
           'vitality are aggravated in both mechanics and mood, and the fifth rank&rsquo;s '
           'meme-craft &mdash; ideas strengthened, memories rotted, oaths made ruinous to break '
           '&mdash; is the most quietly horrifying power in the nine ladders. Gate these ranks '
           'behind the Tradition&rsquo;s own procedure: the Chakravanti of folio 156a climb a '
           'whole ladder of gentler remedies first, and an antagonist who skips those rungs has '
           'told the table exactly what he is.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Declare in session zero how luck '
           'reads at this table: whether the bystander of 533a can ever balk at fortune, or '
           'whether bad luck is the perfect crime. Most chronicles rule Entropy coincidental up to '
           'the edge of the actuarial &mdash; the run of sevens, the nine-car pileup that spares '
           'one door &mdash; and vulgar past it; wherever the edge sits, post it, because the '
           'Sphere&rsquo;s players will live on it, as its canonical masters do.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on nudges, aggravated tones, and the '
                'actuarial edge</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Entropy is the Sphere of the tilt:</span> chance, flaw, decay, '
           'and fate &mdash; the lean in every falling thing, read and then steered.<sup>a</sup> '
           'At the first rank the mage <span class="term">perceives</span>: the currents of '
           'probability, the crack in the blade and the lie in the argument, the tell of the '
           'honest and the doomed. At the second she <span class="term">steers the random</span>: '
           'dice, cards, and coin-flips herded, the weak spot struck twice, the crowd&rsquo;s '
           'drift bent one degree.<sup>b</sup> At the third she <span class="term">works the '
           'inanimate</span>: machines fail early or run past hope, luck settles on objects and '
           'tools like weather. At the fourth she <span class="term">touches the living</span> '
           '&mdash; blessing and blight, vitality granted or disease called down &mdash; and only '
           'here does the Sphere first deal harm, and the harm unmakes patterns: it is aggravated '
           'in every telling.<sup>c</sup> At the fifth she <span class="term">works upon thought '
           'itself</span>: ideas strengthened or rotted, memory degraded, the oath bound so that '
           'its breaking is ruin.<sup>d</sup> One law attends the whole ladder: the worker is '
           'marked &mdash; the Sphere&rsquo;s resonance settles on its mage, and the people of the '
           'Wheel have a folio&rsquo;s worth of law, 156b, about what settles next. And the first '
           'rank is the gate here as everywhere: the currents must be read before they are '
           'steered, and the reader of fortune is herself a tell the observant can read.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'cases. A gambler runs the table all night and the house finds no method: the second '
           'rank, and the bystander of 533a saw a hot streak, for luck is the one miracle the '
           'Consensus never doubts. A courier&rsquo;s engine dies at the one crossroads where '
           'dying strands him: the third rank, and the mechanic will find a worn belt, because '
           'there is one. A tyrant&rsquo;s conviction that he is loved rots over a winter into a '
           'conviction that he is watched: the fifth rank, worked meme by meme, and no working was '
           'ever witnessed because nothing visible occurred. And the blessing that keeps a '
           'hospice&rsquo;s patients comfortable past all prognosis: the fourth rank, vitality '
           'gifted &mdash; and the disputants opposite are asked whether the same rank&rsquo;s '
           'other hand makes its holder a physician or a weapon.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; third of the Sphere folios; fortune&rsquo;s '
             'own law waits overleaf.',
 'folio': '514A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Entropy entire, see M20, the Spheres '
           'chapter, folios 513&ndash;514, whence this page takes its number; the Union calls it '
           'Entropic State Control and changes nothing but the letterhead.</p>\n'
           '        <p><span class="mark">b</span> On steering the random &mdash; small events '
           'cheap, large ones dear &mdash; see the second rank&rsquo;s entry there.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On harm arriving only at the '
           'fourth rank, and arriving aggravated, see the same entry; the clause is the '
           'ladder&rsquo;s moral architecture and the disputants&rsquo; first exhibit.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the fifth rank&rsquo;s memes '
           'and binding oaths &mdash; rolled against the subject&rsquo;s very will &mdash; see the '
           'same entry&rsquo;s close.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the '
           'Chakravanti&rsquo;s, folio 156a, whose license and watches are the ladder&rsquo;s '
           'living jurisprudence; the botch it tithes is folio 393&rsquo;s, where entropy '
           'taxes ambition one face in ten.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The mark upon the worker is '
           'jhor&rsquo;s doorstep: folio 156b keeps the disease, this folio keeps the doorknob. '
           'Read them in either order; the Sphere&rsquo;s masters, the Masoret notes, read 156b '
           'annually by statute.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Luck&rsquo;s coincidence is '
           '533a&rsquo;s cleanest case and this Sphere&rsquo;s whole tactical doctrine; the census '
           'of 533b adds only that nobody watches the dice as closely as the loser.</p>',
 'h1': 'Entropy',
 'hagahah': 'The house always wins, runs the proverb, and Entropy 3 is buying the house. The '
            'Sphere&rsquo;s masters add, in the tone of people who have audited the books, that '
            'the house&rsquo;s winnings were never the money: the house wins because everyone '
            'keeps playing, which is a fifth-rank meme, self-installed, and nobody remembers '
            'casting it.',
 'inner': '<p><span class="lemma">The lean in every falling thing.</span> The jurisdiction test: '
          'Entropy owns tendency &mdash; not the pattern, not the energy, but the odds and the '
          'wear. Where a working shares ground with another Sphere, ask what changed: if the thing '
          'and its forces stayed themselves and only the outcome leaned, this ladder worked alone. '
          'The three readings of that sentence &mdash; chance, fate, decay &mdash; are the '
          'disputants&rsquo; opening case, and the inner commentary observes only that the dice '
          'cannot tell them apart.</p>\n'
          '        <p><span class="lemma">Herded, not dealt.</span> The second rank&rsquo;s plain '
          'sense: the mage does not choose outcomes, she redistributes their likelihood, and the '
          'law&rsquo;s grain rules everywhere &mdash; a coin is one nudge, an election is a '
          'career. Repetition is the rank&rsquo;s real power: the weak spot struck twice, thrice, '
          'always, turns small odds into certainties on the installment plan, which is how the '
          'Sphere&rsquo;s patient masters topple what its hasty ones merely dent.</p>\n'
          '        <p><span class="lemma">Only here does the Sphere first deal harm.</span> The '
          'fourth rank&rsquo;s threshold, and the ladder&rsquo;s strangest kindness: three full '
          'ranks of mastery precede the first point of damage, and the harm, when it comes, is '
          'aggravated &mdash; the unmaking of a pattern, not a bruise on one. The architecture '
          'teaches what the seat&rsquo;s Tradition preaches: decay is not violence but '
          'violence&rsquo;s patient cousin, and the Sphere makes its students live with tendency '
          'for years before it hands them ends.</p>\n'
          '        <p><span class="lemma">Rolled against the subject&rsquo;s very will.</span> The '
          'fifth rank&rsquo;s plain sense: thought-work is contested at the root &mdash; the '
          'difficulty is the subject&rsquo;s will, never less than a floor, and conviction costs '
          'more than whim by the law&rsquo;s own scale. The clause is the rank&rsquo;s ethics '
          'written as arithmetic: a strong mind is expensive to rot, and the cheap targets are '
          'precisely the ones the seat&rsquo;s code forbids first.</p>\n'
          '        <p><span class="lemma">The worker is marked.</span> The resonance '
          'clause&rsquo;s plain sense: Entropy&rsquo;s residue is personal, cumulative, and '
          'visible to the first rank of anyone&rsquo;s ladder &mdash; the death-mage reads as one '
          'across a room, which is why the Tradition&rsquo;s diplomats travel with the Vrati and '
          'why anonymity is the one luxury the Sphere never sells its masters. The disease past '
          'the mark is 156b&rsquo;s; the mark itself is merely true.</p>\n'
          '        <p><span class="lemma">Herself a tell.</span> The gate clause&rsquo;s quiet '
          'corollary: reading the currents is participation in them &mdash; the first-rank glance '
          'at the dice table shifts the gambler&rsquo;s posture, the weighed argument leans under '
          'the weighing &mdash; and the Sphere&rsquo;s observers are observable in turn, by their '
          'stillness at the wrong moments, their bets placed a half-beat early. The Union&rsquo;s '
          'statisticians hunt exactly this signature in casino feeds and actuarial tables, and the '
          'Tradition&rsquo;s couriers are taught to lose, periodically, on purpose.</p>\n'
          '        <p><span class="lemma">Complex machines easier than simple stone.</span> The '
          'third rank&rsquo;s strange pricing, plainly: decay-work runs cheap where failure has '
          'many doors &mdash; the engine with ten thousand parts offers ten thousand invitations, '
          'the granite block offers almost none &mdash; and the law&rsquo;s arithmetic quietly '
          'inverts the world&rsquo;s intuitions about strength. The tactical reading every '
          'saboteur knows: complexity is vulnerability, redundancy is a rumor, and the '
          'fortress&rsquo;s weakest wall is its climate-control system. The strategic reading the '
          'Union declines to publish: their world of machines is softer to this Sphere than the '
          'Traditions&rsquo; world of stones ever was.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; rank by rank, threshold by threshold</span>',
 'name': 'Entropy',
 'outer': '<p><span class="lemma">Chance, flaw, decay, and fate.</span> One Sphere or three '
          'wearing a coat? The readings dispute. <span class="voice">The chance-readers say</span> '
          'the Sphere is probability entire and the rest is poetry: decay is slow chance, fate is '
          'chance summed, and the ladder is statistics given hands. <span class="voice">The '
          'decay-readers say</span> the arrow points the other way: the Sphere is the '
          'universe&rsquo;s one commandment &mdash; everything falls &mdash; and chance is merely '
          'how falling looks from inside a moment; hence the harm, when it finally comes, unmakes '
          'rather than bruises. <span class="voice">The fate-readers say</span> both schools '
          'mistake the mechanism for the meaning: the currents the first rank reads have '
          'direction, not just drift &mdash; the doomed man&rsquo;s tell is not a probability, it '
          'is an appointment &mdash; and the seat&rsquo;s whole Tradition stakes its license on '
          'the reading. The three schools cast identical dice to identical effect, which the '
          'Mishnah&rsquo;s drafters knew, and the dispute is therefore pure paradigm &mdash; folio '
          '567 cites this paragraph as its cleanest specimen.</p>\n'
          '        <p><span class="lemma">Physician or weapon.</span> The curse ethics, faced. '
          '<span class="voice">Some say</span> the fourth rank&rsquo;s two hands are one office: '
          'the power to gift vitality is the power to call disease, as every pharmacist&rsquo;s '
          'shelf attests, and the Sphere is no more culpable than chemistry &mdash; judge the '
          'prescriptions, not the pharmacopoeia. <span class="voice">Others say</span> the analogy '
          'flatters: chemistry does not whisper, and this Sphere&rsquo;s harm is undetectable by '
          'design &mdash; the disease that presents as disease, the ruin that files as misfortune '
          '&mdash; so the ordinary auditors of violence never convene, and the only court that can '
          'see the crime is the one the Chakravanti keep for themselves. Which is, the critics '
          'note, the jurisdiction dispute of folio 156a arriving by another door; and the '
          'defenders&rsquo; answer is the same door: name the auditors you would prefer, and '
          'notice that every candidate list begins with the people already keeping the watch.</p>\n'
          '        <p><span class="lemma">The living-pattern boundary.</span> Where exactly does '
          'the third rank end? The machine that fails is inanimate; the crop that blights is '
          'alive; and between them stand the borderline patterns &mdash; the hive, the culture in '
          'the dish, the forest that is one organism wearing ten thousand coats. <span '
          'class="voice">Some say</span> the boundary follows Life&rsquo;s jurisdiction exactly: '
          'whatever that Sphere would claim, this one touches only at the fourth. <span '
          'class="voice">Others say</span> the boundary follows complexity of pattern, not '
          'vitality &mdash; the simple living thing decays under the third rank as a rope does, '
          'and the fourth&rsquo;s threshold guards persons, not biology. The first reading is '
          'cleaner; the second matches the worked examples; the recensions decline to adjudicate, '
          'and the Storyteller inherits the file, as ever, with the tractate&rsquo;s sympathies. '
          '<span class="kw">TEYKU</span> &mdash; let the boundary lean. The boundary&rsquo;s lean, '
          'the Storyteller should note, is the folio&rsquo;s only dispute with a body count in '
          'playtest anecdote; rule it before the greenhouse scene, not during. The '
          'tractate&rsquo;s sympathies, for the record, run with the worked examples and the '
          'second school: guard persons, and let the rope and the rosebush take their chances '
          'together.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the readings, the curse, and the living line</span>',
 'rubric': 'the Sphere of the tilt, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Entropy &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 514a — Entropy: the Sphere of the tilt',
 'type': 'daf'}
