# Folio 514b - Fortune. Verso of the Entropy folio: blessing, curse, oath,
# and meme law, per the wod-llm-wiki Entropy page (M20 pp.513-514).
FOLIO = {'bottom': '<p><span class="lemma">On curses in play.</span> The slow curse is the setting&rsquo;s '
           'best horror engine and worst combat spell, and the Storyteller should keep it that '
           'way: misfortune that arrives on a schedule, plausibly, deniably, builds dread no '
           'fireball reaches, and the players&rsquo; discovery that the month&rsquo;s disasters '
           'have an author is a better reveal than any monster. Resist letting curse-work resolve '
           'in a scene; the law&rsquo;s own tempo is actuarial, and the dispel is a diagnosis '
           'story &mdash; find the author, the anchor, the grievance &mdash; not a '
           'counter-roll.</p>\n'
           '        <p><span class="lemma">On oaths at the table.</span> The bound oath is troupe '
           'glue with teeth: player characters who swear under the fifth rank have given the '
           'chronicle a live wire that hums in every scene where the promise bends. Use it seldom '
           'and draft it aloud &mdash; the wording is the working &mdash; and let NPCs treat a '
           'mage&rsquo;s bound word as the hard currency the law makes it. A setting where oaths '
           'are physics rediscovers, fast, why the old stories are full of careful phrasing.</p>\n'
           '        <p><span class="lemma">On the blessing economy.</span> Good fortune gifted is '
           'the Sphere&rsquo;s soft power, and its bills arrive socially: the blessed prosper, the '
           'neighbors notice, and the mage becomes patron, target, and single point of failure for '
           'a widening circle. Let blessings work and let them accrete obligation &mdash; the '
           'Wheel&rsquo;s people warn that fortune redirected is fortune owed somewhere, and '
           'whether or not the table&rsquo;s metaphysics agree, its dramatics should.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on slow dread, careful phrasing, and '
                'the price of luck</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Fortune is work, not weather,</span> when a will is on it: the '
           'law of the tilt names four workings and their measures.<sup>a</sup> The <span '
           'class="term">blessing</span> and the <span class="term">curse</span>: luck settled on '
           'object, tool, or &mdash; at the fourth rank &mdash; the living, for a term or for '
           'good, and the living&rsquo;s blessing and blight run aggravated in both directions, '
           'vitality and disease alike.<sup>b</sup> The <span class="term">bound oath</span>: a '
           'promise made load-bearing, its breach paying out in ruin proportioned to the binding '
           '&mdash; and the binding is rolled against the swearer&rsquo;s own will, whim cheap, '
           'conviction dear, obsession dearest.<sup>c</sup> And the <span '
           'class="term">meme</span>: an idea strengthened until it organizes lives or rotted '
           'until its holders cannot recall why they believed &mdash; the fifth rank&rsquo;s quiet '
           'crown, worked against will as the oath is.<sup>d</sup> One measure governs all four: '
           'the working leans, never authors &mdash; fortune bent past what the world could '
           'plausibly deal is no longer fortune, and the bystander of 533a begins to count. Two '
           'further measures govern. Worked fortune is legible to the first rank as natural '
           'fortune never is: the blessing has a grain, the curse a signature. And fortune '
           'redirected is fortune redistributed &mdash; the law does not say from whom, and the '
           'silence is the oldest open file in the Sphere&rsquo;s jurisprudence.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the proportion '
           'in the oath&rsquo;s ruin? <span class="kw">OUR TEACHERS TOLD:</span> a merchant prince '
           'swore peace with a rival under a Chakravanti witness and broke it within the year, '
           'judging the ruin &mdash; some run of losses, surely &mdash; a cost of doing business. '
           'The losses did not come. Instead, for a decade, every gamble he took succeeded &mdash; '
           'each windfall binding him tighter to holdings that all failed in one season, in one '
           'storm, together. He came to the witness demanding to know why the curse had waited. '
           '<span class="aside">It did not wait,</span> said the witness. <span class="aside">Ruin '
           'proportioned to the binding takes time to build; you built it.</span> The disputants '
           'around this text begin with whether that answer is law or cruelty, and end, as this '
           'Sphere&rsquo;s students always end, unable to tell fortune from sentence.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Entropy folio: the recto keeps '
             'the ladder, this side keeps the luck.',
 'folio': '514B',
 'glossL': '<p><span class="mark">a</span> On luck conferred upon objects and the living, see the '
           'third and fourth ranks of M20&rsquo;s Entropy entry, folios 513&ndash;514.</p>\n'
           '        <p><span class="mark">b</span> On aggravated vitality and disease at the '
           'fourth rank, see the same entry; the symmetry of gift and blight is the text&rsquo;s '
           'own.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the binding oath and its scale '
           '&mdash; whim to obsession, rolled against will &mdash; see the fifth rank&rsquo;s '
           'entry.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On memes crafted and destroyed, '
           'see the same; the tractate notes that the rule predates the Sleeper word and the '
           'Sleeper word proves the rule.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The oath bound here is cert&aacute;men&rsquo;s '
           'cousin and the Protocols&rsquo; enforcement clause: folio 158a&rsquo;s '
           'oaths-as-workings are this law worn Hermetically, and the Council&rsquo;s whole legal '
           'order leans on a Sphere most of its members fear.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The meme-work of the fifth '
           'rank is the Union&rsquo;s managed narrative worked retail &mdash; folio 188, wanting, '
           'will show the wholesale operation; the Masoret files the comparison where both parties '
           'can see it.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Fortune bent past '
           'plausibility crossing into 533a&rsquo;s jurisdiction is this verso&rsquo;s one hard '
           'border; the actuarial edge posted by the Later Authorities opposite is that '
           'border&rsquo;s table-side name.</p>',
 'h1': 'Fortune',
 'hagahah': 'Every culture keeps a proverb warning that luck is borrowed, not owned. The '
            'Sphere&rsquo;s masters have checked, and report the proverbs are correct in mechanism '
            'and wrong in one particular: the lender keeps no schedule, which is worse.',
 'inner': '<p><span class="lemma">Work, not weather.</span> The plain sense that governs the '
          'verso: worked fortune is a pattern with an author, and the first rank of any '
          'mage&rsquo;s Entropy reads the authorship &mdash; the blessed man&rsquo;s luck has a '
          'grain to it, a direction, a signature. Natural luck has none. The distinction is the '
          'Sphere&rsquo;s forensic science, and the reason its masters can walk into a casino, a '
          'courtroom, or a marriage and know within minutes whether anyone has been working.</p>\n'
          '        <p><span class="lemma">For a term or for good.</span> Duration&rsquo;s plain '
          'sense: luck settled on a thing spends down like any working unless made permanent, and '
          'permanence is the fourth rank&rsquo;s craft and price. The heirloom that has guarded '
          'its family for six generations is a masterwork of this law, and the chronicle that '
          'introduces one has introduced its maker, its maker&rsquo;s reasons, and the question of '
          'what was paid &mdash; three plot hooks wearing one ring.</p>\n'
          '        <p><span class="lemma">Ruin proportioned to the binding.</span> The '
          'oath&rsquo;s plain sense: the breach&rsquo;s payout scales with the oath&rsquo;s depth '
          'at swearing, not the breaker&rsquo;s remorse at breaking &mdash; the whim lightly bound '
          'pays out a bad week; the obsession bound at full depth pays out a biography. The '
          'Gemara&rsquo;s merchant teaches the corollary the young always miss: ruin is patient, '
          'and proportion may spend years assembling its instrument before the first blow '
          'lands.</p>\n'
          '        <p><span class="lemma">Until its holders cannot recall why.</span> The '
          'meme&rsquo;s plain sense, and its horror stated flatly: the fifth rank does not argue '
          'with a belief, it maintains or starves the belief&rsquo;s roots, and the subject '
          'experiences the working as his own reconsideration. No memory is edited &mdash; that is '
          'Mind&rsquo;s trespass, folio 519&rsquo;s &mdash; only the conviction&rsquo;s vitality, '
          'which makes the working invisible to every audit but the first rank&rsquo;s '
          'grain-reading, and makes the two Spheres&rsquo; border the setting&rsquo;s most '
          'litigated, as the disputants opposite attest.</p>\n'
          '        <p><span class="lemma">Fortune redistributed.</span> The conservation '
          'question&rsquo;s plain sense, stated as carefully as the law states it: the manuscripts '
          'nowhere rule that luck is conserved &mdash; the blessing is not billed to a named '
          'victim, the curse&rsquo;s ruin is not credited elsewhere &mdash; and yet the '
          'Sphere&rsquo;s working folklore, in every Tradition that holds it, warns that the '
          'redirected windfall lands on someone&rsquo;s roof. The Wheel&rsquo;s people teach it as '
          'doctrine, the gamblers as superstition, the Union&rsquo;s actuaries as regression to '
          'the mean; the law teaches only the silence, and the silence has kept the folklore '
          'honest for five centuries.</p>\n'
          '        <p><span class="lemma">The blessing has a grain.</span> The forensics clause, '
          'plainly: worked luck runs directional &mdash; the beneficiary&rsquo;s wins cluster '
          'toward the working&rsquo;s purpose, the victim&rsquo;s losses toward its grievance '
          '&mdash; and the first-rank reader assembles author from grain the way a graphologist '
          'assembles hand from stroke. The plain consequence for play: curses are attributable, '
          'eventually, to the patient, and the Sphere&rsquo;s professionals therefore work through '
          'cutouts &mdash; blessed intermediaries, cursed objects, the misfortune routed through a '
          'chain of plausible bad days &mdash; which is why the diagnosis story the Later '
          'Authorities prescribe is a story and not a roll.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; blessings, oaths, and memes</span>',
 'name': 'Fortune',
 'outer': '<p><span class="lemma">Law or cruelty.</span> The merchant&rsquo;s case, retried. <span '
          'class="voice">Some say</span> the witness spoke plain law: the oath&rsquo;s ruin is a '
          'mechanism, not a judge &mdash; the merchant loaded the spring himself, windfall by '
          'windfall, and the decade of good luck was the sentence executing, visible to any '
          'first-rank eye he declined to hire. Fortune&rsquo;s law is strict liability; the court '
          'convened at the swearing. <span class="voice">Others say</span> a law indistinguishable '
          'from vindictiveness has no business calling itself mechanism: the binding chose the '
          'cruelest possible arithmetic &mdash; hope compounded into catastrophe &mdash; and '
          'somewhere in that choosing is a chooser, whether the Sphere, the witness, or the '
          'fate-readers&rsquo; appointments ledger. The dispute is the recto&rsquo;s three '
          'readings given a victim: chance needs no chooser, decay needs no cruelty, fate needs '
          'both and supplies them. The tractate notes only that every school warns its students, '
          'in identical words, to draft oaths kindly.</p>\n'
          '        <p><span class="lemma">Fortune from sentence.</span> The deeper difficulty '
          'under the case: can worked luck be told from justice? The blessed hospice and the '
          'cursed tyrant of the recto both present as the world working properly &mdash; mercy '
          'where mercy is owed, ruin where ruin is earned &mdash; and the Sphere&rsquo;s finest '
          'workings are exactly the ones indistinguishable from desert. <span class="voice">Some '
          'say</span> this is the Sphere&rsquo;s glory: Entropy done perfectly is providence, the '
          'world nudged toward what it should have done anyway, and the seat&rsquo;s Tradition '
          'calls that reading a job description. <span class="voice">Others say</span> it is the '
          'abyss with a level gaze: a power that cannot be told from justice will be used in '
          'justice&rsquo;s name by everyone who holds it, and the word for engineered desert is '
          'not providence but propaganda with better dice. Folio 224, when it is written, will '
          'want this paragraph; the Wheel&rsquo;s watchers already have it memorized.</p>\n'
          '        <p><span class="lemma">His own reconsideration.</span> The meme border, '
          'litigated. <span class="voice">Some say</span> the Mind line holds firm: Entropy '
          'touches the belief&rsquo;s fortunes and never its content &mdash; no thought is '
          'inserted, no memory touched, and the subject&rsquo;s mind does all its own work, merely '
          'on tilted ground. The working is to persuasion what the loaded die is to the throw: the '
          'hand still throws. <span class="voice">Others say</span> the distinction comforts the '
          'caster and not the cast: a man whose conviction was starved to death by another&rsquo;s '
          'will has been changed against his will, whatever organ did the dying, and the consent '
          'law that folio 519 will demand for Mind&rsquo;s trespasses is owed here identically or '
          'it is owed nowhere. The strict school answers that by that measure all rhetoric is '
          'trespass; the reply, from the Ecstatics&rsquo; corner of the room, is that rhetoric can '
          'be argued with, and the whole point of the fifth rank is that it cannot. <span '
          'class="kw">TEYKU</span> &mdash; let the border stand watch on both sides. The '
          'border&rsquo;s watchers on both sides agree, at least, on the case that settles '
          'nothing: the sincere convert whose conviction was starved and who is grateful &mdash; '
          'the Sphere&rsquo;s version of the question every chapter of this tractate has asked '
          'once, and answered never.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the merchant, providence, and the meme border</span>',
 'rubric': 'the law of worked luck',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of fortune &middot; blessings, curses, oaths, and memes',
 'title': 'Tractate Aliyah · Folio 514b — Fortune: the law of worked luck',
 'type': 'daf'}
