# Folio 515b - Conjunctions. Verso of the Forces folio: the law of joint
# workings, the named partnerships, specialties, and Resonance. Facts per
# the wod-llm-wiki Forces page (M20 pp.514-515) and 533a's rating law.
FOLIO = {'bottom': '<p><span class="lemma">On bookkeeping.</span> A conjunction is one working: one '
           'declaration, one roll, one price. The table that rolls each partner Sphere '
           'separately has invented a tax the law never levied, and the table that lets the '
           'lowest Sphere set the difficulty has invented a discount. Rate by the highest, '
           'roll once, and spend the successes as one pool &mdash; and when a player begins '
           'assembling four-Sphere contraptions in initiative, remember that the declaration '
           'must still fit in a sentence a bystander could fail to understand. If it takes a '
           'paragraph, it is a ritual, and rituals have their own folio, 500b.</p>\n'
           '        <p><span class="lemma">On the shield economy.</span> The walking '
           'force-shield is where conjunction law meets the chronicle&rsquo;s pacing. Priced '
           'honestly &mdash; a working maintained, a vulgarity question asked every scene it '
           'is up, the collector of folio 533a reading the meter &mdash; armor becomes a '
           'decision instead of a default, which is what the fight scenes need it to be. A '
           'table that waves the shield through as ambient costume has quietly repealed '
           'half the Sphere&rsquo;s danger, and will discover the repeal at the worst '
           'moment, from the wrong side.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Require the partnership in '
           'the declaration: which Spheres, what each contributes, in plain words, before '
           'the roll &mdash; the same discipline folio 533a demands of vulgarity, extended '
           'to anatomy. It settles the rating (highest named Sphere), it settles the '
           'creation question (Prime named or the working found), and it leaves a record '
           'when the hung effect discharges three scenes later and everyone has forgotten '
           'what was loaded into it. The Storyteller&rsquo;s ruling arrives once, at '
           'declaration; after the roll there is nothing left to argue with but the '
           'dice.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on pricing joint workings, and on '
                'declaration discipline</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">No Sphere works alone for long.</span> A working that '
           'employs several Spheres is one working: it is rated by the highest Sphere '
           'employed, rolled once, and priced once &mdash; so folio 533a has already '
           'ruled.<sup>a</sup> Creation takes <span class="term">Prime</span> as senior '
           'partner: force from nothing wants Prime&rsquo;s second rank, as the recto '
           'holds.<sup>b</sup> The other partnerships the law names: with <span '
           'class="term">Matter</span> or <span class="term">Life</span>, a body may be made '
           'to draw or repel the flows &mdash; the shield, the lodestone, the walking '
           'calm;<sup>c</sup> with <span class="term">Entropy</span>, energies are eroded or '
           'enriched; with <span class="term">Mind</span>, thought is made force; with <span '
           'class="term">Spirit</span>, the ephemeral is made force; with <span '
           'class="term">Time</span>, a force is stored against a trigger, the bolt hung in '
           'the air of an appointed hour. The partnership is declared with the working: an '
           'organ unnamed is an organ unpaid, and the working fails of it. And a standing '
           'working stands while its successes last; what endures is maintained, and what '
           'is maintained is priced for its whole stay.</p>\n'
           '        <p>Two further laws. At the fourth rank a mage takes a <span '
           'class="term">specialty</span> &mdash; a province of the Sphere that answers her '
           'doubly, every perfect die counting twice.<sup>d</sup> And great workings leave '
           '<span class="term">Resonance</span>: the storm remembers who called it, and '
           'masters of the fifth rank are called, by everyone but themselves, <span '
           'class="term">Nukes</span>.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'partnerships at work. A mage walks a riot unharmed: Forces with Matter and Life, '
           'her coat and skin taught to refuse momentum &mdash; the shield, and the crowd '
           'saw luck. A duelist hangs lightning in an empty doorway against the hour her '
           'enemy crosses it: Forces with Time, the bolt stored and the trigger set, and the '
           'Paradox &mdash; ask the disputants when the Paradox is weighed, for the working '
           'was vulgar when cast and unwitnessed when it fired. A master, hard pressed, '
           'becomes the lightning: Life&rsquo;s fifth rank riding Forces&rsquo; third, flesh '
           'to current and back, and the books mark the feat possible and the practitioners '
           'mark it terrifying. And one who reshapes the weather over a county leaves her '
           'signature in it for a season &mdash; which is the fifth rank&rsquo;s true price, '
           'and the disputants&rsquo; fourth case.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy '
             'Old Style after the M20 interior &middot; verso of the Forces folio: the ladder '
             'stood alone on the recto, and here learns company.',
 'folio': '515B',
 'glossL': '<p><span class="mark">a</span> On rating by the highest Sphere employed, see the '
           'Paradox and casting discussions cited at folio 533a; the rule is theirs, applied '
           'here.</p>\n'
           '        <p><span class="mark">b</span> On the conjunctional partnerships of '
           'Forces &mdash; Prime for creation, Matter and Life for attraction and repulsion, '
           'Entropy, Mind, Spirit, and Time each named &mdash; see M20, the Forces entry, '
           'folios 514&ndash;515.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On flesh become current '
           '&mdash; Life&rsquo;s mastery riding Forces&rsquo; third rank &mdash; see the '
           'same entry&rsquo;s catalogue of combined effects.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On Sphere specialties at the '
           'fourth rank and the doubled tens, and on the provinces named for Forces &mdash; '
           'motion, the elements, weather, weaponry, and their kin &mdash; see the Sphere '
           'chapter&rsquo;s head-matter in M20.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto holds the ladder; this verso holds '
           'its company. The ledger test of 515a &mdash; where is the increase drawn from '
           '&mdash; is assumed throughout, and Prime is the answer&rsquo;s banker.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The hung bolt&rsquo;s '
           'Paradox question is 533a&rsquo;s jurisdiction &mdash; the pool that discharges '
           'at once or hangs like a stormcloud is described there; this folio merely arms '
           'the ambiguity.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Prime&rsquo;s own folio '
           'is 520 and Time&rsquo;s is 522; the creation co-requirement is staged in full at 517 and 520, as the recto&rsquo;s gloss promised.</p>',
 'h1': 'Conjunctions',
 'hagahah': 'Masters of the fifth rank are called Nukes. No one has ever introduced herself '
            'as one. The Resonance handles the introductions, which is the joke: the one '
            'Sphere that can be worked invisibly signs its masterpieces.',
 'inner': '<p><span class="lemma">One working.</span> The plain sense of the rating law: '
          'conjunction is anatomy, not addition. The Spheres named are organs of a single '
          'effect &mdash; one intention, one roll of Arete, one difficulty set by the '
          'highest organ, one Paradox assessment. Nothing about employing three Spheres '
          'makes a working three times anything; it makes it one working that could not '
          'have been simpler.</p>\n'
          '        <p><span class="lemma">Prime as senior partner.</span> Senior because '
          'the question it answers is the recto&rsquo;s ledger question: where is the '
          'increase drawn from? Control and transmutation spend what the scene holds; '
          'creation spends what nothing holds, and Prime is the Sphere of that nothing. '
          'The partnership is not a tax on ambition but an honest accounting of it &mdash; '
          'the working that mints force must name the mint.</p>\n'
          '        <p><span class="lemma">The shield, the lodestone, the walking '
          'calm.</span> The attraction-and-repulsion clause is the Sphere&rsquo;s whole '
          'defensive wing, and note its grammar: the body is <span class="aside">made '
          'to</span> draw or refuse the flows &mdash; the working is done to a pattern, '
          'which is why Matter or Life must stand in the partnership. The bullet turned '
          'aside on the recto was one errand; the coat that refuses all bullets is a '
          'standing law, and standing laws are maintained, priced, and &mdash; the '
          'disputants will insist &mdash; witnessed.</p>\n'
          '        <p><span class="lemma">Thought is made force, the ephemeral is made '
          'force.</span> The Mind and Spirit partnerships read as exotica and are the '
          'quiet workhorses of two whole practices: the martial artist whose intention '
          'arrives as impact, and the shaman for whom the spirit world&rsquo;s weather is '
          'a power grid. Same law, two liturgies &mdash; the recto&rsquo;s Masoret said as '
          'much of the whole Sphere.</p>\n'
          '        <p><span class="lemma">An organ unnamed is an organ unpaid.</span> The '
          'declaration clause&rsquo;s plain sense: the anatomy is stated before the roll '
          '&mdash; which Spheres, doing what &mdash; and a working that turns out to need '
          'a Sphere nobody named does not get it retroactively. The clause protects the '
          'player as much as the table: a declared anatomy is a contract, and no '
          'Storyteller may bill it afterward for organs the ruling never asked to see.</p>\n'
          '        <p><span class="lemma">While its successes last.</span> Duration&rsquo;s '
          'plain sense: successes are the working&rsquo;s food, and a standing effect '
          'spends them as a lamp spends oil. The shield that must last the night wants '
          'more successes than the shield that must last the volley &mdash; which is the '
          'law&rsquo;s quiet answer to the armor question opposite: the coat that refuses '
          'all bullets forever was never one working, and was never priced like one.</p>\n'
          '        <p><span class="lemma">Stored against a trigger.</span> The Time '
          'partnership&rsquo;s plain sense: the working is complete at casting &mdash; '
          'rolled, rated, and paid for &mdash; and only its discharge is deferred. The '
          'hung bolt is not a spell waiting to be cast but a verdict waiting to be read, '
          'which is precisely why the disputants&rsquo; question about its Paradox has '
          'teeth.</p>\n'
          '        <p><span class="lemma">Every perfect die counting twice.</span> The '
          'specialty&rsquo;s plain sense: within her province &mdash; motion, weather, '
          'the elements, weaponry, whichever the fourth rank chose &mdash; the '
          'master&rsquo;s tens count double. It is the only clause on this page that '
          'rewards narrowness, and it is why old masters are famous for one thing: the '
          'law pays them to be.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the partnerships, clause by clause</span>',
 'name': 'Conjunctions',
 'outer': '<p><span class="lemma">Rated by the highest Sphere employed.</span> Clean in '
          'law, gamed in practice. <span class="voice">Some say</span> the rating rule '
          'invites shopping: the cunning player describes every effect in the vocabulary '
          'of her cheapest Sphere &mdash; the bullet turned by luck (Entropy) rather than '
          'motion (Forces), the guard asleep by fatigue (Life) rather than suggestion '
          '(Mind) &mdash; and the same fiction arrives at a friendlier price. <span '
          'class="voice">Others say</span> the shopping is the game working as intended: '
          'paradigm is precisely the art of describing the world in one&rsquo;s own '
          'vocabulary, and a mage who can honestly frame the effect within a Sphere she '
          'holds has done magick&rsquo;s actual work. The test is honesty of mechanism, '
          'not thrift: if the guard sleeps because his body tires, Life it is; if he '
          'sleeps because his mind was told to, no discount survives the telling. The '
          'Storyteller audits the anatomy, and the declaration discipline below the page '
          'exists for exactly this audit.</p>\n'
          '        <p><span class="lemma">The coat that refuses all bullets.</span> Is '
          'the standing shield a standing vulgarity? <span class="voice">Some say</span> '
          'no working is vulgar in itself while nothing impossible shows: the shield '
          'that is never tested is a coat, and a tested shield is one lucky miss &mdash; '
          'judge each event as it comes. <span class="voice">Others say</span> a '
          'standing law is a standing assertion: the mage wears a private physics, and '
          'the Omniscient Observer of 533a &mdash; who watched the invisible working on '
          'the recto &mdash; watches the invisible armor too; the tenth bullet turned in '
          'one night is not ten coincidences, it is one paradigm in public. Both '
          'readings agree on the endpoint and differ on the meter: whether Paradox '
          'reads the shield per event or per evening. The table&rsquo;s choice of meter '
          'is, as ever, a choice of genre &mdash; action serial or slow siege.</p>\n'
          '        <p><span class="lemma">When the Paradox is weighed.</span> The hung '
          'bolt: vulgar at casting, unwitnessed at discharge &mdash; or the reverse. '
          '<span class="voice">Some say</span> at casting, and only then: the working '
          'was complete when rolled, the offense &mdash; folio 533a&rsquo;s word &mdash; '
          'is the attempt, and what the trigger later does is consequence, not crime. '
          '<span class="voice">Others say</span> the assessment attends the assertion, '
          'and the assertion is the discharge: nothing impossible existed until the '
          'doorway filled with lightning, so nothing was assessable before. The first '
          'reading lets a mage pre-pay quietly for a public impossibility; the second '
          'lets her cast loudly and detonate deniably; each reading has a loophole '
          'shaped exactly like the other&rsquo;s virtue. The recto ruled that Paradox '
          'pools <span class="aside">and hangs like a stormcloud</span> &mdash; the '
          'manuscripts of 533a, consulted, decline to say which cloud this is. <span '
          'class="kw">TEYKU</span> &mdash; let the bolt hang.</p>\n'
          '        <p><span class="lemma">The storm remembers who called it.</span> '
          'Resonance as signature: the master who works at the scale of weather cannot '
          'work anonymously, whatever her stealth, for the working itself testifies '
          '&mdash; to other mages, to the Union&rsquo;s instruments, to anything that '
          'reads the world closely. <span class="voice">Some say</span> this is the '
          'fifth rank&rsquo;s hidden governor, kinder than Paradox and more patient: '
          'the Nuke is deterred not by price but by attribution. <span '
          'class="voice">Others say</span> it is the last laugh of the recto&rsquo;s '
          'thesis &mdash; the folio that began with witnesses ends with a Sphere that '
          'manufactures its own: work quietly enough at great enough scale, and the '
          'world itself becomes the witness the mage removed. As folio 3a says: all of '
          'this law is the law of who is watching. Even the weather takes minutes.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; '
               'four difficulties: the shopper, the shield, the hung bolt, and the '
               'signature</span>',
 'rubric': 'no Sphere works alone',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of conjunctions &middot; the law of joint workings',
 'title': 'Tractate Aliyah · Folio 515b — Conjunctions: no Sphere works alone',
 'type': 'daf'}
