# Folio 515a - Forces. The Phase-1 Sphere-mold proof (SPEC section 7):
# dot ladder as Mishnah, rank-boundary disputes as the outer commentary.
FOLIO = {'bottom': '<p><span class="lemma">On the third dot.</span> The rank that conjures is the rank '
           'that changes the chronicle. A cabal with Forces 3 in it has an action movie in its '
           'luggage whether or not anyone packed one, and the Storyteller&rsquo;s tool is not '
           'prohibition but honest pricing: vulgarity ruled before the roll, witnesses counted, '
           'backlash delivered when owed, and the surcharge cutting both ways &mdash; the '
           'enemy has physicists too. Reward the quiet verbs. The player who dims the lights, '
           'hushes the alley, and cools the gun in the guard&rsquo;s holster is playing the same '
           'Sphere as the one who throws fire, at a fraction of the price, and the table that '
           'notices this discovers that Forces is a burglar&rsquo;s Sphere wearing a '
           'soldier&rsquo;s reputation.</p>\n'
           '        <p><span class="lemma">On the fourth dot and past it.</span> At control of the '
           'major, the chronicle changes scale or breaks. A mage who can steer weather and silence '
           'grids has outgrown alley fights; give her problems the size of her reach &mdash; a '
           'storm that must be held off a coastline for three nights, a blackout that must look '
           'like an accident to two million witnesses &mdash; and let the Technocracy function as '
           'the thermostat it claims to be: every major working is a signal flare, and the '
           'response arrives in proportion. Collateral is the genre now. Say so in session zero, '
           'and decide together whether the table wants disaster-movie stakes or wants the master '
           'to spend her rank mostly on not using it.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Post three rulings beside the '
           'vulgarity standard of folio 533a before play begins. First, the ledger: when a player '
           'amplifies a force, ask aloud where the increase is drawn from, and let the answer '
           'sort second rank from third &mdash; the question settles most boundary fights before '
           'they start. Second, the sky: declare whether ambient charge, heat, and motion count '
           'as present forces a controller may draw on, or whether that reading is creation in a '
           'borrowed coat. Third, the surcharge: say how harm is reckoned and stick to it, for '
           'a duelist&rsquo;s arithmetic depends on it. A Forces ruling improvised mid-combat is a '
           'precedent whether the table meant it or not; the Sphere generates case law faster '
           'than any other, because its cases explode.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on what the ladder does to a chronicle, '
                'and on procedure at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Forces is the Sphere of energies:</span> heat and cold, light '
           'and dark, sound, motion, the current in the wire, the pull of the earth &mdash; every '
           'flow that passes through the world without being a thing in it.<sup>a</sup> Its '
           'ladder climbs by two measures at once: what is done, and to how much.</p>\n'
           '        <p>At the first rank the mage <span class="term">perceives</span>: she reads '
           'the flows as a scholar reads a page &mdash; sees the heat of a hand on a cold rail, '
           'hears the current behind the wall, follows the bullet while it flies. At the second '
           'she <span class="term">controls the minor</span>: what already burns, shines, or '
           'moves at a human scale answers her, aimed, dampened, quickened, or turned.<sup>b</sup> '
           'At the third she <span class="term">transmutes the minor</span>: force becomes other '
           'force at her word, and force stands up where none was &mdash; with Prime&rsquo;s '
           'leave &mdash; at the same modest scale.<sup>c</sup> The fourth rank is the second '
           'writ large, <span class="term">control of the major</span>: the storm steered, the '
           'grid stilled, the river&rsquo;s push redirected. The fifth is the third writ large: '
           'transmutation and creation at the scale of weather.</p>\n'
           '        <p>Two laws attend every rung. Harm worked through Forces is reckoned <span '
           'class="term">one success the heavier</span>: the mage opens a door, and the '
           'world&rsquo;s own arsenal adds a round of its own.<sup>d</sup> And no Sphere is '
           'easier to see: fire from an '
           'open palm convicts itself, and the law of the vulgar and the coincidental &mdash; '
           'tried at folio 533a &mdash; attends the Forces mage like a bailiff.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'cases the ladder was built to sort. A bullet flies at the mage&rsquo;s chest and she '
           'turns it aside: control of motion that exists &mdash; the second rank, and the crowd '
           'saw a miss. A candle gutters and she fans it to a torch: the second rank still, say '
           'some, for the flame was there to be fed. She snaps her fingers over a bare table and '
           'fire stands up out of nothing: the third rank, and Prime&rsquo;s leave besides. '
           'Lightning takes her enemy out of a storm: the fourth &mdash; the charge was the '
           'sky&rsquo;s, and she only signed for its delivery. Lightning takes him out of a clear '
           'blue noon: ask the disputants, whose arguments surround this text, where in a '
           'cloudless sky the lightning was waiting.</p>',
 'chapter': 'Chapter the Eleventh',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; first of the nine Sphere folios; its siblings '
             'are wanting, and folio 533a waits past the lacuna to price everything ruled here.',
 'folio': '515A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Forces entire &mdash; its kinds of '
           'energy, its ranks, its worked examples &mdash; see M20, the Spheres chapter, folio '
           '515, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the rungs minor and major across the '
           'recensions, see the Sphere chapters of Revised and 2nd ed.; the rungs keep their '
           'shape and shift their reach.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On creation demanding '
           'Prime&rsquo;s leave &mdash; the conjunctional requirement &mdash; see the casting '
           'procedures and the Prime entry; the fight over its extent is staged at folios 517 '
           'and 520, which are wanting.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the added success of harm, '
           'and on great workings of this Sphere as notorious gatherers of Paradox, see the '
           'Sphere&rsquo;s M20 entry and the discussions of magickal feats in the systems '
           'chapters.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of Forces among the Nine is the Order '
           'of Hermes (folio 158 &mdash; wanting); the Union&rsquo;s iterators prize the Sphere '
           'no less (folio 186 &mdash; wanting). One ladder, two liturgies.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> This folio is secretly '
           'about witnesses, as folio 3a says all of them are: vulgarity is tried at 533a, the '
           'census of eyes at 533b, and the invisible working below is that trial re-armed.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The world harms without a '
           'Sphere&rsquo;s help: fire, fall, and current are catalogued in the hazards luach '
           '(folio 435 &mdash; wanting), where the fireball and the house fire part ways in '
           'law.</p>',
 'h1': 'Forces',
 'hagahah': 'Every apprentice&rsquo;s first question is the fireball. Every master&rsquo;s final '
            'answer is the match &mdash; struck coincidentally, in a dry room, at the correct '
            'moment. The apprentices are never persuaded, and remain unpersuaded right up until '
            'their first sprinkler system.',
 'inner': '<p><span class="lemma">Every flow that passes through the world.</span> The test of '
          'jurisdiction: a force can be poured from one vessel into another without remainder. '
          'Matter holds things and Life holds living things; Forces holds what moves through and '
          'between them &mdash; the heat, not the iron; the current, not the wire; the motion, '
          'not the bullet. Where a working seems to touch two Spheres, ask what changed: if the '
          'thing remains and only its energies were rearranged, this ladder suffices '
          'alone.</p>\n'
          '        <p><span class="lemma">She reads the flows.</span> The first rank is not '
          'sight but literacy, and it is the gate to everything above: no rung of this ladder '
          'works blind, and the master who steers a storm is still, in the working&rsquo;s first '
          'instant, reading it. Perception is also the rank the new player skips in her mind and '
          'should not at the table &mdash; seeing the current in the wall is half of every '
          'heist this Sphere will ever run.</p>\n'
          '        <p><span class="lemma">What already burns.</span> Control&rsquo;s plain sense '
          'is a ledger: existence first, then obedience. The second rank adds nothing to the '
          'world; it reallocates what the scene already contains. The redirected bullet is the '
          'clean case &mdash; its motion is conserved and only its errand changes &mdash; and '
          'the dimmed lamp, the hushed room, and the quickened fall are the same ruling in '
          'other clothes.</p>\n'
          '        <p><span class="lemma">At a human scale.</span> Minor means the room, the '
          'man, the machine: forces a body might plausibly meet and survive meeting. Major '
          'means the storm, the grid, the river &mdash; forces that have neighborhoods. The '
          'boundary is judged, not measured, and the judge is the Storyteller; the ladder gives '
          'her the words to rule with, not a gauge.</p>\n'
          '        <p><span class="lemma">Force becomes other force.</span> Transmutation is '
          'the third rank&rsquo;s native verb: light to heat, sound to motion, the punch '
          'arriving as a shove of cold. Creation is its guest verb, and the guest pays board '
          '&mdash; conjuring force from nothing wants Prime&rsquo;s leave, as the gloss beside '
          'the text records. The working mage lives at this rank; most of what the Sphere is '
          'famous for happens here.</p>\n'
          '        <p><span class="lemma">The second writ large.</span> Note what mastery is '
          'not: no new verbs. The fourth and fifth ranks repeat the second and third with the '
          'world for a workbench, and the apprentice who understands the ledger at rank two '
          'already understands the hurricane &mdash; she merely cannot afford it yet.</p>\n'
          '        <p><span class="lemma">One success the heavier.</span> The plain sense: when '
          'a Forces working deals harm, add one success to the damage count. The law&rsquo;s '
          'reason is the Sphere&rsquo;s nature &mdash; the mage does not swing energy like a '
          'club; she opens a door and the world&rsquo;s own arsenal walks through. The duelist '
          'should read this clause twice: it is why the physicist is feared in the circle.</p>\n'
          '        <p><span class="lemma">Like a bailiff.</span> Kinetic spectacle is '
          'vulgarity&rsquo;s home genre, and this Sphere is its leading employer. But note the '
          'quiet arts: cooling, dimming, hushing, slowing. Forces worked subtractively is the '
          'most coincidental magick in the book &mdash; nothing happened, which no bystander '
          'ever disputes &mdash; and the disputants opposite will ask what that concession is '
          'worth when the working is invisible by design.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; rank by rank, boundary by boundary</span>',
 'name': 'Forces',
 'outer': '<p><span class="lemma">The flame was there to be fed.</span> The great boundary case '
          'of the whole ladder. <span class="voice">Some say</span> fanning is control in its '
          'plain sense: a flame is a process, not a thing, and to feed a process is only to '
          'indulge its nature &mdash; the candle wanted to be a torch, and the second rank let '
          'it. <span class="voice">And some say</span> increase beyond the fuel is creation on '
          'the installment plan: the wax can pay for an inch of fire, and every inch past that '
          'is minted from nothing, which is the third rank&rsquo;s business under whatever '
          'name. An objection to the second view: then every amplification is creation, and the '
          'second rank is empty &mdash; a rung with no cases is no rung. <span '
          'class="voice">Answer:</span> the second rank spends what the scene holds; ask where '
          'the increase is drawn from &mdash; the draft through the door, the oil on the table, '
          'the powder in the next cartridge &mdash; and rule by the ledger. A flame fanned with '
          'the room&rsquo;s own air is found; a flame fanned with nothing is minted.</p>\n'
          '        <p><span class="lemma">Where in a cloudless sky the lightning was '
          'waiting.</span> <span class="voice">Some say</span> the sky is a battery that is '
          'never empty: charge rides every noon, and the storm is merely a convenience for '
          'weaker hands &mdash; the clear-sky bolt is the fourth rank being resourceful. <span '
          'class="voice">Others say</span> a rank cannot be read out of the ladder: if ambient '
          'traces license everything, creation names nothing, and the fifth rung dangles over '
          'an empty docket. On this reading the clear-sky bolt is creation at the scale of '
          'weather, and the mage who wants the cheap version can wait for clouds like everyone '
          'else. The first reading flatters clever players; the second keeps the ladder honest; '
          'the table&rsquo;s ruling on the sky decides a hundred later cases, and should be '
          'made in daylight, in session zero, not at midnight in initiative.</p>\n'
          '        <p><span class="lemma">One success the heavier.</span> The manuscripts do '
          'not quarrel over whether Forces hits harder; they quarrel over what the surcharge is '
          '<span class="aside">for</span>. <span class="voice">Some say</span> it is physics '
          'honored: energy scales murderously in the world, and a game that priced the lightning '
          'like the dagger would be lying about lightning. <span class="voice">Others say</span> '
          'any surcharge tilts the circle &mdash; it makes Forces the default Sphere of war, and '
          'flattens nine arts into one artillery piece with eight hobbies. <span '
          'class="voice">Answer</span>, from the law&rsquo;s own ledger: the heavy hand pays a '
          'heavy tithe. Great workings of this Sphere want many successes, and every success '
          'courts the collector of folio 533a &mdash; the surcharge on harm is repaid in '
          'Paradox, with interest, and the artillery piece is the piece most often heard.</p>\n'
          '        <p><span class="lemma">Fire from an open palm convicts itself.</span> Then '
          'what of the working no eye could catch? The mage who stops a heart with a whisper of '
          'current, who cooks the lock&rsquo;s tumblers from across the street &mdash; unseen, '
          'unheard, unfelt until felt once. <span class="voice">Some say</span> coincidental: '
          'the imagined bystander of 533a balks at nothing, for there is nothing to balk at '
          '&mdash; a man fell, a lock stuck, the world shrugs. <span class="voice">Others '
          'say</span> the Omniscient Observer of that same folio was convened for exactly this '
          'case: the world itself keeps the ledger, and energy from nowhere is vulgar however '
          'politely it arrives. Note what the dispute is really about &mdash; not stealth but '
          'jurisdiction, whose eyes the law consults; which is to say this folio ends where '
          'every folio ends, at 533a, buying ammunition for a standard it cannot choose for '
          'you.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; four boundary '
               'disputes: the fanned flame, the clear sky, the doubled count, and the invisible '
               'working</span>',
 'rubric': 'control, creation, and the ledger between them',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick &middot; '
             'of the Sphere of Forces &middot; the dot ladder as law, with its boundary disputes',
 'title': 'Tractate Aliyah · Folio 515a — Forces: control, creation, and the ledger between them',
 'type': 'daf'}
