# Folio 516b - Healing. Verso of the Life folio: the healer's law, per the
# Verbena Tradition book via the wod-llm-wiki (TB Verbena Rev pp.59-63).
FOLIO = {'bottom': '<p><span class="lemma">On healing as drama.</span> The once-per-scene clause is the '
           'Storyteller&rsquo;s friend: it makes triage real &mdash; who gets the scene&rsquo;s '
           'healing, who waits bleeding for the next &mdash; and triage is drama the fireball '
           'never was. Enforce it evenly, telegraph it early, and the cabal&rsquo;s healer becomes '
           'the character with the campaign&rsquo;s hardest choices, which is what her player '
           'signed up for whether she knew it or not.</p>\n'
           '        <p><span class="lemma">On the deathbed clock.</span> Restoration of the newly '
           'dead &mdash; hours equal to the master&rsquo;s enlightenment, and only if a spark '
           'remains &mdash; is the setting&rsquo;s most merciful rule and its best ticking clock. '
           'Use it as written: the drowned child, the master three cities away, the arithmetic of '
           'hours done aloud at the table. And respect the spark clause &mdash; some deaths are '
           'complete, the law says so, and a table where nothing stays dead has spent the '
           'Sphere&rsquo;s gravest scene for a convenience.</p>\n'
           '        <p><span class="lemma">On the death curse.</span> The slow harm clause &mdash; '
           'damage spread across an interval, presenting as illness &mdash; is horror content and '
           'should clear the table&rsquo;s lines and veils before it appears; it is also the one '
           'working on this page whose author every Tradition&rsquo;s law condemns unprovoked. '
           'When it appears, let it be what the books make it: the weapon of the desperate and the '
           'wicked, whose cure is a diagnosis story &mdash; find the worker, not the germ &mdash; '
           'and whose use by a player character should cost what the Verbena say it costs, which '
           'is standing, sleep, and the World Tree&rsquo;s stain.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on triage, the clock of hours, and '
                'the curse</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The healer&rsquo;s law is a ladder inside the ladder.</span> At '
           'the first rank, the healer&rsquo;s sight: the ailment read, its source named, the '
           'physician&rsquo;s craft sharpened by every success. At the second, the self restored: '
           'her own hurts closed two measures to the success, at once, without ration. At the '
           'third, the simple and the gentle: green things and small lives mended, and the bruises '
           'of her neighbors. At the fourth, the whole art: any hurt on any living pattern, even '
           'the aggravated wounds that unmake. At the fifth, the door itself: the newly dead '
           'restored, if a spark remains, within hours numbered by the healer&rsquo;s own '
           'enlightenment.<sup>a</sup> Three measures govern. A body is healed once in a scene, '
           'and no oftener, however many hands attend it.<sup>b</sup> The healing of aggravated '
           'harm is always vulgar and works at half strength: what unmakes patterns is not quietly '
           'remade.<sup>c</sup> And the same knowledge cuts &mdash; harm worked by this law needs '
           'no aim and permits no dodge, and may be spread across an interval so that murder '
           'presents as illness; the law names this the death curse and every code in this '
           'tractate names it last-resort or forbidden.<sup>d</sup> And the healer&rsquo;s sight '
           'governs the whole ladder: no wound is closed unread, no restoration attempted '
           'undialgnosed &mdash; the art&rsquo;s first rank is its standing malpractice law.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the ration of '
           'one healing to a scene? <span class="kw">OUR TEACHERS TOLD:</span> a young witch, her '
           'coven-sister dying faster than her successes could close the wounds, healed and healed '
           'again in one desperate hour, and the pattern &mdash; handled at the root, over and '
           'over, like cloth wrung twice &mdash; stopped taking the stitch. The elders ruled what '
           'the recensions all rule: the pattern must settle before it is worked again, and the '
           'ration is not a punishment but the flesh&rsquo;s own reading speed. The sister lived, '
           'scarred; the witch keeps the scar&rsquo;s twin on her own arm, self-cut, remembering; '
           'and the disputants around this text begin with what the ration implies about whose law '
           'healing finally is &mdash; the healer&rsquo;s, the patient&rsquo;s, or the '
           'pattern&rsquo;s.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Life folio: the recto keeps the '
             'ladder, this side keeps the ward.',
 'folio': '516B',
 'glossL': '<p><span class="mark">a</span> On the healing ladder rank by rank &mdash; sight to '
           'restoration &mdash; see the Verbena Tradition book&rsquo;s treatment of Life magicks, '
           'which this page restates as law.</p>\n'
           '        <p><span class="mark">b</span> On one healing to a scene, see the same '
           'chapters; the clause binds the patient, not the healer.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On aggravated healing as always '
           'vulgar and half-effective, see the same; folio 406 keeps the injury '
           'ledger this clause writes into.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On harm undodgeable and unarmored, '
           'and on damage spread over an interval &mdash; the death curse &mdash; see the same '
           'chapters&rsquo; harming law.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The healer&rsquo;s ladder is the Verbena&rsquo;s '
           'house law, folio 162a, and its idiom shows &mdash; but the law binds every Life-worker '
           'identically, Progenitor vats included; one ladder, many liturgies, the chapter&rsquo;s '
           'refrain.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The restoration '
           'clause&rsquo;s clock &mdash; hours equal to enlightenment &mdash; is the '
           'tractate&rsquo;s only rule that prices Arete in mercy; the Masoret sets it beside '
           '148b&rsquo;s Wheel and 156a&rsquo;s license as chapter V&rsquo;s three doctrines of '
           'death, here given mechanics.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The death curse is '
           'fortune&rsquo;s cousin from folio 514b worked in flesh, and the two folios&rsquo; '
           'Later Authorities give the same advice independently, which the tractate finds as '
           'close to proof as advice comes.</p>',
 'h1': 'Healing',
 'hagahah': 'Every healing tradition among the Sleepers ends its oath with some form of <em>and do '
            'no harm</em>. The Sphere&rsquo;s version cannot: the same rank that seals the wound '
            'opens it, and the oath, if the law were honest enough to write one, would end <em>and '
            'choose</em>. The Verbena, being honest, carry knives.',
 'inner': '<p><span class="lemma">Two measures to the success, at once.</span> The self-healing '
          'clause&rsquo;s plain sense: the mage&rsquo;s own repair is the art&rsquo;s fastest and '
          'cheapest form &mdash; instant, unrationed by allocation, the native text read at native '
          'speed. The recto&rsquo;s asymmetry cashes out here as mechanics: whatever the asymmetry '
          'is &mdash; anatomy, ethics, interlock &mdash; its dividend is that a Life mage is the '
          'hardest person at the table to keep down.</p>\n'
          '        <p><span class="lemma">However many hands attend it.</span> The ration&rsquo;s '
          'plain sense, and note whom it binds: the patient, not the healer. Two masters cannot '
          'stack their scenes on one body; the pattern settles at its own speed regardless of who '
          'is stitching. The tactical consequence is the triage the Later Authorities bless: '
          'healing is a scarce slot per casualty per scene, and the field decisions this forces '
          'are the Sphere&rsquo;s real skill test, no dice involved.</p>\n'
          '        <p><span class="lemma">Not quietly remade.</span> The aggravated clause&rsquo;s '
          'plain sense: the worst wounds &mdash; the claw of the twice-natured, this '
          'Sphere&rsquo;s own harm, the fires of folio 515a &mdash; are unmakings, and their '
          'repair is loud by nature: always vulgar, always half-speed, always a scene the '
          'bystander of 533a could balk at. The healer of aggravated harm therefore works in '
          'sanctums and safehouses, and the chronicle&rsquo;s wounded are moved before they are '
          'mended, which is a logistics genre the Storyteller gets free.</p>\n'
          '        <p><span class="lemma">If a spark remains.</span> The restoration '
          'clause&rsquo;s plain sense, read narrowly as the law means it: this is not resurrection '
          'but retrieval &mdash; the pattern newly stopped, the spark not yet gone to the '
          'Wheel&rsquo;s jurisdiction, the clock running in hours and the hours counted against '
          'the healer&rsquo;s enlightenment, not her need. Past the clock, past the spark, the law '
          'is silent, and the silence is load-bearing: what lies past it belongs to Tractate '
          'Neshiyah&rsquo;s dead and folio 156a&rsquo;s Wheel, and every attempt to build in the '
          'silence is catalogued, without exception, in folio 224&rsquo;s territory.</p>\n'
          '        <p><span class="lemma">No wound is closed unread.</span> The diagnostic '
          'clause&rsquo;s plain sense: healing laid on a misread pattern heals the misreading '
          '&mdash; the poison sealed under closed flesh, the fracture set crooked at pattern '
          'depth, the possession comfortably housed in a mended body. The sight rank&rsquo;s '
          'successes buy the diagnosis that makes the later ranks safe, and the '
          'field-healer&rsquo;s triage runs sight first, hands second, in every tradition&rsquo;s '
          'teaching &mdash; the Verbena&rsquo;s midwives, the Progenitors&rsquo; intake protocols, '
          'and the combat medics of three Conventions agreeing, for once, on procedure.</p>\n'
          '        <p><span class="lemma">The spark not yet gone.</span> The threshold&rsquo;s '
          'plain sense, held against the folk hopes: the spark is not the soul &mdash; folio '
          '43&rsquo;s Avatar and 148b&rsquo;s Wheel keep those ledgers &mdash; but the '
          'pattern&rsquo;s own unfinished momentum, the body&rsquo;s candle still smoking. '
          'Restoration rekindles what smoke remains; it calls nothing back from anywhere, and the '
          'law&rsquo;s careful physics is the tractate&rsquo;s guard against the necromancies the '
          'sibling tractates keep: what this Sphere restores was never gone, only going, and the '
          'distinction is the whole of the clause&rsquo;s decency.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; the healer&rsquo;s measures</span>',
 'name': 'Healing',
 'outer': '<p><span class="lemma">Whose law healing finally is.</span> The ration&rsquo;s '
          'question, taken up. <span class="voice">Some say</span> the pattern&rsquo;s: the '
          'Gemara&rsquo;s ruling reads the flesh as a party to the working, with its own pace and '
          'its own refusals, and the whole healing law follows &mdash; the ration is the '
          'pattern&rsquo;s consent formalized, the settle-time its signature. On this reading the '
          'healer is an advocate, not an author, and malpractice is pleading a case the client '
          'never brought. <span class="voice">Others say</span> the personification is lovely and '
          'the law is thermodynamics: patterns have capacities, not opinions, and dressing limits '
          'as consent teaches young healers a theology the emergency room will beat out of them. '
          'The dispute matters at exactly one bedside &mdash; the patient who refuses healing '
          '&mdash; where the pattern-school defers and the capacity-school heals; and the codes of '
          'chapter V, consulted, split along their grain: the Ecstatics&rsquo; consent root '
          'defers, the Chorus&rsquo;s service heals, and the Verbena, who wrote this law, ask the '
          'patient twice and then respect the answer, which the tractate records as the working '
          'compromise it is.</p>\n'
          '        <p><span class="lemma">Within hours numbered by enlightenment.</span> The clock '
          'dispute. <span class="voice">Some say</span> the clause is the Sphere&rsquo;s theology '
          'in one line: mercy scales with mastery because mastery <span class="aside">is</span> '
          'intimacy with the living pattern, and the master&rsquo;s hours are earned the way the '
          'mother&rsquo;s cheap reach was earned on folio 512b &mdash; by belonging. <span '
          'class="voice">Others say</span> the clause is the setting&rsquo;s quietest cruelty: the '
          'child&rsquo;s survival priced against which stranger&rsquo;s Arete happened to be '
          'nearest, grace rationed by proximity to enlightenment &mdash; and any theology that '
          'blesses that arithmetic has confused the map of power with the terrain of desert. The '
          'defenders answer that all medicine everywhere is rationed by proximity to skill, and '
          'the law merely declines to lie about it; the critics answer that declining to lie is '
          'not the same as declining to shrug. The folio of the Golden Rule, 384, wanting, is '
          'reserved a seat at this argument.</p>\n'
          '        <p><span class="lemma">Presents as illness.</span> The curse&rsquo;s last '
          'difficulty, briefly, because the codes have said the rest: can a law that teaches the '
          'cure teach the curse and stay a healer&rsquo;s law? <span class="voice">Some say</span> '
          'yes, as anatomy texts teach the surgeon and the torturer alike; knowledge is a ladder, '
          'and the codes exist to guard its top. <span class="voice">Others say</span> the page '
          'itself should be split &mdash; the healing published, the harming kept to oral '
          'transmission and watched lineages &mdash; and the tractate, which has just published '
          'both, is invited to consider its own ruling. It does: the harming here is restated, not '
          'taught &mdash; the measures named, the methods withheld, the citations pointing at '
          'books behind other people&rsquo;s counters &mdash; and whether that line holds is a '
          'question the tractate answers by keeping it visible. <span class="kw">TEYKU</span> '
          '&mdash; let the page stay whole, and watched. The page&rsquo;s watchers may add one '
          'datum: no recension has ever moved the harming law to a separate chapter, and the '
          'tractate reads the stubbornness as the ruling it just made, renewed edition by '
          'edition.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the ration, the clock, and the page</span>',
 'rubric': 'the healer&rsquo;s law, and its knife',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of healing &middot; the ladder inside the ladder',
 'title': 'Tractate Aliyah · Folio 516b — Healing: the healer’s law, and its knife',
 'type': 'daf'}
