# Folio 516a - Life. Sphere mold (f515a); facts per the wod-llm-wiki Life
# page (M20 pp.515-516; TB Verbena Revised for the healing law).
FOLIO = {'bottom': '<p><span class="lemma">On the healer in the cabal.</span> Life 3 changes the '
           'chronicle&rsquo;s injury economy: wounds stop being attrition and start being scenes, '
           'and the Storyteller should move the pressure accordingly &mdash; from hit points to '
           'time, witnesses, and the healer&rsquo;s own body as the party&rsquo;s single point of '
           'failure. The enemy who understands the Sphere shoots the healer first, and the enemy '
           'who understands it better shoots nobody and waits for the aggravated wound the healer '
           'must go vulgar to touch.</p>\n'
           '        <p><span class="lemma">On the better body.</span> The enhancement road is the '
           'Sphere&rsquo;s honest devil&rsquo;s bargain and should be played at full price: '
           'pattern bleeding as a daily bill, the permanent alteration as vulgar surgery, and '
           'every dot past the human ceiling carrying its permanent Paradox like a mortgage. A '
           'chronicle that lets the temptation be real &mdash; and the bills be real &mdash; gets '
           'the Progenitors&rsquo; whole tragedy, chapter VI&rsquo;s, in miniature, without a '
           'single Convention on screen.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Rule the boundaries in session '
           'zero: where the table&rsquo;s vampires and other twice-natured things fall between '
           'this Sphere and Matter; whether the once-per-scene healing clause binds NPCs too (it '
           'should); and what shapeshifting costs in identity at this table &mdash; the '
           'books&rsquo; own hazard &mdash; before a player discovers mid-scene that wearing the '
           'wolf too long is a horror story. The Sphere rewards a table that treats flesh as '
           'sacred; the Verbena of folio 162a would say that is the entire lesson.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on healers as targets, bargains at '
                'full price, and boundaries</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Life is the Sphere of the living pattern:</span> whatever grows, '
           'heals, and dies is its province, and what has finally died passes to '
           'Matter&rsquo;s.<sup>a</sup> Its ladder climbs by two measures: the simplicity of the '
           'pattern, and whose pattern it is. At the first rank the mage <span '
           'class="term">perceives</span> the living: health, age, and ailment read at a glance. '
           'At the second she <span class="term">works the simple, and herself</span>: the plant '
           'and the insect reshaped, her own hurts closed, her own small features changed. At the '
           'third she <span class="term">works the simple wholly, others gently, herself '
           'deeply</span>: healing laid on other bodies, her own body armored and clawed and '
           'gilled &mdash; still human, but negotiably.<sup>b</sup> At the fourth she <span '
           'class="term">works the complex</span>: other bodies remade, her own form traded for '
           'beast-shapes of her own mass. At the fifth she <span class="term">authors</span>: any '
           'form worn or granted, changes made permanent, life itself woven from raw energy with '
           'Prime&rsquo;s leave &mdash; and what she weaves without Mind&rsquo;s partnership is a '
           'sack of life, mindless, and the law does not let her forget it.<sup>c</sup> Two laws '
           'attend the ladder. Harm and healing worked here are aggravated: the Sphere edits '
           'patterns, and patterns remember. And the radical change unpaid bleeds &mdash; the '
           'altered body leaks its own quintessence daily until the change is fed or made '
           'whole.<sup>d</sup> And the first rank gates the rest here as everywhere: no pattern is '
           'worked unread.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'ladder&rsquo;s asymmetry, for it is the folio&rsquo;s spine: the mage heals herself a '
           'full rank before she heals anyone else. Why? <span class="voice">Some say</span> '
           'intimacy: her own pattern is the one text she reads without translation. <span '
           'class="voice">Others say</span> consent: the self is the one patient who cannot be '
           'wronged. And the worked examples say only that it is so, in every recension, unargued. '
           'A witch closes her own knife-wound at the second rank and her sister&rsquo;s at the '
           'third; a Progenitor grows herself gills in an afternoon and her diver a new lung in a '
           'season of vats; and the disputants opposite have been asked to rule whether the '
           'asymmetry is anatomy, ethics, or the oldest safety interlock in the Book of '
           'Magick.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; fourth of the Sphere folios; the '
             'healer&rsquo;s law waits overleaf.',
 'folio': '516A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Life entire, see M20, the Spheres '
           'chapter, folios 515&ndash;516, whence this page takes its number; on the boundary with '
           'Matter and the twice-natured who straddle it, the same chapter&rsquo;s note.</p>\n'
           '        <p><span class="mark">b</span> On the ranks&rsquo; climb &mdash; simple to '
           'complex, self before others &mdash; see the same entry; the shapes and examples are '
           'catalogued there.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On creation with Prime&rsquo;s '
           'leave and consciousness with Mind&rsquo;s, see the fifth rank&rsquo;s entry; the '
           'sack-of-life clause is the text&rsquo;s own warning.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On aggravated working and pattern '
           'bleeding, see the same entry and the Verbena Tradition book&rsquo;s healing '
           'chapters.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Verbena&rsquo;s, '
           'folio 162a, whose blood-and-garden law is its living jurisprudence; the Union&rsquo;s '
           'vats run the same ladder under the Progenitors, folio 190.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The healing this Sphere '
           'works and the injury it repairs are folio 406&rsquo;s ledger; the aggravated '
           'clause here is why that folio&rsquo;s worst column exists.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Where Life ends and Mind '
           'begins in a living brain is argued opposite and will be argued again at folio 519; the '
           'tractate seats the two folios three leaves apart on purpose.</p>',
 'h1': 'Life',
 'hagahah': 'The fifth rank can weave a living body from raw energy, and the law&rsquo;s own text '
            'calls the unminded result a sack of life. No other rank in the nine ladders comes '
            'with a disparagement built into its success; the drafters knew their students, and '
            'knew which ones would reach the fifth rank.',
 'inner': '<p><span class="lemma">Whatever grows, heals, and dies.</span> The jurisdiction test: '
          'Life owns the animated pattern &mdash; not the meat, the animation. Tissue alive '
          'answers this ladder; tissue dead answers Matter&rsquo;s; and the preserved culture, the '
          'stored blood, the seed in the vault answer here, for the law counts the ember as fire. '
          'The twice-natured &mdash; the walking dead of the sibling tractates &mdash; answer both '
          'Spheres at once, and every crossover chronicle should know it before the first Tremere '
          'scene.</p>\n'
          '        <p><span class="lemma">Still human, but negotiably.</span> The third '
          'rank&rsquo;s self-work clause: gills, claws, armored hide &mdash; the body edited '
          'within the species&rsquo; envelope, the envelope stretching. The plain sense for play '
          'is that a Life adept is never unarmed, never quite the person in her passport photo, '
          'and never free of the identity questions the fourth rank makes acute: the books&rsquo; '
          'own hazard list for shapeshifting begins with forgetting which shape is yours.</p>\n'
          '        <p><span class="lemma">Aggravated, for patterns remember.</span> The severity '
          'clause&rsquo;s plain sense: this Sphere&rsquo;s harm and its healing both work at the '
          'pattern&rsquo;s root, beneath the ordinary ledger of bruises &mdash; hence the harm '
          'that cannot be dodged or armored against, and the healing that repairs what nothing '
          'mundane repairs. Power and price travel together: the root level is where the permanent '
          'things happen, in both directions.</p>\n'
          '        <p><span class="lemma">The altered body leaks.</span> Pattern bleeding&rsquo;s '
          'plain sense: a radical change is a debt the pattern services daily &mdash; one '
          'wound&rsquo;s worth of leakage every day until the change is fed with quintessence or '
          'made permanent by the higher law. The clause is the enhancement road&rsquo;s toll '
          'booth, and the term of art for the creature that must eat magic to stay itself &mdash; '
          'thaumivore &mdash; is the Sphere&rsquo;s grimmest noun.</p>\n'
          '        <p><span class="lemma">With Prime&rsquo;s leave, with Mind&rsquo;s '
          'partnership.</span> The fifth rank&rsquo;s checkpoint clauses, and 515b&rsquo;s lesson '
          'again: the borders are drawn where the horrors are. Life alone remakes; with Prime it '
          'creates; with Mind its creations think; and each partnership is a gate with a guard, '
          'because the ladder&rsquo;s top rung overlooks the setting&rsquo;s two worst cliffs '
          '&mdash; the made person, and the unmade one.</p>\n'
          '        <p><span class="lemma">No pattern is worked unread.</span> The gate '
          'clause&rsquo;s clinical sense: the healer&rsquo;s sight precedes the healer&rsquo;s '
          'hand, and the working laid on an unread pattern is surgery blindfolded &mdash; '
          'possible, priced, and remembered by everyone downstream. The diagnostic rank also '
          'carries the Sphere&rsquo;s quiet social power: age, health, pregnancy, addiction, the '
          'surgery scars and the species, all read at a glance, and the codes of chapter V bill '
          'the glance itself under the reading-line dispute of folio 519a &mdash; the body, too, '
          'has surface thoughts.</p>\n'
          '        <p><span class="lemma">Beast-shapes of her own mass.</span> The fourth '
          'rank&rsquo;s conservation clause, plainly: the self transformed keeps its measure '
          '&mdash; the wolf is a big wolf, the bird is a heavy bird or the working is a fall '
          '&mdash; and the special capacities come only where the shape natively holds them. Mass '
          'is the law&rsquo;s anchor against the shapeshifter&rsquo;s oldest temptations, and the '
          'identity hazard rides every hour in the borrowed body: the books&rsquo; own rule bills '
          'will nightly, and the master&rsquo;s exemption from it is earned at the fifth rank, not '
          'assumed at the fourth.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; rank by rank, boundary by boundary</span>',
 'name': 'Life',
 'outer': '<p><span class="lemma">Anatomy, ethics, or interlock.</span> The asymmetry dispute, the '
          'folio&rsquo;s spine pressed. <span class="voice">The anatomists say</span> '
          'self-before-others is plain epistemics: the mage&rsquo;s own pattern is available to '
          'her from inside, every nerve a native informant, and other bodies are foreign texts '
          'read through glass &mdash; the rank gap measures translation, nothing more. <span '
          'class="voice">The ethicists say</span> the gap is the law&rsquo;s conscience: a '
          'healer&rsquo;s first patient is the only one who cannot be violated, and the ladder '
          'teaches consent by making the mage live in her own edited flesh for a rank before she '
          'touches anyone else&rsquo;s. <span class="voice">The engineers say</span> both readings '
          'flatter what is simply an interlock: the Sphere&rsquo;s worst failure mode is the '
          'confident novice remaking a stranger, and the asymmetry is a guard rail bolted where '
          'the bodies were. The three schools converge, note well, on identical practice &mdash; '
          'which the tractate has learned to read as a sign the law is older than its '
          'reasons.</p>\n'
          '        <p><span class="lemma">The better-body temptation.</span> <span '
          'class="voice">Some say</span> enhancement is the Sphere&rsquo;s plain vocation: a '
          'ladder that can straighten a spine, sharpen an eye, and fortify a heart is <span '
          'class="aside">for</span> improving people, and the squeamishness around it is the '
          'Consensus&rsquo;s mediocrity internalized &mdash; the same voice that calls every '
          'excellence unnatural. <span class="voice">Others say</span> the law itself votes '
          'against the road: bleeding, vulgarity, and permanent Paradox are not incidental '
          'frictions but the world&rsquo;s considered opinion, a rising toll on every step past '
          'the human envelope, and the masters who walked it furthest ended as thaumivores in '
          'Horizon exile, eating magic to stay invented. The dispute is the Progenitors&rsquo; '
          'whole chapter in advance, and the Verbena&rsquo;s answer &mdash; the cycle is the '
          'craft, and a body exempted from the cycle has left the garden &mdash; is quoted '
          'opposite with the respect one shows a position that has never once been '
          'convenient.</p>\n'
          '        <p><span class="lemma">Where Life ends and Mind begins.</span> The brain '
          'dispute, staged here and resumed at folio 519. The organ is tissue; the thought is not; '
          'and between them stands every working that touches mood through chemistry &mdash; the '
          'lifted depression, the quieted rage, the sleep granted at the third rank. <span '
          'class="voice">Some say</span> the border follows mechanism: what is worked through '
          'flesh is Life&rsquo;s, whatever it does to the weather inside, and the sleeping guard '
          'of folio 515b&rsquo;s audit was priced correctly. <span class="voice">Others say</span> '
          'the border follows the patient: a mind altered is a mind altered, whichever organ was '
          'the door, and Mind&rsquo;s consent law &mdash; when folio 519 writes it &mdash; reaches '
          'every working whose target is the person rather than the meat. The mechanists keep the '
          'cleaner chart; the personalists keep the cleaner conscience; and the twice-litigated '
          'border keeps both folios honest, which is why the tractate declines to close it. <span '
          'class="kw">TEYKU</span> &mdash; let the brain keep its two doors. The border&rsquo;s '
          'two folios, this and 519, keep between them the tractate&rsquo;s working definition of '
          'a person, which neither states aloud; the Masoret has noticed, and is watching '
          'both.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the asymmetry, the better body, and the brain</span>',
 'rubric': 'the Sphere of the living pattern, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Life &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 516a — Life: the Sphere of the living pattern',
 'type': 'daf'}
