# Folio 517b - The Workshop. Verso of the Matter folio: device law, the
# economy of transmutation, and the made world, per the wod-llm-wiki
# Matter page (M20 pp.516-518).
FOLIO = {'bottom': '<p><span class="lemma">On the workshop as venue.</span> A Matter chronicle&rsquo;s '
           'best set is the bench: the workshop scene &mdash; diagnosis, disassembly, the working '
           'planned like a machining job &mdash; is where this Sphere&rsquo;s character lives, and '
           'it plays best with real clocks. Let fabrication take time on screen; let the rush job '
           'carry rushed successes; and the Sphere&rsquo;s tempo &mdash; the Hermetic&rsquo;s '
           'library tempo with grease under its nails &mdash; becomes the campaign&rsquo;s '
           'heartbeat between fights rather than a vending machine during them.</p>\n'
           '        <p><span class="lemma">On wealth and the watchers.</span> The economy law '
           'opposite is a standing plot generator: every unexplainable fortune is a flare to the '
           'Union&rsquo;s auditors, and a cabal that funds itself by transmutation has chosen a '
           'slow-burn antagonist with subpoena power. Run the paper trail as the hunt it '
           'canonically is &mdash; the assay office, the provenance question, the '
           'Syndicate&rsquo;s polite man asking where the ingots were mined &mdash; and gold '
           'becomes what the folio rules it: liquidity with a fuse.</p>\n'
           '        <p><span class="lemma">On the wonder-smith.</span> The enchanted object '
           '&mdash; the working folded into the thing, folio 520b&rsquo;s law &mdash; is this '
           'Sphere&rsquo;s collaboration with Prime, and the table should feel the difference '
           'between conjured and crafted: the conjured device is groceries, the crafted Wonder is '
           'a character. Give named tools history, temperament, and maintenance costs, and the '
           'Kelim tractate&rsquo;s whole minor literature, K.1, wanting, starts paying rent in '
           'this chronicle early.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on bench time, paper trails, and '
                'named tools</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The made world has its own law.</span> A <span '
           'class="term">device</span> conjured is bounded by its maker&rsquo;s understanding: the '
           'principles known, the mechanism grasped, or the working fails in the trying or worse '
           'in the using.<sup>a</sup> A device transmuted keeps its cunning only if the new stuff '
           'can carry it: the clockwork turned to glass is a sculpture, and the law grants matter, '
           'never function.<sup>b</sup> Wealth worked from base stuff is lawful to the Sphere and '
           'billed by the world: rarity is priced in successes, plenty is priced in witnesses, and '
           'the fortune with no history is a working that never stops being witnessed.<sup>c</sup> '
           'And the made thing outlives its maker&rsquo;s working save where the third '
           'rank&rsquo;s states lapse; what is built is built, what is held is rented, and the '
           'smith is taught the difference before she is taught anything sharp.<sup>d</sup> Two '
           'further laws round the bench. The workshop&rsquo;s products carry their maker&rsquo;s '
           'knowing as a signature the first rank can read: the conjured thing is authored, and '
           'authorship clings. And the complex conjuration is ritual work &mdash; extended, '
           'exacting, and priced in successes by the device&rsquo;s density &mdash; so the '
           'bench&rsquo;s tempo is the library&rsquo;s, not the alley&rsquo;s. And the workshop '
           'teaches before it arms: the syllabus is the law&rsquo;s first safety mechanism, and '
           'the academies exist because the alternative was the entry hall&rsquo;s brass plate, '
           'learned individually.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence the knowledge '
           'clause&rsquo;s severity? <span class="kw">OUR TEACHERS TOLD:</span> an apprentice of '
           'the Society, impatient with study, conjured a pistol from a magazine photograph '
           '&mdash; grip, barrel, sights, everything the picture knew. It fired once. The '
           'examiner, who had stood behind sandbags, collected the pieces and mounted them in the '
           'academy&rsquo;s entry hall under a brass plate reading: THE PICTURE DID NOT KNOW ABOUT '
           'CHAMBER PRESSURE. NEITHER DID YOU. The apprentice retook the year, aced it, and is '
           'today the examiner &mdash; and the plate stays up, for the hall is the syllabus. The '
           'disputants around this text begin with what the plate implies: that the Sphere&rsquo;s '
           'real medium is not matter at all, but the maker&rsquo;s knowing &mdash; and they do '
           'not agree on whether that is a limitation or the entire point.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Matter folio: the recto keeps the '
             'ladder, this side keeps the bench.',
 'folio': '517B',
 'glossL': '<p><span class="mark">a</span> On conjured devices and the knowledge requirement, see '
           'the fourth rank of M20&rsquo;s Matter entry, folios 516&ndash;518; the clause is '
           'restated here as the workshop&rsquo;s first law.</p>\n'
           '        <p><span class="mark">b</span> On transmutation&rsquo;s respect for function, '
           'see the same entry&rsquo;s worked examples; the glass clockwork is the '
           'tractate&rsquo;s, the principle the book&rsquo;s.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On rarity priced in successes, see '
           'the second rank&rsquo;s entry; on plenty priced in witnesses, folios 533a and 533b, '
           'whose law this clause imports.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the third rank&rsquo;s lapsing '
           'states against the built thing&rsquo;s endurance, see the recto and its citations.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The workshop&rsquo;s syllabus is folio '
           '160a&rsquo;s method in miniature: the examiner&rsquo;s plate is peer review by '
           'demonstration with sandbags, and the Society&rsquo;s seat holds this Sphere for '
           'exactly the reasons the hall displays.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Wealth&rsquo;s watchers are '
           'the Syndicate&rsquo;s beat, folio 192, wanting; the fortune with no history is their '
           'term of art, and the Masoret notes with interest that the Traditions and the Union '
           'police this law identically, each insisting the other made it necessary.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The crafted Wonder&rsquo;s '
           'law is Prime&rsquo;s, folio 520b overleaf-but-one, and the Kelim tractate&rsquo;s, '
           'K.1, wanting; this folio builds the body, that one installs the soul.</p>',
 'h1': 'The Workshop',
 'hagahah': 'THE PICTURE DID NOT KNOW ABOUT CHAMBER PRESSURE. NEITHER DID YOU. The academy&rsquo;s '
            'brass plate is the finest piece of pedagogy in this tractate, and the tractate '
            'includes the Talmud&rsquo;s. Its genius is the second sentence, which every reader '
            'applies to herself exactly once.',
 'inner': '<p><span class="lemma">Bounded by its maker&rsquo;s understanding.</span> The first '
          'law&rsquo;s plain sense, with its working test: could the mage repair the device with '
          'mundane tools, given parts and time? If yes, she may conjure it; if no, she is asking '
          'the Sphere to know things for her, and the Sphere, as the recto rules, grants matter '
          'and never understanding. The test travels well: it prices the smartphone above the '
          'musket, the musket above the knife, and the knife at one success, which is why every '
          'Matter mage&rsquo;s first conjuration is a blade and every academy&rsquo;s entry hall '
          'says so.</p>\n'
          '        <p><span class="lemma">The law grants matter, never function.</span> The '
          'transmutation corollary, plainly: cunning is arrangement, and arrangement survives '
          'substance-swap only where the new substance can hold the arrangement&rsquo;s '
          'tolerances. Steel to brass, the clock ticks; steel to glass, the clock is a paperweight '
          'with ambitions; steel to fog, the third rank&rsquo;s door trick. The clause is why '
          'sabotage by transmutation is the Sphere&rsquo;s quietest art: swap one alloy in one '
          'bearing and the machine murders itself on schedule, no working present at the '
          'inquest.</p>\n'
          '        <p><span class="lemma">Plenty is priced in witnesses.</span> The economy '
          'law&rsquo;s plain sense: the gold is easy and the story is hard. Every ingot needs a '
          'mine, every windfall a will, and the fortune that skips the paperwork is a standing '
          'vulgarity in the one arena where the Union&rsquo;s audit never sleeps. The law&rsquo;s '
          'practical form: transmuted wealth spends safely at the speed its cover story can '
          'absorb, which is the same clause that governs stolen paintings, and for the same '
          'reason.</p>\n'
          '        <p><span class="lemma">What is built is built, what is held is rented.</span> '
          'The endurance law&rsquo;s plain sense, and the smith&rsquo;s catechism: a completed '
          'working is a fact in the world &mdash; the conjured knife needs no upkeep and outlives '
          'its maker &mdash; while the held state is a debt serviced by attention, lapsing when '
          'attention does. The catechism&rsquo;s point is career-shaping: build where you can, '
          'hold only what you must, and never stand under anything rented.</p>\n'
          '        <p><span class="lemma">Authorship clings.</span> The signature clause&rsquo;s '
          'plain sense: the made thing remembers its making &mdash; the maker&rsquo;s resonance in '
          'the grain, her understanding&rsquo;s fingerprints in the tolerances &mdash; and the '
          'first rank of any investigator&rsquo;s ladder reads provenance off a conjured gun the '
          'way 514b&rsquo;s readers read worked luck. The tradecraft follows: the professional '
          'conjures generic, works through intermediary materials, and knows that <span '
          'class="aside">untraceable</span> is a Sleeper word &mdash; in the Book of Magick '
          'everything is traceable and the question is only who can afford the tracing.</p>\n'
          '        <p><span class="lemma">The library&rsquo;s tempo.</span> The ritual '
          'clause&rsquo;s plain sense, and the Sphere&rsquo;s temperament in one line: great '
          'matter-work is prepared &mdash; the blueprint studied, the materials staged, the '
          'extended roll accumulated across hours &mdash; and the Matter mage ambushed mid-errand '
          'is a scholar with pockets, as the Hermetic of folio 158a is a scholar with a staff. The '
          'chronicle&rsquo;s rhythm follows: the workshop wins wars between scenes, never during '
          'them, and the cabal that budgets bench time is playing the Sphere the way its '
          'seat&rsquo;s whole Tradition plays it.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; the workshop&rsquo;s four laws</span>',
 'name': 'The Workshop',
 'outer': '<p><span class="lemma">Limitation or the entire point.</span> The plate&rsquo;s '
          'question, argued. <span class="voice">Some say</span> limitation, plainly: the '
          'knowledge clause is a governor bolted onto a Sphere that would otherwise print '
          'arsenals, and reading pedagogy into it gilds a safety valve. The proof is the '
          'workaround economy &mdash; blueprints traded, principles crammed, the Society&rsquo;s '
          'whole examination culture &mdash; none of which would exist if the clause were the '
          'point rather than the obstacle. <span class="voice">Others say</span> the workaround '
          'economy is the proof of the opposite: a clause that makes mages study, apprentice, '
          'examine, and archive has built the Sphere&rsquo;s civilization &mdash; the workshops, '
          'the academies, the journals &mdash; and a governor that generates culture was never '
          'merely a governor. The Sphere&rsquo;s medium is the knowing hand; the matter is the '
          'knowing made visible; and the alchemists said exactly this for six centuries while the '
          'world watched their gold, which is the recto&rsquo;s hagahah arriving at its '
          'destination.</p>\n'
          '        <p><span class="lemma">A working that never stops being witnessed.</span> The '
          'wealth dispute. <span class="voice">Some say</span> the economy law is the census of '
          '533b doing honest work: money is crystallized witness &mdash; every transaction an '
          'observer, every ledger a testimony &mdash; and transmuted wealth is therefore vulgarity '
          'on an installment plan, paid down as the story launders. The reading explains the '
          'Syndicate&rsquo;s whole existence: a Convention that polices plausibility in the one '
          'medium where plausibility is the entire product. <span class="voice">Others say</span> '
          'the reading proves too much &mdash; by its logic all wealth is witness and all '
          'economics is consensus, and the folio has quietly annexed chapter VI&rsquo;s hardest '
          'question. To which the answer, from the back of the room, in the Syndicate&rsquo;s own '
          'voice when that folio is written: <span class="aside">yes.</span> The tractate lets the '
          'annexation stand pending appeal.</p>\n'
          '        <p><span class="lemma">No working present at the inquest.</span> The sabotage '
          'difficulty, briefly and without a manual: the Sphere&rsquo;s quiet art kills at one '
          'remove, and the law&rsquo;s codes reach it unevenly &mdash; the bearing swapped is not '
          'the death curse of folio 516b, no pattern touched, no consent law tripped, and yet the '
          'machine&rsquo;s passengers are as dead as any curse&rsquo;s target. <span '
          'class="voice">Some say</span> the gap is real and the codes should close it; <span '
          'class="voice">others say</span> the gap is where mundane ethics already stand &mdash; '
          'sabotage was murder before magick and needs no Sphere-specific statute &mdash; and the '
          'codes of chapter V legislate only where the gift outruns the Sleeper law. The second '
          'reading holds the manuscripts; the first holds the funerals; and the tractate, which '
          'has ruled this pattern twice already this chapter, rules it again: the law is strictest '
          'where the gift is strongest, and silent where the gift merely sharpens an old knife. '
          '<span class="kw">TEYKU</span> &mdash; let the inquest stay open. The inquest&rsquo;s '
          'file gains one exhibit from the signature clause above: the bearing swapped is authored '
          'too, and the patient tracer reaches the workshop eventually &mdash; which both schools '
          'count as their point, correctly.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the plate, the money, and the bearing</span>',
 'rubric': 'the law of the made world',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the workshop &middot; devices, wealth, and endurance',
 'title': 'Tractate Aliyah · Folio 517b — The Workshop: the law of the made world',
 'type': 'daf'}
