# Folio 517a - Matter. Sphere mold (f515a); facts per the wod-llm-wiki
# Matter page (M20 pp.516-518).
FOLIO = {'bottom': '<p><span class="lemma">On the transmuter in the cabal.</span> Matter is the '
           'quartermaster&rsquo;s Sphere, and its table problem is abundance: lead to gold at the '
           'second rank collapses the money economy of any chronicle that lets it. Rule the '
           'frictions as written &mdash; rarity priced in successes, the vulgarity of '
           'unexplainable wealth, and the Union&rsquo;s economic sentinels, who watch bullion '
           'markets the way the census watches streets &mdash; and gold stays what the alchemists '
           'always said it was: a spiritual exercise with a disposal problem.</p>\n'
           '        <p><span class="lemma">On conjured devices.</span> The fourth rank&rsquo;s '
           'knowledge clause is the Storyteller&rsquo;s best lever: the mage conjures only what '
           'she truly understands, so her arsenal is her biography. Audit it gently but audit it '
           '&mdash; the gun conjured by someone who has stripped one, the car by someone who has '
           'rebuilt one &mdash; and the Sphere rewards exactly the scholarship the Etherites of '
           'folio 160a preach. The shortcut is buying the blueprint, which is a scene; the fraud '
           'is conjuring past one&rsquo;s knowing, which is a botch the law has already '
           'priced.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Post the permanence ruling in '
           'session zero: the third rank&rsquo;s state-changes lapse, the fifth&rsquo;s hold, and '
           'the table must know which transformations snap back &mdash; and when &mdash; before a '
           'bridge made of fog is holding anyone&rsquo;s weight. Post beside it the boundary '
           'rulings the recto&rsquo;s siblings share: dead tissue is Matter, living is Life, and '
           'the twice-natured are both, which in a crossover chronicle is not trivia but targeting '
           'data.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on gold, blueprints, and '
                'snap-back</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Matter is the Sphere of the unminded pattern:</span> substance '
           'without agency, from the lump to the lock to the laptop, and its ladder climbs by '
           'complexity.<sup>a</sup> At the first rank the mage <span '
           'class="term">perceives</span>: composition, structure, flaw, and the hidden layer read '
           'like a bill of materials. At the second she <span class="term">transmutes the '
           'simple</span>: one homogenous stuff into another, shape and state kept &mdash; lead to '
           'gold, wood to stone, water to wine.<sup>b</sup> At the third she <span '
           'class="term">shapes</span>: form reshaped at will, state changed for a time &mdash; '
           'steel to fog and back &mdash; density altered, solids fused or parted. At the fourth '
           'she <span class="term">works the complex</span>: mixtures, mechanisms, and devices '
           'transmuted or conjured whole &mdash; and a device is conjured only by one who knows '
           'its principles, for the Sphere grants matter, never understanding.<sup>c</sup> At the '
           'fifth she <span class="term">authors properties</span>: substances the world never '
           'catalogued, changes made to hold, the stuff of legend and of legend&rsquo;s '
           'warnings.<sup>d</sup> Two laws attend the ladder. Creation from nothing takes Prime as '
           'senior partner, as the whole Book of Magick provides. And Matter is the associative '
           'Art: alone it is a craftsman, and in partnership it is half the catalogue &mdash; the '
           'recto of folio 515b lists its marriages.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'ladder sorted by cases. A prisoner&rsquo;s iron bars are wine by morning: the second '
           'rank, and the guards blame each other, for the shape never changed. A locked '
           'door&rsquo;s steel breathes apart like mist while the thief walks through, and is '
           'steel again behind her: the third rank, state changed for a time, and the time is the '
           'working&rsquo;s whole tactical shape. A field kitchen becomes a banquet from air and '
           'pantry scraps: the fourth, complexity worked wholesale, with Prime&rsquo;s leave for '
           'whatever the pantry lacked. And the master who draws armor out of the air that was '
           'never any metal the world knows: the fifth, deeply vulgar, and the disputants opposite '
           'are asked where transmutation ended and creation began on that ladder &mdash; for the '
           'folio of Prime, two leaves on, is waiting for their answer.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; fifth of the Sphere folios; the '
             'workshop&rsquo;s law waits overleaf.',
 'folio': '517A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Matter entire, see M20, the Spheres '
           'chapter, folios 516&ndash;518, whence this page takes its number; the Union&rsquo;s '
           'Material Sciences are the same ladder in a lab coat.</p>\n'
           '        <p><span class="mark">b</span> On basic transmutation &mdash; shape and state '
           'kept, rarity priced in successes &mdash; see the second rank&rsquo;s entry there.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On complex transmutation and the '
           'knowledge requirement for conjured devices, see the fourth rank&rsquo;s entry; the '
           'clause reads: if the mage knows the principles.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On altered properties and unknown '
           'substances, see the fifth rank&rsquo;s entry; on the temporariness of the third '
           'rank&rsquo;s state-changes, the same chapter.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Society of '
           'Ether&rsquo;s, folio 160a, held as heirs to the alchemists&rsquo; chair &mdash; the '
           'alchemists&rsquo; Sphere, held in trust by people who apologize for alchemy, as the '
           'hagahah has it; the Union&rsquo;s iterators share the appetite, folio 186.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'creation-vs-transmutation border argued opposite is one half of the famous conjunction '
           'fight; folio 520 holds the other half, and the two folios are seated two leaves apart '
           'with the argument between them, as promised at folio 515a.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Dead tissue is this '
           'Sphere&rsquo;s and living is Life&rsquo;s, folio 516a; the twice-natured of Tractate '
           'Masekha answer both ladders at once, which every crossover chronicle should file under '
           'targeting data.</p>',
 'h1': 'Matter',
 'hagahah': 'Lead into gold is the second rank of five, and the alchemists knew it: the '
            'transmutation the world remembers them for was their entrance examination. The '
            'curriculum above it they kept quieter, which is why the world remembers the gold.',
 'inner': '<p><span class="lemma">From the lump to the lock to the laptop.</span> The complexity '
          'ladder&rsquo;s plain sense: the Sphere prices pattern-density, not size or worth. A '
          'boulder is a lump; a padlock is a mechanism; a laptop is a city of mechanisms &mdash; '
          'and each step up the density scale is a rank or a fistful of successes. The '
          'mage&rsquo;s working question is never &ldquo;how big&rdquo; but &ldquo;how many kinds '
          'of thing, fitted how closely,&rdquo; which is also, the Etherites note, just '
          'engineering&rsquo;s question wearing robes.</p>\n'
          '        <p><span class="lemma">Shape and state kept.</span> The second rank&rsquo;s '
          'clause, plainly: basic transmutation swaps substance under an unchanged form &mdash; '
          'the bars stay bar-shaped as they become wine only in the Gemara&rsquo;s joke; in law '
          'they would slump, for wine keeps no shape, and the working must respect what the new '
          'stuff can do. The clause is the rank&rsquo;s guard rail: substance swapped, physics '
          'kept, and the physics&rsquo; keeping is where the bystander of 533a does his '
          'auditing.</p>\n'
          '        <p><span class="lemma">For a time.</span> The third rank&rsquo;s temporariness, '
          'plainly: state-changes lapse &mdash; the fog remembers being steel, and becomes it '
          'again on the working&rsquo;s schedule, not the mage&rsquo;s hopes. Permanence waits at '
          'the fifth rank, and between the two lies the Sphere&rsquo;s whole tactical craft: the '
          'door that breathes open must breathe shut, and the master plans her exits at casting or '
          'joins the setting&rsquo;s long list of mages entombed in their own lapsed '
          'workings.</p>\n'
          '        <p><span class="lemma">Never understanding.</span> The knowledge clause&rsquo;s '
          'plain sense, and its teeth: conjuration is recall, not invention &mdash; the fourth '
          'rank furnishes what the mage&rsquo;s mind already contains, and the device conjured '
          'past her understanding arrives wrong in ways she cannot see, which the law prices as '
          'the botch it is. Hence the Sphere&rsquo;s strange virtue: its masters are scholars of '
          'the made world, boring at parties about locks and metallurgy, and their libraries are '
          'their armories.</p>\n'
          '        <p><span class="lemma">The associative Art.</span> The partnership clause, '
          'plainly: Matter alone shapes what is; its marriages do the famous things &mdash; Prime '
          'to create, Forces to animate, Life to bridge the living border, Time to hold a state '
          'past its lapse. The catalogue is 515b&rsquo;s and not repeated here; the plain sense is '
          'strategic: a Matter mage&rsquo;s power is measured half in her own rank and half in her '
          'cabal&rsquo;s, which makes her the natural quartermaster and the worst solo act in the '
          'nine ladders.</p>\n'
          '        <p><span class="lemma">Rarity priced in successes.</span> The second '
          'rank&rsquo;s market clause, plainly: the common transmutation is cheap &mdash; stone to '
          'stone, iron to copper &mdash; and the working climbs in successes as the product climbs '
          'in strangeness: the noble metals, the rare earths, the substances with export controls. '
          'The pricing is the law&rsquo;s quiet economics lesson: the Sphere does not know what '
          'gold costs, only what it is, and the successes measure molecular distance while the '
          'vulgarity measures social distance &mdash; the two bills arriving, as the verso will '
          'show, from different creditors.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; rank by rank, density by density</span>',
 'name': 'Matter',
 'outer': '<p><span class="lemma">Where transmutation ended and creation began.</span> The '
          'conjunction fight&rsquo;s Matter half, staged as promised. <span class="voice">Some '
          'say</span> the border is bright: transmutation works on stuff in hand and creation '
          'works on nothing, and Prime&rsquo;s partnership is owed exactly when the ledger of 515a '
          'finds no debit &mdash; the armor from air is creation because air was never '
          'armor&rsquo;s worth of anything. <span class="voice">Others say</span> the bright '
          'border dims on inspection: every transmutation adds something &mdash; the wine&rsquo;s '
          'complexity was not in the iron, the gold&rsquo;s nobility not in the lead &mdash; and '
          'if the added measure comes from somewhere, Prime is a silent partner in every '
          'second-rank working and the co-requirement is bookkeeping theater. The strict school '
          'answers with the law as written: the recensions bill Prime for creation and not for '
          'transmutation, and a theory that finds the statute incoherent has found its own limits. '
          'The loose school answers that statutes encode compromises, not physics &mdash; and this '
          'one, they note, is argued from the other side at folio 520, where Prime&rsquo;s own '
          'folio claims the whole ladder as its tributary. The tractate seats the fight across two '
          'leaves and declines to seat it further.</p>\n'
          '        <p><span class="lemma">Changes made to hold.</span> The permanence dispute. '
          '<span class="voice">Some say</span> the fifth rank&rsquo;s permanence is the '
          'third&rsquo;s temporariness outgrown &mdash; mastery simply holds what apprenticeship '
          'could only borrow, one competence deepening. <span class="voice">Others say</span> the '
          'two clauses describe different acts entirely: the lapse is the world&rsquo;s memory '
          'reasserting &mdash; the Consensus recalling what the steel is &mdash; and permanence is '
          'therefore not a stronger grip but a rewriting of the memory itself, which is why it '
          'sits at the rank of legend and why its price reads like 533a&rsquo;s docket. On this '
          'reading every permanent transmutation is a small local victory in the Ascension War '
          '&mdash; one object&rsquo;s worth of Consensus, conquered &mdash; and the Union&rsquo;s '
          'Material Sciences agree so precisely that their procedures cite stabilization where the '
          'Traditions cite victory, one law, two liturgies, the chapter&rsquo;s refrain sung by '
          'the enemy for once.</p>\n'
          '        <p><span class="lemma">Knows its principles.</span> The knowledge clause, '
          'pressed. <span class="voice">Some say</span> the clause is epistemically humble and '
          'mechanically perfect: it makes the Sphere&rsquo;s ceiling each mage&rsquo;s own '
          'learning, rewards the scholar, and starves the power-gamer, and no other rank in the '
          'nine ladders self-balances so cleanly. <span class="voice">Others say</span> the clause '
          'smuggles a metaphysics: if conjured matter needs a knowing mind, then matter unminded '
          '&mdash; the Sphere&rsquo;s own definition &mdash; is never truly free of mind, and the '
          'laptop conjured from understanding differs from the laptop assembled from parts in a '
          'way the first rank can read. The Etherites&rsquo; journals have run the comparison; the '
          'results are contested, as their results are; and folio 519, whose Sphere claims all '
          'minding, has filed a jurisdictional brief the tractate here acknowledges and defers. '
          '<span class="kw">TEYKU</span> &mdash; let the workshop keep its ghost. The '
          'ghost&rsquo;s jurisdiction, pending folio 519&rsquo;s brief, pays this folio one '
          'dividend already: the workshop&rsquo;s masters sign their work whether they mean to or '
          'not, and the first rank reads makers the way 514b&rsquo;s readers read grain.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the Prime border, permanence, and the knowing hand</span>',
 'rubric': 'the Sphere of the unminded pattern, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Matter &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 517a — Matter: the Sphere of the unminded pattern',
 'type': 'daf'}
