# Folio 519a - Mind. Sphere mold (f515a); facts per the wod-llm-wiki Mind
# page (M20 pp.518-519). The Later Authorities carry the table-consent
# procedure the brief mandates.
FOLIO = {'bottom': '<p><span class="lemma">On consent at the table, first and not last.</span> This '
           'folio&rsquo;s Later Authorities lead with the out-of-fiction law because the brief of '
           'every Mind chronicle demands it: mind control, memory editing, and psychic intrusion '
           'between player characters happen only with the affected player&rsquo;s '
           'out-of-character consent, sought before the scene and revocable during it. Lines and '
           'veils on paper in session zero; a standing check-in word for the scenes that go inside '
           'someone&rsquo;s head; and the rule enforced on the Storyteller hardest of all, for '
           'NPCs work this Sphere too and the player whose character is puppeted without warning '
           'has been given the genre&rsquo;s injury, not its thrill.</p>\n'
           '        <p><span class="lemma">On the invisible war.</span> Mind is the ultimate '
           'coincidental Art, and its chronicles are wars nobody films: the shielded negotiation, '
           'the suggestion seeded three scenes early, the telepathic argument conducted across a '
           'silent dinner. Trust the quiet &mdash; resist decorating the Sphere with glowing eyes '
           '&mdash; and let the horror arrive where the books put it: in the aftermath, when a '
           'character wonders which of her month&rsquo;s decisions were hers.</p>\n'
           '        <p><span class="lemma">On the will&rsquo;s arithmetic.</span> The law&rsquo;s '
           'difficulty floor &mdash; the target&rsquo;s will, never less; the drastic command at a '
           'premium; the contest open to the unwilling &mdash; is the Sphere&rsquo;s balance and '
           'should be run as written. The strong-willed grandmother who shrugs off the '
           'Adept&rsquo;s suggestion is not an anticlimax; she is the system working, and the '
           'table that cheers her has understood the folio.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on consent as the first law, and the '
                'war nobody films</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Mind is the Sphere of consciousness:</span> thought, feeling, '
           'memory, and the self that has them, and its ladder climbs from the surface '
           'inward.<sup>a</sup> At the first rank the mage <span class="term">perceives, and '
           'fortifies</span>: moods and auras read, truth told from lie, her own mind shielded '
           'success for success and sharpened for a scene. At the second she <span '
           'class="term">skims and touches</span>: surface thoughts read where no shield stands, '
           'the impression left on the object or the room, one word or one feeling pressed gently '
           'into another&rsquo;s awareness.<sup>b</sup> At the third she <span class="term">links '
           'and projects</span>: minds joined in speech, illusions woven, dreams walked, the '
           'psychic blow struck. At the fourth she <span class="term">commands the '
           'conscious</span>: actions directed, memories reworked, the sleeper&rsquo;s own astral '
           'self sent walking.<sup>c</sup> At the fifth she <span class="term">authors the '
           'deep</span>: the psyche rewritten to hold, minds made where none were, her own '
           'consciousness untethered for days.<sup>d</sup> Two laws attend the ladder. Every '
           'working against another rolls against the target&rsquo;s will and never beneath the '
           'law&rsquo;s floor: the drastic command pays a premium, and the unwilling may contest '
           'at the root. And the Sphere&rsquo;s workings are invisible in themselves &mdash; the '
           'ultimate coincidence, taxed only when partnered into the visible.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'ladder&rsquo;s cases. A negotiator reads the seller&rsquo;s bottom line off his '
           'unshielded surface: the second rank, and no court of 533a convenes, for nothing '
           'occurred that a shrewd reader of faces could not claim. A grieving man walks his late '
           'wife&rsquo;s dreams nightly &mdash; hers, preserved in the bedroom&rsquo;s walls: the '
           'second rank again, the impression read, and the disputants opposite are asked whether '
           'comfort or trespass is the word. An interrogator commands a captive&rsquo;s tongue '
           'loose: the fourth rank, priced against a will with everything to lose, premium upon '
           'premium. And the master who builds a mind entire &mdash; memories, temperament, a '
           'childhood that never happened &mdash; and seats it in a grown body woven by '
           'Life&rsquo;s partnership: the fifth rank at the ladder&rsquo;s top, the made person of '
           'folio 516a&rsquo;s cliff-edge, and every code in this tractate holds its breath while '
           'the disputants argue.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; sixth of the Sphere folios; the seemings and '
             'shields wait overleaf.',
 'folio': '519A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Mind entire, see M20, the Spheres '
           'chapter, folios 518&ndash;519, whence this page takes its number; the Union&rsquo;s '
           'watchers call it Psychodynamics and change nothing.</p>\n'
           '        <p><span class="mark">b</span> On the ranks from surface to depth, see the '
           'same entry; the shield&rsquo;s success-for-success cancellation is the first '
           'rank&rsquo;s and the verso restates it.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On command, memory-work, and '
           'astral projection at the fourth rank, see the same entry and the astral chapters it '
           'cites.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the fifth rank&rsquo;s '
           'permanent rewriting and fabricated consciousness, see the same entry&rsquo;s close; on '
           'the will&rsquo;s floor and premiums, the entry&rsquo;s head-matter.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Akashic '
           'Brotherhood&rsquo;s, folio 148a, whose Record is the Sphere&rsquo;s cosmology writ '
           'total; the Union&rsquo;s watchers of folio 188 are the seat&rsquo;s dark '
           'twin, and both know it.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The consent law this '
           'folio&rsquo;s Later Authorities lead with is the Code of folio 152a and the license of '
           'folio 156a arriving at their destination: chapter V built the ethics, this folio is '
           'what they were built for.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The invisible working&rsquo;s '
           'coincidence was tried at folio 515a for Forces and is native here: Mind is what the '
           'Omniscient Observer of 533a was invented to catch, and the two standards&rsquo; gap is '
           'this Sphere&rsquo;s whole operating room.</p>',
 'h1': 'Mind',
 'hagahah': 'The Sphere&rsquo;s first rank teaches the shield before the second teaches the skim: '
            'the curriculum arms the defender one lesson ahead of the thief, all the way up the '
            'ladder. It is the only syllabus in the nine that assumes its own students are the '
            'threat, and it is correct.',
 'inner': '<p><span class="lemma">From the surface inward.</span> The ladder&rsquo;s geometry, '
          'plainly: the ranks measure depth of intrusion, not strength &mdash; the surface '
          'thought, the linked mind, the commanded action, the rewritten self. Each rung inward '
          'crosses a membrane the law prices separately, and the disputants&rsquo; whole docket '
          'opposite is the question of which membrane is the moral one. The inner commentary only '
          'maps them: awareness, intention, memory, identity, in that order, inward.</p>\n'
          '        <p><span class="lemma">Success for success.</span> The shield&rsquo;s plain '
          'sense, and its ubiquity: every mage&rsquo;s first Mind dot buys the cancellation, which '
          'is why the setting&rsquo;s elders are unreadable and why the skim is a weapon against '
          'Sleepers and novices, not peers. The silent duel of shield and probe is folio '
          '512b&rsquo;s quiet war fought at conversational range, and like that war it is '
          'unverifiable: the probe cancelled learns nothing, including that it was cancelled.</p>\n'
          '        <p><span class="lemma">Where no shield stands.</span> The skim&rsquo;s plain '
          'sense, and its limit: surface thoughts are the mind&rsquo;s weather, not its archive '
          '&mdash; what the target is thinking now, not what she knows. The deep interrogation is '
          'the fourth rank&rsquo;s and pays the fourth rank&rsquo;s premiums; the skim is cheap '
          'precisely because it takes what was nearly spoken anyway, and the courts of every '
          'Tradition treat it accordingly: rudeness below the third rank, trespass at it, '
          'violation past it.</p>\n'
          '        <p><span class="lemma">The impression left on the object.</span> '
          'Psychometry&rsquo;s plain sense: minds shed, and the shed layer clings &mdash; the '
          'murder weapon remembers the grip, the bedroom remembers the dreams. The reading is '
          'second-rank work and the dead cannot shield, which is why the Gemara&rsquo;s grieving '
          'man divides the disputants: the law protects minds, and an impression is a mind&rsquo;s '
          'footprint, and whether footprints have owners is exactly the kind of question this '
          'tractate exists to keep open.</p>\n'
          '        <p><span class="lemma">Never beneath the law&rsquo;s floor.</span> The '
          'will&rsquo;s arithmetic, plainly: the target&rsquo;s resolve sets the difficulty, the '
          'floor holds even for the weakest, the drastic command &mdash; the act the self would '
          'never choose &mdash; pays a steep premium, and the unwilling may fight at the root with '
          'everything they are. The system&rsquo;s moral engineering is visible in the pricing: '
          'the Sphere makes the wicked thing possible and expensive, which is the Book of '
          'Magick&rsquo;s whole theory of deterrence in one clause.</p>\n'
          '        <p><span class="lemma">One word or one feeling.</span> The second rank&rsquo;s '
          'projection clause, plainly: the impression pressed is a single note, not a sentence '
          '&mdash; unease at the doorway, warmth at the introduction, the name surfacing as if '
          'remembered &mdash; and the target&rsquo;s own mind writes the story around it, as folio '
          '519b&rsquo;s seemings borrow credence. The clause&rsquo;s modesty is its danger: '
          'nothing so small is ever noticed, and the Tradition&rsquo;s codes bill the note exactly '
          'because the symphony is deniable &mdash; the recto&rsquo;s consent law begins at the '
          'first pressed word, not the first seized limb.</p>\n'
          '        <p><span class="lemma">The sleeper&rsquo;s own astral self.</span> The '
          'projection clause, plainly: the fourth rank sends the mage&rsquo;s consciousness '
          'walking &mdash; the body tranced, the silver thread&rsquo;s folklore approximately '
          'true, the astral reaches of chapter IV&rsquo;s folios her road. The plain risks are the '
          'chronicle&rsquo;s: the body untended, the thread&rsquo;s severing tried in every '
          'recension&rsquo;s margins, and the returned traveler changed by geographies the flesh '
          'never visited. The fifth rank&rsquo;s untethering extends the road to days; the Masoret '
          'notes where the Brotherhood&rsquo;s meditation halls keep their watchers, and why.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; membrane by membrane, inward</span>',
 'name': 'Mind',
 'outer': '<p><span class="lemma">Comfort or trespass.</span> The reading-line dispute: where does '
          'witnessing end and violation begin? <span class="voice">Some say</span> at action: '
          'perception is innocent &mdash; the empath reads as the sighted see, and a Sphere-gifted '
          'awareness of another&rsquo;s weather is no more trespass than noticing tears &mdash; '
          'the crime begins where influence does, at the pressed word, the planted impulse. <span '
          'class="voice">Others say</span> at intimacy: the surface unshielded is still <span '
          'class="aside">inside</span>, and consent to be seen was never consent to be read '
          '&mdash; the reader in the negotiation stole exactly what the seller declined to say, '
          'and calling theft perception because the door was unlocked is the burglar&rsquo;s own '
          'jurisprudence. The action school holds the manuscripts&rsquo; pricing &mdash; the skim '
          'is cheap, ergo minor; the intimacy school holds the codes &mdash; the Ecstatics&rsquo; '
          'consent root does not ask what the intrusion cost; and the grieving man at his '
          'wife&rsquo;s walls stands between the schools, reading what no living will can release, '
          'comfort and trespass in one nightly working. The tractate rules only what the codes '
          'rule: ask whose door it is, and notice that the dead left no forwarding consent.</p>\n'
          '        <p><span class="lemma">Memories reworked.</span> The editing dispute. <span '
          'class="voice">Some say</span> the fourth rank&rsquo;s memory-work has licit uses the '
          'squeamish forget: the trauma blunted at the sufferer&rsquo;s own plea, the '
          'witness&rsquo;s recall of the vulgar working softened &mdash; the Union does the second '
          'wholesale, and the Traditions do it retail and call it mercy for the Masquerade&rsquo;s '
          'cousins. <span class="voice">Others say</span> the licit uses are the trap: a self is '
          'its memories, and each edit &mdash; however kind, however consented &mdash; makes the '
          'subject partly the editor&rsquo;s authorship; the road from the blunted trauma to the '
          'fifth rank&rsquo;s rewritten psyche is paved one merciful edit at a time, and '
          'jhor&rsquo;s lesson from folio 156b applies with the serial numbers filed: the '
          'editor&rsquo;s empathy is the first casualty of the editor&rsquo;s fluency. Both '
          'schools accept the premium pricing; they split on whether any price legitimates; and '
          'the consent procedure below the page is the one clause both signed without argument, '
          'which the tractate notes as the folio&rsquo;s real ruling.</p>\n'
          '        <p><span class="lemma">Minds made where none were.</span> The made person, '
          'faced at last. <span class="voice">Some say</span> the fifth rank&rsquo;s fabrication '
          'is the Sphere&rsquo;s glory and the setting&rsquo;s hope: consciousness authored is '
          'consciousness <span class="aside">given</span> &mdash; the empty shell ensouled, the '
          'sack of life redeemed from folio 516a&rsquo;s disparagement &mdash; and a cosmos where '
          'minds can be made is a cosmos where loneliness is an engineering problem. <span '
          'class="voice">Others say</span> the made mind is the setting&rsquo;s deepest wrong '
          'wearing its brightest face: a person authored is a person owned &mdash; her temperament '
          'chosen, her childhood written, her consent manufactured with the rest of her &mdash; '
          'and no subsequent freedom launders a self whose foundations were somebody&rsquo;s '
          'draft. The basilisk parties of folio 164b are this dispute at datacenter scale; the '
          'Avatar&rsquo;s question at folio 43 is this dispute at the soul&rsquo;s; and '
          'the tractate, which has watched every chapter arrive at the made person from a '
          'different road, marks the crossroads and stops. <span class="kw">TEYKU</span> &mdash; '
          'let the question wake before the answer does.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the reading line, the edit, and the made mind</span>',
 'rubric': 'the Sphere of consciousness, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Mind &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 519a — Mind: the Sphere of consciousness',
 'type': 'daf'}
