# Folio 519b - The Seeming. Verso of the Mind folio: illusion law and the
# disbelief procedure, per the wod-llm-wiki Mind page (M20 p.504).
FOLIO = {'bottom': '<p><span class="lemma">On illusions as scenes.</span> The three grades give the '
           'Storyteller three genres: the mental seeming is a con game &mdash; one mark, one '
           'story, unraveling on the mark&rsquo;s schedule; the physical seeming is stagecraft '
           '&mdash; everyone sees it, so it obeys theater&rsquo;s rules, sight lines and timing; '
           'and the immersive seeming is a heist set &mdash; a built world with a maintenance '
           'budget. Choose the grade for the scene you want, and price the working accordingly; '
           'the commonest table error is billing a con at stagecraft rates.</p>\n'
           '        <p><span class="lemma">On running disbelief.</span> The procedure is a '
           'player-facing right: any character may plant her feet and test the seeming, and the '
           'roll&rsquo;s difficulty follows believability as the law provides &mdash; the absurd '
           'collapses easily, the plausible holds like truth. Honor the attempt visibly, narrate '
           'the flicker at the edges on partial success, and never let disbelief work on the '
           'physical grades: the fire woven from real light burns the skeptic exactly as the law '
           'says, and the table should learn the difference the safe way, once.</p>\n'
           '        <p><span class="lemma">On the long con.</span> The seeming maintained across '
           'sessions &mdash; the dead friend kept walking, the fortune kept visible, the '
           'enemy&rsquo;s stronghold kept unburned &mdash; is the Sphere&rsquo;s campaign-scale '
           'form, and its bookkeeping is the drama: renewals, witnesses multiplying, the seams '
           'where new observers arrive. Run the upkeep as scenes and the collapse as consequence, '
           'and the folio&rsquo;s last law &mdash; every seeming ends &mdash; becomes the '
           'chronicle&rsquo;s engine rather than its footnote.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on grades as genres, the '
                'skeptic&rsquo;s right, and upkeep</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">A seeming is a shown thing that is not there,</span> and the law '
           'knows three grades.<sup>a</sup> The <span class="term">mental</span> seeming lives in '
           'its audience: woven into minds, invisible to the camera and the dog, and open to <span '
           'class="term">disbelief</span> &mdash; the audience that plants its feet and refuses '
           'may test the weave, and the test&rsquo;s difficulty follows believability: the absurd '
           'collapses at a push, the plausible holds like truth itself.<sup>b</sup> The <span '
           'class="term">physical</span> seeming lives in the world: light and force woven where '
           'nothing stands, seen by every eye and lens alike, immune to disbelief and open only to '
           'inspection&rsquo;s sharp eye at the flawed seam.<sup>c</sup> The <span '
           'class="term">immersive</span> seeming is the physical grade built total &mdash; a '
           'place woven whole, walkable, answering touch &mdash; the master&rsquo;s stagecraft and '
           'the Union&rsquo;s training floors. Its realism is priced in successes, sense by sense, '
           'from the single glimpse to the world that answers questions.<sup>d</sup> One law binds '
           'all three grades: a seeming does no harm unless harm is woven in and paid for, and '
           'every seeming ends &mdash; the weave lapses, the light disperses, and what the '
           'audience does with the ending is the working&rsquo;s true price.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence '
           'disbelief&rsquo;s power over the mental grade alone? Because the mental seeming is a '
           'loan against the audience&rsquo;s own credence, and a loan can be called: the mind '
           'that refuses withdraws the collateral, and the seeming, built of nothing else, has '
           'nothing to stand on. The physical grade borrowed nothing from its audience &mdash; the '
           'light is real, merely arranged &mdash; and no refusal unarranges it. <span '
           'class="kw">IT HAPPENED THAT</span> a skeptic of the Union&rsquo;s schooling stood '
           'before a Chorister&rsquo;s vision of the burning bush and disbelieved with all his '
           'trained will, and the bush burned on, for it was woven of real fire held harmless; and '
           'the same skeptic, a year later, disbelieved a horror wearing his dead brother&rsquo;s '
           'face and it tore like wet paper, for it had been cut from his own grief and nothing '
           'else. He reported both results accurately, being a scientist. The disputants around '
           'this text have the reports, and what they argue is which working was the crueler.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Mind folio: the recto keeps the '
             'ladder, this side keeps the stage.',
 'folio': '519B',
 'glossL': '<p><span class="mark">a</span> On the three grades of illusion &mdash; mental, '
           'physical, immersive &mdash; and their Sphere requirements, see the illusion tables of '
           'M20&rsquo;s systems chapter.</p>\n'
           '        <p><span class="mark">b</span> On disbelief &mdash; its roll, its threshold, '
           'and the believability scale from the impossible to the all too likely &mdash; see the '
           'same tables.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the physical grades&rsquo; '
           'immunity to disbelief and the inspection of seams, see the same; the flawed seam is '
           'found by wit, not will.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On realism priced sense by sense, '
           'from one glimpse to the interactive whole, see the successes ladder beside the '
           'tables.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The mental seeming is the one working in the Book '
           'of Magick that the Sleeper defeats unaided: disbelief needs no Sphere, only feet '
           'planted &mdash; the Consensus&rsquo;s own weapon, issued to every mind at birth, and '
           'folio 62 calls it by name.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The physical seeming is '
           'Forces&rsquo; and Prime&rsquo;s craft as much as Mind&rsquo;s &mdash; folios 515a and '
           '520 hold the partners &mdash; and the camera that cannot see the mental grade sees the '
           'physical one perfectly, which hands 533b&rsquo;s census its strangest cases.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The horror cut from the '
           'skeptic&rsquo;s grief is Quiet&rsquo;s doorstep, folio 554: a seeming '
           'believed long enough furnishes a private world, and the difference between a paradigm '
           'and a Quiet, the hagahah of 554 will say, is other people.</p>',
 'h1': 'The Seeming',
 'hagahah': 'Stage magicians, the books observe, are the one Sleeper guild that polices this '
            'folio&rsquo;s law without knowing it: they build physical seemings from mirrors and '
            'misdirection, invite disbelief nightly, and take a bow when it fails. Several are '
            'Awakened. None has ever needed to be.',
 'inner': '<p><span class="lemma">A loan against the audience&rsquo;s credence.</span> The mental '
          'grade&rsquo;s plain sense: the working borrows the target&rsquo;s own world-building '
          '&mdash; her expectations furnish the details, her senses sign the invoice &mdash; which '
          'is why the grade is cheap, why it is invisible to instruments, and why it fails against '
          'the prepared: the skeptic&rsquo;s planted feet are a credit freeze. The '
          'craftsman&rsquo;s corollary: weave with the grain &mdash; the seeming the audience '
          'half-expected costs least and holds hardest, believability being both the price list '
          'and the armor.</p>\n'
          '        <p><span class="lemma">The light is real, merely arranged.</span> The physical '
          'grade&rsquo;s plain sense: this is conjury, not psychology &mdash; Forces bent into '
          'image, Prime paying the light bill &mdash; and its budget scales with fidelity: each '
          'sense added, each motion granted, each question the seeming can answer is successes on '
          'the table. The seam is its weakness: the woven thing imperfectly known shows the '
          'maker&rsquo;s ignorance at the edges, and the inspection that finds the seam is folio '
          '517b&rsquo;s knowledge clause working for the defense.</p>\n'
          '        <p><span class="lemma">Harm woven in and paid for.</span> The damage '
          'clause&rsquo;s plain sense: seemings hurt only by explicit purchase &mdash; the mental '
          'blow bruising as the mind believes, the physical fire burning as fire &mdash; and the '
          'purchase is priced at the partnered Spheres&rsquo; own rates. The clause kills the folk '
          'theory that a believed death kills: belief alone stops at trauma, the law says, and the '
          'working that kills through a seeming paid for the killing separately, somewhere the '
          'first rank of any investigator&rsquo;s ladder can read.</p>\n'
          '        <p><span class="lemma">What the audience does with the ending.</span> The lapse '
          'clause&rsquo;s plain sense, and the Sphere&rsquo;s deferred billing: every seeming '
          'ends, and the ending is an event in its witnesses &mdash; the fortune revealed as '
          'leaves, the friend revealed as absence, the fortress revealed as field. The law counts '
          'the revelation among the working&rsquo;s effects, chargeable to its maker: the '
          'con&rsquo;s collapse is the con&rsquo;s last act, and 533a&rsquo;s court, which may '
          'have slept through the seeming, is often widest awake at its funeral.</p>\n'
          '        <p><span class="lemma">Priced in successes, sense by sense.</span> The realism '
          'ladder&rsquo;s plain sense: the seeming is bought by the sense and the behavior &mdash; '
          'one glimpse cheap, the moving image more, the thing that answers touch and question '
          'climbing toward the interactive whole &mdash; and the budget is the craftsman&rsquo;s '
          'storyboard: what will the audience test, and in what order? The con&rsquo;s economics '
          'follow: the master seeming is not the most detailed but the best-predicted, spending '
          'its successes exactly where the mark&rsquo;s hands will go, and the Sphere&rsquo;s '
          'stagecraft is finally audience-reading, which the recto priced at the second rank and '
          'the wise never stop paying.</p>\n'
          '        <p><span class="lemma">Immune to disbelief.</span> The physical grades&rsquo; '
          'immunity, plainly, with its compensating audit: what cannot be refused can be inspected '
          '&mdash; the seam where the maker&rsquo;s knowledge ran out, the shadow cast wrong, the '
          'echo missing &mdash; and the inspection is wit&rsquo;s work, priced in the '
          'observer&rsquo;s craft rather than her will. The division of labor is the folio&rsquo;s '
          'deep structure: the mental grade falls to conviction, the physical to attention, and '
          'the pairing guards the world twice &mdash; the skeptic and the detective each get one '
          'grade, and the seeming that survives both has earned its scene.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; loans, light, and lapses</span>',
 'name': 'The Seeming',
 'outer': '<p><span class="lemma">Which working was the crueler.</span> The skeptic&rsquo;s two '
          'reports, argued. <span class="voice">Some say</span> the brother: the mental seeming '
          'conscripted the man&rsquo;s own grief as its material &mdash; the working made him '
          'co-author of his torment, and the tearing-like-wet-paper was not mercy but the '
          'insult&rsquo;s completion, his love revealed as load-bearing for a lie. The physical '
          'bush deceived his eyes; the mental brother embezzled his heart. <span '
          'class="voice">Others say</span> the bush: the mental seeming, whatever its cruelty, '
          'submitted to his refusal &mdash; the law gave him a vote and his vote counted &mdash; '
          'while the bush burned on against all the will he could raise, and a world where trained '
          'disbelief moves nothing is the deeper violence to a mind built on testing. The first '
          'school protects the heart, the second the franchise; the skeptic&rsquo;s own report, '
          'consulted, says only that he sleeps worse for the brother and works harder because of '
          'the bush, which the disputants agree is the most useful datum either side has.</p>\n'
          '        <p><span class="lemma">Open to disbelief.</span> The franchise dispute beneath '
          'the procedure. <span class="voice">Some say</span> disbelief is the Consensus in '
          'miniature and a mercy: the mental grade works by enlistment, so the law arms every '
          'enlistee with resignation papers &mdash; the one working in the Book that its victim '
          'may simply quit. <span class="voice">Others say</span> the mercy is means-tested by '
          'temperament: disbelief demands the planted foot, the trained refusal, the five-success '
          'certainty &mdash; and the trusting, the young, and the grief-stricken hold no such '
          'papers, so the grade preys precisely on the openness the codes of chapter V call '
          'virtue. The law&rsquo;s answer is its pricing &mdash; the plausible seeming holds even '
          'against the skeptic, so refusal was never full armor &mdash; and the codes&rsquo; '
          'answer is the consent procedure of the recto, which does not ask whether the target '
          'could have disbelieved. Both answers stand; neither comforts; the folio files them '
          'adjacent.</p>\n'
          '        <p><span class="lemma">Invisible to the camera and the dog.</span> The census '
          'difficulty, inherited and sharpened. The mental seeming has no witnesses but its '
          'targets &mdash; the lens records a man screaming at nothing, the beast smells no fire '
          '&mdash; and 533b&rsquo;s census, asked to price such a working, finds its categories '
          'inverted: the crowd that saw nothing impossible saw a man unmade by it. <span '
          'class="voice">Some say</span> price the seeming by its targets alone, for the law of '
          'witnesses guards the world&rsquo;s agreement and the world, uninvited, never attended. '
          '<span class="voice">Others say</span> the man screaming at nothing <span '
          'class="aside">is</span> the impossible thing &mdash; madness with an author is an '
          'assault on the Consensus through its citizen &mdash; and the census counts what the '
          'crowd made of him, as the lapse clause counts endings. The manuscripts split; the '
          'standards of 533a split along their existing grain; and the tractate, having promised '
          'at 515a that every folio ends at that court, keeps the promise and the question both. '
          '<span class="kw">TEYKU</span> &mdash; let the audience keep the last word, as audiences '
          'do.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the two cruelties, the franchise, and the empty stage</span>',
 'rubric': 'the law of shown things',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the seeming &middot; illusions, disbelief, and endings',
 'title': 'Tractate Aliyah · Folio 519b — The Seeming: the law of shown things',
 'type': 'daf'}
