# Folio 520b - The Well. Verso of the Prime folio: the quintessence
# economy - nodes, tass, periapts, wonders - per the wod-llm-wiki Prime
# page (M20 pp.519-520).
FOLIO = {'bottom': '<p><span class="lemma">On the chantry budget.</span> Run the well&rsquo;s economy as '
           'an actual economy: the chantry&rsquo;s node yields so much a season, the wonders drink '
           'so much a use, and the gap between income and ambition is the campaign&rsquo;s '
           'standing pressure. Scarcity is the Sphere&rsquo;s gift to drama &mdash; every working '
           'has an opportunity cost the treasurer can name &mdash; and the table that tracks the '
           'pool discovers that half its stories were about fuel all along, which is the '
           'setting&rsquo;s own confession.</p>\n'
           '        <p><span class="lemma">On tass in the market.</span> Embodied quintessence is '
           'currency, and currency moves: the night-markets of the sibling tractates trade it, the '
           'Union audits it, and a cabal holding surplus tass holds what every neighbor wants. '
           'Price it by resonance as the law provides &mdash; the battlefield&rsquo;s tass is not '
           'the garden&rsquo;s &mdash; and let provenance matter: dirty fuel works, and works on '
           'the worker, and the folio&rsquo;s quiet horror is the mage who stopped asking where '
           'her light was mined.</p>\n'
           '        <p><span class="lemma">On the dry season.</span> The best Prime story is '
           'famine: the node fouled or taken, the periapts draining, the cabal&rsquo;s arts '
           'rationed week by week. Run it rarely and honestly &mdash; magic&rsquo;s absence is the '
           'one thing a Mage chronicle can make players feel in their hands &mdash; and the '
           'recovery, when it comes, teaches what the Chorus&rsquo;s seat has always sung: the '
           'first stuff is a grace, and graces are noticed at their return.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on budgets, provenance, and '
                'famine</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The well has an economy,</span> and the law names its '
           'vessels.<sup>a</sup> The <span class="term">node</span>: a wellspring in the world '
           'where first stuff rises, held in tenure, worked like a living thing &mdash; overdrawn '
           'it sickens, tended it deepens, and its yield carries the <span '
           'class="term">resonance</span> of its place and keepers.<sup>b</sup> <span '
           'class="term">Tass</span>: quintessence embodied &mdash; the dew, the honey, the stone '
           'that is also fuel &mdash; portable, tradable, and flavored irrevocably by its source. '
           'The <span class="term">periapt</span>: a vessel charged to hold what patterns cannot, '
           'the mage&rsquo;s banked reserve. And the <span class="term">wonder</span>: the working '
           'folded into the thing and made to keep &mdash; charged by this Sphere, built with its '
           'partners, lasting as the fourth rank provides.<sup>c</sup> Two measures govern the '
           'economy entire. Resonance travels with the stuff: fuel is never neutral, and the '
           'working fed on wrath tastes of it. And the flow is finite where it is finite: the '
           'node&rsquo;s season, the periapt&rsquo;s cap, the Avatar&rsquo;s measure &mdash; the '
           'law of the well is that wells have bottoms, whatever the deep sources '
           'hold.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence tenure in first '
           'stuff &mdash; who may own a well of the world&rsquo;s own light? The chapter has heard '
           'this question before: folio 78 holds the property law entire, '
           'and this verso keeps only the economy&rsquo;s grammar. <span class="kw">IT HAPPENED '
           'THAT</span> two chantries shared a node on a parish boundary for two hundred years, '
           'splitting the yield by a treaty neither could produce when asked. A new prior demanded '
           'the document; the treasurers of both houses, who had met monthly for their whole '
           'tenures, testified that there had never been one &mdash; only the meeting, renewed. '
           'The prior drafted a proper charter; the node&rsquo;s yield thinned that season and the '
           'season after; and the charter was burned by mutual consent at the next meeting, after '
           'which the yield returned. The elders of both houses declined to explain, saying only '
           'that some economies are kept, not written. The disputants around this text have been '
           'arguing about that sentence ever since, it being either the deepest thing in the folio '
           'or a coincidence about weather.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Prime folio: the recto keeps the '
             'ladder, this side keeps the well.',
 'folio': '520B',
 'glossL': '<p><span class="mark">a</span> On the economy&rsquo;s vessels &mdash; nodes, tass, '
           'periapts, wonders &mdash; see M20&rsquo;s Prime entry, folios 519&ndash;520, and the '
           'setting chapters&rsquo; node material.</p>\n'
           '        <p><span class="mark">b</span> On resonance traveling with the stuff, see the '
           'same entry; the flavored fuel is the text&rsquo;s own doctrine.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On wonders permanent at the fourth '
           'rank &mdash; and the soulgem and soulflower above them &mdash; see the fourth and '
           'fifth ranks&rsquo; entries.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On caps and seasons &mdash; the '
           'Avatar&rsquo;s measure, the periapt&rsquo;s bound, the node&rsquo;s yield &mdash; see '
           'the same entry and folio 520a&rsquo;s first rank.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The node&rsquo;s property law is folio '
           '78b&rsquo;s; the commons-versus-title fight staged there is this '
           'verso&rsquo;s Gemara in long form, and the burned charter is the Masoret&rsquo;s early '
           'evidence for the commons.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The wonder built here wears '
           'folio 517b&rsquo;s body and this folio&rsquo;s charge; the Kelim tractate, K.1, '
           'wanting, inherits both, and its property law &mdash; the item that outlives its '
           'paradigm &mdash; is already visible from this page.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Resonance as flavor is '
           '515b&rsquo;s signature clause generalized: the storm remembers who called it, and the '
           'fuel remembers where it rose; the Book of Magick&rsquo;s materials all keep diaries, '
           'which 533b&rsquo;s census should note before trusting anything unwitnessed.</p>',
 'h1': 'The Well',
 'hagahah': 'Every economy in this tractate runs on something that remembers: reputation logs, '
            'lineage books, stapled retractions, flavored fuel. The Sphere&rsquo;s contribution is '
            'to make the money itself the witness, which the Syndicate noticed first and the '
            'Masoret notes last, both with professional admiration.',
 'inner': '<p><span class="lemma">Worked like a living thing.</span> The node&rsquo;s plain sense: '
          'yield is husbandry, not extraction &mdash; the well overdrawn sickens, fouls, or dies, '
          'and the tenure that strip-mines its own node has eaten its seed corn. Node-keeping is '
          'therefore a craft with seasons, and the chantry&rsquo;s gardener outranks its treasurer '
          'in every house that has survived a century.</p>\n'
          '        <p><span class="lemma">Flavored irrevocably.</span> Resonance&rsquo;s plain '
          'sense: quintessence carries the signature of its rising &mdash; the shrine&rsquo;s '
          'peace, the battlefield&rsquo;s iron, the server farm&rsquo;s hum &mdash; and the flavor '
          'enters what the fuel feeds. Workings inherit their fuel&rsquo;s temper; wonders charged '
          'on wrath run hot; and the mage herself, banking flavored stuff in her own pattern, is '
          'seasoning her soul on an installment plan, which folio 156b&rsquo;s watchers would '
          'recognize at a glance.</p>\n'
          '        <p><span class="lemma">The mage&rsquo;s banked reserve.</span> The '
          'periapt&rsquo;s plain sense: the vessel holds what the Avatar&rsquo;s cap will not, and '
          'the banked point is the Sphere&rsquo;s unit of preparedness &mdash; the working funded '
          'in advance, the wonder recharged in the field. The tactical corollary: periapts are '
          'targets, and the enemy who cannot beat the cabal can sometimes simply rob it, a genre '
          'the sibling tractates&rsquo; thieves have refined past anything this chapter '
          'teaches.</p>\n'
          '        <p><span class="lemma">Wells have bottoms.</span> The finitude clause&rsquo;s '
          'plain sense, and its deliberate edge: the law names every local bound &mdash; season, '
          'cap, measure &mdash; and stays silent on the total. Whether the world&rsquo;s first '
          'stuff is finite &mdash; whether the Ascension War is, among its other descriptions, a '
          'resource war over a fixed supply &mdash; is a question the recensions raise and '
          'decline, and the disputants opposite inherit it as the verso&rsquo;s deepest case.</p>\n'
          '        <p><span class="lemma">Tended it deepens.</span> The husbandry clause&rsquo;s '
          'upside, plainly: nodes answer keeping &mdash; the shrine swept, the rites renewed, the '
          'resonance curated &mdash; and the yield of a loved well grows over decades as the '
          'neglected one silts. The chantry&rsquo;s gardener is therefore its treasurer&rsquo;s '
          'equal in law and better in longevity, and the setting&rsquo;s oldest houses sit on '
          'wells whose tending predates their charters &mdash; inherited obligations first, income '
          'second, which every succession dispute in the corpus eventually relearns.</p>\n'
          '        <p><span class="lemma">Charged by this Sphere, built with its partners.</span> '
          'The wonder clause&rsquo;s plain sense: the artifact is a partnership in object form '
          '&mdash; the body built by Matter or Life, the working woven by whatever Sphere the '
          'wonder wields, the charge and permanence Prime&rsquo;s &mdash; and the fourth '
          'rank&rsquo;s craft is the folding, not the parts. The economy&rsquo;s consequence: '
          'wonders concentrate capital &mdash; quintessence, expertise, bench time &mdash; and the '
          'setting&rsquo;s treasuries are armories, its heists are acquisitions, and the Kelim '
          'tractate&rsquo;s property law, K.1, wanting, is already the corpus&rsquo;s most '
          'anticipated probate court.</p>\n'
          '        <p><span class="lemma">The Avatar&rsquo;s measure.</span> The personal '
          'cap&rsquo;s plain sense, restated from the recto because the economy turns on it: the '
          'unaided mage banks quintessence only to her Avatar&rsquo;s depth, and the '
          'Sphere&rsquo;s first rank raises the ceiling &mdash; so the well&rsquo;s whole '
          'vessel-system, periapt to node, exists because souls are small containers. The theology '
          'is optional; the logistics are not; and folio 43 inherits the question of why '
          'the container is sized as it is.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; vessels, flavors, and bottoms</span>',
 'name': 'The Well',
 'outer': '<p><span class="lemma">Kept, not written.</span> The burned charter, argued. <span '
          'class="voice">Some say</span> the elders named a real law: the node answered the '
          'charter because first stuff is responsive to the relations around it &mdash; the well '
          'fed by two hundred years of renewed trust was itself party to the treaty, and the '
          'parchment&rsquo;s claim of ownership curdled what the meeting&rsquo;s practice had kept '
          'sweet. On this reading folio 78&rsquo;s coming property fight is already decided: wells '
          'are held in relationship or not at all, and title is the thing that thins the yield. '
          '<span class="voice">Others say</span> weather: nodes ebb, seasons turn, and the human '
          'genius for reading covenant into coincidence is the same genius that built every altar '
          'in chapter V &mdash; the charter&rsquo;s burning changed the treasurers, not the water '
          'table, and the yield&rsquo;s return rewarded their reconciliation by chance and taught '
          'a theology by accident. The first school has the better story and the second the better '
          'epistemics, and the tractate observes that this exact ratio has decided every paradigm '
          'since the Shattering, which is either an argument for the first school or the whole '
          'problem, depending on the reader&rsquo;s Tradition.</p>\n'
          '        <p><span class="lemma">Fuel is never neutral.</span> The provenance dispute. '
          '<span class="voice">Some say</span> resonance is information, not morality: the '
          'wrathful tass works, the working tastes of iron, and a competent mage seasons to taste '
          'like any cook &mdash; the handwringing over dirty fuel is chapter V&rsquo;s codes '
          'mistaking flavor for sin. <span class="voice">Others say</span> the market&rsquo;s '
          'history reads otherwise: where fuel is never neutral, demand curves bend toward the '
          'darkest supply &mdash; the tass of suffering is potent, distinctive, and cheap wherever '
          'suffering is &mdash; and an economy that prices anguish will farm it, which is folio '
          '224&rsquo;s entire supply chain described politely. The flavor school answers that '
          'prohibition never once starved that market, only priced it; the provenance school '
          'answers that participation funds it at any price; and the chantry treasurers of the '
          'setting, who must actually buy fuel this season, keep both folios&rsquo; arguments in '
          'the ledger&rsquo;s margin, where this tractate keeps its honesty too.</p>\n'
          '        <p><span class="lemma">Whatever the deep sources hold.</span> The finitude '
          'dispute, briefly, at the edge where the law left it. <span class="voice">Some '
          'say</span> finite: the nodes are counted, the wars over them are real, and the '
          'Ascension War&rsquo;s material base is a fixed light divided &mdash; scarcity explains '
          'the Council, the Union, and most of the corpses. <span class="voice">Others say</span> '
          'the fifth rank falsifies the premise annually: nodes are <span '
          'class="aside">created</span>, wellsprings rise at great events, and the supply grows '
          'wherever meaning does &mdash; the light is fixed only in an age that has stopped '
          'meaning things, which is a diagnosis, not a geology. The first reading funds realism; '
          'the second funds hope; and the tractate notes that the setting&rsquo;s own name for '
          'victory &mdash; Ascension &mdash; reads naturally as the second school&rsquo;s economy '
          'achieved, which proves nothing and encourages everyone. <span class="kw">TEYKU</span> '
          '&mdash; let the well keep its bottom out of sight.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the charter, the fuel, and the bottom</span>',
 'rubric': 'the economy of the first stuff',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the well &middot; nodes, tass, and wonders',
 'title': 'Tractate Aliyah · Folio 520b — The Well: the economy of the first stuff',
 'type': 'daf'}
