# Folio 520a - Prime. Sphere mold (f515a); facts per the wod-llm-wiki
# Prime page (M20 pp.519-520).
FOLIO = {'bottom': '<p><span class="lemma">On the banker in the cabal.</span> Prime is infrastructure, and '
           'its player is the cabal&rsquo;s quartermaster of magic itself: the quintessence '
           'gathered, the wonders charged, the patterns fed. Give that player the ledger openly '
           '&mdash; pools, flows, the chantry&rsquo;s income and burn rate &mdash; and the '
           'Sphere&rsquo;s quiet drama surfaces: every other mage&rsquo;s reach exceeds her fuel, '
           'and the Prime mage is the one who says so aloud, at budget meetings, which the '
           'chronicle should actually stage.</p>\n'
           '        <p><span class="lemma">On the fifth dot.</span> Node-creation and '
           'Paradox-nullification are campaign-enders if priced as utilities: they are wonders of '
           'the age, and the Storyteller should stage them as such &mdash; a new Node is a new '
           'front in every faction&rsquo;s war, and a nullification is a legend told carefully, '
           'once. The master of Prime does not solve the cabal&rsquo;s problems; she changes what '
           'the map is a map of, and maps redrawn attract cartographers with guns.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Post the creation ruling beside '
           '533a&rsquo;s standards: when the second rank&rsquo;s partnership is owed, what ambient '
           'quintessence the table&rsquo;s scenes hold, and how the Avatar&rsquo;s cap binds the '
           'unfueled. The whole Book of Magick bills through this folio &mdash; every conjuration, '
           'every wonder, every fed pattern &mdash; and a table that rules Prime loosely has '
           'quietly repriced all nine ladders, usually by accident, always downward.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on ledgers, legends, and the price of '
                'loose rulings</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Prime is the Sphere of the first stuff:</span> quintessence, the '
           'raw energy patterned into all things, and its ladder climbs from seeing the flow to '
           'owning the well.<sup>a</sup> At the first rank the mage <span class="term">perceives '
           'and holds</span>: the flows read, resonance tasted, quintessence drawn into her own '
           'pattern past the Avatar&rsquo;s unaided cap. At the second she <span '
           'class="term">feeds and founds</span>: patterns new-made given their first fuel &mdash; '
           'the partnership every creation owes &mdash; and things enchanted to touch the '
           'untouchable: the blade that bites spirits, the armor that turns the unmaking '
           'wound.<sup>b</sup> At the third she <span class="term">channels</span>: quintessence '
           'drawn free-flowing from node and tass, stored in the periapt, shaped into weapons of '
           'raw radiance. At the fourth she <span class="term">binds and drains</span>: the flow '
           'pulled from things until they gray and crumble, wonders made lasting, the well of '
           'great events tapped.<sup>c</sup> At the fifth she <span class="term">owns the '
           'source</span>: life-force itself drawn or granted, nodes created where none were '
           '&mdash; and Paradox itself, the court of 533a, nullified by mastery of the stuff it '
           'polices.<sup>d</sup> One law attends the ladder, and it is the Book of Magick&rsquo;s '
           'spine: nothing is made from nothing without this Sphere&rsquo;s leave &mdash; Prime is '
           'senior partner to every creation, as folio 515b provides and every Sphere folio has '
           'confessed.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'ladder&rsquo;s cases. A hedge-chapel&rsquo;s font runs one cup of blessing a season, '
           'and the parish saint knows to the day when it fills: the first rank, perception, and '
           'the humblest working in this chapter. A swordsmith feeds her blade&rsquo;s pattern '
           'until it parts what has no body: the second rank, the enchanted edge, and half the '
           'setting&rsquo;s named blades besides. A chantry&rsquo;s treasurer walks the node-lines '
           'monthly, skimming the flow into periapts against the dry season: the third rank, '
           'worked as bookkeeping, which it is. And the archmage who stood where a node had never '
           'been and made one &mdash; and the other archmage, elsewhere, who faced a backlash the '
           'size of a verdict and canceled it &mdash; are the fifth rank&rsquo;s two famous cases, '
           'and the disputants opposite have been asked which of the two unmade more of the '
           'world&rsquo;s order, for it is not the one the young assume.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; seventh of the Sphere folios; the well and its '
             'economy wait overleaf.',
 'folio': '520A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Prime entire &mdash; quintessence, the '
           'odyllic force, the fifth essence &mdash; see M20, the Spheres chapter, folios '
           '519&ndash;520, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the second rank&rsquo;s pattern-founding and '
           'enchantment &mdash; weapons and wards against the unmaking wound &mdash; see the same '
           'entry.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On channeling, periapts, and the '
           'tapping of wellsprings, see the third and fourth ranks there; on draining unto ruin, '
           'the fourth.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On node-creation and the '
           'nullification of Paradox at the fifth rank, see the same entry&rsquo;s close; the '
           'tractate confirms the reader&rsquo;s double-take is warranted.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Celestial '
           'Chorus&rsquo;s, folio 150a, who call the first stuff divine and are not obviously '
           'wrong; the Syndicate&rsquo;s Primal Utility, folio 192, prices the same stuff '
           'and is not obviously wrong either, which is the chapter&rsquo;s joke told at its own '
           'expense.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The creation partnership '
           'confessed by every Sphere folio &mdash; 515a&rsquo;s ledger, 516a&rsquo;s checkpoint, '
           '517a&rsquo;s border &mdash; is this folio&rsquo;s law seen from the debtor&rsquo;s '
           'side; the famous conjunction fight&rsquo;s other half was staged at 517a as promised, '
           'and concludes opposite.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The life-blood this Sphere '
           'pools and the node-law it founds are folio 78&rsquo;s; the wells, tithes, and '
           'trespass of that folio will cite this one as their charter.</p>',
 'h1': 'Prime',
 'hagahah': 'Every Tradition&rsquo;s word for quintessence is a theology: the Chorus&rsquo;s '
            'divine substance, the Ether&rsquo;s subtle medium, the Syndicate&rsquo;s liquidity. '
            'The Sphere answers to all of them with perfect indifference, like water ignoring the '
            'argument between the well, the pipe, and the invoice.',
 'inner': '<p><span class="lemma">The raw energy patterned into all things.</span> The '
          'jurisdiction test: Prime owns the fuel, never the form. Where a working shares ground '
          'with a Pattern Sphere, ask what changed: if the form stood and only its charge moved '
          '&mdash; fed, drained, stored, shaped raw &mdash; this ladder worked alone. The '
          'corollary the young miss: Prime undoes nothing and makes nothing by itself; it is the '
          'purest partner Sphere in the nine, and its solo repertoire is exactly the flow.</p>\n'
          '        <p><span class="lemma">Past the Avatar&rsquo;s unaided cap.</span> The first '
          'rank&rsquo;s quiet revolution: the unaided mage holds quintessence only to her '
          'Avatar&rsquo;s measure, and Prime raises the ceiling. The plain sense for play is that '
          'the Sphere&rsquo;s first dot changes a character&rsquo;s economy before her capability '
          '&mdash; she can bank &mdash; and folio 43 owes this clause a '
          'cross-reference when it prices the Avatar itself.</p>\n'
          '        <p><span class="lemma">The partnership every creation owes.</span> The '
          'senior-partner law, plainly, and the conjunction fight&rsquo;s settled core: to stand a '
          'new pattern in the world &mdash; flame where no fuel was, flesh from raw light, matter '
          'from air &mdash; the maker pays in first stuff, and Prime&rsquo;s second rank writes '
          'the check. What remains disputed is the border traffic &mdash; 517a&rsquo;s loose '
          'school and its silent-partner theory &mdash; and the disputants opposite inherit it '
          'with the chapter&rsquo;s compliments.</p>\n'
          '        <p><span class="lemma">Until they gray and crumble.</span> The fourth '
          'rank&rsquo;s draining, plainly: patterns unfed do not explode, they exhaust &mdash; the '
          'drained blade goes brittle, the drained garden fails, the drained man &mdash; the fifth '
          'rank&rsquo;s business, and the law&rsquo;s coldest clause &mdash; goes out like a lamp. '
          'The Sphere&rsquo;s harm is starvation at every rank that deals it, which is why its '
          'masters are watched by the same instinct that watches the Wheel&rsquo;s people, and why '
          'the two Spheres&rsquo; seats have always understood each other across the chapter.</p>\n'
          '        <p><span class="lemma">Nullified by mastery.</span> The fifth rank&rsquo;s '
          'scandal, stated plainly because the law states it: the master of first stuff can pay '
          'Paradox&rsquo;s bill in Paradox&rsquo;s own coin &mdash; the backlash unwoven before it '
          'lands. The clause does not repeal 533a; it prices an appeal to a higher court, at costs '
          'that folio&rsquo;s standards never imagined, and the disputants opposite hold the '
          'implications, which are the chapter&rsquo;s largest.</p>\n'
          '        <p><span class="lemma">Resonance tasted.</span> The first rank&rsquo;s second '
          'sense, plainly: the flows carry flavor as 520b&rsquo;s economy provides, and the '
          'Prime-eye reads provenance off a working the way sommelier reads slope off a vintage '
          '&mdash; this fire fed from a node of wrath, that ward built on tithed peace. The '
          'forensic consequence threads the whole chapter: workings are attributable through their '
          'fuel, wonders through their charge, and the Sphere&rsquo;s perceivers are the Book of '
          'Magick&rsquo;s auditors, called to every scene the census of 533b cannot read.</p>\n'
          '        <p><span class="lemma">The blade that bites spirits.</span> The enchantment '
          'clause, plainly: the second rank&rsquo;s infusion lets the material touch the '
          'immaterial &mdash; the weapon that wounds ephemera, the armor that turns the unmaking '
          'wound &mdash; and the clause is the mundane cabal&rsquo;s whole insurance policy '
          'against chapter IV&rsquo;s neighbors. Priced plainly, renewed as charged, and the '
          'verso&rsquo;s periapts carry the ammunition: the Sphere&rsquo;s second dot is the most '
          'widely borrowed rung in the nine ladders, and the tractate&rsquo;s armories would empty '
          'without it.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; flow, cap, and partnership</span>',
 'name': 'Prime',
 'outer': '<p><span class="lemma">Which of the two unmade more.</span> The Gemara&rsquo;s paired '
          'archmages, argued. <span class="voice">Some say</span> the node-maker: a new well of '
          'first stuff redraws the world&rsquo;s deep map &mdash; ley and flow, tenure and tithe, '
          'the geography every faction&rsquo;s law assumes &mdash; and the wars a node seeds run '
          'for centuries; the nullifier merely dodged one verdict, a private grace with no heirs. '
          '<span class="voice">Others say</span> the young assume exactly this and are exactly '
          'wrong, as the Gemara warned: the node changes a map, but the nullification changes what '
          'law <span class="aside">is</span> &mdash; a court whose worst sentence can be unwoven '
          'by sufficient mastery is a court with a price list, and every mage who learns the '
          'clause exists has her relationship to 533a quietly restructured, paid or not, used or '
          'not. The world&rsquo;s order was never the map; it was the belief that the verdicts '
          'were final. The first school counts craters; the second counts precedents; and the '
          'tractate, which is itself a book of precedents, votes with its spine and says so.</p>\n'
          '        <p><span class="lemma">Senior partner to every creation.</span> The conjunction '
          'fight, concluded from Prime&rsquo;s side. <span class="voice">The imperial reading '
          'says</span> the whole Book of Magick is this folio&rsquo;s tributary system: every '
          'Sphere&rsquo;s creation clause is a borrowing, every transmutation&rsquo;s added '
          'measure a loan unbooked, and the loose school of 517a was right for the wrong reasons '
          '&mdash; Prime is everywhere, merely unbilled below the statutory line. <span '
          'class="voice">The federal reading says</span> the statute&rsquo;s line is the wisdom: '
          'the Book bills Prime where first stuff demonstrably enters and nowhere else, because a '
          'law that found Prime in everything would find it in nothing usefully &mdash; '
          'jurisdiction is not honored by annexation. The readings converge on every actual '
          'casting and diverge on every actual theology, which the folio of Focus, 567, '
          'inherits as its founding case; the Masoret has reserved it a pew.</p>\n'
          '        <p><span class="lemma">A court with a price list.</span> The nullification '
          'dispute, faced without flinching. <span class="voice">Some say</span> the clause is '
          'mercy at the summit: the master who can unweave backlash can shield the innocent '
          'bystander, the botched apprentice, the city block downwind of somebody&rsquo;s vulgar '
          'noon &mdash; and a power that mostly buys back catastrophe is the most defensible dot '
          'in the nine ladders. <span class="voice">Others say</span> read what the clause '
          'protects in practice: the masters themselves, whose workings are largest, whose bills '
          'are worst, and whose access to the appeal is exclusive by definition &mdash; the law of '
          '533a binds the small and licenses the great, which is not a court but a weather pattern '
          'with fees. The defenders&rsquo; best answer is the record: the nullifications on file '
          'are rescues, mostly, so far. The critics&rsquo; best answer is the phrase <span '
          'class="aside">so far</span>, and the archive of folio 164b, which never closes. <span '
          'class="kw">TEYKU</span> &mdash; let the appeal stay expensive. The pew reserved at 567 '
          'gains a plaque: the imperial and federal readings are, the Masoret suspects, the Chorus '
          'and the Adepts arguing metaphysics through jurisprudence, which is how this tractate '
          'prefers its theology anyway.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the two archmages, the tribute, and the appeal</span>',
 'rubric': 'the Sphere of the first stuff, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Prime &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 520a — Prime: the Sphere of the first stuff',
 'type': 'daf'}
