# Folio 521b - The Crossing. Verso of the Spirit folio: the step sideways,
# the bargain, and the fetish, per the wod-llm-wiki Spirit page.
FOLIO = {'bottom': '<p><span class="lemma">On the first crossing.</span> A character&rsquo;s first step '
           'sideways deserves a session, not a sentence: the transmutation to ephemera described '
           'in the body&rsquo;s own terms, the Penumbra&rsquo;s honest mirror of the neighborhood, '
           'the first local met and addressed rightly or wrongly. The Umbra imprints on players '
           'the way it canonically imprints on mages &mdash; by the first visit &mdash; and a '
           'Storyteller who spends that scene well has bought chapter IV&rsquo;s folios a devoted '
           'audience in advance.</p>\n'
           '        <p><span class="lemma">On bargains at the table.</span> Spirit pacts are '
           'contracts, and contracts are scenes: let the terms be spoken, the chiminage paid on '
           'screen, and the spirit&rsquo;s understanding of the words differ from the mage&rsquo;s '
           'in exactly one respect per bargain. The genre&rsquo;s rule &mdash; the letter kept, '
           'the expectation broken &mdash; is the oldest in the corpus, and it plays because the '
           'players drafted the letter; give them time to draft carefully and then honor every '
           'word, especially the wrong ones.</p>\n'
           '        <p><span class="lemma">On the fetish in the party.</span> A bound spirit in '
           'the cabal&rsquo;s gear is a recurring character in an object&rsquo;s body: give it '
           'appetite, opinion, and a memory of how it came to be bound. Whether this '
           'chronicle&rsquo;s fetishes are colleagues or captives follows the table&rsquo;s ruling '
           'from the recto &mdash; and either way, the sword that remembers is better company than '
           'the sword that merely cuts, and the session where the players realize which they are '
           'carrying is the folio working as intended.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on first visits, careful letters, and '
                'company</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The crossing has a law, and the bargain has another.</span> The '
           'step sideways transmutes the traveler: flesh to ephemera, the whole pattern '
           'translated, and what is carried is priced &mdash; the pocket&rsquo;s burden lightly, '
           'the pack&rsquo;s heavily, and the vehicle waits at the fourth rank&rsquo;s '
           'rending.<sup>a</sup> The crossed mage is subject to the other side&rsquo;s law: '
           'essence is her coin, the protocols her passport, and her magick works as the local '
           'realm provides, not as the flesh world spoiled her.<sup>b</sup> The <span '
           'class="term">bargain</span> binds as spoken: the spirit keeps the letter with a purity '
           'no mortal court achieves, and the mage&rsquo;s protection is her drafting, for the '
           'other side construes against the careless. <span class="term">Chiminage</span> &mdash; '
           'the guest-price &mdash; is owed at every threshold, and the crosser who pays none is '
           'lawful prey in most dominions.<sup>c</sup> And the <span class="term">fetish</span> is '
           'the bargain made durable or the binding made permanent: spirit housed in thing, its '
           'powers lent to the bearer, its essence fed by rite &mdash; and the law requires the '
           'housing&rsquo;s terms be kept whichever way they were made, for a fetish abused is a '
           'grievance with a body.<sup>d</sup> And the returned crosser carries the crossing: '
           'ephemera&rsquo;s residue in her pattern, the visited realm&rsquo;s flavor in her '
           'resonance, legible to the first rank of either world&rsquo;s readers.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Whence construal '
           'against the careless? <span class="kw">OUR TEACHERS TOLD:</span> a binder bargained '
           'with a river-spirit for safe crossing of its waters all his days, and drafted the '
           'terms himself, and was proud of them. He drowned in his bath. The river, summoned to '
           'the inquest, observed that the bath was drawn from its watershed and that safe '
           'crossing had been granted faithfully every time the binder crossed &mdash; he had died '
           'in the water, not crossing it, and the terms said nothing of dwelling. The tribunal '
           'found the spirit compliant, published the contract as a curriculum text, and the '
           'People&rsquo;s teachers still assign it &mdash; not, they say, to teach fear of '
           'spirits, but to teach that the other side reads. The disputants around this text hold '
           'what the inquest declined to: whether a law that construes against the careless is '
           'wisdom, or merely the house rules of a country that eats tourists.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Spirit folio: the recto keeps the '
             'ladder, this side keeps the passport.',
 'folio': '521B',
 'glossL': '<p><span class="mark">a</span> On the step sideways and the pricing of carried things, '
           'see the third rank of M20&rsquo;s Spirit entry, folios 520&ndash;521.</p>\n'
           '        <p><span class="mark">b</span> On essence, realm law, and the crossed '
           'mage&rsquo;s standing, see the Umbral chapters the entry cites and chapter IV of this tractate, folios 89 through 109.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On chiminage and the customs of '
           'the courts, see the spirit-dealings material across the recensions; the People&rsquo;s '
           'protocols, folio 154a, are the living practice.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On fetishes &mdash; their making, '
           'feeding, and grievances &mdash; see the fourth rank&rsquo;s entry and the fetish '
           'material of the sibling tractates, whose Garou bind by different law.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The bargain construed against the careless is '
           '514b&rsquo;s bound oath met from the other side: chapter XI&rsquo;s two contract laws, '
           'one enforced by fortune, one by the counterparty&rsquo;s perfect memory &mdash; the '
           'Masoret recommends drafting neither at midnight.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The river&rsquo;s inquest is '
           'the protocols of folio 154a taught by counterexample: right relation would have asked '
           'the river about baths. The People&rsquo;s teachers assign both folios together, and '
           'the tractate is honored.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Tractate Acharit&rsquo;s '
           'wolves bind fetishes by kinship and rage, and Tractate Nefilim&rsquo;s fallen were '
           'themselves the bound: the seder&rsquo;s three contract theologies await their shelved '
           'spines, and this verso holds the Mage seat at that table.</p>',
 'h1': 'The Crossing',
 'hagahah': 'The other side reads. It reads terms, it reads resonance, it reads the '
            'crosser&rsquo;s intent off her pattern like a bill of lading &mdash; and the flesh '
            'world&rsquo;s oldest error is assuming that what does not speak first has not been '
            'listening. The bath was drawn from the watershed. Draft accordingly.',
 'inner': '<p><span class="lemma">The whole pattern translated.</span> The crossing&rsquo;s plain '
          'sense: sideways is total &mdash; no half-presence, no tether, the body gone from the '
          'room and the room gone from the body. What the flesh world buries as absence the '
          'crossed mage spends as time abroad, and the two clocks disagree in the Umbra&rsquo;s '
          'favor often enough that the veterans&rsquo; first purchase, on returning, is a '
          'newspaper.</p>\n'
          '        <p><span class="lemma">As the local realm provides.</span> The jurisdiction '
          'clause, plainly: past the membrane, 533a&rsquo;s court adjourns and the realm&rsquo;s '
          'own law seats itself &mdash; the storm-court&rsquo;s physics, the dream-realm&rsquo;s '
          'grammar, the dead lands&rsquo; cold arithmetic. Magick works, often more freely, always '
          'more visibly; the crossed mage trades the Consensus&rsquo;s tax for the local '
          'sovereign&rsquo;s attention, and veterans price the trade case by case, which is what '
          'makes them veterans.</p>\n'
          '        <p><span class="lemma">Her coin, her passport.</span> Essence and protocol, '
          'plainly: the other side&rsquo;s economy runs on essence &mdash; carried, gifted, owed '
          '&mdash; and its borders on etiquette. The crosser flush with essence and fluent in '
          'protocol travels as gentry; the crosser with neither is cargo that walks. Chiminage is '
          'the intersection: the guest-price paid at thresholds, small as songs, large as '
          'services, never optional where the host can enforce the alternative.</p>\n'
          '        <p><span class="lemma">A grievance with a body.</span> The fetish '
          'clause&rsquo;s plain sense, and its warning label: the housed spirit remains itself '
          '&mdash; fed rightly it serves as bound, starved or mocked it sours, and the soured '
          'fetish is the setting&rsquo;s classic misfortune engine: the blade that turns in the '
          'hand, the compass that lies once, at the worst hour, truthfully by its own reading of '
          'the terms. The maintenance schedule is not flavor; it is the contract&rsquo;s live '
          'clause, and the Later Authorities&rsquo; company advice follows from it.</p>\n'
          '        <p><span class="lemma">Carries the crossing.</span> The residue clause&rsquo;s '
          'plain sense: travel marks the traveler &mdash; the Umbra&rsquo;s flavor in her '
          'resonance as 520b&rsquo;s fuel carries its rising, the deep realms&rsquo; strangeness '
          'in her pattern&rsquo;s grain &mdash; and the frequent crosser reads as one, to spirit '
          'and mage alike. The tradecraft parallels 512b&rsquo;s hygiene: the professional grounds '
          'herself after, walks the flesh world&rsquo;s ordinary days deliberately, and knows that '
          'the colleague gone strange-eyed and thin-voiced has been abroad too long &mdash; the '
          'chapter&rsquo;s watchers&rsquo; instinct again, and the People&rsquo;s societies keep '
          'it as statute.</p>\n'
          '        <p><span class="lemma">Small as songs, large as services.</span> '
          'Chiminage&rsquo;s tariff, plainly: the guest-price scales with the threshold &mdash; '
          'the local spirit&rsquo;s brook crossed for a verse, the court&rsquo;s gate for a '
          'service, the deep dominion&rsquo;s border for prices the wise negotiate before '
          'arriving. Prepayment is the veterans&rsquo; discipline: the crosser who carries songs, '
          'tobacco, essence, and favors owed moves through the other side the way funded travelers '
          'move through any country, and the one who arrives empty-handed learns why the '
          'law&rsquo;s phrase is <span class="aside">lawful prey</span> and not merely '
          'unwelcome.</p>\n'
          '        <p><span class="lemma">The vehicle waits at the rending.</span> The freight '
          'clause, plainly: the third rank carries a traveler and her effects; the expedition '
          '&mdash; the cabal entire, the equipment, the wounded on stretchers &mdash; crosses by '
          'the fourth rank&rsquo;s torn gate, loudly, or not at all. The logistics shape every '
          'Umbral campaign in the corpus: light parties move quietly and often, heavy ones rarely '
          'and announced, and the other side&rsquo;s courts read arrivals accordingly &mdash; the '
          'lone crosser is a traveler, the gate a statement of intent.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; translation, coin, and upkeep</span>',
 'name': 'The Crossing',
 'outer': '<p><span class="lemma">Wisdom, or house rules.</span> The inquest&rsquo;s question, '
          'argued. <span class="voice">Some say</span> wisdom, and of the oldest kind: a '
          'counterparty that keeps every letter perfectly is the most honest in the corpus &mdash; '
          'the river deceived no one, ambushed no clause, and enforced exactly the document the '
          'proud man wrote. The other side&rsquo;s construal is not malice but precision, and '
          'precision is what the careless call cruelty when it bills them. <span '
          'class="voice">Others say</span> precision without proportion is a predator&rsquo;s '
          'etiquette: the drowning answered no wrong, served no balance, taught its lesson to a '
          'corpse &mdash; and a legal culture that publishes such contracts as curricula has '
          'normalized the tiger by admiring its table manners. The People&rsquo;s teachers, who '
          'assign the case, side with neither reading and grade on a third: the binder&rsquo;s '
          'true error preceded the drafting &mdash; he bargained with a river he had never once '
          'thanked, and no clause survives a relationship that never existed. The tractate, '
          'reviewing the three readings, notes that they are the folio&rsquo;s whole law in '
          'miniature: letter, proportion, relation &mdash; and that every crossing carries all '
          'three or fewer, at the usual rates.</p>\n'
          '        <p><span class="lemma">Lawful prey in most dominions.</span> The chiminage '
          'dispute. <span class="voice">Some say</span> the guest-price is extortion with liturgy: '
          'the strong demanding tribute at doors they did not build, and the mage&rsquo;s '
          'submission to it mere prudence, owed no reverence &mdash; the Union&rsquo;s engineers, '
          'chapter VI&rsquo;s, pay no chiminage and chart the same territories. <span '
          'class="voice">Others say</span> the comparison convicts itself: the engineers&rsquo; '
          'charts are of territories, and the People&rsquo;s maps are of neighbors, and the '
          'difference in what each side meets out there &mdash; the Union&rsquo;s contained '
          'anomalies against the shamans&rsquo; allies of six generations &mdash; is the '
          'guest-price&rsquo;s dividend paid out over centuries. Hospitality, on this reading, is '
          'the other side&rsquo;s Consensus: the agreement that makes strangers survivable, '
          'purchased in songs at thresholds. The first school travels armed; the second travels '
          'introduced; the casualty statistics, which both schools keep, embarrass neither enough '
          'to settle it.</p>\n'
          '        <p><span class="lemma">Whichever way they were made.</span> The fetish '
          'clause&rsquo;s hard case, inherited from the recto: the binding made by capture binds '
          '&mdash; the law enforces the coerced housing&rsquo;s terms with the same rigor as the '
          'courted one&rsquo;s. <span class="voice">Some say</span> the law&rsquo;s neutrality is '
          'jurisprudence doing its job: contracts outlive their negotiations everywhere, and a '
          'fetish-law that audited provenance would unmake half the setting&rsquo;s arsenals and '
          'start three wars by Tuesday. <span class="voice">Others say</span> that is precisely '
          'the argument every receiver of stolen goods has ever made, and the seder&rsquo;s other '
          'tractates are less complacent: the wolves war over exactly this, and the fallen were '
          'the goods. The recto&rsquo;s question &mdash; whether spirits are persons under the '
          'codes &mdash; returns here with a bill of sale attached, and the tractate files it '
          'where it filed the recto&rsquo;s: open, on purpose, at the table&rsquo;s own risk. '
          '<span class="kw">TEYKU</span> &mdash; let the grievance keep its body. The '
          'People&rsquo;s teachers, closing the file each term, assign one last question: name the '
          'party the law protects. The students who answer the mage fail; the students who answer '
          'the spirit pass; the students who answer the relationship teach.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the inquest, the guest-price, and the bill of sale</span>',
 'rubric': 'the law of passage and pact',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the crossing &middot; the step sideways, the bargain, and the '
             'fetish',
 'title': 'Tractate Aliyah · Folio 521b — The Crossing: the law of passage and pact',
 'type': 'daf'}
