# Folio 521a - Spirit. Sphere mold (f515a); facts per the wod-llm-wiki
# Spirit page (M20 pp.520-521).
FOLIO = {'bottom': '<p><span class="lemma">On the spirit-worker in the cabal.</span> Spirit is the Sphere '
           'of a second setting: its adept carries a passport the rest of the cabal lacks, and the '
           'Storyteller&rsquo;s craft is keeping both worlds in one story &mdash; the '
           'Penumbra&rsquo;s honest mirror consulted like a witness, the spirit courts&rsquo; '
           'politics bleeding into the street&rsquo;s. Let the Umbra answer questions the flesh '
           'world hides and demand prices the flesh world never imagined, and the chronicle earns chapter IV&rsquo;s folios in advance.</p>\n'
           '        <p><span class="lemma">On the crossing as commitment.</span> Stepping sideways '
           'strands the body&rsquo;s world: the crossed mage is elsewhere, truly, and the table '
           'should feel the door close &mdash; time flowing strangely, the phone dead, the cabal '
           'split across a membrane. Price the luggage as the law does, brief the players on the '
           'protocols of wherever they land &mdash; folio 154a&rsquo;s People wrote the etiquette '
           '&mdash; and never let the Umbra become a fast-travel system; it is a country, and '
           'countries have customs in both senses.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Post the Gauntlet&rsquo;s local '
           'readings in session zero &mdash; the lab thick, the wild thin, the node&rsquo;s '
           'strange weather &mdash; and rule early on the binding question the folio argues: '
           'whether this chronicle&rsquo;s spirits are persons in the codes&rsquo; full sense. '
           'Every scene with a fetish, a summons, or a bargain inherits that ruling, and a table '
           'that leaves it implicit will discover it mid-scene, loudly, over somebody&rsquo;s new '
           'sword.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on two worlds in one story, and the '
                'ruling under every bargain</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Spirit is the Sphere of the other side:</span> the worlds behind '
           'the world, the beings native there, and the membrane between &mdash; the <span '
           'class="term">Gauntlet</span>, which thickens where disbelief is dense and thins at the '
           'sacred and the wild.<sup>a</sup> At the first rank the mage <span '
           'class="term">perceives</span>: the local membrane&rsquo;s weight read, spirits sensed, '
           'the Penumbra glimpsed in reflection. At the second she <span '
           'class="term">touches</span>: the membrane thinned or thickened by degrees, spirits '
           'hailed and briefly reached.<sup>b</sup> At the third she <span class="term">crosses '
           'and rouses</span>: the step sideways, flesh made ephemera &mdash; luggage priced by '
           'the pound &mdash; and the sleeping spirit of place or thing roused to speech, or the '
           'restless one lulled.<sup>c</sup> At the fourth she <span class="term">rends and '
           'binds</span>: gates torn for the many, breaches sealed, spirits compelled to appear '
           'and bound into fetish or place, the possessing thing cast out. At the fifth she <span '
           'class="term">works ephemera as a maker</span>: realms shaped, essence poured or '
           'drained, the soul instilled &mdash; and the one sentence this tractate has already '
           'trembled at, <span class="term">Gilgul</span>, the Avatar&rsquo;s destruction, which '
           'is this rank&rsquo;s power and the Council&rsquo;s gravest verdict.<sup>d</sup> One '
           'law attends the ladder: the other side is inhabited &mdash; every crossing is an '
           'arrival in someone&rsquo;s country, and the Sphere grants passage, never welcome.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'cases. A medicine worker reads a hospital&rsquo;s membrane and finds it thick as vault '
           'steel, and the same worker at a crossroads shrine wades it like water: the first rank, '
           'and the map it draws is folio 82&rsquo;s. A city shaman rouses the spirit of '
           'a hundred-year bridge to ask what it has carried and when it will fall: the third '
           'rank, and the bridge answers slowly, being old. A binder chains a storm-spirit into a '
           'war-fetish for a client with excellent references: the fourth rank, lawful in every '
           'letter &mdash; and the disputants opposite have the case, for the letter is not where '
           'the argument lives. And the tribunal that sentenced the betrayer of folio 2b invoked '
           'this ladder&rsquo;s summit; the tractate&rsquo;s first grief and this folio&rsquo;s '
           'last power are the same sentence, and the Masoret has waited nine folios to say so in '
           'the Sphere&rsquo;s own house.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; eighth of the Sphere folios; the '
             'crossing&rsquo;s law waits overleaf.',
 'folio': '521A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Spirit entire, see M20, the Spheres '
           'chapter, folios 520&ndash;521, whence this page takes its number; on the '
           'Gauntlet&rsquo;s ratings by locale, the systems chapter&rsquo;s chart and folio 82.</p>\n'
           '        <p><span class="mark">b</span> On thinning and thickening by degrees &mdash; '
           'and the floor beneath which no earthly working drops the membrane &mdash; see the '
           'second rank&rsquo;s entry.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On stepping sideways and the '
           'pricing of carried things, see the third rank; on rousing and lulling, the same.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On binding, exorcism, realm-craft, '
           'and Gilgul, see the fourth and fifth ranks; on the sentence&rsquo;s use at the First '
           'Cabal&rsquo;s trial, folio 2b of this tractate.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the '
           'Dreamspeakers&rsquo;, folio 154a, whose protocols are the law this ladder grants no '
           'one: passage, never welcome. The Union&rsquo;s Dimensional Science, folio 194, '
           'is the girsa that maps where the People make relatives.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The bargain and the binding '
           'argued opposite reach across the seder: the fallen angels of Tractate Nefilim are the '
           'corpus&rsquo;s great case study in pacts with the ephemeral, and the Masoret winks at '
           'that tractate&rsquo;s empty spine with genuine respect.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Gilgul ties this folio to '
           '2b&rsquo;s trial, 148b&rsquo;s Wheel, and 156a&rsquo;s one absolute murder: the '
           'chapter&rsquo;s doctrines of the soul all converge on the fifth rank&rsquo;s worst '
           'clause, which is why the tractate keeps saying the Book of Magick is about everything '
           'else first.</p>',
 'h1': 'Spirit',
 'hagahah': 'The Sphere grants passage, never welcome. Every Tradition&rsquo;s first lesson about '
            'the other side is some phrasing of this clause, and every Tradition&rsquo;s first '
            'casualty is someone who heard it as travel advice rather than law.',
 'inner': '<p><span class="lemma">Thickens where disbelief is dense.</span> The Gauntlet&rsquo;s '
          'plain sense: the membrane is the Consensus&rsquo;s skin &mdash; thick where the world '
          'is most agreed upon, thin where wonder or wildness loosens the weave &mdash; and the '
          'first rank&rsquo;s reading of it is the Sphere&rsquo;s tactical literacy. The '
          'laboratory&rsquo;s vault-steel and the shrine&rsquo;s wading water are the same law at '
          'two densities, and folio 82 keeps the gazetteer.</p>\n'
          '        <p><span class="lemma">By degrees, above the floor.</span> The second '
          'rank&rsquo;s clause, plainly: the membrane moves success by success, and no working on '
          'living earth thins it past the law&rsquo;s floor &mdash; the door can be loosened, '
          'never removed. The floor is the folio&rsquo;s quiet mercy in both directions: the flesh '
          'world cannot be casually flooded, and the other side cannot be casually invaded, and '
          'both sides&rsquo; borders have professional opinions about mages who try.</p>\n'
          '        <p><span class="lemma">Luggage priced by the pound.</span> The crossing&rsquo;s '
          'plain sense: the step sideways transmutes the traveler to ephemera, and everything '
          'carried raises the toll &mdash; the ordinary burden a little, the bulky one more, and '
          'the verso holds the schedule. The tactical meaning is the chapter&rsquo;s recurring '
          'lesson: the other side is entered light or entered slowly, and the war-party&rsquo;s '
          'crossing is the fourth rank&rsquo;s rending, loud as law allows.</p>\n'
          '        <p><span class="lemma">Roused to speech.</span> The animist clause, plainly: '
          'everything has a spirit, mostly asleep &mdash; the bridge, the engine, the office tower '
          '&mdash; and the third rank wakes what the People&rsquo;s protocols then address. Note '
          'the division of labor the chapter has already taught: the Sphere opens the '
          'conversation; the relationship conducts it; and the mage who rouses what she cannot '
          'befriend has made a stranger, at midnight, in its own house.</p>\n'
          '        <p><span class="lemma">Passage, never welcome.</span> The inhabited '
          'clause&rsquo;s plain sense, and the folio&rsquo;s center of gravity: the Umbra is '
          'jurisdictions all the way out &mdash; courts, broods, dominions, things older than the '
          'naming of things &mdash; and every rank of this ladder is diplomatic capacity, not '
          'sovereignty. The mage crosses as a foreigner, works as a guest or a burglar, and is '
          'remembered either way; the other side&rsquo;s memory is long, communal, and &mdash; the '
          'People attest &mdash; occasionally forgiving.</p>\n'
          '        <p><span class="lemma">Glimpsed in reflection.</span> The Penumbra clause, '
          'plainly: the first rank&rsquo;s sight opens on the near shadow &mdash; the '
          'place&rsquo;s honest mirror, showing what it is rather than how it looks &mdash; and '
          'the reading is the Sphere&rsquo;s investigative gift: the sweatshop&rsquo;s Penumbra '
          'bleeds, the loved house&rsquo;s glows, and folio 89 keeps the atlas. The '
          'consequence for play arrives before any crossing: the Spirit-worker knows what every '
          'place <span class="aside">means</span>, which is intelligence no camera gathers and no '
          'ward against sight &mdash; folio 512b noted &mdash; was ever built to stop.</p>\n'
          '        <p><span class="lemma">The possessing thing cast out.</span> The exorcism '
          'clause, plainly: the fourth rank contests the occupied body &mdash; wills opposed at '
          'the root, the intruder&rsquo;s grip against the mage&rsquo;s art and the host&rsquo;s '
          'own remainder &mdash; and the law&rsquo;s shape is the chapter&rsquo;s familiar '
          'decency: the power to bind is housed one rung with the power to free, and the '
          'Tradition&rsquo;s seat teaches the freeing first. The sibling tractates keep the '
          'possessed of their own lines; this folio&rsquo;s clause is the Mage seat at that '
          'bedside, and the protocols&rsquo; etiquette governs even eviction: the cast-out spirit '
          'is escorted, not obliterated, save where folio 224&rsquo;s cases begin.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; membrane, toll, and jurisdiction</span>',
 'name': 'Spirit',
 'outer': '<p><span class="lemma">Lawful in every letter.</span> The binding dispute, the '
          'folio&rsquo;s engine. <span class="voice">Some say</span> binding is the Sphere&rsquo;s '
          'honest craft: spirits are not persons but patterns of purpose &mdash; the storm wants '
          'to storm, the blade-spirit wants to bite &mdash; and the fetish is employment, not '
          'enslavement: purpose given place, essence paid as wages, the compact&rsquo;s terms '
          'enforceable by either side&rsquo;s law. The People&rsquo;s own smiths bind, they note, '
          'with songs and consent. <span class="voice">Others say</span> the exception convicts '
          'the rule: where binding is courtship it needs no fourth rank &mdash; the compelled '
          'appearance, the chained storm, the war-fetish for a client are capture, and the whole '
          'vocabulary of the rank &mdash; compel, bind, cast out &mdash; is a slaver&rsquo;s '
          'lexicon read aloud in court. Between the schools stands the question the Later '
          'Authorities posted: whether spirits are persons under the codes &mdash; and the '
          'chapter&rsquo;s own seats split, the People&rsquo;s protocols answering yes in '
          'practice, the Hermetic grimoires answering no in Latin, and the fallen of Tractate '
          'Nefilim answering, from their empty spine, that this exact question is how their book '
          'begins.</p>\n'
          '        <p><span class="lemma">The membrane between.</span> The Gauntlet&rsquo;s status '
          'dispute. <span class="voice">Some say</span> the Gauntlet is scar tissue: the '
          'Consensus&rsquo;s wound where the worlds were sundered, thickened by centuries of '
          'trained disbelief &mdash; the Union&rsquo;s masterwork whether or not its founders drew '
          'the plans &mdash; and every thinning is therefore a small mending of the world. <span '
          'class="voice">Others say</span> the membrane is load-bearing: whatever raised it, the '
          'two worlds have grown apart beneath it, and the borders now protect both sides &mdash; '
          'the flesh world from the Umbra&rsquo;s appetites, the spirit courts from the '
          'Consensus&rsquo;s flattening &mdash; so the mender who dreams of no Gauntlet at all is '
          'dreaming somebody&rsquo;s apocalypse, and both sibling tractates of the seder keep '
          'folios saying whose. The first school works to thin; the second to tend; and the '
          'People, asked which school holds their proxy, answer that the door is not the point, '
          'the neighbors are &mdash; which is not a ruling but has governed better than most.</p>\n'
          '        <p><span class="lemma">The same sentence.</span> Gilgul, faced in the '
          'Sphere&rsquo;s own house. <span class="voice">Some say</span> the power&rsquo;s '
          'existence at the fifth rank is simple honesty: the ladder that instills souls can '
          'uninstall them, as the healer&rsquo;s law cuts &mdash; the summit sees both slopes, and '
          'pretending otherwise would only move the knowledge into worse hands. <span '
          'class="voice">Others say</span> the tractate has already ruled and should not blink '
          'now: folio 156a called the soul&rsquo;s destruction the one murder absolute, folio 148b '
          'called it the Wheel broken, and a Council that keeps the sentence on its books &mdash; '
          'and used it, folio 2b, at its very founding &mdash; has built its house over the one '
          'power its own law calls unforgivable. The defenders answer that the alternative to a '
          'sentence is a secret, and secrets of this size are how the Fallen recruit; the critics '
          'answer that legality is how institutions forget to be horrified; and the tractate, '
          'whose first grief this was, declines for once to balance the scales with a joke. <span '
          'class="kw">TEYKU</span> &mdash; and let this one stand in silence.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the binding, the membrane, and the sentence</span>',
 'rubric': 'the Sphere of the other side, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Spirit &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 521a — Spirit: the Sphere of the other side',
 'type': 'daf'}
