# Folio 522a - Time. Sphere mold (f515a); facts per the wod-llm-wiki Time
# page (M20 pp.521-523, charts p.505). Faces Salonikas from the mechanics
# side, as the brief requires.
FOLIO = {'bottom': '<p><span class="lemma">On the seer at the table.</span> Time&rsquo;s second rank hands '
           'a player the Storyteller&rsquo;s own instrument, and the folio of the Burden, 152b, '
           'has already carried the working doctrine: texture over transcript, the leaning of '
           'futures rather than their footage. Run every glimpse as weather &mdash; probable, '
           'partial, perspectival &mdash; and reserve the sharp image for moments the chronicle '
           'can afford to keep, because the table will keep them: a shown future is a promise or a '
           'betrayal, and the Storyteller should know which she is making before she describes '
           'anything.</p>\n'
           '        <p><span class="lemma">On bullet time and the action economy.</span> The third '
           'rank&rsquo;s multiplied actions are the Sphere&rsquo;s combat signature and its '
           'bookkeeping hazard: extra deeds, one working of magick a turn, the world slowed frame '
           'by frame. Run it as written and sparingly witnessed &mdash; nothing reads vulgar '
           'faster than the impossible dodge &mdash; and remember the folio&rsquo;s standing '
           'counsel: the mage who stretches seconds is borrowing them, and 533a&rsquo;s court has '
           'a page for borrowers.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Decide the chronicle&rsquo;s '
           'metaphysic of futures in session zero, as 152b directed, and add this folio&rsquo;s '
           'two rulings: whether glimpsed futures bind the Storyteller&rsquo;s plotting, and how '
           'the table handles the rewind &mdash; the verso&rsquo;s whole subject &mdash; whose '
           'retcons touch every player&rsquo;s agency at once. Time is the one Sphere whose '
           'mechanics are made of the medium the game itself is made of; rule it in daylight.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on promises, borrowed seconds, and '
                'the medium itself</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Time is the Sphere of the flow:</span> the current all patterns '
           'ride, and its ladder climbs from hearing the current to leaving it.<sup>a</sup> At the '
           'first rank the mage <span class="term">perceives</span>: the internal clock made '
           'perfect, the ripples of other time-workings felt as a fisherman feels wakes. At the '
           'second she <span class="term">looks along the stream</span>: the past and future of '
           'her place glimpsed hazily, farther by success as the verso&rsquo;s chart provides '
           '&mdash; and, reversed, the walls of time thickened against other lookers, success '
           'cancelling success.<sup>b</sup> At the third she <span class="term">works the '
           'current&rsquo;s pace</span>: her own moments multiplied, a target&rsquo;s slowed, the '
           'surroundings rewound a breath or two &mdash; the small retcon whose large sibling the '
           'verso tries.<sup>c</sup> At the fourth she <span class="term">steps out and sets '
           'snares</span>: withdrawal from the flow, workings hung on triggers, beings bubbled '
           'outside the stream, the anchor driven for mastery&rsquo;s travel. At the fifth she '
           '<span class="term">travels</span>: forward, backward, or out entire &mdash; and the '
           'law prices the backward road as no other working in the nine ladders is priced, as the '
           'verso recounts.<sup>d</sup> One law attends the ladder, and 152b carried its ethics '
           'before this folio carried its engine: the glimpsed future is a leaning, not a ledger '
           '&mdash; the seer reads pressure, and the pressure includes her reading.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and hear the '
           'Sphere faced where the tractate has twice promised to face it: at Salonikas. The '
           'master of this ladder saw the First Cabal&rsquo;s betrayal &mdash; folio 2b &mdash; '
           'and did not speak, and the court of folio 3a held his silence privileged, ruling vii, '
           'and the Burden of 152b argued the ethics to a standstill. This folio holds only the '
           'mechanics, and they are these: he glimpsed along the second rank, wherein futures '
           'crowd hazily and the telling is itself a working; he did not rewind along the third, '
           'for the third rewinds breaths, not betrayals; and the fifth rank&rsquo;s backward '
           'road, which could have carried him to the ambush&rsquo;s eve, is priced by the law '
           '&mdash; the verso says how &mdash; at rates that turn rescue into legend and legend '
           'into warning. The seer&rsquo;s silence, read from this folio, was not only conscience: '
           'it was arithmetic. The disputants opposite are asked whether that reading honors him '
           'or the ladder, and whether those are different questions.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; last of the nine Sphere folios; the rewind '
             'waits overleaf, and the chapter&rsquo;s ladders are all bound.',
 'folio': '522A',
 'glossL': '<p><span class="mark">a</span> On the Sphere of Time entire, see M20, the Spheres '
           'chapter, folios 521&ndash;523, whence this page takes its number; no Convention keeps '
           'a variant &mdash; the flow is the flow.</p>\n'
           '        <p><span class="mark">b</span> On looking along the stream and thickening its '
           'walls, see the second rank&rsquo;s entry; the reach chart is the verso&rsquo;s to '
           'restate.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On multiplied moments, slowed '
           'targets, and the small rewind, see the third rank&rsquo;s entry.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On triggers, bubbles, anchors, and '
           'travel, see the fourth and fifth ranks; on the backward road&rsquo;s pricing, the '
           'verso and its citations.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The seat of this Sphere is the Cult of '
           'Ecstasy&rsquo;s, folio 152a, and its mistress shares her Avatar with the master this '
           'folio&rsquo;s Gemara faces; the chapter&rsquo;s circle closes where the '
           'tractate&rsquo;s grief began, which the Masoret declines to call coincidence in a '
           'folio about fate.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The seer&rsquo;s ethics are '
           '152b&rsquo;s and the court&rsquo;s ruling is 3a&rsquo;s, vii; this folio completes the '
           'triangle with the engine, and the three pages should be read as one case wearing three '
           'bindings.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> Whether the rewind unmakes '
           'Paradox is the verso&rsquo;s central dispute, promised since folio 533a hung its '
           'stormclouds; the reader who has waited nine folios for it is thanked for her patience, '
           'which is thematic.</p>',
 'h1': 'Time',
 'hagahah': 'Time 1 tells you how the argument ends. Scholars with Time 1 argue anyway &mdash; the '
            'tractate&rsquo;s whole method, confessed in one rank. The Sphere&rsquo;s masters say '
            'the arguing is what the glimpsed ending is made of, and smile, and are insufferable, '
            'and are right.',
 'inner': '<p><span class="lemma">The current all patterns ride.</span> The jurisdiction test: '
          'Time owns sequence &mdash; not the thing, not the place, but the order and pace of its '
          'happening. Where a working shares ground with another Sphere, ask what changed: if the '
          'pattern stood whole and only its when moved &mdash; hastened, held, revisited &mdash; '
          'this ladder worked alone. The Sphere&rsquo;s deep claim, its seat&rsquo;s whole '
          'practice attests, is that the present is a convention of attention: the moment has '
          'neighbors, and discipline visits them.</p>\n'
          '        <p><span class="lemma">Hazily, farther by success.</span> The second '
          'rank&rsquo;s plain sense: sight along the stream is priced by distance in years &mdash; '
          'the verso&rsquo;s chart &mdash; and paid in clarity: near is legible, far is '
          'impression, and all of it is leaning, never ledger. The thickened walls are the '
          'counter-art: success cancels success, as 512b&rsquo;s spy-war and 519a&rsquo;s shields '
          '&mdash; the Book of Magick&rsquo;s three silent duels, all priced identically, which '
          'the tractate files as the drafters&rsquo; one confessed aesthetic.</p>\n'
          '        <p><span class="lemma">Her own moments multiplied.</span> The third '
          'rank&rsquo;s plain sense: two successes buy a deed, the deeds stack, and the working of '
          'magick stays rationed to one a turn &mdash; the law multiplies hands, never Spheres. '
          'The slowed target loses increments as the mage gains them; the small rewind takes back '
          'a breath per two successes; and all three read vulgar in exact proportion to their '
          'visibility, the impossible dodge being the census&rsquo;s favorite exhibit.</p>\n'
          '        <p><span class="lemma">Workings hung on triggers.</span> The fourth '
          'rank&rsquo;s plain sense, and 515b&rsquo;s hung bolt generalized: the effect completed '
          'at casting, its discharge deferred to the appointed hour or sign &mdash; the '
          'contingency as high art. The bubble is its defensive twin, the being or blast held '
          'outside the stream; the anchor is its navigational one, the buoy driven into now '
          'against the fifth rank&rsquo;s voyages; and the withdrawal &mdash; the mage stepping '
          'out of sequence entire &mdash; is the rank&rsquo;s quiet masterpiece and the '
          'setting&rsquo;s best alibi.</p>\n'
          '        <p><span class="lemma">The pressure includes her reading.</span> The observer '
          'clause, plainly, for it governs the whole ladder: the seer&rsquo;s glimpse is an event '
          'in the stream it glimpses &mdash; futures lean differently once read, the telling works '
          'upon the told, and 152b&rsquo;s doctrine is this folio&rsquo;s physics. The '
          'mechanics&rsquo; deep joke, which the seat&rsquo;s Tradition treats as scripture: '
          'Time&rsquo;s perception is never passive, and the only future safe from a seer is one '
          'she declines to visit.</p>\n'
          '        <p><span class="lemma">Felt as a fisherman feels wakes.</span> The first '
          'rank&rsquo;s counter-intelligence, plainly: time-work ripples, and the ripples run '
          '<span class="aside">both directions</span> &mdash; the sensitive feels the working that '
          'was, and sometimes the working that will be, building ahead like weather off the sea. '
          'The Sphere polices itself thereby: every trigger hung and bubble set is legible to the '
          'first rank of every rival, which is why the fourth rank&rsquo;s snares are laid '
          'sparingly and why two Time-workers in one city circle each other like duelists who have '
          'already read the ending and disagree about it.</p>\n'
          '        <p><span class="lemma">One working of magick a turn.</span> The ration&rsquo;s '
          'plain sense, and the ladder&rsquo;s load-bearing clause: multiplied moments multiply '
          'deeds, never castings &mdash; the blade swings thrice, the spell still comes once '
          '&mdash; and the clause is the only thing standing between the third rank and the '
          'artillery problem folio 512a buried. Its legalism is famous, its edge cases are the '
          'recensions&rsquo; longest footnotes, and the table that waives it has, the Later '
          'Authorities would say, repriced the whole Book in one generous mistake.</p>',
 'inner_head': 'The Ladder<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; sequence, pace, and snares</span>',
 'name': 'Time',
 'outer': '<p><span class="lemma">Whether that reading honors him.</span> The arithmetic defense '
          'of the seer, argued. <span class="voice">Some say</span> the Gemara&rsquo;s mechanics '
          'complete the acquittal: the court excused what conscience could not compel, the Burden '
          'weighed what ethics could not settle, and this folio shows the ledger &mdash; no rank '
          'he held could have carried the rescue at a price the world could pay, and a silence '
          'that arithmetic itself would have imposed needs no privilege at all. <span '
          'class="voice">Others say</span> the arithmetic defense is the most dangerous sentence '
          'in three folios: conscience excused by ledger is conscience retired, and every seer who '
          'reads this page will find her own silence pre-approved by mathematics she never '
          'checked. The master himself, they note, spent four centuries declining this exact '
          'absolution &mdash; the Burden&rsquo;s datum &mdash; and a tractate that hands it to him '
          'posthumously has overruled its own best witness. The tractate accepts the objection, '
          'prints both readings, and observes only that the ladder and the man have now each been '
          'used to excuse the other, which is how legends calcify, and why the folio faces him at '
          'all.</p>\n'
          '        <p><span class="lemma">A leaning, not a ledger.</span> The plot dispute, named '
          'honestly, for it is about the game: whose future does the seer see &mdash; the '
          'world&rsquo;s, or the Storyteller&rsquo;s? <span class="voice">Some say</span> the '
          'unwritten plot is the truth of the matter: futures glimpsed are drafts of a story still '
          'being told, and the leaning doctrine is the mechanics&rsquo; way of saying the author '
          'has not decided &mdash; prophecy in this game is a negotiation between the '
          'table&rsquo;s hopes, correctly priced. <span class="voice">Others say</span> the '
          'reduction insults both the Sphere and the craft: within the fiction the futures are '
          'real pressures, and the discipline of running them &mdash; promises kept, leanings '
          'honored, the shown thing binding the shower &mdash; is what separates prophecy from '
          'foreshadowing. The dispute is the one place the tractate&rsquo;s two audiences &mdash; '
          'the characters&rsquo; law and the players&rsquo; &mdash; read the same clause and mean '
          'different things, and the folio marks the seam deliberately: every table stands on it, '
          'and the ones that know it stand steadier.</p>\n'
          '        <p><span class="lemma">The small retcon.</span> The third rank&rsquo;s rewind, '
          'disputed at its edge before the verso takes the whole. <span class="voice">Some '
          'say</span> the breath rewound is mercy mechanics: the fumbled word unsaid, the wrong '
          'door unopened, two successes buying the smallest of second chances &mdash; and its '
          'modesty is the proof that the ladder&rsquo;s drafters understood their own medium. '
          '<span class="voice">Others say</span> modesty is the camel&rsquo;s nose: the breath and '
          'the betrayal differ in successes, not in kind, and a law that lets moments be '
          'unhappened has conceded the principle and is merely haggling &mdash; the verso&rsquo;s '
          'stacked prices are the haggling, written down. Both schools agree the clause is the '
          'chapter&rsquo;s strangest sentence: a rule of the game that edits the game&rsquo;s own '
          'record, law about the eraser, printed in pencil. <span class="kw">TEYKU</span> &mdash; '
          'and the teyku, uniquely, could be rewound, which is why it must stand. The seam&rsquo;s '
          'wisest occupants add a practice note: the table&rsquo;s prophecies should be rarer than '
          'its glimpses, and its glimpses rarer than its players wish &mdash; scarcity is the only '
          'difficulty modifier narrative authority respects.</p>',
 'outer_head': 'The Gradient<span class="comm-sub">the outer commentary &middot; three boundary '
               'disputes: the acquittal, the author, and the eraser</span>',
 'rubric': 'the Sphere of the flow, and its ladder',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the Sphere of Time &middot; the dot ladder as law, with its '
             'boundary disputes',
 'title': 'Tractate Aliyah · Folio 522a — Time: the Sphere of the flow',
 'type': 'daf'}
