# Folio 522b - The Rewind. Verso of the Time folio: the backward road's
# pricing and the Paradox question, per the wod-llm-wiki Time page
# (M20 pp.521-523, charts p.505).
FOLIO = {'bottom': '<p><span class="lemma">On running the rewind.</span> The retroactive working touches '
           'every player&rsquo;s agency at once, and the table law must precede the table&rsquo;s '
           'first use of it: what a rewind can revise (the Storyteller&rsquo;s world, freely), '
           'what it revises only by consent (another player&rsquo;s declared choices), and what it '
           'never revises (the table&rsquo;s own experience &mdash; everyone remembers the '
           'unhappened scene, which is the mechanic&rsquo;s strange gift: the game keeps what the '
           'world loses). Post it with 533a&rsquo;s standards and 519a&rsquo;s consent law; the '
           'three documents are one constitution.</p>\n'
           '        <p><span class="lemma">On the backward road as campaign.</span> True travel is '
           'not a spell but an expedition: always vulgar, stacked with Paradox by the law&rsquo;s '
           'own meter, imprecise as the chart provides, and haunted by the anchor problem &mdash; '
           'the mage who goes without one drifts, and the books&rsquo; own phrase for the failure '
           'mode is lost to history. Run it once a chronicle at most, as the setting does: the '
           'paired archmages of folio 520a are remembered because such workings are countable, and '
           'a table that rewinds weekly has spent the genre&rsquo;s rarest coin at the vending '
           'machine.</p>\n'
           '        <p><span class="lemma">On the trigger economy.</span> The fourth rank&rsquo;s '
           'snares are the practical estate: contingencies hung, bubbles set, anchors driven '
           '&mdash; and their bookkeeping is the drama, as 515b&rsquo;s hung bolt taught. Track '
           'what every player&rsquo;s mage has hanging, and when; the campaign&rsquo;s finest '
           'reversals live in triggers set three sessions early, and its finest horror in the '
           'enemy&rsquo;s, discovered one tick late.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on constitutions, expeditions, and '
                'what hangs</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The backward road is priced apart.</span> All travel against the '
           'flow is <span class="term">vulgar always</span> &mdash; no coincidence covers it, no '
           'standard of 533a excuses it &mdash; and it is harder than any working of its size, the '
           'law adding its own increment to every difficulty.<sup>a</sup> And its Paradox <span '
           'class="term">stacks</span>: each turn rewound lays another layer, each interval of the '
           'deep chart two, the debt compounding as the mage descends &mdash; the one working in '
           'the nine ladders whose price is written as multiplication.<sup>b</sup> Sight along the '
           'stream is priced by the chart&rsquo;s intervals: the year, the five, the twenty, the '
           'hundred, farther by success, perception only &mdash; the reach of the eye, never the '
           'hand.<sup>c</sup> The feats of the hand have their own ladder: the mage out of the '
           'stream, the companion carried, the room, the field, the event &mdash; successes '
           'mounting to the outlandish. And one clause governs the whole verso: <span '
           'class="term">what was rewound was still</span> &mdash; the law does not say the '
           'unhappened never happened; it says the stream flows over it, and the disputants hold '
           'what that grammar means.<sup>d</sup> And the anchor governs all deep travel: the buoy '
           'driven in the traveler&rsquo;s own now, without which the voyage drifts as the chart '
           'provides.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> And here the promised '
           'question: does the rewind unmake Paradox? A mage works vulgarly, the stormcloud of '
           '533a gathers, and she rewinds the working out of the world &mdash; no witnesses now, '
           'no working, no offense. Does the cloud disperse? <span class="voice">Come and '
           'hear</span> the law&rsquo;s own grammar: the rewind is itself vulgar always, itself '
           'stacked &mdash; the eraser is the loudest instrument in the drawer &mdash; so the mage '
           'has answered one offense with a greater, before any court rules on the first. And '
           'whether the first offense survives its own unhappening: the manuscripts hold both '
           'readings, and the tractate has hung the question since its first bound folio. The '
           'stormcloud, consulted, hangs; the disputants, opposite, begin; and the reader who '
           'wishes the tractate had opened with this page is reminded that it nearly did &mdash; '
           'folio 533a came first in the binding for exactly this reason, and the chapter now '
           'closes on the debt it opened with.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; verso of the Time folio, and the Sphere '
             'ladders&rsquo; last page: the chapter&rsquo;s remaining folios are wanting, and the '
             'wanting is the plan.',
 'folio': '522B',
 'glossL': '<p><span class="mark">a</span> On backward travel as always vulgar and harder by the '
           'law&rsquo;s own increment, see M20&rsquo;s Time entry, folios 521&ndash;523.</p>\n'
           '        <p><span class="mark">b</span> On Paradox stacking by the turn and by the '
           'interval, see the same entry; the multiplication is the text&rsquo;s, not the '
           'tractate&rsquo;s.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the timelines chart &mdash; the '
           'year to the millennium, perception only &mdash; and the feats ladder beside it, see '
           'the systems chapter&rsquo;s charts.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the grammar of the unhappened, '
           'the recensions speak carefully and the tractate follows them; the drafting is the '
           'dispute&rsquo;s whole terrain.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The stormcloud that hangs is folio 533a&rsquo;s, '
           'hung there since the tractate&rsquo;s first bound leaf; this verso is the promised '
           'weather report, and the promise&rsquo;s keeping across eleven folios is the '
           'Masoret&rsquo;s favorite proof that the binding has a spine.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The anchor of the fourth '
           'rank is the voyage&rsquo;s lifeline and 512b&rsquo;s connection law worked in the '
           'fourth dimension: the traveler reaches her own driven buoy as the seer reaches her '
           'beloved &mdash; by belonging. Lost to history is the chart&rsquo;s name for traveling '
           'unconnected.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The trigger, the bubble, and '
           'the hung working share 515b&rsquo;s teyku on when assessment falls; this verso&rsquo;s '
           'stacked pricing is the one case where the law answered: for the backward road, always, '
           'and in advance, and again.</p>',
 'h1': 'The Rewind',
 'hagahah': 'The one working priced as multiplication is the one that promises subtraction. The '
            'drafters of the law were not subtle people, and the tractate has stopped pretending '
            'they needed to be: some doors are labeled by what leans against them from the other '
            'side.',
 'inner': '<p><span class="lemma">Vulgar always.</span> The absolute&rsquo;s plain sense, and its '
          'loneliness: every other working in the nine ladders can, in some scene, pass as the '
          'world&rsquo;s own doing &mdash; the lucky miss, the found object, the plausible storm. '
          'The backward road has no such scene: the world holds no story in which yesterday '
          'un-happens, so no bystander, real or hypothetical, can bless it. The clause is '
          '533a&rsquo;s standards meeting the one case they cannot disagree about, which is why '
          'every table&rsquo;s vulgarity argument ends here, in rare and total peace.</p>\n'
          '        <p><span class="lemma">Written as multiplication.</span> The stacking&rsquo;s '
          'plain sense: the debt is per-turn and per-interval, laid in layers as the mage '
          'descends, and the arithmetic is the law&rsquo;s whole message &mdash; the deep past is '
          'not far, it is <span class="aside">expensive</span>, and the price curve was drawn by '
          'someone who wanted it read from across the room. The veterans&rsquo; rule of thumb: the '
          'rescue one turn back is a gamble; the rescue one scene back is a career; the rescue one '
          'year back is a myth, and myths are what the setting calls its cautionary '
          'vacancies.</p>\n'
          '        <p><span class="lemma">The eye, never the hand.</span> The charts&rsquo; '
          'division, plainly: the timelines ladder prices perception &mdash; the look along the '
          'stream, farther by success &mdash; and the feats ladder prices intervention, and the '
          'two are never confused in law however often in ambition. The seer at the hundred-year '
          'window is a scholar; the hand through it is a traveler, with the traveler&rsquo;s '
          'bills; and the gap between the ladders is where the Sphere keeps its sanity, and the '
          'Storyteller hers.</p>\n'
          '        <p><span class="lemma">The stream flows over it.</span> The grammar clause, '
          'plainly, before the disputants take it: the law describes the rewound moment as '
          'stilled, not erased &mdash; flowed over, the way a river reclaims a channel. What that '
          'preserves, and where, and legible to whom, the Mishnah declines to say; the '
          'drafting&rsquo;s care is itself the datum; and the first rank of this Sphere, note '
          'well, feels the ripples of time-workings &mdash; including, the manuscripts imply, the '
          'ones that no longer happened, which is either a mercy or the whole case, opposite.</p>\n'
          '        <p><span class="lemma">Without which the voyage drifts.</span> The anchor '
          'clause&rsquo;s plain sense: the backward road has no landmarks the traveler did not '
          'bring &mdash; the stream&rsquo;s far reaches are read hazily even by mastery, and the '
          'return leg is navigation toward a now that keeps moving. The fourth rank&rsquo;s anchor '
          'is the lifeline: driven before departure, reached for by belonging as 512b&rsquo;s '
          'connections reach, and the mage who travels unanchored joins the chart&rsquo;s tallest '
          'price tier, the one the books name <span class="aside">lost to history</span> and '
          'decline to elaborate, which the veterans read as kindness.</p>\n'
          '        <p><span class="lemma">Two layers per interval.</span> The deep chart&rsquo;s '
          'meter, plainly: past the turn-by-turn shallows, the debt is laid by the timelines '
          'chart&rsquo;s own rungs &mdash; the year, the five, the twenty &mdash; two layers a '
          'rung, compounding as the traveler descends. The arithmetic is readable at a glance and '
          'meant to be: the decade costs more than most masters have ever carried, the century is '
          'a number the recensions print without expecting customers, and the chart&rsquo;s '
          'deepest rungs exist, the veterans say, as the law&rsquo;s way of drawing the whole '
          'cliff so no one mistakes the fog for a floor.</p>',
 'inner_head': 'The Ladder, Continued<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; absolutes, arithmetic, and grammar</span>',
 'name': 'The Rewind',
 'outer': '<p><span class="lemma">Does the cloud disperse?</span> The promised dispute, at last. '
          '<span class="voice">Some say</span> yes, and the law&rsquo;s honesty requires it: '
          'Paradox is the world&rsquo;s answer to an offense, and an offense unhappened is '
          'unanswered &mdash; the stream flows over the working and the cloud above it both, and '
          'what remains is only the rewind&rsquo;s own fresh debt, stacked and vulgar as the '
          'Mishnah provides. The books&rsquo; own cloud-grammar &mdash; Paradox pools, discharges, '
          'or <span class="aside">hangs</span> &mdash; describes weather, and weather over a '
          'stilled channel rains elsewhere. <span class="voice">Others say</span> no, and the '
          'law&rsquo;s grammar requires that: the stilled moment is flowed over, not erased '
          '&mdash; the offense persists in whatever ledger the drafting so carefully declines to '
          'name, and the world&rsquo;s answer follows the offender, not the channel. On this '
          'reading the rewind launders nothing: it adds the eraser&rsquo;s debt to the '
          'original&rsquo;s, and the mages who report otherwise are alive to report because their '
          'experiments were small. The manuscripts hold both readings in suspension, the '
          'recensions decline across thirty years to resolve them, and the tractate&rsquo;s duty '
          'here is not to choose but to name what each reading makes of the world: in the first, '
          'reality is process, and justice a fact about the present; in the second, reality is '
          'record, and somewhere &mdash; the Record of 148a, the deep sectors of 164b, the still '
          'channels of this page &mdash; everything is kept. The chapter has been arguing archive '
          'against flow since its first Tradition; the Sphere of sequence was always going to host '
          'the final round.</p>\n'
          '        <p><span class="lemma">Lost to history.</span> The traveler&rsquo;s dispute, '
          'briefly, for the big one has taken the room. <span class="voice">Some say</span> the '
          'backward road, priced as it is, exists in law only as a deterrent: a rank written to be '
          'read and not ridden, the ladder&rsquo;s summit kept as a lighthouse. <span '
          'class="voice">Others say</span> the setting&rsquo;s own history falsifies the comfort: '
          'the roads were ridden &mdash; the paired archmages, the vanished masters, the '
          'time-locked realms the chronicles inherit as dungeons &mdash; and a deterrent that '
          'legends keep testing is a door, not a wall. Both schools tell their students the same '
          'sentence at the same rung, which the tractate therefore prints as the verso&rsquo;s '
          'practical ruling: the past is reachable, ruinously, and the reachable-ruinous is the '
          'setting&rsquo;s definition of temptation entire.</p>\n'
          '        <p><span class="lemma">Everything is kept.</span> The closing difficulty, and '
          'the chapter&rsquo;s: if the second school is right, the Book of Magick ends by agreeing '
          'with the book it is bound in &mdash; a tractate is a record arguing that records '
          'outlast their moments, and the Sphere of the flow closes the chapter by hanging the '
          'question of whether anything is ever truly unwritten. The tractate, being paper, '
          'declares its interest and recuses itself. <span class="kw">TEYKU</span> &mdash; let it '
          'stand; everything in this binding is a vote that it stands; and the reader holding the '
          'page has just joined the majority. And the majority, the Masoret adds, includes every '
          'recension yet printed, each of which chose to keep this page rather than rewind it.</p>',
 'outer_head': 'The Gradient, Continued<span class="comm-sub">the outer commentary &middot; three '
               'difficulties: the cloud, the road, and the record</span>',
 'rubric': 'the backward road, and its stacked price',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of Magick, '
             'continued &middot; of the rewind &middot; travel against the flow, and whether it '
             'unmakes Paradox',
 'title': 'Tractate Aliyah · Folio 522b — The Rewind: the backward road, and its stacked price',
 'type': 'daf'}
