# Folio content module - generated from the chat-era build, hand-editable.
FOLIO = {'bottom': '<p><span class="lemma">On what each standard buys.</span> Choosing a standard is '
           'choosing a genre, and the choice should be made with open eyes. Under <span '
           'class="voice">HOO</span>, magick is expensive everywhere and always: mages become '
           'misers of enlightenment, hoarding their Spheres for the hour of need, and the '
           'coincidental arts collapse into mere probability-nudging. Static reality is nearly '
           'total; the Technocracy has, in this sense, already won, and the chronicle&rsquo;s tone '
           'bends toward horror and scarcity &mdash; which some tables want, and should therefore '
           'choose knowingly. Under <span class="voice">HAB</span>, the coincidental toolkit '
           'flourishes, and play rewards narrative wit: the player who can dress an effect in a '
           'plausible story &mdash; the gas leak, the faulty wiring, the lucky ricochet &mdash; is '
           'playing the game the standard rewards. The tone is urban fantasy and conspiracy, the '
           'default register of the line. Under <span class="voice">HYP</span>, stealth and '
           'staging dominate: players empty rooms, case buildings, and engineer the absence of '
           'witnesses, and the chronicle drifts toward the heist. The table then inherits the '
           'camera problem, the drone problem, and the roommate-asleep-upstairs problem, and must '
           'legislate each; a standard adopted to simplify rulings ends by multiplying them.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Whatever the standard, declare it '
           'before the chronicle begins and keep it. Paradox is a pricing system, and pricing '
           'disciplines behavior only when prices are predictable: a mage who cannot guess what a '
           'working costs cannot be said to choose her risks. The ruling &mdash; vulgar or '
           'coincidental, witnessed or not &mdash; is the Consensus in miniature, spoken aloud '
           'before the roll, arguable then and never after.</p>\n'
           '        <p><span class="lemma">On drift.</span> The standard need not be eternal, only '
           'announced. A chronicle may migrate as the Ascension War tilts: a Technocratic '
           'ascendancy hardens HAB toward HOO, one incredulous camera at a time, while a rising '
           'Traditions arc softens it, and the players should be able to feel the border move. In '
           'this way the table&rsquo;s own rules become the story&rsquo;s barometer &mdash; which '
           'is, perhaps, the most Ascension-flavored ruling of all.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the consequences of each standard, '
                'and on procedure at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">Reality resists.</span> When a mage works her will upon the '
           'world, the world &mdash; which is to say the <span class="term">Consensus</span>, the '
           'sum of what humanity agrees is possible &mdash; pushes back against whatever it cannot '
           'accept. This backlash is called <span class="term">Paradox</span>.<sup>a</sup></p>\n'
           '        <p>An effect that could pass for chance or natural law is <span '
           'class="term">coincidental</span>: the gun jams, the taxi arrives, the fever breaks. '
           'Successful coincidental magick gathers no Paradox. An effect that visibly breaks the '
           'world&rsquo;s rules is <span class="term">vulgar</span>: fire from an open palm, a '
           'wound sealing itself, a man stepping through a mirror. Vulgar magick gathers Paradox '
           'whether or not it succeeds, reckoned by the highest Sphere employed, and gathers one '
           'more when Sleepers witness it.<sup>b</sup> A botch worsens every case.</p>\n'
           '        <p>Paradox pools, and discharges at once or hangs like a stormcloud. When it '
           'breaks, <span class="term">backlash</span> comes in rising severity: <span '
           'class="term">burn</span>, injury written on the body; <span class="term">flaws</span>, '
           'warps in the mage&rsquo;s pattern &mdash; she casts no shadow, milk sours at her '
           'touch; <span class="term">Quiet</span>, a private madness in which her broken reality '
           'becomes, for her, the only one; <span class="term">Paradox spirits</span>, beings of '
           'correction; and banishment to a <span class="term">Paradox realm</span> built from the '
           'shape of the offense.<sup>c</sup></p>\n'
           '        <p>What the Consensus holds possible is local.<sup>d</sup> A charm vulgar in a '
           'hospital may be coincidental at a midnight crossroads, and unremarkable within a Node '
           'or a Technocratic Construct. The Storyteller rules vulgar or coincidental, witnessed '
           'or not, before the dice are rolled.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> And here the '
           'disputation begins: the Mishnah does not say <em>by whose eyes</em> vulgarity is '
           'judged. The Bystander holds one imagined witness sufficient. The Omniscient Observer '
           'answers that the world itself watches. The Passerby standard counts only those '
           'actually present. Their arguments surround this text &mdash; as is only fitting.</p>',
 'chapter': 'Chapter the Fourth',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; teyku &mdash; let the camera question stand.',
 'folio': '533A',
 'glossL': '<p><span class="mark">a</span> On the Axis of Coincidence and the three standards, see '
           'M20, the Paradox discussion, folios 533&ndash;534 &mdash; whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On coincidental and vulgar generally: Revised '
           'ed. 137&ndash;138; 2nd ed. 160; 1st ed. 170&ndash;171, where the older, looser, '
           'result-facing reading prevails.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the forms of backlash &mdash; '
           'burn, flaw, Quiet, spirit, realm &mdash; see the systems chapter of any edition; the '
           'ladder rises with the size of the pool.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On local consensus &mdash; Nodes, '
           'Constructs, Horizon Realms &mdash; see the setting chapters; the bystander of the '
           'Mishnah is always a local.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The witness axis (HAB / HOO / HYP) is one of two. '
           'The other asks what is judged: <span class="mark">RBD</span>, result-based &mdash; '
           'only the outcome need be plausible &mdash; against <span class="mark">PBD</span>, '
           'process-based, where the mechanism itself must pass. The axes cross; every table lives '
           'in one of their cells.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> First edition leaned '
           'result-ward: bullets turned to air could pass as an unloaded gun. Later editions '
           'tightened toward process. The drift of editions is itself a drift of Consensus.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> On the mage as her own '
           'witness: her senses cannot be fooled about her own workings; the Avatar is the auditor '
           'within.</p>',
 'h1': 'Paradox',
 'hagahah': 'Some read HYP as &ldquo;Hypothetical,&rdquo; confusing it with the Bystander. The '
            'received reading is <em>Harass Yonder Passerby</em> &mdash; the joke standard that '
            'insists on playing itself straight, as jokes at gaming tables reliably do.',
 'inner': '<p><span class="lemma">Reality resists.</span> Not as a judge who deliberates, but as a '
          'pressure, the way water resists a hand. The Mishnah personifies for brevity; do not '
          'build a theology on it yet &mdash; the disputants opposite will do that for you.</p>\n'
          '        <p><span class="lemma">Which is to say the Consensus.</span> The sum of what '
          'Sleeping humanity agrees is possible. Note well: agrees, not observes. The agreement '
          'blankets the empty warehouse as surely as the crowded street; it is thinner in some '
          'places and hours, which is why the Mishnah later says <span '
          'class="aside">local</span>.</p>\n'
          '        <p><span class="lemma">Visibly breaks the world&rsquo;s rules.</span> Visibly '
          'to whom? To the <span class="voice">Hypothetical Average Bystander</span> &mdash; an '
          'imagined ordinary Sleeper of that time and place, conjured for the purpose of judgment '
          'and then dismissed. Set them at the mage&rsquo;s elbow in your mind. If they would '
          'mutter <span class="aside">lucky</span>, the effect is coincidental. If they would say '
          '<span class="aside">impossible</span>, it is vulgar &mdash; whether or not anyone '
          'actually stood there. The business card drawn from a pocket passes: cards live in '
          'pockets. The sniper rifle drawn from gym shorts does not: no garment ever concealed '
          'one, and the imagined witness knows it.</p>\n'
          '        <p><span class="lemma">Whether or not it succeeds.</span> Because the offense '
          'is the attempt, not the outcome. A failed impossibility is still an impossibility '
          'asserted against the world.</p>\n'
          '        <p><span class="lemma">One more when Sleepers witness it.</span> Here is the '
          'proof of the whole method. Actual witnesses do not <span class="aside">create</span> '
          'the offense; they raise its price. The offense exists the moment the hypothetical '
          'bystander would balk &mdash; hence the Mishnah can coherently speak of vulgar magick '
          '<span class="aside">without</span> witnesses, a category the standards opposite must '
          'labor to explain. Vulgarity is measured against the imagined observer; the surcharge, '
          'against the real one.</p>\n'
          '        <p><span class="lemma">Local.</span> The average bystander of a Delhi market '
          'shrine is not the average bystander of a Boston boardroom, and neither is the bystander '
          'of a Verbena farming village, before whom a healing posset may pass without remark. '
          'Inside a Node, a Chantry, a Construct, the local agreement is rewritten wholesale, and '
          'the imagined witness is rewritten with it.</p>\n'
          '        <p><span class="lemma">Before the dice are rolled.</span> The ruling is part of '
          'the price, and prices are quoted before purchase. A Storyteller who rules after the '
          'dice have fallen is not adjudicating but punishing. This is the plain sense of the '
          'Mishnah, and the peace of the table depends on it.</p>',
 'inner_head': 'The Bystander<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; the Hypothetical Average Bystander (HAB), default at most tables</span>',
 'name': 'Paradox',
 'outer': '<p><span class="lemma">Reality resists.</span> Grant it. But a resistance must be '
          'located somewhere &mdash; in the world, or in the witnesses, or in the space between. '
          'Everything below turns on where you put it.</p>\n'
          '        <p><span class="lemma">Visibly breaks the world&rsquo;s rules.</span> A '
          'difficulty: the Bystander&rsquo;s witness is a fiction, conjured and dismissed at the '
          'Storyteller&rsquo;s pleasure. Why should the world&rsquo;s law hang on an imaginary '
          'person?</p>\n'
          '        <p><span class="voice">Some say</span> the witness is not imaginary at all, but '
          'total: this is the standard of the <span class="voice">Hypothetical Omniscient '
          'Observer</span> (HOO). Reality is everywhere and observes everything; the universe '
          'itself keeps the books. The conjured business card is vulgar even though no living eye '
          'could tell it from a printed one, for the world <span class="aside">knows</span> no '
          'press ever printed it. Under HOO nearly all true magick is vulgar, and coincidence '
          'shrinks to those workings whose very process is mundane &mdash; the nudged probability, '
          'the well-timed word.</p>\n'
          '        <p>An objection: if the omniscient observer already sees all, why does the '
          'Mishnah add a point for witnesses? Are two watchers worse than one who watches '
          'everything? <span class="voice">Answer:</span> the world&rsquo;s vigilance sets the '
          'base price; a Sleeper&rsquo;s living disbelief sharpens it. The witness clause proves '
          'witnesses matter <span class="aside">more</span> &mdash; not that they alone '
          'matter.</p>\n'
          '        <p><span class="voice">And some say</span> the opposite: judge by the people '
          'actually present. This is the standard called <span class="voice">Harass Yonder '
          'Passerby</span> (HYP) &mdash; offered first as a joke, for its image of the mage '
          'polling the crowd, yet argued in earnest ever since. Consensus is enforced through '
          'Sleeping minds; where no such mind attends, who exactly is disbelieving? The fireball '
          'in the empty warehouse offends no one, for no one is there to be offended.</p>\n'
          '        <p>An objection: then the vulgar-without-witnesses clause is a dead letter, and '
          'every mage&rsquo;s first Sphere is scouting for empty rooms. <span class="voice">Some '
          'answer:</span> the mage herself is present, and her Avatar keeps honest books &mdash; '
          'she cannot un-know that she cheated. <span class="voice">Others answer:</span> '
          'unwitnessed vulgarity leaves evidence &mdash; scorched brick, a card with no printing '
          'history &mdash; and evidence is a witness deferred, collecting its point on a '
          'delay.</p>\n'
          '        <p>A further difficulty, on which HYP founders or is refined: what of the '
          'camera? A lens is no passerby; but the Sleeper who reviews the tape at midnight surely '
          'is. Does Paradox arrive retroactively, hours after the working, when the file is '
          'opened? And if the file is deleted unwatched &mdash; was the working ever vulgar at '
          'all? <span class="aside">The question stands.</span></p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; difficulties '
               'and dissents &middot; wherein HOO and HYP are raised against the Bystander</span>',
 'rubric': 'by whose eyes is vulgarity judged?',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter: The Vulgar and the Coincidental &middot; '
             'an out-of-character disputation on the Paradox rules of Mage: the Ascension, in the '
             'form of a daf',
 'title': 'Tractate Aliyah · Folio 533a — Paradox: a disputation on vulgarity in Mage: the '
          'Ascension',
 'type': 'daf'}
