# Folio content module - generated from the chat-era build, hand-editable.
FOLIO = {'bottom': '<p><span class="lemma">On monsters in the audience.</span> The ruling on the '
           'Night-Folk decides what kind of night the chronicle has. Count them as witnesses, and '
           'every crossover scene taxes the mage: she works guarded among vampires as among '
           'bankers, and the hidden world stays partitioned &mdash; each kind of monster a '
           'stranger to the rest. Discount them, and the hidden world becomes a backstage: mages '
           'work openly in Elysium, wonders trade freely in the night-markets, and the '
           'supernatural forms one society with the Consensus as its common enemy. Neither ruling '
           'is wrong; they are different genres wearing the same rulebook, and a troupe should '
           'choose the night it wants before the first crossover scene, not during it.</p>\n'
           '        <p><span class="lemma">On habituation.</span> Discounting consors and '
           'Sleepwalkers builds an incentive the table should see clearly: mages will collect '
           'entourages, and chantries will become bubbles of private consensus where the '
           'master&rsquo;s arts are ordinary weather. This is not an exploit &mdash; it is the '
           'Traditions in miniature, and arguably the whole theory of the mystery cult. But watch '
           'the drift: a table that lets familiarity erase witnesses altogether has quietly '
           'migrated to the Passerby standard of folio 533a, one trusted servant at a time.</p>\n'
           '        <p><span class="lemma">On the broadcast age.</span> Whatever is ruled for one '
           'lens scales to the saturated city. Count recordings and feeds as witnesses, and the '
           'surveilled downtown converges in practice on the Omniscient Observer &mdash; the '
           'standards of the previous folio collapse into one another at scale, and vulgar magick '
           'dies in public. Launder them, and the same downtown becomes the safest place on earth '
           'to throw fire, provided no unmediated eye is near. The two rulings produce opposite '
           'geographies of magick from identical camera counts; know which map your chronicle is '
           'drawing.</p>\n'
           '        <p><span class="lemma">On procedure.</span> Publish the census in session '
           'zero: a posted list &mdash; who counts fully, who at a discount, who not at all '
           '&mdash; beside the vulgarity standard already chosen. The players&rsquo; risk '
           'arithmetic depends on both, and the two rulings interlock: a strict witness census '
           'under a lenient vulgarity standard, or the reverse, each produces a playable game; '
           'strict upon strict produces the Technocracy&rsquo;s victory lap, and lenient upon '
           'lenient produces a superhero chronicle in a trench coat. Both are games someone wants; '
           'neither should arrive by accident.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the consequences of the census, '
                'and on procedure at the table</span>',
 'center': '<p class="noindent"><span class="dropcap">M</span><span class="kw">ISHNAH.</span> '
           '<span class="incipit">The Sleeper who witnesses</span> vulgar magick adds to its '
           'price.<sup>a</sup> Witness is presence with perception: one who sees, hears, or '
           'otherwise apprehends the working as it occurs. And the crowd does more than tax: where '
           'many Sleepers watch, static reality gathers force, and an effect may fray, falter, or '
           'come undone before their eyes.</p>\n'
           '        <p>The <span class="term">Awakened</span> are not Sleepers, and are never '
           'witnesses for the price. Of those between, the Mishnah names but does not measure: the '
           '<span class="term">Sleepwalker</span>, half-roused;<sup>b</sup> the <span '
           'class="term">consor</span> and the acolyte, companions of the wise; the <span '
           'class="term">Night-Folk</span>, who are themselves impossible;<sup>c</sup> the <span '
           'class="term">beast</span>, which perceives but does not agree; and the <span '
           'class="term">machine</span>, which records but neither perceives nor '
           'agrees.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Where does Sleep end? '
           'Four cases are brought before the court of this page: the leech, whose mind was human '
           'once; the half-roused, whose agreement hangs ajar; the multitude, who watch together; '
           'and the lens &mdash; held over from the previous folio, where the question was left '
           'standing. Their arguments surround this text, as before.</p>',
 'chapter': 'Chapter the Fourth &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan work in the '
             'form of a daf; no rules text is reproduced &middot; set in Abbess &amp; Goudy Old '
             'Style after the M20 interior &middot; continued from folio 533a, where the lens was '
             'left standing.',
 'folio': '533B',
 'glossL': '<p><span class="mark">a</span> On witnesses raising the price, and on Sleeper '
           'disbelief degrading a working, see the Paradox discussions of M20 and Revised.</p>\n'
           '        <p><span class="mark">b</span> On Sleepwalkers &mdash; the half-roused who '
           'serve chantries and carry Tass &mdash; see M20&rsquo;s companion material and the Book '
           'of Secrets.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the Night-Folk as neighbors and '
           'hazards, see the appendix of gods and monsters; on their own arts, the sibling '
           'tractates of this seder.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the lens: the question was '
           'raised overleaf, folio 533a, and left standing. This page takes it up.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The witness problem recurs across Seder Chashak: '
           'Tractate Masekha&rsquo;s breach, Tractate Acharit&rsquo;s Veil and its Delirium, '
           'Tractate Chalom&rsquo;s Banality. One law, refracted through four tractates.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Note the difference of '
           'jurisdiction: the Veil enforces itself upon the witness&rsquo;s mind; Paradox, upon '
           'the worker. The Delirium punishes seeing; Paradox punishes being seen.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Enlightened of the Union '
           'are no Sleepers, yet they command the Sleepers&rsquo; agreement as a weapon: '
           'procedures, protocols, and the evening news. Disbelief, industrialized.</p>',
 'h1': 'Witnesses',
 'hagahah': 'The dog sees the fireball and barks. The Consensus does not bark. But the neighbor '
            'who rises at two in the morning to see why the dog is barking is another matter '
            'entirely &mdash; the beast is no witness, yet it reliably summons them. Rule the '
            'animal out of the census and it will re-enter through the window.',
 'inner': '<p><span class="lemma">Presence with perception.</span> Two conditions, both required. '
          'The Sleeper asleep in the next room is present and perceives nothing: no witness. The '
          'one who hears the thunderclap of displaced air through the wall perceives and is, for '
          'that sense, present: a witness, though he saw nothing. Perception through any sense '
          'suffices; understanding is not required. He need not know it was magick &mdash; only '
          'apprehend the impossible thing itself.</p>\n'
          '        <p><span class="lemma">As it occurs.</span> Witness is contemporaneous: one who '
          'apprehends the working while it works. And one who apprehends only the aftermath '
          '&mdash; the scorch, the card that no press printed? No witness, says the plain sense, '
          'though perhaps an assessor of evidence; the deferred case belongs to the disputants '
          'opposite, who inherit it with the lens.</p>\n'
          '        <p><span class="lemma">The crowd does more than tax.</span> Numbers are not '
          'merely additive in the price. Where many watch, static reality is not a toll-keeper but '
          'a tide: a working before a crowd is not only costlier but harder, and may be impossible '
          'in the plain sense of the word. One eye raises the bill; a thousand raise the '
          'wall.</p>\n'
          '        <p><span class="lemma">Never witnesses for the price.</span> The rival mage may '
          'counter your working, unweave it, despise it &mdash; but her disbelief is her own, not '
          'the world&rsquo;s. She left the agreement when she Awakened; she cannot enforce a '
          'contract she no longer signs. The Enlightened of the Technocracy likewise: their '
          'disbelief arrives as procedures and amalgams, not as Paradox.</p>\n'
          '        <p><span class="lemma">The Sleepwalker, half-roused.</span> Touched by the '
          'supernatural and left ajar: the chantry servant, the hedge-witch&rsquo;s daughter, the '
          'man who carries Tass and does not ask. The common ruling discounts them &mdash; their '
          'agreement is already loose, and loose agreement exerts little force. But note the word: '
          'loose, not absent. The Census counts them at a fraction, and disputes the fraction '
          'below.</p>\n'
          '        <p><span class="lemma">Companions of the wise.</span> Habituation wears a '
          'groove. The consor who has watched a hundred workings holds a private consensus in '
          'which her mage&rsquo;s arts are simply how the world is. Most tables discount her as '
          'they discount the Sleepwalker. Prudence discounts; it does not erase.</p>\n'
          '        <p><span class="lemma">The beast.</span> Consensus is a human agreement. The '
          'dog perceives the fireball entirely and votes on nothing. No witness &mdash; but see '
          'the gloss below the page, for the beast has other offices.</p>\n'
          '        <p><span class="lemma">The machine.</span> The Census counts only minds, and so '
          'hands the lens across the page to the disputants, who have been waiting for it since '
          'the previous folio.</p>',
 'inner_head': 'The Census<span class="comm-sub">the inner commentary &middot; the plain sense '
               '&middot; who counts, category by category</span>',
 'name': 'Witnesses',
 'outer': '<p><span class="lemma">The Night-Folk, who are themselves impossible.</span> The great '
          'difficulty of this page. <span class="voice">Some say</span> the vampire counts as a '
          'witness: its mind was formed human, and human it dreams. It fears the sun because it '
          'half-believes the sun&rsquo;s verdict on it; it keeps to shadows because it has never '
          'stopped agreeing that things like itself should not be. A mind so anchored in the '
          'world&rsquo;s rules enforces them, fangs notwithstanding.</p>\n'
          '        <p><span class="voice">And some say</span> it cannot count: the impossible '
          'cannot testify for the possible. A walking contradiction of the Consensus is estopped '
          'from enforcing it &mdash; let the leech first explain its own existence to the court, '
          'and then it may object to yours.</p>\n'
          '        <p>An objection to the second view: then the mage in a room of monsters works '
          'freely, and the whole hidden world becomes a backstage where anything is permitted. '
          '<span class="voice">Answer:</span> so it is &mdash; and the elders of every night-court '
          'have always preferred it so. Whether the players&rsquo; chronicle prefers it is another '
          'matter; see below the page.</p>\n'
          '        <p>An objection to the first view: if the leech counts as a witness, why does '
          'the leech&rsquo;s own blood-sorcery pay no Paradox? Why should one who pays no tax '
          'collect it? <span class="voice">Answer:</span> Paradox is not a tax the witness '
          'collects but a debt the worker owes the world; the witness is merely the assessor, and '
          'an assessor need not be a taxpayer. The leech&rsquo;s arts are its own affair, tried in '
          'a sibling tractate.</p>\n'
          '        <p><span class="lemma">Half-roused.</span> Where exactly does the rousing '
          'begin? Consider the chain: a man sees one miracle and has rationalized it by morning '
          '&mdash; a full witness, surely, at the moment of witness. He sees a second, and begins '
          'to drink. He serves a chantry kitchen thirty years and hands the Hermetic her salt '
          'without comment. At which working did he stop counting? <span class="voice">Some '
          'say</span> the price follows disbelief, and disbelief is measured at the moment of '
          'witness, not by biography: count him fully until the day nothing in him objects. <span '
          'class="voice">Others say</span> biography is precisely what loosens the agreement, and '
          'the discount accrues like tenure. The first reading is cleaner; the second is truer; '
          'the table must pick its poison.</p>\n'
          '        <p><span class="lemma">The multitude.</span> Ten thousand watch the working '
          'live upon a stream. <span class="voice">Some say</span> each viewer is a witness, and '
          'the working is doomed before it finishes &mdash; static reality gathers with the crowd, '
          'and no Sphere outshouts ten thousand certainties. <span class="voice">Others say</span> '
          'the lens launders everything it carries: pixels attest nothing in the age of '
          'fabrication, and the Consensus itself has lately ruled that seeing footage is not '
          'believing. On this reading the modern age is, perversely, a gift to the vulgar '
          'willworker &mdash; the more cameras, the less any camera counts.</p>\n'
          '        <p><span class="lemma">The lens.</span> So the question held over from folio '
          '533a returns inverted. Once it was asked whether the camera makes every working '
          'witnessed; now it must be asked whether fabrication makes every witness a camera '
          '&mdash; trusting nothing it sees, enforcing nothing it doubts. Whether this frees the '
          'mage or starves the world of wonder, and whether those are different things &mdash; '
          '<span class="aside">the question stands.</span></p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; four '
               'difficulties: the leech, the half-roused, the multitude, and the lens</span>',
 'rubric': 'where does Sleep end?',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter: The Vulgar and the Coincidental, '
             'continued &middot; of witnesses &middot; an out-of-character disputation on the '
             'Paradox rules of Mage: the Ascension',
 'title': 'Tractate Aliyah · Folio 533b — Witnesses: where does Sleep end?',
 'type': 'daf'}
