# Folio 554b - The Three Faces. Verso of Quiet: denial, madness, and
# morbidity, with the elder girsa and the inner countries, per the
# wod-llm-wiki quiet page (M20 pp.556-559; Masters of the Art pp.75-76).
FOLIO = {'bottom': '<p><span class="lemma">On casting the face.</span> The face a Quiet wears '
           'follows the choices made while sane, and the Storyteller should read the '
           'sheet before choosing: the denier&rsquo;s Quiet grows from what the '
           'character already refuses to see, the morbid one&rsquo;s from what she '
           'already lingers on, and the mad one&rsquo;s from the pressures already '
           'cracking her. A Quiet assigned at random is a penalty; a Quiet grown '
           'from the character is the chronicle&rsquo;s best mirror, and the player '
           'will recognize it with a chill that no random table buys.</p>\n'
           '        <p><span class="lemma">On the hobgoblin&rsquo;s casting.</span> '
           'Give the hobgoblin a portfolio, not a jump-scare: it embodies what the '
           'mage denies, lasts a day per dot of her enlightenment, and works best '
           'as a recurring character with an agenda &mdash; the paint-smear that '
           'is always nearer the door, the twin who answers her mail. The '
           'moment it speaks something true that the mage has refused to say, the '
           'device has done its work, and not before.</p>\n'
           '        <p><span class="lemma">On running the mindscape.</span> The '
           'sealed country is a bottle episode by law &mdash; the body catatonic, '
           'the clock in days per point of the fee, or weeks past ten, the allies entering by the '
           'dreamer&rsquo;s arts &mdash; and its exit is the folio&rsquo;s one '
           'guaranteed reward: emergence clears the pool entire. Build the '
           'mindscape from the character&rsquo;s own materials, let the rescue '
           'party learn her from the inside, and spend the clearing as the '
           'fresh start it is; the law put a prize at the bottom of the pit on '
           'purpose.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on mirrors, twins, and '
                'the bottom of the pit</span>',
 'center': '<p class="noindent"><span class="dropcap">Q</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The Quiet wears three faces,</span> and each is the '
           'mage&rsquo;s own, magnified. <span class="term">Denial</span> shuts out '
           'what she will not accept, and what is repressed is expressed: from '
           'stubborn refusal, through blindness and deafness to the refused thing, '
           'to the reshaping of the world around her so that the denied ceases '
           'locally to exist.<sup>a</sup> <span class="term">Madness</span> is the '
           'commonest face: moods and visions rising from quirk to a dementia '
           'others begin to share, to wildness or the stillness past it. And <span '
           'class="term">Morbidity</span> is the soul-sickness that turns toward '
           'death: from provocation, through cruelty grown casual, to the thing '
           'that hunts &mdash; the face that ends among the Fallen.<sup>b</sup> '
           'The elder manuscripts name the faces otherwise &mdash; Clarity for the '
           'over-ordered world, Jhor for the death-taint, Madness for the excess '
           'of the Dynamic &mdash; and rule that Madness and Clarity met in one '
           'mage cancel toward balance, while Jhor met with anything '
           'dominates.<sup>c</sup> The Quiet also keeps countries: the <span '
           'class="term">hobgoblin</span>, the denial walking, a day per dot of '
           'enlightenment; the warped weather of the deep grades, landscape and '
           'bystanders alike bent toward the sufferer&rsquo;s dream; and the <span '
           'class="term">mindscape</span>, the sealed inner world entered by will '
           'or by misfortune, one day within for every point of the fee &mdash; a '
           'week per point once the pool passes ten &mdash; the body quiet as '
           'the name, and emergence clearing the pool '
           'entire.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Why '
           'three faces and not one madness? Come and hear the taxonomy&rsquo;s '
           'logic: the Quiet is the mage&rsquo;s own will turned inward, so it '
           'inherits her will&rsquo;s posture toward the world. The one who met '
           'reality by refusing it denies harder; the one who met it by dancing '
           'faster dances into dementia; the one who met it by studying its '
           'endings is studied by them in turn. The faces are not diseases '
           'caught but stances compounded &mdash; which is why the elder '
           'ruling fears Jhor above the others: refusal and frenzy are '
           'postures toward life, and the death-taint is a posture toward the '
           'thing that needs no help winning. The disputants around this text '
           'hold the girsa&rsquo;s politics and the taxonomy&rsquo;s missing '
           'subject.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Quiet: the recto keeps the law of the break, this side '
             'keeps its faces and its countries.',
 'folio': '554B',
 'glossL': '<p><span class="mark">a</span> On Denial &mdash; miscalled Clarity in '
           'one recension, as the books themselves note &mdash; and its ladder '
           'from refusal to local reshaping, see M20, the Book of Magick, folios '
           '556&ndash;559.</p>\n'
           '        <p><span class="mark">b</span> On Madness and on Morbidity '
           '&mdash; the latter called Jhor in the revised recension, a '
           'soul-sickness distinct from the death Resonance &mdash; see the same '
           'folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the elder '
           'triad &mdash; Clarity, Jhor, Madness &mdash; the cancellation and '
           'dominance rulings, the five-level removal counsel, and the archmage '
           'warning, see Masters of the Art, folios 75&ndash;76 of that '
           'volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On hobgoblins, '
           'environmental alteration, and mindscapes with their entries, '
           'clocks, and clearing exit, see M20, folios 556&ndash;559; the '
           'dreamwalking arts that reach a sealed friend are Mind&rsquo;s, '
           'folio 519a.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Jhor is 156b&rsquo;s whole '
           'subject worn as a face: the watchers&rsquo; seat built its '
           'discipline against exactly this taint, and the elder ruling that '
           'Jhor dominates any pairing is the mechanical form of that '
           'folio&rsquo;s warning. The correspondence between the two pages is '
           'the Masoret&rsquo;s favorite in the binding.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> '
           'Clarity as the elder name for the over-ordered Quiet &mdash; a '
           'Technocratic affliction, the manuscript says &mdash; is chapter '
           'VI&rsquo;s business, folio 168 onward: the Union&rsquo;s folios '
           'carry the question of whether perfect order is their doctrine '
           'or their diagnosis.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'mindscape&rsquo;s clearing exit is the setting&rsquo;s strangest '
           'mercy: the pool paid in full by a journey nobody chooses. The '
           'Seeking it resembles is folio 43&rsquo;s, and the '
           'resemblance is the recto&rsquo;s third dispute wearing '
           'travel clothes.</p>',
 'h1': 'The Three Faces',
 'hagahah': 'In the Tarot the books deal for it, Quiet is The Moon: a hall of '
            'mirrors with one true exit, and the exit is also a mirror. The '
            'ones who return say you leave by the reflection that shows you '
            'something you denied, which is why nobody leaves quickly.',
 'inner': '<p><span class="lemma">What is repressed is expressed.</span> '
          'Denial&rsquo;s plain sense, and its signature paradox: the denier '
          'acts out the very thing he shuts away, so the face is legible to '
          'everyone but its wearer &mdash; the colleague who cannot say the '
          'dead friend&rsquo;s name and sets three places at table. At the '
          'deep grades the denial stops being behavior and becomes '
          'geography: the refused thing vanishes from the local world, '
          'which is the mechanism behind the warps that trail the Mad, and '
          'the reason the face&rsquo;s elder name &mdash; Clarity &mdash; '
          'was always half a compliment and wholly a warning.</p>\n'
          '        <p><span class="lemma">A dementia others begin to '
          'share.</span> Madness&rsquo;s plain sense: the common face '
          'escalates by leaking &mdash; the private quirk, then the visions, '
          'then the strangeness that bystanders start to perceive &mdash; '
          'and the sharing is the diagnostic line: a delusion that recruits '
          'witnesses has stopped being psychology and become a small rogue '
          'consensus &mdash; the books&rsquo; quiet horror being that belief, '
          'even broken belief, recruits.The face&rsquo;s far end forks &mdash; wildness or '
          'stillness &mdash; and the fork is the recto&rsquo;s sixth grade '
          'seen from inside: the will burning outward, or sealing the '
          'doors.</p>\n'
          '        <p><span class="lemma">The face that ends among the '
          'Fallen.</span> Morbidity&rsquo;s plain sense, stated with the '
          'books&rsquo; own gravity: the death-turned Quiet escalates from '
          'provocation through casual cruelty to predation, and its terminus '
          'is not the asylum but the Nephandi &mdash; the one face whose '
          'deep grades are less a prison than a recruitment. The '
          'distinction the gloss preserves matters: this is soul-sickness, '
          'not the death Resonance, and the honest scholar of endings '
          '&mdash; 156a&rsquo;s whole seat &mdash; is not morbid but '
          'exactly what morbidity counterfeits.</p>\n'
          '        <p><span class="lemma">Cancel toward balance; Jhor '
          'dominates.</span> The elder girsa&rsquo;s plain sense: the '
          'manuscript treats the faces as humours that mix &mdash; order '
          'and frenzy neutralizing toward a strange sanity, the death-taint '
          'corrupting every mixture it enters &mdash; and appends the '
          'counsel that five levels of any face removes the character from '
          'play, and that the old, isolated, and mighty are prone to all '
          'three. The tractate files the girsa unharmonized per its law, '
          'and notes that both recensions agree on the asymmetry: two of '
          'the faces are exaggerations of life, and one is a door.</p>\n'
          '        <p><span class="lemma">A day within per point of the '
          'fee.</span> The mindscape&rsquo;s plain sense: the sealed '
          'country runs on the pool&rsquo;s own clock &mdash; days per '
          'point while the pool is shallow, weeks per point once it '
          'passes ten, so the deep countries are long by design and the '
          'law means them to be &mdash; entered by '
          'misfortune or &mdash; the strange clause &mdash; on purpose, by '
          'meditation against a wall of the grade and three; the sufferer may signal '
          'out by will, the ally may walk in by the dreaming arts, and '
          'the harm within bruises only. The exit&rsquo;s full clearing of '
          'the pool is the design&rsquo;s deliberate prize, and the '
          'voluntary entry is its most audacious implication: the '
          'mindscape is also a treatment, for those with the nerve to '
          'check in.</p>',
 'inner_head': 'On the Faces<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; face by face, country by '
               'country</span>',
 'name': 'The Three Faces',
 'outer': '<p><span class="lemma">The girsa&rsquo;s politics.</span> The naming '
          'dispute, for the names are accusations. The elder manuscript calls '
          'the ordered face Clarity and hangs it on the Union; the revised '
          'recension miscalled Denial by that same name, as the modern text '
          'notes with a librarian&rsquo;s sigh; and Jhor arrived from the '
          'death-scholars&rsquo; own vocabulary, borrowed to name their '
          'corruption. <span class="voice">Some say</span> the drift is mere '
          'manuscript weather, the kind this binding files nine times a '
          'chapter. <span class="voice">Others say</span> the names were '
          'always weapons: to call the Technocrat&rsquo;s temperament a form '
          'of madness is the Traditions&rsquo; whole polemic in one word, to '
          'name the corruption after the death-seat&rsquo;s own term for it '
          'is to make that seat carry the stigma of its counterfeit, and '
          'the tractate&rsquo;s standing rule &mdash; keep the variants, '
          'for the roughness is data &mdash; here reads as: keep the '
          'evidence. The schools agree the modern text chose its names to '
          'disarm the old accusations, and disagree, comfortably, about '
          'whether it succeeded.</p>\n'
          '        <p><span class="lemma">The taxonomy&rsquo;s missing '
          'subject.</span> The second difficulty, and the sharpest: three '
          'faces, and none of them is the Quiet that sees truly. The '
          'wisdom-from-madness clause is printed on the recto; the '
          'teaching reading has its school; and yet the taxonomy offers no '
          'face for the break that turns out to have been a window. <span '
          'class="voice">Some say</span> rightly so: a madness with a '
          'truth-face would romance exactly what the folio&rsquo;s care '
          'counsel guards against, and the wisdom clause is deliberately '
          'an outcome, never a kind. <span class="voice">Others say</span> '
          'the omission is the setting flinching from its own premise: a '
          'cosmos where consensus manufactures reality has no principled '
          'way to declare any private world false &mdash; only outvoted '
          '&mdash; and the missing fourth face is missing because naming '
          'it would collapse the distinction between the Mad and the '
          'Ascended that every faction&rsquo;s legitimacy requires. The '
          'first school keeps the table safe; the second keeps the '
          'question honest; and folio 234, wanting, inherits both, as '
          'the Masoret has already warned it.</p>\n'
          '        <p><span class="lemma">Stances compounded.</span> A last '
          'difficulty, pastoral. If the faces grow from the mage&rsquo;s '
          'own postures, then every mage carries her Quiet&rsquo;s seed in '
          'her method &mdash; the refuser her Denial, the dancer her '
          'Dementia, the scholar of endings her Jhor. <span '
          'class="voice">Some say</span> the implication is the '
          'folio&rsquo;s real teaching: know your seed, and the '
          'watchers&rsquo; discipline of 156b generalizes to every seat '
          '&mdash; each Tradition owes its members a watch calibrated to '
          'its own temptation. <span class="voice">Others say</span> the '
          'teaching curdles fast: a community that reads every '
          'colleague&rsquo;s method as incipient pathology has built the '
          'paranoia it feared, and the setting&rsquo;s history of '
          'inquisitions &mdash; chapter VII&rsquo;s, wanting &mdash; began '
          'each time with exactly this syllogism. The tractate answers '
          'from the recto&rsquo;s hagahah: the sane sublet &mdash; and '
          'subletting means neighbors, and neighbors mean both the watch '
          'and its abuse, and the folio declines to promise the one '
          'without the other. <span class="kw">TEYKU</span> &mdash; watch, '
          'and be watched kindly.</p>',
 'outer_head': 'The Alienists<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the names, the fourth face, and the '
               'seed</span>',
 'rubric': 'denial, madness, morbidity, and the inner countries',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of the three faces &middot; the kinds of '
             'Quiet as law',
 'title': 'Tractate Aliyah · Folio 554b — The Three Faces: the kinds of Quiet',
 'type': 'daf'}
