# Folio 554a - Quiet. The madness of mages, per the wod-llm-wiki quiet
# page (M20 pp.51, 554-559).
FOLIO = {'bottom': '<p><span class="lemma">On taking the voice.</span> Quiet is the one law in '
           'this binding under which the Storyteller may narrate a player&rsquo;s own '
           'senses to her falsely, and the license is radioactive: declare it in '
           'session zero, per 384b, as its own line item &mdash; when Quiet takes '
           'hold, what the character perceives is mine to describe and yours to '
           'believe &mdash; and agree the signals by which the player may distinguish '
           'table from mindscape when it matters. The consent gathered in advance is '
           'what makes the gaslight a genre instead of an offense.</p>\n'
           '        <p><span class="lemma">On keeping the player playing.</span> The '
           'deepest error is benching: the mage in Quiet is not removed from play '
           '&mdash; she is playing a different game whose board only she can see, '
           'and the craft is giving her real choices inside the delusion while the '
           'cabal plays the outside. Run the two boards in parallel and cut between '
           'them; the scene where the table realizes both boards describe the same '
           'room is the folio&rsquo;s whole payoff.</p>\n'
           '        <p><span class="lemma">On real madness at the table.</span> The '
           'books themselves counsel care: Quiet is metaphysics wearing '
           'madness&rsquo;s clothes, not a portrait of mental illness, and the '
           'distinction should be said aloud where the table needs it said. The '
           'lines and veils of 384b govern here with full force, and the player '
           'for whom this folio&rsquo;s territory is not fiction is owed the fade, '
           'immediately and without discussion, as always.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the voice, the two '
                'boards, and care</span>',
 'center': '<p class="noindent"><span class="dropcap">Q</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The break that turns inward is called Quiet.</span> '
           'Where the court of 533a fines the world or the body, Quiet collects from '
           'the mind: the will flips inside out and walls the mage into a reality of '
           'her own manufacture, and while she is within it she is suspended from '
           'her Path.<sup>a</sup> It enters by the fee accumulated, by the great '
           'backlash of ten and more discharged at once, and by trauma &mdash; the '
           'mind&rsquo;s wounds, the breaking of the self &mdash; resisted by will '
           'or by body against a wall of the standing fee itself.<sup>b</sup> Its '
           'depth tracks the fee in six grades: the quirk, the drift, the delusion, '
           'the senses backfiring, the mindscape or the menace, and past twenty the '
           'catatonia from which some go Mad outright and do not return.<sup>c</sup> '
           'The mage who knows her state may stand still a turn, spend a point of '
           'will, and roll it for three successes and no fewer: the full count '
           'asserts sanity for the scene and forgives a point of the fee; the '
           'partial count deepens the dream; the botch gives the dream a body. And '
           'the cure is long &mdash; will and time, or an ally&rsquo;s deep working '
           'of Mind and Prime, paying double or treble essence for every point '
           'forgiven &mdash; and the books command that it not be easy.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD of the descent from inside, for the outside tells '
           'nothing. First the world is merely wrong in small ways &mdash; a door '
           'that was always on the other wall, a friend&rsquo;s name that tastes '
           'misspelled &mdash; and the mage, being a professional, corrects it. '
           'The corrections hold. That is the trap: within the Quiet her will '
           'works perfectly, every fix fixes, every proof proves, and the world '
           'agrees with her more completely than the true one ever did. By the '
           'fourth grade the agreement is total and the disagreement is other '
           'people, who have begun to flicker. She does not experience madness; '
           'she experiences everyone else&rsquo;s. The teachers ended the telling '
           'there, saying only that the sixth grade is quiet in the plain sense, '
           'and that the ones who return describe a door, never the same door '
           'twice. The disputants around this text hold what the state is '
           '&mdash; sentence, symptom, or teaching &mdash; and who else it can '
           'catch.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'faces of the Quiet and its inner countries wait overleaf.',
 'folio': '554A',
 'glossL': '<p><span class="mark">a</span> On Quiet as reality overload, the will '
           'turned inward, and the suspension from the Path, see M20, folio 51 and '
           'the Book of Magick, folios 554&ndash;559, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On the doors in &mdash; the '
           'accumulated pool, the ten-point backlash, and trauma with its '
           'resisting rolls &mdash; see folio 555.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the six grades '
           'tracking the standing pool, see the same folio&rsquo;s chart, '
           'abridged here to its bands per the luachs&rsquo; standing rule.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'assertion of sanity, its all-or-nothing count, the hobgoblin of the '
           'botch, and the ally&rsquo;s costly cure, see folios '
           '555&ndash;556.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Quiet is 533a&rsquo;s fourth form '
           'of payment, and the court&rsquo;s cruelest: the fine that fines the '
           'judge. The backlash that overflows ten points arrives here, and the '
           'Masoret routes the reader accordingly.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The Mad who '
           'never return are folio 234&rsquo;s &mdash; the walking '
           'Quiets whose weather follows them &mdash; and the wild talent that '
           'ends there is 527&rsquo;s optional storm; this folio keeps the doorway and that one keeps the country.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'watchers of 156b posted the discipline this folio assumes: the '
           'colleague who tracks a friend&rsquo;s drift and says so early. '
           'Their seat&rsquo;s jhor is the third face overleaf, and the two '
           'folios have been corresponding since chapter V.</p>',
 'h1': 'Quiet',
 'hagahah': 'The difference between a paradigm and a Quiet is other people. Every '
            'mage lives in a reality of her own manufacture; the sane ones '
            'sublet.',
 'inner': '<p><span class="lemma">Suspended from her Path.</span> The '
          'suspension&rsquo;s plain sense: Quiet is not a detour on the road to '
          'Ascension but a stoppage of it &mdash; the mage within is not '
          'progressing, not Seeking in the sanctioned sense, not accumulating '
          'anything but depth. The clause matters at the table as a clock: '
          'however rich the mindscape, the character&rsquo;s story outside it '
          'is frozen, and the cabal&rsquo;s urgency to retrieve her is the '
          'urgency the law intends.</p>\n'
          '        <p><span class="lemma">Against a wall of the fee '
          'itself.</span> The trauma clause&rsquo;s plain sense, and its '
          'elegant cruelty: the roll to hold off Quiet is walled by the '
          'standing Paradox pool, so the mage most burdened is the mage least '
          'able to refuse &mdash; the debt itself weakens the door. Will '
          'answers the mind&rsquo;s wounds and Stamina the body&rsquo;s, per '
          'the health law&rsquo;s own division, and the mage who manages her '
          'pool like a portfolio is not being cowardly; she is reading this '
          'clause correctly.</p>\n'
          '        <p><span class="lemma">Ten and more discharged at once.</span> '
          'The overflow door&rsquo;s plain sense: the backlash large enough '
          'spends its violence on the mind whatever the bookkeeping says '
          '&mdash; the court&rsquo;s sentence arriving as concussion &mdash; '
          'and the clause is why the elders fear the great discharge more than '
          'the great pool. A pool is a mortgage, renegotiable, watched; ten '
          'points in one blast is a verdict delivered at the door, and the '
          'mage it finds standing is not consulted about the grade she wakes '
          'in.</p>\n'
          '        <p><span class="lemma">Six grades.</span> The chart&rsquo;s '
          'plain sense, banded: the shallow grades are texture &mdash; quirks, '
          'drift, the delusion politely held &mdash; the middle grades leak, '
          'the senses backfiring and the strangeness becoming visible to '
          'others, and the deep grades are countries: the sealed mindscape, '
          'the walking menace, the catatonia. The tracking of grade to pool '
          'makes Quiet legible at the table in a way madness never is in '
          'life, which is the design being kind to Storytellers and honest '
          'about being a game in the same stroke.</p>\n'
          '        <p><span class="lemma">Three successes and no fewer.</span> '
          'The assertion&rsquo;s plain sense: sanity is all-or-nothing by '
          'law &mdash; the full count buys a scene of clarity and forgives a '
          'point, the partial count is worse than nothing, deepening the '
          'dream it failed to break, and the botch incarnates the denial as '
          'a hobgoblin with the mage&rsquo;s own address. The all-or-nothing '
          'is the folio&rsquo;s sharpest piece of psychology: half-fighting '
          'a delusion feeds it, which every table knows from arguments and '
          'the drafters knew from somewhere. And the turn of stillness the '
          'law demands first is not flavor: the assertion begins with the '
          'mage doing nothing &mdash; one full turn of not correcting the '
          'world &mdash; which is, within a Quiet, the single hardest '
          'working she knows.</p>\n'
          '        <p><span class="lemma">That it not be easy.</span> The '
          'cure clause&rsquo;s plain sense, with the books&rsquo; own '
          'emphasis kept: the way out is will and roleplay across real '
          'sessions, or an ally&rsquo;s extended working of the fourth ranks '
          'of Mind and Prime, each point of the fee bought out with two or '
          'three of the healer&rsquo;s own essence &mdash; a transfusion, '
          'priced like one. The command against ease is doctrine, not '
          'difficulty tuning: a Quiet cured in a scene teaches the table '
          'that minds are equipment, and everything this folio guards '
          'depends on the table believing otherwise.</p>',
 'inner_head': 'On the Inward Court<span class="comm-sub">the inner commentary '
               '&middot; the plain sense &middot; doors, grades, and the '
               'price of return</span>',
 'name': 'Quiet',
 'outer': '<p><span class="lemma">Sentence, symptom, or teaching.</span> The '
          'triple reading, as the brief demands. <span class="voice">Some '
          'say</span> sentence: Quiet is the court&rsquo;s inward arm, '
          'punishment scaled to the pool like every other fee, and reading '
          'meaning into it flatters a penalty. <span class="voice">Others '
          'say</span> symptom: the books themselves call it reality overload '
          '&mdash; the mind buckling under contradiction as bodies buckle '
          'under blows &mdash; no more a judgment than a fever, and the '
          'proper response is nursing, not theology. <span class="voice">And '
          'some say</span> teaching: the state is a monumental involuntary '
          'Seeking, the wisdom-from-madness clause is printed law &mdash; the '
          'survivor may emerge with her issues resolved, her Nature '
          'changed, her lore deepened, her pool cleared &mdash; and a '
          'punishment that graduates its victims wiser is either a very '
          'strange punishment or not one at all. The three schools have '
          'held these positions since the elder manuscripts, the Avatar&rsquo;s '
          'own folio, 43, is claimed as authority by all three, '
          'and the tractate notes only what the text guarantees: the '
          'teaching reading is sometimes true and never promised, which is '
          'the exact shape of every mercy in this binding.</p>\n'
          '        <p><span class="lemma">Who else it can catch.</span> The '
          'contagion dispute. The deep Quiet leaks &mdash; hobgoblins '
          'visible to bystanders, weather bending around the sufferer, the '
          'elder testimony of one mage&rsquo;s permanent Quiet dragging '
          'three colleagues down &mdash; and the Mad walk in bubbles of it '
          'for life. <span class="voice">Some say</span> the leakage is '
          'metaphor made mechanics: madness has always been social, the '
          'folie &agrave; deux is older than the Order, and the rules '
          'merely price what asylums documented. <span class="voice">Others '
          'say</span> the leakage is the setting&rsquo;s deepest warning '
          'about its own premise: if reality is consensus, then a '
          'sufficiently committed private reality is not a retreat from '
          'the war but a combatant in it, and the line between a deep '
          'Quiet and a small successful Ascension is thinner than any '
          'Tradition preaches. The first school comforts; the second is '
          'why folio 234 exists; and the shared-descent testimony is '
          'filed by both, with different shudders. The practical law both '
          'schools keep is the same: the deep Quiet is treated as an area '
          'effect, and the cabal plans a rescue the way it would plan entry '
          'to a hostile realm, for that is what it is.</p>\n'
          '        <p><span class="lemma">Her will works perfectly.</span> '
          'The last difficulty, the Gemara&rsquo;s own: inside the Quiet, '
          'the mage&rsquo;s corrections hold &mdash; the private world '
          'obeys her as the Consensus never has. <span class="voice">Some '
          'say</span> this is the trap described and nothing more: the '
          'obedient world is the tell, and the teaching folios should '
          'drill every apprentice to test for it. <span '
          'class="voice">Others say</span> attend to what the trap '
          'implies: the thing every mage is promised at the '
          'mountain&rsquo;s top &mdash; a world that answers will without '
          'resistance &mdash; is the thing the Quiet counterfeits at the '
          'mountain&rsquo;s bottom, and the counterfeit is '
          'indistinguishable from inside. The dispute is the '
          'setting&rsquo;s whole soteriology held to a mirror, and the '
          'tractate, having promised honest teykus, files its most honest: '
          'no test distinguishes the summit from the pit that is '
          'administered from within either. <span class="kw">TEYKU</span> '
          '&mdash; which is why the sane sublet.</p>',
 'outer_head': 'The Alienists<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the reading, the contagion, and the '
               'mirror</span>',
 'rubric': 'the break inward, and its grades',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of Quiet &middot; the madness of mages as '
             'law',
 'title': 'Tractate Aliyah · Folio 554a — Quiet: the break inward, and its grades',
 'type': 'daf'}
