# Folio 567a - Focus: Belief. First of the focus trio, per the wod-llm-wiki
# focus and paradigms pages (M20 pp.61, 371-372, 567-571; BoS pp.167-196).
FOLIO = {'bottom': '<p><span class="lemma">On the paradigm interview.</span> Session zero should '
           'ask every player the Gemara&rsquo;s question in advance: why does your '
           'magick work? Not which Spheres &mdash; why. A sentence suffices, posted '
           'with 384b&rsquo;s constitution, and every vulgarity call, every '
           'instrument ruling, every refusal this folio licenses becomes a reading '
           'of that sentence instead of an ambush. The lens is the character sheet&rsquo;s '
           'most load-bearing line and the only one with no box printed for it.</p>\n'
           '        <p><span class="lemma">On refusing without bullying.</span> The '
           'Storyteller&rsquo;s veto &mdash; that working does not fit your belief '
           '&mdash; is a genre tool, not a leash, and it should arrive the way good '
           'genre does: predictably. Telegraph the lens&rsquo;s edges early, refuse '
           'at the edges and not in the heart, and let the refusal cost the table a '
           'scene of invention rather than a scene of sulking. A veto that surprises '
           'is a veto delivered too late.</p>\n'
           '        <p><span class="lemma">On paying the wage.</span> The books pay '
           'players for exploring the lens, and the counsel is to pay visibly: name '
           'the award at the table when the witch solves the vault problem with '
           'witchcraft instead of with the vault. What is rewarded aloud is repeated, '
           'and the whole engine of this chapter runs better when belief is the '
           'cheapest thing at the table to spend and the dearest to abandon.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the interview, the veto, '
                'and the wage</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">Every working is cast through a lens,</span> and the '
           'lens is called <span class="term">focus</span>: one unit of three parts '
           '&mdash; the paradigm, which answers why magick works; the practice, which '
           'shapes the doing; the instruments, which the doing holds &mdash; and this '
           'folio keeps the first part.<sup>a</sup> The <span class="term">paradigm</span> '
           'is the mage&rsquo;s model of the world: how it runs, her place within it, '
           'why her will can move it. Every mage needs one; the books count twelve in '
           'common use and keep counting past the twelve; and two mages may cast the '
           'identical working while believing utterly different things about what they '
           'have just done.<sup>b</sup> Paradigms may be joined where they cohere and '
           'never where they cannot &mdash; the machine-cosmos and the call of the '
           'wild do not share a house &mdash; and a new one may be drafted under '
           'three laws: belief follows need; the belief must be strong enough to '
           'bear weight, for no trivial god casts; and evidence must substantiate '
           'it, in the caster&rsquo;s own life if nowhere else.<sup>c</sup> And the '
           'paradigm binds what it enables: the working her grammar cannot say she '
           'cannot cast, however high her arts &mdash; the player may claim what the '
           'character believes, the Storyteller may refuse what the belief will not '
           'carry, and the books price the bargain in both directions, paying the '
           'lens well played in the coin of experience.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come and '
           'see one fire, lit five ways. The tinkerer lights it because creation is '
           'a machine and she has found the valve. The priest lights it because the '
           'order of heaven stoops to a petition correctly made. The chaote lights '
           'it because nothing means anything until he says so, and tonight he says '
           'fire. The coder lights it because reality is running code and code can '
           'be patched. The suit lights it because combustion is merely science, '
           'and science is the magick that won. Five reasons, one fire, one roll '
           'against one wall &mdash; and the disputants around this text hold what '
           'that unanimity of arithmetic does to the five reasons: whether the lens '
           'is a prison, whether a false lens can focus, and where the joining of '
           'lenses ends.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set in '
             'Abbess &amp; Goudy Old Style after the M20 interior &middot; first of '
             'the focus trio; the making of a lens waits overleaf, the practice at '
             '572, the tools at 586.',
 'folio': '567A',
 'glossL': '<p><span class="mark">a</span> On focus as one unit &mdash; paradigm, '
           'practice, instruments &mdash; see M20, folios 61 and 567, whence this '
           'page takes its number; the older recensions read the word otherwise, '
           'and the margin below keeps the variant.</p>\n'
           '        <p><span class="mark">b</span> On the paradigm and the twelve '
           'common models, see the Book of Magick, folios 567&ndash;571; the '
           'further dozens are the Book of Secrets&rsquo;, folios 188&ndash;196 '
           'of that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On joining and '
           'drafting paradigms &mdash; coherence, strength, and evidence &mdash; '
           'see folio 571 and the Book of Secrets&rsquo; answers, folios '
           '167&ndash;175 of that volume.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On enforcing focus '
           '&mdash; the claim, the refusal, and the experience paid for playing '
           'the lens &mdash; see folios 371&ndash;372, with the wage tables of '
           'the sixth chapter, folios 335&ndash;336.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> This folio is the first of the '
           'trio 500a promised: belief here, the practice at 572, the tools at '
           '586, and the rotes of 607 closing the chapter. The engine&rsquo;s '
           'second step &mdash; can her way of working believe it? &mdash; '
           'consults all four.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'constitution of 2a stands behind every line: no seat compels a '
           'paradigm, and the convocation seated nine lenses without ruling any '
           'of them true. The tractate&rsquo;s own method &mdash; variants kept, '
           'nothing harmonized &mdash; is this folio&rsquo;s law applied to '
           'itself, which the Masoret files as either rigor or infection.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The Union '
           'of chapter VI, folio 168 onward, runs this same law under other '
           'names &mdash; Enlightenment for the lens, Procedures for the '
           'castings &mdash; and will not thank the Masoret for saying so. The '
           'mirror is filed there.</p>',
 'h1': 'Focus: Belief',
 'hagahah': 'Everyone&rsquo;s paradigm accounts for everyone else&rsquo;s. This is '
            'either the setting&rsquo;s deepest kindness or its best joke, and the '
            'folio declines to rule.',
 'inner': '<p><span class="lemma">One unit of three parts.</span> The '
          'girsa first: the older recensions used the word focus for the tools '
          'alone, and a mage of rank could outgrow her focus entire; the '
          'twentieth reads focus as the whole act &mdash; belief, doing, tools, '
          'one lens &mdash; and rules that the tools may be outgrown but the '
          'belief never. The tractate files the variant unharmonized per its '
          'law, and notes the modern reading governs this chapter: what the '
          'master sheds at the summit is equipment, not conviction, and the '
          'books call shedding the last of it a pinnacle of the Path and '
          'decline, pointedly, to call it wisdom.</p>\n'
          '        <p><span class="lemma">Answers why.</span> The '
          'division&rsquo;s plain sense: the paradigm is how the world works; '
          'belief is why it works that way; and the working must fit both, '
          'which is the clause tables forget. The suit who believes in '
          'combustion cannot snap her fingers for it &mdash; the fingers are '
          'the wrong grammar &mdash; and the priest who could petition for '
          'fire cannot patch it in, though the arithmetic of both castings '
          'is identical to the die. The engine prices the what; the lens '
          'authorizes the how; neither substitutes for the other.</p>\n'
          '        <p><span class="lemma">Never where they cannot.</span> The '
          'coherence rule&rsquo;s plain sense: joining is normal &mdash; most '
          'mages of the present age blend two lenses or three into one '
          'personal seeing &mdash; and the forbidden pairing is the one whose '
          'halves refute each other, the books naming as their standing '
          'example the machine-cosmos wed to the creed of wildness: a mage '
          'cannot hold that answers live in the circuits and that the '
          'circuits are the sickness, not because the court forbids it but '
          'because no one can cast through a lens at war with its own '
          'glass.</p>\n'
          '        <p><span class="lemma">No trivial god casts.</span> The '
          'drafting laws&rsquo; plain sense: new lenses are legal and '
          'welcome, ground in real metaphysics, and gated by weight &mdash; '
          'the books refuse by name the cartoon divinity offered as a test '
          'case, for a belief adopted as a joke bears no load &mdash; and by '
          'evidence: belief follows need, and a belief that never once pays '
          'its holder starves. The Storyteller holds final approval, which '
          'is the constitution&rsquo;s quiet teeth: the table&rsquo;s reality '
          'is also a consensus, and new gods apply at the door.</p>\n'
          '        <p><span class="lemma">Binds what it enables.</span> '
          'Enforcement&rsquo;s plain sense, and the folio&rsquo;s center of '
          'gravity: the trade is symmetrical and priced. The player&rsquo;s '
          'claim &mdash; my character believes, therefore she can &mdash; is '
          'real currency, and so is the refusal &mdash; your character '
          'believes, therefore she cannot &mdash; and the books instruct the '
          'Storyteller to enforce the lens, favoring story over rules, '
          'precisely because the engine&rsquo;s flexibility would otherwise '
          'be its abuse. The wage clause completes the circuit: experience '
          'paid for exploring the lens makes belief profitable to keep, '
          'which is the design aligning the player&rsquo;s incentives with '
          'the character&rsquo;s soul, and doing it with money, which the '
          'sixth chapter would appreciate.</p>',
 'inner_head': 'On the Lens<span class="comm-sub">the inner commentary &middot; the '
               'plain sense &middot; the parts, the joining, and the '
               'trade</span>',
 'name': 'Focus: Belief',
 'outer': '<p><span class="lemma">Prison or lens.</span> The first dispute, '
          'as old as the chapter. <span class="voice">Some say</span> prison: '
          'the paradigm forbids more than it grants &mdash; the suit cannot '
          'snap, the priest cannot patch &mdash; and a law that binds every '
          'working to one grammar has simply relocated the Consensus into '
          'the mage&rsquo;s own skull, warden and inmate one flesh. <span '
          'class="voice">Others say</span> lens: nothing focuses without '
          'shape, the eye does not resent its curve, and the grammar that '
          'forbids is the same grammar that speaks &mdash; a mage with no '
          'paradigm casts nothing at all, which the books state as flatly '
          'as they state anything. The schools meet at the master&rsquo;s '
          'clause and split over its reading: grown past tools but never '
          'past belief means either that the last wall is load-bearing, or '
          'that the prison&rsquo;s innermost door is the one nobody is '
          'permitted to open. The folio notes only that both schools teach '
          'their apprentices the same first lesson: know your lens, for it '
          'is the one thing you cannot see through.</p>\n'
          '        <p><span class="lemma">Whether a false lens focuses.</span> '
          'The pragmatist fight, and the chapter&rsquo;s deepest. Five '
          'reasons, one fire: either at most one of the five is true and '
          'the false ones cast anyway, or truth is not what a paradigm is '
          'for. <span class="voice">Some say</span> the setting has ruled: '
          'belief works because belief works, the question which paradigm '
          'is true is a category error &mdash; asking which key is the '
          'true key when every one of them opens the door &mdash; and the '
          'court of 533a fines impossibility witnessed, never falsehood '
          'believed. <span class="voice">Others say</span> the setting has '
          'only deferred: beneath the Consensus there is a fact of the '
          'matter, the ascended presumably know it, and the paradigms are '
          'approximations ranked by a judge who has not yet published. The '
          'stakes are pastoral, not academic: the first school&rsquo;s mage '
          'can respect every rival she meets; the second&rsquo;s must '
          'quietly believe her rivals succeed by accident. <span '
          'class="kw">TEYKU</span> &mdash; the fire, consulted, burns '
          'either way.</p>\n'
          '        <p><span class="lemma">Where the joining ends.</span> '
          'Syncretism&rsquo;s limits. <span class="voice">Some say</span> '
          'the blend-of-three custom is a ceiling in fact if not in law: '
          'past three lenses the seeing smears, the practice loses its '
          'hands, and the mage who claims seven paradigms holds none '
          '&mdash; eclecticism as the vanity of the uncommitted. <span '
          'class="voice">Others say</span> the ceiling is colonial '
          'bookkeeping: whole living traditions are already blends deeper '
          'than three &mdash; the syncretic faiths the books themselves '
          'shelve with respect &mdash; and the coherence rule, honestly '
          'read, prices integration, not number: a hundred beliefs that '
          'cohere are one lens, and two that quarrel are none. The folio '
          'keeps the rule and the caution both: coherence is the law; '
          'counting is a heuristic; and the mage who cannot say in one '
          'sentence why her magick works has failed the only census that '
          'matters. The drafters, both schools note, planted the flag '
          'themselves: the founding lens of the whole Council &mdash; that '
          'all are one and divine in disguise &mdash; is already a '
          'syncretism vast enough to hold nine seats, which either proves '
          'the blend&rsquo;s power or explains the Council&rsquo;s '
          'meetings.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the prison, the pragmatist, and the '
               'blend</span>',
 'rubric': 'the lens, and why magick works',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of belief &middot; the paradigm as law',
 'title': 'Tractate Aliyah · Folio 567a — Focus: Belief — the lens, and why magick works',
 'type': 'daf'}
