# Folio 567b - The Inheritance. Verso of Belief: where a paradigm comes
# from and how it changes, per the wod-llm-wiki focus page (M20 pp.61,
# 371; Initiates of the Art pp.50-51; BoS pp.167-175).
FOLIO = {'bottom': '<p><span class="lemma">On playing the apprenticeship.</span> The formation '
           'this folio keeps is a chronicle&rsquo;s best prologue: run a session in '
           'the teaching years before the campaign proper, let the player feel the '
           'lens being fitted &mdash; the lessons accepted at face value, the '
           'question that was answered with a chore &mdash; and the paradigm on the '
           'sheet stops being a text box and becomes a scar with a name. The mentor '
           'thus created is the campaign&rsquo;s cheapest recurring character and '
           'its heaviest.</p>\n'
           '        <p><span class="lemma">On the rebuilt student.</span> If a '
           'character&rsquo;s backstory includes the breaking-and-rebuilding this '
           'folio files, treat it with 384b&rsquo;s care tools: the books&rsquo; own '
           'language for the method is the language of coercion, and a table should '
           'decide with eyes open whether that history is texture or subject. '
           'Handled honestly it is the setting&rsquo;s sharpest question wearing a '
           'single character&rsquo;s face.</p>\n'
           '        <p><span class="lemma">On the telltale quirk.</span> The '
           'inherited signature is a gift to Storytellers: let the observant '
           'notice whose hands taught the strange mage&rsquo;s hands &mdash; the '
           'same fold in the working, the same debt in the echo &mdash; and '
           'lineage becomes an investigable fact of the world. A mystery whose '
           'clues are mannerisms costs nothing and remembers everything.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on prologues, care, and '
                'the mannerism as clue</span>',
 'center': '<p class="noindent"><span class="dropcap">N</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">No one is born holding a lens.</span> The paradigm '
           'is formed in the teaching years: everything a teacher says or shows '
           'contributes to it, and the master helps make, unmake, or confirm the '
           'student&rsquo;s belief whether either of them intends the work or '
           'not.<sup>a</sup> The student who arrives already believing sets the '
           'teacher a choice &mdash; work within the found paradigm, or break it '
           'down and build again from the foundation, an immense and painful labor '
           'done at its gentlest by questioning and at its commonest by methods the '
           'books do not flatter.<sup>b</sup> The student who arrives empty is clay, '
           'shaped easily and fired narrow, and takes the teacher&rsquo;s every '
           'skew as the shape of the world. And the teaching leaves a signature: '
           'the student inherits the master&rsquo;s quirks and side-tones as if '
           'they were nature, so that a discerning eye can name a mage&rsquo;s '
           'teacher from the echo her workings carry.<sup>c</sup> Nor does the lens '
           'set like plaster: belief follows a life, the paradigm may change as its '
           'holder does, and at the far end of the Path the mage sheds tools and '
           'then rules and never the believing itself &mdash; the books calling '
           'that shedding a pinnacle of Awakening and withholding, deliberately, '
           'the word wise.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD of a house of three generations. The founder believed '
           'the world was a garden and taught her student so; the student, who '
           'had buried a crop to blight, believed the world was a garden with a '
           'debt against it, and taught her student so; and that student, born '
           'in a drowned decade, believes the world is a debt wearing a '
           'garden&rsquo;s name, and casts accordingly, and her workings carry '
           'the founder&rsquo;s fold in the soil and the middle teacher&rsquo;s '
           'salt at the rim. None of the three chose her lens from a shelf; '
           'each was handed one warm from another&rsquo;s grinding, and each '
           'reground it against her own decade until it fit. Three lenses, '
           'one lineage, no lesson repeated '
           'exactly &mdash; and the disputants around this text hold whose '
           'belief a taught belief is, and what the teaching owes the '
           'taught.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Belief: the recto keeps the lens, this side keeps the '
             'grinding of it.',
 'folio': '567B',
 'glossL': '<p><span class="mark">a</span> On the apprenticeship as the forge of '
           'paradigm &mdash; every lesson contributing, the master&rsquo;s hand '
           'acknowledged &mdash; see Initiates of the Art, folios 50&ndash;51 of '
           'that volume, a second-recension witness the tractate cites as '
           'elder testimony.</p>\n'
           '        <p><span class="mark">b</span> On the found paradigm and '
           'the two roads &mdash; working within, or the breaking and '
           'rebuilding &mdash; see the same folios, whose own comparison for '
           'the common method is to the cult-breaker&rsquo;s trade.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the empty '
           'student fired narrow, and the inherited signature by which a '
           'teacher is named in the student&rsquo;s echo, see the same '
           'folios; the echo itself is the resonance of 533a&rsquo;s '
           'margins.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the lens '
           'changing across a life, and the shedding of tools that never '
           'reaches belief, see M20, folios 61 and 371, with the Book of '
           'Secrets&rsquo; answers at folios 167&ndash;175 of that '
           'volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto rules that no one '
           'compels a paradigm, citing 2a; this side files the caveat the '
           'constitution never printed: no one chooses one alone, either. '
           'The two folios should be read as one argument having second '
           'thoughts.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'teacher&rsquo;s shaping hand is chapter V&rsquo;s whole '
           'infrastructure seen from below: every Tradition folio&rsquo;s '
           'gate &mdash; who is taken, who is taught, who teaches &mdash; is '
           'this folio&rsquo;s law wearing robes. The Akashic record of '
           '148a and the Hermetic houses of 158a file the two extremes.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'signature by which lineage is read returns at 572b, where the '
           'blended practice carries its teachers&rsquo; fingerprints, and '
           'the Union&rsquo;s cross-training at that folio is this '
           'law&rsquo;s industrialized form: one curriculum, one echo, by '
           'design.</p>',
 'h1': 'The Inheritance',
 'hagahah': 'Ask a mage where her paradigm came from and she names a teacher; ask '
            'the teacher and he names a debt. The lens is always secondhand; '
            'only the seeing is new.',
 'inner': '<p><span class="lemma">Whether either of them intends the work or '
          'not.</span> The formation clause&rsquo;s plain sense: paradigm '
          'transmission is not a curriculum but a climate &mdash; the '
          'offhand answer, the demonstrated shortcut, the question deflected '
          '&mdash; and the books&rsquo; point is that the master shapes the '
          'lens even in the lessons he thinks are about knots. The first '
          'few teachings land on trust and set like mortar, which is why '
          'the elder manuscript locates the danger early: the student '
          'cannot yet tell the world&rsquo;s shape from the teacher&rsquo;s '
          'posture, and by the time she can, the two have fused.</p>\n'
          '        <p><span class="lemma">Methods the books do not '
          'flatter.</span> The rebuilding&rsquo;s plain sense, kept at the '
          'books&rsquo; own temperature: the elder manuscript names subtle '
          'questioning and the arts of Mind as the gentle instruments, and '
          'then says plainly that the common method is the one the '
          'cult-breakers use. The tractate restates without softening: the '
          'sanctioned pedagogy of the setting includes the deliberate '
          'demolition of a person&rsquo;s working model of reality, '
          'undertaken because the found model blocks the door, and every '
          'seat that practices it has a word for it that is not the plain '
          'word. The margin below says what the table owes this fact.</p>\n'
          '        <p><span class="lemma">Shaped easily and fired '
          'narrow.</span> The blank slate&rsquo;s plain sense, and its '
          'price: the teachable student is the moldable student, and the '
          'mold&rsquo;s convenience is paid for in rigidity &mdash; a lens '
          'ground to one master&rsquo;s prescription, absorbing his every '
          'skew as a fact of optics. The elder manuscript&rsquo;s pairing '
          'is deliberate: the eclectic self-taught arrival is harder to '
          'teach and healthier to have taught, and the master who prefers '
          'clay should ask himself, the text implies, what he is actually '
          'preferring.</p>\n'
          '        <p><span class="lemma">Name a mage&rsquo;s teacher from '
          'the echo.</span> The signature&rsquo;s plain sense: quirks, '
          'side-tones, and resonance pass down the teaching line like an '
          'accent, unnoticed by the speaker and unmistakable to the '
          'listener, so that lineage is legible in the workings themselves '
          '&mdash; a provenance no forger thought to fake because no one '
          'chose to write it. The clause dignifies what every table '
          'already plays: magick has handwriting, and handwriting is '
          'taught. The clause also cuts the other way, and the elder '
          'manuscript says so: the student who would hide her school must '
          'unlearn gestures she cannot see herself making, which is why '
          'defectors are caught by their commas.</p>\n'
          '        <p><span class="lemma">Never the believing itself.</span> '
          'The far end&rsquo;s plain sense, completing the recto&rsquo;s '
          'girsa: the paradigm is not plaster but neither is it clothing '
          '&mdash; it changes as a life changes, by grief and evidence and '
          'the slow arguments of decades, and what the summit sheds is '
          'everything but it. The books&rsquo; withheld word matters: '
          'shedding the last tool is called a pinnacle of the Path and not '
          'of wisdom, because a lens with nothing left to grind against '
          'answers only to its own curve &mdash; and the folio of Quiet, '
          '554a, has already said where that country lies.</p>',
 'inner_head': 'On the Grinding<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; how a lens is made, marked, and '
               'remade</span>',
 'name': 'The Inheritance',
 'outer': '<p><span class="lemma">Whose belief is a taught belief.</span> The '
          'authenticity dispute. <span class="voice">Some say</span> the '
          'inheritance changes nothing: every human belief is secondhand '
          '&mdash; language, number, the very idea of evidence &mdash; and '
          'the mage&rsquo;s lens is no more compromised by having a teacher '
          'than her speech is by having a mother tongue; authenticity is '
          'what you do with the inheritance, not the absence of one. <span '
          'class="voice">Others say</span> the stakes here are not human-'
          'ordinary, and the analogy cheats: speech does not determine what '
          'fires you can light. In a cosmos where belief is load-bearing, '
          'the teacher has not influenced the student&rsquo;s opinions; he '
          'has installed her physics &mdash; and the constitutional right '
          'of 2a, that no seat compels a paradigm, is honored everywhere '
          'in the letter and nowhere in the raising. The first school '
          'answers: then no mage has ever consented to her own cosmos, '
          'which proves too much. The second answers: it proves exactly '
          'enough. <span class="kw">TEYKU</span> &mdash; the lineage of '
          'the Gemara files no complaint, and casts.</p>\n'
          '        <p><span class="lemma">What the teaching owes the '
          'taught.</span> The pedagogy dispute, pressed to its sore point: '
          'the rebuilding. <span class="voice">Some say</span> the '
          'demolition is sometimes mercy &mdash; the found paradigm that '
          'blocks the door also, in this setting, walks its holder toward '
          'the Quiet or the Fallen, and a teacher who lets a student keep '
          'a lens that will kill her has chosen his comfort over her '
          'life; the gentleness of the method matters more than the '
          'method&rsquo;s existence. <span class="voice">Others say</span> '
          'read what the books compare it to and believe them: the common '
          'method is the cult-breaker&rsquo;s, the direction of the '
          'comparison runs the wrong way, and a community that demolishes '
          'minds for their own good holds a tool no oversight in the '
          'setting audits &mdash; the seats police heresy and leave '
          'pedagogy sovereign, which is exactly backward. The schools '
          'agree on one reform and file it below: the method, where it '
          'exists at all, belongs in the open, named, consented to by '
          'the community if it cannot be by the student &mdash; for the '
          'alternative is the thing chapter VII will spend folios '
          'mourning.</p>\n'
          '        <p><span class="lemma">The empty student.</span> A '
          'third difficulty, quieter. The books prefer the eclectic '
          'arrival to the blank slate &mdash; harder to teach, healthier '
          'taught &mdash; and yet every institution of the setting is '
          'built to prefer the slate: the gathered young, the standard '
          'curriculum, the echo inherited by design. <span '
          'class="voice">Some say</span> this is mere institutional '
          'physics, no more sinister in a chantry than in a guild. <span '
          'class="voice">Others say</span> the preference is the quiet '
          'engine of every failure chapter V documents seat by seat: '
          'orthodoxies are not argued into a Tradition, they are '
          'admitted into it, one moldable cohort at a time. The folio '
          'notes that the setting&rsquo;s healthiest lineages, on the '
          'books&rsquo; own showing, are the ones that recruit the '
          'already-believing and argue with them forever after &mdash; '
          'and that this is also, precisely, the more expensive '
          'option.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the secondhand lens, the demolition, '
               'and the slate</span>',
 'rubric': 'where a lens comes from',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of the inheritance &middot; the making '
             'of belief as law',
 'title': 'Tractate Aliyah · Folio 567b — The Inheritance: where a lens comes from',
 'type': 'daf'}
