# Folio 572a - Focus: Practice. Second of the focus trio, per the
# wod-llm-wiki focus and practices pages (M20 pp.572-586; BoS pp.196-205).
FOLIO = {'bottom': '<p><span class="lemma">On naming the practice aloud.</span> A practice is '
           'the most filmable thing on a character sheet: it is what the camera '
           'sees. Ask each player to describe, once, what their magick looks like '
           'to a bystander &mdash; the hands, the tools, the noise &mdash; and post '
           'it beside the paradigm sentence. Every scene after that inherits free '
           'texture, and every vulgarity call inherits a fact pattern instead of a '
           'debate.</p>\n'
           '        <p><span class="lemma">On the practice as spotlight.</span> '
           'Build set-pieces to practices, not to Spheres: the witch&rsquo;s scene '
           'wants a kitchen and a garden, the ritualist&rsquo;s wants chalk and '
           'hours, the weird scientist&rsquo;s wants a device with one too many '
           'switches. A party whose members cast identically is a design failure '
           'the engine never forced; the practices exist so that five castings of '
           'the same Effect are five different scenes.</p>\n'
           '        <p><span class="lemma">On respecting the source.</span> Several '
           'practices in the lists wear the names of living traditions, and the '
           'books themselves flag the era&rsquo;s borrowings as often being theft. '
           'The counsel is the standing one: play cultures as homes people live '
           'in, not costumes, and when the table cannot do that with care, choose '
           'a different coat.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the camera, the '
                'set-piece, and the borrowed coat</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The practice is the shape of the doing:</span> the '
           'road by which belief becomes act, drawing on learned abilities and '
           'channeled through the tools the next folio keeps.<sup>a</sup> The books '
           'shelve the shapes in families, each name a country and not a village: '
           'the transmuter&rsquo;s craft of raising lower states to higher; the '
           'high ceremony of circle, hour, and word; the witch&rsquo;s hearth-'
           'craft and the shaman&rsquo;s crossing; the healer&rsquo;s road and the '
           'martial way; faith&rsquo;s devotion and the chaote&rsquo;s improvised '
           'iconoclasm; the gutter-mage&rsquo;s make-do; the mesmerist&rsquo;s '
           'dominion and the dealer&rsquo;s craft of desire; and the machine-'
           'roads &mdash; the visionary&rsquo;s weird science, the engineer&rsquo;s '
           'hypertech, the cyberneticist&rsquo;s steered flesh, the '
           'reality-hacker&rsquo;s edit.<sup>b</sup> Each family favors its arts '
           'and demands its tools, and none is a village: a hundred real '
           'disciplines shelter under every name.<sup>c</sup> The practice is '
           'load-bearing at the wall: the doing that fits the street&rsquo;s '
           'expectations tips a working toward coincidence, and the doing that '
           'affronts them pays the vulgar rate &mdash; the same fire, priced by '
           'its theater, and the theater chosen once at creation and carried '
           'into every street thereafter. And the practice reaches through the '
           'sheet: a working '
           'practice wants at least one learned ability and prospers on three or '
           'more, besides whatever its instruments demand of the hands &mdash; '
           'the ritualist her dead tongues, the herbalist her lore, the '
           'engineer her workshop years &mdash; for the doing is a competence '
           'before it is a mystery.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and see one healing, done five ways. The witch simmers it; the '
           'ritualist inscribes it across four hours of chalk; the martial '
           'artist presses two fingers where the meridian crosses; the '
           'Ecstatic dances it out of the patient; the weird scientist '
           'straps on the resonating coil, which has never once worked the '
           'same way twice. Five theaters, one mending, and the street '
           'files three of them under folk remedy, one under physical '
           'therapy, and one under call the police &mdash; which is the whole '
           'law of 533a restated as staging. The disputants around this '
           'text hold the shopping question, the gating question, and the '
           'question of whose hands the names belong to.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'second of the focus trio; the blending and learning of practices '
             'waits overleaf, the tools at 586.',
 'folio': '572A',
 'glossL': '<p><span class="mark">a</span> On practice as the shape of focus '
           '&mdash; to make or to do &mdash; see M20, the Book of Magick, folio '
           '572, whence this page takes its number.</p>\n'
           '        <p><span class="mark">b</span> On the common practices, '
           'shelved and described, see folios 572&ndash;586; the expanded '
           'seven are the Book of Secrets&rsquo;, folios 196&ndash;205 of '
           'that volume.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On each entry '
           'as an exceedingly generalized country of real disciplines, see '
           'folio 572; the books&rsquo; own word.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'abilities a practice wants &mdash; one at the least, likely '
           'three and more, plus the instruments&rsquo; demands &mdash; see '
           'the Book of Secrets, folios 167&ndash;175 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The trio&rsquo;s middle folio: '
           'belief behind at 567, tools ahead at 586, and the engine of 500a '
           'consulting all three at its second step. The vulgarity pricing '
           'this page leans on is 533a&rsquo;s law entire.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> Chapter '
           'V is this folio&rsquo;s portrait gallery: every Tradition seat is '
           'a practice-family raised to a politics, and the reader who wants '
           'the countries toured house by house should read 148 through 164 '
           'with this page open.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'martial way&rsquo;s own folio is 423a, where Do is priced; the '
           'craft of desire is the Syndicate&rsquo;s at 192, in chapter VI; '
           'and the healer&rsquo;s road runs through 516b&rsquo;s wards. The '
           'Masoret notes the tractate keeps returning here without '
           'meaning to.</p>',
 'h1': 'Focus: Practice',
 'hagahah': 'The paradigm is what your head believes. The practice is what your '
            'hands believe, and hands are harder to convert.',
 'inner': '<p><span class="lemma">The road by which belief becomes act.</span> '
          'The definition&rsquo;s plain sense: practice stands between the '
          'lens and the tools as doing stands between intending and '
          'holding &mdash; the recto&rsquo;s paradigm supplies why, this '
          'folio supplies how, and the two must fit: the machine-believer '
          'does not simmer herbs, the garden-believer does not solder. The '
          'older recensions called this the mage&rsquo;s style, and the '
          'girsa is worth its line: style named a flavor, practice names a '
          'discipline, and the promotion is the twentieth recension '
          'saying the doing is not decoration.</p>\n'
          '        <p><span class="lemma">A country and not a village.</span> '
          'The families&rsquo; plain sense: each shelved name is a '
          'generalization over dozens or hundreds of real disciplines '
          '&mdash; the witch&rsquo;s country holds kitchen-craft and '
          'coven-craft and hedge-lore that share little but a posture '
          'toward the world &mdash; and the books say so in as many '
          'words. The table&rsquo;s use is precision downward: a character '
          'does not practice witchcraft, she practices her witchcraft, '
          'and the folio&rsquo;s counsel is to write the village on the '
          'sheet and let the country stay in the index.</p>\n'
          '        <p><span class="lemma">Priced by its theater.</span> The '
          'wall clause&rsquo;s plain sense: practice is where vulgarity '
          'lives, because the street judges the doing and never the '
          'Sphere. The five healings of the Gemara are one Effect at one '
          'rank; their prices differ because their theaters do, and the '
          'practice chosen at character creation is therefore a standing '
          'bet about which streets the chronicle will walk. The '
          'technomancer is cheap in the city and dear at the standing '
          'stones; the witch, the reverse; and the engine, as always, is '
          'pricing belief&rsquo;s fit rather than power&rsquo;s size.</p>\n'
          '        <p><span class="lemma">Wants at least one learned '
          'ability.</span> The sheet clause&rsquo;s plain sense: a practice '
          'is not an aura but a competence, and the books gate it through '
          'the mundane columns &mdash; one ability at the minimum, three '
          'or more in an honest build, plus whatever the tools demand: '
          'the ritualist&rsquo;s dead languages, the herbalist&rsquo;s '
          'lore, the engineer&rsquo;s workshop hands. The clause is the '
          'engine&rsquo;s quiet realism: magick is a craft practiced by '
          'the same person who knows things, and the mage with no '
          'abilities behind her practice is a believer with no '
          'hands. The minimum of one is a floor for the desperate; the '
          'books&rsquo; honest expectation is three and upward, and the '
          'seder of 250a already prices the difference at creation, '
          'where the ability columns and the practice are bought from '
          'the same purse on purpose.</p>\n'
          '        <p><span class="lemma">The machine-roads.</span> A note '
          'on the technomantic families, against a common misreading: '
          'weird science, hypertech, cybernetics, and the hacker&rsquo;s '
          'edit are practices, not allegiances &mdash; the Etherite and '
          'the Iterator may share a family and share nothing else &mdash; '
          'and the difference between the visionary&rsquo;s device that '
          'works only for her and the Union&rsquo;s device that works for '
          'anyone cleared to hold it is the deepest sorting fact in the '
          'setting&rsquo;s machine-half. Chapter VI takes that thread up '
          'at length; this folio only labels the spool.</p>',
 'inner_head': 'On the Doing<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; families, theaters, and '
               'hands</span>',
 'name': 'Focus: Practice',
 'outer': '<p><span class="lemma">The shopping question.</span> <span '
          'class="voice">Some say</span> practice-shopping is the '
          'munchkin&rsquo;s oldest trick wearing anthropology&rsquo;s coat: '
          'the build that takes the ritualist&rsquo;s discounts, the '
          'chaote&rsquo;s flexibility, and the technomancer&rsquo;s street '
          'camouflage has optimized away the one thing a practice is for, '
          'which is constraint with a face. <span class="voice">Others '
          'say</span> the accusation confuses breadth with bad faith: real '
          'occultism is magpie to the bone, the books bless the blend of '
          'three, and the character who prays, codes, and boxes is not '
          'gaming the chart but living in this century. The schools '
          'converge, as the recto&rsquo;s did, on coherence: the blend '
          'must answer one why, and the build whose practices share '
          'nothing but their discounts has failed the census whatever '
          'its sheet says. The remaining daylight between them is '
          'temperamental &mdash; whether one polices the border or the '
          'interior &mdash; and the folio files it as weather, noting only '
          'that the border patrol has never once caught a munchkin the '
          'interior audit would have missed.</p>\n'
          '        <p><span class="lemma">The gating question.</span> '
          'Whether practices gate the arts or merely dress them &mdash; '
          'the girsa runs deep. The eldest recension tied tools to '
          'Spheres and whole fellowships to uniform kits; the later '
          'recensions untied both, and the Book of Secrets says plainly '
          'that the tying was an error to ignore. <span '
          'class="voice">Some say</span> the untying was the line&rsquo;s '
          'best single edit: the arts are grammar, the practice is '
          'diction, and no diction forbids a sentence &mdash; the witch '
          'can reach the machine-arts through her own country if her '
          'belief stretches there honestly. <span class="voice">Others '
          'say</span> something true was lost with the tying: a practice '
          'that gates nothing risks meaning nothing, the affinity a seat '
          'feels for its own arts is real and earned, and the modern '
          'reading keeps that truth only as a soft pressure the table '
          'must remember to apply. The folio keeps both readings and '
          'the books&rsquo; ruling: the gate is belief, not equipment '
          '&mdash; and belief, honestly played, gates plenty.</p>\n'
          '        <p><span class="lemma">Whose hands the names belong '
          'to.</span> The appropriation dispute, which the books '
          'themselves open. Several countries on the shelf are living '
          'peoples&rsquo; houses &mdash; the crossing, the loa&rsquo;s '
          'service, the yogas &mdash; and the era chapters say in plain '
          'text that the great syncretic century took much of what it '
          'took without asking. <span class="voice">Some say</span> the '
          'lists honor what they include: the setting shelves these '
          'houses beside the ceremonial west with equal rules-weight, '
          'which is more respect than the real century paid. <span '
          'class="voice">Others say</span> inclusion at rules-weight is '
          'exactly how a museum honors a temple, and the question is not '
          'the shelf but the door: who at the table wears the coat, and '
          'how. The folio has no ruling that survives contact with a '
          'particular table, and says so; the counsel below is the '
          'binding&rsquo;s standing one, and it is counsel, not law. '
          '<span class="kw">TEYKU</span> &mdash; and the hands '
          'remember.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the shopper, the gate, and the '
               'names</span>',
 'rubric': 'the shape of the doing',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of practice &middot; the doing as law',
 'title': 'Tractate Aliyah · Folio 572a — Focus: Practice — the shape of the doing',
 'type': 'daf'}
