# Folio 572b - The Blend. Verso of Practice: the personalized practice,
# learning new ones, and learning across foci, per the wod-llm-wiki focus
# page (BoS pp.167-175; M20 p.571).
FOLIO = {'bottom': '<p><span class="lemma">On playing the learning.</span> The books gate the '
           'new practice behind play, and the counsel is to take them at their word: '
           'the season in which the witch learns lab-craft is a story engine no '
           'random encounter matches &mdash; a new teacher with new debts, a first '
           'failure in an unfamiliar grammar, the old practice jealous in her hands. '
           'Grant the dots when the story has earned them, and the sheet will read '
           'like a biography instead of a receipt.</p>\n'
           '        <p><span class="lemma">On the convert&rsquo;s window.</span> '
           'The cross-focus surcharge prices a rare scene: two mages trading arts '
           'across a worldview. Stage it &mdash; the payment in patience, the '
           'translation that keeps failing, the moment the student stops '
           'converting units and starts believing &mdash; and the surcharge stops '
           'being a tax and becomes the drama it was priced to represent.</p>\n'
           '        <p><span class="lemma">On the defector.</span> The '
           'Union&rsquo;s wall &mdash; train within freely, teach outward never, '
           'convert to cross &mdash; is a campaign frame in one clause: every '
           'Technocrat who teaches a Tradition mage has already committed the '
           'offense chapter VI prices, and every such lesson is therefore a plot. '
           'The Storyteller who wants a defection arc has the books&rsquo; own '
           'invoice for it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on seasons, windows, and '
                'defections</span>',
 'center': '<p class="noindent"><span class="dropcap">N</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">No mage practices a country; she practices her own '
           'village in it.</span> The working practice of the present age is '
           'personal: assembled from as many as three of the shelved families, '
           'blended into one discipline that answers one belief, or invented '
           'outright where the belief demands it.<sup>a</sup> A new practice is '
           'learned and not bought: the learning is played out in the chronicle, '
           'the student takes at least a dot of an ability the practice works '
           'through, and the scholarship is priced &mdash; a specialty of the '
           'esoteric lore at its fourth rank, or of the sciences for the '
           'machine-roads.<sup>b</sup> Learning across a focus costs more than '
           'learning within one: the working taken from a teacher whose way of '
           'believing is foreign pays a surcharge of experience and takes twice '
           'the season, for the student is not memorizing a technique but '
           'renegotiating a world.<sup>c</sup> And the Union walls its own '
           'garden: within the Technocracy the conventions cross-train freely, '
           'one curriculum beneath five uniforms, but their arts pass outward '
           'only by defection &mdash; the operative who would teach the '
           'Traditions must first convert to them, and the operative who '
           'would learn from them has, by the Union&rsquo;s own bookkeeping, '
           'already begun to.<sup>d</sup> So the law of crossings runs: free '
           'where the believing is shared, priced where it must be '
           'translated, forbidden where it may not be.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD of a witch who needed the machine-country&rsquo;s '
           'arts. She found an Etherite patient enough to teach, and the first '
           'season was spent failing: she reached for the coil as she reached '
           'for the knife, and the coil is not a knife. In the second season '
           'she stopped translating &mdash; stopped asking what the capacitor '
           'was instead of &mdash; and one morning calibrated the instrument '
           'the way she proofed bread, by the feel of the day, and it sang '
           'for her. Her workings ever after carried yeast in the copper, '
           'and her teacher called it contamination, and called it that with '
           'unmistakable pride. The disputants around this text hold whether '
           'the blend completes or dilutes, what the scholarship gate '
           'guards, and what the Union&rsquo;s wall confesses.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Practice: the recto keeps the countries, this side keeps '
             'the crossings between them.',
 'folio': '572B',
 'glossL': '<p><span class="mark">a</span> On the blend of up to three '
           'practices into one personalized discipline, and on inventing new '
           'ones, see M20, folio 571, with the Book of Secrets&rsquo; answers, '
           'folios 167&ndash;175 of that volume.</p>\n'
           '        <p><span class="mark">b</span> On learning a new practice '
           '&mdash; the played season, the ability dot, and the specialty of '
           'Esoterica at the fourth rank or Science in its place &mdash; see '
           'the same folios of the Book of Secrets.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the '
           'cross-focus surcharge &mdash; the two points of experience and '
           'the doubled time &mdash; see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'Union&rsquo;s free cross-training within and its wall without '
           '&mdash; teaching the Traditions only by converting &mdash; see '
           'the same folios; the offense as the Union prices it is chapter '
           'VI&rsquo;s business, folio 168 onward.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The inherited signature of '
           '567b returns here compounded: the blended practice carries every '
           'teacher&rsquo;s fingerprint at once, and the Gemara&rsquo;s '
           'yeast-in-the-copper is that folio&rsquo;s law told as a '
           'success story instead of a warning.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'esoteric lore that gates the learning is the same scholarship '
           'the seder of 250a prices at creation &mdash; the tractate&rsquo;s '
           'recurring insistence that magick is a literate trade. The '
           'Masoret files the design signature.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'Union&rsquo;s one-curriculum echo &mdash; five uniforms, one '
           'handwriting &mdash; is read against 567b&rsquo;s lineage law at '
           'chapter VI, where the conventions&rsquo; folios 186 through 194 '
           'each wear the shared grammar differently.</p>',
 'h1': 'The Blend',
 'hagahah': 'Every personalized practice is a treaty between the countries that '
            'raised it, and like all treaties it is renegotiated nightly, in '
            'the hands.',
 'inner': '<p><span class="lemma">Her own village in it.</span> The '
          'personalization clause&rsquo;s plain sense: the shelved families '
          'are indexes, not identities, and the practice a mage actually '
          'holds is singular &mdash; her blend, her emphases, her '
          'inherited quirks &mdash; assembled from at most three countries '
          'so long as one belief holds the assembly together. The '
          'coherence test is the recto&rsquo;s and the lens folio&rsquo;s, '
          'applied a third time: the binding asks one question at three '
          'altitudes, and the question is always whether the pieces '
          'answer the same why.</p>\n'
          '        <p><span class="lemma">Learned and not bought.</span> '
          'The acquisition clause&rsquo;s plain sense: a practice cannot '
          'be purchased between sessions like a rank, because it is not a '
          'quantity but a competence with a history. The books gate it '
          'three ways at once &mdash; through play, so the learning has a '
          'story; through an ability dot, so the hands have something to '
          'know; and through the specialty, so the mind has somewhere to '
          'file it. The triple gate is the engine&rsquo;s statement that '
          'the doing is as deep as the believing, which is this '
          'verso&rsquo;s whole thesis.</p>\n'
          '        <p><span class="lemma">The scholarship is priced.</span> '
          'The specialty clause&rsquo;s plain sense, with its rank named: '
          'the esoteric lore must stand at its fourth rank before the '
          'specialty can be taken, which sets the new practice behind '
          'years of study in the fiction and real points on the sheet. '
          'The machine-roads substitute the sciences, rank for rank. The '
          'clause reads as elitism and functions as honesty: the mage '
          'who would hold two countries must know both countries, and '
          'the folio&rsquo;s margin holds the dispute about who that '
          'honesty prices out.</p>\n'
          '        <p><span class="lemma">Renegotiating a world.</span> '
          'The surcharge&rsquo;s plain sense: the cross-focus lesson '
          'costs two points more and twice the time because the '
          'technique is the cheap part &mdash; what the student actually '
          'buys is the translation of a working out of a foreign '
          'believing and into her own, and translations of that order '
          'are paid for in seasons. The Gemara&rsquo;s witch is the '
          'clause walked: the first season buys nothing but failure, '
          'and the purchase completes the morning the translation '
          'stops. Note what the surcharge is not: a tax on friendship '
          'across factions. The books price the lesson, never the '
          'teacher, and two mages of foreign believings may share a '
          'campfire for years before either pays a point &mdash; the '
          'bill arrives only when a working changes hands.</p>\n'
          '        <p><span class="lemma">One curriculum beneath five '
          'uniforms.</span> The Union clause&rsquo;s plain sense: '
          'cross-training within the Technocracy is free because the '
          'conventions share a single believing &mdash; the machine-'
          'cosmos, administered &mdash; so nothing needs translating; '
          'and the wall stands outward because teaching across it would '
          'require exactly the renegotiation the surcharge prices, '
          'which the Union does not sell. The defection clause is '
          'therefore not cruelty but bookkeeping: the operative who '
          'can honestly teach a witch has already stopped believing '
          'as an operative believes, and the paperwork merely '
          'catches up.</p>',
 'inner_head': 'On the Crossing<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; blends, gates, and walls</span>',
 'name': 'The Blend',
 'outer': '<p><span class="lemma">Completes or dilutes.</span> The '
          'blend&rsquo;s dispute proper. <span class="voice">Some say</span> '
          'dilution: every country in a blend is held at tourist depth, '
          'the singular practices of the old lineages went further '
          'precisely because they went narrower, and the present '
          'age&rsquo;s magpie discipline trades mastery for coverage in '
          'a market where mastery is the only currency the wall '
          'respects. <span class="voice">Others say</span> completion: '
          'the narrow lineage was the artifact &mdash; of scarcity, of '
          'guild jealousy, of teachers hoarding &mdash; and the blended '
          'practice is what a whole believing looks like when nothing '
          'artificial forbids it; the witch who proofs bread in the '
          'copper is not shallower than her teachers, she is wider than '
          'their categories. The evidence cuts both ways on the '
          'books&rsquo; own showing &mdash; the setting&rsquo;s masters '
          'include monomaniacs and polymaths in like proportion &mdash; '
          'and the folio suspects the dispute is temperament wearing '
          'pedagogy&rsquo;s coat, which does not make it less real at '
          'a table &mdash; for the player must actually choose, at '
          'creation and at every season after, whether the next dot '
          'deepens the village or annexes a province, and the two '
          'sheets that result play like different characters because '
          'they are.</p>\n'
          '        <p><span class="lemma">What the gate guards.</span> '
          'The scholarship dispute. <span class="voice">Some say</span> '
          'the fourth-rank gate guards coherence itself: it is the '
          'engine&rsquo;s proof against the coupon-book focus, pricing '
          'the second country in the one currency that cannot be '
          'min-maxed, which is time spent knowing things. <span '
          'class="voice">Others say</span> look at who the gate prices '
          'out: the gutter-mage, the self-taught, the traditions whose '
          'lore was never permitted a library &mdash; the gate reads '
          'scholarship as books because its drafters did, and a folio '
          'that has already ruled the practice is what the hands '
          'believe should notice when the law suddenly demands the '
          'hands produce a bibliography. The schools agree the gate '
          'guards something worth guarding and disagree whether it '
          'guards it fairly; the tractate files the question with '
          'chapter V&rsquo;s gates, where it has relatives &mdash; and '
          'notes for the defense that the gate at least prices '
          'learning rather than lineage, which not every seat in that '
          'chapter can say of its own doors.</p>\n'
          '        <p><span class="lemma">What the wall confesses.</span> '
          'The Union dispute, in advance of its chapter. <span '
          'class="voice">Some say</span> the free interior proves the '
          'conventions are one Tradition wearing five masks &mdash; one '
          'curriculum, one echo, one believing &mdash; and the wall '
          'outward is ordinary security, no stranger than any '
          'chantry&rsquo;s. <span class="voice">Others say</span> read '
          'the asymmetry: every Tradition can in principle teach every '
          'other, at a price, because their believings are '
          'renegotiable; the Union&rsquo;s arts pass outward only by '
          'conversion because its believing is not a lens among lenses '
          'but a claim to be the glass itself &mdash; and an art that '
          'cannot survive translation has confessed what it is. The '
          'first school calls that polemic; the second calls it the '
          'plain reading; and chapter VI, which begins at folio 168, '
          'inherits the file. <span class="kw">TEYKU</span> &mdash; '
          'held open against the Union&rsquo;s own folios.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the blend, the gate, and the '
               'wall</span>',
 'rubric': 'blends, learning, and the crossing of foci',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of the blend &middot; the crossing as law',
 'title': 'Tractate Aliyah · Folio 572b — The Blend: blends, learning, and the crossing of foci',
 'type': 'daf'}
