# Folio 586a - Focus: Instruments. Third of the focus trio, per the
# wod-llm-wiki instruments hub (M20 pp.586-600, 566-567; BoS pp.205-210).
FOLIO = {'bottom': '<p><span class="lemma">On the toolkit interview.</span> After the paradigm '
           'sentence and the practice description, ask for the seven: have each '
           'player list their instruments by name &mdash; not categories, objects. '
           'The list is a scene generator (any tool can be stolen, broken, '
           'borrowed, or profaned), a vulgarity guide (the working&rsquo;s theater '
           'is its tools), and a portrait the player draws without noticing '
           'they&rsquo;re drawing.</p>\n'
           '        <p><span class="lemma">On breaking the unique.</span> The '
           'unique instrument&rsquo;s permanence clause is the Storyteller&rsquo;s '
           'heaviest legal weapon and should be drawn accordingly: destroying it '
           'is not a complication but an amputation, done once a chronicle if at '
           'all, telegraphed, and paid for in story. The threat of the loss is '
           'worth ten losses; the loss itself is worth one, and it had better be '
           'the right one.</p>\n'
           '        <p><span class="lemma">On the shedding as milestone.</span> '
           'When a mage&rsquo;s rank permits a tool to be dropped, make the '
           'dropping a scene: the wand set down deliberately is a graduation, '
           'and the wand clutched past need is characterization. The books '
           'withhold the word wise from the fully unencumbered on purpose; the '
           'table should feel the withholding.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on the seven, the '
                'breaking, and the setting-down</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The instrument is whatever will hold an '
           'intention:</span> object or activity, wand or dance, formula or fast, '
           'glance or coin &mdash; if it can capture a purpose and carry it into '
           'the world, it serves.<sup>a</sup> The mage begins with seven at the '
           'least, as the seder already priced, and sheds them only as her rank '
           'rises.<sup>b</sup> The law grades the tools by intimacy: the standard '
           'tool of a practice earns nothing and its absence costs; the tool '
           'personalized to the mage&rsquo;s first arts eases her wall a step in '
           'those arts alone; the unique tool &mdash; one of its kind in the '
           'world &mdash; eases a step and can be lost, and its virtue dies with '
           'it; the tool both personal and unique eases two steps and serves its '
           'mage only. And the significant tool of the optional reading may, '
           'used impressively and believably, either ease a step or clothe a '
           'vulgar working in coincidence &mdash; one gift or the other, never '
           'both.<sup>c</sup> No stacking of tools moves any wall past the third '
           'step. The mage stripped of her tools before her rank releases them '
           'works bare at a heavy price &mdash; a point of will spent and three '
           'more on the wall &mdash; and the mage grown past tools entirely has '
           'reached what the books call a pinnacle of the Path, in a sentence '
           'that pointedly does not contain the word wisdom.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and read one toolkit as a biography. A pocketknife with a repaired '
           'hinge: her father&rsquo;s, and the first thing she ever fixed. A '
           'deck of cards missing the three of cups: the missing card is the '
           'point; she lost it the night she learned what loss was for. Chalk, '
           'bought by the gross, because circles should be cheap and doorways '
           'dear. A ring of keys to houses she no longer enters: closure is '
           'also a working. Her grandmother&rsquo;s measuring spoons, which '
           'measure other things now. A phone full of photographs she has '
           'never once printed. And a red thread around the left wrist, '
           'which she will not explain, and which is the only one whose '
           'loss would bare her. Seven tools, one woman legible &mdash; and '
           'the disputants around this text hold when a tool may be set '
           'down, and what the mundane-seeming kit does to the court&rsquo;s '
           'arithmetic.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'third of the focus trio; the full inventory waits overleaf, and '
             'the rotes of 607 close the chapter.',
 'folio': '586A',
 'glossL': '<p><span class="mark">a</span> On the instrument as object or '
           'activity &mdash; anything that captures intention &mdash; see M20, '
           'the Book of Magick, folio 586, whence this page takes its '
           'number.</p>\n'
           '        <p><span class="mark">b</span> On the seven at the least '
           'and the shedding by rank, see the same folio; the seder&rsquo;s '
           'pricing is folio 250a of this binding, at its fourth step.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the grades '
           '&mdash; standard, personalized, unique, personal-and-unique, and '
           'the optional significant tool with its either-or gift &mdash; see '
           'folios 587&ndash;588, with the mythic threads of the optional '
           'reading.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the cap at '
           'three, the bare working&rsquo;s will-and-three, and the pinnacle '
           'sentence with its withheld word, see folios 61 and '
           '566&ndash;567.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The trio closes: belief at '
           '567, doing at 572, holding here &mdash; and the engine of 500a '
           'consults all three before any die is cast. The wall arithmetic '
           'this folio grades feeds directly into 500a&rsquo;s modifier '
           'catalogue.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'tool as witness-management is 533a and 533b&rsquo;s law worn on '
           'the body: the lighter and lacquer that make fire coincidental '
           'are this folio&rsquo;s standard tools doing the court&rsquo;s '
           'work in advance. The disputes below press the point.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'unique tool&rsquo;s mortality touches the Wonders of the minor '
           'tractate Kelim, wanting: the instrument is to the Wonder as '
           'the habit is to the vow, and the two laws will want '
           'reconciling when that tractate is bound.</p>',
 'h1': 'Focus: Instruments',
 'hagahah': 'The wand is for the mage, not the magick. This is the one sentence '
            'in the chapter that every school, seat, and century signs '
            'without amendment.',
 'inner': '<p><span class="lemma">Whatever will hold an intention.</span> The '
          'definition&rsquo;s plain sense, and its breadth on purpose: the '
          'law refuses to distinguish object from activity because belief '
          'does not &mdash; the fast is a tool exactly as the knife is, '
          'and the books&rsquo; list runs from armor to zealotry through '
          'blood, chalk, fashion, mathematics, meals, money, ordeals, '
          'prayer, and the crowd itself. Every tool tugs a symbol&rsquo;s '
          'thread, marks its holder&rsquo;s tribe, and costs time to '
          'use, which is the definition&rsquo;s three quiet teeth.</p>\n'
          '        <p><span class="lemma">Seven at the least.</span> The '
          'count&rsquo;s plain sense: seven is a floor, not a flavor '
          '&mdash; the beginning mage&rsquo;s believing is genuinely '
          'distributed across her kit, and the law means the '
          'distribution. The floor is why the bare working costs what it '
          'costs: a mage stripped of her tools has not lost equipment '
          'but grammar, and the will-and-three price is the engine '
          'writing that sentence as arithmetic.</p>\n'
          '        <p><span class="lemma">Grades the tools by '
          'intimacy.</span> The ladder&rsquo;s plain sense: the discounts '
          'do not price the tool&rsquo;s power &mdash; no wand in the '
          'catalogue throws a bigger fire &mdash; they price the '
          'tool&rsquo;s closeness to the believing. Standard is the '
          'practice&rsquo;s furniture; personalized is the mage&rsquo;s '
          'own history condensed, and eases only the arts she first '
          'learned through it; unique is closeness raised to '
          'mortality, the virtue dying with the object; and the '
          'double grade is both at once, usable by her alone. The '
          'ladder is the recto pair&rsquo;s thesis made portable: '
          'focus is intimacy, and intimacy discounts.</p>\n'
          '        <p><span class="lemma">One gift or the other, never '
          'both.</span> The significant tool&rsquo;s plain sense, under '
          'the optional reading: the impressive tool wielded believably '
          'may ease the wall or may dress the vulgar as coincidence, '
          'and the either-or is load-bearing &mdash; a tool that did '
          'both would collapse the court&rsquo;s whole fee schedule '
          'into stagecraft. The believability clause does the real '
          'work: the gift exists only where the local street could '
          'credit the theater, which keeps the significant tool a '
          'reading of 533a rather than an exception to it.</p>\n'
          '        <p><span class="lemma">Before her rank releases '
          'them.</span> The shedding&rsquo;s plain sense: tools are '
          'outgrown from the top of the sheet downward, rank by rank, '
          'and the timetable is the mage&rsquo;s enlightenment and not '
          'her convenience. The stripped mage works bare at will-and-'
          'three because she is casting ahead of her own believing; '
          'the graduated mage pays nothing because her believing has '
          'genuinely moved indoors. The two bare castings are '
          'identical to a camera and opposite in law, which is this '
          'chapter in one image.</p>\n'
          '        <p><span class="lemma">No stacking past the third '
          'step.</span> The cap&rsquo;s plain sense, restated from the '
          'engine&rsquo;s side: the discounts net against every other '
          'modifier in 500a&rsquo;s catalogue, and the sum never moves '
          'a wall more than three steps in either direction &mdash; so '
          'the collector who layers personalized, unique, and '
          'significant tools atop essence and patience has assembled '
          'texture, not arithmetic, past the third step. The cap is '
          'the same mercy and the same tax it was at the casting '
          'folio: it keeps the beloved toolkit from becoming a '
          'machine for buying certainty, and it keeps the '
          'discount-hunter&rsquo;s hobby harmless. What survives above '
          'the cap is exactly what the chapter wants to survive: the '
          'tools&rsquo; meaning, which no ledger nets.</p>',
 'inner_head': 'On the Holding<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; the kit, the ladder, and the '
               'letting go</span>',
 'name': 'Focus: Instruments',
 'outer': '<p><span class="lemma">When a tool may be set down.</span> The '
          'abandonment dispute. <span class="voice">Some say</span> '
          'discipline: the timetable is the law&rsquo;s and the '
          'teacher&rsquo;s, the tool is dropped when the rank releases it '
          'and not one working sooner, and the student who improvises her '
          'own graduation has confused impatience with transcendence '
          '&mdash; the kit is a curriculum, and curricula are finished. '
          '<span class="voice">Others say</span> the discipline reading '
          'quietly inverts the folio&rsquo;s own hagahah: if the wand is '
          'for the mage, then the mage is the only honest judge of when '
          'the wand has finished its work, and a teacher who holds a '
          'student to tools her believing has outgrown is teaching the '
          'tools, not the student. The schools trade their best cases '
          '&mdash; the prodigy crippled by premature bareness; the '
          'master kept kneeling to equipment out of institutional habit '
          '&mdash; and the folio notes the law itself takes a side: the '
          'shedding is indexed to rank, which is to say to the '
          'believing&rsquo;s actual depth, and neither to the calendar '
          'nor to the teacher&rsquo;s comfort. What remains disputed is '
          'who reads the index, and that dispute is chapter V&rsquo;s '
          'gate question wearing an apron.</p>\n'
          '        <p><span class="lemma">The mundane-seeming kit.</span> '
          'The camouflage dispute. The Gemara&rsquo;s toolkit would pass '
          'any customs in the world: knife, cards, chalk, keys, spoons, '
          'phone, thread. <span class="voice">Some say</span> this is the '
          'law working exactly as written &mdash; the tool that reads as '
          'ordinary is witness-management perfected, the working&rsquo;s '
          'theater staying inside what the street believes, and the '
          'court of 533a has no complaint against a fire lit with a '
          'lighter by a woman holding a lighter. <span '
          'class="voice">Others say</span> follow the incentive to its '
          'floor: if the ordinary-seeming kit is strictly dominant, the '
          'law is quietly taxing every robe, sigil, and stave in the '
          'setting &mdash; pricing the mystic look itself &mdash; and '
          'the Consensus wins a war this chapter never declared, one '
          'discarded wand at a time. The answer from the first school '
          'is the significant tool: the impressive instrument earns '
          'back in mythic weight what it loses in camouflage, and the '
          'law thus prices a genuine choice of theaters rather than a '
          'surrender. Whether the exchange rate is fair &mdash; whether '
          'a believable marvel can really buy what invisibility buys '
          '&mdash; the folio cannot settle from the bench. <span '
          'class="kw">TEYKU</span> &mdash; the red thread does not '
          'testify.</p>\n'
          '        <p><span class="lemma">The mortal tool.</span> A third '
          'difficulty, on the unique grade&rsquo;s cruelest clause: the '
          'virtue that dies with the object. <span class="voice">Some '
          'say</span> the permanence is the grade&rsquo;s whole meaning '
          '&mdash; a bond that could be re-forged at will would be a '
          'preference, not an intimacy, and the law honors the unique '
          'tool by making its loss real the way the deaths of 406a are '
          'real: no refund, no restoration, grief with a rules-weight. '
          '<span class="voice">Others say</span> the clause punishes '
          'exactly the wrong player &mdash; the one who committed '
          'hardest to the fiction &mdash; and hands every antagonist a '
          'button that breaks a character&rsquo;s build along with her '
          'heart; drama bought at that price is extortion with a '
          'sourcebook. The schools compromise in practice as the '
          'counsel below records: the loss belongs to the chronicle, '
          'not the dice &mdash; drawn seldom, telegraphed always, and '
          'paid for in story on both sides of the screen. What neither '
          'school disputes is the design&rsquo;s honesty: the ladder '
          'prices intimacy, and intimacy has always cost exactly '
          'this.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the setting-down, the ordinary kit, '
               'and the mortal tool</span>',
 'rubric': 'the tools, their grades, and the letting go',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of instruments &middot; the holding as law',
 'title': 'Tractate Aliyah · Folio 586a — Focus: Instruments — the tools, their grades, and the letting go',
 'type': 'daf'}
