# Folio 586b - The Inventory. Verso of Instruments: the catalog toured,
# the gadget and the invention, the weaponized name, and the person as
# tool, per the wod-llm-wiki instruments hub (M20 pp.586-600; BoS
# pp.205-210).
FOLIO = {'bottom': '<p><span class="lemma">On shopping the catalog.</span> Read the full lists '
           'with each player once and then close the book: the catalog&rsquo;s use '
           'is to prove that anything held with belief serves, after which the '
           'player&rsquo;s own seven, drawn from their character&rsquo;s life, will '
           'beat anything picked from a menu. The lists are a permission, not a '
           'store.</p>\n'
           '        <p><span class="lemma">On the invention&rsquo;s player.</span> '
           'The maker&rsquo;s tool that serves allies at a lesser rate and '
           'strangers not at all is a party engine: it makes the weird '
           'scientist&rsquo;s bench a place other characters visit with requests, '
           'and every loaner carries the maker&rsquo;s stake in the scene. Let the '
           'device fail interestingly in stranger hands rather than merely '
           'failing; the clause is about belief, and belief failing is a '
           'story.</p>\n'
           '        <p><span class="lemma">On the darker shelves.</span> The '
           'expanded lists price tools a table may not want priced &mdash; the '
           'broken taboo, the consumed essence, the marked body. They are in the '
           'books deliberately and in chronicles optionally: put them behind '
           '384b&rsquo;s consent tools like every other heavy thing, and if they '
           'enter, let them enter as subject, never as texture.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on menus, benches, and '
                'the heavy shelves</span>',
 'center': '<p class="noindent"><span class="dropcap">N</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The catalog is long because belief is,</span> and '
           'the law tours it by family. The made marks: drawing and carving, '
           'writing and rune, the circle and the figured design. The '
           'body&rsquo;s stock: blood and the living fluids, bone and remainder, '
           'the dance, the ordeal, the fast, the marked skin. The kitchen and '
           'the cellar: brews and simples, herb and stone, the shared meal. The '
           'reader&rsquo;s tools: book and scroll, number and formula, the '
           'sacred tongues, the true and legal name. Chance&rsquo;s tools: card, '
           'die, and cast bone. The social tools: fashion and mask, coin and '
           'contract, the crowd gathered, the underling directed &mdash; for the '
           'law counts the directed servant an instrument, gated behind the '
           'deep purse of backgrounds it presumes. And the machine-shelf: '
           'device and engine, the laboratory itself, the net and its '
           'traffic, the implanted work &mdash; and the darker shelves the '
           'later books added, priced and fenced: the marked body, the '
           'consumed essence, the broken taboo.<sup>a</sup> Two makings are graded '
           'apart: the <span class="term">gadget</span>, built for one working '
           'and spent by it, and the <span class="term">invention</span>, which '
           'carries its maker&rsquo;s enlightenment &mdash; easing her wall two '
           'steps, an ally&rsquo;s one, a stranger&rsquo;s none.<sup>b</sup> The '
           'name is a tool of both edges: the mage hides hers behind a working '
           'name, and the watchers of the Union wield the legal name and the '
           'state&rsquo;s number for it as a unique instrument against its '
           'owner.<sup>c</sup> And the rule above every shelf: any human activity '
           'may serve, if the belief that holds it holds.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> Come '
           'and hear the clerk and the witch, audited. The Union&rsquo;s '
           'requisitions officer files: one standard-issue sidearm, faith in '
           'procedure, a badge that opens doors, a name that closes them, '
           'the department&rsquo;s good suit. The witch inventories: one '
           'knife, faith in the garden, a key that opens houses, a name she '
           'tells nobody, her grandmother&rsquo;s spoons. The Masoret has '
           'seen these two lists before, and so has the reader: they are '
           'the same list, translated &mdash; and neither holder would '
           'survive the comparison politely. The disputants around this '
           'text hold the servant-as-tool and the name-as-weapon.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Instruments: the recto keeps the law of holding, this '
             'side keeps the shelves.',
 'folio': '586B',
 'glossL': '<p><span class="mark">a</span> On the catalog entire &mdash; the '
           'families abridged here to their bands per the luachs&rsquo; '
           'standing rule &mdash; see M20, the Book of Magick, folios '
           '588&ndash;600; the directed servant&rsquo;s background gate is the '
           'optional management reading at folio 592&rsquo;s span.</p>\n'
           '        <p><span class="mark">b</span> On the gadget spent by its '
           'working and the invention carrying its maker&rsquo;s enlightenment '
           '&mdash; the two steps, the one, and the none &mdash; see the same '
           'folios&rsquo; gadget entry.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the working '
           'name kept and the legal name wielded &mdash; the state&rsquo;s '
           'number as a unique instrument &mdash; see the true-names entry of '
           'the same folios.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On any '
           'activity serving where belief holds it, see folio 586; the '
           'expanded shelves &mdash; the marked body, the net, the '
           'surgeon&rsquo;s procedures, the broken taboo &mdash; are the Book '
           'of Secrets&rsquo;, folios 205&ndash;210 of that volume.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The recto grades intimacy; '
           'this side shelves its objects. Read the Gemara&rsquo;s audit '
           'against 533b&rsquo;s census: the badge and the key are both '
           'witness-management, and the two lists price the same war from '
           'opposite trenches.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'invention that serves its maker best is the Etherite&rsquo;s '
           'whole seat at 160a in one clause &mdash; paradigma as personal '
           'property &mdash; and the Union&rsquo;s interchangeable-issue '
           'devices at chapter VI are the same clause refused on '
           'principle.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'weaponized legal name belongs to the watchers of 188, in '
           'chapter VI, and the Masoret routes the reader there; the '
           'name-law&rsquo;s mystic half &mdash; the true name hidden '
           '&mdash; waits on the summonings of the minor tractates.</p>',
 'h1': 'The Inventory',
 'hagahah': 'An instrument is anything that will hold an intention. People '
            'qualify. The folio wishes they did not, and files them '
            'anyway.',
 'inner': '<p><span class="lemma">The catalog is long because belief '
          'is.</span> The tour&rsquo;s plain sense: the families are not a '
          'taxonomy of powers but a census of human seriousness &mdash; '
          'everything people have ever done with full attention appears, '
          'from chalk to fasting to bookkeeping &mdash; and the '
          'length is the argument: the books are demonstrating, shelf by '
          'shelf, that no artifact in the setting is magical and no '
          'artifact is excluded, because the magic was never in the '
          'object. The reader who finds the lists exhausting has '
          'understood them.</p>\n'
          '        <p><span class="lemma">The directed servant.</span> The '
          'management entry&rsquo;s plain sense, kept at arm&rsquo;s '
          'length: the optional reading counts commanded underlings as an '
          'instrument &mdash; the working cast through staff &mdash; and '
          'gates it behind deep holdings in the social backgrounds, three '
          'dots in two of them at the least. The servants cannot exceed '
          'human limits; what the tool provides is reach, not miracle. '
          'The law&rsquo;s deadpan here is its own commentary: social '
          'power is a form of magick, the books say, and the margin '
          'below says what that sentence costs.</p>\n'
          '        <p><span class="lemma">Spent by it.</span> The '
          'gadget-and-invention clause&rsquo;s plain sense: the gadget is '
          'a working frozen into an object and thawed once &mdash; its '
          'whole virtue discharged in the using &mdash; while the '
          'invention is the maker&rsquo;s believing given a chassis, '
          'which is why its gift decays with distance from her: two '
          'steps for the hands that built it, one for the hands she '
          'trusts, none for the stranger, to whom it is a prop. The '
          'decay schedule is the recto&rsquo;s intimacy ladder restated '
          'in engineering.</p>\n'
          '        <p><span class="lemma">The state&rsquo;s number for '
          'it.</span> The name clause&rsquo;s plain sense, both edges '
          'shown: naming is claiming, so the mage works under a name '
          'she can afford to have claimed &mdash; and the Union&rsquo;s '
          'watchers, understanding the same law from the other side, '
          'treat the legal name and its filing number as a unique '
          'instrument against the person they index: one of a kind, '
          'intimately theirs, easing the wall two steps toward its '
          'owner. The clause is the catalog&rsquo;s quietest horror: '
          'the bureaucracy is a grimoire, and everyone in it is '
          'inscribed.</p>\n'
          '        <p><span class="lemma">If the belief that holds it '
          'holds.</span> The governing rule&rsquo;s plain sense: the '
          'catalog&rsquo;s door clause admits any activity &mdash; the '
          'expanded shelves add the marked body, the net&rsquo;s '
          'traffic, the surgeon&rsquo;s procedures, and the broken '
          'taboo &mdash; and the admission fee is always the same '
          'coin: the tool must fit the paradigm and bear the '
          'practice&rsquo;s weight. The cyborg fumbling tarot works '
          'against his own programming, as the books put it; the '
          'shelf is open and the fit is law. The darker entries carry '
          'their own fences in the source &mdash; consequence systems, '
          'story costs, the counsel of restraint printed beside the '
          'price &mdash; and this binding adds the fence the margin '
          'below describes.</p>',
 'inner_head': 'On the Shelves<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; family by family, edge by '
               'edge</span>',
 'name': 'The Inventory',
 'outer': '<p><span class="lemma">The servant as tool.</span> The '
          'folio&rsquo;s heaviest dispute. <span class="voice">Some '
          'say</span> the management entry merely names what every court '
          'and chantry has always done &mdash; power works through '
          'people, the general&rsquo;s army and the abbess&rsquo;s '
          'convent are her instruments in any honest description, and a '
          'law that prices the practice is better than a piety that '
          'hides it. <span class="voice">Others say</span> mark what the '
          'entry does grammatically: it moves persons from the '
          'sentence&rsquo;s subject to its object &mdash; the underling '
          'is filed between the wand and the laboratory &mdash; and a '
          'chapter whose whole teaching is that belief dignifies the '
          'tool should notice what it dignifies here: the belief that '
          'people are equipment. The first school answers that the '
          'gate is honest &mdash; deep backgrounds, human limits, reach '
          'and not miracle. The second answers that the Union of '
          'chapter VI keeps precisely those books, and calls the '
          'filing personnel. A third voice, quieter, notes what the '
          'gate actually gates: the entry is priced in backgrounds '
          '&mdash; allies, retainers, resources, renown &mdash; which '
          'means the law charges for the relationships before it '
          'permits the use, and a mage who has genuinely earned three '
          'dots of loyal staff has already been billed in obligations '
          'the sheet tracks; the tool was never free, only the '
          'cynicism about it. The folio holds the line it can hold: '
          'the entry is optional, the option is a mirror, and a table '
          'should decide while looking into it. <span '
          'class="kw">TEYKU</span> &mdash; the staff, consulted, were '
          'not consulted.</p>\n'
          '        <p><span class="lemma">The name as weapon.</span> '
          'The second dispute, twinned with the first. <span '
          'class="voice">Some say</span> the weaponized legal name is '
          'the setting&rsquo;s fair symmetry: the mystic hides her true '
          'name because names bind, the Union indexes names because '
          'names bind, and the law simply refuses to pretend the '
          'oldest rule stopped applying when the ledgers went digital. '
          'The wall between witch and clerk is professional, not '
          'metaphysical &mdash; the Gemara&rsquo;s audit says so. <span '
          'class="voice">Others say</span> the symmetry flatters the '
          'stronger party: the witch must learn her target&rsquo;s '
          'name; the state already holds everyone&rsquo;s, harvested at '
          'birth and cross-filed at every door &mdash; a unique '
          'instrument against each citizen, pre-forged, pre-dedicated, '
          'waiting in a drawer. A law of names that binds by intimacy '
          'has, in the filing cabinet, met an intimacy manufactured at '
          'civilizational scale, and the folio&rsquo;s catalog files it '
          'in one line because more lines would frighten the binding. '
          'The schools agree the entry belongs to 188&rsquo;s watchers '
          'and send the reader there armed; and they agree on the '
          'practical law a table can use tonight: the working name is '
          'not paranoia but hygiene, the character who scrubs her legal '
          'name from the world is playing the rules as written, and the '
          'Storyteller who lets a villain open the drawer should let the '
          'players hear it open. The folio keeps only the '
          'hagahah&rsquo;s sigh, and the witch&rsquo;s untold name.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the staff, and the drawer of '
               'names</span>',
 'rubric': 'the catalog, the made things, and the names',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of the inventory &middot; the shelves as law',
 'title': 'Tractate Aliyah · Folio 586b — The Inventory: the catalog, the made things, and the names',
 'type': 'daf'}
