# Folio 607b - The Casebook. Verso of Rotes: the sample workings as
# precedents, per the wod-llm-wiki rotes-and-procedures page (M20
# pp.601-611).
FOLIO = {'bottom': '<p><span class="lemma">On using the casebook.</span> The sample workings '
           'are seeds, not statutes: lift their shapes, rename them for the '
           'chronicle&rsquo;s own lineages, and let players counter-draft. A table '
           'that treats the printed dockets as the complete law of magick has '
           'read the chapter backward; the samples exist to prove how wide the '
           'door is, and the best working in any campaign should be one the '
           'books never printed.</p>\n'
           '        <p><span class="lemma">On precedent as escalation.</span> '
           'Because rotes are unpriced, the casebook is also an arms race in '
           'waiting: whatever the players codify, their rivals may learn, steal, '
           'or counter-draft. Let antagonists cite the party&rsquo;s own '
           'precedents back at them &mdash; nothing teaches the weight of '
           'case law like being on the wrong end of your own.</p>\n'
           '        <p><span class="lemma">On the conditioning file.</span> One '
           'family of Procedures in the books&rsquo; chest reprograms persons '
           'outright, and this binding declines to keep it on the open shelf: '
           'it is filed with the watchers of 188, behind 384b&rsquo;s consent '
           'tools, where its chapter can weigh it properly. The refusal is '
           'deliberate and the Masoret records it.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on seeds, escalation, '
                'and the closed drawer</span>',
 'center': '<p class="noindent"><span class="dropcap">N</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The casebook opens on the subtle shelf.</span> '
           'The Union&rsquo;s Adjustments are drafted coincidental: the borrowed '
           'key that persuades a networked lock it was asked politely; the '
           'sidearm tuned so its report negotiates before its round does; the '
           'mark fed a story-shape until he plays the part his own cinema wrote '
           'him.<sup>a</sup> The heavy shelf answers: the scene recycled to '
           'clean energy, an hour and a weight of matter per success; the area '
           'sealed by a field that wants three successes and five for a broad '
           'one; the charge phased past the world&rsquo;s veil to burst in the '
           'countries beyond, priced by the local wall; the two-gun cinema '
           'that passes because the street has seen that film.<sup>b</sup> The '
           'mystic shelf keeps the old cases: the object roused to remember '
           'it is alive; the rumor drafted to compel two retellings per '
           'success until the town does the working; the ruin restored to the '
           'day it was new; claws grown, grafted, and charged past nature; '
           'the bullet met by the Way and handed back; the poppet that '
           'withers what it names.<sup>c</sup> And the casebook closes on a '
           'farce with teeth: the working, famous and inadvisable, that turns '
           'a night-lord into furniture &mdash; guaranteed its fee, opposed by '
           'its victim&rsquo;s own arts, and remembered by the chair.<sup>d</sup></p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD the case of the chair, for the casebook teaches by '
           'farce what it dares not teach by tragedy. A mage of more art than '
           'sense transformed a night-lord entire &mdash; blood, malice, '
           'centuries &mdash; into a lawn chair, and the court assessed the '
           'fee in full, for no street in the world believes in that. The '
           'working held. The grudge held longer. The chair was still a '
           'mind; the mind kept court; and the night-courts hunt the '
           'furniture-maker to this hour, while the case is cited in every '
           'chantry as the perfect precedent: a working may succeed '
           'completely and be, in every sense the law can name, a total '
           'defeat. The disputants around this text hold why the books '
           'print jokes, and what the sanctioned shelf is for.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; '
             'verso of Rotes, and the Book of Magick&rsquo;s last leaf: the '
             'chapter that began at 500a closes on a cautionary chair.',
 'folio': '607B',
 'glossL': '<p><span class="mark">a</span> On the subtle Adjustments &mdash; '
           'the networked key, the tuned weapon, the story-shape fed to a '
           'mark &mdash; see M20, the Book of Magick, folios 602&ndash;604; '
           'every case is abridged here to its band per the luachs&rsquo; '
           'standing rule, and the grain is in the source.</p>\n'
           '        <p><span class="mark">b</span> On the heavy Procedures '
           '&mdash; the recycled scene, the sealed area, the phased charge, '
           'the two-gun cinema &mdash; see folios 604&ndash;605.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On the mystic '
           'cases &mdash; the roused object, the compelled rumor, the '
           'restored ruin, the grown claws, the met bullet, the withering '
           'poppet &mdash; see folios 607&ndash;610, whence this page takes '
           'its number.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the '
           'notorious furniture case &mdash; its guaranteed fee, the '
           'night-arts that oppose it, and the hunt that follows &mdash; '
           'see folios 610&ndash;611; the books&rsquo; own verdict on it is '
           'the epithet stupid, printed.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> Every case on this leaf casts '
           'through 500a and prices through 533a: the subtle shelf is drafted '
           'to the coincidental wall, the heavy shelf pays the vulgar rates, '
           'and the rumor that compels retellings is 533b&rsquo;s census '
           'weaponized &mdash; witnesses conscripted as couriers.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The met '
           'bullet is 423a&rsquo;s Way answering gunfire, and the withering '
           'poppet is 514a&rsquo;s fortune-art at its coldest; the casebook '
           'is chapter XI citing itself, which is what casebooks are '
           'for.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'night-lord who remembers is a sibling tractate&rsquo;s subject '
           '&mdash; the shelf behind this binding keeps his court&rsquo;s '
           'own law &mdash; and the Masoret notes with satisfaction that '
           'the chair, as furniture, would be catalogued by Kelim, '
           'wanting.</p>',
 'h1': 'The Casebook',
 'hagahah': 'The chair is still angry. The books say so, in as many words. It '
            'is the only ruling in the binding that holds a grudge, and the '
            'only one nobody appeals.',
 'inner': '<p><span class="lemma">Drafted coincidental.</span> The subtle '
          'shelf&rsquo;s plain sense: the Adjustment is case law written by '
          'the winning side &mdash; each working pre-fitted to what the '
          'street already believes, the key reading as clever tech, the '
          'tuned weapon as good engineering, the story-shape as a '
          'mark&rsquo;s own bad taste &mdash; so the fees stay at the '
          'coincidental floor by construction. The craft in the drafting '
          'is real and the folio names it: these are workings designed by '
          'a committee that read 533a first, which no witch&rsquo;s bad '
          'hour ever permitted her.</p>\n'
          '        <p><span class="lemma">An hour and a weight of matter '
          'per success.</span> The heavy shelf&rsquo;s plain sense: the '
          'Procedures scale like the industry they are &mdash; the '
          'recycled scene is an extended working metered in hours and '
          'pounds; the sealed area is bought in successes, three for a '
          'room and five for a campus; the phased charge prices by the '
          'local veil&rsquo;s wall, and its botch holds the blast between '
          'worlds, wounding both. Vulgarity is not an accident on this '
          'shelf but a budget line: the heavy cases assume the '
          'bystanders are cleared first, which tells the reader exactly '
          'who drafted them.</p>\n'
          '        <p><span class="lemma">The old cases.</span> The '
          'mystic shelf&rsquo;s plain sense, case by case: the roused '
          'object gains a spirit&rsquo;s standing and an echo in the '
          'countries beyond; the rumor compels two retellings per '
          'success and then rides ordinary gossip, needing no art past '
          'the first push; the restoration looks backward through time '
          'and pays essence to rebuild; the claws upgrade the '
          'body&rsquo;s own case law; the met bullet is a dodge rolled '
          'through discipline and belief; and the poppet works at a '
          'distance only for the caster who holds a thread to the '
          'named. Each is older than its writing, which is the '
          'shelf&rsquo;s point: the mystic register cites custom, not '
          'sanction, and custom&rsquo;s citations run deeper than any '
          'issue number.</p>\n'
          '        <p><span class="lemma">Remembered by the chair.</span> '
          'The farce&rsquo;s plain sense, and the law inside the joke: '
          'the furniture case is printed with its fee guaranteed, its '
          'resistance rules intact &mdash; the night-lord&rsquo;s own '
          'counter-arts, the required depth of success, the '
          'transformation&rsquo;s dependence on the fifth ranks of two '
          'arts &mdash; and its aftermath specified: the victim persists, '
          'the grudge persists, and the hunt is canonical. The '
          'books&rsquo; printed verdict on the working is the epithet '
          'stupid, and the folio reads the epithet as doctrine: the '
          'casebook includes one complete anatomy of a working that '
          'succeeds at everything except being worth doing.</p>\n'
          '        <p><span class="lemma">Teaches by farce.</span> The '
          'Gemara&rsquo;s method, made explicit: the casebook&rsquo;s '
          'darkest lessons wear comedy because comedy is the only '
          'register in which a table will study total defeat '
          'voluntarily. The chair is the chapter&rsquo;s memento mori '
          'with the sheet pulled off, and the laughter it earns is the '
          'sound of the lesson landing where a lecture would have '
          'bounced.</p>',
 'inner_head': 'On the Cases<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; shelf by shelf, and the '
               'chair</span>',
 'name': 'The Casebook',
 'outer': '<p><span class="lemma">Why the books print jokes.</span> <span '
          'class="voice">Some say</span> the farce is filler: the casebook '
          'is a chest of tools, the chair is a gag that costs a page, and '
          'a chapter with finite pages owes its readers usable precedents '
          'rather than punchlines. <span class="voice">Others say</span> '
          'the farce is the chapter&rsquo;s conscience: every other case '
          'teaches what magick can do, and exactly one case teaches what '
          'it cannot make worth doing &mdash; the omnipotence fantasy '
          'anatomized, priced, and left grinning on the lawn. A casebook '
          'of pure successes would train players to believe the '
          'engine&rsquo;s only limit is arithmetic; the chair teaches '
          'that the deepest limits are consequences, and does it in the '
          'one voice nobody argues with. The first school presses: then '
          'why only one? A casebook honest about failure would keep a '
          'shelf of ruins, not a single celebrated farce. The second '
          'answers that one is the correct dose &mdash; the chair works '
          'because it is singular, quotable, and universally cited, a '
          'proverb with a stat block, where a shelf of failures would '
          'read as the drafters despising their own engine. The folio '
          'sides, for once, '
          'openly: the joke is load-bearing, the dose is right, and the '
          'binding&rsquo;s own '
          'hagahah tradition is its imitation.</p>\n'
          '        <p><span class="lemma">What the sanctioned shelf is '
          'for.</span> The last dispute of the Book of Magick. <span '
          'class="voice">Some say</span> the Adjustment shelf is simply '
          'competence: any durable fellowship drafts its case law '
          'carefully, the Union&rsquo;s carefulness extends to the '
          'court&rsquo;s fees, and the Traditions are free &mdash; '
          'encouraged, even, by their own redactors &mdash; to draft as '
          'well and pay as little; half the mystic shelf above is '
          'exactly such drafting, older than the Union and just as '
          'shrewd. The shelf is a standard to envy, '
          'not an indictment. <span class="voice">Others say</span> '
          'read the two shelves as one document: the subtle shelf '
          'never pays the court because it is drafted inside the '
          'street&rsquo;s belief, and the heavy shelf pays without '
          'flinching because its drafters clear the street first '
          '&mdash; between them, the sanctioned register has abolished '
          'the wager every mystic case still runs, which is the wager '
          'of believing something the world does not. Case law '
          'without that wager is administration; and whether '
          'administration is magick&rsquo;s maturity or its death is '
          'the question this whole chapter has been carrying since '
          'its first folio priced the coincidental discount. The '
          'first school&rsquo;s last word: the Traditions&rsquo; own '
          'masters draft toward coincidence every time they can, and '
          'nobody calls their craft dead &mdash; prudence is not '
          'apostasy. The second&rsquo;s: prudence chosen working by '
          'working is craft; prudence installed as the register '
          'itself is surrender with a style guide, and the difference '
          'is the whole Ascension War in miniature. Handed '
          'now to chapter VI unopened. <span class="kw">TEYKU</span> '
          '&mdash; the Book of Magick ends, as it began, at the '
          'wall.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'two difficulties: the punchline, and the sanctioned '
               'shelf</span>',
 'rubric': 'precedents, subtle and heavy, and one chair',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, concluded &middot; of the casebook &middot; the precedents as law',
 'title': 'Tractate Aliyah · Folio 607b — The Casebook: precedents, subtle and heavy, and one chair',
 'type': 'daf'}
