# Folio 607a - Rotes and Procedures. Chapter XI's closing law, per the
# wod-llm-wiki rotes-and-procedures and casting-magick pages (M20
# pp.528-529, 601-611).
FOLIO = {'bottom': '<p><span class="lemma">On the starting spellbook.</span> Let every new '
           'character bring a handful of rotes with names and histories: not '
           'entries from a list but inheritances &mdash; the working her teacher '
           'called by a private joke, the one she half-invented and still '
           'distrusts. A named rote is free characterization and a hook the '
           'Storyteller can pull for a whole season: someone else knows that '
           'working, and remembers who taught it.</p>\n'
           '        <p><span class="lemma">On rote drift.</span> When a rote '
           'passes between characters in play, let it change hands imperfectly: '
           'the copy carries the copyist, per 567b&rsquo;s law of echoes, and the '
           'version the apprentice casts should differ from the master&rsquo;s in '
           'one visible habit. Drift costs nothing mechanically and makes the '
           'chronicle&rsquo;s magic feel inhabited &mdash; a literature, not a '
           'menu.</p>\n'
           '        <p><span class="lemma">On the joke with teeth.</span> The '
           'books print at least one working that is a guaranteed catastrophe '
           'played straight, and the counsel is to honor the genre: when a '
           'player attempts the famously stupid working, do not soften the '
           'court&rsquo;s arithmetic and do not skip the consequences&rsquo; '
           'comedy. The setting keeps its cautionary tales funny because '
           'funerals teach worse than farces.</p>',
 'bottom_head': 'The Later Authorities<span class="comm-sub">on spellbooks, drift, '
                'and farce</span>',
 'center': '<p class="noindent"><span class="dropcap">E</span><span class="kw">MISHNAH.</span> '
           '<span class="incipit">The rote is case law:</span> a working solved '
           'once, kept, and taught &mdash; an Effect with a history. The known '
           'working costs nothing to hold and nothing to keep holding: no point '
           'buys it, no ledger caps it, and it is cast through the engine of 500a '
           'at the engine&rsquo;s own walls, only without the improviser&rsquo;s '
           'fumbling.<sup>a</sup> It is learned as scholarship: intellect with '
           'the esoteric lore for the mystic, with the sciences for the '
           'machine-roads, against a wall of the working&rsquo;s highest art and '
           'five; and the rote taken from a foreign way of believing, unshared, '
           'pays two more upon the wall until it is made one&rsquo;s '
           'own.<sup>b</sup> The caster must hold every art the working names at '
           'its named rank; the book confers no rank, only precedent.<sup>c</sup> '
           'And the registers are three, by flavor and not by law: the '
           '<span class="term">rote</span> or spell, the mystic&rsquo;s working '
           'with a lineage; the <span class="term">Adjustment</span>, the '
           'Union&rsquo;s subtle working, sanctioned and built to pass unseen; '
           'and the <span class="term">Procedure</span>, the Union&rsquo;s heavy '
           'working, sanctioned and often vulgar &mdash; for the Technocracy '
           'files its magick as it files everything, and the filing is the '
           'flavor.<sup>d</sup> One law binds all three registers: the book '
           'confers precedent and never power, and the docket is only as '
           'deep as the hand that holds it.</p>\n'
           '        <p class="gemara-break"><span class="kw">GEMARA.</span> OUR '
           'TEACHERS TOLD the life of one rote. It was invented at need, in a '
           'bad hour, by a mage who never meant to cast it twice. It worked, '
           'so she wrote it down; the writing was the second casting, longer '
           'than the first. Her student copied it and the copy disagreed with '
           'the original in one gesture, which the student swore was a '
           'correction. Two chantries later the rote had a name she would not '
           'have chosen, a reputation she would not have wanted, and a '
           'variant tradition of its own; a redactor bound it beside its '
           'rivals and footnoted the quarrel. She is gone; the working is '
           'arguing still. The disputants around this text hold whether the '
           'writing-down was the working&rsquo;s salvation or its first '
           'death.</p>',
 'chapter': 'Chapter the Eleventh &middot; continued',
 'colophon': 'An out-of-character disputation for Mage: the Ascension &middot; fan '
             'work in the form of a daf; no rules text is reproduced &middot; set '
             'in Abbess &amp; Goudy Old Style after the M20 interior &middot; the '
             'chapter&rsquo;s closing law; the casebook of precedents waits '
             'overleaf, and the Book of Magick ends with it.',
 'folio': '607A',
 'glossL': '<p><span class="mark">a</span> On the rote as an Effect used or '
           'learned before &mdash; unpriced, unlimited, cast through the '
           'standard engine &mdash; see M20, the Book of Magick, folios '
           '528&ndash;529; the case-law framing is this binding&rsquo;s.</p>\n'
           '        <p><span class="mark">b</span> On learning &mdash; '
           'intellect with Esoterica or Science against the highest art and '
           'five, and the unshared focus&rsquo;s two-step surcharge &mdash; '
           'see the same folios.</p>\n'
           '        <p class="drop"><span class="mark">c</span> On holding '
           'every named art at its named rank, see folio 602.</p>\n'
           '        <p class="drop"><span class="mark">d</span> On the three '
           'registers &mdash; Effect the game&rsquo;s term, rote and spell '
           'the mystic&rsquo;s, Adjustment and Procedure the Union&rsquo;s '
           'sanctioned pair &mdash; see folios 601&ndash;602.</p>',
 'glossR': '<p><span class="mark">&#8224;</span> The engine that casts every '
           'rote is 500a&rsquo;s, and the rote clauses there &mdash; one per '
           'turn, the familiar working&rsquo;s exemption from the '
           'stranger&rsquo;s fumbling &mdash; are this folio&rsquo;s law '
           'stated from the engine&rsquo;s side.</p>\n'
           '        <p class="drop"><span class="mark">&#8225;</span> The '
           'redactor of 2b compiled this binding&rsquo;s own ur-grimoire: '
           'the tractate is a rote-book of arguments, solved once and '
           'taught, and the Gemara&rsquo;s drifting working describes its '
           'own transmission. The Masoret files the mirror with its '
           'compliments.</p>\n'
           '        <p class="drop"><span class="mark">&sect;</span> The '
           'cross-focus surcharge is 572b&rsquo;s law applied to a single '
           'working; and the Union&rsquo;s conditioning of minds, the '
           'darkest Procedure in the books&rsquo; sample chest, is filed '
           'with the watchers at 188, where it belongs.</p>',
 'h1': 'Rotes and Procedures',
 'hagahah': 'A rote is a rebuttal that worked twice. A grimoire is a docket of '
            'them. A tradition is a docket old enough to be argued with, '
            'which is to say: a tractate.',
 'inner': '<p><span class="lemma">A working solved once, kept, and '
          'taught.</span> The definition&rsquo;s plain sense: every mage is '
          'her own spellbook, as the books say, and the rote is memory '
          'given standing &mdash; the difference between improvising a '
          'working and citing one. Nothing mechanical separates the '
          'rote&rsquo;s casting from the fresh working&rsquo;s save the '
          'familiarity itself: the walls are the engine&rsquo;s, the '
          'successes the chart&rsquo;s, and the advantage is the '
          'advantage of precedent everywhere &mdash; the argument '
          'already won once, needing only to be won again, before the '
          'same court, on the same books.</p>\n'
          '        <p><span class="lemma">Costs nothing to hold.</span> '
          'The unpriced clause&rsquo;s plain sense, against the '
          'instinct of players trained on other engines: rotes are not '
          'a resource. No pool caps the repertoire, no slot empties '
          'with the casting, and the mage who knows a thousand workings '
          'holds a library, not an arsenal. What is priced is '
          'acquisition &mdash; the learning roll, the surcharge, the '
          'season &mdash; because in this engine knowledge is the '
          'expensive act and use is free, which is the reverse of '
          'most magic and the same as scholarship.</p>\n'
          '        <p><span class="lemma">Against the highest art and '
          'five.</span> The learning wall&rsquo;s plain sense: the '
          'first-rank working is studied at six and the fifth-rank at '
          'ten, so the library&rsquo;s depth tracks the '
          'scholar&rsquo;s, and the intellect-with-lore pairing keeps '
          'the gate on the sheet&rsquo;s mundane side &mdash; the same '
          'insistence, fourth time in this chapter, that magick is a '
          'literate trade. The unshared rote&rsquo;s surcharge is '
          '572b&rsquo;s translation law in miniature: two steps of '
          'wall until the foreign working believes in you.</p>\n'
          '        <p><span class="lemma">Only precedent.</span> The '
          'rank clause&rsquo;s plain sense, and the folio&rsquo;s '
          'anti-fraud provision: the book teaches the shape of the '
          'working, never the arts that power it, and the apprentice '
          'with a master&rsquo;s grimoire holds a docket she cannot '
          'argue. The clause kills the oldest fantasy in the genre '
          '&mdash; power by mere possession &mdash; and the '
          'setting&rsquo;s grimoire-thefts remain profitable anyway, '
          'for precedent is worth stealing even when rank is not: the '
          'thief with the arts casts tonight what the drafter spent a '
          'career solving, and the thief without them holds collateral '
          'every chantry in the city will bid on. The clause thus '
          'creates the setting&rsquo;s rare-book trade in a sentence, '
          'and the custody dispute below is its natural child.</p>\n'
          '        <p><span class="lemma">The filing is the flavor.</span> '
          'The registers&rsquo; plain sense: rote, Adjustment, and '
          'Procedure name one mechanical thing three social ways. The '
          'mystic&rsquo;s rote carries lineage &mdash; whose it was, who '
          'changed it; the Union&rsquo;s pair carries sanction &mdash; '
          'approved, versioned, issued; and the difference between a '
          'spell with a genealogy and a Procedure with a document '
          'number is the difference between common law and code law, '
          'which chapter VI spends six folios pricing. Subtle '
          'Adjustments run coincidental by design; Procedures are the '
          'big guns and pay the big guns&rsquo; fees.</p>',
 'inner_head': 'On the Docket<span class="comm-sub">the inner commentary &middot; '
               'the plain sense &middot; precedent, price, and '
               'register</span>',
 'name': 'Rotes and Procedures',
 'outer': '<p><span class="lemma">Salvation or first death.</span> The '
          'codification dispute, which is the tractate arguing about '
          'itself. <span class="voice">Some say</span> the writing-down '
          'saves: the rote is how insight survives its inventor, the '
          'grimoire is the only afterlife the setting guarantees, and an '
          'art of pure improvisation would burn its whole inheritance '
          'every generation &mdash; the Gemara&rsquo;s mage lives '
          'precisely because her working is still arguing. <span '
          'class="voice">Others say</span> the writing-down is where the '
          'living working begins to die: the rote calcifies the '
          'solution of one bad hour into every student&rsquo;s first '
          'resort, the docket grows until precedent crowds invention, '
          'and the mystery religions of the setting keep their deepest '
          'workings unwritten for exactly this reason. The folio '
          'observes that both schools are describing the same book '
          '&mdash; one reading the ink, one reading the margins &mdash; '
          'and that the binding in the reader&rsquo;s hands has wagered '
          'its whole existence on the first school while formatting '
          'itself as a standing apology to the second. <span '
          'class="kw">TEYKU</span> &mdash; the rote&rsquo;s inventor, '
          'asked, is gone; her variant tradition answers for her, in '
          'variants.</p>\n'
          '        <p><span class="lemma">The register&rsquo;s '
          'politics.</span> A second dispute, on the three names. <span '
          'class="voice">Some say</span> the registers are honest '
          'sociology: the same working really is a different object in '
          'different hands &mdash; the spell inherited at a '
          'deathbed and the Procedure issued at a briefing differ in '
          'everything that matters to the people holding them, and a '
          'law that collapsed the registers would be flattening real '
          'life. <span class="voice">Others say</span> watch what the '
          'sanctioned register smuggles: the Adjustment is built '
          'coincidental &mdash; the Union writes its case law '
          'pre-fitted to the street&rsquo;s belief, which is to say it '
          'legislates from the winning side of 533a&rsquo;s wall &mdash; '
          'and the vocabulary of sanction, versions, and issue numbers '
          'is how a faction persuades its own operatives that the '
          'fees they pay are administration rather than magick. The '
          'first school calls that just the Union being the Union; the '
          'second notes that this is the folio&rsquo;s point, said '
          'politely. Chapter VI is hereby served.</p>\n'
          '        <p><span class="lemma">Grimoire custody.</span> The '
          'third dispute, and the oldest in any library. Who may hold '
          'the book? <span class="voice">Some say</span> the chantry: '
          'the docket is a commons &mdash; drafted by the dead, owed to '
          'the unborn &mdash; and the mage who locks a working in a '
          'private drawer has stolen from everyone who might have '
          'needed it in a bad hour; the redactor of 2b is the '
          'school&rsquo;s patron saint. <span class="voice">Others '
          'say</span> the drawer: every working in the docket is also '
          'a weapon with the drafter&rsquo;s handwriting on it, the '
          'commons that holds the cure holds the curse and the '
          'thief&rsquo;s map to both, and the mystery lineages that '
          'teach mouth-to-ear have never once suffered a grimoire '
          'theft. The schools split every real chantry down the '
          'middle &mdash; the library with the locked case in it is '
          'the setting&rsquo;s standard compromise &mdash; and the '
          'folio notes only that both schools shelve their argument '
          'in writing, which the second school has never adequately '
          'explained.</p>',
 'outer_head': 'The Disputants<span class="comm-sub">the outer commentary &middot; '
               'three difficulties: the ink, the issue number, and the '
               'locked case</span>',
 'rubric': 'case law: the working solved once',
 'subtitle': 'Tractate Aliyah (&ldquo;Ascension&rdquo;) of Seder Chashak (חשך, &ldquo;to be dark, '
             'hidden, obscured&rdquo;) &middot; Chapter the Eleventh: The Book of '
             'Magick, continued &middot; of rotes &middot; precedent as law',
 'title': 'Tractate Aliyah · Folio 607a — Rotes and Procedures: case law, the working solved once',
 'type': 'daf'}
